### ISSUE TITLE
tst_varsperf uses asserts to check results, but we can't use asserts that way in tests

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1018]
In tst_varsperf.c asserts are used to check test results.

It's tempting, but can't be done. The reason is that we still want tests to run and work without asserts. So most HPC builds will (or should) use the NDEBUG flag, and breaks this test.

I have a new version of the test that uses the err_macros.h macros instead of asserts.

**Comment by DennisHeimbigner** [comment]
Its a bad habit that occurs because I build a quick and dirty test for some problem
and then forget to clean it up when I add it as true test case. I will try to avoid doing it.

**Comment by edhartnett** [comment]
It's cool, easy to fix. I've got a new version up in a PR now.
