### ISSUE TITLE
Duplicated code for the vars/vara functions in nc4hdf5.c

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1020]
There is lot of duplication between the nc4_put/get_vars() and the nc4_put/get_vara() functions. The vars functions can do all the work, and the vara functions can be removed. A vara call is just a vars call with NULL stride, which defaults to strides of 1.

This is important not just to reduce code duplication, but because this code is slated for a lot of work:
* (re-)removal of HDF5_CONVERT stuff.
* changes to many structs in accord with #856.

So there are plenty of changes to this code coming shortly.

Since these are large and tricky functions, best not to make complex changes on duplicated parts of the code. That will just invite mistakes. So I will reduce the code a bit before proceeding with #856.

If there is interest in testing new vs. old vars performance, that may still be easily achieved by calling NC4_get_vars vs. NCDEFAULT_get_vars. This tests using the native HDF5 stride, vs. calling a bunch of vara() to simulate the stride (as used to be done). See tst_varsperf for an example.

**Comment by DennisHeimbigner** [comment]
Good point since the vars code came from the vara code.

**Comment by edhartnett** [comment]
Well I'm just glad I don't have to mess with the varm code! ;-)
