### ISSUE TITLE
ncgen w/ classic and NOFILL have different lengths on Windows, Linux/OSX

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#103]
While modifying the shell-script based tests to work on any Windows install which has `bash` available, I've discovered some strange behavior.  In `ncdump/tst_lengths.sh`, we find the following stanza:

~~~.sh
echo "*** testing length of classic file written with NOFILL"
../ncgen/ncgen -b -x ${srcdir}/small.cdl
if test `wc -c < small.nc` != 68; then
    exit 1
fi
~~~

On Linux/OSX, `wc-c < small.nc` gives `68` as expected.  On Windows 8.1 using MSVC 2010-generated executables (64-bit, 'Release' configuration), `wc-c < small.nc` gives `65`, resulting in a failed test.  Examining the contents of `small.nc` in a hex editor on each platform shows that the three trailing zero bytes on Windows are not written to file (see attached images; too hard to cut-and-paste into markdown).  

I need to figure out why this happened, is it a property of File I/O on Windows/NTFS, is it something in ncgen, etc.

### OSX
![osx](https://cloud.githubusercontent.com/assets/4324946/5927371/4ac4e554-a62f-11e4-94ca-48f376a873ed.png)

### Windows
![windows](https://cloud.githubusercontent.com/assets/4324946/5927373/4dc88148-a62f-11e4-9c50-f067f5611d84.png)

**Comment by DennisHeimbigner** [comment]
weird.

Ward Fisher wrote:

**Comment by WardF** [comment]
Further experimentation with Windows 7 (64-bit), Visual Studio 2010.

* Debug build works, or at least generates a binary .nc file of expected size.
* Release build **does not work**. So, new hypothesis is that some sort of optimization is causing the problem. Will investigate this further.

**Comment by WardF** [comment]
After speaking with @russrew, there is a question about the utility of this test and whether or not it is portable enough to keep.  We would need to maintain the test in place, simply because other tests rely on the file generated, but it's possible that checking the number of bytes in the file isn't a great way to test the functionality, particularly since using `ncdump` on the binary files returns the same information, regardless of whether the binary file was `65` or `68` bytes.

**Comment by DennisHeimbigner** [comment]
I agree. One possibility is to use diff -wBb
to compare the two files for equality.
=Dennis

Ward Fisher wrote:

**Comment by WardF** [comment]
Test is too strict, curve too steep, lets just drop it.
