### ISSUE TITLE
User-Defined Format Issues...

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#1031]
I think that before we publicize the user-defined formats capability --
pr https://github.com/Unidata/netcdf-c/pull/977  --
we need to discuss some issues.

1. Once we formalize this capability, it will become difficult to modify the
    dispatch table structure. We need to consider adding some form of versioning
    to that table.
2. On my todo list has been a cleanup of the dispatch table to merge related
    entries (somewhat like the inq_var_all). to reduce the table size.
3. For user-defined formats, it may be desirable to consider some alternate
    form of dispatch table that will make it easier to modify the table without
    causing existing user format code to fail (related to making use of versioning info).

**Comment by edhartnett** [comment]
I agree, and also will add that we need to clean up the interfaces of libsrc4 a bit as well.
