### ISSUE TITLE
ncgen.exe on Windows fails with trailing '-o' argument.

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#104]
While debugging issue #103, I've discovered that the following command fails on Windows:

~~~.bash
$ ncgen -b small.cdl -o output.nc
g:\netcdf-c\build\ncgen\ncgen.exe: only one input file argument permitted
~~~

Whereas the following command works properly:

~~~.bash
$ ncgen -o output.nc -b small.cdl
~~~

> This may be related to the `XGetOpt` code (which replaces the absent `getopt` in Visual Studio)

**Comment by DennisHeimbigner** [comment]
That sounds right, the option processor
is assuming that all flags precede all non-flag
arguments, so it treats -o output.nc as two non-flag
arguments.
Not clear if it is worth fixing.
=Dennis


Ward Fisher wrote:

**Comment by WardF** [comment]
Since the behavior on Linux is different, I'd be inclined to bring them in to sync. Since the Linux version is more flexible I'll argue that that's the behavior we should standardize with, although I'll agree it's not a high priority.

**Comment by DennisHeimbigner** [comment]
I would suggest a Jira issue for it so we don't forget.
=Dennis

Ward Fisher wrote:
> Since the behavior on Linux is different, I'd be inclined to bring them in to sync. Since the Linux version is more flexible I'll argue that that's the behavior we should standardize with, although I'll agree it's not a high priority. 
> 
> Sent from my iPhone
>

**Comment by DennisHeimbigner** [comment]
Maybe we should consider alternatives to Xgetopt.
Here are two I found:
1. https://svn.apache.org/repos/asf/qpid/proton/trunk/examples/include/pncompat/internal/getopt.c
2. http://research.microsoft.com/en-us/um/redmond/projects/invisible/src/games/ping/getopt.c.htm

**Comment by WardF** [comment]
Sounds good to me. The Apache version seems preferable at a glance; the MS version has a license that seems to imply any time we talk about NetCDF we need to mention that it uses software from UC Berk (clause 3).  I'll see about merging in the former once I get the cdf5 stuff wrapped up.
