### ISSUE TITLE
Writing NC_COMPOUND type attribute with NC_STRING fields may loose data

### ISSUE THREAD

**Issue by jarlela** [Unidata/netcdf-c#107]
Using a compound type corresponding to a struct sush as:
struct S{
  char\* c1;
  char\* c2;
};

The strings pointed to by S.c1 and S.c2 may not be written to the file by a call to 'nc_put_att(int, int, const char_, nc_type, size_t, const void_)'. The reason for this is that the struct is copied by a call to 'memcpy' (file:libsrc4/nc4attr.c, line:482) and 'nc_put_att' returns without explicitly writing to file, the strings may be changed or have run out of scope before any attempt to write them to file.

The call to memcpy should be replaced with a deep copy routine for NC_COMPOUND.

**Comment by edwardhartnett** [comment]
I believe this has been done and this issue can be closed.
