### ISSUE TITLE
Need to properly handle hdf5_set_log_level()

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1086]
This is a consequence of splitting HDF5 from libsrc4.

Mostly logging is about libsrc4 code. That is, there is no HDF5 code involved in logging. Except for one important call: the call to turn on the HDF5 error stack, H5Eset_auto().

We don't want this HDF5 call involved in logging, because then other dispatch libraries will not be able to use logging.

To fix this, I introduced hdf5_set_log_level() in libhdf5. This is the same as nc_set_log_level() but also turns on HDF5 logging.

This is a bit of an annoying solution. I am open to suggestions as to any other way to support the HDF5 error stack without introducing a new function.

**Comment by WardF** [comment]
Off the top of my head and between meetings, since the downstream users will be linking against libhdf5, they could turn on hdf5 logging directly using the appropriate hdf5 API; is it necessary to provide a pass-through API call exposed to the developer?

**Comment by DennisHeimbigner** [comment]
IMO, users should not have to call any HDF5 functions directly if they
are using the netcdf-c API.

**Comment by edhartnett** [comment]
Ward I think that is an excellent idea, at least for the short term.

Dennis the problem is that we used to turn on HDF5 error handling in nc_set_log_level(). But the way we are structuring the library, dispatch layers will call libsrc4 code, but libsrc4 code will not call dispatch layer code. So there is no way to call the hdf5 code.

**Comment by DennisHeimbigner** [comment]
I see the point. We need to think beyond the hdf5 case. It is possible/probable
that various formats will want to provide format specific error/debug/tracing output.
So we need to think of a way to provide format-specific functions that can be
invoked at an appropriate point to enable the format-specific error/debug/trace
code. We could as some extra dispatch table entries, but we would need to
decide when things are invoked.

**Comment by edhartnett** [comment]
Alternatively we could allow the user to register a callback function for logging. Is this what you meant by new entries in the dispatch table?

But this is adding a lot of complexity for mere debug logging. I would prefer not to get too complex just to support a develop feature almost no users are using. 

Right now, you can only using logging if you define LOGGING in your own code builds, and most users don't know that. So other than a handful of advanced developers, we are the only ones who use this. I am perfectly content to call the HDF5 function directly from test code, as needed. 

I don't like my current solution, a hdf5_set_log_level() function, because I have to deal with it's absence, just like the nc_set_log_level() used to be (but isn't any more). So that seems uncool. And it certainly should not be in netcdf.h, so where do I put the prototype?

I would like to come up with something simpler.

**Comment by DennisHeimbigner** [comment]
As a short-term hack, I would propose this:
The HDf5 dispatch table open/create code would look at the current
log level and if >= 0 then it would turn on hdf5 logging. This would
effectively  mimic current behavior.

**Comment by edhartnett** [comment]
@DennisHeimbigner best idea yet. I am perusing this one. It's not exactly perfect, because HDF5 logging will not be turned on even if you set nc_set_log_level() if you do it after the open or create, but that's acceptable. And this means the whole problem can be neatly hidden inside the libhdf5 directory.

I will do this on my lazy var work branch and bring it into master when the queue clears out a bit.

**Comment by edhartnett** [comment]
OK, this has been fixed on my lazy var branch. Once some of the backlog of PRs get merged I'll put this up.
