### ISSUE TITLE
Loading time of compressed data NetCDF4 data vs un-compressed NetCDF classic

### ISSUE THREAD

**Issue by ArchangeGabriel** [Unidata/netcdf-c#1088]
Hi there,

I’ve tried to write to support-netcdf@unidata.ucar.edu [following the FAQ](https://www.unidata.ucar.edu/software/netcdf/docs/faq.html#Is-there-a-mailing-list-for-netCDF-discussions-and-questions), but my email was automatically rejected by the server, so I’m posting here instead, sorry if that is inappropriate.

I’m a quite new (in terms of knowledge) user of NetCDF, and I’m having the following situation :

I ran a number of quite large numerical simulations, resulting in terabytes of data. This has implications on the storage and the analysis of those simulations outputs. However, I know my data is highly compressible, because outputs are mainly formed by 11 arrays, of which 7 are filled with zeroes¹ and the other ones have important range of data with identical values. So when I learned NetCDF-4 offered the possibility to compress data, I became very interested in learning more about this.

The code used in those simulations was using PnetCDF to write the data, `ncdump -k` tells me that they are in the `64-bit offset` format. So I’ve converted them to NetCDF-4 format and compressed them on the way, since I also read that it should be transparent for my analysis software (which was written in python some years ago by someone else but uses the netCDF4 python library).

Compression works amazingly well as expected (I’m having compressed files of as low as 1/12 of the original file size), however analysis does not afterwards. While I would have expected a faster loading time (since there is much less data to read from the disk, and compression/decompression being generally preferred for performances because of that), I’m having horrible loading times instead. For
instance, on my test file, I’ve tried loading using two different machines :

– one where storage speed is clearly the bottleneck, but which is dedicated to my exclusive use. Loading time went from around 33s to load (which is already an important penalty to me) to above 500s !

– one where storage is quite fast, but that I have to share with dozen of other users. Here, loading time went from around 6s to load (something I would love to see on the other machine) to almost 300s.

Since I have thousands of files to analyse, such loading times are not sustainable.

I’m wondering whether this is an issue with my analysis tool, or if this is something to expect generally when using compression with NetCDF. I hope the former, because currently it means I have the choice between being able to store my data efficiently and analyse them in a reasonable time.

That being said, I’m quite sure it’s a bug somewhere (in the python analysis tool I guess?): while the decompressed file is around 1GB, and it’s compressed sibling 80MB, `htop` indicates that the python program did dozen of GB reads.

What are you thoughts on this? Should I try looking into the python code loading my data?

Thanks in advance!

¹: I know, it would be better to not write them in the first place, but this possibility was apparently not considered when the code was developed, and now it would require quite some work for which no one has available time right now.

**Comment by edhartnett** [comment]
Howdy! My first though is chunksizes. Do an ncdump -h -s on one of your slow opening compressed netcdf-4 files, and post the results here.

**Comment by ArchangeGabriel** [comment]
Here you go:
```
netcdf data.000000 {
dimensions:
	nb_int = 6 ;
	nb_real = 13 ;
	nx = 109 ;
	ny = 245 ;
	nz = 364 ;
variables:
	int meta_int(nb_int) ;
		meta_int:_Storage = "chunked" ;
		meta_int:_ChunkSizes = 6 ;
		meta_int:_DeflateLevel = 9 ;
		meta_int:_Shuffle = "true" ;
		meta_int:_Endianness = "little" ;
		meta_int:_NoFill = "true" ;
	double meta_real(nb_real) ;
		meta_real:_Storage = "chunked" ;
		meta_real:_ChunkSizes = 13 ;
		meta_real:_DeflateLevel = 9 ;
		meta_real:_Shuffle = "true" ;
		meta_real:_Endianness = "little" ;
		meta_real:_NoFill = "true" ;
	double rho(nz, ny, nx) ;
		rho:_Storage = "chunked" ;
		rho:_ChunkSizes = 122, 82, 37 ;
		rho:_DeflateLevel = 9 ;
		rho:_Shuffle = "true" ;
		rho:_Endianness = "little" ;
		rho:_NoFill = "true" ;
	double E(nz, ny, nx) ;
		E:_Storage = "chunked" ;
		E:_ChunkSizes = 122, 82, 37 ;
		E:_DeflateLevel = 9 ;
		E:_Shuffle = "true" ;
		E:_Endianness = "little" ;
		E:_NoFill = "true" ;
	double vx(nz, ny, nx) ;
		vx:_Storage = "chunked" ;
		vx:_ChunkSizes = 122, 82, 37 ;
		vx:_DeflateLevel = 9 ;
		vx:_Shuffle = "true" ;
		vx:_Endianness = "little" ;
		vx:_NoFill = "true" ;
	double vy(nz, ny, nx) ;
		vy:_Storage = "chunked" ;
		vy:_ChunkSizes = 122, 82, 37 ;
		vy:_DeflateLevel = 9 ;
		vy:_Shuffle = "true" ;
		vy:_Endianness = "little" ;
		vy:_NoFill = "true" ;
	double vz(nz, ny, nx) ;
		vz:_Storage = "chunked" ;
		vz:_ChunkSizes = 122, 82, 37 ;
		vz:_DeflateLevel = 9 ;
		vz:_Shuffle = "true" ;
		vz:_Endianness = "little" ;
		vz:_NoFill = "true" ;
	double Bx(nz, ny, nx) ;
		Bx:_Storage = "chunked" ;
		Bx:_ChunkSizes = 122, 82, 37 ;
		Bx:_DeflateLevel = 9 ;
		Bx:_Shuffle = "true" ;
		Bx:_Endianness = "little" ;
		Bx:_NoFill = "true" ;
	double By(nz, ny, nx) ;
		By:_Storage = "chunked" ;
		By:_ChunkSizes = 122, 82, 37 ;
		By:_DeflateLevel = 9 ;
		By:_Shuffle = "true" ;
		By:_Endianness = "little" ;
		By:_NoFill = "true" ;
	double Bz(nz, ny, nx) ;
		Bz:_Storage = "chunked" ;
		Bz:_ChunkSizes = 122, 82, 37 ;
		Bz:_DeflateLevel = 9 ;
		Bz:_Shuffle = "true" ;
		Bz:_Endianness = "little" ;
		Bz:_NoFill = "true" ;
	double Bxr(nz, ny, nx) ;
		Bxr:_Storage = "chunked" ;
		Bxr:_ChunkSizes = 122, 82, 37 ;
		Bxr:_DeflateLevel = 9 ;
		Bxr:_Shuffle = "true" ;
		Bxr:_Endianness = "little" ;
		Bxr:_NoFill = "true" ;
	double Byr(nz, ny, nx) ;
		Byr:_Storage = "chunked" ;
		Byr:_ChunkSizes = 122, 82, 37 ;
		Byr:_DeflateLevel = 9 ;
		Byr:_Shuffle = "true" ;
		Byr:_Endianness = "little" ;
		Byr:_NoFill = "true" ;
	double Bzr(nz, ny, nx) ;
		Bzr:_Storage = "chunked" ;
		Bzr:_ChunkSizes = 122, 82, 37 ;
		Bzr:_DeflateLevel = 9 ;
		Bzr:_Shuffle = "true" ;
		Bzr:_Endianness = "little" ;
		Bzr:_NoFill = "true" ;

// global attributes:
		:_NCProperties = "version=1|netcdflibversion=4.6.1|hdf5libversion=1.10.2" ;
		:_SuperblockVersion = 0 ;
		:_IsNetcdf4 = 1 ;
		:_Format = "netCDF-4 classic model" ;
}
```

**Comment by ArchangeGabriel** [comment]
Since I posted one hour ago, I started wondering if the data structure could be involved. Basically, those are 2D simulations, this one has a grid size of 2678×3346 but was decomposed in 26×14 domains to run on 364 procs, which matches the `z` direction apparently. After looking a bit at the python code reading them, it seems that it reads the data proc by proc, and I’m wondering if that is efficient.

So I guess that there is room for improvements in both compression and reading.

**Comment by edhartnett** [comment]
Try doing an ncdump of a file into a text output file, and see how long it takes. Much less time than the python program? Then your problem is in the python.

Also how you read the data matter. The data are stored in chunks, and when you ask for any value from a chunk, the entire chunk must be decompressed. So if you go through the file in a way that hits one value from each chunk, over and over, you will get very slow read times. Instead, read in a chunk of data at a time, or change your chunk sizes to better match how you are reading the data.

Please let me know what you find.

**Comment by ArchangeGabriel** [comment]
`ncdump file.nc > file.txt` is taking forever. Currently above 480s, and I guess far from being done (`file.txt` is not even half the size of the compressed `file.nc` yet). It is also currenty at 50GB IO_RBYTES in htop… What do you get from that?

Also, from your answer and my above analysis, it seems that the chunking should indeed be an issue here.

**Comment by edhartnett** [comment]
OK, well now I would suggest you write a program in python to try and read just one chunk of one var and see if that is happening in a reasonable time.

**Comment by ArchangeGabriel** [comment]
Do you want me to keep the `txt` dump running?

Regarding reading in python, I’m not sure what to do. I’ve tried several things, but everything is lightning fast. For instance:
```
import netCDF4 as nc
import numpy as np
import time
data = nc.Dataset('data.000000.nc','r')
rho = np.ndarray(shape=(364,245,109))
start = time.time() ; rho[:,:,:] = data.variables['rho'][:,:,:] ; print(time.time()-start)
```

This give: `0.46244096756`.

**Comment by ArchangeGabriel** [comment]
So even reading the whole thing is fast. I’ve also tried to play around the chunks like this:
```
rho = np.ndarray(shape=(1,82,37))
start = time.time() ; rho[:,:,:] = data.variables['rho'][1,:82,:37] ; print(time.time()-start)
rho = np.ndarray(shape=(82,37,1))
start = time.time() ; rho[:,:,:] = data.variables['rho'][:82,:37,:1] ; print(time.time()-start)
```

Results are `0.000684022903442` and `0.000846147537231`.

**Comment by edhartnett** [comment]
No you can cancel the ncdump.

Seems like you have good read times from the library, so how is your analysis tool doing things differently?

**Comment by ArchangeGabriel** [comment]
Basically doing a loop over the procs, reading corresponding chunks of data and storing them from what I can get of it (as said above, I did not write it, and do not understand all of it).

Actually I was made aware that the code is public, available here: https://sourcesup.renater.fr/plugins/scmgit/cgip-bin/gitweb.cgi?p=dumses.git;a=blob_plain;f=utils/dumpy/data/rd_dumses.py;hb=HEAD.

I can reduce it to NetCDF only parts (it supports reading other formats), the important part are `class DataNetCDFReader(DataParallelReader):` and `class DataParallelReader(DataReader):`.

**Comment by edhartnett** [comment]
Good luck. I think you should close this ticket, since apparently you are not finding a problem with the netcdf library, but with your analysis code.

**Comment by ArchangeGabriel** [comment]
OK, sure. My main point in opening this was to know whether I should expect compression to work the way I thought, and apparently the answer is yes. So I guess I’ll have to dig deeper into that python code.

While I’m here, is there somewhere I can find advice on choosing and setting the chunking size when compressing my data?

**Comment by edhartnett** [comment]
There is a lot you can do, including changing cacheing:

**Comment by ArchangeGabriel** [comment]
@edhartnett Thanks a lot for your help! Using different chunking size better matching how the data are read, I’ve managed even better compression ratio while keeping almost identical reading time (on the fast machine, the slow machine went down because of an ongoing electric maintenance so I couldn’t test). I think I can still win a lot by reading the data differently, I’ll keep looking in this direction a bit.

I guess that given the very peculiar structure of the data, I could likely manage even better than that, but it would likely require much more learning before getting interesting results, so I’ll stop here for now.

Anyway, thanks again for your help, and all this made me realize how much the data structure matters and seems screwed in this code. ;)
