### ISSUE TITLE
releases contain `autom4te.cache`

### ISSUE THREAD

**Issue by nschloe** [Unidata/netcdf-c#109]
The releases contain the directory `autom4te.cache` which shouldn't be there. In Debian, these files had to be removed, cf. [1].

[1] http://lists.alioth.debian.org/pipermail/pkg-grass-devel/2015-March/028330.html

**Comment by WardF** [comment]
Thanks for pointing this out; `autom4te.cache` has been added to the `.gitignore` file in 329a801. This should prevent it from being accidentally included in future releases.

**Comment by nschloe** [comment]
Not sure if it would: `autom4te.cache` has never been part of the sources, but was somehow generated in the process of creating the release tarball.

**Comment by WardF** [comment]
It was included accidentally as part of generating the source tarball; it's generated when I run `autoreconf` to generate `configure` et. al., and was included by accident.  A quick test on my end showed that adding it to the `.gitignore` kept it from being included as part of our process.

If it is somehow generated and rolled in by github (which would surprise me), don't know what we can do about that, but we can cross that bridge when we reach it.
