### ISSUE TITLE
The HTTP.SSL.VALIDATE option at RC auth is not working as expected

### ISSUE THREAD

**Issue by cofinoa** [Unidata/netcdf-c#110]
Dear @DennisHeimbigner, 

If `HTTP.SSL.VALIDATE=1` is set on the `.dodsrc` file some users are reporting this error
```
CURLOPT_SSL_VERIFYHOST no longer supports 1 as value!
```
This is happening with netcdf-c library v4.3.3.1 (macports) and not in my netcdf-c v4.3.2 (pre-built windows binaries). 
If you read the cURL doc:
http://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYHOST.html

it is mentioning the mis-usage of value 1 instead of value 2 for the `CURLOPT_SSL_VERIFYHOST` option. 

Regards

Antonio

**Comment by WardF** [comment]
Thanks for reporting this, Antonio; I'll take a look at the pull request you've submitted and see about getting it merged in!

**Comment by WardF** [comment]
Fixed, thanks!

**Comment by DennisHeimbigner** [comment]
We may need to worry about back compatibility
with older versions of libcurl. May need to check version
in configure.ac. there is already one check there for a flag
name change. Anyone know the version of libcurl in which this
changed?

**Comment by WardF** [comment]
I can research this and add a check.

**Comment by WardF** [comment]
So here's something I see after a quick look, from the curl documentation provided above:

> When the verify value is 1, curl_easy_setopt will return an error and the option value will not be changed. It was previously (in 7.28.0 and earlier) a debug option of some sorts, but it is no longer supported due to frequently leading to programmer mistakes. Future versions will stop returning an error for 1 and just treat 1 and 2 the same.

> When the verify value is 0, the connection succeeds regardless of the names in the certificate. Use that ability with caution!

> The default value for this option is 2.

So it looks like the option with value `1`, in versions `7.28.0` and earlier, was for debugging, and future versions will treat `1` and `2` as equivalent.  So at a glance it seems like we don't need to worry about previous versions of curl; `1` has so far only been used for debugging and `2` was the proper value.

I'll look for more documentation on this to see if there is anything contradicting this.

**Comment by DennisHeimbigner** [comment]
I read that also, and it is, to me, ambiguous
because the term "debug" is unclear in meaning.
Also, did pre 7.28.0 versions accept 2 as a value?
Unclear.
=Dennis


Ward Fisher wrote:

**Comment by WardF** [comment]
I can't find a versioned copy of the curl documentation, but there is a lot of discussion amongst other projects when I google this. The inference I take from scanning these is that a value of 2 was accepted, and was the proper value for  CURL_SSL_VERIFYHOST since it was introduced; I can't nail down when this was, yet. Perhaps this option was there from the start?

The best description of the problem I can find (so far) is this:

> CURLOPT_SSL_VERIFYHOST Should use an integer of 2 instead of true to enforce proper SSL verification. Setting to true acts like 1, which only checks for the existence of a common name, and not that the common name matches the requested hostname.

In the absence of any documentation saying that the default value is 1 until some version of libcurl, I think we're safe not worrying about older versions.

**Comment by cofinoa** [comment]
you can find the history of symbols introduced/deprecated/removed on this URL:
http://curl.haxx.se/libcurl/c/symbols-in-versions.html

**Comment by cofinoa** [comment]
You can find the previous version of the doc here:
https://github.com/bagder/curl/blob/curl-7_28_0/docs/libcurl/curl_easy_setopt.3#L2309-L2339


> When the value is 1, the certificate must contain a Common Name field, but it
> doesn't matter what name it says. (This is not ordinarily a useful setting).

Antonio

**Comment by WardF** [comment]
Add to release notes then close issue.
