### ISSUE TITLE
make check fails on alpine edge

### ISSUE THREAD

**Issue by bickelj** [Unidata/netcdf-c#1106]
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### Environment Information

docker 1.13.0
alpine edge (~2018-08-08)
hdf5 (from alpine repository)
netcdf-c-4.6.1 (from source)

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [X] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [X] 64-bit
* What build system are you using?
  * [X] autotools (`configure`)
  * [ ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [ ] Yes (please attach to this issue, thank you!)
  * [X] No
  * [ ] Not at this time

### Summary of Issue

"make check" reports several test failures due to not finding /bin/bash, alpine uses busybox with /bin/sh only.

### Steps to reproduce the behavior

Create a Dockerfile:
FROM alpine:edge
RUN apk [install hdf5]
RUN wget [the netcdf-c library]
RUN tar -zxvf [the netcdf-c library]
WORKDIR [the dir]
RUN ./configure
RUN make && make check

docker build .

(EDIT: added configure step and hdf5 info)

**Comment by WardF** [comment]
Unfortunately, using 'sh' is unreliable across other platforms (including OSX), as the 'sh' shell isn't guaranteed to contain the functionality the scripts use, but bash (to date) is.  Is it possible to install bash in alpine linux?

**Comment by edhartnett** [comment]
According to autotools practice, we should be using only sh and not bash.

There should be nothing that we can do in bash that cannot be done in sh.

**Comment by bickelj** [comment]
When I find/replace 'bash' with 'sh' before the make check, at least some of the tests passed, something like this:

`find . -name "tst*sh" -exec sed -i 's/bash/sh/g' "{}" \+`

For example the tests in ncdump will pass under alpine after replacement.

**Comment by bickelj** [comment]
Agree that an easy workaround is to install bash in alpine. Also understand that if the find/replace above causes tests to fail on OSX then this suggestion can be closed.

**Comment by DennisHeimbigner** [comment]
I think there are two issues. The automake tools and ./configure restrict themselves
to sh. But I think our test cases long ago gave up and use bash features (functions?).
So, I think having bash is the proper thing for our tests.

**Comment by bickelj** [comment]
I am a little skeptical that the tests truly depend on bash. Again, many of the tests pass when I do a find of "bash" and replace with "sh".

**Comment by DennisHeimbigner** [comment]
I thing I do not know is: does sh have functions,, or is that bash only?

**Comment by DennisHeimbigner** [comment]
Also remember that on many systems sh is a hard/soft link to bash.

**Comment by WardF** [comment]
I’ll give it a test so that I can at least be specific about the failure we saw. I’m more than happy to switch to sh if workarounds are identified :)

**Comment by WardF** [comment]
Ok, I had conflated this with a similar issue we saw on OSX, the issue here was Ubuntu.  I've made some changes which should address `make check` on Alpine linux.  I'll test this, and see about working Alpine into our CI rotation.  Thanks for bringing this to our attention!
