### ISSUE TITLE
UTF8 Build paths

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#1110]
re: esupport SWJ-921804
I infer from this esupport request that our build process (at least automake) is failing
when the path to the netcdf-c directory contains non-ascii characters.
Need to verify and fix.

**Comment by Dave-Allured** [comment]
HDF5 does not currently support UTF-8 characters in data file names (open file, create file, etc.)  This is likely the cause of this netcdf issue.  Here is the most recent HDF5 ticket for this.

[https://forum.hdfgroup.org/t/non-english-characters-in-hdf5-file-name/4627](https://forum.hdfgroup.org/t/non-english-characters-in-hdf5-file-name/4627)

There are a couple of suggested application-level worksrounds in that ticket.  They seem kludgy and restrictive to me.  Best would be for HDF Group to simply fix UTF-8 support in their API file name calls.

**Comment by Dave-Allured** [comment]
Your original ticket SWJ-921804 says:  "It looks like the library compiled and built correctly, but
some of the tests failed."  This is what you would expect with the HDF5 open/create file name limitation.

**Comment by DennisHeimbigner** [comment]
Sounds right to me. I will close this until such time as HDF5 supports utf8 paths.
