### ISSUE TITLE
nc_test/tst_inmemory is failing, but the failure is not noticed since script returns 0 anyway

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1111]
The program nc_test/tst_inmemory.c (which is called by test script run_inmemory.sh) is failing, but the failure is not detected since the script does not return non-zero value.

When I run the script I get this:

```
bash -x ./run_inmemory.sh 
+ test x = x
++ pwd
+ srcdir=/home/ed/tmp/netcdf-c/nc_test
+ . ../test_common.sh
++ TOPSRCDIR=/home/ed/tmp/netcdf-c
++ TOPBUILDDIR=/home/ed/tmp/netcdf-c
++ set -e
++ test x = x1
++ top_srcdir=/home/ed/tmp/netcdf-c
++ top_builddir=/home/ed/tmp/netcdf-c
++ test x/home/ed/tmp/netcdf-c/nc_test = x
+++ pwd
++ builddir=/home/ed/tmp/netcdf-c/nc_test
++ execdir=/home/ed/tmp/netcdf-c/nc_test
+++ basename /home/ed/tmp/netcdf-c/nc_test
++ thisdir=nc_test
+++ pwd
++ WD=/home/ed/tmp/netcdf-c/nc_test
++ cd /home/ed/tmp/netcdf-c/nc_test
+++ pwd
++ srcdir=/home/ed/tmp/netcdf-c/nc_test
++ cd /home/ed/tmp/netcdf-c/nc_test
++ cd /home/ed/tmp/netcdf-c
+++ pwd
++ top_srcdir=/home/ed/tmp/netcdf-c
++ cd /home/ed/tmp/netcdf-c/nc_test
++ cd /home/ed/tmp/netcdf-c/nc_test
+++ pwd
++ builddir=/home/ed/tmp/netcdf-c/nc_test
++ cd /home/ed/tmp/netcdf-c/nc_test
++ cd /home/ed/tmp/netcdf-c
+++ pwd
++ top_builddir=/home/ed/tmp/netcdf-c
++ cd /home/ed/tmp/netcdf-c/nc_test
++ cd /home/ed/tmp/netcdf-c/nc_test
+++ pwd
++ execdir=/home/ed/tmp/netcdf-c/nc_test
++ cd /home/ed/tmp/netcdf-c/nc_test
++ export srcdir top_srcdir builddir top_builddir execdir
++ test -e /home/ed/tmp/netcdf-c/ncdump/ncdump.exe
++ ext=
++ export NCDUMP=/home/ed/tmp/netcdf-c/ncdump/ncdump
++ NCDUMP=/home/ed/tmp/netcdf-c/ncdump/ncdump
++ export NCCOPY=/home/ed/tmp/netcdf-c/ncdump/nccopy
++ NCCOPY=/home/ed/tmp/netcdf-c/ncdump/nccopy
++ export NCGEN=/home/ed/tmp/netcdf-c/ncgen/ncgen
++ NCGEN=/home/ed/tmp/netcdf-c/ncgen/ncgen
++ export NCGEN3=/home/ed/tmp/netcdf-c/ncgen3/ncgen3
++ NCGEN3=/home/ed/tmp/netcdf-c/ncgen3/ncgen3
++ ncgen3c0=/home/ed/tmp/netcdf-c/ncgen3/c0.cdl
++ ncgenc0=/home/ed/tmp/netcdf-c/ncgen/c0.cdl
++ ncgenc04=/home/ed/tmp/netcdf-c/ncgen/c0_4.cdl
++ cd /home/ed/tmp/netcdf-c/nc_test
+ set -e
++ uname -p
+ CPU=x86_64
++ uname
+ OS=Linux
+ FILE3=tst_inmemory3
+ CREATE3=tst_inmemory3_create
+ FILE4=tst_inmemory4
+ CREATE4=tst_inmemory4_create
+ OMEMFILE=f03tst_open_mem.nc
+ echo ''

+ echo '*** Testing in-memory operations'
*** Testing in-memory operations
++ /home/ed/tmp/netcdf-c/nc-config --has-nc4
+ HASNC4=yes
+ /home/ed/tmp/netcdf-c/nc_test/tst_inmemory

*** Testing the inmemory API: netcdf-3.

	***Test open 1: nc_open_mem(): read-only

	***Test open 2: nc_open_memio(): read-only
	finaldata: size=300 memory=0x563c946bd850

	***Test open 3: nc_open_memio(): read-write, copy
	finaldata: size=348 memory=0x563c9473e150

	***Test open 4: nc_open_memio(): read-write, locked, extra space
	finaldata: size=262144 memory=0x563c946be030

	***Test create 1: nc_create_memio(): no initialsize
	finaldata: size=300 memory=0x563c94740a40

	***Test create 2: nc_create_memio(): initialsize; save file
	finaldata: size=262144 memory=0x563c94742000

	***Test misc 1: use nc_close on created inmemory file

	***Test misc 2: use nc_close on opened inmemory file

	***Test xfail 1: nc_open_mem(): write to read-only
	***XFail: status=-37 NetCDF: Write to read only

	***Test xfail 2: nc_open_memio(): modify without overallocating
	***XFail: status=1 Operation not permitted

*** Testing the inmemory API: netcdf-4.

	***Test open 1: nc_open_mem(): read-only

	***Test open 2: nc_open_memio(): read-only
	finaldata: size=11537 memory=0x563c946be030

	***Test open 3: nc_open_memio(): read-write, copy
***Fail: line: 478; status=-101 NetCDF: HDF error
***Fail: line: 624; status=-101 NetCDF: HDF error
+ echo 'FAIL: tst.inmemory'
FAIL: tst.inmemory
+ /home/ed/tmp/netcdf-c/nc_test/tst_open_mem /home/ed/tmp/netcdf-c/nc_test/f03tst_open_mem.nc
+ echo '**** Test ncdump of the resulting inmemory data'
**** Test ncdump of the resulting inmemory data
+ /home/ed/tmp/netcdf-c/ncdump/ncdump -n tst_inmemory3 tst_inmemory3.nc
+ /home/ed/tmp/netcdf-c/ncdump/ncdump -n tst_inmemory3 tst_inmemory3_create.nc
+ diff -wb tst_inmemory3.cdl tst_inmemory3_create.cdl
+ rm -f tst_inmemory3.nc tst_inmemory4.nc tst_inmemory3_create.nc tst_inmemory4_create.nc
+ rm -f tst_inmemory3.cdl tst_inmemory4.cdl tst_inmemory3_create.cdl tst_inmemory4_create.cdl
+ echo 'PASS: all inmemory tests'
PASS: all inmemory tests
+ exit 0

```
Note that it is returning 0.

When I run tst_inmemory I get this output:

```
 ./tst_inmemory 

*** Testing the inmemory API: netcdf-3.

	***Test open 1: nc_open_mem(): read-only

	***Test open 2: nc_open_memio(): read-only
	finaldata: size=300 memory=0x55c36a3a9850

	***Test open 3: nc_open_memio(): read-write, copy
	finaldata: size=348 memory=0x55c36a42a150

	***Test open 4: nc_open_memio(): read-write, locked, extra space
	finaldata: size=262144 memory=0x55c36a3aa030

	***Test create 1: nc_create_memio(): no initialsize
	finaldata: size=300 memory=0x55c36a42ca40

	***Test create 2: nc_create_memio(): initialsize; save file
	finaldata: size=262144 memory=0x55c36a42e000

	***Test misc 1: use nc_close on created inmemory file

	***Test misc 2: use nc_close on opened inmemory file

	***Test xfail 1: nc_open_mem(): write to read-only
	***XFail: status=-37 NetCDF: Write to read only

	***Test xfail 2: nc_open_memio(): modify without overallocating
	***XFail: status=1 Operation not permitted

*** Testing the inmemory API: netcdf-4.

	***Test open 1: nc_open_mem(): read-only

	***Test open 2: nc_open_memio(): read-only
	finaldata: size=11537 memory=0x55c36a3aa030

	***Test open 3: nc_open_memio(): read-write, copy
***Fail: line: 478; status=-101 NetCDF: HDF error
***Fail: line: 624; status=-101 NetCDF: HDF error
```

So something is wrong here, but the test still passes, because it is not detecting the failure and is returning 0.

**Comment by WardF** [comment]
The script shouldn't return 0 all the time, I'll take a look at that.  FWIW I'm not seeing the HDF error you are reporting, however.  Thanks!

**Comment by WardF** [comment]
Also maybe you created those errors intentionally to illustrate the script always returns 0 even when failures are observed.  Anyways, will fix this.

**Comment by WardF** [comment]
Added a sibling issue to capture some new errors revealed when script syntax errors have been resolved.

**Comment by edhartnett** [comment]
Howdy Ward! I did not create any errors intentionally to illustrate the script. I just happened to run the script from the command line, and noticed it was reporting errors.

The script does not exit because there is error checking. ;-)


```
# Execute the core of the inmemory tests
if ! ${execdir}/tst_inmemory; then
   echo "FAIL: tst.inmemory"
fi
if ! ${execdir}/tst_open_mem ${srcdir}/${OMEMFILE}; then
   echo "FAIL: tst_open_mem"
fi
```
I believe if this is changed to just:

`${execdir}/tst_inmemory
`

then you will see the error that you expect from set -e. As the code is currently written, the call to tst_inmemory returns non-zero, but the if-statement that calls it handles that (by printing "FAIL...") but then the if-statement returns 0. So set -e is happy.

**Comment by WardF** [comment]
Hi Ed, I'm not seeing any error with HDF5 1.8.20, our default install.  I am now seeing the error with 1.10.2, however.  So it appears to be version dependent.

**Comment by WardF** [comment]
# tst_inmemory binary output

## HDF5 1.8.20

* Testing the inmemory API: netcdf-3.

	***Test open 1: nc_open_mem(): read-only

	***Test open 2: nc_open_memio(): read-only
	finaldata: size=300 memory=0x7f87a1c39df0

	***Test open 3: nc_open_memio(): read-write, copy
	finaldata: size=348 memory=0x7f87a200bc00

	***Test open 4: nc_open_memio(): read-write, locked, extra space
	finaldata: size=262144 memory=0x10be68000

	***Test create 1: nc_create_memio(): no initialsize
	finaldata: size=300 memory=0x7f87a200a600

	***Test create 2: nc_create_memio(): initialsize; save file
	finaldata: size=262144 memory=0x10be68000

	***Test misc 1: use nc_close on created inmemory file

	***Test misc 2: use nc_close on opened inmemory file

	***Test xfail 1: nc_open_mem(): write to read-only
	***XFail: status=-37 NetCDF: Write to read only

	***Test xfail 2: nc_open_memio(): modify without overallocating
	***XFail: status=1 Operation not permitted

*** Testing the inmemory API: netcdf-4.

	***Test open 1: nc_open_mem(): read-only

	***Test open 2: nc_open_memio(): read-only
	finaldata: size=11537 memory=0x7f87a200a600

	***Test open 3: nc_open_memio(): read-write, copy
	finaldata: size=11537 memory=0x7f87a200d400

	***Test open 4: nc_open_memio(): read-write, locked, extra space
	finaldata: size=262144 memory=0x10be68000

	***Test create 1: nc_create_memio(): no initialsize
	finaldata: size=65536 memory=0x7f87a2076c00

	***Test create 2: nc_create_memio(): initialsize; save file
	finaldata: size=65536 memory=0x7f87a2086c00

	***Test misc 1: use nc_close on created inmemory file

	***Test misc 2: use nc_close on opened inmemory file

	***Test xfail 1: nc_open_mem(): write to read-only
	***XFail: status=-37 NetCDF: Write to read only

	***Test xfail 2: nc_open_memio(): modify without overallocating
	Suppressed because of HDF5 library bug
ok.
*** Tests successful!

## HDF5 1.10.2


*** Testing the inmemory API: netcdf-3.

	***Test open 1: nc_open_mem(): read-only

	***Test open 2: nc_open_memio(): read-only
	finaldata: size=300 memory=0x7fba34d03640

	***Test open 3: nc_open_memio(): read-write, copy
	finaldata: size=348 memory=0x7fba35006a00

	***Test open 4: nc_open_memio(): read-write, locked, extra space
	finaldata: size=262144 memory=0x10249c000

	***Test create 1: nc_create_memio(): no initialsize
	finaldata: size=300 memory=0x7fba35005400

	***Test create 2: nc_create_memio(): initialsize; save file
	finaldata: size=262144 memory=0x10249c000

	***Test misc 1: use nc_close on created inmemory file

	***Test misc 2: use nc_close on opened inmemory file

	***Test xfail 1: nc_open_mem(): write to read-only
	***XFail: status=-37 NetCDF: Write to read only

	***Test xfail 2: nc_open_memio(): modify without overallocating
	***XFail: status=1 Operation not permitted

*** Testing the inmemory API: netcdf-4.

	***Test open 1: nc_open_mem(): read-only

	***Test open 2: nc_open_memio(): read-only
	finaldata: size=11537 memory=0x7fba35005400

	***Test open 3: nc_open_memio(): read-write, copy
***Fail: line: 478; status=-101 NetCDF: HDF error
***Fail: line: 624; status=-101 NetCDF: HDF error

**Comment by WardF** [comment]
@DennisHeimbigner is there an API change you might be aware of that would explain this? If not, I'll investigate further to see if we need to do something different for inmemory functionality, or if we need to open a bug report with the HDF group for their 1.10.x branch.

**Comment by WardF** [comment]
The branch I'm working on has added explicit error checking so the script now fails as expected, at least.

**Comment by WardF** [comment]
Note: Failure is at nc4mem.c:101, the call to `H5Pget_file_image()`.  It is returning `-1` with hdf5 1.10.2.

**Comment by edhartnett** [comment]
BTW I checked the other shell scripts for this same sort of problem, but didn't find one. In other cases, we call our test programs like this:

```
# Try to rename 2nd level group
if ! ${execdir}/renamegroup tst_grp_rename.nc "inner/inner_inner" "inner_renamed" ; then
  echo "***FAIL: attempt to rename /inner/inner_inner failed"
  FAIL=1
fi

exit $FAIL

```
or (most often) like this:
```
echo "Generating test netcdf files."
${execdir}/tst_empty_vlen_unlim

```

**Comment by WardF** [comment]
@edhartnett Thanks Ed!

**Comment by DennisHeimbigner** [comment]
I am working on the underlying problem. It is indeed how 1.10
handles the core driver and image file access. Hope result
will be somewhat less fragile.

**Comment by WardF** [comment]
Thanks @DennisHeimbigner.  The branch `gh1111.wif` has fixes to the shell script, if you want to work in that branch. Otherwise I can merge the two together with your branch. Thanks!

**Comment by DennisHeimbigner** [comment]
Ok, when I get it working, I will go ahead and merge the fix into the gh1111.wif
branch.

**Comment by edhartnett** [comment]
I believe this has been fixed and merged, so I will close the ticket.
