### ISSUE TITLE
nc_test/run_inmemory failing.

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#1113]
In addition to #1111, there were some syntax errors in the `run_inmemory.sh` script.  Now fixed, I am seeing additional errors.  

`ncdump: tst_inmemory4_create.nc: NetCDF: Unknown file format`

**Comment by DennisHeimbigner** [comment]
I suspect that the issue is the hdf5 library: 1.8 vs 1.10.

**Comment by WardF** [comment]
this is correct, #1111 has additional details. I’m not sure why, however.

**Comment by WardF** [comment]
Closing this out to avoid duplication with #1111, since the underlying issue is probably the same.
