### ISSUE TITLE
Problem reading file in 4.6.2-devel; works in 4.4.1

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#1115]
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### Environment Information

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [x] Linux
  * [ ] Windows
  * [x] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [x] 64-bit
* What build system are you using?
  * [x] autotools (`configure`)
  * [x] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [x] Yes (please attach to this issue, thank you!)
  * [ ] No
  * [ ] Not at this time

### Summary of Issue
I have a file which reads OK in some previous versions; in particular 4.4.1 but I haven't tried anything between 4.4.1 and 4.6.2-devel.  When I read it in 4.6.2-devel, I get an error in `NC_check_voffs`:
```
Variable "qa_records" begin offset (15943) is less than previous variable end offset (15944)
```
If I `ncdump` the file using a previous version and then `ncgen` it using either old (4.4.1) or new (4.6.2-devel) versions, the file is no longer "corrupt" and can be read by both the new and old `ncdump`

I modified `NC_check_voffs` to print out statistics for the variables and I get the following:

Ncdump Original:
============
name          | prevoff|begin   |len    | prev_off+len
--------------|--------|--------|-------|--------------
coor_names    |  15844 |  15844 |  100  |   15944
qa_records    |  15944 |  15943 |  1584 |   17528  <-- error in NC_check_voffs
info_records  |  17527 |  17527 |  84   |   17611
coord         |  17611 |  2296  |  13548|   31159  <-- error in NC_check_voffs
eb_prop1      |  15844 |  47736 |  12   |   15856
eb_status     |  47748 |  47724 |  12   |   47760  <-- error in NC_check_voffs
connect1      |  47736 |  17608 |  11264|   59000  <-- error in NC_check_voffs
connect2      |  28872 |  28872 |  2688 |   31560
connect3      |  31560 |  31560 |  3592 |   35152
attrib3       |  35152 |  35152 |  12572|   47724
elem_map      |  47724 |  47748 |  3540 |   51264
node_map      |  51288 |  51288 |  4516 |   55804
ns_prop1      |  55804 |  59452 |  16   |   55820
ns_status     |  59468 |  59436 |  16   |   59484  <-- error in NC_check_voffs
node_ns1      |  59452 |  55804 |  1800 |   61252  <-- error in NC_check_voffs
dist_fact_ns1 |  57604 |  57604 |  1800 |   59404
node_ns2      |  59404 |  59404 |  4    |   59408
dist_fact_ns2 |  59408 |  59408 |  4    |   59412
node_ns3      |  59412 |  59412 |  4    |   59416
dist_fact_ns3 |  59416 |  59416 |  4    |   59420
node_ns4      |  59420 |  59420 |  8    |   59428
dist_fact_ns4 |  59428 |  59428 |  8    |   59436

Ncgen:
=====
name          | prevoff|begin   |len     | prev_off+len
--------------|--------|--------|--------|--------------
coor_names    |  2296  |  2296  |  100   |  2396
qa_records    |  2396  |  2396  |  1584  |  3980
info_records  |  3980  |  3980  |  84    |  4064
coord         |  4064  |  4064  |  13548 |  17612
eb_prop1      |  17612 |  17612 |  12    |  17624
eb_status     |  17624 |  17624 |  12    |  17636
connect1      |  17636 |  17636 |  11264 |  28900
connect2      |  28900 |  28900 |  2688  |  31588
connect3      |  31588 |  31588 |  3592  |  35180
attrib3       |  35180 |  35180 |  12572 |  47752
elem_map      |  47752 |  47752 |  3540  |  51292
node_map      |  51292 |  51292 |  4516  |  55808
ns_prop1      |  55808 |  55808 |  16    |  55824
ns_status     |  55824 |  55824 |  16    |  55840
node_ns1      |  55840 |  55840 |  1800  |  57640
dist_fact_ns1 |  57640 |  57640 |  1800  |  59440
node_ns2      |  59440 |  59440 |  4     |  59444
dist_fact_ns2 |  59444 |  59444 |  4     |  59448
node_ns3      |  59448 |  59448 |  4     |  59452
dist_fact_ns3 |  59452 |  59452 |  4     |  59456
node_ns4      |  59456 |  59456 |  8     |  59464
dist_fact_ns4 |  59464 |  59464 |  8     |  59472

I'm not sure what version of the library was used to write the original file, but I suspect it was possibly a Java implementation around 2009.  I have a few files which are exhibiting this behavior.

I realize a quick solution is to just "ncdump | ncgen" and the file is fixed; however, I am more concerned that I will find more of these files "in the wild" and unless I keep an older version of ncdump available for my users; I won't be able to provide them with a path to use the file.  As you can see, this file was originally generated about 2009 and is still being used.  The application that created the file is still in use and I haven't verified whether the files it is currently creating are exhibiting this same behavior.

Is the test that is failing a valid test that indicates a corrupt file, or is it just something that was added as a potential sanity check.  If I remove the call to `NC_check_voffs`, then all tests pass and the file content seems to be read correctly...

Thanks, sorry for probing the corners...
[bad_file.zip](https://github.com/Unidata/netcdf-c/files/2297743/bad_file.zip)

**Comment by Dave-Allured** [comment]
Ncdump 4.4.1.1 understands this file and shows normal-looking results:
```
> ncdump -k spring_placement.g 
classic
```
Ncdump 4.6.1 (normal release version) prints this:
```
> ncdump -k spring_placement.g
ncdump: spring_placement.g: NetCDF: Unknown file format
```
Based only on Greg's offset diagnostics above, this is a malformed or corrupt netcdf-3 file that violates the official format spec.  Good diagnostics, by the way.

In my opinion netcdf-C should only be expected, at best, to return some kind of error status when a format violation is detected.  There should be no obligation to somehow return successful data reads.  That could easily result in data with hidden defects and no warning.

However it would be nice to return more specific error status when the code has specific knowledge.  In this case "Format violation, invalid variable offset" would be more informative than the current "Unknown file format".

Greg, I suggest your best way forward is to try to find a valid original copy of this file for your users.  Failing that, clean it up with ncdump/ncgen and check the result carefully.

**Comment by DennisHeimbigner** [comment]
Agreed about the error reporting. We need to make more use of our logging output
to provide extra information.

**Comment by Dave-Allured** [comment]
There is something else going on.  @gsjaardema wrote:

> I'm not sure what version of the library was used to write the original file, but I suspect it was possibly a Java implementation around 2009. I have a few files which are exhibiting this behavior.

More than one file suggests this is not simple file corruption.  Rather, there may have been "rogue" netcdf writer software that made malformed netcdf-3 files with bad var offsets.  This may have gone unnoticed for a while.  Such files could apparently be read by older netcdf-C versions before offset checking was added (somewhere between 4.5.0 and 4.6.1).

It might be worth investigating to find out whether the offset problem was ever definitively identified and corrected in that writer software.

**Comment by gsjaardema** [comment]
@Dave-Allured I agree with further investigation and will let you know if I find anything.  I have a method for converting the files into files readable by the current library, so I am fine with closing this issue.  Just wanted to make sure that the `NC_check_voffs` check was a valid test which it appears that it is.

**Comment by WardF** [comment]
Closing this for now but we can reopen if need be.  Thanks all for their input and information!
