### ISSUE TITLE
run_par_tests.sh fails : An error occurred in MPI_Comm_create_keyval

### ISSUE THREAD

**Issue by k2patel** [Unidata/netcdf-c#1122]
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### Environment Information

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [ ] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [x] 64-bit
* What build system are you using?
  * [x] autotools (`configure`)
  * [ ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [ ] Yes (please attach to this issue, thank you!)
  * [x] No
  * [ ] Not at this time

### Summary of Issue
<pre>
==========================================
   netCDF 4.6.1: h5_test/test-suite.log
==========================================

# TOTAL: 26
# PASS:  25
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: run_par_tests.sh
======================

Testing parallel I/O with HDF5...
[k2patelrad:6533] *** An error occurred in MPI_Comm_create_keyval
[k2patelrad:6533] *** reported by process [794689537,0]
[k2patelrad:6533] *** on communicator MPI_COMM_WORLD
[k2patelrad:6533] *** MPI_ERR_ARG: invalid argument of some other kind
[k2patelrad:6533] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[k2patelrad:6533] ***    and potentially your MPI job)
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[12126,1],0]
  Exit code:    13
--------------------------------------------------------------------------
</pre>
### Steps to reproduce the behavior
OS = RHEL 7.5
HDF5 = 1.10

./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-netcdf-4 --enable-dap --enable-extra-example-tests CPPFLAGS=-I/usr/include/hdf LIBS=-ljpeg --enable-hdf4 --disable-dap-remote-tests LDFLAGS=-L/usr/lib64/hdf LD_LIBRARY_PATH=/usr/lib64/hdf/ CPPFLAGS=-I/usr/include/hdf --libdir=/usr/lib64/mpich/lib --bindir=/usr/lib64/mpich/bin --sbindir=/usr/lib64/mpich/sbin --includedir=/usr/include/mpich-x86_64 --datarootdir=/usr/lib64/mpich/share --mandir=/usr/lib64/mpich/share/man --enable-parallel-tests

make
make test

**Comment by edhartnett** [comment]
Was this in the h5_test directory? If so, there is something wrong with your HDF5 parallel I/O build. The h5_test programs test HDF5 without involving netCDF.

Was HDF5 built with --enable-parallel? You say version is 1.10, can you try 1.10.1?

**Comment by k2patel** [comment]
Sorry about not specifying exact version. hdf5 version i've is 1.10.2. I'll try to run same test against 1.10.1.
will update you with result.
Thank you.

**Comment by k2patel** [comment]
So i've tested with version
hdf = 1.10.1
netcdf = 4.6.1
openmpi = 1.10.7
It passes the parallel mpich test but failed with following openmpi error.
```
=========================================
   netCDF 4.6.1: ncgen3/test-suite.log
=========================================

# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: run_nc4_tests.sh
======================

*** Testing ncgen3 for netCDF-4.
*** creating netCDF-4 file c0_4.nc from c0.cdl...
/scr/lrknox/rpmbuild/BUILD/netcdf-c-4.6.1/openmpi/ncgen3/.libs/ncgen3: symbol lookup error: /scr/lrknox/rpmbuild/BUILD/netcdf-c-4.6.1/openmpi/liblib/.libs/libnetcdf.so.13: undefined symbol: H5Pset_all_coll_metadata_ops
```

**Comment by edhartnett** [comment]
Can you test with current master branch?

**Comment by edhartnett** [comment]
Also, if you see this problem with the master branch, and you provide the full output from configure.

**Comment by edwardhartnett** [comment]
I believe this problem is fixed for all the current versions of HDF5 and netcdf-c. I believe this issue can be closed.

**Comment by mmeindl97** [comment]
Which Version of HDF5 and netcdf-c do you mean by your last post? With hdf5-verson 1.10.5 I get:

[n405-001:220119] *** An error occurred in MPI_Comm_create_keyval
[n405-001:220119] *** reported by process [13875379257834143745,0]
[n405-001:220119] *** on communicator MPI_COMM_WORLD
[n405-001:220119] *** MPI_ERR_ARG: invalid argument of some other kind
[n405-001:220119] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[n405-001:220119] ***    and potentially your MPI job)

when running a script via SLURM.
