### ISSUE TITLE
ncoffsets.h:Alignment.typename: In C++ typename is a reserved word

### ISSUE THREAD

**Issue by schwehr** [Unidata/netcdf-c#1131]
### Environment Information

* What platform are you using? (please provide specific distribution/version in summary)
  * [x] Linux
* 32 and/or 64 bit?
  * [x] 64-bit
* What build system are you using?
  * [x] bazel
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [x] No
* Compiler
  * [x] clang / llvm

### Summary of Issue

In include/ncoffsets.h, Alignment has a member named `typename`.  This causes trouble with systems using netcdf from C++.

typename is a reserved word in C++.

https://en.cppreference.com/w/cpp/keyword/typename

### Steps to reproduce the behavior

```c++
typedef struct Alignment {
    char* typename;
    unsigned int alignment;
} Alignment;
```

Parse the header from C++ fails.

The best solution from a C++ user POV would be to rename the member.  But if for API compatibility, perhaps you just have to do an ifdef

```c++
#ifdef __cplusplus
typedef struct Alignment Alignment;
#else
typedef struct Alignment {
    char* typename;
    unsigned int alignment;
} Alignment;
#endif
```

**Comment by DennisHeimbigner** [comment]
Fixed by pull request https://github.com/Unidata/netcdf-c/pull/1132
