### ISSUE TITLE
Configure 'enable_filter_testing' error with supported options.

### ISSUE THREAD

**Issue by naromero77** [Unidata/netcdf-c#1134]
### Environment Information
Linux
64-bit
autotools
Intel 18 compiler

### Summary of Issue
Configure does not complete due to buglet triggered by combination of options.

### Steps to reproduce the behavior
Issue with with netcdf 4.6.1.

On an X86 machine with the Intel compiler, do:
```
#!/bin/csh
setenv NETCDFHOME $HOME/netcdf/intel/4.6.1
setenv HDF5HOME $HOME/hdf5/intel/1.8.10/parallel

setenv CC `which mpiicc`
setenv CXX `which mpiicpc`
setenv F77 `which mpiifort`
setenv FC `which mpiifort`
setenv CFLAGS "-I${NETCDFHOME}/include -I${HDF5HOME}/include -O2"
setenv CXXFLAGS "-I${NETCDFHOME}/include -I${HDF5HOME}/include -O2"
setenv FFLAGS "-I${NETCDFHOME}/include -I${HDF5HOME}/include -O2"
setenv FCFLAGS "-I${NETCDFHOME}/include -I${HDF5HOME}/include -O2"
setenv F90FLAGS "-I${NETCDFHOME}/include -I${HDF5HOME}/include -O2"
setenv FPPFLAGS "-I${NETCDFHOME}/include -I${HDF5HOME}/include -O2"
setenv CPPFLAGS "-I${NETCDFHOME}/include -I${HDF5HOME}/include -O2"
setenv LDFLAGS "-L${NETCDFHOME}/lib -L${HDF5HOME}/lib"

./configure --enable-pnetcdf --enable-netcdf4 --enable-shared=no --with-pic=no --enable-erange-fill --enable-zero-length-coord-bound --disable-filter-testing --prefix=${NETCDFHOME} > configure.log
```
Here is the error that I get:
```
configure: WARNING: Shared libraries are disabled => --disable-filter-testing
./configure: line 18214: enable_filter_testing: command not found
```

**Comment by WardF** [comment]
Hi,  are you seeing an error in addition to the `warning` reported here?  I'm seeing the same error when I test `4.6.1` but it doesn't stop `configure` from completing successfully.

I've just checked `master` and it may be a moot point, as this is corrected in the upcoming release.  If you can run `make` after running `configure`, I suspect it is safe to ignore the error you are observing.

**Comment by naromero77** [comment]
I was not concerned with the warning message, but with the `command not found` error.

Correction, configure does complete and the settings look correct. I am able to do `make`. The error is benign. 

If its fixed upstream, you can close this issue.
