### ISSUE TITLE
set_fmode causing errors 

### ISSUE THREAD

**Issue by Judi-Triathlete** [Unidata/netcdf-c#1138]
Windows
32 bit
Visual Studio 2015

This section of code in nc_initialize.c is causing subsequent loaded dll to fail.
#ifdef _MSC_VER
    /* Force binary mode */

    _set_fmode(_O_BINARY);

#endif

When another dll is loaded after this flag is set and try to open a file, it fails since this sets global binary mode.

**Comment by WardF** [comment]
Thanks for pointing this out!

**Comment by Judi-Triathlete** [comment]
You are welcome.
I also set all the fopen to include -b flag just in case (locally of course)
