### ISSUE TITLE
retire NC_MPIIO

### ISSUE THREAD

**Issue by wkliao** [Unidata/netcdf-c#1145]
I think NC_MPIIO may have become redundant, since NetCDF 4.1 incorporated a PnetCDF driver to do parallel I/O on classic files. In my view, API nc_create_par() implied the user's parallel I/O intent and the format of file to be created depends on whether NC_NETCDF4, NC_64BIT_OFFSET, or NC_64BIT_DATA appears in the creation mode argument. These flags are sufficient to decide to call HDF5 or PnetCDF driver underneath. Thus, there is no need to check NC_MPIIO in order to use PnetCDF driver.

As for API nc_open_par(), parallel I/O driver is selected based on the format of file to be opened, not the user mode flag. Thus, it also need not check NC_MPIIO.

As for sequential APIs, e.g. nc_create() and nc_open(), should NC_MPIIO be ignored or cause NC_ENOPAR returned? A test shows NetCDF is not consistent. 4.6.1 ignores it, but 4.5.0 throws NC_ENOPAR.

**Comment by DennisHeimbigner** [comment]
Not sure I follow. Since e.g. nc_open_par is a wrapper around nc_open,
we need a flag to pass along to nc_open that indictes that the original
call was to nc_open_par. What flag are you suggesting we use?

**Comment by wkliao** [comment]
Argument `useparallel` in [NC_open](https://github.com/Unidata/netcdf-c/blob/18a05d0ed62d16e2ac02e6688223c9e4129e1fd7/libdispatch/dfile.c#L2204) serves that purpose. nc_create_par and nc_open_par will set it to 1, while nc_create and nc_open will use 0.

**Comment by DennisHeimbigner** [comment]
Thought we got rid of the useparallel argument; guess not.
I think the issue is: does the user have to call nc_open_par
or is it ok to call nc_open with the NC_MPIO (badly named in restrospect)
flag set. There may be back compatibility issues here.

**Comment by DennisHeimbigner** [comment]
Good point. Although it may have once been the case that the MPI
communicator was defaulted.
In doing a search, it also looks like we do not need the NC_MPIPOSIX flag
anymore. However both NC_MPI and NC_MPIPOSIX will need to stay
in include/netcdf.h.
I would like Ed Hartnett's analysis of this proposal since he has the most
historical knowledge about this code.

**Comment by wkliao** [comment]
I agree these constants should be kept in netcdf.h. I also suggest to add a note saying they are deprecated in netcdf.h and user guides. If this becomes official, then several NetCDF internal subroutines need to change to ignore these constants and NetCDF APIs will no longer return NC_EINVAL or NC_ENOPAR error due to the use of them (for example using NC_MPIIO in serial nc_create). Any thoughts on this new behavior? Note NetCDF has been inconsistent on this.

**Comment by edhartnett** [comment]
What about NC_MPIPOSIX under this proposal?

**Comment by wkliao** [comment]
@DennisHeimbigner mentioned "we do not need the NC_MPIPOSIX flag anymore".
Looks like NC_MPIPOSIX is replaced with NC_MPIIO before entering the HDF5 driver for parallel I/O.

**Comment by edhartnett** [comment]
In that case it may be ignored.

As noted by @wkliao it is not needed to indicate parallel IO. It is only there to differentiate between MPIIO and MPIPOSIX.

**Comment by DennisHeimbigner** [comment]
Does anyone know what the difference was between NC_MPIIO and NC_MPIPOSIX?
A quick search seemed to show that it had to do with using POSIX IO vs something else.

**Comment by wkliao** [comment]
When NC_MPIIO is used, `nc4_create_file()` calls `H5Pset_fapl_mpio()`.
When NC_MPIPOSIX is used, `nc4_create_file()` calls `H5Pset_fapl_mpiposix()`

From HDF5 doc about [H5Pset_fapl_mpiposix()](https://support.hdfgroup.org/HDF5/doc/RM/H5P/H5Pset_fapl_mpiposix.htm), this API is removed since 1.8.13. That reads to me it is safe for NetCDF to call `H5Pset_fapl_mpio()` only.

**Comment by DennisHeimbigner** [comment]
Thanks for finding that! I agree, I think we can start ignoring MPIPOSIX flag.
I suppose that there are some people out there using some old version of HDF5,
but 1.8.13 is pretty old.

**Comment by wkliao** [comment]
That is OK. If a user built NetCDF with HDF5 1.8.12 and prior, using NC_MPIPOSIX or not will go through the path of `H5Pset_fapl_mpio()` internally in NetCDF. Although different I/O methods, the resulted I/O requests are expected the same. The only difference is the performance and HDF5 says MPIO is as good or better.
