### ISSUE TITLE
ncdump fails to open a particular file

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#1151]
As reported by @rsignell-usgs, the following command fails using either netCDF `4.6.2-rc1` or the older `4.4.1`.  

    $ ncdump -h https://stellwagen.er.usgs.gov/thredds/dodsC/TSdata/MVCO_15/10571whV-a.nc

It returns an invalid argument error.  Grabbing the file and opening it locally works just fine.

**Comment by rsignell-usgs** [comment]
cc @emontgomery-usgs

**Comment by DennisHeimbigner** [comment]
I am looking at it. Looks like a problem inside the DAP2 library. The File looks
ok to a superficial perusal.

**Comment by DennisHeimbigner** [comment]
Ok, I think the failure point is the variable "Or", and its "_FillValue" attribute.
The type of "Or" is int and the type of the "_Fillvalue" is float.
I could swear this problem has come up before, but I cannot find the issur or pull request
related to it.

**Comment by rsignell-usgs** [comment]
@DennisHeimbigner, thanks for the sleuthing and this quick response!   
We will change the `_FillValue` of the variable `Or` to `int` to match the `int` variable type.

**Comment by DennisHeimbigner** [comment]
Ok. I see this occasionally. I do have a question: is it better to do the conversion
or to fail when this mismatch occurs?

**Comment by rsignell-usgs** [comment]
How about doing the conversion if the conversion works (e.g. if they converted value has the same numeric value) and failing if it doesn't. 

So in this case you would fail be cause there is no way to store `1.e35` as `int`.   But if the value was `-9999` instead, it would not fail and be converted. 

Does that make sense?

**Comment by DennisHeimbigner** [comment]
Doing that check will, of course, only work for atomic types, not user types.
Also, there is the perennial question of what does "equal" mean for floating point
values when, for example, the variable is of type float and the _FillValue is of type
double or UINT64 In that case, converting the double to a float and back to double to compare may cause truncation of least significant bits. 
My alternate proposal is to give the user a way to allow or disallow such a mismatch
on a per-url request basis.

**Comment by DennisHeimbigner** [comment]
Fixed by pull request https://github.com/Unidata/netcdf-c/pull/1155
