### ISSUE TITLE
HDF5 1.10.x memory problem

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#1156]
Starting with at least HDF5 version 1.10.2,
the filter testing in netcdf-c is failing. The
error occurs in plugins/H5bzip2.c  at the free()
at about line 172.
Code works with HDF5 version 1.8.20.
Other version of the HDF5 library are unknown.
First discovered by accident in PR https://github.com/Unidata/netcdf-c/pull/1155

**Comment by WardF** [comment]
I'm recompiling my local hdf5 with memory checking in place, to see if anything pops up.  It's a shot in the dark but we will see what it says.

**Comment by DennisHeimbigner** [comment]
I think I have a fix, but it raises some questions about the libhdf5 code.

**Comment by DennisHeimbigner** [comment]
Fixed by PR https://github.com/Unidata/netcdf-c/pull/1157

**Comment by edhartnett** [comment]
Under what circumstances do we need to use the hdf5 memory function?
