### ISSUE TITLE
ncdap test failing but returns success

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#117]
The following line, taken from the test script `ncdap_test/tst_ncdap3.sh` fails but returns 0.  As a result of this, no error has been raised on our testing dashboard until today, when a Windows environment started seeing the error.  Other Windows (and linux, and OSX) environments still fail, but return success.  

The test in my environment is as follows; modify the path to your environment:

> $ ./ncdump [log][cache][noprefetch]file:///home/wfisher/netcdf-c/build/ncdap_test/testdata3/synth9

This generates the following:

~~~~
netcdf synth9 {
dimensions:
	lat = 2 ;
	long = 2 ;
variables:
	int lat(lat) ;
	int long(long) ;
	float G1(lat, long) ;
data:

NetCDF: Index exceeds dimension bound
Location: file /home/wfisher/Desktop/gitprojects/netcdf-c/ncdump/vardata.c; line 473
 lat = 
~~~~

Two issues here. First is the bug being reported in `vardata.c` line 473, and second is the fact that, despite the failure, `0` is being returned.

I have confirmed that this behavior exists in the current `master`, `v4.3.3.1`, `v4.3.3`.

On version `4.3.2`, the error exists but the message changes.  It is as follows:

~~~~
Log:Lost attribute: v1
Log:Lost attribute: v1
netcdf synth9 {
dimensions:
	lat = 2 ;
	long = 2 ;
variables:
	int lat(lat) ;
	int long(long) ;
	float G1(lat, long) ;
data:

Log:missing/invalid begin/end record marker

NetCDF: Index exceeds dimension bound
Location: file vardata.c; line 479
 lat = 
~~~~

**Comment by DennisHeimbigner** [comment]
The fact that the script is not return 1
may be due to the fact that it does not contain
a "set -e" command. I have added and am testing now.
=Dennis

Ward Fisher wrote:

**Comment by durack1** [comment]
@WardF @DennisHeimbigner is this issue fixed in `4.4.0-rc1`? Should I add an issue on the Unidata bug tracker (https://bugtracking.unidata.ucar.edu/browse/NCF) or is there already a bug in that system?

**Comment by DennisHeimbigner** [comment]
Sorry, the original issue got lost in dealing with the bad return value.
I will look the original problem.

**Comment by durack1** [comment]
@DennisHeimbigner any more info to enlighten folks here? I'm certainly curious if the `dap` issues I was hitting in `4.3.3.1` will be, or is fixed in `4.4.0-rc1`

**Comment by durack1** [comment]
@russrew @WardF @DennisHeimbigner any more info to enlighten folks here or with the issue found in #115? I'm certainly curious if the `dap` issues I was hitting in `4.3.3.1` will be, or is fixed in `4.4.0-rc1`

**Comment by DennisHeimbigner** [comment]
No news, but thanks for the periodic ping.

**Comment by DennisHeimbigner** [comment]
It appears the problem is that synth9 was erroneously
included in testing. It involves a nested sequence which
is not translatable. Not sure why it was still there,
but fix is to suppress the test.

**Comment by WardF** [comment]
Looks good, thanks Dennis!
