### ISSUE TITLE
Documentation warning: can't find dap4 ref for guide.dox

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1178]
When I do a documentation build, I get this warning:

`/home/ed/tmp/netcdf-c/docs/guide.dox:16: warning: unable to resolve reference to `dap4' for \ref command`

Not sure what happened to the dap4 section...

**Comment by DennisHeimbigner** [comment]
Does the file docs/DAP4.md exist?

**Comment by WardF** [comment]
It looks like the file `DAP4.dox` is present but is not included in the doxyfile template.  I'll fix this.

**Comment by WardF** [comment]
Merging fix into 4.6.2 release branch, where it will propagate back into `master`

**Comment by edhartnett** [comment]
This is still happening for me with today's master:

```
ed@mikado:~/tmp/netcdf-c$ cd docs/
ed@mikado:~/tmp/netcdf-c/docs$ make
Making all in images
make[1]: Entering directory '/home/ed/tmp/netcdf-c/docs/images'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/ed/tmp/netcdf-c/docs/images'
make[1]: Entering directory '/home/ed/tmp/netcdf-c/docs'
doxygen Doxyfile \
cp auth.md obsolete/fan_utils.html html
/home/ed/tmp/netcdf-c/docs/DAP4.dox:44: warning: Invalid list item found
/home/ed/tmp/netcdf-c/docs/DAP4.dox:44: warning: Invalid list item found
make[1]: Leaving directory '/home/ed/tmp/netcdf-c/docs'
```

**Comment by WardF** [comment]
It still seems to render properly in the generated html; pretty low priority for the time being but we'll circle back around to it.

**Comment by edhartnett** [comment]
The problem is with this line:

   +  [protocol=dap4]http://remotetest.unidata.ucar.edu/d4ts/test.01

@DennisHeimbigner is there supposed to be a reference called "protocol=dap4"?

I don't see any other reference to it in the documentation...

**Comment by DennisHeimbigner** [comment]
I have been trying to fix them, but nothing I do (including escaping the [] chars
seems to work. This line and several around it are showing example URLS
that have tags attached that are interpreted by our DAP code. So they are not
supposed to be doxygen references but are legitimate parts of the URL example.
If you know an escape sequence that fixes it, let me know. Those warnings
are irritating, but do not appear to affect the output.

**Comment by edhartnett** [comment]
OK, now I get it. Let me try and escape them, there must be a way!

**Comment by edhartnett** [comment]
OK, funny, it wasn't that at all.

There was a space missing before the hyphen of the first element in the list.

`-  URL - this is a standard form URL with specific markers to indicate that
`
Should be:

` - URL - this is a standard form URL with specific markers to indicate that`

Note extra space in front.

This is to align the hyphen with other items in the list. From the doxygen manual:

`By putting a number of column-aligned minus (-) signs at the start of a line, a bullet list will automatically be generated.
`

So they must be column-aligned!

I will incorporate this into my current PR,; you can also fix it sooner if you like.

**Comment by DennisHeimbigner** [comment]
LOL I never would have guessed.
