### ISSUE TITLE
Chunking using nccopy

### ISSUE THREAD

**Issue by ArchangeGabriel** [Unidata/netcdf-c#1183]
The man page says:
> If the variable is specified but no chunk sizes are specified (i.e. _-d var:_) then chunking is disabled for that variable.

First, I think there is an issue because it should be `-c` and not `-d`. Second, it does not work for me, I get:
```
NetCDF: Invalid argument
Location: file ncdump/nccopy.c; line 1818
```

**Comment by DennisHeimbigner** [comment]
could you post the complete ncdump command you use, and if possible,
the .nc file (or its .cdl equivalent)?

**Comment by DennisHeimbigner** [comment]
fixed by pull request https://github.com/Unidata/netcdf-c/pull/1192
