### ISSUE TITLE
Incorrect function arguments for tst_open in tst_udf.c

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#1196]
In current repository source, the `tst_open` function has an extra argument not in the `NC_Dispatch` struct definition.  `NC_Dispatch` has:
```
int (*open)(const char *path, int mode,
            int basepe, size_t *chunksizehintp,
            void* parameters, struct NC_Dispatch* table, NC* ncp);
```

But `tst_open` at line 27 of `tst_udf.c` has:
```
int
tst_open(const char *path, int mode, int basepe, size_t *chunksizehintp,
             int use_parallel, void *parameters, NC_Dispatch *dispatch,
             NC *nc_file)
{
   return NC_NOERR;
}
```
Note that the `int use_parallel` argument is extra.

**Comment by gsjaardema** [comment]
Forgot part of the report...

This causes a warning when `tst_open` is used in the `tst_dispatcher` struct at line 72 of `tst_udf.c`

**Comment by edhartnett** [comment]
I believe this issue may now be closed.
