### ISSUE TITLE
test for netCDF 4.6.1 fails on testurl.sh (on GuixSD)

### ISSUE THREAD

**Issue by mvhulten** [Unidata/netcdf-c#1215]
### Environment Information
* Platform: x86_64 GNU/Linux
* Build system: GNU build system (Autotools)

### Summary of Issue
I try to build NetCDF 4.6.1.  It gives this issue:

```
$ cat test-suite.log 
=============================================
   netCDF 4.6.1: ncdap_test/test-suite.log
=============================================

# TOTAL: 12
# PASS:  11
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: testurl
=============

***Testing url prefix parameters
command: /tmp/guix-build-netcdf-4.6.1.drv-0/netcdf-4.6.1/ncdump/ncdump -h [log][show=fetch]http://remotetest.unidata.ucar.edu/dts/test.03
FAIL testurl.sh (exit status: 1)
```

The file `http://remotetest.unidata.ucar.edu/dts/test.03` does not exist, but `http://remotetest.unidata.ucar.edu/dts/test.03.dds` does.  Is this the issue, or is `.dds` automatically added?

### Steps to reproduce the behavior
Roughly, the Guix build system downloads `ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.6.1.tar.gz` and does a `./configure` and `gmake`.

**Comment by DennisHeimbigner** [comment]
Yes, the .dds extension is automatically added. 
This appears to be fixed in the github master.
It might also be fixed in the latest 4.6.2 release candidate.
