### ISSUE TITLE
./configure fails on hdf5 library (on OpenBSD-current)

### ISSUE THREAD

**Issue by mvhulten** [Unidata/netcdf-c#1216]
### Environment Information

* Platform: amd64 OpenBSD
* Build system: GNU build system (Autotools)

### Summary of Issue

I try to build netCDF 4.6.1, but it fails during configure with the message

```
checking for library containing H5Fflush... no
configure: error: Can't find or link to the hdf5 library. Use --disable-netcdf-4, or see config.log for errors.
```

The [config.log](https://github.com/Unidata/netcdf-c/files/2595325/config.log) shows an issue with curl as well as hdf5, but both hdf5 1.8.20 and curl 7.62.0 are installed (under `/usr/local/`).

**Comment by edhartnett** [comment]
Are you setting CPPFLAGS and LDFLAGS with the locations of the libraries?

Can you try with current master?

I recently fixed these issues, I believe. 

A workaround for old releases is to add the missing library information to CPPFLAGS, LDFLAGS, and LIBS, before running configure.

**Comment by t-b** [comment]
I suceeded in compiling it on debian stretch with

```
CFLAGS="`pkg-config --cflags hdf5`" LDFLAGS="`pkg-config --libs-only-L hdf5`" ./configure
```

but unfortunately my autotools foo is way to low to make a PR so that configure itself looks for pkg-config values.

**Comment by edwardhartnett** [comment]
I believe this issue should be closed.

**Comment by mvhulten** [comment]
I tried to configure netcdf-c-4.7.3 with CPPFLAGS and LDFLAGS set.  I got the same errors.  Here is the [config.log](https://github.com/Unidata/netcdf-c/files/4190781/config.log).

`pkg-config` doesn't return any path.
