### ISSUE TITLE
License Update

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#1226]
The documentation to update the license to the BSD 3-clause license needs to be put in place for the next release.

**Comment by WardF** [comment]
Testing this with a comment.

**Comment by WardF** [comment]
This space intentionally left blank.

**Comment by DennisHeimbigner** [comment]
What does this entail? Much of the code has been modified to refer to the
license file, but there are probably some files that have the old license
embedded in the file.

**Comment by WardF** [comment]
I'll be modifying the top-level license file and also modifying any embedded license instances to refer to the top-level license file.
