### ISSUE TITLE
Can libdispatch/u subdirectory be removed?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1235]
Under libdispatch we have a sub directory called "u":

 ```
 /home/ed/tmp/netcdf-c/libdispatch/u:
  total used in directory 80 available 53602068
  drwxrwxr-x 2 ed ed  4096 Nov 12 07:36 .
  drwxrwxr-x 4 ed ed 12288 Dec  3 04:23 ..
  -rw-rw-r-- 1 ed ed 29959 Nov 12 07:36 utf8proc.c
  -rw-rw-r-- 1 ed ed 29500 Nov 12 07:36 utf8proc.h
```
It is not used in the build.

Can this directory and contents be removed?

**Comment by WardF** [comment]
@DennisHeimbigner I believe this is something you created; any reason not to remove it?

**Comment by DennisHeimbigner** [comment]
These were I think the old versions of utf8proc. They can be removed.

**Comment by WardF** [comment]
I'll roll this into the next pull request I process whatever it may be. Thanks Dennis!
