### ISSUE TITLE
netcdf lib open in memory question

### ISSUE THREAD

**Issue by MisterRaindrop** [Unidata/netcdf-c#1251]
The nc file is on a private cloud. I am now reading with nc_open_mem. But the nc file is too big. Is there a similar "fread" way to read, one-time cache to memory is too expensive.
The current implementation does not recommend downloading this method locally.
Or is there another way?

**Comment by DennisHeimbigner** [comment]
Not sure  I understand the question. The normal nc_open of course reads from disk.
The nc_open_mem is designed purely for when the dataset is completely in memory.
Can you elaborate on what workflow you are trying to achieve?

**Comment by MisterRaindrop** [comment]
supplement: Amazon s3 object store.

**Comment by MisterRaindrop** [comment]
Is it possible, for example, the header of an nc file is assumed to be 1k in size. I only download files of 1k size, can I parse out what subdataset ID I want?

**Comment by MisterRaindrop** [comment]
Is it possible that netcdf rewrites the underlying read and seek. Read directly to the Amazon S3 object store. Can I change this? If I want to change how to change?

**Comment by DennisHeimbigner** [comment]
I ran across this as a possibility.
https://github.com/s3fs-fuse/s3fs-fuse

**Comment by MisterRaindrop** [comment]
Yes, each file is stored as a single file in s3. And there may be thousands of these files. Since my program may be deployed to an S3 server, I will access the s3 object store via the internal network very quickly. It is estimated that it can be put at 100M/s. Large Chengdu depends on network bandwidth.

**Comment by MisterRaindrop** [comment]
The file format is mostly netcdf-3, but there may be netcdf-4

**Comment by MisterRaindrop** [comment]
Maybe doing byte range reads from S3 to be very slowly.  But, if you have thousands of files in s3. if you want list these files information. how to do it ?

**Comment by DennisHeimbigner** [comment]
I think s3fs_fuse is your only hope in the short run.

**Comment by MisterRaindrop** [comment]
I think so.  Do you have any plans to do something at s3? in the future

**Comment by DennisHeimbigner** [comment]
Yes, but it is along the lines of providing a netcdf interface to the Zarr system.

**Comment by MisterRaindrop** [comment]
Zarr ?  Python package?

**Comment by DennisHeimbigner** [comment]
The version 2 spec.
https://zarr.readthedocs.io/en/stable/spec/v2.html

But this won't do you any good because you need to access already netcdf
formatted data that just happens to be stored in the cloud.

**Comment by DennisHeimbigner** [comment]
I was looking at this. Since the goal is only to read the contents of an object
(via byte ranges), implementing this in the netcdf-c library might not be too
difficult.
I have some questions. First, are the s3 netcdf files you are reading publically
accessible? If so, then could you send me the object urls for a netcdf-3 object
and for a netcdf-4 object?

**Comment by MisterRaindrop** [comment]
I only have one sample on the s3 object store. Now S3 I set it to public. However, when it is actually used, it may be private. I should now set the bucket to read and write permissions. You can test it above.
url: https://s3-us-west-1.amazonaws.com/test-sample-netcdf/input.nc

**Comment by MisterRaindrop** [comment]
You can try the test, if the S3 has a problem, just tell me.

**Comment by MisterRaindrop** [comment]
How to build a debug version. Use configure？

**Comment by DennisHeimbigner** [comment]
I have an experimental version of the netcdf-c library capable
of accessing remote datasets using the HTTP byte-range mechanism.
This should address your problem since the S3 objects you have
support byte-range access.
WARNING: this is pretty slow.

**Comment by DennisHeimbigner** [comment]
I am just using, for example, the URL you gave me. I do not know which
network is implied by that.

**Comment by MisterRaindrop** [comment]
Sorry. If you want to run, you must go to the Amazon cloud to start a machine. This way your program will be on the internal network on the Amazon cloud. Or you might want to vpn specifically link to the Amazon cloud. Otherwise you are so slow to access the network directly.

**Comment by MisterRaindrop** [comment]
You'd better be able to deploy the program to Amazon EC2. But currently I don't have an EC2 machine right now.

**Comment by MisterRaindrop** [comment]
Amazon Elastic Compute Cloud (Amazon EC2)

**Comment by DennisHeimbigner** [comment]
I see what you mean.  We do not have any EC2 instances to use, but
it would be interesting to do a performance comparison.

**Comment by MisterRaindrop** [comment]
you may try it
