### ISSUE TITLE
Cmake build failing for non-netcdf-4 builds

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1253]
On the current master, disable-netcdf-4 builds are failing on cmake for me with the following:

`cmake -DBUILD_SHARED_LIBS=ON -DENABLE_NETCDF_4=OFF -DHDF5_C_LIBRARY=/usr/local_cmake/lib/libhdf5.so -DHDF5_HL_LIBRARY=/usr/local_cmake/lib/libhdf5_hl.so -DHDF5_INCLUDE_DIR=/usr/local_cmake/include -DCMAKE_PREFIX_PATH=/usr/local_cmake/ ..
`
leads to:

```
[ 20%] Built target netcdf3
Scanning dependencies of target misc
[ 20%] Building C object plugins/CMakeFiles/misc.dir/H5Zmisc.c.o
/var/lib/jenkins/workspace/WDC_cmake_shared_no_netcdf4/plugins/H5Zmisc.c:6:10: fatal error: hdf5.h: No such file or directory
 #include <hdf5.h>
          ^~~~~~~~
compilation terminated.
plugins/CMakeFiles/misc.dir/build.make:62: recipe for target 'plugins/CMakeFiles/misc.dir/H5Zmisc.c.o' failed
make[2]: *** [plugins/CMakeFiles/misc.dir/H5Zmisc.c.o] Error 1
CMakeFiles/Makefile2:1310: recipe for target 'plugins/CMakeFiles/misc.dir/all' failed
make[1]: *** [plugins/CMakeFiles/misc.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by DennisHeimbigner** [comment]
I think there is a cmake flag that can be set to force cmake to show its compilation
commands. We need to look at the compilation for H5Zmisc.c and see what -I flags
are specified.

**Comment by gsjaardema** [comment]
`make VERBOSE=1`

**Comment by DennisHeimbigner** [comment]
This means that for some reason, this line in the top-level CMakeLists.txt
is not being evaluated properly
> IF(ENABLE_FILTER_TESTING AND NOT ENABLE_NETCDF_4)
or the ENABLE_FILTER_TESTING conditional in plugins/CMakeLists.txt
is not being evaluated properly.

**Comment by DennisHeimbigner** [comment]
ok, apprently the problem is the use of CACHE in the SET().
The lines like this:
    SET(ENABLE_FILTER_TESTING OFF CACHE BOOL "")
need to be changed to this:
    SET(ENABLE_FILTER_TESTING OFF)

**Comment by WardF** [comment]
Good catch, I'll sort/fix this in an upcoming PR. Thanks!

**Comment by WardF** [comment]
Fixed
