### ISSUE TITLE
Query HDF5 library version

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#1254]
Is there a way to query the version of the HDF5 library that a NetCDF library has been linked with either at runtime, or via a symbol in an include file?

I have a function which prints the configuration of the Exodus and NetCDF library which gives something like:
```
Exodus Configuration Information:
	Exodus Version 7.17
	Exodus Parallel NOT enabled
	Exodus Thread Safe NOT enabled
	Exodus Deprecated Functions Available

	NetCDF Version 4.6.3-development
	Using NetCDF with HDF5 enabled
	Using NetCDF with CDF5 support
	Using NetCDF with ERANGE_FILL support
	Using NetCDF with RELAX_COORD_BOUND defined
	Using NetCDF with NC_HAVE_META_H defined
```
I think it would also be useful to output the HDF5 library version, but didn't now whether I had to get it from the HDF5 config information, or whether NetCDF "knows" it and can regurgitate it. 

Probably similar question about PNetCDF (if using)

**Comment by WardF** [comment]
The version is printed in the provenance information, so it must be available, although I don’t know off the top of my head.  I’ll look it up when I’m back from AGU or in front of my laptop, unless @DennisHeimbigner knows off the top of his head. Thanks!

**Comment by DennisHeimbigner** [comment]
The provenance property, _NCProperties, get the HDF5 lib version using the funtion
H5get_libversion(major,minor,release)

**Comment by WardF** [comment]
@gsjaardema I assume this answers the question so I’ll close this out. Thanks @dennisheimbigner !

**Comment by gsjaardema** [comment]
Thanks.
