### ISSUE TITLE
Big endian test failures on QEMU MIPS

### ISSUE THREAD

**Issue by t-b** [Unidata/netcdf-c#1278]
### Environment Information

* What platform are you using? (please provide specific distribution/version in summary)
  * [ ] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [x] QEMU MIPS big-endian
* 32 and/or 64 bit?
  * [X] 32-bit
  * [ ] 64-bit
* What build system are you using?
  * [ ] autotools (`configure`)
  * [X] cmake

### Summary of Issue

```
The following tests FAILED:
         59 - nc_test (Timeout)
         65 - nc_test4_tst_filter (Failed)
         71 - nc_test4_tst_files4 (Timeout)
        125 - nc_test4_tst_filterparser (Failed)
        158 - ncdap_tst_ncdap3 (Failed)
        159 - ncdap_t_dap3a (Failed)
        160 - ncdap_test_cvt (Failed)
        161 - ncdap_test_vara (Failed)
        162 - ncdap_tst_ber (Failed)
        163 - ncdap_tst_remote3 (Failed)
        164 - ncdap_tst_fillmismatch (Failed)
        165 - ncdap_test_varm3 (Failed)
        166 - dap4_test_test
```

The timeouts are due to the slow CPU I guess.

### Steps to reproduce the behavior
- Create QEMU MIPS image as described in https://github.com/t-b/debian-mips-qemu
- `mkdir build`
- `cd build`
- `cmake ..`
- `make` (take a long nap, go for a walk, etc)
- `ctest --timeout 600 .`

**Comment by WardF** [comment]
Thanks! Looking at building the debians-mips-qemu image now.

**Comment by WardF** [comment]
Setting up to duplicate your tests, although as you note it takes quite a long time.  Do you know offhand if the error occurs when using autoconf-based builds as well?

**Comment by WardF** [comment]
Thanks; we are still looking at debugging this.  We are also looking for Big Endian hardware solutions which should speed up the development/debugging cycle.

**Comment by DennisHeimbigner** [comment]
I am in the process of trying to fix these using the qemu emulation.,
I have some of the true failures (as opposed to timeouts) fixed,
and hope to have all of them fixed soon.

**Comment by t-b** [comment]
@DennisHeimbigner @WardF Nice to hear that the QEMU image is of use. I'm happy also review the fix PR.

@WardF Regarding speeding it up, QEMU supports also S390x (aka IBM Z-Systems) and debian supports that as well, and that should be, thanks to KVM, much faster as the MIPS thingie. See also https://wiki.qemu.org/Documentation/Platforms/S390X.

**Comment by DennisHeimbigner** [comment]
I think I have fixed the big-endian errors. See PR https://github.com/Unidata/netcdf-c/pull/1302
