### ISSUE TITLE
ABI tracker for netcdf-c

### ISSUE THREAD

**Issue by aponomarenko** [Unidata/netcdf-c#129]
Hello,

I'm the maintainer of the non-official page for tracking API/ABI changes in the netcdf library: http://upstream-tracker.org/versions/netcdf.html

It would be great if you can setup the local instance of the ABI tracker for the netcdf library and share reports for the Linux community in order to help updating your library in the Linux distributions.

The source code of the tracker is available here: https://github.com/lvc

I've created reports for several latest versions of the library to simplify setup of the tracker: http://abi-laboratory.pro/files/netcdf-c-abi-tracker.tar.gz

I'll redirect the page for netcdf at upstream-tracker.org to your site if you'll decide to host and support the tracker.

Thank you.

![netcdf-c-abi-tracker](https://cloud.githubusercontent.com/assets/1382645/10119915/d0887bb4-64ad-11e5-8606-81e41cd5a32e.jpg)

**Comment by WardF** [comment]
While this looks interesting, we are a bit resource constrained at the moment and won't be able to add this.  It might be useful to help us maintain our 100% backwards compatibility commitment to our community.  I'm going to tag this appropriately and close it, but revisit it when we have the resources to do so.
