### ISSUE TITLE
Fix cmake module path when included as subdir

### ISSUE THREAD

**Issue by Jerry-Ma** [Unidata/netcdf-c#1295]
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### Environment Information

* What build system are you using?
  * [ ] autotools (`configure`)
  * [x] cmake

### Summary of Issue

When including the source via `add_subdirectory(netcdf-c)`, the configuration fails because the script is unable to locate the custom cmake modules in netcdf-c/cmake/modules, e.g, MakeDistConfig.cmake.

The problem is due to that in line 85 of netcdf-c/CMakeLists.txt, it mistakenly uses ${CMAKE_SOURCE_DIR} as the base directory to the module, which, when netcdf-c is included as subdirectory, refers to the root source dir.

### Suggested Fix

Use ${CMAKE_CURRENT_SOURCE_DIR} instead.

**Comment by WardF** [comment]
Thanks for the report, I'll roll this in with the next group of fixes.

**Comment by Jerry-Ma** [comment]
Well, after some more digging, it seems that there are several places that used CMAKE_SOURCE_DIR where it may actually need CMAKE_CURRENT_SOURCE_DIR (the same for CMAKE_BINARY_DIR).

For my case, I just did a mass find/replace, and I have not carefully check the result yet, as I am having some other issues with configuring and using a custom build of hdf5 added as subdir alongside netcdf-c.

I'll post updates if I can make it work on my machine.

**Comment by WardF** [comment]
Sounds good, thanks. I'll open a PR with my initial change and update it as need be.

**Comment by WardF** [comment]
We do need to test carefully, as there are a few places where `CMAKE_SOURCE_DIR` was used specifically to refer to the top-level source directory from within a subdirectory, so we can't just do a project-wide search and replace.  I have no doubt that there are further instances of the issue you've encountered, however.

**Comment by DennisHeimbigner** [comment]
>CMAKE_SOURCE_DIR where it may actually need CMAKE_CURRENT_SOURCE_DIR
> (the same for CMAKE_BINARY_DIR).
I may be guilty of this. What is the intended semantic difference between, say.,
CMAKE_SOURCE_DIR and CMAKE_CURRENT_SOURCE_DIR?
