### ISSUE TITLE
DAP Access of Zero-length Variable

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#1300]
As reported by Upanita Goswami at Mathworks, netCDF gives an error when accessing a dataset containing a zero-length variable.  The issue can be recreated with the current `master` development branch, and exists in netCDF-C `4.6.2`.  Recreating the issue with `ncdump` is easy, as shown below:

    $ ncdump http://test.opendap.org/opendap/data/nc/zero_length_array.nc

This command prints out the metadata, and then the following is observed:

````
data:

dim->dim.declsize0 > 0

Assertion failed: (dappanic("dim->dim.declsize0 > 0")), function dapvar2projection, file /Users/wfisher/Desktop/gitprojects/netcdf-c/libdap2/constraints.c, line 720.
 lat = 

Abort trap: 6 (core dumped)
````

@DennisHeimbigner is this expected behavior?  It looks like DAP is explicitly checking for zero-length variables, is this prohibited? If so, is there documentation to that effect somewhere? I will look for it myself shortly as well.

**Comment by DennisHeimbigner** [comment]
I figured out the problem. There was a place where I forgot to see
if the variable was invisible (had a zero dimension). It is a one-line fix.

**Comment by WardF** [comment]
Looks good Dennis, I'm adding a test for zero-length variables such as caused this issue and then will merge in. Thanks!
