### ISSUE TITLE
rename bug - varids change order after rename

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1307]
When we rename a var it changes the creation order of that dataset in the HDF5 file. The next time the file is read, the renamed var will show up last (i.e. have the largest varid) even if it was not the last var before the rename.

For my rename fixes to work, I need varids to stay the same after a rename. The answer is simply to also rename all the vars with varid > the varid of the renamed var. For these vars I first rename them to a temporary name, then back to their actual name. This resets their creation time as well, and thus all vars remain in the correct order.

Part of #597.

I have a PR with a fix which I will put up shortly.

**Comment by DennisHeimbigner** [comment]
I am surprised that in the voluminous HDF5 API, there is no way to set the creation time :-)
