### ISSUE TITLE
Parallel compression enabled in HDF5-1.10.2 and later

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#1315]
As of HDF5-1.10.2, compression is possible in both serial and parallel.  See https://portal.hdfgroup.org/display/support/HDF5%201.10.2#releasenotes.  

This is not yet supported in NetCDF and if NetCDF detects that the file is parallel, it will return from `nc_def_var_deflate` with an `NC_EINVAL` return code (hdf5var.c)
```
   /* Can't turn on parallel and deflate/fletcher32/szip/shuffle. */
   if (h5->parallel == NC_TRUE)
      if (deflate || fletcher32 || shuffle)
         return NC_EINVAL;
```

I would create a PR to enable this in NetCDF, but not sure what is the best method to test for it and what variable to set.

**Comment by gsjaardema** [comment]
Sorry, hit the wrong button before filling in the issue text.  Should have some content now...

**Comment by edhartnett** [comment]
Thanks for bringing this to my attention! I will take a look...

**Comment by gsjaardema** [comment]
The parallel compression is not yet as good as the serial compression; perhaps chunk sizes need to be adjusted or some other tweaking, but it does work.  Here is some very quick data:

| Processors | Compress | File Size       |
|-------------|-----------|-------------:|
|       2           |      no         | 233843228  |
|       2           |    yes         |    26216298  |
|       1           |     yes        |      1944296  |
|       8          |      yes       |     26216302 |
|       1           |     no         |  209636290 |

**Comment by edhartnett** [comment]
First question: is there a compile-time test we can run to find out if this is enabled in the HDF5 library?

**Comment by gsjaardema** [comment]
Not that I could see.  As best I could tell, it can only be determined by testing the version >= 1.10.2 which isn't the best.

**Comment by DennisHeimbigner** [comment]
I am not sure I understand what a parallel filter is/does.
It is still the case that the only kind of parallelism we support
is IO parallelism using mpi. Multiple thread parallelism is still
not supported by netcdf-c. My naive assumption would be that
filter parallelism is based on multiple threads, not on mpi.

**Comment by DennisHeimbigner** [comment]
Probably the simplest way to enable this is to just allow the user to add
a ./configure flag to control this, independent of any version of HDF5.
Since it would normally be disabled, any error in using this flag
is on the builder.
Proposal: add ./configure flag --enable-parallel-filters

**Comment by gsjaardema** [comment]
The filter parallelism is the IO parallelism using mpi.
```
- Enabled compression for parallel applications. 
      With this release parallel applications can create and write compressed
      datasets (or the datasets with the filters such as Fletcher32 applied).
      (EIP - 2018/03/29)
```

**Comment by DennisHeimbigner** [comment]
I see, so the filters themselves are not run in parallel.
So correction:
 Proposal: add ./configure flag --enable-mpio-filters

**Comment by edhartnett** [comment]
We always want to enable where present. THis will be a popular feature.

**Comment by DennisHeimbigner** [comment]
I see four choices to detect:
1. hdf5 version
2. a ./configure AC_COMPILE_IFELSE, assuming the lack of the feature can be
    detected at compile time
3. presence/absence of some HDF5 definition (a macro or function) -- currently no
   such definition appears to exist.
3. a forcing ./configure flag like --enable-mpio-filters

**Comment by edhartnett** [comment]
Checking the HDF5 version is less than ideal, but will get the job done. Looks to me like there will be no new function to check for.

**Comment by DennisHeimbigner** [comment]
I may have spoken too soon. It looks like there is a flag
 H5D_MPIO_PARALLEL_FILTERED_WRITES_DISABLED
in H5Ppublic.h. Not sure if it is intended to be public or not
(despite the name of the file).
It is defined in 1.10.3 and 1.10.4, but is not defined in 1.10.1 or 1.10.2.
So it misses 1.10.2. But still might be adequate.
Someone might double check this.

**Comment by gsjaardema** [comment]
I have a message to the HDF5 forum asking for guidance on whether there is a feature test that is recommended.  Will update here if and when I hear anything.

**Comment by gsjaardema** [comment]
Looks like @DennisHeimbigner was on the right track...   

Here is response from HDF forum (https://forum.hdfgroup.org/t/parallel-compression-support-detection/5398)

> bljones
> The HDF Group Staff
>
> You should be able to look at the libhdf5.settings file in the lib/ directory of your HDF5 installation  to determine whether parallel compression was enabled or not.
>
> There is a feature called “Parallel Filtered Dataset Writes” in the libhdf5.settings file which may indicate parallel compression, but it is not clear. I entered bug HDFFV-10702 to add/improve the information in the libhdf5.settings file with regards to parallel compression. We will add this to the upcoming HDF5-1.10.5 release.
>
> -Barbara

**Comment by DennisHeimbigner** [comment]
I do not think we have used libhdf5.settings before to look for features of hdf5, so
we may need to provide some automake and cmake support code.

**Comment by edhartnett** [comment]
I just looked at the libhdf5.settings file and it's pretty rough. I wonder if there is some equivalent to nc-config?

I will look around and see how this can be tested in a compile, if possible...

**Comment by gsjaardema** [comment]
Here is an excerpt of the HDF5 check that sets the parallel filtered dataset writes.  It is inside a block where they know it is parallel:
```
  ## ----------------------------------------------------------------------
  ## Check for the MPI-3 functions necessary for the Parallel Compression
  ## feature. If these are not present, issue a warning that Parallel
  ## Compression will be disabled.
  ##
  AC_MSG_CHECKING([for MPI_Mprobe and MPI_Imrecv functions])

  AC_LINK_IFELSE(
      [AC_LANG_PROGRAM(
          [[
              #include <mpi.h>
          ]],
          [[
              MPI_Message message;
              MPI_Init(0, (void *) 0);
              MPI_Mprobe(0, 0, 0, &message, (void *) 0);
              MPI_Imrecv((void *) 0, 0, 0, (void *) 0, (void *) 0);
          ]]
      )],
      [AC_MSG_RESULT([yes])
       PARALLEL_FILTERED_WRITES=yes],
      [AC_MSG_RESULT([no])
       AC_MSG_WARN([A simple MPI program using the MPI_Mprobe and MPI_Imrecv functions could not be compiled and linked.
                    Parallel writes of filtered data will be disabled.])
       PARALLEL_FILTERED_WRITES=no]
  )
```
Basically, it looks like they enable it if they have an MPI-3 system which `MPI_Mprobe` and `MPI_Imrecv` functions.

**Comment by jswhit** [comment]
Does the issue being discussed here only affect parallel writes?  Should parallel reads of compressed data work 'out of the box' with HDF5 >= 1.10.2?

**Comment by edwardhartnett** [comment]
This is part of #1545 

Elena has promised me some help doing this after the AGU/AMS madness is over.

**Comment by edwardhartnett** [comment]
This work has been completed and merged to master. This issue should be closed.

**Comment by edwardhartnett** [comment]
This issue should be closed. Parallel read/writes with zlib have been working for some time now...
