### ISSUE TITLE
Create third project to install both C and Fortran libraries...

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1325]
I see some mention of adding a way to install the netcdf-fortran library at the same time the netcdf-c library in installed.

This is cumbersome and not the way autoconf/automake want us to proceed.

Instead we make a third project, very lightweight, which launches first the C library install, then the Fortran library install. Doing a 'make dist' on this third project will create a tarball with both the C and Fortran libraries, and they will be installed in one operation, with ./configure --prefix=/somewhere && make install.

The advantage of this approach is that neither the C nor FORTRAN libraries have to know about the other.

I have recently done this for the GPTL C/Fortran libraries. (https://github.com/NOAA-GSD/GPTL-all). As you can see, this third project does almost nothing. The configure.ac is only about 35 lines of code. It simply launches the C and then Fortran builds.

I would be happy to do one for the netCDF C/Fortran libraries. Any interest?

**Comment by edhartnett** [comment]
Incidedntly, the technique using git submodues of creating that third library, which includes both C and Fortran libraries, is fully described in this AMS paper: https://ams.confex.com/ams/2019Annual/meetingapp.cgi/Paper/350095

**Comment by WardF** [comment]
I’ll take a look at this but we are pretty saturated project wise here. This may be something we revisit in the future but based on support questions, the current system is sufficient. I’ll take this for future review when we get some slack :)
