### ISSUE TITLE
SONAME bump for 4.4.0-rc5 to account for removed symbols

### ISSUE THREAD

**Issue by sebastic** [Unidata/netcdf-c#133]
Despite 4.4.0 still being in RC stage, it uses the same SOVERSION as 4.3.3.1 and some earlier releases.

In RC3 three symbols were removed (nc_exit, num_plists & num_spaces), this breaks the ABI and requires a SONAME bump.

It looks like you're trying to keep the Automake & CMake builds in sync by adopting the libtool versioning for the library build with CMake too.

With that in mind I think the following changes are appropriate for the SONAME bump, but I very much appreciate a second opinion due to my unfamiliarity with netcdf-c development.
```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -30,8 +30,8 @@ SET(NC_VERSION_NOTE "-rc3")
 SET(netCDF_VERSION ${NC_VERSION_MAJOR}.${NC_VERSION_MINOR}.${NC_VERSION_PATCH}${NC_VERSION_NOTE})
 SET(VERSION ${netCDF_VERSION})
 SET(NC_VERSION ${netCDF_VERSION})
-SET(netCDF_LIB_VERSION 7.3.0)
-SET(netCDF_SO_VERSION 7)
+SET(netCDF_LIB_VERSION 11.0.0)
+SET(netCDF_SO_VERSION 11)
 SET(PACKAGE_VERSION ${VERSION})
 
 # Get system configuration, Use it to determine osname, os release, cpu. These
--- a/liblib/Makefile.am
+++ b/liblib/Makefile.am
@@ -19,7 +19,7 @@ lib_LTLIBRARIES = libnetcdf.la
 # for information regarding incrementing `-version-info`.
 ##
 
-libnetcdf_la_LDFLAGS = -version-info 10:0:3
+libnetcdf_la_LDFLAGS = -version-info 11:0:0
 
 libnetcdf_la_CPPFLAGS = ${AM_CPPFLAGS}
 libnetcdf_la_LIBADD =
```

**Comment by sebastic** [comment]
Since the removed symbols were introduced in the earlier 4.4.0 RCs, bumping the SONAME for their removal may not be required.

**Comment by sebastic** [comment]
Reopening this issue, because RC4 removes a lot of symbols introduced before 4.4.0, as documented in this commit to the Debian package symbols file:
https://anonscm.debian.org/cgit/pkg-grass/netcdf.git/commit/?id=d37390c5f31a76e14f8fb77ef78f1f13ae18c8e5

Unless RC5 reverts the removal of these pre-4.4.0 symbols, a SONAME bump is required before the final 4.4.0 release.

**Comment by DennisHeimbigner** [comment]
I do not follow. If I read that debian report right, then no changes to netcdf.h occurred,
so there should be no effect on the externally accessible interface, hence no soname bump is required. 
Can you clarify why you think the soname should be bumped?

**Comment by sebastic** [comment]
The symbols represent the externally accessible interface, and many of the symbols were removed.

To quote the [libtool manual](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html):
> Here are a set of rules to help you update your library version information:
> 
>  1. Start with version information of ‘0:0:0’ for each libtool library.
>  2.  Update the version information only immediately before a public release of your software. More frequent updates are unnecessary, and only guarantee that the current interface number gets larger faster.
>  3. If the library source code has changed at all since the last update, then increment revision (‘c:r:a’ becomes ‘c:r+1:a’).
>  4. If any interfaces have been added, removed, or changed since the last update, increment current, and set revision to 0.
>  5. If any interfaces have been added since the last public release, then increment age.
>  6. If any interfaces have been removed or changed since the last public release, then set age to 0. 

Rules 4 & 6 apply, so the libtool version-info must be updated from 10:0:3 to 11:0:0.

All programs that use any of the removed symbols must be recompiled, or they will segfault with undefined references to the removed symbols.

The three symbols removed in RC3 were introduced in earlier 4.4.0 RCs, and not used by any programs yet, so for that update we could do without a SONAME bump. In RC4 many older symbols were removed that will break programs linked against libnetcdf7, [VTK](http://www.vtk.org/) for example uses NC_initialize (introduced in netcdf 4.1.3), but this symbol is no longer available in RC4. For VTK this case from the libtool manual applies:
>  Programs may need to be changed, recompiled, and relinked in order to use the new version. Bump current, set revision and age to 0.

Another example is nc_cktype, this symbols used by VTK & [ParaView](http://www.paraview.org/), but no longer available in netcdf 4.4.0 RC4.

**Comment by WardF** [comment]
I had to refer back to my notes on this.  I see that I referred to the guidelines found at http://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html; this is the same link you referenced. The second item in the list is (as you quote above):

> 1. ...
> 2. Update the version information only immediately before a public release of your software. More frequent updates are unnecessary, and only guarantee that the current interface number gets larger faster. 

At the time, I think I interpreted 'public release' as a full release and not a release candidate; I am now reconsidering that conclusion upon a second reading.  It has certainly been my intention to increment the `.so` version with the (long awaited) full release.

Sorry for the delayed response to this issue; I'm not going to go back and update the existing release candidate, and I'm a bit fatigued with releasing (I've done two RC in the past 2 days) so I'm not inclined to create an RC6 at this point to solve a hypothetical problem :).  I'll bump the .so with the full release, and I will reconsider the process I've adopted over the last year or so of only bumping so version with full releases.

**Comment by DennisHeimbigner** [comment]
You have to be careful here. Since C does not provide namespaces, we have to use naming conventions to achieve the same effect. For example, nc_cktype was used internally inside the netcdf-c library, but is not and has never been (AFAIK) part of netcdf.h. It is purely an internal function. If e.g. paraview was using it, then that is a mistake on their part. If they needed it be be officially part of the API, then they should have made a request to us for that functionality and we could work with them on it.
In looking at the actual code, nc_cktype was renamed to nc3_cktype for exactly this reason; it only was used for internal netcdf-3 code (i.e. in libsrc) and the nc3_ was used to emphasize its limited "namespace".
I note that there were some changes to netcdf.h with respect to some flags (see current release notes) and those changes may justify the soname bump.

**Comment by opoplawski** [comment]
Some thoughts:
- Private internal symbols should not be exported in the first place (hidden via symbol-visibility)
- I would suggest doing a soname bump in a late RC.  You might surprised at how many times I've seen this step done incorrectly.
- Fedora's abipkgdiff report between 4.3.3.1 and 4.4.0-rc5: http://www.cora.nwra.com/~orion/netcdf-4.4-abipkgdiff.txt

**Comment by WardF** [comment]
Making this bump now, as we're about to (finally) release 4.4.0.  Closing this out, will reopen if there's a problem
