### ISSUE TITLE
ModuleNotFoundError: No module named 'set_globattr' error 

### ISSUE THREAD

**Issue by mada0007** [Unidata/netcdf-c#1331]
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### conda environment 

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  *
  * [ ] OSX

* 32 and/or 64 bit?
  *
  * [ ] 64-bit

from icclim import icclim

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-620e0b25f313> in <module>
----> 1 from icclim import icclim

~/anaconda3/lib/python3.6/site-packages/icclim-4.2.11-py3.6.egg/icclim/icclim.py in <module>
     19 from netCDF4 import Dataset, MFDataset
     20 
---> 21 import set_globattr
     22 import set_longname_units
     23 import set_longname_units_custom_indices

ModuleNotFoundError: No module named 'set_globattr

install icclim using conda install icclim
run from icclim import icclim and then this error from netcdf pops up

**Comment by dopplershift** [comment]
That error message is coming from `icclim.py`, and it’s trying to import its own `set_globattr` module. This is a problem with your install of icclim, the import of the `netCDF4` module (and even then netCDF4-python, not the C library) appears to work fine. You should probably open an issue on the [icclim issue tracker](https://github.com/cerfacs-globc/icclim/issues).
