### ISSUE TITLE
Retrieving backslash character in strings from Opendap

### ISSUE THREAD

**Issue by ggalibert** [Unidata/netcdf-c#134]
(Not really sure where this issue is relevant, might be related to https://github.com/Unidata/oc)

See this netcdf file on our THREDDS : http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/demos/ANMN/SA/catalog.html?dataset=eMII/demos/ANMN/SA/IMOS_ANMN-SA_BCEFOPSTU_20080213T235500Z_SAM2CP_FV01_CTD-Profile_C-20150807T130052Z.nc

Note that if you click on opendap and look at the global attributes, the first one goes

```toolbox_input_file: T:\DATA\SAIMOS\Processed_CTD_IMOS\2008_02\CNV_Unbinned\b4cafld.cnv```

We can see that the backlashes in the path are well rendered.

Now let's download the file via http and do

```ncdump -h IMOS_ANMN-SA_BCEFOPSTU_20080213T235500Z_SAM2CP_FV01_CTD-Profile_C-20150807T130052Z.nc | grep input```

you get

```        :toolbox_input_file = "T:\\DATA\\SAIMOS\\Processed_CTD_IMOS\\2008_02\\CNV_Unbinned\\b4cafld.cnv" ;```

I'm guessing this is consistent with the practice which recommends escaping the characters " or \ to be able to use them. The DAP2 spec section 7.2.1.1 says “If the value contains a double quote, that MUST be escaped using the backslash (\) character. The backslash character is represented as backslash-backslash (\\).”

Now let's do the same ncdump on the opendap url

```ncdump -h http://thredds.aodn.org.au/thredds/dodsC/IMOS/eMII/demos/ANMN/SA/IMOS_ANMN-SA_BCEFOPSTU_20080213T235500Z_SAM2CP_FV01_CTD-Profile_C-20150807T130052Z.nc | grep input```

you get 

```        :toolbox_input_file = "T:DATASAIMOSProcessed_CTD_IMOS2008_02CNV_Unbinnedb4cafld.cnv" ;```

<b>The backslashes have disappeared!</b>

I did some other tests and from what I've seen :
-libdap 3.6.2 and above render backslashes successfully using getdap.
-ocapi http://www.opendap.org/ocapi 1.4.3 fails on backslashes.
-OC 1.0 renders backslashes successfully using octest.
-didn't manage to test OC 2.0 and I assume this is the API used by ncdump?

**Comment by DennisHeimbigner** [comment]
This removal is occurring in oc. I have the following note in the code:
 /* Remove spec ambiguity by convering \c to c for any character c */
I think this refers to section A.2 of the dap2 spec, which says:
The backslash character (”\”) MAY be used as a single-character quoting mechanism
only within quoted-string and comment constructs.
    quoted-pair    = "\" CHAR
The ambiguity is that it is not stated if the backslash is to be left in the string
or not. There is also an unstated, but related issue of what to do about e.g. '\n';
convert to newline or not.

**Comment by ggalibert** [comment]
Do you think the implementation of the same specification across different DAP API could be made consistent?

It looks like libdap and the API used in the OPeNDAP Dataset Access Form are resolving the ambiguity : http://thredds.aodn.org.au/thredds/dodsC/IMOS/eMII/demos/ANMN/SA/IMOS_ANMN-SA_BCEFOPSTU_20080213T235500Z_SAM2CP_FV01_CTD-Profile_C-20150807T130052Z.nc.html

This dataset has global attributes with the characters backslash \, new line and double quote " . While these characters are respectively found to be stored as follow : \\, \n and \" using ncdump, 

```
:toolbox_input_file = "T:\\DATA\\SAIMOS\\Processed_CTD_IMOS\\2008_02\\CNV_Unbinned\\b4cafld.cnv" ;
...
:quality_control_log = "imosSurfaceSoakQC(minSoakSec=60, optSoakSec=70) flagged 58 TEMP samples with flag Bad_Data.\nimosSurfaceSoakQC(minSoakSec=70, optSoakSec=90) flagged 70 CNDC samples with flag Bad_Data.\n
...
:citation = "The citation in a list of references is: \"IMOS [year-of-data-download], [Title], [data-access-URL], accessed [date-of-access].\"." ;
```

we can see that the OPeNDAP Dataset Access Form is displaying them as expected

```
toolbox_input_file: T:\DATA\SAIMOS\Processed_CTD_IMOS\2008_02\CNV_Unbinned\b4cafld.cnv
...
quality_control_log: imosSurfaceSoakQC(minSoakSec=60, optSoakSec=70) flagged 58 TEMP samples with flag Bad_Data.
imosSurfaceSoakQC(minSoakSec=70, optSoakSec=90) flagged 70 CNDC samples with flag Bad_Data.
...
citation: The citation in a list of references is: "IMOS [year-of-data-download], [Title], [data-access-URL], accessed [date-of-access].".
```

**Comment by DennisHeimbigner** [comment]
After consultation with Ward, we have added this change to the github master.
It will be available in the next release. If you want to get the change immediately,
then extract oc2/daplex.c and insert it into your local netcdf-c source directory.
