### ISSUE TITLE
[Branch v4.6.3-dev-branch.wif] nc_test4/test_filter crashes when linked against libhdf5 1.10.4 built with debugging enabled.

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#1344]
The test executable `test_filter` in the `nc_test4` directory crashes when the underlying `libhdf5` has been built with debugging turned on.  The specific failure occurs at `libhdf5/nc4hdf.c:1006`, in the call to `H5Dcreate2()`.  This function returns an error code.  

The same code works fine when linked against libhdf5 1.10.4 built without debugging enabled.

**Comment by WardF** [comment]
This crash is reproducible on both OSX and Ubuntu 18.04.

**Comment by edhartnett** [comment]
When you say debugging you mean the -g option?

**Comment by DennisHeimbigner** [comment]
I assume he means the --enable-build-mode=debug flag to  hdf5.
I ran the same config under Ubuntu 16.2 (with debug mode)  and it seems to work
ok for me.

**Comment by WardF** [comment]
Yes, as @DennisHeimbigner said; turning on debugging during `configure` via `--enable-build-mode=debug`.  Debug vs. No Debug is only one axis of inquiry at this point, as I did add some fenceposting for some hdf5 functions introduced in `1.8.15`.  I'd like to avoid bumping the minimum required version unless absolutely unnecessary.

I've also amended the title of the issue to specify the branch where this is happening.  It appears to have been introduced in the commit where I added the fenceposting. I feel like I'm overlooking some minor detail, so hopefully this will be easily fixed.

**Comment by WardF** [comment]
It seems to me the most obvious reason for the debug vs. no debug split boils down to compiler optimization; whatever bug was introduced/is occurring gets optimized out when debug info is turned off.   That is my current theory, at least.

**Comment by WardF** [comment]
To highlight one important detail initially left out: this is on branch `v4.6.3-dev-branch.wif`.

**Comment by WardF** [comment]
Ah, I believe I may have it.

**Comment by WardF** [comment]
@t-b yes, at cdash.unidata.ucar.edu

Thanks!
