### ISSUE TITLE
CMake requirement too high for RHEL & CentOS 7

### ISSUE THREAD

**Issue by marack** [Unidata/netcdf-c#135]
The CMake version required to build netcdf is currently set to 2.8.12.  This prevents use of the CMake build system on RHEL7 / CentOS7 which supply 2.8.11.

Downgrading the requirement manually reveals only a single incompatibility with 2.8.11.  This is found in liblib/CMakeLists.txt line 105:

    INSTALL(
      TARGETS netcdf EXPORT netCDFTargets
      LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
        COMPONENT libraries
      ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
        COMPONENT libraries
      RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
        COMPONENT libraries
      INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
      )

The `INCLUDES` destination here was introduced in CMake 2.8.12.  This could be worked around by using the older `PUBLIC_HEADER` destination instead.  (Or conditionally only for 2.8.11)

RHEL7 / CentOS 7 are near the beginning of life cycle and likely to grow in utilization as organizations port systems from RHEL/Centos 5 & 6.  For this reason it would be useful to maintain the CMake build support for these platforms.

Please see also the [CMake documentation on life cycle support](https://cmake.org/Wiki/CMake_Life_Cycle_Considerations).

**Comment by WardF** [comment]
I will take a pass at conditionally using the `PUBLIC_HEADER` destination for versions less than 2.8.12; while I want this to be as broadly usable as possible, we are resource constrained and the relative age of 2.8.11 *and* the presence of an alternative build system (autotools) already in place means I can't spend too long on this.  Alternatively, a pull request would be reviewed in short order :)

**Comment by WardF** [comment]
This issue has been addressed; cmake should be usable on systems with 2.8.11 now.
