### ISSUE TITLE
RELAX_COORD_BOUND broken?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1351]
No doubt this is my fault but relaxed coord bounds are broken in master.

@WardF you will certainly want to fix this before release. I will have a PR up in a moment.

**Comment by WardF** [comment]
I'm not observing any test failures in `master` with relaxed coord bounds turned on or off; can you expand on the failure you're seeing?

**Comment by edhartnett** [comment]
I am not sure if this is broken, when I look at it from the netcdf-c side, it seems to be working fine. But when PIO tries to use this, I get an EEDGE error where I would expect relaxed coord bounds to let me get through, and it is not. Quite possibly this is a PIO bug. I just didn't want you to release 4.6.3 the day after I found a bug, but didn't tell you. ;-)

**Comment by WardF** [comment]
Thanks! Also no worries; I released 4.6.3 on Friday, so barn door etc etc. can always shoot 4.6.4 out immediately if there’s a reason to

**Comment by edhartnett** [comment]
OK, I am starting to believe this is a PIO problem anyway. I will close this ticket and reopen if I find I was wrong.
