### ISSUE TITLE
4.6.3 provenance attribute reads incorrectly with older ncdump

### ISSUE THREAD

**Issue by Dave-Allured** [Unidata/netcdf-c#1352]
### Environment Information

Platform: 64-bit Linux
Build: autotools
Sample program:  From netcdf examples: `simple_xy_nc4_wr.f90`

### Summary of Issue

Generate a test netcdf-4 file using new release 4.6.3.  Ncdump from same build 4.6.3 reads the provenance attribute "as expected":
```
linux128:/data/dallured/test-suite/netcdf-examples 248> \
? /home/dmwork/Hoop/Trio_Builds/netcdf-c-4.6.3/NCC463/bin/ncdump |& grep version
netcdf library version 4.6.3 of Mar  4 2019 17:45:08 $
linux128:/data/dallured/test-suite/netcdf-examples 249> \
? /home/dmwork/Hoop/Trio_Builds/netcdf-c-4.6.3/NCC463/bin/ncdump -s simple_xy_nc4.nc \
?  | grep Properties
		:_NCProperties = "version=2,netcdf=4.6.3,hdf5=1.8.20" ;
```
Older ncdump 4.6.1 reads the provenance attribute strangely from the same file:
```
linux128:/data/dallured/test-suite/netcdf-examples 250> \
? /usr/local/bin/ncdump | & grep version
netcdf library version 4.6.1 of Oct 16 2018 08:23:18 $
linux128:/data/dallured/test-suite/netcdf-examples 251> \
? /usr/local/bin/ncdump -s simple_xy_nc4.nc | grep Properties
		:_NCProperties = "version=2|netcdf" ;
```
### Steps to reproduce the behavior

1.  Build and install netcdf-c 4.6.3 with current netcdf-fortran.

2.  LD_LIBRARY_PATH manipulation is needed in my case, because I have 4.6.3 installed in a special test path, but system default 4.6.1 installed in a "normal" system path.  Therefore, set LD_LIBRARY_PATH as needed to ensure linking with desired library version 4.6.3.

3.  With new 4.6.3 C library, compile and run example `simple_xy_nc4_wr.f90`.  Creates test output file `simple_xy_nc4.nc`.  The fortran compiler should not matter, but for the record it was gfortran 7.3.0.

4.  Run two versions of ncdump on same test file, as shown above.  Unset LD_LIBRARY_PATH when running older version.

### Complaint

Strange.  Is `_NCProperties` not stored as a simple `NC_CHAR` string attribute?  How can this happen?

**Comment by DennisHeimbigner** [comment]
Yes, _NCProperties should be typed NC_CHAR. Are you seeing something else?

As for the forward compatibilty issue, I am not sure what to do. Since it is by definition
a version of _NCProperties not known to the library, it is unclear what it should report.
Assuming there is eventually a version 3 at some point, we should come to some
decision about it to implement now.  My belief is that if given a version it does not
recognize, the library should report only the value of _NCProperties as an uninterpreted
string.

**Comment by Dave-Allured** [comment]
No, both versions of ncdump are implicitly displaying `_NCProperties` as type `NC_CHAR`.  The data type is not the problem, it is the apparent contents of the attribute as displayed.  I guess I did not explain this very well.

Two different versions of ncdump should display identically the contents of any simple `NC_CHAR` attribute within the same file.  If the attribute is stored this way inside netcdf-4, then there should be no forward/backward compatibility problems.  Ncdump versions all the way back to 4.0 should be able to display all forward versions of `_NCProperties` as long as this is always stored internally as a simple `NC_CHAR` string attribute.

But something else is happening.  Ncdump version 4.6.3 correctly displays this:
```
:_NCProperties = "version=2,netcdf=4.6.3,hdf5=1.10.5" ;
```
But ncdump version 4.6.1 displays something weird:
```
:_NCProperties = "version=2|netcdf" ;
```

**Comment by DennisHeimbigner** [comment]
Fair enough. The reason this happens is that internally _NCProperties is parsed
and when its value is requested, the value is reconstructed from the parsed form.
I think you are correct that the displayed value should in fact be the unparsed value.

**Comment by Dave-Allured** [comment]
That explains it.  Yes I agree, display the unparsed version in future releases.

**Comment by WardF** [comment]
+1 to the solution, or perhaps providing the unparsed version by default and provide a mechanism to provide the parsed version if need be?

**Comment by DennisHeimbigner** [comment]
Since we do not use the parsed version much, just caching it seems reasonable.
For files that do not have that property at all, I plan to return the empty string.

**Comment by Dave-Allured** [comment]
I checked a couple other ncdump versions with this same test file.  Here is a summary of displayed _NCProperties:
```
ncdump 4.3.0   "version=2,netcdf=4.6.3,hdf5=1.10.5"
ncdump 4.4.0   "version=2,netcdf=4.6.3,hdf5=1.10.5"
ncdump 4.6.1   "version=2|netcdf"
ncdump 4.6.3   "version=2,netcdf=4.6.3,hdf5=1.10.5"
```
It looks like 4.4.0 and earlier treat _NCProperties as an ordinary `char` attribute.  Therefore you see the original, unparsed provenance.  This is fortunate because the inability to display version 2 will be limited to only a few intermediate versions.

**Comment by WardF** [comment]
So this is good news, thanks for checking @Dave-Allured .  I'll leave this open until @DennisHeimbigner has his fix PR in, but it's nice to know that the issue only hits a small range of releases.

**Comment by Dave-Allured** [comment]
Here is a workaround for users who have only one version of ncdump (or netcdf library) available.  This will always display the unparsed attribute directly from the file, and should work with all modern versions of HDF5.
```
$ h5dump -a /_NCProperties simple_xy_nc4.nc | grep \"
```
Prints:
```
HDF5 "simple_xy_nc4.nc" {
ATTRIBUTE "_NCProperties" {
   (0): "version=2,netcdf=4.6.3,hdf5=1.10.5"
```
This does require that the user actually installed the HDF5 command tools, not just the libraries.

**Comment by DennisHeimbigner** [comment]
Good suggestion, thanks.
