### ISSUE TITLE
suggest moving performance and benchmarking tests to new directory nc_perf

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1359]
nc_test4 is getting very full and the build files pretty complicated.

A large chunk of the tests and build complexity have to do with the optional performance testing programs that get turned on with --enable-benchmarks.

I suggest that I create a new directory, nc_perf, and move all the benchmarking tests there. This will simplify nc_test4.

This should be a pretty simple task - if there are no objections I will put up a PR.

**Comment by WardF** [comment]
Sounds like a good idea, thanks!  I can't think of a reason not to offhand, unless @DennisHeimbigner has an objection I say go for it.
