### ISSUE TITLE
foreign copyright notice in netcdf code file

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1362]
I hate to bring up what can only be a dumb legal issue, but we have a file, examples/C/parallel_vara.c (a pnetcdf example). It contains:

```
/*********************************************************************
 *
 *  Copyright (C) 2014, Northwestern University and Argonne National Laboratory
 *  See COPYRIGHT notice in top-level directory.
 *
 *********************************************************************/

```

My (terrible) legal understanding is that when they contribute the code they assign the copyright to Unidata. So should we change this?

If this is not felt to be appropriate, should be remove this program? (I can easily rewrite the example from scratch).

**Comment by WardF** [comment]
I don't think it's a particular issue at this point, although if we can change/update the copyright or at least append the Unidata copyright, that would be ideal.  @wkliao do you have any thoughts on this?

**Comment by wkliao** [comment]
Hey, that file was added in 2015 when I first developed a patch for supporting CDF-5 in NetCDF. I am OK with appending or prepending NetCDF's copyright statement. I have seen lots like this.

**Comment by dopplershift** [comment]
To be clear, though, contributing code to Unidata projects **DOES NOT** assign UCAR/Unidata the copyright. This is why we now have the CLA, which while it still does not assign copyright, it does explicitly require contributors to grant us a perpetual license to redistribute the contribution under any OSI approved permissive license.

**Comment by edhartnett** [comment]
OK, thanks all for the comments and info. My takeaway is that this and other foreign copyright notices are fine and should be left alone. Thanks for the clarification!
