### ISSUE TITLE
nccopy -w output not written to disk on releases > 4.6.1.

### ISSUE THREAD

**Issue by asantam** [Unidata/netcdf-c#1365]
### Environment Information
Platform: Archlinux 64-bit, kernel 5.0.0
Build sytstem: autotools
Sample netCDF: attached

### Summary of Issue
When using nccopy (v4.6.2-rc1, v4.6.2-rc2, v4.6.2, and v4.6.3) with the -w option on a netCDF classic and netCDF4 files the output is never written to disk. If the input file has compression (i.e. deflate level 1) no message is printed, while using an uncompressed file gives the following error on v4.6.2 (v4.6.3 remains silent):
```bash
double free or corruption (!prev)
Aborted (core dumped)"
```

### Steps to reproduce the behavior

1. configure and make

2. cd into ncdump directory

3. ./nccopy -w testfile.nc outfile.nc

### Sample files
[testfile.nc.gz](https://github.com/Unidata/netcdf-c/files/2963309/testfile.nc.gz)
[testfile.nc4.gz](https://github.com/Unidata/netcdf-c/files/2963311/testfile.nc4.gz)

Other files give the same results.

Thanks!

**Comment by DennisHeimbigner** [comment]
At some point (presumably in 4.6.1) we changed the diskless handling
of flags and added a new NC_PERSIST flag. Looks like we did not fix
all occurrences of the old flag set. Also looks like we need a new/better
test for this option. In any case, I will fix.

**Comment by asantam** [comment]
Thanks for your reply Dennis. I've double checked and it seems that while 4.6.1 creates the file, it's not doing it in memory, as the output its constantly being written to while the processing is going on, and the memory usage never spikes.

**Comment by DennisHeimbigner** [comment]
Fixed by issue https://github.com/Unidata/netcdf-c/pull/1366
