### ISSUE TITLE
Benchmark builds not supported by cmake build

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1369]
Turns out there is no way to build the benchmark programs with cmake.

After I get them separated into the nc_perf directory, I will make it work in cmake as well.

**Comment by WardF** [comment]
What is the issue when trying to build them with cmake, out of curiosity?

**Comment by edwardhartnett** [comment]
I could not find a way to enable them. Is there such a way?

**Comment by WardF** [comment]
Ah, ok, it's entirely possible they weren't wired in; I had read the subject as meaning cmake itself wouldn't support some facet of the benchmark tests, but it's that they haven't been added to the infrastructure.  Thanks for clarifying!

**Comment by edwardhartnett** [comment]
It should work fine. I have a cmake file that should do the job. ;-)

**Comment by edhartnett** [comment]
THis was done and now works.
