### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#1372]
```
CMake Error: File /scratch/gdsjaar/seacas-parallel/TPL/netcdf/netcdf-c/nc_test4/run_par_test2.sh.in does not exist.
CMake Error at CMakeLists.txt:1011 (configure_file):
  configure_file Problem configuring file


CMake Error at CMakeLists.txt:1016 (FILE):
  FILE COPY cannot find
  "/scratch/gdsjaar/seacas-parallel/TPL/netcdf/netcdf-c/build/tmp/run_par_test2.sh".
```
This is with current master.

**Comment by edhartnett** [comment]
I will fix...

**Comment by gsjaardema** [comment]
Note that this results in a build failure when parallel is enabled.

**Comment by edwardhartnett** [comment]
@gsjaardema can you send me the cmake command you are using to build?

**Comment by gsjaardema** [comment]
You have to undo commit commit 3823307b9e461acacc931b5c3376a6ea143ad393
```
Author: Ward Fisher <wfisher@ucar.edu>
Date:   Tue Mar 26 15:38:22 2019 -0600

    Disable run_par_test2.sh.in template processing code temporarily.
```

Then, my cmake command is:
```
cmake .. -DCMAKE_C_COMPILER:FILEPATH=mpicc \
         -DBUILD_SHARED_LIBS:BOOL=ON \
         -DBUILD_TESTING:BOOL=OFF \
         -DCMAKE_INSTALL_PREFIX=${INSTALL_PATH} \
         -DCMAKE_INSTALL_LIBDIR:PATH=lib \
         -DENABLE_NETCDF_4:BOOL=ON \
         -DENABLE_PNETCDF:BOOL=ON \
         -DENABLE_CDF5=ON \
         -DENABLE_DAP:BOOL=OFF \
         -DENABLE_V2_API:BOOL=OFF \
         -DENABLE_CONVERSION_WARNINGS:BOOL=OFF \
         -DHDF5_C_LIBRARY:PATH=${INSTALL_PATH}/lib/libhdf5.dylib \
         -DHDF5_HL_LIBRARY:PATH=${INSTALL_PATH}/lib/libhdf5_hl.dylib \
         -DHDF5_INCLUDE_DIR:PATH=${INSTALL_PATH}/include
```

**Comment by WardF** [comment]
I don't recall why I made the commit you referenced above, but my guess would be it is related to this error?  Unless there is a file @edhartnett wants to add in, I'd say that this isn't so much an issue, as the issue was resolved by commenting out the lines in the CMakeLists.txt file.  If there isn't a file to be added back in, we can probably remove the commented out lines altogether;  I'll take care of that while prepping the 4.7.1 release in the next day, unless I hear differently.

**Comment by edwardhartnett** [comment]
OK, I have confirmed that there is no run_par_test2.sh file to include or run. The parallel testing is all done in run_par_test.sh, and that's working fine.

Also, I don't see run_par_test2.sh in any of the CMakeLists.txt files, except the commented out lines in the main CMakeLists.txt file, which can actually just be removed.

Seemingly run_par_test2.sh was an artifact of development activities and we can just remove all mention of it.
