### ISSUE TITLE
add configure option --with-xxx for external libraries

### ISSUE THREAD

**Issue by wkliao** [Unidata/netcdf-c#1391]
May I suggest to add configure options --with-xxx=DIR to allow users to specify the
installation paths of external libraries? For example, --with-hdf5=/path/to/hdf5
and --with-pnetcdf=/path/to/pnetcdf. This is a practice adopted by PnetCDF and MPICH.

**Comment by WardF** [comment]
This is the behavior that netCDF used to use, but was removed at some point before my arrival at Unidata.  Maybe @edhartnett can provide some historical context for the change?

**Comment by edhartnett** [comment]
I really don't remember. ;-)

We did used to have a --with-hdf5, --with-zlib, and --with-szlib options.

**Comment by DennisHeimbigner** [comment]
One reason was because it turns out that various systems do not adhere
to the linux model of <prefix>/{lib,include,bin} model. So, we were starting
to proliferate to have --with-hdf5-lib=... --with-hdf5-include=..., etc.

**Comment by DennisHeimbigner** [comment]
I also have vague recollection that there were problems with static builds.
The issue may have been that there was no easy way to tell the build that there
were additional (implicit) libraries that needed to be loaded. This was not an issue
with dynamic libraries because they were loaded at run-time.

**Comment by wkliao** [comment]
Regarding to different include and lib directories, HDF5 uses the followings (from its command ./configure --help).
```
 For the following --with-xxx options, you can specify where the header
 files and libraries are in two different ways:

    --with-xxx=INC,LIB - Specify individually the include directory and
                         library directory separated by a comma
    --with-xxx=DIR     - Specify only the directory which contains the
                         include/ and lib/ subdirectories
```
For static build,  my understanding is libtool can find the dependent libraries.
So, far it works well with me, but I did not test NetCDF with static build thoroughly.
