### ISSUE TITLE
nc_finalize() must work, and must be internal function, or user memory checking in CI systems will fail due to netCDF

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1395]
It should be that nc_finalize() may be called at any time, as long as all netCDF files are closed, right?

Yet when I turn this on in PIOc_finalize(), whcih is only called when all files are closed, it causes error in one of my tests. The error I get is a segfault in the provenance code.

I have to finish some other things, but I will try and circle back around and try to narrow this down.

**Comment by DennisHeimbigner** [comment]
To be precise, nc_finalize should be called at the point where your program will
no longer be using the netcdf-c library. That is potentially different than calling it
when all files are closed because there would be the possibility that you might
starting using the netcdf-c library again after calling nc_finalize.
I think I should add some code to enforce the
"no more library use after nc_finalize is called"
rule.

**Comment by edhartnett** [comment]
That is not what I understood. If my program calls nc_finalize() I expect all memory to be freed. 

But then I also expect to be able to call nc_open/nc_create and open a new file.

It has to work this way to be useful. I am not in charge of user code, I am only in charge of the PIO code, so I can call it in PIOc_finalize() but I cannot stop the user from then calling PIOc_Init_Intracomm() and starting over again.

**Comment by DennisHeimbigner** [comment]
The first statement is true: all memory should be reclaimed.
The second statement is currently false, the library is no longer usable
because all memory has been reclaimed.

**Comment by edhartnett** [comment]
Well then nc_finalize() is not very helpful.

Seems like you could release the resources, and set the pointers to NULL. You could initialize the pointers to NULL. Then, when create/open happen you can check if those pointers are NULL and (re-)allocate them. That way, nc_create/nc_close/nc_finalize can be called again and again, freeing all memory each time.

**Comment by DennisHeimbigner** [comment]
I will put it on my to-do list.

**Comment by DennisHeimbigner** [comment]
There is a branch called finalize.tmp that should fix it.
I have not yet turned it into a pull request.

**Comment by DennisHeimbigner** [comment]
I do have a question. What should be done if nc_finalize
is called and there are still open files. The two options would
appear to be:
1. abort all open files
2. cause nc_finalize to return an error and not do the finalization.
Any preferences?

**Comment by edhartnett** [comment]
I think aborting all open files makes sense.

**Comment by edhartnett** [comment]
This is becoming a serious problem for me, and I'm sure other netcdf programmers (i.e. users) will feel this pain. So @DennisHeimbigner perhaps we could move this up the to-do list?

The reason is that I use memory checking in my CI systems (and have caught more than a few netcdf memory leaks that way, IIRC). But now they break. :-( Leaving me wailing and gnashing my teeth.

Actually nc_finallize must be an internal function. If you add a requirement to call nc_finalize() to clean memory, you break every exisiting netCDF program as soon as memory checking is turned on. So that's not good at all!

For example, if users want to run memory checking on a weather model, you can't require that they change the code to make it work. It should just continue to work, as it used to.

Seems like it would be trivial to call nc_finallize() internally when the last file is closed. Then the next nc_open() or nc_create() should re-initialize the library. All of this should happen without user notice or intervention. Otherwise you are introducing memory bugs into all user applications.

**Comment by DennisHeimbigner** [comment]
Not sure how to address this.

What you really want is in effect an nc_reset() that just resets the library
back to its initial state, but allows continued use.
Also, I never intended that programs be required to invoke nc_finalize.
The idea was to provide it exactly for the purpose of memory checking.
It should be the case that your program should work identically
whether or not you called nc_finalize.

I am somewhat reluctant to call nc_finalize every time the open file
count goes to zero because I can easily imagine programs that serially
open-read-close a sequence of files. In this situation we would have the
overhead of invoking nc_finalize every time a file was closed and then
the overhead of nc_initialize every time a file was opened.

Besides the branch mentioned above, somewhere I have a branch that causes nc_finalize to be invoked automatically
just before the program exists (using at_end() if I recall). But not sure
if this  quiets the memory checkers.

I suppose we can add yet another ./configure option to cause nc_finalize
to be invoked when the open file count goes to zero.

**Comment by edhartnett** [comment]
Requiring nc_finalize is breaking the API. Memory checking used to work fine, now it does not. Can we fix that?

Also, I really question what is going on with this memory that we cannot free it when the last file is closed. The memory that you are using is for dap initialization? Because the classic and netCDF-4 code cleans up after itself.

So what memory thing are you doing that cannot be easily cleaned up?

A configure option is a bad idea. Writing code that cleans up after itself in the normal way is a good idea. Why not just do that?

**Comment by gsjaardema** [comment]
We have some use cases in which we open/close files repeatedly.  I'm not sure what the overhead of this repeatedly calling nc_initialize/nc_finalize each time the file count goes to zero would be.

Would it be possible to register `nc_finalize` with `atexit`?

**Comment by DennisHeimbigner** [comment]
I have a branch that calls nc_finalize at atexit. What I have not tested is if
it shuts up the memory checker.

**Comment by DennisHeimbigner** [comment]
Ed-
I do not understand this comment:
>Memory checking used to work fine, now it does not. 
It has always been the case the e.g. valgrind would complain
about  the global memory no being reclaimed. You seem
to be implying that nc_finalize is no introducing new memory errors.

**Comment by WardF** [comment]
@DennisHeimbigner Ed may be referring to the bounds checkers used when compiling with `CFLAGS="-fsanitize=address -fno-omit-frame-pointer`.  The leaked memory returns as a failure, not just a warning, and this is new behavior.  

Getting caught up on email and messages (in reverse order, of course) so wanted to mention that while it was fresh.

**Comment by WardF** [comment]
@edhartnett will correct me if I'm off base.

**Comment by DennisHeimbigner** [comment]
The atexit() soln appears to work for valgrind. Except. There is some unfreed
memory in some support libraries (I see libcrypto and libhdf5) that we have
no control over. It does not look like sanitize recognizes memory that is reachable but unfreed at program exit.

**Comment by edhartnett** [comment]
OK, lots of development here which is good!
I was experimenting with valgrind and thought I had found a leak. 

Then I read Dennis' reply and thought I must have been wrong. 

Now I read Ward's comment about the leak sanitizer and I am confused again. Maybe there are real leaks. 

I will keep looking at this and let you know what I have, when I have something more concrete.

**Comment by WardF** [comment]
@edhartnett My comment was supposition on what you might have been talking about, and not in reference to a specific error I'm seeing on my end.

**Comment by edhartnett** [comment]
OK, let me check more thoroughly when I get back next week...
