### ISSUE TITLE
missing the configure script

### ISSUE THREAD

**Issue by timhoar** [Unidata/netcdf-c#1397]
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### Environment Information

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [ ] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [ ] 64-bit
* What build system are you using?
  * [*] autotools (`configure`)
  * [ ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [ ] Yes (please attach to this issue, thank you!)
  * [ ] No
  * [ ] Not at this time

### Summary of Issue

The configure script is not present in 06ac972bc0525ea

**Comment by edhartnett** [comment]
The configure script is not stored in the repo. If you are building from the repo, do autoreconf -i first, to build the configure script.

**Comment by timhoar** [comment]
Understood.

I believe the INSTALL.md document makes no mention of that ...


Thanks -- Tim

Tim Hoar
Data Assimilation Research Section
National Center for Atmospheric Research
thoar@ucar.edu
303.497.1708

**Comment by WardF** [comment]
The non-release branches are typically used for development and aren’t expected to be for ‘end user’ consumption (the releases do include the configure script and supporting automake/autoconf files).

**Comment by timhoar** [comment]
You're welcome - and Thanks!
Tim Hoar
Data Assimilation Research Section
National Center for Atmospheric Research
thoar@ucar.edu
303.497.1708
