### ISSUE TITLE
many CI builds now failing due to szip configure problems

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1400]
Many of my CI jobs which used to work are now failing with this error:

```
configure: error: libhdf5 installed with szip support, but cannot find or link to the szip library.
Build step 'Execute shell' marked build as failure
```

**Comment by DennisHeimbigner** [comment]
What does ldd say?

**Comment by WardF** [comment]
I am not seeing any instances of this on our CI or environments with szip support.

**Comment by WardF** [comment]
I'll poke around a bit more to see if I can get it to fail to find/link libsz.

**Comment by edhartnett** [comment]
Stand by I am working through CI issues one at a time... I will get to this one shortly. ;-)

**Comment by DennisHeimbigner** [comment]
Remember that we use libaec, which also provides libszip.

**Comment by edhartnett** [comment]
OK, looks like these are due to some weirdness (user error) when I installed HDF5 1.10.1. I'm reinstalling that and hopefully it will allow me to close this issue. But it takes a while. ;-) I will check back later.

**Comment by edhartnett** [comment]
Once I fixed all my CI jobs, this problem went away.

But I'm not sure it's really correct or I really understand what is happening. It used to be that I did not need to provide the szip lib directory, it was found via the HDF5 shared library mechanism automatically. Now I have to provide it.

Anyway I will close this ticket and if I ever figure this out I will make a note here later.
