### ISSUE TITLE
broken build for --enable-hdf4 --disable-hdf5

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1402]
This build no longer works:

```
+ autoreconf -i
+ export CPPFLAGS=-I/usr/local/zlib-1.2.11/include -I/usr/local/hdf-4.2.13/include
+ export LDFLAGS=-L/usr/local/zlib-1.2.11/lib  -L/usr/local/hdf-4.2.13/lib
+ ./configure --enable-hdf4 --disable-dap-remote-tests --enable-hdf4-file-tests --disable-hdf5 --disable-utilities
```

It fails like this:

```
In file included from dfilter.c:18:0:
../include/hdf5internal.h:15:10: fatal error: hdf5.h: No such file or directory
 #include <hdf5.h>
```

The problem is that this include is not protected by ifdef USE_HDF5.

**Comment by edhartnett** [comment]
OK, this is actually a bigger issue. When @DennisHeimbigner recently made the filter test changes, we broke the ability to build without HDF5 (but with HDF4). This build is a good test that we have kept the libsrc4 code independent of the libhdf5 code, so when we break it, we have introduced some dependencies that have to be resolved.

Also enable-filter-testing needs to be turned off if HDF5 is not present.

I have a partial fix for all this which I will put up as a PR.

**Comment by WardF** [comment]
This has reared back up in our unit testing.  Currently we are seeing failures with HDF4 on and HDF5 disabled in our travis-ci tests.  I need to figure out why this cropped up in the `master` branch, which implies our CI tests weren't failing when it was merged.  It's a knot I'll try to untangle.

**Comment by DennisHeimbigner** [comment]
I am probably responsible for this. I am trying to separate out --enable-netcdf4
and --enable-hdf5. Basically, one should always use --disable-hdf5 in preference
to --disable-netdf4.  However, for back compatibility, --disable-netcdf4 is treated
as --disable-hdf5.  It may be that the configure.ac code or the CMakeLists.txt code
for testing HDF4 is not doing this correctly.
