### ISSUE TITLE
shared library version-info different for autotools vs. cmake build

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1416]
Note sure if this is an issue, but the autotools and cmake builds use different version-info numbers (a.k.a. SO numbers) for the C library.

From liblib/Makefile.am:
```
##
# These linker flags specify libtool version info.
# See http://www.gnu.org/software/libtool/manual/libtool.html#Libtool-versioning
# for information regarding incrementing `-version-info`.
##

libnetcdf_la_LDFLAGS = -version-info 14:1:1
```

From CMakeLists.txt:

```
SET(netCDF_LIB_VERSION 13)
SET(netCDF_SO_VERSION 13)

```

This seems related to issue #355.

**Comment by opoplawski** [comment]
If I'm not mistaken, I believe a -version-info of 14:1:1 will result in a so version of 13.

**Comment by WardF** [comment]
@opoplawski is correct; the CMakeLists.txt SO version is set after adjusting the autotools-based numbers, creating the library, and confirming their SO version :).

**Comment by edhartnett** [comment]
Thanks!

**Comment by WardF** [comment]
No problem; at the time we adopted SO versioning into the cmake-based builds, I could not find a similar spec for adjusting the SO version as the one provided by gnu.org.  If there is better documentation out there now (I'll take a look) I'm happy to adjust our process, but keeping the .so version consistent between build systems seemed like a good idea.

**Comment by edhartnett** [comment]
Yes I think I will have to start doing the same with PIO.
