### ISSUE TITLE
nc_open in 4.7.0 gives SEGV if given NULL as file name

### ISSUE THREAD

**Issue by PaulWessel** [Unidata/netcdf-c#1419]
### Environment Information

* What platform are you using? (please provide specific distribution/version in summary)
  * [ ] Linux
  * [ ] Windows
  * [X] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [X ] 64-bit
* What build system are you using?
  * [ ] autotools (`configure`)
  * [ ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [ ] Yes (please attach to this issue, thank you!)
  * [ ] No
  * [ ] Not at this time

### Summary of Issue

4.6.3 and earlier netcdf versions would return an error if nc_open was given NULL as filename.  With 4.7.0 we get a SEGV, which is not a backwards compatible change.  I do not know if this is intentional or not.  I am not building netcdf, I am using the mac ports version which was updated to 4.7.0 today (June 29).

### Steps to reproduce the behavior

This code gives SEGV on 4.7.0 but prints the message on 4.6.3:

```
#include <stdio.h>
#include <netcdf.h>

int main () {
	int ncid;
	if (nc_open (NULL, NC_NOWRITE, &ncid))
		printf ("Not a netCDF file\n");
	else
		printf ("A netCDF file\n");
}

```

**Comment by edhartnett** [comment]
Sigh.

**Comment by edhartnett** [comment]
I have a PR up with a fix for this.
