### ISSUE TITLE
C preprocessor macro USE_REFCOUNT used by never defined

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1427]
In dfile.c I see:

```
#ifdef USE_REFCOUNT
    /* If this path is already open, then bump the refcount and return it */
    ncp = find_in_NCList_by_name(path);
    if(ncp != NULL) {
	nullfree(path);
	ncp->refcount++;
	if(ncidp) *ncidp = ncp->ext_ncid;
	return NC_NOERR;
    }
#endif
```

But no USE_REFCOUNT is defined in config.h or the configure.ac file.

Checking the code I see:
```
ed@mikado:~/tmp/netcdf-c$ find . -name '*.[ch]'|xargs grep USE_REFCOUNT
./libdispatch/dfile.c:#ifdef USE_REFCOUNT
./libdispatch/dfile.c:#ifdef USE_REFCOUNT
./libdispatch/dfile.c:#ifdef USE_REFCOUNT
./libdispatch/dfile.c:#ifdef USE_REFCOUNT
./libdispatch/dfile.c:#ifdef USE_REFCOUNT
./libdispatch/dfile.c:#ifdef USE_REFCOUNT
./libdispatch/dfile.c:#ifdef USE_REFCOUNT
./libdispatch/nclistmgr.c:#ifdef USE_REFCOUNT
./libdispatch/nclistmgr.c:#ifdef USE_REFCOUNT
./include/nc.h:#ifdef USE_REFCOUNT
```

So it is never set anywhere. I believe code with USE_REFCOUNT will break for the PIO/netCDF integration layer. The same file will be open twice, once by PIO, and once by netCDF without PIO (acting under PIO).

Also, there should not be the use of macros that are not defined in configure.ac, since there is no way to test this code. As untested code, it lurks like a submerged iceberg, ready to sink the unwary.

Let us decide if USE_REFCOUNT is to be used, if it is, let us support it properly in configure.ac/config.h, and let us change our CI systems to regularly test this code.

Otherwise, let us remove it.

**Comment by DennisHeimbigner** [comment]
Go ahead and remove it. I think it was part of some early experiments
in threading.

**Comment by edhartnett** [comment]
OK, will do. Thanks!
