### ISSUE TITLE
[cdf-5] nc_test fails on cdf-5 tests in parallel environment on 32-bit platforms.

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#143]
The test `nc_test` fails on 32-bit platforms in a parallel environment.  An example of this failure can be seen here:

 * http://my.cdash.org/testDetails.php?test=21307749&build=847440

You can replicate by building netcdf using `mpicc` in a 32-bit environment.  This issue does not occur in 64-bit environments, or in a 32-bit non-parallel environment.  Unfortunately I can't compare the `.cdl` of the files created in a 32-bit parallel/serial environment due to https://github.com/Unidata/netcdf-c/issues/142.  

If you have docker, you can duplicate these issues using the following:

    $ docker run -it -e CBRANCH=cdf-5 unidata/nctests:serial32
    $ docker run -it -e CBRANCH=cdf-5 unidata/nctests:openmpi32

**Comment by DennisHeimbigner** [comment]
I can't test since I need a physical 32-bit machine with mpicc installed.

**Comment by WardF** [comment]
If you are able to get docker running in a cmd shell, you could use the image unidata/nctests:openmpi32 and run it with the 'bash' command. This would drop you into a command line environment.

**Comment by WardF** [comment]
Issue is fixed and was in the 4.4.0-rc5 release.
