### ISSUE TITLE
User-defined types being forced to classic model but should not be

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1435]
In dinfermodel.c, we have:

```
    /* Force flag consistency */
    switch (model->impl) {
    case NC_FORMATX_NC4:
    case NC_FORMATX_NC_HDF4:
    case NC_FORMATX_DAP4:
    case NC_FORMATX_UDF0:
    case NC_FORMATX_UDF1:
	omode |= NC_NETCDF4;
	if(model->format == NC_FORMAT_NETCDF4_CLASSIC)
	    omode |= NC_CLASSIC_MODEL;
	break;
```

I don't believe we want to assume UDFs are classic model. The PIO integration uses UDFs and is not fully classic model. I am going to take this out for UDF0/UDF1 and see if that's OK.

**Comment by DennisHeimbigner** [comment]
I am not sure I follow. NC_CLASSIC_MODEL will only be assumed
if by some other path it is determined that
model->format == NC_FORMAT_NETCDF4_CLASSIC
Are you actually observing this happening?
