### ISSUE TITLE
 nccopy to compressed NetCDF-4 file is magnitudes slower on version 4.6.0+

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1436]
Mike Chen mike.scchen@gmail.com via unidata.ucar.edu 
7:51 AM (1 hour ago)
￼￼
 to netcdfgroup
￼
Hi,
We have a storage shortage and we'd like to leverage the compression to save space.
The idea works fine for some time.
However, I was testing different NetCDF versions and happens to find that the nccopy to compressed NetCDF-4 file is magnitudes slower on version 4.6.0+.

The test method follows:
OS: CentOS 6.10
HDF5: 1.10.5
NetCDF: 4.4.1.1, 4.5.0, 4.6.2, 4.7.0, HPC-NetCDF 4.6.2.4 from NOAA
All building uses system-provided GCC suite 4.4.1.

The test is simple: nccopy a ~400MB classic NetCDF file to NetCDF-4 with:
nccopy -4 -d 1 -s input.nc output.nc4
With version v4.5.0 and lower, the process takes ~7 seconds.
HPC-NetCDF also gives similar speed.
(gzip-ing the same file takes similar time.)
But with version v4.6.2+, the copy can take ~25 minutes!

Our production system still uses 4.4.0, so the speed should be okay.
But I'd like to know more so I can plan the updates accordingly.

Mike Chen
Research Assistant / System Engineer
Dept. of Atmospheric Science
National Taiwan University

**Comment by neumannd** [comment]
Probably related to close issue #1398?

**Comment by DennisHeimbigner** [comment]
Is the fix for https://github.com/Unidata/netcdf-c/issues/1398
in version 4.7.0 or is it still only in master?

**Comment by DennisHeimbigner** [comment]
In any case, you might try forcing the chunk sizes to see if that makes
the speed problem go away. That will tell us if https://github.com/Unidata/netcdf-c/issues/1398 is the same issue.

**Comment by DennisHeimbigner** [comment]
I am pretty sure the problem is the default chunking.

**Comment by mike-scchen** [comment]
I'm the original mail poster.
It looks like the default chunking is the blame.
I'll turn away for now and see if the NCO (our colleagues uses ncks rather than the nccopy) with newer NetCDF has this issue too.

**Comment by DennisHeimbigner** [comment]
Nccopy is actually overriding the default chunking incorrectly.
The problem appears to be with UNLIMITED dimensions.
As a temporary work-around, add the option "-c U/1"
to the nccopy command where U is the name of any unlimited dimension.

**Comment by DennisHeimbigner** [comment]
If you need a quick fix, then use that attached nccopy.c and tell me
if it solves your problem.
[nccopy.zip](https://github.com/Unidata/netcdf-c/files/3388100/nccopy.zip)
