### ISSUE TITLE
Mistake in cmake_faq.md

### ISSUE THREAD

**Issue by bosborne** [Unidata/netcdf-c#146]
I'm seeing:

            -DHDF5_INCLUDE_DIR=/path/to/hdf5/include
And:

            -DHDF5_INCLUDE_DIRS=/path/to/hdf5/include/

**Comment by WardF** [comment]
Good catch, thanks! I should go back and re-write the cmake-related documentation now that I have a better handle on it.  I'll clarify this for the pending 4.4.0 release candidate.

**Comment by bosborne** [comment]
I had trouble installing NetCDF, using HDF5 in a non-standard location. None of the suggested methods worked for me, I tried all kinds of variations of things like this:

cmake . -DHDF5_LIB=/software/apps/hdf5/gcc/64/1.8.8/lib/libhdf5.so -D .....

Using all the different library names (.a, .so), quoting the path, and so on, tried all the different examples. Putting the "." after the arguments, etc. What did work for me was just exporting these env's:

HDF5_HL_LIB, HDF5_LIB, HDF5_INCLUDE_DIR, HDF5_INCLUDE_DIRS

Then doing "cmake ."

**Comment by WardF** [comment]
I will clarify the documentation on these as well; out of curiosity, did
you try setting "CMAKE_PREFIX_PATH=/software/apps/hdf5/gcc/64/1.8.8"?

I also see now (as a result of typing that out) that you appear to be using
hdf5 version 1.8.8; I should mention that netcdf requires hdf5 1.8.9 or
higher.

Thanks again for the bug report/information, I'll clarify the documentation!

**Comment by bosborne** [comment]
Hmm. Did I try CMAKE_PREFIX_PATH? I think I did not, of course the documentation _does_ mention that. Thanks for mentioning the HDF version, will fix that.

**Comment by bosborne** [comment]
OK! "-DCMAKE_PREFIX_PATH= ...." does work, NetCDF finds HDF5 (1.8.9). You might want to remove all the stuff about HDF5_HL_LIB and HDF5_LIB, this is simpler.

**Comment by WardF** [comment]
CMAKE_PREFIX_PATH and HDF5_HL_LIB, etc, serve different purposes.  The former is used to point to libraries located in a specific non-standard area, whereas the latter can be used to specify *specific* libraries, instead of the first ones encountered.  I'll make that clearer in the documentation.
