### ISSUE TITLE
Fails writing a scalar of type MPI_BYTE with hdf5 1.10.5

### ISSUE THREAD

**Issue by jedwards4b** [Unidata/netcdf-c#1462]
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### Environment Information

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [ X] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [X] 64-bit
* What build system are you using?
  * [ ] autotools (`configure`)
  * [ ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [ ] Yes (please attach to this issue, thank you!)
  * [ ] No
  * [ ] Not at this time

### Summary of Issue
Fails in hdf5 1.10.5 to write a single scalar of type MPI_BYTE, see issue
https://jira.hdfgroup.org/servicedesk/customer/portal/2/SUPPORT-503

### Steps to reproduce the behavior
Currently this is in a pio test case, I will try to eliminate pio and submit a netcdf only testcase.

**Comment by jedwards4b** [comment]
A testcase is provided in https://github.com/NCAR/ParallelIO/issues/1582

**Comment by edhartnett** [comment]
I am adding this test to nc_test4/tst_parallel5.c. Works fine with HDF5-1.10.5. I'm now running it thru my CI to test older versions of HDF5.

**Comment by edhartnett** [comment]
I have added a test to tst_parallel5.c, based on your test code. I create a netCDF-4 file with parallel I/O, define a scalar var, write a value to it, then close the file. Then I reopen the file with nc_open_par() and read the scalar to confirm its value.

```
if (!mpi_rank)
        printf("*** testing NC_BYTE type and parallel I/O...");
    {
        /* This test is related to
         * https://github.com/Unidata/netcdf-c/issues/1462. */
        int ncid, varid;
        signed char test_data_in, test_data = 42;

        /* Crate a file with a scalar NC_BYTE value. */
        if (nc_create_par(FILE, NC_NETCDF4, MPI_COMM_WORLD, MPI_INFO_NULL,
                          &ncid)) ERR;
        if (nc_def_var(ncid, "fred", NC_BYTE, 0, NULL, &varid)) ERR;
        if (nc_enddef(ncid)) ERR;
        if (nc_put_var_schar(ncid, varid, &test_data));
        if (nc_close(ncid)) ERR;

        /* Reopen the file and check. */
        if (nc_open_par(FILE, 0, comm, info, &ncid)) ERR;
        if (nc_get_var_schar(ncid, varid, &test_data_in));
        if (test_data_in != test_data) ERR;
        if (nc_close(ncid)) ERR;
    }
    if (!mpi_rank)
        SUMMARIZE_ERR;

```

This test passes with current master on my workstation. I put up a PR, and it's running through the various CI systems now...

**Comment by jedwards4b** [comment]
It seems to be dependent on the version of mpi.  It fails with mpt/2.19 and mpt/2.20 but passes with all other mpi libraries I've tried.

**Comment by edhartnett** [comment]
OK, this issue can be closed, as this appears to be an MPI implementation issue.

**Comment by epourmal** [comment]
We confirmed in HDF5 that this is MPI I/O library issue. See [HDFFV-10882](https://jira.hdfgroup.org/browse/HDFFV-10882).
