### ISSUE TITLE
Allow parallel IO with filters ...

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#1473]
As of version HDF5 1.10.2, it is possible to use MPI and filters together.
We should probably modify our checks to allow this.

**Comment by DennisHeimbigner** [comment]
Maybe we should not check at all for MPIxFilters and instead
let HDF5 do its thing.

**Comment by edhartnett** [comment]
Writing in parallel with zlib is very much desired by several HPC users.
