### ISSUE TITLE
Error in netcdf-4 endianness handling?

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#1479]
The attached file appears to produce incorrect result.
I believe this is because endianness is attached to the type
object (NC_TYPE_INFO_T) rather than the var object (NC_VAR_INFO_T).
In the attached, we define an enum type and use it as the var type
for two different variables. We then set different endianness on the
two variables. What happens is that the endianness of the first variable
is changed when the endianness of the second variable is set.
[t_endian.zip](https://github.com/Unidata/netcdf-c/files/3542691/t_endian.zip)

**Comment by edhartnett** [comment]
The rule is, as documented, that endianness should be set only for numeric types, not user-defined types.

This is a restriction on user-defined types that few are likely to notice or care about. No one really wants to mess with endianness, now that every processor uses little-endian and netCDF-4 uses native endian by default. 

@WardF if you have a way to assign issues to me, you can do that with this issue. I'll can fix it when I get back from vacation.
