### ISSUE TITLE
ncdump v4.6.3 NetCDF: Unknown file format

### ISSUE THREAD

**Issue by abhishekBansal** [Unidata/netcdf-c#1485]
ncdump version: `4.6.3`
`MacOS 10.14.5`, `ncdump` installed via `homebrew`

This might be a noob question, I am just starting with understanding of netcdf files and format.
I am unable to open files that I am downloading from here
https://tgftp.nws.noaa.gov/SL.us008001/DF.of/DC.radar/DS.p94r1/SI.kpoe/

These files open in [Panoply](https://www.giss.nasa.gov/tools/panoply/download/) fine. I keep getting this error `sn.last: NetCDF: Unknown file format`
Am I doing something wrong?

**Comment by WardF** [comment]
These files don't appear to be netCDF files.  Do you know how they were generated?

**Comment by abhishekBansal** [comment]
I am not sure, its govt. database I assumed it must be netCDF. Here is panoply screenshot which reads its as netCDF, its also able to export same file as CDL. 
<img width="947" alt="Screen Shot 2019-09-10 at 11 35 49 AM" src="https://user-images.githubusercontent.com/1726219/64588217-6ea48200-d3bf-11e9-9c0b-b8c99d3f60e9.png">

**Comment by abhishekBansal** [comment]
okay so seemed like I had to convert it to netCDF first
https://www1.ncdc.noaa.gov/pub/data/radar/Radar-Decoding-EasySolution.txt

After this conversion `ncdump` started working for me, thanks!

**Comment by dopplershift** [comment]
For the record, those files are NEXRAD Level 3 product files, also known as NIDS files.

**Comment by DennisHeimbigner** [comment]
If the conversion to netcdf is straightforward, would it
be useful to have the netcdf-c library directly read such files?
=Dennis

**Comment by dopplershift** [comment]
NIDS can describe many different product types (lines, points, polar grids, rectangular grids), so no the conversion to netcdf is not straightforward, though netcdf-java does its best.

In terms of supporting conversions from other file formats, that's duplicating the IOSP layer from netcdf-java. IMO, that's a topic that would go well-beyond the issue tracker.

**Comment by edwardhartnett** [comment]
Well we have duplicated the IOSP layer from netcdf-java, and its called user-defined formats. ;-)

**Comment by dopplershift** [comment]
That's so cute. 😉 

Seriously, while I recognize a significant amount of effort in developing a useful C abstraction layer and interface, there is so much more work in:
1. Rewriting a bunch of binary I/O in C
2. Porting netcdf-java's netcdf schema for all those files into the C-API calls

I'm not saying it's a terrible idea, or one that's technically hard. But it's a massive undertaking that needs to be weighed against other on-going tasks, like Zarr and FORTRAN/C++ library updates, not to mention just basic C library maintenance.

**Comment by DennisHeimbigner** [comment]
NIDS is only worth doing if it is low-hanging fruit; but I gather
that is not the case, so never mind.

**Comment by WardF** [comment]
Resolved so closing, but only for housekeeping, not to shut down the conversation. :)

**Comment by edhartnett** [comment]
@dopplershift climate science/meteorology have always pressed hardware and software to their limits. 

I/O has become the bottleneck for both model development and performance. This situation is expected to continue as Earth observation assets achieve greater diversity and data rates, models greater resolution, and HPC systems more processors.

There are no scientific problem of greater importance! We need bold actions, daring design, and days, weeks, months, and years of heads-down coding. That is my usual prescription - also my usual routine. ;-)

The point of the user-defined formats is that other programmers can make these contributions. No longer are these efforts restricted to a handful of past and present Unidata programmers. Now, just as with Java IOSPs, the wider community can contribute.

**Glory awaits the netCDF C programmer who writes a GRIB reader.** And there are so many other possibilities!

I hope that others take up the banner of netCDF progres. There is so much to be done...
