### ISSUE TITLE
netcdf-4.7.1 creates Bus Error when testing ncgen3

### ISSUE THREAD

**Issue by remkos** [Unidata/netcdf-c#1486]
This is on Mac OS 10.14.6 with Command Line Tools 10.3.

When running `make check` after compilation, the test of `ncgen3` fails with a `Bus error: 10`.
When installing without the test, the installed `ncgen3` **and** `ncgen` both also create a bus error on any CDL file on input.
This may be related to issue #1480.
<pre>
Making check in ncgen3
/Library/Developer/CommandLineTools/usr/bin/make  check-TESTS
FAIL: run_tests.sh
FAIL: run_nc4_tests.sh
============================================================================
Testsuite summary for netCDF 4.7.1
============================================================================
# TOTAL: 2
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See ncgen3/test-suite.log
Please report to support-netcdf@unidata.ucar.edu
============================================================================
</pre>

**Comment by WardF** [comment]
Seeing this under the following circumstances:

* netCDF4 support not required (disables `run_nc4_tests.sh`), still see BUS error in `run_tests.sh`.
* Failure appears when configuring/compiling with `configure/make`, **does not** happen when configuring/compiling with `cmake/make`.
* Bringing the compiler flags into parity between the two systems does not cause an issue.
* Forcing `cmake` to use `gcc` via the `-DCMAKE_C_COMPILER` flag results in the same BUS error.  
* `configure` detects `/usr/bin/gcc`
* `cmake` detects `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc`

Querying `gcc -v`, `cc -v`, etc, results in similar but not identical `clang` version info:

````
$ cc --version
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
````

````
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
````

Investigation is ongoing.
