### ISSUE TITLE
HDF5 error when unlimited dimension and a variable share the same name

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf-c#1496]
Reported by a python user (https://github.com/Unidata/netcdf4-python/issues/975).  The error occurs when a variable has the same name as an unlimited dimension, but does not have an unlimited dimension.  Both C and python programs to trigger the error included in the python issue.

**Comment by WardF** [comment]
Thanks Jeff; I see there is an example C program in the linked python issue.  I'll take a look!  Tagging in @DennisHeimbigner in case anything pops out at him as well.

**Comment by edhartnett** [comment]
OK, this was a subtle one. I have a fix I am submitting now.
