### ISSUE TITLE
Timeout for nc_test4_run_par_test in 4.7.2

### ISSUE THREAD

**Issue by ArchangeGabriel** [Unidata/netcdf-c#1500]
Hi,

While building the new 4.7.2 release, I’ve encountered timeout in `157: nc_test4_run_par_test`:

```
        Start 157: nc_test4_run_par_test
157/204 Test #157: nc_test4_run_par_test .................***Timeout 1500.11 sec
```

This is the only test failure. Arch Linux as always, with OpenMPI.

**Comment by WardF** [comment]
I'm trying to duplicate this.  Can I ask how many processors your machine has, and what version of HDF5 you're using?

**Comment by ArchangeGabriel** [comment]
HDF5 is 1.10.5, OpenMPI 4.0.2. This is a 48 cores machine.

**Comment by opoplawski** [comment]
Possibly this? https://github.com/open-mpi/ompi/issues/7109

**Comment by edhartnett** [comment]
@ArchangeGabriel any further resolution of this issue?

Can you try building master and see if it occurs?

Also, can you run the test script with bash -x?

**Comment by edhartnett** [comment]
Any further information here?

**Comment by ArchangeGabriel** [comment]
@edhartnett Sorry for the delay, been quite busy lately. The issue is still happening with 4.7.3, but as reported above it’s likely an OpenMPI issue fixed in a recent patch. I’m trying to get it backported to ArchLinux openmpi package and will report here if it indeed fixes the issue.

**Comment by ArchangeGabriel** [comment]
I can confirm the mentionned OpenMPI fixes is the solution. Now running fine on a patched OpenMPI.
