### ISSUE TITLE
Parallel cmake build does not install ncexternl.h

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#1502]
Version 4.7.2, using cmake build and parallel enabled, the `ncexternl.h` include file is not installed.  It is referenced by `netcdf_par.h`, so the client builds will fail

**Comment by DennisHeimbigner** [comment]
Actually, netcdf_par.h should not include ncexternl.h at all.
This is because the same macros are in netcdf.h already.

**Comment by gsjaardema** [comment]
@DennisHeimbigner Should `netcdf_par.h` include `netcdf.h` then?  Currently it only includes `mpi.h` and `ncexternl.h`

**Comment by gsjaardema** [comment]
I will add a pull request, but not sure of recommended fix:

- Install `ncexternl.h`
- add the definition of `EXTERNAL` to `netcdf_par.h`

Note that either fix may entail a new release as 4.7.2 is not usable for parallel at the current time.

**Comment by gsjaardema** [comment]
Related to the above, the `netcdf_aux.h` include file has uses of `EXTERNL`, but the symbol is not defined nor are there any includes in the file that would define the symbol, so the include file is not "standalone consistent" and must currently be included *after* an include file which does define `EXTERNL`

**Comment by DennisHeimbigner** [comment]
The assumption is the following.
- If you plan to use any of the netcdf_XXX.h files, then it it is assumed
  that you first include netcdf.h, followed by any netcdf_XXX.h files
  you need. The EXTERNL (and other things) are defined in netcdf.h
  so they should be available for use by the netcdf_XXX.h files.

**Comment by gsjaardema** [comment]
OK, I can work with that assumption.  Note that there are some NetCDF files that don't follow that assumption, for example, `nc4internal.h` 

I assume then that the recommended fix for `netcdf_par.h` then is to just remove the `#include "ncexternl.h"` ?

I will prepare a PR if you want, but not sure how you handle the new release...

**Comment by DennisHeimbigner** [comment]
Sorry, I meant only the publically installed headers. nc4internal.h should
not be publically installed.

**Comment by DennisHeimbigner** [comment]
The two exceptions are netcdf_meta.h and netcdf_f.h

**Comment by gsjaardema** [comment]
And `netcdf_mem.h` has its own definitions of `EXTERNL`

**Comment by t-brown** [comment]
Are you going to cut a new version (`4.7.3`)?

**Comment by WardF** [comment]
Yes, although not in the next day or two.  The end of the week would be the
earliest we see a release.
