### ISSUE TITLE
old ncgen documentation should be removed

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1503]
The documentation here: https://www.unidata.ucar.edu/software/netcdf/netcdf/ncgen.html

Says:

```
-c
    Generate C source code that will create a netCDF dataset matching the netCDF specification. The C source code is written to standard output. This is only useful for relatively small CDL files, since all the data is included in variable initializations in the generated program.

```

But when I try:
```
 /home/ed/local/netcdf-c-4.7.2/bin/ncgen -c ncdump.out > glm_write_ncgen.c
-c is deprecated: please use -lc
```

There is no mention of -lc in the docs...

**Comment by edhartnett** [comment]
OK, turns out that this is just out of date documentation. @oxelson perhaps you can remove it? It is coming up first on my google searches...

**Comment by oxelson** [comment]
@edhartnett and @WardF -- those docs have been removed and archived offline.  Let me know if you need anything else!

**Comment by edhartnett** [comment]
Awesome work Jen!!
