### ISSUE TITLE
ncgen does not ignore "secret" attributes

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1504]
I ran ncgen -lc on an ncdump output. I had used the -s option with the ncdump output, so it contained hidden attributes.

ncgen then generates code that tries to set hidden attributes. This surprised me. I would have thought ncgen would be smart enough to ignore the hidden atts.

```
    stat = nc_put_att_text(ncid, NC_GLOBAL, "_Format", 1, "netCDF-4");
    check_err(stat,__LINE__,__FILE__);

```

Also when this code ran, the error message surprised me. I would have thought we had a message for trying to set a hidden attribute, but we get:

`line 201 of tst_glm_ncgen_write.c: NetCDF: String match to name in use`

Maybe we should have an error that says that this is a protected attribute name and should not be used by the user?

**Comment by edhartnett** [comment]
As I pondered this I realized that it might also be good to actually use the hidden attributes, instead of ignoring them. In ohter words, if there is a _Format of netCDF-4, then treat that as if the user had specified the flag that called for a netcdf-4 file.

This strays rather beyond the original issue title. Perhaps a ignoring them is better.

**Comment by DennisHeimbigner** [comment]
For _Format, I think it does that now.
IN any case, some attributes are used: _Endianness, for example.

**Comment by edhartnett** [comment]
Well I just got the error for _Format, and that was with 4.7.2. Am I using it wrong? See above for the exact error message...

**Comment by DennisHeimbigner** [comment]
THis .cdl works:
netcdf t {
:_Format = "netcdf4";
}

**Comment by edhartnett** [comment]
Will you also be adding a test? ;-)

**Comment by DennisHeimbigner** [comment]
oops, I will do that.

**Comment by edhartnett** [comment]
I believe this has been fixed, so I will close this issue.
