### ISSUE TITLE
Failure building with mpicc in current master

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#1507]
Appears to be an issue with `EXTERNL` not being defined properly in `netcdf_par.h`.  Fixing now, should be pretty straight-forward.

**Comment by gsjaardema** [comment]
I thought that the correct usage was to require that `netcdf.h` be included prior to including `netcdf_par.h` wherever it was used.  See #1502

**Comment by WardF** [comment]
You're right, of course, @gsjaardema.  Reworking so that the fix is in line with correct usage.
