### ISSUE TITLE
Please Substitute CMAKE_{SOURCE,BINARY}_DIR with CMAKE_CURRENT_{SOURCE,BINARY}_DIR

### ISSUE THREAD

**Issue by turingeret** [Unidata/netcdf-c#1509]
If you directly include netcdf-c in another CMake project, it fails to configure properly as it looks for several things in CMAKE_SOURCE_DIR which will be the parent CMake project's source directory, not the netcdf-c's source directory. This can be simply fixed by replacing it with CMAKE_CURRENT_SOURCE_DIR. The same applies for CMAKE_BINARY_DIR.

In order to quickly reproduce this issue, create a simple CMake project and add the following lines:
```
include(FetchContent)

FetchContent_Declare(
        netcdf
        GIT_REPOSITORY https://github.com/Unidata/netcdf-c.git
        GIT_TAG        v4.7.2
)

FetchContent_MakeAvailable(netcdf)
```

**Comment by WardF** [comment]
This will require some rewriting of the CMakeLists.txt files over and above substituting one for the other.  I will work on this when I get a chance, and as always, pull requests are welcome. Thanks for reporting this, however, I wasn't aware of `FetchContent`. Thanks!

**Comment by turingeret** [comment]
Yeah, I'm noticing that it wasn't quite a easy substitution. While I am using FetchContent myself, this will happen if it's just included as a subproject of another CMake project.

I'll see if I can play with it a little and maybe fix the issue.

**Comment by WardF** [comment]
Sounds good; it may not be as difficult as I originally thought, I’ve created a branch to see if I can make this broader change. Thanks!


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by turingeret** [comment]
I created a pull request with what I believe works. It compiled successfully and all tests passed.

https://github.com/Unidata/netcdf-c/pull/1514
