### ISSUE TITLE
Files Generated by CMake Should Not Go In Source Tree

### ISSUE THREAD

**Issue by turingeret** [Unidata/netcdf-c#1513]
Files generated by CMake should not go in the source tree. For example, "findtestserver.c.in" is configured and put in the source directory, but it should probably go in the build directory. A out-of-source CMake build should leave the source tree completely untouched so that several out-of-source builds can be run simultaneously without any risk of interfering with each other.

**Comment by WardF** [comment]
Thanks for pointing this out.

**Comment by WardF** [comment]
So for findtestserver, there are legitimate reasons to keep these source files in the source tree, along with other source files.  This is also in line with how our autotools build works for out-of-tree builds.  I'll look at generating the files only if they don't exist; this should help prevent multiple builds from conflicting with each other.
