### ISSUE TITLE
can we now remove non-relaxed coord bounds?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1519]
See #1010 for the long discussion.

To summarize, coordinate bounds checking for netCDF-4 was originally slightly broken with parallel I/O. This was fixed (and the fix called "relaxed coord bounds"). Unfortunately, instead of just making the fix, an option was included to continue to build the old, incorrect code.

Using non-relaxed coord bounds is wrong and dangerous. This is reflected in the --enable documentation:
```
dnl Always build with relaxed coord bound checking, to prevent API
dnl incompatibilities between different installs of netCDF.
AC_ARG_ENABLE([zero-length-coord-bound],
   [AS_HELP_STRING([--disable-zero-length-coord-bound],
                   [Disable relaxed boundary error check. Deprecated. Using this can cause API incompatibilities. This option will be removed in the next release of netCDF.])])
test "x$enable_zero_length_coord_bound" = xno || enable_zero_length_coord_bound=yes
...
AC_SUBST(RELAX_COORD_BOUND,[$enable_zero_length_coord_bound])
```

Last time I brought this up, there was a lot going on, and I don't believe that this issue was properly resolved, but we all just moved on.

Now I would like to finally resolve this by removing the option to build without relaxed coord bounds. I'm sure no one is doing it, and, if they are, they should certainly not be. There is no benefit to continuing to support the old buggy behavior. We don't want users to write code that depends on non-relaxed coord bounds, under any circumstances.

@WardF, can I submit a PR with this resolved?

**Comment by WardF** [comment]
<muttering outloud to myself as I review this>

Reviewing #1010, it seems that the main issue against removing it altogether was raised by @wkliao and we ended in a place where we erred on the side of caution; I disagree that this was a mistake, but that's neither here nor there ;).  @wkliao changed the default behavior in pnetcdf to match. We checked in with Charlie Zender at the time, he had no objections.  We've had no bug reports/support questions related to the new behavior, so the odds of having to back it out at this point are small.  This is probably ok to remove now, approximately a year later.

</muttering> 

@DennisHeimbigner do you have any thoughts on why we shouldn't go ahead and remove this now that we've given potential issues a year to appear, and they haven't?

**Comment by edwardhartnett** [comment]
OK, let's withdraw my perhaps too-critical evaluation of the history of this issue.

Nonetheless I believe it's time to put this to rest and remove this code. @Ward, may I proceed with this and present a PR?

**Comment by WardF** [comment]
@edhartnett Sounds good, as I've heard no objections. We've allowed plenty of time for any workflow/wilderness issues to surface, so I'm comfortable we aren't breaking an unusual corner cases. Thanks!
