### ISSUE TITLE
User-defined formats must take priority in NC_infermodel()

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1522]
I'm glad I caught this before the next release, because it breaks user-defined formats in some cases.

The determination that this is a user-defined format must be done before any other cmode/omode flags. That's because the user-defined format may use some of the same flags as netCDF, but needs to handle them in the UDF code.

For example:

`nc_create("file.nc", NC_PIO|NC_NETCDF4, &ncid);
`

will create a netCDF-4 file with PIO (NC_PIO = NC_UDF0). And this is a general thing that a user-defined format might want to do, since how flags are interpreted and used can be determined by the dispatch layer.

But in order for this to work, the function NC_infermodel() has to check the UDF flags first, and defer handling the rest of the flags to the dispatch layer.

This is an easy fix, but I am also going to modify the test of user-defined formats to check this...

**Comment by DennisHeimbigner** [comment]
Good call. I will fix.

**Comment by edhartnett** [comment]
No need, I've got a PR ready, just working on the test.

The fix itself is trivial, I just move this code to the top of the function:
```
    if(fIsSet(cmode,(NC_UDF0|NC_UDF1))) {
	model->format = NC_FORMAT_NETCDF4;
        if(fIsSet(cmode,NC_UDF0)) {
	    model->impl = NC_FORMATX_UDF0;
	} else {
	    model->impl = NC_FORMATX_UDF1;
	}
	goto done;
    }

```

I'm having trouble getting the test to detect this issue...
