### ISSUE TITLE
should NC_MAX_NAME be used with netcdf4 files?

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf-c#153]
There doesn't appear to be any way to determine the length of attribute and variable names ahead of time, so in netcdf4-python we are allocating the space for those names with NC_MAX_NAME.  However, as I understand it, there is no requirement that names not exceed NC_MAX_NAME in netcdf4 (non-classic) files.  What is the recommended way to handle this?

**Comment by DennisHeimbigner** [comment]
I took a look at where the code calls HDF5 functions.
The HDF5 functions all appear to take a string buffer plus a buffer size.
For the netcdf-4 code, it always sets the buffer size to NC_MAX_NAME.
The effect is that if there is a name in the HDF5 file longer than NC_MAX_NAME,
then it is truncated and only the first NC_MAX_NAME characters are used.
It is not clear is the underlying HDF5 functions provide any means of getting the size
of a name either.

**Comment by jswhit** [comment]
Thanks Dennis.  At least I know we're safe using NC_MAX_NAME.

**Comment by jswhit** [comment]
The docs probably should be changed.  For example, 

https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_8h.html#ab9e71c71ff6221a898bfdb97379fa9d8

implies NC_MAX_NAME is not used for netcdf4 files that don't use the classic data model.

**Comment by DennisHeimbigner** [comment]
I forgot about NC_MAX_ATTRS; it does not appear that it is enforced
anywhere in the netcdf-c code.

**Comment by DennisHeimbigner** [comment]
I also found this in the code:
*  the field names of compound types (and enumeration constant names)
    are retrieved using H5Tget_member_name, which returns the name in a malloc'd
    chunk => no size limit, but the size is checked immediately afterwards to enforce
    NC_MAX_NAME.

**Comment by WardF** [comment]
Is there more to say to resolve this or can we close it out?

**Comment by jswhit** [comment]
Seems like either this line in the docs should be changed

"These maximums are not used for netCDF-4/HDF5 files unless they were created with the NC_CLASSIC_MODEL flag."

or the library should enforce the NC_MAX* values for NC_NETCDF4 files.

**Comment by jswhit** [comment]
To summarize what Dennis found, when a file is created with the NC_NETCDF4 flag,

* NC_MAX_NAME is enforced for attributes, compound type field names, and enum field names.
* NC_MAX_VARS is enforced.
* NC_MAX_ATTRS and NC_MAX_DIMS are not enforced

**Comment by WardF** [comment]
Thanks, Jeff.  If I'm reading this right, we are enforcing limits that we said were not enforced; this is pretty clearly a mistake.  I'll confer with @dmh when I return to the office next week and we'll move forward with fixing this.  Thanks again!

**Comment by WardF** [comment]
I'm behind schedule on my AGU material so this fix may not make the 4.4.0 release, although as always patches are welcome :).  In no way expected, but welcome.

**Comment by DennisHeimbigner** [comment]
Close it out

**Comment by WardF** [comment]
Closing out as per @dmh

**Comment by jswhit** [comment]
Why was this closed? The documentation should at least be corrected to note that some, but not all, of the NC_MAX* limits are being enforced when files are created with the NC_NETCDF4 flag.

**Comment by WardF** [comment]
@jswhit closed re: @dmh, I'll re-open it now and to help remember to update the documentation.

**Comment by WardF** [comment]
As @dmh just reminded me, this will depend on what the standard says.  For an unrelated issue I need to refer to the netCDF specification; if the spec says these are the limits, we will leave the documentation in place regardless of whether or not they are enforced.  We will then need to find the resources to go enforce them, probably :).  If they are not mentioned in the spec, then updating the documentation will probably be the next logical step.   Regardless, it will probably be after AGU before I can address this, but thanks for staying on top of it @jswhit.

**Comment by jswhit** [comment]
OK Ward, thanks.  

I can't find any mention of the NC_MAX* limits anywhere except in the C API documentation.
