### ISSUE TITLE
Provide zlib compression in a classic format

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1550]
This is one I'm not going to do in the near-term, as I have more than enough to keep me busy with netCDF-4 and PIO! ;-)

But it seems like it would not be too hard to use zlib in one of the classic formats. I believe the only difference is that you would have to store both offsets and lengths of blocks of data. That is, the lengths would not be calculatable, because they would depend on how the data deflated.

Seems like we could ask the user to specify how many dimensions are involved in a chunk, and then require that the user only write data in integer multiples of that. Then the data could be deflated and stored in a classic style binary format.

Part of #1545.

@gsjaardema how about this as a nice new CDF6?

**Comment by WardF** [comment]
We'd need to come up with a new label than 'classic', since classic netCDF3 files are pretty well defined/documented as not working with compression.  Maybe classic+ or classicc (the extra c is for compression) or something along those lines.

**Comment by WardF** [comment]
Ah, you snuck CDF6 in as I commented.

**Comment by edwardhartnett** [comment]
OK, we have a bunch of new compression functionality under discussion, but this is not part of that. I will close this issue, but would very much welcome it if some other programmer were to take this idea and run with it.
