### ISSUE TITLE
Can netcdf support unsigned types in all classic formats?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1556]
I am looking at some data from the wonderful and amazing Geostationary Lightning Mapper (GLM) instruments on GOES-16 and GOES-17. Here's something from their data file README:

> Unsigned Integer Read: This is an issue that affects multiple instruments on GOES-16, and a pilot
> fix is being worked. The classic model for NetCDF does not support unsigned integers larger than
> 8 bits. Many of the variables in GOES-16 data files are unsigned integers that are either 16-bits or
> 32-bits. So, until a fix is achieved, we recommend using the following process to convert:
> • Retrieve the variable data (using low level routines).
> • If there is an attribute “_Unsigned” then cast the variable data to unsigned.
> • This step must be completed before applying scale_factor and add_offset values to
> convert from scaled integer to science units. For example, when reading the NetCDF
> files, one has to MANUALLY read in the event lat/lon as an unsigned integer (using
> low level routines), and then manually take care of the scale and offset.

Which made me wonder, how come the classic formats don't support unsigned types? I know that CDF5 does, but how about CDF1 and CDF2?

It seems like this should be pretty easy. The unsigned types are the same sizes as existing types, and we have the API to handle them.

**Comment by t-b** [comment]
According to https://cdn.earthdata.nasa.gov/conduit/upload/496/ESDS-RFC-011v2.00.pdf only signed integers are supported. And if you would add support for unsigned types you are basically creating a new fileformat or? I do know that as we've written a proprietary tool to read all kinds of netcdf classic files. How would old netcdf libraries handle unsigned variables? Would they crash or error gracefully out?

**Comment by edhartnett** [comment]
@t-b good questions! 

That document you cite has my name on it, but I don't remember writing it. ;-)

However, it is from 2008 and is out of date, as one might expect. The CDF5 is a new classic format, which allows unsigned types, and is not mentioned in that document.

**Comment by Dave-Allured** [comment]
Why not simply use the existing and time-tested facilities of Netcdf-4 for enhanced support such as unsigned integers?  Where is there any advantage of expanding classic format capabilities?

**Comment by t-b** [comment]
And I found http://cucis.ece.northwestern.edu/projects/PnetCDF/CDF-5.html which documents the changes of CDF5 vs CDF1/2.

@Dave-Allured Good point! I would be in favour of keeping the classical formats as they are as well.

**Comment by edhartnett** [comment]
OK, I believe @t-b and @Dave-Allured have raised some excellent points and CDF1 and CDF2 should be left alone. However, we do need to change our description of classic vs. enhanced model.
