### ISSUE TITLE
udata.grps in libhdf5/hdf5open.c rec_read_metadata() may be uninitialized during BAIL() exit processing

### ISSUE THREAD

**Issue by brentd42** [Unidata/netcdf-c#1558]
Version: 4.7.1
Operating System: Windows, Linux, MacOS

The _rec_read_metadata()_ function in libhdf5/hdf5open.c may terminate early on error conditions by invoking the _BAIL()_ macro. _BAIL()_ jumps to the 'exit:' label, where there's an attempt to clean up the child groups as specified by udata.grps. Unfortunately, _BAIL()_ may be invoked prior to udata.grps being initialized (statement 2567). Invoking _nclistlength()_ and _nclistget()_ on an uninitialized udata.grps results in unpredictable behavior (and usually a crash).

There are likely a number of scenarios to reproduce this. The following code that (1) creates an HDF5 file (without H5P_CRT_ORDER_TRACKED), then (2) attempts to reopen it using _nc_open()_ (w/ NC_WRITE) will do the trick ...

```
  hid_t file_hid, fcpl_hid;
  int ncid, retval;
  char *filename = "foo.h5";

/* fails */
  file_hid = H5Fcreate(filename, H5F_ACC_TRUNC, H5P_DEFAULT, H5P_DEFAULT);

/* works */
/*
  fcpl_hid = H5Pcreate(H5P_FILE_CREATE);
  H5Pset_link_creation_order(fcpl_hid, H5P_CRT_ORDER_TRACKED);
  H5Pset_attr_creation_order(fcpl_hid, H5P_CRT_ORDER_TRACKED);
  file_hid = H5Fcreate(filename, H5F_ACC_TRUNC, fcpl_hid, H5P_DEFAULT);
*/

  H5Fclose(file_hid);

  if ((retval = nc_open(filename, NC_WRITE, &ncid)))
    ERR(retval);
  if ((retval = nc_close(ncid)))
    ERR(retval);
```

**Comment by edwardhartnett** [comment]
Thanks! I will fix...

**Comment by edhartnett** [comment]
Thanks again! Fix is up in a PR now.
