### ISSUE TITLE
NetCDF: HDF error

### ISSUE THREAD

**Issue by Liu-Richard** [Unidata/netcdf-c#1562]
OS:centOS7.6
server: aarch64 arm
gcc： 4.8.5
cmake :2.8.12
hdf5:1_8_21
netcdf:4.7.0
issue:
I compiled hdf5 and netcdf and installed them  in arm server.also compiled and installed gmt(5.4.5) successfully.
but when I run gmt, issue found:

[root@localhost home]# gmt pscoast -JM10c -R70/140/2/60 -Bafg -Ggray -Wthin > map.ps
pscoast: NetCDF: HDF error [GSHHG low resolution shorelines]
pscoast: No GSHHG databases available - must abort

and netcdf info:
[root@localhost gshhg]# ldd /usr/local/netcdf/lib/libnetcdf.so
    linux-vdso.so.1 =>  (0x0000ffff837b0000)
    libhdf5_hl.so.10 => /usr/local/hdf5/lib/libhdf5_hl.so.10 (0x0000ffff835b0000)
    libhdf5.so.10 => /usr/local/hdf5/lib/libhdf5.so.10 (0x0000ffff832b0000)
    libm.so.6 => /lib64/libm.so.6 (0x0000ffff831d0000)
    libdl.so.2 => /lib64/libdl.so.2 (0x0000ffff831a0000)
    libz.so.1 => /lib64/libz.so.1 (0x0000ffff83160000)
    libcurl.so.4 => /usr/local/curl/lib/libcurl.so.4 (0x0000ffff830e0000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x0000ffff830a0000)
    libc.so.6 => /lib64/libc.so.6 (0x0000ffff82f10000)
    /lib/ld-linux-aarch64.so.1 (0x0000ffff837c0000)
I grep error info in netcdf.h:
netcdf-c-4.7.0/include/netcdf.h:438:#define NC_EHDFERR       (-101)    /**< Error at HDF5 layer. */

so, how can I fix it 

* the version of the software with which you are encountering an issue
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
* a description of the issue with the steps needed to reproduce it

If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

**Comment by edwardhartnett** [comment]
Firstly, upgrade to the latest release of netcdf-c, which is 4.7.3.

Also, did you run make check after building netcdf-c?

**Comment by Liu-Richard** [comment]
tthanks, The result of make check as follow:
============================================================================
Testsuite summary for netCDF 4.7.0
============================================================================
# TOTAL: 26
# PASS:  25
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See h5_test/test-suite.log
Please report to support-netcdf@unidata.ucar.edu

the test-suite.log
==========================================
   netCDF 4.7.0: h5_test/test-suite.log
==========================================

# TOTAL: 26
# PASS:  25
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tst_h_vars
================


*** Checking HDF5 variable functions.
*** Checking HDF5 boolen variables...ok.
*** Checking HDF5 variable with unlimited dimension...ok.
*** Checking HDF5 deflate filter setting and getting...Sorry! Unexpected result,../../h5_test/tst_h_vars.c, line: 230FAIL tst_h_vars (exit status: 2)

so next?

**Comment by edhartnett** [comment]
Was HDF5 built with zlib? It must be, for netcdf-4.

Unfortunately this problem is not detected by netcdf-c configure, as it should be. I am working on that... (see #1557).

To check, rebuild HDF5 (use 1.10.5) and ensure that it is finding and building with zlib. Then rebuild netcdf-c using that HDF5 build.

**Comment by Liu-Richard** [comment]
@edhartnett  thanks a lot
I built hdf5 with zlib(--with-zlib) and issue is solved
but I found netcdf has other error when I make check :
PASS: t_dap3a
PASS: test_cvt3
PASS: test_vara
PASS: tst_ncdap3.sh
PASS: tst_ber.sh
FAIL: tst_remote3.sh
PASS: tst_formatx.sh
PASS: testurl.sh
PASS: tst_fillmismatch.sh
PASS: tst_zero_len_var.sh
PASS: test_partvar
FAIL: test_varm3
FAIL: test_nstride_cached
PASS: t_misc
============================================================================
Testsuite summary for netCDF 4.7.0
============================================================================
# TOTAL: 14
# PASS:  11
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0
============================================================================
See ncdap_test/test-suite.log
Please report to support-netcdf@unidata.ucar.edu
===========================================
the test-suite.log is as follows:
=============================================
   netCDF 4.7.0: ncdap_test/test-suite.log
=============================================

# TOTAL: 14
# PASS:  11
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tst_remote3
=================

*** Testing DAP to netCDF-3 translation using remote server 
        Base URL: http://xx:8080/dts
        Client Parameters: [log][netcdf3]
        Caching: on

...
syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR

*** FAIL:  test.56
*** Testing: test.57 ; url=[cache][prefetch]http://xx:8080/dts/test.57
syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
...

*** FAIL:  test.57
*** Testing: test.66 ; url=[cache][prefetch]http://xx:8080/dts/test.66
*** Testing: test.67 ; url=[cache][prefetch]http://xx:8080/dts/test.67
*** Testing: test.68 ; url=[cache][prefetch]http://xx:8080/dts/test.68
*** Testing: test.69 ; url=[cache][prefetch]http://xx:8080/dts/test.69
*** Testing: test.01.1 ; url=[cache][prefetch]http://xx:8080/dts/test.01?f64
*** Testing: test.02.1 ; url=[cache][prefetch]http://xx:8080/dts/test.02?b[1:2:10]
....

*** FAIL:  test.02;1;b[1:2:10]
*** Testing: test.03.1 ; url=[cache][prefetch]http://xx:8080/dts/test.03?i32[0:1][1:2][0:2]
syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
...

*** FAIL:  test.03;1;i32[0:1][1:2][0:2]
*** Testing: test.04.1 ; url=[cache][prefetch]http://xx:8080/dts/test.04?types.i32
*** Testing: test.05.1 ; url=[cache][prefetch]http://xx:8080/dts/test.05?types.floats.f32
*** Testing: test.07.1 ; url=[cache][prefetch]http://xx:8080/dts/test.07?person.age
*** Testing: test.07.3 ; url=[cache][prefetch]http://xx:8080/dts/test.07?person
*** Testing: test.07.4 ; url=[cache][prefetch]http://xx:8080/dts/test.07?types.f32
*** FAILED: 20/24 ; 0 expected failures ; 4 unexpected failures
FAIL tst_remote3.sh (exit status: 1)

FAIL: test_varm3
================

**Comment by edhartnett** [comment]
OK, those are dap tests, which might mean the remote server is down, or your system cannot connect to it on the internet. Try adding --disable-dap-remote-tests to configure and build netCDF again.

**Comment by Liu-Richard** [comment]
@edhartnett  Thanks a lot. happy thanksgiving day

**Comment by edwardhartnett** [comment]
I think this issue can be closed. THe problem was a HDF5 install without zlib. We are searching for a way to detect that in configure (see #1557). If we can figure it out, we will detect this in configure. Meanwhile, I note that this was actually detected by the test suite, which is good.

**Comment by WardF** [comment]
Thanks!
