### ISSUE TITLE
Issue building NCO with latest netCDF (related to #1148 ?)

### ISSUE THREAD

**Issue by mathomp4** [Unidata/netcdf-c#1573]
All,

Recently I tried building NCO 4.9.0 with netCDF-C 4.7.3 and encountered this:
```
ld: /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.3-SLES12/x86_64-unknown-linux-gnu/ifort_18.0.5.274-intelmpi_18.0.5.274/Linux/lib/libnetcdf.a(libdispatch_la-dfile.o): in function `nc_open_mem':
/gpfsm/dswdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.3-SLES12/src/netcdf/libdispatch/dfile.c:748: multiple definition of `nc_open_mem'; ./.libs/libnco.a(nco_netcdf.o):nco_netcdf.c:(.text+0x9d0): first defined here
Makefile:980: recipe for target 'ncatted' failed
make[4]: *** [ncatted] Error 1
make[4]: Leaving directory '/gpfsm/dswdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.3-SLES12/src/nco/src/nco'
Makefile:381: recipe for target 'install-recursive' failed
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory '/gpfsm/dswdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.3-SLES12/src/nco/src'
Makefile:443: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/gpfsm/dswdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.3-SLES12/src/nco'
GNUmakefile:823: recipe for target 'nco.install' failed
make[1]: *** [nco.install] Error 2
make[1]: Leaving directory '/gpfsm/dswdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.3-SLES12/src'
GNUmakefile:307: recipe for target 'install' failed
make: *** [install] Error 2
```
This has happened once or twice with NCO and netCDF-C:
https://sourceforge.net/p/nco/discussion/9831/thread/ef2655a6/
https://sourceforge.net/p/nco/discussion/9831/thread/e6faa0b8c1/

These discussions led to #1148 being opened which I believe led to commit 6830cfa4f289601c74b5b8c01768e2d45cd090b7 (given the commit message). However, recently commit 9062af469749492da21c6ac6e8fbfbeb62513415 seems to have reversed it and *removed* that change. 

Was there a reason this was done? I'm going to try building NCO with reverting netCDF-C to 4.7.2 to see if that fixes the build issue.

**Comment by Dave-Allured** [comment]
Recent changes to EXTERNL definition and use of include files are discussed in #1502 and #1507.  This may be related to your build problem.

**Comment by DennisHeimbigner** [comment]
My belief was that we had settled on the rule I articulated in https://github.com/Unidata/netcdf-c/issues/1502.
The multiple-definitions error, however is baffling. There appears to be
only one such definition in the code in dfile.c. Nor does it appear
like dfile.c is being compiled twice in Makefile.am or CMakeLists,txt.
If you look at the logs, it may say where the second definition
is coming from.

**Comment by Dave-Allured** [comment]
Actually the multiple definition is visible in Matt's excerpt above.  The second definition of nc_open_mem comes from nco_netcdf.c as a consequence of an NCO configure problem.

A fix to the configure problem is proposed in one of the NCO discussion threads above.

**Comment by DennisHeimbigner** [comment]
Missed that. so I believe nco can fix without netcdf change.

**Comment by mathomp4** [comment]
Charlie Zender has incorporated @Dave-Allured's [solution](https://sourceforge.net/p/nco/discussion/9831/thread/e6faa0b8c1/#340f/7d78), so I will close this issue.  Thanks all for the help!
