### ISSUE TITLE
nc_test/run_diskless.sh: ncgen fails, and error is concealed

### ISSUE THREAD

**Issue by Dave-Allured** [Unidata/netcdf-c#1576]
### Environment

- Netcdf-C 4.7.3 with HDF5 1.10.5
- Multiple platforms: Linux, Mac OS
- GCC versions 7.3 and 9.2

### Steps to reproduce

- Standard install of netcdf-c 4.7.3
- configure, make, make check
- Capture console output from make check

### Symptoms

1.  Unit test log file contains unexpected ncgen error message.  Also notice the final status on the last line is **PASS**, when **FAIL** should actually be indicated somewhere.
```
... netcdf-c-4.7.3/nc_test 21> tail -4 run_diskless.log 
**** Test extended enhanced diskless netCDF with persistence
**** tst_diskless2.nc created
lt-ncgen: tmp1.cdl line 53: Enumconstant associated with a non-econst type
PASS run_diskless.sh (exit status: 0)
```
2.  Error is not counted in any of the `make check` test summaries.
```
make  check-TESTS
make[2]: Entering directory '/home/.../netcdf-c-4.7.3/nc_test'
make[3]: Entering directory '/home/.../netcdf-c-4.7.3/nc_test'
PASS: t_nc
PASS: tst_small
PASS: nc_test
PASS: tst_misc
PASS: tst_norm
PASS: tst_names
PASS: tst_nofill
PASS: tst_nofill2
PASS: tst_nofill3
PASS: tst_atts3
PASS: tst_meta
PASS: tst_inq_type
PASS: tst_utf8_validate
PASS: tst_utf8_phrases
PASS: tst_global_fillval
PASS: tst_max_var_dims
PASS: tst_formats
PASS: tst_def_var_fill
PASS: tst_err_enddef
PASS: tst_default_format
PASS: tst_diskless6
PASS: run_diskless.sh      <-------------
PASS: run_diskless5.sh
PASS: run_inmemory.sh
PASS: run_cdf5.sh
==================================================================
Testsuite summary for netCDF 4.7.3
==================================================================
# TOTAL: 25
# PASS:  25        <-------------
# SKIP:  0
# XFAIL: 0
# FAIL:  0         <-------------
# XPASS: 0
# ERROR: 0
==================================================================
```

**Comment by Dave-Allured** [comment]
This breaks into two separate issues immediately, but I am reporting them together.

1.  Ncgen fails on an enum inside a compound type.  I am not sure whether this is a real ncgen bug, or a problem in the CDL input.  This appears to be repeatable outside of the test suite.

2.  run_diskless.sh includes an ncdump/ncgen cycle, but fails to properly detect and report a failure within the cycle.

**Comment by DennisHeimbigner** [comment]
Looks like we have alot to fix here. The enum const in a compound
rings a bell. I think this may reflect either an ambiguity in CDL
or a problem in the library.
In any case, I will try to get up to speed on the underlying cause.

**Comment by Dave-Allured** [comment]
This problem was originally found by the [ncgen](https://gitlab.com/remikz/nccmp) test suite:
https://gitlab.com/remikz/nccmp/issues/10

Also there is a little more information and a simple reproducer in the original bug report to netcdfgroup:
https://www.unidata.ucar.edu/mailing_lists/archives/netcdfgroup/2019/msg00113.html

**Comment by Dave-Allured** [comment]
Here are some results from other versions of netcdf-c, including my own tests and other people's reports.

4.4.1.1 -- Correct output file
4.6.2 -- Assertion failure
4.6.3 -- Conflicting reports, fails for me
4.7.0 -- Assertion failure
4.7.2 -- Enum failure
4.7.3 -- Enum failure

So, I guess you would call this a regression.

**Comment by WardF** [comment]
Thanks @Dave-Allured !

**Comment by DennisHeimbigner** [comment]
I think the enum part was fixed by PR https://github.com/Unidata/netcdf-c/pull/2109

**Comment by WardF** [comment]
I believe Dennis is correct, as I am not able to duplicate this issue any longer.
