### ISSUE TITLE
Allow parallel I/O writes to use zlib

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1580]
Allow users to use zlib on parallel writes. This feature is needed urgently by NOAA. No doubt it is desired by many other large data producers.

Large data producers like NOAA are turning to netCDF-4 due to built-in compression. On HPC applications especially, they are writing very large files (10s of GB per file is normal, even with compression).

Since these files are produced on a HPC system, the data start on many processors. Due to the current limitation of the netcdf-c library, they must move all data to one processor, and have that one processor do all compression and writing sequentially. This slows down their very expensive machine!

More importantly, it means that compromises must be made in what is saved. Instead of saving every value that the science team wants, only a subset of values and data are saved. This makes the science harder but makes operations work.

Allowing users to write data compressed with parallel I/O will save them the step of moving all data to one processor, and will also allow the compression to be spread to many processors, instead of just one. This will improve their write time by almost an order of magnitude.

Decrease in I/O time leads to increased time for computation, allowing the science team to increase resolution or use more intensive algorithms, and still meet operational requirements. 

Thus improving the I/O times directly impacts the science.

**Comment by edwardhartnett** [comment]
In case anyone is interested, this had a major and positive impact for the GFS. The following is from Jun Wang at NOAA.

Total write time for one forecast hour has been reduced from 550s to 150s.

> The latest results for C768L127,
> Here are results from C768L127, results look promising. Writing the 3D file atmf file speeds up ~15 times (450s down to 30s), while 2D surface file writing increases 60% (45s to 70s). Total time on writing grid comp (writing 2 history files and inline post) for one forecast hour is reduced from 550s->150s. Inline post takes 50s in both runs.
> 
> file size 
> parallel writing:  slightly increased 
> -rw-r--r-- 1 Jun.Wang g01 6680866372 Jan 22 11:45 atmf000.nc
> -rw-r--r-- 1 Jun.Wang g01 6769628821 Jan 22 11:48 atmf001.nc
> -rw-r--r-- 1 Jun.Wang g01 6675425724 Jan 22 11:51 atmf002.nc
> -rw-r--r-- 1 Jun.Wang g01 1060341025 Jan 22 11:46 sfcf000.nc
> -rw-r--r-- 1 Jun.Wang g01 1026448059 Jan 22 11:49 sfcf001.nc
> -rw-r--r-- 1 Jun.Wang g01 1044235908 Jan 22 11:52 sfcf002.nc
> 
> No parallel writing:
> -rw-r--r-- 1 Jun.Wang g01 6677616851 Jan 21 22:29 atmf000.nc
> -rw-r--r-- 1 Jun.Wang g01 6778890732 Jan 21 22:31 atmf001.nc
> -rw-r--r-- 1 Jun.Wang g01 6663228925 Jan 21 22:33 atmf002.nc
> -rw-r--r-- 1 Jun.Wang g01 1049063514 Jan 21 22:30 sfcf000.nc
> -rw-r--r-- 1 Jun.Wang g01 1015687585 Jan 21 22:32 sfcf001.nc
> -rw-r--r-- 1 Jun.Wang g01 1033478036 Jan 21 22:34 sfcf002.nc
> 
> Parallel:
> parallel netcdf Write Time is 33.48398 at Fcst 00:00
> parallel netcdf Write Time is 69.58479 at Fcst 00:00
> parallel netcdf Write Time is 30.34695 at Fcst 01:00
> parallel netcdf Write Time is 70.54954 at Fcst 01:00
> parallel netcdf Write Time is 29.85357 at Fcst 02:00
> parallel netcdf Write Time is 71.57624 at Fcst 02:00
> 
> No parallel writing:
> netcdf Write Time is 426.01005 at Fcst 00:00
> netcdf Write Time is 43.87808 at Fcst 00:00
> netcdf Write Time is 454.70615 at Fcst 01:00
> netcdf Write Time is 48.44027 at Fcst 01:00
> netcdf Write Time is 448.26954 at Fcst 02:00
> netcdf Write Time is 46.95907 at Fcst 02:00
>

**Comment by WardF** [comment]
Thanks for sharing the results, @edwardhartnett !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
