### ISSUE TITLE
Can more than one filter be applied to a variable?

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1584]
I have been using the filter code to explore new compression filters. It's very nice! Thank you @DennisHeimbigner 

It seems as though nc_def_var_filter() and associated code is written to handle just one filter on the var. Yet the filter concept, as described by the HDF5 team, is that multiple filters can be applied.

The one use case for this is the proposed quantization filter (or "bit grooming" to use Charlie's term). The bit grooming filter only makes sense when combined with a compression filter. Other use cases can be imagined, but the bit grooming one is the most important.

So can more than one filter be applied?

**Comment by czender** [comment]
Concrete example is that `h5repack` supports sequential filter chains:

`h5repack -i in.nc -o out.h5 --filter=var:UD=32017,1,3 --filter=var:UD=32015,1,5`

Think of first as lossy and second as lossless. By including `szip` it is possible to imagine useful chains of up to three filters. An API that permits multiple filters would be helpful. The current workaround would seem to be a filter that takes the arguments for itself and a second filter, and the glue code parses that and calls both filters. That is my current plan for quantization, though it is an untested idea at this point.
