### ISSUE TITLE
HDF4 files not available on Unidata ftp site?

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1600]
There is an extra set of HDF4 tests, which use some HDF4 files from the Unidata FTP site. These tests are only run of HDF4 is present and enabled. In autotools build, these extra tests are only run if --enable-hdf4-file-tests is used, in the CMake build, these extra tests are always run when HDF4 is present.

The script  hdf4_test/run_get_hdf4_files.sh is failing.

Here's the output of the attempt:

```
+ wget -c --passive-ftp ftp://ftp.unidata.ucar.edu/pub/netcdf/sample_data/hdf4/AMSR_E_L2_Rain_V10_200905312326_A.hdf.gz
--2020-01-17 10:48:40--  ftp://ftp.unidata.ucar.edu/pub/netcdf/sample_data/hdf4/AMSR_E_L2_Rain_V10_200905312326_A.hdf.gz
           => ‘AMSR_E_L2_Rain_V10_200905312326_A.hdf.gz’
Resolving ftp.unidata.ucar.edu (ftp.unidata.ucar.edu)... 128.117.149.10
Connecting to ftp.unidata.ucar.edu (ftp.unidata.ucar.edu)|128.117.149.10|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/netcdf/sample_data/hdf4 ... 
No such directory ‘pub/netcdf/sample_data/hdf4’.

```

It seems that the directory pub/netcdf/sample_data is no longer present on the FTP site. Has it been moved, or deleted?

@oxelson is this related to your recent pull request?

This is causing Travis builds to fail, as well as many builds in my Jenkins CI system.

**Comment by oxelson** [comment]
@edwardhartnett - not related to my PR.  However, we just did a manor cleanup of our ftp file system and the sample_data directory was moved offline.  It has been restored.  Are there any other dependencies in the netcdf ftp directory?  If not, rerun travis as it should find this data now.

**Comment by edwardhartnett** [comment]
Thanks Jen! I will rerun and let you know if there are any further issues. ;-)
