### ISSUE TITLE
netCDF_LIBRARIES name in Config file does not have namespace prefix

### ISSUE THREAD

**Issue by raovgarimella** [Unidata/netcdf-c#1607]
Version netCDF 4.7.3
Ubuntu 18.04
CMake 3.14.5
gcc 9.1.0

```netCDFConfig.cmake``` sets ```netCDF_LIBRARIES``` as ```netcdf``` like so:

```set(netCDF_LIBRARIES netcdf)``` 

but ```netCDFTargets.cmake``` sets the dependencies of target ```netCDF::netcdf``` like so:

```
add_library(netCDF::netcdf STATIC IMPORTED)

set_target_properties(netCDF::netcdf PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "/home/scratch/TPLs-0.97.1-gcc-9.1.0-ompi-3.1.4-aaa/lib/libhdf5_hl.a;/home/scratch/TPLs-0.97.1-gcc-9.1.0-ompi-3.1.4-aaa/lib/libhdf5.a;dl;/usr/lib/x86_64-linux-gnu/libm.so;/home/scratch/TPLs-0.97.1-gcc-9.1.0-ompi-3.1.4-aaa/lib/libz.a"
)
```

So if I set ```${netCDF_LIBRARIES}``` as a dependency of a library I am building, it will not pick up the transitive dependencies (namely HDF5 libraries etc).

Fix - ```netCDFConfig.cmake``` should write out:
```set(netCDF_LIBRARIES netCDF::netcdf)```

**Comment by WardF** [comment]
Thanks! I'll take a look at updating this.
