### ISSUE TITLE
Missing percent sign in format docs

### ISSUE THREAD

**Issue by Dave-Allured** [Unidata/netcdf-c#1609]
There is a typo in the on-line NetCDF User's Guide, [NetCDF Classic Format Specification](https://www.unidata.ucar.edu/software/netcdf/docs/file_format_specifications.html).  In the specs for netCDF object names, the percent sign is missing in this line:

`special2 = ' ' | '!' | '"' | '#'  | '$' | '' | '&' | '\'' |`

Notice that the sixth item currently shows as two single quotes.  In "older documentation", this position has a percent sign inside the quotes:  `'%'`.  It looks like this was somehow accidentally deleted.  Please restore.  Thanks.

**Comment by Dave-Allured** [comment]
Strange.  I looked in master on Github.  In `netcdf-c/docs/file_format_specifications.md`, the percent sign is present.

* Is the on-line version sourced from this same file?
* Is conversion of *.md to HTML somehow eating this percent sign?

**Comment by Dave-Allured** [comment]
Percent sign is missing in two browsers on my Mac desktop:  Safari and Firefox.

Also, "Show Document Source" shows missing percent sign in the raw HTML, as received.

**Comment by WardF** [comment]
Thanks @Dave-Allured let me take a look at it from my end.

**Comment by WardF** [comment]
I suspect that doxygen is eating the sign.  I'll confirm locally and address. Thanks!

**Comment by WardF** [comment]
Managing another PR, worked this in with it since it was a minor change.  #1611

**Comment by Dave-Allured** [comment]
Looks good.  Thanks.  Closing.
