### ISSUE TITLE
can NOAA get a release of netcdf-c with the latest zlib/szip features?

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1610]
@WardF, the NOAA operational team (from back East) have asked me to ask whether there can be a netcdf-c library release within the next month or so? And if not, then when can there be a release?

The recent changes to zlib/szip compression have made a big difference for them, and they want to release that (already delayed) code into operations and to the science community,. The slow sequential compression was a big roadblock to their release, and now it is gone.

Their goal in this release is to give the community netcdf-based data files, for greater ease of use in the science community.

However, they cannot release code that depends on the netcdf-c master branch, they need to specify a formal release. While they can build and use the master branch, for the purposes of scientific reproducability, they really need a release version.

So any information you can provide would be helpful, and I will pass it along to the NOAA team. If there is anything I can do to help, please let me know.

**Comment by DennisHeimbigner** [comment]
Ideally, I would like to hold off until I get my multiple filter fixes
incorporated.

**Comment by jswhit** [comment]
How about creating a tag for us?

**Comment by WardF** [comment]
@DennisHeimbigner is there an approximate timeline for these filter fixes? Thanks! -Ward

**Comment by DennisHeimbigner** [comment]
I am in testing now. Should issue an initial PR in a day or so.
=Dennis

**Comment by edwardhartnett** [comment]
The next netcdf release is of interest to leadership at the Environmental Modeling Center (EMC). (Those are the guys that do the operational weather forecasts.) 

I have explained to them that I am no longer working for Unidata; that I don't influence the team, nor do I have any access to team planning.

They are in charge of a serious operational system and are used to things being planned far in advance. They are not looking for a firm commitment to any date, but just asking if there will be a release in the next few months.

I'm sure they would welcome any information you wish to provide.

**Comment by WardF** [comment]
We will have a release out shortly; just working on a few details. Feel free to put them in contact (or message me your contact their offline if you prefer) and I'll reach out and give them the details.  Thanks Ed, appreciate it!

**Comment by edwardhartnett** [comment]
Thanks, I have let them know that you are the one to contact for release info. You may get contacted. ;-)

I have also relayed the news that a release will be out reasonably soon. This is all they are immediately concerned about. Their next release goes out in a couple months, and they are counting on the szip and parallel zlib being present in a formally released netcdf-c by then. They are currently testing with netcdf-c and netcdf-fortran master branch, but they would like to specify an actual release for their eventual users. 

Thanks for all your hard work and thanks for merging my PRs. These changes are making netcdf considerably more performant for high-volume data producers like NOAA.
