### ISSUE TITLE
nc_def_var_filter() should say in docs that it will cause vars to be switched to chunking

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1612]
Filters only work with chunked data.

nc_def_var_filter() needs to check that a var is chunked and return NC_EINVAL when an attempt is made to set a filter on a contiguous (or compact) variable.

I have a fix and will put a PR up shortly.

**Comment by edwardhartnett** [comment]
OK, what actually happens is that the var is silently converted to chunked. This should be mentioned in the documentation for nc_def_var_filter().

**Comment by DennisHeimbigner** [comment]
I noticed that code. Perhaps it would be better to not
do the change to chunked and report the error.

**Comment by edwardhartnett** [comment]
For all the built-in filters, we do the same - we silently convert the variable to chunked. This seems like it's working out, and I think it would be least confusing if the user-defined filters work the same way.

So I suggest we document this and leave it alone.

**Comment by DennisHeimbigner** [comment]
ok
