### ISSUE TITLE
need to fix output for szip in cmake build

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1617]
Here's some output from the cmake build. Note that the szip fields are blank, instead of "no".
```
# Features
514--------
515NetCDF-2 API:		yes
516HDF4 Support:		yes
517HDF5 Support:		yes
518NetCDF-4 API:		yes
519NC-4 Parallel Support:	no
520PnetCDF Support:	no
521DAP2 Support:		yes
522DAP4 Support:		yes
523Byte-Range Support:	no
524Diskless Support:	yes
525MMap Support:		yes
526JNA Support:		no
527CDF5 Support:		yes
528ERANGE Fill Support:	yes
529Relaxed Boundary Check:	yes
530SZIP Support:           
531SZIP Write Support:     
532Parallel Filters:       no
```

**Comment by DennisHeimbigner** [comment]
It also appears this happens for automake when netcdf4 is disabled.

**Comment by WardF** [comment]
I'm working on a branch, I can fix this. Thanks!

**Comment by DennisHeimbigner** [comment]
I see that parallel filter support is also blank because the
corresponding AC_SUBST is inside the test for netcdf4.
It should be moved to be with the other block of AC_SUBST
definitions.
