### ISSUE TITLE
Semantics of Names within CDL and NC API

### ISSUE THREAD

**Issue by marqh** [Unidata/netcdf-c#1638]
Hello Unidata Folks

I have a question regarding the semantics of the root group name within the netCDF C API.

Specifically, is the name given to a root group a semantic entity?
Is it accessible via the API?
Is it part of the identity of entities within the file?

For example, consider the file defined in CDL:
https://www.unidata.ucar.edu/software/netcdf/examples/test_hgroups.cdl

This declares:
```
netcdf test_hgroups {
...
}
```
Is the string `test_hgroups` accessible via the API, once this CDL file is encoded into a HDF5 NC encoding?

Is this name a semantic part of the dataset?

If I choose to identify the file it's location:
https://www.unidata.ucar.edu/software/netcdf/examples/test_hgroups.nc

should i identify the root group as:
1. https://www.unidata.ucar.edu/software/netcdf/examples/test_hgroups.nc
1. https://www.unidata.ucar.edu/software/netcdf/examples/test_hgroups.nc/
1. https://www.unidata.ucar.edu/software/netcdf/examples/test_hgroups.nc/test_hgroups
1. ...
?

Please may you offer some insight or advice on this topic for me?

many thanks
mark

**Comment by DennisHeimbigner** [comment]
Good question. That name (e.g. netcdf <name> {)
currently is not semantically meaningful and in fact is
not stored in the .nc file at all.
For all netcdf files, the name of the root group is '/'.
What is available is the file path that was used to
nc_open() the file.

**Comment by marqh** [comment]
Hello @DennisHeimbigner 

that's really helpful thank you

based on ongoing research, my current perspective on the example suggests:

* https://www.unidata.ucar.edu/software/netcdf/examples/test_hgroups.nc
    * this is the identifier of the file
* https://www.unidata.ucar.edu/software/netcdf/examples/test_hgroups.nc/
    * this is the identifier for the root group within the file
    * (usefully, for the unidata website implementation, this identifier 404s as a location)

I think that differentiating between the file identifier and the root group identifier is important, and that using the trailing slash to indicate that this is file content is useful.

given:
>  That name -- e.g. netcdf <name> {...} -- currently is not semantically meaningful and in fact is not stored in the .nc file at all.

I think that this explicitly takes this 'name' out of consideration

I'll close this ticket, as I am happy that the question is resolved cleanly

much obliged
mark
