### ISSUE TITLE
nc-config --static not providing expected information

### ISSUE THREAD

**Issue by simonpf** [Unidata/netcdf-c#1641]
netcdf version:   netCDF 4.7.4-development
cc:                     GCC 9.2.0
os:                     Arch Linux
kernel:               Linux 5.4.8-arch1-1

nc-config displays different information for `--static` when used with `--all` and `--static` flags. This is the output for `--all`:

````
$ nc-config --all

This netCDF 4.7.4-development has been built with the following features: 

  --cc            -> /usr/bin/cc
  --cflags        -> -I/usr/local/include
  --libs          -> -L/usr/local/lib -lnetcdf
  --static        -> -lhdf5_hl -lhdf5 -lrt -lpthread -lz -ldl -lm -lsz -lcurl

  --has-c++       -> no
  --cxx           -> 

  --has-c++4      -> no
  --cxx4          -> 

  --has-fortran   -> no
  --has-dap       -> yes
  --has-dap2      -> yes
  --has-dap4      -> yes
  --has-nc2       -> yes
  --has-nc4       -> yes
  --has-hdf5      -> yes
  --has-hdf4      -> no
  --has-logging   -> no
  --has-pnetcdf   -> no
  --has-szlib     -> no
  --has-cdf5      -> yes
  --has-parallel4 -> no
  --has-parallel  -> no

  --prefix        -> /usr/local
  --includedir    -> /usr/local/include
  --libdir        -> /usr/local/lib
  --version       -> netCDF 4.7.4-development
````

But when called with `--static` no output is produced:

````
$ nc-config --static

````

I suspect the reason for this is that the case for [--static](https://github.com/Unidata/netcdf-c/blob/867caa288d29e64ac3b451c82527dfec2bd29f67/nc-config.cmake.in#L357) is empty. If that's confirmed I am happy to turn this into a PR.

**Comment by WardF** [comment]
What happens if you invoke `nc-config —static —libs`, is it still blank?

**Comment by WardF** [comment]
My iPad is “autocorrecting” the double dash above, but take it as read that I typed the correct syntax for using both the `static` and `libs` arguments to `no-config` :)

**Comment by simonpf** [comment]
For `nc-config --static --libs` the output is:

````
-L/usr/local/lib -lnetcdf -lhdf5_hl -lhdf5 -lrt -lpthread -lz -ldl -lm -lsz -lcurl
````

OK, so it was rather just me using `nc-config` improperly. Thanks for the heads up!
