### ISSUE TITLE
compact storage not correctly handled by ncdump

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1642]
Compact storage is a new (to netcdf-c) storage option for HDF5 datasets (in addition to chunked and contiguous). Compact storage is significantly faster for large HPC systems, but only small, fixed vars can be compact.

I am adding compact storage to fortran and I noticed that ncdump does not correctly handle compact storage.

I am adding test (in netcdf-fortran) nf_test4/ftst_var_compact.F and I create a variable with compact storage. This is confirmed by h5dump -p:

```
   DATASET "var1" {
      DATATYPE  H5T_STD_I32LE
      DATASPACE  SIMPLE { ( 22 ) / ( 22 ) }
      STORAGE_LAYOUT {
         COMPACT
         SIZE 88
      }

```
But ncdump -h -s shows:

`		var1:_Storage = "chunked" ;`

**Comment by DennisHeimbigner** [comment]
Is compact storage contiguous, then?

**Comment by edwardhartnett** [comment]
Compact is a new type of storage, so where there used to be chunked or contiguous,  now there is chunked, contiguous,  or compact.

**Comment by DennisHeimbigner** [comment]
Supporting compact will have a noticeable code impact.
Everywhere we now access contiguous vs chunked, we will
have to add this 3rd option

**Comment by edwardhartnett** [comment]
I believe this has already been done everywhere except ncgen/ncdump.

**Comment by DennisHeimbigner** [comment]
I see. I will add to ncgen and ncdump.
I must confess that I am unhappy about having this show
thru the netcdf-c API.

**Comment by edwardhartnett** [comment]
It is required to show through the API, so that users can select it. ;-)

This will be a very popular thing for coordinate vars on HPC systems, because it is a lot quicker to read from many, many processors. Since all programs tend to read the coord vars, the cumulative savings in read time can be significant. 

The original issue, suggested by @gsjaardema, has a graph. See #1568

**Comment by DennisHeimbigner** [comment]
My point is that it has no semantics independent of HDF5.

**Comment by edwardhartnett** [comment]
Well neither does chunking. 

If you want to consider what it would be like in other formats, I imagine the same - it would be data stored with the metadata that is read at file startup. So reading compact data is very quick because it has already been read.

**Comment by DennisHeimbigner** [comment]
Chunking does have a semantics independent of HDF5.
It is true that HDF5 invented it (I think), but e.g.
the zarr implementation is not hdf5 and has chunking.
WRT
> - it would be data stored with the metadata that is read at file startup.
I do not think the concept of "stored with metadata' has meaning since it
explicitly refers to storage and cannot be defined independently of the
implementation.

**Comment by edwardhartnett** [comment]
Most file formats read some metadata at startup. The concept of stored with metadata can apply for many file formats. 

Just as chunking only existed in HDF5 until Zarr came along, 15 years later, we may wait some years before another storage format uses compact storage, but I believe it can be understood separately from the HDF5 model. If desired, compact vars could be implemented in a classic format, for example, with the same effect.

**Comment by DennisHeimbigner** [comment]
Well, it is done, I guess.
Question: currently the nccopy code only pays attention to chunked/contig
if the variable is not scalar. Can a scalar variable be compact?

**Comment by edwardhartnett** [comment]
No, scalar cannot be compact.

**Comment by edwardhartnett** [comment]
I have to take that back. I was wrong, scalars can be compact in HDF5.

**Comment by DennisHeimbigner** [comment]
Are you adding a test for the scalar case?

**Comment by edwardhartnett** [comment]
Yes, also some documentation. I got confirmation from the HDF5 team that scalar should work for continuous and compact, but not chunked data.

Looks like our code will silently ignore an attempt to set chunking on a scalar. I will document this behavior.

**Comment by DennisHeimbigner** [comment]
Ok, I have a branch that fixes the utilities.
Will PR it when other stuff clears.
