### ISSUE TITLE
CMake based builds now failing on master with tests tst_nccopy4 and tst_h_vars

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1651]
Since the merge of the multiple filters changes to  master, all my cmake builds are failing like this:

```
The following tests FAILED:
	 34 - ncdump_tst_nccopy4 (Failed)
	148 - tst_h_vars (Failed)
```

Meanwhile, the travis CMake builds are working. So there is a mystery here. I will look into it on Monday...

**Comment by DennisHeimbigner** [comment]
Try adding set -x to ncdump/tst_nccopy4.sh
and see if the output shows exactly what command is failing.

**Comment by edwardhartnett** [comment]
Well this is weird.

```
+ echo '*** Test nccopy -d1 can compress a classic format file ...'
*** Test nccopy -d1 can compress a classic format file ...
+ /home/ed/noaa/netcdf-c/build/ncdump/nccopy -d1 tst_inflated.nc tst_deflated.nc
++ wc -c
++ wc -c
+ test 48240 -ge 40080
+ exit 1
```

Also, the error in tst_h_vars is weird. It's getting an unknown filter for the name of the deflate filter.

All this only happens in the CMake build. The autotools build works fine. All this worked fine before your merge.

But I cannot see anything that you did which could affect the h5_test directory. It doesn't depend on any code from the other directories. So what's going on?

**Comment by edwardhartnett** [comment]
Here's how I'm doing my build, in case you want to try it:


```
ed@mikado:~/noaa/netcdf-c/build$ export HDF5_INCLUDE_DIR=/usr/local/hdf5-1.10.6/include
ed@mikado:~/noaa/netcdf-c/build$ export HDF5_HL_LIBRARY=/usr/local/hdf5-1.10.6/lib/hdf5_hl.so
ed@mikado:~/noaa/netcdf-c/build$ export HDF5_LIB=/usr/local/hdf5-1.10.6/lib/hdf5.so
ed@mikado:~/noaa/netcdf-c/build$ cmake -DCMAKE_FIND_ROOT_PATH=/usr/local/hdf5-1.10.6 -DENABLE_DAP_REMOTE_TESTS=Off ..
ed@mikado:~/noaa/netcdf-c/build$ make
ed@mikado:~/noaa/netcdf-c/build$ make test
```

**Comment by edwardhartnett** [comment]
Could this be a test environment issue on my machine? But it happens with all versions of HDF5...

Dennis, can you tell me what is in your plugin directory? Mine is empty.

But since zlib is built in to HDF5 that should not matter. 

Also, no matter how far back I take the code, the error occurs. So it's not the code, it's my machine. Something weird is going on with HDF5 filters on my machine?

**Comment by DennisHeimbigner** [comment]
You are right. Since the test uses deflate, it should not matter about
the plugins directory. It is barely possible that you did not
set HDF5_PLUGIN_PATH  env variable  and that is causing the problem,
but I am very sceptical of that. Try running the actual command with
logging enabled and see if you are getting HDF5 warnings.

**Comment by DennisHeimbigner** [comment]
Since this is cmake, can you send me the cmake build output?
My bet is that filters are being disabled.

**Comment by edwardhartnett** [comment]
Seems like this must be an artifact of my machine, not the code base. I am continuing to investigate.

@DennisHeimbigner you would seem to lose that bet. Filter testing seems to be happening. I will let you know more once I get it figured out.

**Comment by edwardhartnett** [comment]
OK, after a total rebuild of my test environment, this problem has gone away. I have been messing about with HDF5 filters, so perhaps I did something strange.
