### ISSUE TITLE
--enable-large-file-tests build now failing on master in tst_h_files

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1652]
Here's another weird one. When I build with --enable-large-file-tests, the build now fails in tst_h_files:

```
ed@mikado:~/noaa/netcdf-c/h5_test$ ./tst_h_files

*** Checking HDF5 file functions.
*** Checking HDF5 file creates and opens...ok.
*** Checking HDF5 file creates and opens some more...ok.
*** Creating file...ok.
*** large file test for HDF5...Sorry! Unexpected result, tst_h_files.c, line: 367
```

When I look at the test code I see:
```
        /* Reopen the file and check it. */
        if ((fileid = H5Fopen(file_name, H5F_ACC_RDWR, H5P_DEFAULT)) < 0) ERR;
        if (H5Gget_num_objs(fileid, &num_obj) < 0) ERR;
        if (num_obj) ERR;
        if (H5Fclose(fileid) < 0) ERR;

```

The line that's causing the error is:

`        if (num_obj) ERR;
`

I've got no idea what this is all about.

**Comment by edwardhartnett** [comment]
OK, this one is on me. ;-)

I uncommented that section of code in a test. That broke largefile tests. I guess there was a good reason that code was commented out. Instead, I have removed it. Now largefile tests work.

I have added this to my current PR.

**Comment by DennisHeimbigner** [comment]
I tried cmake under ubuntu and cannot duplicate the tst_nccopy4.sh failure.
I infer from the error that compression was not actually applied.
No idea why it wasn't being applied in you build.
