### ISSUE TITLE
CMake build not properly finding H5free_memory and other functions

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1665]
I found this while trying to get the build with HDF5 1.12.0 working in CMake.

CMakeLists.txt contain the following:

```
  CHECK_LIBRARY_EXISTS(${HDF5_C_LIBRARY_hdf5} H5Pset_libver_bounds "" HAVE_H5PSET_LIBVER_BOUNDS)
  CHECK_LIBRARY_EXISTS(${HDF5_C_LIBRARY_hdf5} H5free_memory "" HAVE_H5FREE_MEMORY)
  CHECK_LIBRARY_EXISTS(${HDF5_C_LIBRARY_hdf5} H5allocate_memory "" HAVE_H5ALLOCATE_MEMORY)
  CHECK_LIBRARY_EXISTS(${HDF5_C_LIBRARY_hdf5} H5resize_memory "" HAVE_H5RESIZE_MEMORY)
```

The problem I found relates to H5free_memory() but also seems to apply to the other functions here.

With 1.10.6 H5free_memory() is present, and properly detected by autotools, but CMake does not correctly set the result in the config.h file:

```
/* if true, H5free_memory() will be used to free hdf5-allocated memory in
   nc4file. */
/* #undef HAVE_H5FREE_MEMORY */

```

Looking in CMakeError.log I see:

```
Determining if the function H5allocate_memory exists in the hdf5 failed with the following output:
Change Dir: /home/ed/netcdf-c/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_c043e/fast"
/usr/bin/make -f CMakeFiles/cmTC_c043e.dir/build.make CMakeFiles/cmTC_c043e.dir/build
make[1]: Entering directory '/home/ed/netcdf-c/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c043e.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=H5allocate_memory   -o CMakeFiles/cmTC_c043e.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_c043e
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c043e.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=H5allocate_memory    CMakeFiles/cmTC_c043e.dir/CheckFunctionExists.c.o  -o cmTC_c043e -lhdf5 
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_c043e.dir/build.make:97: recipe for target 'cmTC_c043e' failed
make[1]: *** [cmTC_c043e] Error 1
make[1]: Leaving directory '/home/ed/netcdf-c/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_c043e/fast' failed
make: *** [cmTC_c043e/fast] Error 2

```

So it looks like the HDF5 include directory is not being set correctly when the test for H5free_memory() is attempted to be compiled.

@WardF this is beyond my CMake knowledge, can you help?

**Comment by WardF** [comment]
I'll take a look

**Comment by WardF** [comment]
At a glance, I'm not seeing this issue but I am testing against 1.10.x and 1.8.x; it is detecting H5free_memory()  (or its absence) properly.  We don't have any systems with 1.12.x installed, as 1.12.x support is low on our priority list (but reviewing PR's certainly makes it easier ;)).  I'll try to install it tomorrow and see what behavior is exhibited. 

The HDF5 support in our cmake files is a bit convoluted due to inconsistencies in the cmake HDF5 support between hdf5 versions, and platforms.  I won't be surprised if we need to add a stanza specific to 1.12.x.  Let me dig in and see what's going on. Thanks!

**Comment by brtnfld** [comment]
@WardF Do you need my help, or is there anything I can do?

**Comment by WardF** [comment]
@brtnfld I've been focused on other priorities, but let me pull this up now and see if I can duplicate the issue with 1.12.x. I'll follow up here shortly :)

**Comment by WardF** [comment]
I'm finding the folllowing in the `config.h` generated by cmake using either 1.12.x or 1.10.6.

````
/* if true, H5free_memory() will be used to free hdf5-allocated memory in
   nc4file. */
#define HAVE_H5FREE_MEMORY 1
````

From `CMakeOutput.log` I'm seeing the following:

````
Determining if the function H5allocate_memory exists in the hdf5 passed with the following output:
Change Dir: /Volumes/Workspace/gitprojects/netcdf-c/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_6f846/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_6f846.dir/build.make CMakeFiles/cmTC_6f846.dir/build
Building C object CMakeFiles/cmTC_6f846.dir/CheckFunctionExists.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -I/Users/wfisher/environments/local-serial-1.12.0/include -DCHECK_FUNCTION_EXISTS=H5allocate_memory -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fPIE   -o CMakeFiles/cmTC_6f846.dir/CheckFunctionExists.c.o   -c /opt/local/share/cmake-3.16/Modules/CheckFunctionExists.c
Linking C executable cmTC_6f846
/opt/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6f846.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -I/Users/wfisher/environments/local-serial-1.12.0/include -DCHECK_FUNCTION_EXISTS=H5allocate_memory -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/Users/wfisher/environments/local-serial-1.12.0/lib  CMakeFiles/cmTC_6f846.dir/CheckFunctionExists.c.o  -o cmTC_6f846  -lhdf5
````


@edwardhartnett how are you invoking cmake?

**Comment by edwardhartnett** [comment]
To build:

```
export HDF5_INCLUDE_DIR=/usr/local/hdf5-1.10.6_szip/include
export HDF5_HL_LIBRARY=/usr/local/hdf5-1.10.6_szip/lib/hdf5_hl.so
export HDF5_LIB=/usr/local/hdf5-1.10.6_szip/lib/hdf5.so
rm -rf build
mkdir build
cd build
cmake -DCMAKE_FIND_ROOT_PATH=/usr/local/hdf5-1.10.6_szip -DENABLE_DAP_REMOTE_TESTS=Off ..
make
make test
```

OK, this is a bit weird. But here's what the config.h file says in my 1.10.6 build:

```
/* if true, H5free_memory() will be used to free hdf5-allocated memory in
   nc4file. */
/* #undef HAVE_H5FREE_MEMORY */
```
So it is certainly not finding H5free_memory() for me. But this only causes errors on the 1.12.0 build. That is, my 1.10.6 build does not fail, even though apparently H5free_memory() is not correctly found.

I will try to add memory checking and see if that turns up anything...

**Comment by WardF** [comment]
If you're doing this in a parallel environment, which I assume you probably are, you should also specify:

* -DCMAKE_C_COMPILER=mpicc

That might explain why it's not finding the "right" hdf5? At least, when I do parallel testing and it fails to find hdf5, it's often because I forgot to specify the compiler to use.

**Comment by edwardhartnett** [comment]
This is not a parallel build, it's a sequential build. I have not tried parallel with CMake since I rebuilt my testing system last week. I will add it next.

When you run on your system with those same CMake commands it find H5free_memory() for you?

**Comment by edwardhartnett** [comment]
I will submit this work as a PR and we will see what Travis does...

**Comment by WardF** [comment]
Let me set up a temp environment using the same pathing you're using; I use a local directory and set (for example):

* `CMAKE_PREFIX_PATH=${HOME}/environments/local-serial-1.10.6`

instead of specifying `HDF5_INCLUDE_DIR`, `HDF5_HL_LIBRARY` and `HDF5_LIB` explicitly, where the prefix path contains the standard `lib/`, `include/`, `bin/`, `share/` directory structure.

**Comment by edwardhartnett** [comment]
OK, this seems to only be happening to me. CMake, why do you hate me? (But, I'll admit, it's a mutual hatred.)

I will close this ticket.
