### ISSUE TITLE
problem opening file with Chinese chars in path

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf-c#1666]
Reported in https://github.com/Unidata/netcdf4-python/issues/997

Consider this test script:

```python
import netCDF4, os
dirpath1 =\
b'\xe6\xb5\xb7\xe6\xb4\x8b\xe6\x8e\xa2\xe6\xb5\x8b\xe6\x8a\x80\xe6\x9c\xaf\xe4\xb8\x93\xe9\xa2\x98\xe5\xae\x9e\xe9\xaa\x8c'.decode('utf-8')
dirpath2 =\
b'\xe4\xb8\x93\xe9\xa2\x98\xe5\xae\x9e\xe9\xaa\x8c\xe5\x85\xab'.decode('utf-8')
dirpath = os.path.join(dirpath1,dirpath2)
os.makedirs(dirpath,exist_ok=True)
filename=os.path.join(dirpath,'V2019151040600.L2_SNPP_OC.nc')
print(filename)
nc = netCDF4.Dataset(filename,'w')
nc.filename = filename
nc.close()
nc = netCDF4.Dataset(filename)
```

The file is created, but a `Permission denied` error is raised when the file is read back in.  
The file can be read via h5dump or h5py, but ncdump cannot see it (`No such file or directory`).  

h5dump 海洋探测技术专题实验/专题实验八/V2019151040600.L2_SNPP_OC.nc works
ncdump 海洋探测技术专题实验/专题实验八/V2019151040600.L2_SNPP_OC.nc does not.

**Comment by DennisHeimbigner** [comment]
This issue came up once before (in esupport, I think). I do not recall the
 resolution, so let me see if I can find it.

**Comment by DennisHeimbigner** [comment]
Cannot find it. Does anyone else recall the previous resolution?

**Comment by DennisHeimbigner** [comment]
Found the problem (or at least one of them).
The path handling code in NC_create and NC_open (dfile.c)
is improperly handling whitespace. Will have fix up shortly.

**Comment by DennisHeimbigner** [comment]
I am uploading a revised libdispatch/dfile.c
Can someone see if it fixes the problem for them?
[dfile.zip](https://github.com/Unidata/netcdf-c/files/4314811/dfile.zip)

**Comment by jswhit** [comment]
Dennis - that does seem to fix it.

**Comment by DennisHeimbigner** [comment]
ok, I will submit the PR for it.
