### ISSUE TITLE
When does CDL include data type specifier 'string' in global attributes?

### ISSUE THREAD

**Issue by hyoklee** [Unidata/netcdf-c#167]
Hi,

If you ncdump the test file [1], the "string" appears in global attributes for non-scalar string attributes. 

```
netcdf test {
dimensions:
	phony_dim_0 = 10 ;
variables:
	string vldset1(phony_dim_0, phony_dim_0) ;

// global attributes:
		string :vlattr = "does", "it work" ;
		string :vlattr2 = "does" ;
		:vlattr3 = "does" ;
}
```

I'm wondering if it's the correct and consistent behavior and why ncdump adds "string" for some attributes. Does ncgen handle attributes with data type specifier differently? 

[1] https://gamma.hdfgroup.org/ftp/pub/outgoing/joe/data/github/test.h5

**Comment by WardF** [comment]
Hello @hyoklee , I need to confirm this but I believe what is happening is that `vlattr3` is a fixed-length string (`STRSIZE 5`) and is therefore treated as a character array by netcdf, whereas `vlattr` and `vlattr2` are variable-length strings (`STRSIZE H5T_VARIABLE`).

This is supported by running ncgen to generate C code (`ncgen -l c -k 3 test.h5.cdl`); in the generated code, I see `nc_put_att_string()` used for `vlattr` and `vlattr2`, and `nc_put_text()` for `vlattr3`.

So to answer your question, yes, this appears to be correct and consistent behavior, and yes ncgen handles attributes with data type specifiers differently.

**Comment by WardF** [comment]
Having said that, I am happy to be corrected if @dmh or @russrew can say differently.

**Comment by hyoklee** [comment]
Thanks @WardF for the quick answer!
