### ISSUE TITLE
nc_inq_var_deflate() no longer returns 0 for deflate_level when deflate is not in use

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1673]
Although there was no test for this in the C library, netcdf-fortran tests depend on 0 being returned for deflate_level when deflate is not in use. This used to be the case, but is no longer happening. 

I will submit a PR shortly.

**Comment by DennisHeimbigner** [comment]
We had a discussion about this and a level of 0 is legal
and should not mean that deflation filter is not being used.
I think changing the test would be better. Wonder if anyone
really depends on that fortran behavior?

**Comment by edwardhartnett** [comment]
0 is not actually a legal deflate level - it means no deflate is in use. Also, this matches what nc_inq_var_szip() does.

Also, given that this behavior has been in place for a long time, are you sure you want to change it?

**Comment by DennisHeimbigner** [comment]
Why no? You thought it would be ok to change
nc_def_var_chunking to change behavior when applied to a scalar.

**Comment by edwardhartnett** [comment]
You guys must decide. If you want to keep it as it is, then I will change the test in netcdf-fortran. If you would like to make it behave as it used to, then merge this PR. ;-)

I'm fine either way. I just want to get the netcdf-fortran tests working again so I can put in the constant (and a test) for compact data type...

**Comment by edwardhartnett** [comment]
OK, turns out this is not optional. The F90 API depends on this.

In the function nf90_inquire_variable() there is not a separate parameter for deflate vs. deflate_level. Instead, deflate_level is used for both. It is documented like this:

```
deflate_level

: The deflate_level from 0 to 9. A value of zero indicates no deflation is in use.
```

Now this could be hacked into the f77 API, but I think it would make more sense to make the C API consistent and then the F77 and F90 APIs will work automatically.

So I believe the best approach is to merge this PR, and specify in the C docs that deflate_level is returned as 0 if deflate is not in use.

**Comment by WardF** [comment]
This Fortran behavior kind of ties our hands, so documenting the discrepancy is probably the way to go; this may be one of those things where a slight inconsistency between the Fortran and C behavior is acceptable, as long as it is documented, and is driven by pragmatism/the individual languages.  The alternative would be to change standing expected behavior for the Fortran API, and given the repercussions for our last change in expected behavior vis-a-vis fill value types, I'd be hesitant to deviate from documented behavior here.

**Comment by edwardhartnett** [comment]
@WardF I have added this information to the documentation, as you suggest.

When this is merged I can get netcdf-fortran running again in my CI system, and can submit the PR there to add and test compact data storage.

**Comment by DennisHeimbigner** [comment]
> there is not a separate parameter for deflate vs. deflate_level.
I see. Then indeed we are constrained. Are there other fortran
functions like this (i.e. have a reduced signature vis-a-vis C)?

**Comment by edwardhartnett** [comment]
@DennisHeimbigner I don't know if there are any other fortran functions with funny parameters. I worked on that a long time ago! ;-)

I did not remember this instance, until we stumbled across it.

The good news is that netcdf-fortran has good tests and allowed this to be caught.
