### ISSUE TITLE
cmake build without netcdf4 fails

### ISSUE THREAD

**Issue by jedwards4b** [Unidata/netcdf-c#168]
I am trying to build on an ibm pwr-8 system without hdf5 installed:

 CC=xlc cmake -D CMAKE_INSTALL_PREFIX=/u/b5p195aa -DENABLE_NETCDF4=OFF -DENABLE_DAP=OFF -DENABLE_REMOTE_FORTRAN_BOOTSTRAP=ON ../
-- The C compiler identification is Clang 3.5.0
-- Check for working C compiler: /usr/bin/xlc
-- Check for working C compiler: /usr/bin/xlc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindHDF5.cmake:347 (find_package_handle_standard_args)
  CMakeLists.txt:490 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/u/b5p195aa/Downloads/netcdf-c/bld/CMakeFiles/CMakeOutput.log".

**Comment by WardF** [comment]
Replace `ENABLE_NETCDF4` with `ENABLE_NETCDF_4`.  I'll update the CMakeLists.txt to respect both options.

**Comment by jedwards4b** [comment]
Thanks

**Comment by WardF** [comment]
Reopening issue so that I don't forget about it for the next release :).

**Comment by WardF** [comment]
Corrected in master, either `ENABLE_NETCDF4` or `ENABLE_NETCDF_4` should work now.
