### ISSUE TITLE
New semantics in CURL_SSL_VERIFYHOST

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#1684]
The semantics of CURLOPT_SSL_VERIFYHOST
has changed and it needs to be accounted for in netcdf.
See: https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYHOST.html

**Comment by WardF** [comment]
So it looks like we need to query the curl version and then gatepost on < 7.28.0, 7.28.1 <= 7.65.3 and then > 7.66.0, if I'm reading this correctly?

**Comment by DennisHeimbigner** [comment]
I think so, yes.
