### ISSUE TITLE
ENABLE_REMOTE_FORTRAN_BOOTSTRAP

### ISSUE THREAD

**Issue by jedwards4b** [Unidata/netcdf-c#169]
This option to cmake doesn't seem to do anything.

**Comment by WardF** [comment]
This is an experimental option and I'll make sure it's labeled as such, but after having built and installed netcdf-c, you should be able to run `make build-netcdf-fortran` and `make install-netcdf-fortran`.  Does this work for you?

**Comment by jedwards4b** [comment]
No

make build-netcdf-fortran

make: *** No rule to make target `build-netcdf-fortran'.  Stop.


I downloaded and tried to build netcdf-fortran separately and have opened
another issue on that page.



On Fri, Dec 4, 2015 at 11:08 AM, Ward Fisher <notifications@github.com>
wrote:

> This is an experimental option and I'll make sure it's labeled as such,
> but after having built and installed netcdf-c, you should be able to run make
> build-netcdf-fortran and make install-netcdf-fortran. Does this work for
> you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unidata/netcdf-c/issues/169#issuecomment-162037698>.
>



-- 
Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by WardF** [comment]
I'm unable to duplicate this issue; closing out until such time as it is reported again.
