### ISSUE TITLE
Issue in nc_def_var_extra with shuffle

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#1720]
This may be related to #1713.

I think there are a few errors in `nc_def_var_extra` with parallel builds.
I am trying to enable the parallel compression feature, and it is always returning an `NC_EINVAL` from line 673.  This happens whether I have `shuffle` enabled or not.

```
#ifndef HDF5_SUPPORTS_PAR_FILTERS
    if (h5->parallel == NC_TRUE)
        if (nclistlength(var->filters) > 0  || fletcher32 || shuffle)
            return NC_EINVAL;
#endif
```
I think the code is checking `shuffle` and it should be checking `*shuffle` (Or, check that shuffle is non-NULL and then check the value and return if the *value* is non-zero)

Note that the call to this routine from `NC4_def_var_deflate` is:
```
    if((stat = nc_def_var_extra(ncid, varid, &shuffle, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL))) goto done;
```
And `shuffle` is an integer parameter to `NC4_def_var_deflate`, so `&shuffle` will always be a non-NULL address, so the test in `nc_def_var_extra` 

The overall behavior is probably the same since this is inside a block only active if the underlying HDF5 doesn't support parallel compression, so eventually the code will return with `NC_EINVAL`, but it shouldn't be returning that at this point.

**Comment by DennisHeimbigner** [comment]
Looks like a correct diagnosis.
