### ISSUE TITLE
SZIP settings in netcdf_meta.h wrong

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#1723]
I am having some trouble understanding how the SZIP settings in `netcdf_meta.h` are supposed to be interpreted.  If I do:
```
(base) s1041980:netcdf-c(master)> git grep HAS_SZIP
```
The following is returned:
```
configure.ac:AX_SET_META([NC_HAS_SZIP],[$ac_cv_func_H5Z_SZIP],[yes])
include/netcdf_meta.h.in:#define NC_HAS_SZIP      @NC_HAS_SZIP@ /*!< szip support (HDF5 only) */
include/netcdf_meta.h.in:#define NC_HAS_SZIP_WRITE @NC_HAS_SZIP@ /*!< szip write support (HDF5 only) */
```
Note that there is nothing related to CMake build which will touch the `NC_HAS_SZIP` variable, so I end up with my `netcdf_meta.h` having the following (whether or not HDF5 supports the szip filter:
```
#define NC_HAS_SZIP       /*!< szip support (HDF5 only) */
#define NC_HAS_SZIP_WRITE  /*!< szip write support (HDF5 only) */
```
The other SZIP-related symbols are `HAVE_H5Z_SZIP` and `USE_SZIP` which are available in config.h, but that is not available to the client.

**Comment by edwardhartnett** [comment]
So the cmake build is not appropriately setting NC_HAS_SZIP and NC_HAS_SZIP_WRITE?

Those two values will always be the same (i.e. both yes or both no). Older versions of netcdf-c had NC_HAS_SZIP but did not have NC_HAS_SZIP_WRITE, which was added when I added nc_def_var_szip() in 4.7.4.

**Comment by gsjaardema** [comment]
No, the values are not being set in the CMake builds.

**Comment by edwardhartnett** [comment]
Thanks for catching and fixing! ;-)

**Comment by edwardhartnett** [comment]
I believe this is fixed now, and so can be closed?

**Comment by gsjaardema** [comment]
Yes, thanks.
