### ISSUE TITLE
ncdump and time units

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/netcdf-c#1729]
According to the man page of `ncdump`, it is capable of displaying time data in an easier to digest (by humans) format if the data are stored in a variable that uses a UDUNITS compliant time unit, such as `days since 1970-01-01' or `seconds since 2009-03-15 12:01:17'. However, one of the pieces of code that enables that functionality contains the following comment (from `ncdump/nctime0.c`):

~~~c
 /* Check for unit compatible with cdtime library, no attempt
   * to enforce CF-compliance or udunits compliance here ... */
~~~ 

which is true. For example, all of the following units are valid and equivalent from the point of view of UDUNITS:

~~~
hours since 2020-05-14
hour since 2020-05-14
Hour since 2020-05-14
hOUrS since 2020-05-14
~~~

as UDUNITS unit `names` [are case-insensitive](https://www.unidata.ucar.edu/software/udunits/udunits-2.0.4/udunits2lib.html#Extracting) (`symbols`, however, are case-sensitive). Currently, `ncdump` only recognizes the first two.

PR Unidata/netcdf-c#1728 addresses allows ncdump to handle the case-insensitive nature of UDUNITS names.

**Comment by Dave-Allured** [comment]
Fixed by PR #1728.  Please close this issue.
