### ISSUE TITLE
Question about whether CMake build provides proper package config file...

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1733]
I have this question from a fellow NOAA programmer about the CMake config file for netcdf-c:

> The CMake build of NetCDF (C, Fortran and C++) do not provide a correct package config file.  In other words, I never had success with find_package(NetCDF C Fortran C++) using the package config file provided by the NetCDF package.  This is the reason I (and some others) have been using the old configure based build system and came up with our version of FindNetCDF.cmake that relies on nc-config, nf-config, ncxx4-config.

**Comment by zerothi** [comment]
I would really second this!!

It would be super fantastic if netcdf installed a cmake and pkg-config file for end users!

**Comment by edwardhartnett** [comment]
What would be helpful is if some cmake-expert netCDF users would submit a PR with these fixes...

**Comment by ibaned** [comment]
Hi all,

We're using NetCDF with the CMake config file, one difference is the name is `netCDF` not `NetCDF` so `find_package(netCDF CONFIG)` works for us. We have a few nitpicks about transitive dependence on HDF5 but overall it does work okay.

**Comment by WardF** [comment]
> Hi all,
> 
> We're using NetCDF with the CMake config file, one difference is the name is `netCDF` not `NetCDF` so `find_package(netCDF CONFIG)` works for us. We have a few nitpicks about transitive dependence on HDF5 but overall it does work okay.

Hi @ibaned, are the nitpicks that the transitive dependence is present in the first place? Or is there something we can clean up there to make it more functional?

**Comment by mathstuf** [comment]
See #2751 for at least getting the HDF5 bit covered.
