### ISSUE TITLE
Current master failing on link error to H5Znoop

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1735]
For a simple build against hdf5-1.10.6. Not sure why Travis doesn't catch this...

```
libtool: link: gcc -shared  -fPIC -DPIC  .libs/H5Znoop.o .libs/H5Zutil.o   -lhdf5_hl -lhdf5 -lm -ldl -lz /usr/lib/x86_64-linux-gnu/libcurl.so    -pthread -Wl,-soname -Wl,libnoop.so -o .libs/libnoop.so
/usr/bin/ld: cannot find -lhdf5_hl
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
Makefile:565: recipe for target 'libnoop.la' failed
make[2]: *** [libnoop.la] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: link: gcc -shared  -fPIC -DPIC  .libs/H5Znoop1.o .libs/H5Zutil.o   -lhdf5_hl -lhdf5 -lm -ldl -lz /usr/lib/x86_64-linux-gnu/libcurl.so    -pthread -Wl,-soname -Wl,libnoop1.so -o .libs/libnoop1.so
/usr/bin/ld: cannot find -lhdf5_hl
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
Makefile:568: recipe for target 'libnoop1.la' failed
make[2]: *** [libnoop1.la] Error 1
libtool: link: gcc -shared  -fPIC -DPIC  .libs/H5Zmisc.o .libs/H5Zutil.o   -lhdf5_hl -lhdf5 -lm -ldl -lz /usr/lib/x86_64-linux-gnu/libcurl.so    -pthread -Wl,-soname -Wl,libmisc.so -o .libs/libmisc.so
/usr/bin/ld: cannot find -lhdf5_hl
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
Makefile:562: recipe for target 'libmisc.la' failed
make[2]: *** [libmisc.la] Error 1
make[2]: Leaving directory '/home/ed/netcdf-c/plugins'
Makefile:708: recipe for target 'check' failed
make[1]: *** [check] Error 2
make[1]: Leaving directory '/home/ed/netcdf-c/plugins'
Makefile:707: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

**Comment by WardF** [comment]
I'm not seeing it locally either, let me investigate.

**Comment by WardF** [comment]
Interesting. A fresh checkout fails.  Diving in deeper.

**Comment by WardF** [comment]
Interesting.  Not sure why it's doing any of this, but the situation appears to be that H5Znoop1.c is generated by a cmake-based build, but is used by both cmake and autotools.  So, if you run a cmake build first (as I typically do in my workflow, and travis does as well), there's no problem.  I'll clean this up. Thanks @edwardhartnett !

**Comment by DennisHeimbigner** [comment]
I thought I had a built-source in the plugins Makefile.am.
Sorry about that.

**Comment by DennisHeimbigner** [comment]
I was right: plugins/Makefile.am has this:
> BUILT_SOURCES = H5Znoop1.c
> CLEANFILES = H5Znoop1.c
> H5Znoop1.c: Makefile H5Znoop.c
> 	echo '#define NOOP_INSTANCE 1' > $@
> 	cat ${srcdir}/H5Znoop.c >> $@

The question is why it is not being invoked.

**Comment by edhartnett** [comment]
IIRC you don't want that in CLEANFILES but in MOSTLY_CLEANFILES.

But I don't think that's the cause of this issue.

**Comment by DennisHeimbigner** [comment]
IMO I would put it in distclean.

**Comment by edhartnett** [comment]
There is a convention, recently explaiined to us in the netcdf-fortran
project. Search there for MOSTLY_CLEANFILES and you fill find the reasons.

**Comment by edwardhartnett** [comment]
@WardF you may wish to change the order of your test runs, and do cmake last.

CMake does not apparently have the equivalent of make distclean, which guarantees to clean the code to the point after it was unpacked.

**Comment by DennisHeimbigner** [comment]
Frankly it shouldn't matter. I was probably over-thinking this case.
H5Znoop.c and H5Znoop1.c are the same except for a single #define
added at the front Of H5Znoop1.c. So I could have just added
H5Znoop1.c to the code base. I did not in order to avoid accidental
discrepancies between them when one got modified and someone
forgot to modify the other. So once created, and assumIng you are not
editing H5Znoop.c, then H5Znoop1.c can hang around.

**Comment by edwardhartnett** [comment]
@DennisHeimbigner created sources must be handled correctly in autotools to support some of the advanced features available, for example "make distcheck".

So the file cannot just "hand around." ;-)

**Comment by DennisHeimbigner** [comment]
Sorry, I was not clear. My point was that it does not have to be a built
source at all if we live with the possibility of future, accidental,
incompatibilities between H5Znoop.c and H5Znoop1.c

**Comment by edwardhartnett** [comment]
Whatever you want to do is fine by me. If you want to just commit H5Znoop1.c that's fine too...

**Comment by edwardhartnett** [comment]
This is fixed now so I will close this.
