### ISSUE TITLE
make m4 compile time dependency

### ISSUE THREAD

**Issue by magnusuMET** [Unidata/netcdf-c#1739]
The cmake build will fail if  `m4` is not installed, which occured in https://github.com/georust/netcdf/pull/56, which did not give a clear error message. The user was compiling on a MSVC toolchain which did not come with `m4`.

Should the cmake build be modified to fail with a useful error in the case where `m4` is not available?

**Comment by WardF** [comment]
I'll clarify the message; we currently check for m4 but the assumption is that a developer will have it on their system.  Not necessarily a good assumption, so I'll revisit that.  The messaging also needs to be clear.  Thanks!

**Comment by magnusuMET** [comment]
This issue has been fixed
