### ISSUE TITLE
no longer linking to dnotnc3.c in libdispatch

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1749]
We are no longer linking to dnotnc3.c in libdispatch.

If we don't need this file, we need to delete it.

However at the moment PIO is failing do to lack of function NC_NOTNC3_get_varm and NC_NOTNC3_put_varm.

Have these functions been replaced by something else?

This needs to be fixed before next release of netcdf-c or PIO will not work...

**Comment by edwardhartnett** [comment]
OK, I believe that dnotnc3.c is required. I have re-added it to the build, and readded the two functions in it to the netcdf_dispatch.h file.

I have included these changes in my currently open PR.

**Comment by DennisHeimbigner** [comment]
I removed it in a previous PR. Why does PIO need a netcdf-3 related function?
They are used nowhere else. Might be better to build PIO specific
replacements for those two functions so we can git rid of dnotnc3.c

**Comment by edwardhartnett** [comment]
I believe they belong in the netcdf library because they deal with the two deprecated netCDF classic functions. By deprecated, we mean that dispatch layers probably do not want to implement them, so it seems good to provide some noop versions as we do with all the netcdf-4 functions that users may not want to implement in a dispatch layer.
