### ISSUE TITLE
netcdf documentation needs to be updated to include info about CDF5

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1756]
I was trying to explain CDF5 to the peeps over at GFDL, and find that there's no mention of it in the docs:

https://www.unidata.ucar.edu/software/netcdf/docs/file_format_specifications.html

The link here does not work. It says: See Large File Support.

https://www.unidata.ucar.edu/software/netcdf/docs/group__datasets.html#ga427f5a0b24f1d426a99bcc37b8a39cac

Where is CDF5 documented?

**Comment by t-b** [comment]
@edhartnett At http://cucis.ece.northwestern.edu/projects/PnetCDF/CDF-5.html I think. I would also appreciate if that could be incorporated in the official docs.

**Comment by edwardhartnett** [comment]
@WardF it seems that the users guide has moved to its own GitHub repo?

What is that repo, so I can submit a PR adding info about CDF5?

**Comment by WardF** [comment]
https://github.com/Unidata/netcdf is the repo.  Tagging @ethanrd as he has been working on a reorganization and may have some feedback about the merge process.

**Comment by ethanrd** [comment]
@edwardhartnett - The reorganization of the NUG is currently in PR #[47](https://github.com/Unidata/netcdf/pull/47) of the Unidata/netcdf repo, off a branch in my fork. The goal of the reorg is to extract any library/language specific content from the more abstract, leaving mainly the data models, file formats, CDL, conventions, and best practices.

The [existing netCDF-3 BNF documentation](https://docs.unidata.ucar.edu/netcdf/NUG/file_format_specifications.html) hasn't made its way into the reorg yet but that's the plan. I'm hoping to have a full rough draft of the reorg by late next week.

I have not thought too much about CDF-5 yet but have looked at the [PnetCDF CDF-5 document](http://cucis.ece.northwestern.edu/projects/PnetCDF/CDF-5.html) which extends the current NUG netCDF-3 BNF. Were you thinking along those lines?

**Comment by edwardhartnett** [comment]
I was responding to a user who pointed out that nowhere in the documentation do we explain the CDF5 format, and it's limits.

So that needs to be in the documenation in the same place we describe the other binary formats.

**Comment by ethanrd** [comment]
OK. Yup, we'll get it in there. Thanks Ed!

**Comment by edwardhartnett** [comment]
Are you planning to release the documentation at the same time as the next netcdf-c release?

**Comment by ethanrd** [comment]
In the longer run, the goal is to separate the release schedule of the NUG from that of the libraries. I expect the first release will need to be synchronized with netCDF-C in some way. Our planning hasn't gotten quite that far. @WardF any thoughts?

**Comment by edwardhartnett** [comment]
I would strongly advise that netcdf-c-4.9.0 be released without waiting for the NUG.

The most critical information is that in the C function descriptions. The NUG is more explanatory and will change less with each release. I will open an issue for this in the NUG repo, and close this issue.
