### ISSUE TITLE
Reported failure of --enable-logging build on NOAA machine

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1760]
More details will be added to this ticket by George...

**Comment by GeorgeVandenberghe-NOAA** [comment]
libtool: compile:  mpiicc -DHAVE_CONFIG_H -I. -I.. -I../include -I/work/noaa/noaatest/gwv/l530/lib/netcdfp/include -MT libnchdf5_la-hdf5open.lo -MD -MP -MF .deps/libnchdf5_la-hdf5open.Tpo -c hdf5open.c -o libnchdf5_la-hdf5open.o >/dev/null 2>&1
mv -f .deps/libnchdf5_la-hdf5open.Tpo .deps/libnchdf5_la-hdf5open.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile mpiicc -DHAVE_CONFIG_H -I. -I..  -I../include  -I/work/noaa/noaatest/gwv/l530/lib/netcdfp/include   -MT libnchdf5_la-hdf5var.lo -MD -MP -MF .deps/libnchdf5_la-hdf5var.Tpo -c -o libnchdf5_la-hdf5var.lo `test -f 'hdf5var.c' || echo './'`hdf5var.c

the compile below fails using hdf5/1.10.6  when --enable-logging is specified in the netcdf configure


libtool: compile:  mpiicc -DHAVE_CONFIG_H -I. -I.. -I../include -I/work/noaa/noaatest/gwv/l530/lib/netcdfp/include -MT libnchdf5_la-hdf5var.lo -MD -MP -MF .deps/libnchdf5_la-hdf5var.Tpo -c hdf5var.c  -fPIC -DPIC -o .libs/libnchdf5_la-hdf5var.o
hdf5var.c(2292): error: identifier "preemptions" is undefined
      LOG((1, "%s: ncid 0x%x varid %d size %d nelems %d preemption %d",
      ^

**Comment by edwardhartnett** [comment]
OK, that one's my fault, and is currently fixed in master I believe. Stand by, I will check, and email you a tarball...

**Comment by edwardhartnett** [comment]
This has been fixed on master and will be in the next release.
