### ISSUE TITLE
Upgrade logging to handle multi-core case well

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1762]
We have logging for netCDF-4 and it's very helpful for debugging difficult bugs.

But it works poorly when running in parallel. In that case, all processors just spew their messages to stdout, intermixed, and without any indication of which task logged which message.

In PIO, I took the netCDF logging code and made some simple upgrades. One is that multi-processor log output can be sent to one file per processor, instead of stdout.

So if a parallel program turns on logging, after it is run there is a file, log.N, where N is the processor number, for each processor. This allows us to open different processor files and see what was going on on each processor.

Of course, for one processor, we can just log everything out to one file. 

This capability would be very helpful in general. As an example, it would be very helpful right now in debugging a strange I/O problem on one of the NOAA HPC systems (see https://github.com/Unidata/netcdf-fortran/issues/264)

**Comment by edwardhartnett** [comment]
OK, NOAA needs this badly, because they are having a problem when running code in parallel I/O mode, and it only breaks occasionally, and only when they run on many processors. So they've asked me what to do and I am totally stumped.

But if I change the logging as discussed in this issue, then each processor will be one output file with all netcdf activity. That will help a lot...

**Comment by Dave-Allured** [comment]
One of the Intel support tools uses a single merged debug log.   Multiple processes spew their messages indiscriminately into the same log in real time, just like you described above.  Most event-related messages are prefixed with the process ID and time stamp.  The prefix fields are fixed width for readability.  The time stamps are precise to 0.01 seconds or better, I forget exactly.   I found this style very helpful for multi-process debugging.

Perhaps this would be a helpful netCDF logging improvement for your scenario.  This would avoid the multiple file clutter that you mentioned.

**Comment by edwardhartnett** [comment]
OK, I have an upgrade which handles the multi-core case better.

@Dave-Allured I have considered your idea of putting everything in one file. But how do I stop collisions when multiple processes want to write to the file? To avoid this, I have left each processor to write its own file.

@DennisHeimbigner is there an exit point in the netCDF library that we know will be called before any netCDF program ends? I need to call nc4_finalize_logging() somewhere. My current code calls it whenever logging is set to -1 again. (That is, when logging is turned off). This requires that any parallel user who turns on logging must also be sure to turn it off, in order to close all the files. I don't think this is a big problem, but it would be nice if I could just call nc4_finalize_logging() from an exit function.

**Comment by Dave-Allured** [comment]
Ed, my previous experiences indicated that collisions were usually handled gracefully.  Log messages came in small packets of one or more complete text lines.  The file system acted as a collective receiver and handled messages in the order received.  Broken lines were rare to nonexistent, I don't remember exactly.  Anyway, that is what was implied by the behavior that I saw.  I think this would be a good approach for parallel netCDF.

Note that with this approach, if you want to know only what one process said, just grep on the process ID column.

**Comment by Dave-Allured** [comment]
I am sure that whatever you implement will be helpful.  Thanks for working on this.

**Comment by DennisHeimbigner** [comment]
> @DennisHeimbigner is there an exit point in the netCDF library that we know will be called before any netCDF program ends?

You have several choices, all of which will ultimately be called by nc_finalize function in the file
netcdf-c/liblib/nc_initialize.c

1. Just stick the logging finalize in the body of nc_finalize()
2. put the logging finalization into NCDISPATCH_finalize() which is in the file libdispatch/ddispatch.c
3. put the logging finalization into NC_HDF5_finalize() which is in libhdf5/hdf5dispatch.c

But remember, calling nc_finalize by the client program is optional, so you will need to make
sure that nc_finalize() gets called in your PIO cod
I have an unsubmitted PR that calls nc_finalize using the atexit() function. But I do not know
how that interacts with parallelism.

**Comment by edwardhartnett** [comment]
@DennisHeimbigner it seems like calling nc_finalize() from atexit() would not be a problem for parallel I/O. By that time, MPI_Finalize() has been called in all well-behaved programs, and so everything that parallel I/O cares about is already shut down.

I will ponder over the weekend.

With my draft PR, for parallel I/O programs, logging has to be turned on and then off. For example:

```
nc_set_log_level(3);
... bunch of netcdf code that outputs logging statements ...
nc_set_log_level(-1);

```
For sequential programs, nothing changes: no files are created, and the output continues to go to stderr. If logging is not turned off, and the program ends, some of stderr might get lost as well, but that's not something anyone has ever noticed or complained about. ;-)

If parallel I/O users forget to turn off logging with the -1, the log files end up empty or missing some logging statements at the end (because buffers were not flushed). This is not ideal but not a huge problem either. 

With this PR, sequential users of logging will not see any change. And currently there are no parallel I/O users of logging, because it's useless. ;-)
