### ISSUE TITLE
need to put nc_create_par/nc_open_par in the dispatch table

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1793]
We have some parallel I/O only functions:

nc_create_par
nc_open_par
nc_var_par_access

These functions are not currently in the dispatch table. But I need them to be, so that I can override them in the PIO/netCDF integration code. ;-)

@DennisHeimbigner any objections or comments about this?

**Comment by DennisHeimbigner** [comment]
Would it be possible to compress these three into a single dispatch table entry
that takes, say, a create/open flag + access flag as args, or something like that?

**Comment by edwardhartnett** [comment]
Let me ponder that...

**Comment by edwardhartnett** [comment]
Well nc_var_par_access() is very different from the nc_create_par/nc_open_par functions, so it should get it's own entry in the dispatch table. 

I could combine the open/create, but would that really be useful? Yes, it would be one less function in the dispatch table, but it would be inconsistent with the way we handle nc_open/nc_create. 

So I would suggest I add three functions to the dispatch table.

Here's the signatures of the three functions:

```
/* Create a file and enable parallel I/O. */
    EXTERNL int
    nc_create_par(const char *path, int cmode, MPI_Comm comm, MPI_Info info,
                  int *ncidp);

/* Open a file and enable parallel I/O. */
    EXTERNL int
    nc_open_par(const char *path, int mode, MPI_Comm comm, MPI_Info info,
                int *ncidp);

/* Change a variable from independent (the default) to collective
 * access. */
    EXTERNL int
    nc_var_par_access(int ncid, int varid, int par_access);

```

**Comment by DennisHeimbigner** [comment]
It appears that these three functions are already defined in include/netcdf_par.h
and implemented in libdispatch/dparallel.c.

**Comment by edwardhartnett** [comment]
OK, I see now that they call NC_create() which calls the create dispatch function. So you are correct, I don't need these in the dispatch table at all! ;-)
