### ISSUE TITLE
Version of the dispatch table in CMake build is incorrect - it should be 2

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1796]
I see this in CMakeLists.txt:

# Version of the dispatch table, in case we change it.

`SET(NC_DISPATCH_VERSION 1)
`
Yet in configure.ac we have:

`AC_SUBST([NC_DISPATCH_VERSION], [2])
`

These should match. I will submit a PR shortly.

**Comment by DennisHeimbigner** [comment]
Please put a comment by both settings to remind developers that if one
is changed, the other needs to be changed also.

**Comment by edwardhartnett** [comment]
Yes, I did put in comments in both places. ;-)
