### ISSUE TITLE
Building from a read-only directory

### ISSUE THREAD

**Issue by magnusuMET** [Unidata/netcdf-c#1805]
Building out-of-tree with the `netcdf-c` directory configured as read-only results in the following errors:

```
CMake Error: Could not open file for write in copy operation /home/magnusu/Builds/netcdf-c/include/netcdf_meta.h.tmp
CMake Error: : System Error: Permission denied
CMake Error at CMakeLists.txt:2100 (configure_file):
  configure_file Problem configuring file


CMake Error: Could not open file for write in copy operation /home/magnusu/Builds/netcdf-c/ncdap_test/findtestserver.c.tmp
CMake Error: : System Error: Permission denied
CMake Error at CMakeLists.txt:2129 (configure_file):
  configure_file Problem configuring file


CMake Error: Could not open file for write in copy operation /home/magnusu/Builds/netcdf-c/dap4_test/findtestserver4.c.tmp
CMake Error: : System Error: Permission denied
CMake Error at CMakeLists.txt:2130 (configure_file):
  configure_file Problem configuring file


CMake Error: Could not open file for write in copy operation /home/magnusu/Builds/netcdf-c/dap4_test/pingurl4.c.tmp
CMake Error: : System Error: Permission denied
CMake Error at CMakeLists.txt:2135 (configure_file):
  configure_file Problem configuring file


-- Configuring incomplete, errors occurred!
See also "/home/magnusu/Builds/buildCDF/CMakeFiles/CMakeOutput.log".
See also "/home/magnusu/Builds/buildCDF/CMakeFiles/CMakeError.log".
```

The build should ideally not write to any directories apart from `CMAKE_CURRENT_BINARY_DIR`, and causes errors when trying to package for the [rust crate](https://github.com/georust/netcdf/issues/69).

 This occurs on 4.7.4 and the latest master.

**Comment by edwardhartnett** [comment]
Coincidentally I just fixed this in PIO. The problem is we are doing a file_configure to the source dir, then a copy to the binary dir.

Instead, we can just do the configure_file directly to the binary dir.

**Comment by magnusuMET** [comment]
There is also code generation for `m4` which puts the generated file in the current source directory.

**Comment by magnusuMET** [comment]
`ncdap_test` should probably be gated on `ENABLE_TESTS`

**Comment by DennisHeimbigner** [comment]
It looks like ncdap_test and nc_test4 are gated in the branch I have.
What are you seeing?

**Comment by DennisHeimbigner** [comment]
If we generate the .c files directly into the binary build dir, will cmake and/or automate
properly find them?

**Comment by magnusuMET** [comment]
> It looks like ncdap_test and nc_test4 are gated in the branch I have.
> What are you seeing?

I'm thinking of the three following `configure_file`s
https://github.com/Unidata/netcdf-c/blob/a66b8ba0a9a25cc3e2fb6165da952f549a958c6c/CMakeLists.txt#L2129

**Comment by DennisHeimbigner** [comment]
I see. Yes, that needs fixing, thanks.

**Comment by magnusuMET** [comment]
> If we generate the .c files directly into the binary build dir, will cmake and/or automate
> properly find them?

If we change the `GEN_m4` macro to output to
```CMakeLists.txt
MACRO(GEN_m4 filename)

  IF(HAVE_M4)

  ADD_CUSTOM_COMMAND(
    OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/${filename}.c
    COMMAND ${NC_M4}
    ARGS ${M4FLAGS} ${CMAKE_CURRENT_SOURCE_DIR}/${filename}.m4 > ${CMAKE_CURRENT_BINARY_DIR}/${filename}.c
    VERBATIM
    )
  ELSE(HAVE_M4)
    IF(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${filename}.c)
        FILE(COPY ${CMAKE_CURRENT_BINARY_DIR}/${filename}.c)
    ELSE()
        MESSAGE(FATAL_ERROR "file ${CMAKE_CURRENT_SOURCE_DIR}/{filename}.c does not exists, and m4 is not available to create the file")
    ENDIF()
  ENDIF(HAVE_M4)
ENDMACRO(GEN_m4)
```
and change where they are used to
```
SET(libsrc_SOURCES ${CMAKE_CURRENT_BINARY_DIR}/putget.c)
```
`CMake` would track this correctly. Might be an idea to let the macro return the new location and `APPEND` this to the list of sources to include.

**Comment by magnusuMET** [comment]
There is a stray file `t_ncxx.{m4,c}` which does not seem to be in use, but is still processed and included

**Comment by magnusuMET** [comment]
Autotools does not seems to support building out-of-tree in a simple manner. I am going to close this issue as one can get out-of-tree builds through `CMake`.

**Comment by edwardhartnett** [comment]
@magnusuMET I test out of tree building with autotools with "make distcheck".

Perhaps I don't understand what you mean by out of tree, but distcheck creates a distribution, unpacks it, then builds and runs tests, with the object and executable files (and all data produced by tests, etc.) goes into different directories than where the source code has been unpacked.

**Comment by magnusuMET** [comment]
I am thinking of a completely out-of-tree build, where the source directory does not have write permissions.

 I might have misunderstood how autotools work, but I assume one is required to generate `configure` in the tree using `autoconf`? I see the releases have these packaged, so maybe it does work out-of-the box for this build too.

**Comment by magnusuMET** [comment]
With the build as it is now one can `chmod -w netcdf-c -R`, and generate the build with `CMake`. This is very useful when dealing with several unrelated build types, such as when cross-compiling or testing different release profiles.

**Comment by edwardhartnett** [comment]
The release contains configure and all the outputs of autoconf/automake/libtool, so the end user does not have to have these tools. The distribution depends only on shell script and generic make being installed on the user systems.

The make distcheck creates, then upacks the distribution, and builds it and runs tests in a different directory tree. The autotools build does support cross-compilation. 

For more details on building out of tree with autotools, see https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html

Actually it works the same as CMake. Create a build subdirectory, then from there do ../configure.

**Comment by magnusuMET** [comment]
@edwardhartnett I see, thanks for explaining the autotools build! There is even a note on the bottom of that page for exactly this usecase (well, minus the CD-ROM)!
