### ISSUE TITLE
Reduce size of unlimited dimension

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#1824]
Is is possible to reduce the size of the unlimited dimension and as a result clear out all data that was written to the variable(s) for the larger size of the unlimited dimension.

For example, if I have a var `double vals_nod_var1(time_step, num_nodes) ;` and `time_step` is the unlimited dimesion.  If the current value of `time_step` is 10, is there a way to reduce the value to 5 and all data that exists in the file for the `vals_nod_var1` variable for time steps 6 to 10 is eliminated and all data for steps 1 to 5 is retained?

**Comment by edwardhartnett** [comment]
I believe not. There is no way to erase data.

**Comment by gsjaardema** [comment]
Thanks.  That is what I thought
