### ISSUE TITLE
nc_inq_var_filters() needs to be in the dispatch table

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1830]
nc_inq_var_filters() needs to be in the dispatch table or it is impossible to make nc_inq_var_deflate() work.

nc_inq_var_deflate() calls nc_inq_var_filters(), but nc_inq_var_filters() does not run through the dispatch table. So it cannot be made to work in PIO or other software using the dispatch layer.

@DennisHeimbigner any objection to adding this to the dispatch table? (Which would bump the dispatch version as well.)

**Comment by edwardhartnett** [comment]
Oh, stand by, perhaps that's what NC4_filter_actions is for?

**Comment by DennisHeimbigner** [comment]
Yes, all the filter APIs now are funneled thru a single dispatch entry.
It is that entry that you need to implement.
