### ISSUE TITLE
Configure fails when trying to build netcdf-c 4.7.4 on Github actions

### ISSUE THREAD

**Issue by RobertPincus** [Unidata/netcdf-c#1834]
Hi there - 

I use Github Actions continuous integration  (running on Ubuntu 18.04 LTS  on Azure)  for some [software of mine](https://github.com/earth-system-radiation/rte-rrtmgp). My software relies on the netCDF library which I access through the Fortran interface. In my CI I use the Ubuntu package manager to install [version 4.6.0 of the C library](https://packages.ubuntu.com/bionic/libdevel/libnetcdf-dev), then [build the Fortran interface](https://github.com/earth-system-radiation/rte-rrtmgp/blob/1a67de4ba9704ceac6f655e1763d14f68a0a38ba/.github/workflows/continuous-integration.yml#L76) with whatever Fortran compiler is being tested

I'd like to expand the CI to include gfortran-10. This Fortran compiler is supported as of version [4.5.3 of the netcdf Fortran interface](https://www.unidata.ucar.edu/software/netcdf/docs-fortran/nf_release_notes.html); this requires version 4.7.4+ of the C library. I thought to download and build that version of the netcdf-c library and build the Fortran interface on top of that. 

Alas, I'm getting the error 
"configure: error: Can't find or link to the hdf5 library. Use --disable-netcdf-4, or see config.log for errors.
checking for library containing H5Fflush... no" although I've set environment variable `LDFLAGS=-L/usr/lib/x86_64-linux-gnu/`

In general it would be great to have a recipe for Github Actions that let one build the netcdf-c library from source.

**Comment by edwardhartnett** [comment]
Howdy Robert! ;-)

I am building netcdf-c from source for github action testing on the PIO project, take a look: https://github.com/NCAR/ParallelIO/runs/1068685498?check_suite_focus=true

**Comment by edwardhartnett** [comment]
This issue should be closed. netcdf-c does build under github actions.

**Comment by RobertPincus** [comment]
@edhartnett This is in the `a3.yml` action? It seems you've built  HDF-5 from source and are know the install location? 
Perhaps I could sharpen the question - if one installs netcdf and its dependencies using `apt-get` what information does one need to provide to `configure` to build the netCDF library from source?

**Comment by edwardhartnett** [comment]
Well I don't know the answer but if you install netcdf with apt-get you
would not also build netcdf right?

Do you mean you installed hdf5 with apt-get and it's not being found? I
don't know what is going on with your github actions, but clearly netcdf is
working correctly. ;-)

**Comment by RobertPincus** [comment]
@edwardhartnett Yes,  HDF5 is being installed with `apt-get` and not being found when trying to build netCDF-c from source. 

In the pnetCDF [a3.yml](https://github.com/NCAR/ParallelIO/blob/3a77973ad5e09d354257045bf3d53827ae36a86b/.github/workflows/a3.yml#L1) you build HDF5 and then netcdf-c libraries from source and install them in `/home/runner/$package`.  In [other actions](https://github.com/NCAR/ParallelIO/blob/3a77973ad5e09d354257045bf3d53827ae36a86b/.github/workflows/strict_autotools.yml#L1) you install these libraries using `apt-get` and configure and  build `pnetcdf`. 

It would be useful to be able to install the requirements for netCDF using `apt-get` and then build netcdf from source, no? 

I wondered if this was related to #1216 but this issue has been closed.

**Comment by dopplershift** [comment]
Are you making sure to install something like libhdf5-dev?

**Comment by RobertPincus** [comment]
@dopplershift `libhdf5-dev` is [installed as a dependency](https://github.com/earth-system-radiation/rte-rrtmgp/runs/1089261955?check_suite_focus=true#step:7:13) of `libnetcf-dev` :

**Comment by edwardhartnett** [comment]
Can this issue be closed?

Currently netcdf-c and netcdf-fortran are building in the CI with GitHub actions. Furthermore on the ParallelIO (PIO) project I also routinely build netcdf-c with the GitHub CI.

**Comment by RobertPincus** [comment]
@edwardhartnett Yes, the issue can be closed. I don't remember how I resolved this issue but my current [continuous integration](https://github.com/earth-system-radiation/rte-rrtmgp/blob/main/.github/workflows/continuous-integration.yml) does build netcdf-c v 4.7.4 and netcdf-fortran v4.5.3 on top of `libhdf5-dev`

**Comment by edwardhartnett** [comment]
@RobertPincus can you close this issue please?
