### ISSUE TITLE
Missing symbols when building static on OSX

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#1839]
I'm observing missing symbols on my OSX platform when building via cmake with `-DBUILD_SHARED_LIBS=OFF`.  Will update with more details as I debug; it's entirely possible that these are not limited to OSX, which reveals another yet another blind spot in our CI testing, which I will patch as part of fixing this.  Related to (or at least discovered) when fixing #1829.

**Comment by WardF** [comment]
First example:

````
[ 27%] Linking C executable ncdumpchunks
Undefined symbols for architecture x86_64:
  "_zutest", referenced from:
      _NCZ_transfer in libnetcdf.a(zwalk.c.o)
      _NCZ_walk in libnetcdf.a(zwalk.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [ncgen/ncdumpchunks] Error 1
````

**Comment by DennisHeimbigner** [comment]
Never seen this before. I will look at zutest and see if there is something
special about it.

**Comment by DennisHeimbigner** [comment]
I will have a fix shortly.

**Comment by WardF** [comment]
It only happens specifically when I'm building with cmake, and passing `-DBUILD_SHARED_LIBS`.  

> I will have a fix shortly

Awesome, thanks @DennisHeimbigner !

**Comment by DennisHeimbigner** [comment]
Famous last words on my part :-)

**Comment by DennisHeimbigner** [comment]
See if pull request https://github.com/Unidata/netcdf-c/pull/1840
fixes this for you.
