### ISSUE TITLE
It would be good to have something in netcdf_meta.h about filter support

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1843]
Filter support changed sometime before netcdf-c-4.7.4 and after 4.7.2. In that time the inq_filter function changed to start returning ENOFILTER error when no filter was found.

Also there is now the ability to add multiple filters, which was not present before.

So it would be great to have some value in the netcdf_meta.h file that indicates that all the current filter capabilities (ENOFILTER and multiple filters) is present in netcdf-c. Something like NC_HAVE_FILTERS perhaps?

**Comment by czender** [comment]
If my understanding is correct, some of the pre-4.7.4 behavior will be re-instated in 4.8.0. Therefore NCO has code to treat 4.7.4 as a special case, so there is also that wrinkle in the API to consider, in addition to the new multiple filter support:
```
	      /* 20200418 netCDF 4.7.4 nc_inq_var_filter() is backwards incompatible
		 https://github.com/Unidata/netcdf-c/issues/1693
		 As of 4.7.4, nc_inq_var_filter() called on a chunked and shuffled 
		 though not compressed variable in a netCDF4 dataset returns error -136:
		 "NetCDF: Filter error: filter not defined for variable"
		 Prior to 4.7.4, nc_inq_var_filter() returns NC_NOERR on such variables, and sets the filter ID to 0 */
	      // 20200701 Dennis Heimbigner reverted the 4.7.4 change in 4.8.0-develop
	      if(NC_LIB_VERSION == 474){
		rcd=nco_inq_var_filter_flg(grp_id,var_id,&flt_id,&prm_nbr,NULL);
		if(rcd == NC_ENOFILTER){
		  rcd=NC_NOERR;
		  flt_id=0;
		  prm_nbr=0;
		} /* !rcd */
	      }else{ /* !netCDF < 4.7.4 || >= 4.8.0 */
		rcd=nco_inq_var_filter(grp_id,var_id,&flt_id,&prm_nbr,NULL);
	      } /* !netCDF 4.7.4 */

```

**Comment by DennisHeimbigner** [comment]
I am about ready to push the (mostly) reverted filter fix.
I will send you the revised NUG/filters.md file to see if it is clear.

**Comment by edwardhartnett** [comment]
OK, so as part of the new release if there is a netcdf_meta.h flag for this, that would be super-helpful. Then we can know when we are encountering a netcdf-c with proper filter behavior.

**Comment by DennisHeimbigner** [comment]
Good idea. any suggestions for a tag name?

**Comment by edwardhartnett** [comment]
NC_FULL_FILTERS

**Comment by DennisHeimbigner** [comment]
Now that  I think about, I am not sure what this flag would signify wrt
to user-visible changes.  Multiple filters? change to error return codes? what?

**Comment by edhartnett** [comment]
It would mean a return to full functionality without the changes in 4.7.4.

Basically I'm going to turn on filter functionality in PIO for netcdf-c
4.8.0 and later. So a symbol that indicates full and expected filter
functionality would be useful.
