### ISSUE TITLE
64bit dimension sizes  in cdf-5 (NC_FORMAT_64BIT_DATA)

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf-c#185]
Is NC_FORMAT_64BIT_DATA supposed to allow 64 bit dimension lengths?

If so, I don't think it works.  With github master, I get an NC_EDIMSIZE error code when trying to create a dimension size greater than X_INT_MAX-3.  I think it is due to this code in dim.c:

        if ((ncp->flags & NC_64BIT_OFFSET) && sizeof(off_t) > 4) {
            /* CDF2 format and LFS */
            if(size > X_UINT_MAX - 3) /* "- 3" handles rounded-up size */
                return NC_EDIMSIZE;
        } else {
            /* CDF1 format */
            if(size > X_INT_MAX - 3)
                return NC_EDIMSIZE;
        }

Shouldn't there be a elif for NC_64BIT_DATA that allows for dimension sizes up to whatever the max value of size_t is?

**Comment by jswhit** [comment]
Even if 64 bit dimension sizes are not allowed in CDF-5, there is still a bug, since dimension sizes should at least be as large as NC_64BIT_OFFSET.  Note in the above code that only NC_64BIT_OFFSET is checked, so for NC_64BIT_DATA files the dimension sizes are limited to what they are in cdf-1.

**Comment by DennisHeimbigner** [comment]
CDF-5 does support 64 bit dimensions. I though I had got all the cases, but it looks like
I may have missed one; I will check it out.

**Comment by WardF** [comment]
@dmh should this be treated as a roadblock for 4.4.0?

**Comment by DennisHeimbigner** [comment]
Do not know; was planning to put in a fix today, but we need the original
submitters to test it out.
=Dennis

**Comment by DennisHeimbigner** [comment]
Also, it occurs to me that I need to see what ncdump does
to make sure my changes do not break it.
=Dennis

**Comment by WardF** [comment]
This appears to be fixed with the recent pull request, closing out the issue unless we see proof to the contrary.
