### ISSUE TITLE
Specifying a custom named hdf5 library using configure when building netcdf

### ISSUE THREAD

**Issue by nvishnoiMW** [Unidata/netcdf-c#1862]
Hi, 

I am trying to build netcdf 4.7.1 with hdf5. 
I am using configure to build it on Linux/Mac. I have the following set:
CPPFLAGS = -I${HDF5_DIR}/include -I${CURL_DIR}/include
LDFLAGS  += -L${HDF5_DIR}/lib -L${CURL_DIR}/lib
I am using a custom named hdf5 library (suffixed with its version, for example, libhdf5-1.10.so). Unfortunately, the above works perfectly fine if my library is named as libhdf5.so but not when it is suffixed. What do I need to change in order to build the netcdf library correctly with suffixed hdf5 lib.

configure fails with: 
checking for library containing H5Fflush... no
configure: error: Can't find or link to the hdf5 library. Use --disable-netcdf-4, or see config.log for errors.

Thanks,
Nalini

**Comment by DennisHeimbigner** [comment]
This is a bit tricky. The simplest solution would be to add a symbolic link
so that libhdf5.so points to the one you currently have.
The problem is that the lib name hdf5_hl is hard coded into configure.ac.

**Comment by nvishnoiMW** [comment]
Thanks Dennis! Our usecase is such that we have two hdf5 library versions, named libhdf5.so and libhdf5-1.8.so, loading in the same process. We want to link netcdf with libhdf5-1.8.so, so the symlink solution would not be feasible for us, 
1. Can we modify configure.ac to change the hard coded HDF5 library names? What will be the steps for that?
2. Looks like CMake did not have any problem in building the stuff once I pointed it to the correct location/names. We currently use CMake only on Windows, does that mean that one possible solution is to use CMake for Linux/Mac as well?

Thanks for your help. 
Nalini

**Comment by DennisHeimbigner** [comment]
CMake works for linux  also. So if that works, then I would say go that route.

**Comment by nvishnoiMW** [comment]
Thanks, Dennis - I changed my build system to use CMAKE on all three platforms - Linux, Mac and Windows and it was able to accept custom named HDF5 libraries. 

Appreciate your help. 
Thanks, 
Nalini
