### ISSUE TITLE
Not finding library

### ISSUE THREAD

**Issue by afernandezody** [Unidata/netcdf-c#1865]
Hello,
The compilation (master at GitHub) on an Ubuntu 18.04 system with a PGI compiler is producing the following error:
```
-- The C compiler identification is PGI 20.9.0
-- The CXX compiler identification is PGI 20.9.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/nvidia/hpc_sdk/Linux_x86_64/20.9/compilers/bin/pgcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/nvidia/hpc_sdk/Linux_x86_64/20.9/compilers/bin/pgc++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
"/home/ubuntu/netcdf-c/build/CMakeFiles/hdf5/cmake_hdf5_test.c", line 15:
          warning: last line of file ends without a newline
  }
   ^

"/home/ubuntu/netcdf-c/build/CMakeFiles/hdf5/cmake_hdf5_test.c", line 12:
          warning: variable "fid" was set but never used
    hid_t fid;
          ^

-- Found HDF5: /opt/hdf5/lib/libhdf5.so;z;dl;m (found version "1.10.6") found components: C HL
-- Found HDF5 libraries version 1.10.6
-- Using HDF5 include dir: /opt/hdf5/include
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Looking for H5Pget_fapl_mpio in hdf5
-- Looking for H5Pget_fapl_mpio in hdf5 - not found
-- Looking for H5Pset_all_coll_metadata_ops in hdf5
-- Looking for H5Pset_all_coll_metadata_ops in hdf5 - not found
-- Looking for H5Z_SZIP in hdf5
-- Looking for H5Z_SZIP in hdf5 - not found
-- Looking for H5Pset_libver_bounds in hdf5
-- Looking for H5Pset_libver_bounds in hdf5 - not found
-- Looking for H5free_memory in hdf5
-- Looking for H5free_memory in hdf5 - not found
-- Looking for H5allocate_memory in hdf5
-- Looking for H5allocate_memory in hdf5 - not found
-- Looking for H5resize_memory in hdf5
-- Looking for H5resize_memory in hdf5 - not found
-- Looking for H5Dread_chunk in hdf5
-- Looking for H5Dread_chunk in hdf5 - not found
-- Looking for H5Pset_fapl_ros3 in hdf5
-- Looking for H5Pset_fapl_ros3 in hdf5 - not found
-- Performing Test HAVE_HDF5_ZLIB
-- Performing Test HAVE_HDF5_ZLIB - Success
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
-- Performing Test HAVE_CURLOPT_USERNAME
-- Performing Test HAVE_CURLOPT_USERNAME - Failed
-- Performing Test HAVE_CURLOPT_PASSWORD
-- Performing Test HAVE_CURLOPT_PASSWORD - Failed
-- Performing Test HAVE_CURLOPT_KEYPASSWD
-- Performing Test HAVE_CURLOPT_KEYPASSWD - Failed
-- Performing Test HAVE_CURLINFO_RESPONSE_CODE
-- Performing Test HAVE_CURLINFO_RESPONSE_CODE - Failed
-- Performing Test HAVE_CURLINFO_HTTP_CONNECTCODE
-- Performing Test HAVE_CURLINFO_HTTP_CONNECTCODE - Failed
-- Performing Test HAVE_CURLOPT_BUFFERSIZE
-- Performing Test HAVE_CURLOPT_BUFFERSIZE - Failed
-- Performing Test HAVE_CURLOPT_KEEPALIVE
-- Performing Test HAVE_CURLOPT_KEEPALIVE - Failed
-- Performing Test HAVE_LIBCURL_766
-- Performing Test HAVE_LIBCURL_766 - Failed
-- Found Math library: HAVE_LIBM-NOTFOUND
CMake Error at CMakeLists.txt:913 (MESSAGE):
  Unable to find the math library.


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/netcdf-c/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/netcdf-c/build/CMakeFiles/CMakeError.log".
```
This doesn't happen with GNU compilers and I'm wondering what might be the issue. Initially, I thought that curl.h might be the culprit but it's installed at /usr/include/x86_64-linux-gnu/curl/curl.h. The error log is attached. Thanks.

[CMakeError.log](https://github.com/Unidata/netcdf-c/files/5378463/CMakeError.log)

**Comment by WardF** [comment]
Interesting.  This could be something environmental, or it could be a blind spot in the `CMakeLists.txt` file.  What happens if you try using autotools? You'll need to run `autoreconf -if` to generate the `configure` script, but once you have that, does a similar error occur running `./configure` ?

**Comment by afernandezody** [comment]
It actually complains about hdf5 
```
...
checking size of void*... 8
checking for library containing deflate... -lz
checking for library containing dlopen... none required
checking for floor in -lm... yes
checking for library containing H5Fflush... no
configure: error: Can't find or link to the hdf5 library. Use --disable-hdf5, or see config.log for errors.
```

**Comment by afernandezody** [comment]
I wasn't able to complete the compilation with autotools but switching from Ubuntu to RHEL led to a successful compilation with cmake. Not really sure why but I'll close the thread unless you indicate otherwise.

**Comment by WardF** [comment]
I'll close the issue out, but I'm still going to try to replicate this.  Which PGI compiler were you using? Is it the same version as on the RHEL system?

**Comment by afernandezody** [comment]
It's the community edition (v20.9).

**Comment by afernandezody** [comment]
Hi @**WardF**,
Unfortunately I need to reopen this conversation as, after going back, some issues keep cropping up. Let me begin with the autotools compilation: It keeps complaining about the lack of HDF5 library. Looking at the config file, it cannot find the hdf5dll library, and it doesn't because it's simply not there. The available libraries are:
```
libhdf5.a      libhdf5_hl.so          libhdf5.la        libhdf5.so.103
libhdf5_hl.a   libhdf5_hl.so.100      libhdf5.settings  libhdf5.so.103.2.0
libhdf5_hl.la  libhdf5_hl.so.100.1.3  libhdf5.so
```
I don't know much about HDF5 libraries so I'm not sure why netcdf is looking for that specific library or why it's not there. 
Regarding the compilation with cmake, I think that my comment last week (that switching from an Ubuntu-based system to a RHEL fixes the problem) is inaccurate. cmake seems to have simply ignored PGI and compile it with GNU so it's almost back to square one following this route.
Thanks.

**Comment by WardF** [comment]
Hi @afernandezody, it is looking for libhdf5dll because there are a variety of names which the libhdf5 library may be present under, and it is checking all of them.  Can you attach the config.log file generated? It will have also looked for libhdf5 and libhdf5_hl, and I'd like to see if it fails to find those as well (and with what error).  Thanks!

**Comment by afernandezody** [comment]
[config.log](https://github.com/Unidata/netcdf-c/files/5425808/config.log)

**Comment by WardF** [comment]
Looking at the output from config.log, it checks the locations it knows about for an hdf5 library containing `H5Fflush()`.  If it finds this function in a particular library, it knows which library to use on the system (which is the whole point behind using `configure` to prepare a build environment).  The script attempts to link against `libhdf5dll` and `libhdf5`, and is unable to do so in either case.  Clearly, you have these libraries installed on your system.  So the question is, "why can't pgcc find them?"

I notice from `config.log` that no value has been set for CFLAGS or LDFLAGS.  If the libhdf5 libraries are located in a non-standard location, you may need to set these environmental variables, e.g. 

    $ export LDFLAGS="-L/path/to/libhdf5/lib"
    $ export CFLAGS="-I/path/to/libhdf5/include"
    $ export LD_LIBRARY_PATH="/path/to/libhdf5.lib"

before running configure.  Note that the syntax may be different for setting environmental variables, depending on your shell.

What happens if you specify these to explicitly tell the compiler where to find the libraries and their header files?

**Comment by afernandezody** [comment]
Declaring LDFLAGS and CFLAGS helps (not sure why I need to explicitly declare them as HDF5 is at /opt/hdf5, but will figure it out later) as the compilation starts but there's some issue with curl:
```
...
.  -I../include -I../oc2   -I/opt/hdf5/include -c -o ncgeny.o ncgeny.c
/bin/sh ../libtool  --tag=CC   --mode=link /opt/nvidia/hpc_sdk/Linux_x86_64/2020/compilers/bin/pgcc  -I/opt/hdf5/include  -L/opt/hdf5/lib -o ncgen3 main.o load.o escapes.o getfill.o init.o genlib.o ncgeny.o ../liblib/libnetcdf.la -lhdf5_hl -lhdf5 -lm -lz
libtool: link: /opt/nvidia/hpc_sdk/Linux_x86_64/2020/compilers/bin/pgcc -I/opt/hdf5/include -o .libs/ncgen3 main.o load.o escapes.o getfill.o init.o genlib.o ncgeny.o  -L/opt/hdf5/lib ../liblib/.libs/libnetcdf.so /opt/hdf5/lib/libhdf5_hl.so /opt/hdf5/lib/libhdf5.so -ldl -lm -lz -Wl,-rpath -Wl,/opt/netcdf/lib
../liblib/.libs/libnetcdf.so: undefined reference to `curl_easy_perform'
../liblib/.libs/libnetcdf.so: undefined reference to `curl_easy_getinfo'
../liblib/.libs/libnetcdf.so: undefined reference to `curl_easy_init'
../liblib/.libs/libnetcdf.so: undefined reference to `curl_easy_strerror'
../liblib/.libs/libnetcdf.so: undefined reference to `curl_version_info'
../liblib/.libs/libnetcdf.so: undefined reference to `curl_easy_cleanup'
../liblib/.libs/libnetcdf.so: undefined reference to `curl_easy_setopt'
../liblib/.libs/libnetcdf.so: undefined reference to `curl_global_init'
../liblib/.libs/libnetcdf.so: undefined reference to `curl_global_cleanup'
make[2]: *** [Makefile:729: ncgen3] Error 2
make[2]: Leaving directory '/home/odyhpc/netcdf-c/ncgen3'
make[1]: *** [Makefile:722: all-recursive] Error 1
make[1]: Leaving directory '/home/odyhpc/netcdf-c'
make: *** [Makefile:567: all] Error 2
```
The curl-devel version is 7.61.1-12.el8.x86_64

**Comment by afernandezody** [comment]
Hi. This is mostly under control but I have a (hopefully) final question. The compilation of an app (WRF) is producing the error message:
```
************************** W A R N I N G ************************************
NETCDF4 IO features are requested, but this installation of NetCDF
  /opt/netcdf
DOES NOT support these IO features.

Please make sure NETCDF version is 4.1.3 or later and was built with
--enable-netcdf4
``` 
This was easy to fix when building netcdf-c with cmake but it's a bit more difficult to deal with autools, The configuration uses:
`./configure --prefix=/opt/netcdf --enable-netcdf4  --disable-dap
`which results in: 
```
# NetCDF C Configuration Summary
==============================

# General
-------
NetCDF Version:         4.8.0-development
Dispatch Version:       2
Configured On:          Thu Oct 22 23:50:48 UTC 2020
Host System:            x86_64-pc-linux-gnu
Build Directory:        /home/odyhpc/netcdf-c
Install Prefix:         /opt/netcdf

# Compiling Options
-----------------
C Compiler:             /opt/nvidia/hpc_sdk/Linux_x86_64/2020/compilers/bin/pgcc
CFLAGS:                 -I/opt/hdf5/include
CPPFLAGS:
LDFLAGS:                -L/opt/hdf5/lib -lcurl
AM_CFLAGS:
AM_CPPFLAGS:
AM_LDFLAGS:
Shared Library:         yes
Static Library:         yes
Extra libraries:        -lhdf5_hl -lhdf5 -lm -lz

# Features
--------
NetCDF-2 API:           yes
HDF4 Support:           no
HDF5 Support:           yes
NetCDF-4 API:           yes
NC-4 Parallel Support:  no
PnetCDF Support:        no
DAP2 Support:           no
DAP4 Support:           no
Byte-Range Support:     no
Diskless Support:       yes
MMap Support:           no
JNA Support:            no
CDF5 Support:           yes
ERANGE Fill Support:    no
Relaxed Boundary Check: yes
SZIP Support:           no
SZIP Write Support:     no
Parallel Filters:       yes
NCZarr Support:         no
Multi-Filter Support:   yes

```
 I modified the Makefile manually but it's still complaining. Are there any specific flags that I should be using with autotools in addition to  --enable-netcdf4 & --disable-dap? Thanks.
