### ISSUE TITLE
Bug in hdf5 handling when an early filter has no data

### ISSUE THREAD

**Issue by pterjan** [Unidata/netcdf-c#1874]
For some reason this broke tests only on arm32 and arm64 and with hdf5 1.10.7 but there is a bug in libhdf5/hdf5open.c.

The code does
```
    size_t cd_nelems = CD_NELEMS_ZLIB;
[...]
    for (f = 0; f < num_filters; f++)
    {
        if ((filter = H5Pget_filter2(propid, f, NULL, &cd_nelems, cd_values_zip,
                                     0, NULL, NULL)) < 0)
            return NC_EHDFERR;
        switch (filter)
        {
```

`cd_nelems` gets updated with the number of values for the filter, so when the first filter has 0 it gets set to 0 and when the second filter has 1 it doesn't get written to `cd_values_zip` because `cd_nelems` is now 0. This causes a failure when the uninitialised value is > 9 for H5Z_FILTER_DEFLATE (maybe it gets initialised to 0 on other architectures?).

Setting `cd_nelems = CD_NELEMS_ZLIB` inside the loop makes the tests pass.

**Comment by pterjan** [comment]
This was actually already fixed in https://github.com/Unidata/netcdf-c/commit/84c69afca7cd4493905f208cfaeaa2224816325f#diff-69d85613974e9a9e174118838e5f3d8f931fbe4a36f6e2c9f8970459180ce15c

**Comment by DennisHeimbigner** [comment]
So is this a reversion report?

**Comment by pterjan** [comment]
The bug existed in 5.7.4 but is now fixed at head
