### ISSUE TITLE
findtestserver.exe cannot find dts on Windows

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#1875]
When invoking `ncdap_test/findtestserver.exe` on Windows with arguments `dap2 dts`, 'not found: dts' is returned.  The same command returns properly when built on Linux or OSX.  Haven't stepped through yet, does this work for you @DennisHeimbigner ?

**Comment by DennisHeimbigner** [comment]
I have seen no problems with it under either cygwin or visual studio.
If you can run it with 'set -x' or sh -x, you can see where it is failing.
You might stick 'https://remotetest.unidata.ucar.edu/dts/' in your browser
to make sure it is up.

**Comment by WardF** [comment]
Unfortunately it is the compiled executable `findtestserver.exe` that is failing (see attached screen shot).  The URL opens for me in the browser on the same machine.  I'll see if I can figure out why this is happening.  I'm also seeing a failure in the `nc_test4/tst_filter` test.  Does this one work on your end as well? I presume it does.

**Comment by DennisHeimbigner** [comment]
Humm...
You are using visual studio + Cmake, correct?
What options are you using?
As for tst_filter, you might look back in the ./configure output and
see if there are errors/warning being reported when building the plugins
directory.

**Comment by DennisHeimbigner** [comment]
I just ran the dap tests successfully using Visual Studio plus Cygwin tools (bash, etc).
My CMake command was as follows:
````
cmake '' -DCMAKE_BUILD_TYPE=Release -DNC_FIND_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/tmp/netcdf -DENABLE_NCZARR=false -DHDF5_DIR=c:/tools/hdf5-1.10.6/cmake/hdf5 -DENABLE_NCZARR_S3=false -DENABLE_LOGGING=true -DENABLE_BYTERANGE=true -DENABLE_FILTER_TESTING=true -DENABLE_EXAMPLES=false -DCURL_NO_CURL_CMAKE=TRUE '-DNCPROPERTIES_EXTRA="key1=value1|key2=value2"' ..
````

**Comment by WardF** [comment]
Thanks Dennis, that gives me some more avenues to try. I'll give that a shot and report back.  I am using VS15 and CMake, and have tested in both an MSYS2 bash shell as well as a Windows CMD window.  I typically work with MSYS2 bash because it explicitly lacks the *nix underpinnings from Cygwin.  Let me take a look and get back to you.

**Comment by DennisHeimbigner** [comment]
A long shot, but in a number of shell scripts I have had to deal with
extraneous carriage return characters (\r) in strings. In those cases,
I have had to filter the string using the command
    tr -d '\r'
You might run e.g. tst_remote3.sh with set -x and see if those extraneous
carriage return characters are appearing.

**Comment by WardF** [comment]
I’ll give it a try; would that explain the failure when invoking findtestserver directly, outside of a shell script?

**Comment by DennisHeimbigner** [comment]
Probably not. But it depends on what strings are actually being passed to
findtestserver. Le me build a version with some debugging output.

**Comment by WardF** [comment]
Sounds good; in the meantime, I can actually step through the program to see what is being passed back, once I find the time to do so; I'll prioritize it once I'm out of these meetings.

**Comment by DennisHeimbigner** [comment]
I forgot that there actually is  a limited debug capability.
If you set
export NC_REPORTSEARCH=1
then findtestserver will provide info on its search

**Comment by WardF** [comment]
Thanks Dennis, turning to debugging this now, I'll take a look

**Comment by WardF** [comment]
@DennisHeimbigner with `NC_REPORTSEARCH=1` defined I get the following:

````
Ward@livingston MINGW64 /d/netcdf-c/build/ncdap_test
# ./findtestserver.exe dap2 dts
nc_findtestserver: candidate=remotetest.unidata.ucar.edu/dts: found=no
not found: dts
````
Putting remotetest.unidata.ucar.edu/dts in Chrome in the same VM opens a dirrectory listing (as expected).  

Looking at this, I wonder if my local libcurl supports ssl; let me dig into that.

**Comment by WardF** [comment]
I suspect that may have been it, recompiling libcurl with ssl support and will see if the issue continues.

**Comment by WardF** [comment]
Unfortunately, that was not it.

**Comment by DennisHeimbigner** [comment]
Attached is a modified version of include/nctestserver.h that turns on CURLOPT_VERBOSE.
It might give some useful info. (Note, I had to rename it nctestserver.txt to
get git to allow it).
[nctestserver.txt](https://github.com/Unidata/netcdf-c/files/5462521/nctestserver.txt)

**Comment by WardF** [comment]
Thanks Dennis, testing now.  I can also step through and see what's happening.  I'm 95% sure this is probably environmental on my end, but I'd like to know for sure *what* is happening so that we can document it.

**Comment by WardF** [comment]
So I've tested the modified file on Windows and am seeing the following:

````
# ./findtestserver4.exe  dap2 dts
*   Trying 128.117.149.6...
* TCP_NODELAY set
* Connected to remotetest.unidata.ucar.edu (128.117.149.6) port 443 (#0)
* ALPN, offering http/1.1
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
*   Trying 128.117.149.6...
* TCP_NODELAY set
* Connected to remotetest.unidata.ucar.edu (128.117.149.6) port 80 (#0)
> GET /dts HTTP/1.1
Host: remotetest.unidata.ucar.edu
Accept: */*

< HTTP/1.1 301 Moved Permanently
< Date: Mon, 02 Nov 2020 17:56:42 GMT
< Server: Apache
< X-Frame-Options: SAMEORIGIN
< Location: https://remotetest.unidata.ucar.edu/dts
< Content-Length: 247
< Content-Type: text/html; charset=iso-8859-1
<
* Ignoring the response-body
* Connection #0 to host remotetest.unidata.ucar.edu left intact
* Issue another request to this URL: 'https://remotetest.unidata.ucar.edu/dts'
*   Trying 128.117.149.6...
* TCP_NODELAY set
* Connected to remotetest.unidata.ucar.edu (128.117.149.6) port 443 (#1)
* ALPN, offering http/1.1
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 1
not found: dts
````

I've committed this modified file on a branch, `nctestserver-debug.wif`, that will be deleted when we figure out what's going on.  I feel like this is something in my environment, although I've recompiled libcurl with SSL support so it's not as easy as 'lack of SSL support'.

**Comment by WardF** [comment]
Contrasting this against my OSX machine, where I see:

````
*   Trying 128.117.149.6...
* TCP_NODELAY set
* Connected to remotetest.unidata.ucar.edu (128.117.149.6) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
````

I think I see the issue; the local system isn't able to set (or find?) a local certificate location.  Why this is the case, and how to fix this remains TBD.

**Comment by WardF** [comment]
I'm still not 100% that the issue is in the 'local storage' step and not the 'retrieve certificate' step, however.

**Comment by WardF** [comment]
Ok, the issue was using `openssl` instead of `winssl`.  Compiling `libcurl` on my system with `-DCMAKE_USE_WINSSL=TRUE` tells libcurl to use the system CA store, which corrects the issue.  Thanks, @DennisHeimbigner !

**Comment by DennisHeimbigner** [comment]
Good catch!

**Comment by WardF** [comment]
Thanks, and thanks to @oxelson for all of her help getting this figured out!
