### ISSUE TITLE
plugins directory fails to build when enabling memory sanitizing

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#1878]
Plugins fails with 'undefined symbols' error, on OSX, when passing CFLAGS="-fsanitize=address -fno-omit-frame-pointer" to configure.  I believe the issue is the `-no-undefined` at the top of `plugins/Makefile.am`.  Removing this solves the issue, I need to determine why we have this ld flag added and if there is a downside to removing it.  Thoughts @DennisHeimbigner ?

**Comment by DennisHeimbigner** [comment]
I think the no-undefined is related to the creation of shared libraries.
If memory serves, some systems cannot create shared libraries if there
are undefined symbols. This might be a cygwin issue.

**Comment by WardF** [comment]
I'll see if I can confirm.

**Comment by WardF** [comment]
I've confirmed this is correct.  Working to add a conditional on Cygwin so that --no-undefined is added only if we're working in cygwin.

**Comment by WardF** [comment]
I see we actually check for that already in configure.ac; modifying `plugins/Makefile.am` to take advantage of this.

**Comment by WardF** [comment]
I've gotten it working and am waiting for travis-ci.org to finish.  It is running slower now that it is a bit throttled.  We'll be converting to GitHub actions soon.
