### ISSUE TITLE
nccopy failes to convert a particular nc3 file to an nc4 file

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#189]
Originally reported by Kent at the HDF group.  The e-support ID is 26542.  See the message for the file Kent provided, it's too large to attache to this issue.

-------

Use the current nccopy(4.3.3.1) to covert the NetCDF-3 file to netCDF-4 file, then 

`$ nccopy -k4 -d1 outfile-n3-GLAH outfile-n4-GLAH`

Have:
NetCDF: HDF error
Location: file nccopy.c; line 1444

The platform is CentOS 7.1

**Comment by WardF** [comment]
Findings by @dmh:

I have recreated the error using cygwin.

A couple of things I noticed so far:
1. It appears to actually create the output netcdf4 file.
2. A diff of the metadata appears to show that the netcdf3 metadata
   and the netcdf4 metadata are consistent except that the netcdf4
   metadata is missing all attributes named 'CLASS' or 'NAME'.
   Weird.

=Dennis Heimbigner
  Unidata

**Comment by WardF** [comment]
Follow-up from Kent:

I did a little more investigation of the original HDF5 that may be helpful.
In the original nc3 file, the attribute CLASS=IMAGE. This is a special convention for an HDF5 high-level image file.
I think nccopy fails when calling H5DSattach_scale. In the function H5DSattach_scale, it will return FAIL if this dataset is an image(CLASS=IMAGE) or table(CLASS = TABLE).
HDF5 IMAGE and TABLE cannot have dimension scales.

One solution for this problem is to check if the attribute CLASS is IMAGE or TABLE, don't attach the scale if finding the variable is actually HDF5 image or table.

**Comment by DennisHeimbigner** [comment]
In my investigation, I discovered that for some reason, the netcdf-c/libsrc4 code is not successfully extracting certain attributes from the hdf5 file. Now to find out why.

**Comment by DennisHeimbigner** [comment]
I created a program to do some testing. The program is at the end.
The interesting thing is that doing ncdump gives this:
------------------------------------------------------
netcdf tst_gh189 {
variables:
	int BROWSE_Image_00 ;
data:
 BROWSE_Image_00 = _ ;
}
------------------------------------------------------
Note that the attribute "CLASS" is not listed.
If I use h5dump, I get this:
------------------------------------------------------
HDF5 "tst_gh189.nc" {
GROUP "/" {
   DATASET "BROWSE_Image_00" {
      DATATYPE  H5T_STD_I32LE
      DATASPACE  SCALAR
      DATA {
      (0): -2147483647
      }
      ATTRIBUTE "CLASS" {
         DATATYPE  H5T_STRING {
            STRSIZE 4;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "abcd"
         }
      }
   }
}
}
------------------------------------------------------
Note that "CLASS" attribute is defined. So somewhere, the "CLASS" attribute is either suppressed by HDF5 library or by the netcdf library.
Test program:
------------------------------------------------------
-#include <nc_tests.h>
#include <stdio.h>
#include <stdlib.h>
#include <netcdf.h>
#define FILENAME "tst_gh189.nc"
int main(int argc, char **argv) 
{
    /* Minimal demonstration of github issue 189 */
    int ncid,varid;
    char data[5] = "abcd";
    if (nc_create(FILENAME, NC_CLOBBER|NC_NETCDF4, &ncid)) ERR;
    if (nc_def_var(ncid, "BROWSE_Image_00", NC_INT, 0, NULL, &varid)) ERR;
    if (nc_put_att(ncid,varid,"CLASS",NC_CHAR,4,data)) ERR;
    if (nc_close (ncid)) ERR;
    SUMMARIZE_ERR;
    FINAL_RESULTS;
}
-----------------------------------------------------

**Comment by edhartnett** [comment]
Could the answer be that "CLASS" is a protected word for attributes in HDF5 and should not be allowed for a netCDF attribute name?

**Comment by WardF** [comment]
Dennis and I've had a couple more exchanges with Kent and the HDF group and this is indeed the case; I'm probably going to close this out since the behavior is both explained and not going to change.  I'll re-open the issue if further discussion dictates it. 

I'm hesitant to tell people they can't use `CLASS` across the board, but documenting this somewhere that this is a reserved word for netcdf4 files wouldn't be a bad idea.  Ideally we'd have a way to return a reserved-keyword error, and I suppose we could add code to do that, but it seems low priority until we actually observe this "in the wild".  

> Note that we'd have to maintain the list of reserved keywords ourselves; from talking with Kent, HDF5 does not raise any sort of flag or error code beyond `FAIL` in this case, and so does not indicate the reserved-keyword problem.

**Comment by DennisHeimbigner** [comment]
Ward, My proposal on this is as follows:
1. Get a list of all the known HDF5 reserved attribute names.
2. Assuming there is a way to read them using some HDF5 procedure,
     add special code to extract the attributes that way.
There is some performance cost for this because it would need to ask
for these special names on every variable and every group.
=Dennis

**Comment by DennisHeimbigner** [comment]
Ok, So I found out what is going on. In the file libsrc4/nc4file.c,line1750, the following atttributes names are checked and ignored: REFERENCE_LIST, CLASS, DIMENSION_LIST, NAME, COORDINATES, NC_DIMID_ATT_NAME.

It turns out that this is documented in the file: ''docs/file_format_specifications.md''
The claim is that "...This attribute is created and maintained by the HDF5 dimension
  scale API".

This information was in the old netcdf.texi, (''docs/old/netcdf.tex''),  but apparently got lost in the move to doxygen.

So, we need to restore this info to the current documentation,

**Comment by WardF** [comment]
Given that the file isn't created/copied, is there a problem with how the attribute names are being checked?  I'll copy over the old info into the new documentation on Tuesday; I've been working on tightening up the documentation anyways.

**Comment by WardF** [comment]
Closing this out now for housekeeping reasons, will open a new, related issue specific to the change we're making.  Also tagged with `revisit` to keep it from falling through the cracks.
