### ISSUE TITLE
Is it possible to query the size of a vlen variable?

### ISSUE THREAD

**Issue by geoffmatt** [Unidata/netcdf-c#1893]
I'm using NetCDF 4.7.4 c api
Running on Windows 10

I am attempting to read a vlen type variable, which I can do successfully using nc_get_vara.
However I cannot read the size of this variable without reading all its values into memory. The file structure must have this knowledge, but the documentation provides no access to it that I can see.

**Comment by WardF** [comment]
Hello. Thinking out loud, this information is returned from the underlying libhdf5 call at the very least.  The length for each array (indexed by dimension) is accessible through the `nc_vlen_t` struct, e.g. `data[dimindex].len`, but I suspect you already know that.  I suspect that the information is not available without opening the file and reading in the variable.  If we were to add an interface function, it would still read the values in to memory under the hood.

If there is an API call into the underlying library that circumvents this, I will try to find it and add an interface for it, but at the current time, the variable is read into memory and the length for each vlen variable (per dimension) is computed at run time, not stored as metadata.

**Comment by WardF** [comment]
@DennisHeimbigner please feel free to correct me if I'm wrong.

**Comment by DennisHeimbigner** [comment]
You are correct. I might add that this is because the length of each vlen instance
can be different, so there is no fixed "length" of a vlen.

**Comment by geoffmatt** [comment]
Thanks for the quick reply.
@WardF Yep at the moment I'm using the length property of the nc_vlen_t structure, but obviously that requires reading the vlen.
If the length of the vlen is calculated at runtime, I guess the issue could be how that is achieved. I was assuming the file would have to know the byte count for the vlen to be able to read it at all. If that's the case then presumably the length could be calculated using the byte count and the data type.
But it could be possible that the vlen is being read by simply continuing the read until it reaches a terminator, at which point it stops and can then calculate the length. If that's the case then I don't think my request would be possible, as the position of the terminator could only be determined by reading the data.

**Comment by DennisHeimbigner** [comment]
First, I assume you are not asking for the lenght/size of ehe nc_vlen_t structure,
but rather to the length of the data pointed to by the structure.
The structure is used internally, so when you write a vlen instance,
you have to give the length and a pointer to the data of that length.
That is how the library knows what to store in the file. When you read,
the library constructs an nc_vlen_t structure, gets its length from the file,
allocates memory to hold the data, and then reads the data from the file
into that allocated memory. As you say, the size (in bytes) of the instance's
allocated data is the length in the structure * typesize.

**Comment by czender** [comment]
If you have NCO installed, it will print the RAM size of VLEN variables when invoked like this:

ncks -m -D 2 --udt --hdn ~/nco/data/vlen.nc

**Comment by DennisHeimbigner** [comment]
Is this the sum of the lengths of the individual array elements (of type vlen) or what?

**Comment by czender** [comment]
It is the total RAM needed to hold the vlen variable in memory, i.e., the product of all the dimension sizes, the mean vlen size, and the size of the base type.
```
dimensions:
    lat = 2 ; // ID = 0
    time = UNLIMITED ; // (2 currently) ID = 3
  variables:

  vlen_flt_t vlen_flt_2D(lat,time) ; // RAM size = 2*2*mean_length(NC_VLEN)*sizeof(NC_FLOAT) = 4*2*4 = 32 bytes, ID = 2
```

**Comment by edwardhartnett** [comment]
To answer the original question: there is no way to learn the length of a vlen variable in advance from HDF5. You must simply read the dataset and see what you get. So there is no way for netcdf to provide this information without reading the data.

I believe this issue can be closed.

**Comment by geoffmatt** [comment]
Thanks for the response. Closing the issue.
