### ISSUE TITLE
autoreconf -if warning

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#1899]
autoreconf -if results in a warning about `noinst_PROGRAMS` redefinition in `ncdump/Makefile.am`

**Comment by DennisHeimbigner** [comment]
Thought I fixed this, but maybe in some other branch.
Anyway, the fix is to change noinst_PROGRAM = XXX
to noinst_PROGRAM += XXX

**Comment by WardF** [comment]
Hi Dennis,  you did fix this, I just created this issue to associate against the PR you issued. Thanks!
