### ISSUE TITLE
data with unknown filter causes ncdump to error

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1908]
I am using the zstandard filter, and I have a filtered test dataset. (This is with hdf5-1.10.7, today's netcdf-c master branch).

When I use ncdump without the filter, I get an error:

```
(base) ed@mikado:~/ccr/test$ /usr/local/netcdf-c-4.8.0-development_hdf5-1.10.7_mpich/bin/ncdump tst_par_zlib.nc 
netcdf tst_par_zlib {
dimensions:
	d1 = 24 ;
	d2 = 24 ;
	d3 = 10 ;
variables:
	int v1(d1, d2, d3) ;
data:

 v1 =
NetCDF: HDF error
Location: file vardata.c; line 478
```

When I add the plugin to the plugin path, it works:

```
  (base) ed@mikado:~/ccr/test$ HDF5_PLUGIN_PATH="../hdf5_plugins/ZSTANDARD/src/.libs:$HDF5_PLUGIN_PATH" /usr/local/netcdf-c-4.8.0-development_hdf5-1.10.7_mpich/bin/ncdump tst_par_zlib.nc 
netcdf tst_par_zlib {
dimensions:
	d1 = 24 ;
	d2 = 24 ;
	d3 = 10 ;
variables:
	int v1(d1, d2, d3) ;
data:

 v1 =
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
  3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
  4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
  5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
  6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
  7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
  8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
  9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
  10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
  11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
  12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
  13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
  14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
...
```

**Comment by DennisHeimbigner** [comment]
If the netcdf-c/HDF5 library does not have access to the filter
and the dataset says its uses the filter, then of course, ncdump cannot dump
that variable.
What do to in this situation. First, we should be generating a better error message.
Also, ncdump should remove that variable from its output.
I suppose it might be useful to dump the contents of the raw unfiltered data,
but  I am not sure that is possible with HDF5.
Fixing the error message is doable. Dropping the variable might require time.
Any suggested alternative?

**Comment by edwardhartnett** [comment]
Dumping the unfiltered values is worthless, so don't bother.

Just a good error message, saying 'can't find filter' would be good. I don't think you should drop the variable, just provide a good error message and let the user sort it out.

**Comment by DennisHeimbigner** [comment]
ok, thanks.
