### ISSUE TITLE
Adding create/modified times to the file provenance?

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#1909]
I am considering adding a create time and a last modified time to
the _NCProperties provenance attribute.
Any opinions on this?

Details:
1. add two fields to the _NCProperties attribute of the form
````...,Created=<time>,Modified=<time>````
2. The time is number of microseconds since the start of the Unix epoch time.
3. The modtime is an approximation in that it is changed whenever a file is closed
   (sync'd actually) and the file was opened for writing. This means that if the file
   was opened for writing, but not actually written, the modtime will still be changed.
4. There is a cost to re-writing the _NCProperties attribute if the modtime is changed.

**Comment by edwardhartnett** [comment]
I believe this information is already directly available from the OS. You can find the create and last modified time of any file.

**Comment by dopplershift** [comment]
The filesystem information is not (necessarily) preserved when data files are transferred between systems--like downloaded off a web server.

**Comment by edwardhartnett** [comment]
The concern raised by someone (on the mailing list) seems valid: this will make two identical netCDF files appear different to cmp because they have different create times.

**Comment by WardF** [comment]
I would agree that the comparison is a valid concern; this is something that the user can add via metadata if they really want to, otherwise I think it can be excluded for the sake of easier binary comparison.

**Comment by DennisHeimbigner** [comment]
Yes, I had not thought about that. But technically, that is already the case unless
you set fillvalue on all variables and create the metadata in the same order.
Still, if it works for them, I do not want to mess with it.
