### ISSUE TITLE
How to learn about filters on a var if there are more than one?

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1921]
We have:

```
/* Learn about the first filter on a variable */
EXTERNL int
nc_inq_var_filter(int ncid, int varid, unsigned int* idp, size_t* nparams, unsigned int* params);

```

If there are more than one filter for a variable, how do we learn about the non-first one? That is, how do we learn about filter 2, 3, 4, etc.?

@DennisHeimbigner am I missing something here?

**Comment by edwardhartnett** [comment]
OK, I found the answer in netcdf_filter.h.

I'm not sure that netcdf_filter.h and related files are a good idea. What do they add? Why not just put the declarations from netcdf_filter.h into netcdf.h?

**Comment by DennisHeimbigner** [comment]
Dividing stuff into various netcdf_xxx.h files was initiated by me some time ago.
The primary reason was to keep netcdf.h from being too cluttered and to all
users to see all the relevant functions about a topic in a single file.

**Comment by edwardhartnett** [comment]
BTW, nc_inq_var_filter() documentation says it gives the first filter. But in use it appears to give the last filter applied...

**Comment by DennisHeimbigner** [comment]
Odd. The code looks to be like it is giving the first filter defined. When a filter is defined
it is added to the end of an array. Getting the 0'th entry of the array should return
the first defined filter. Wonder what is going on?

**Comment by DennisHeimbigner** [comment]
I think I figured it out. The order if you are creating a file is the order
in which the nc_def_var_filter is called, which is also the order of application.
However when reading, the order
of application is the reverse of that order, and apparently that is the order in
which HDF5 returns them. To be consistent, I suppose I should reverse the list
when reading. Or should I leave it as is?

**Comment by edwardhartnett** [comment]
I don't know, that's a good question. 

Do we get a different answer when we do the inq after the file was created, but before we close it?

Whether it is changed or not we certainly need to figure it out and correctly document it...

**Comment by DennisHeimbigner** [comment]
Up until it is closed, the order is the create order. After being closed, the order is the read order.

**Comment by edwardhartnett** [comment]
OK, that's not good.

Can you easily tell which condition the list is in? And then reverse it, as you suggest, on re-open?

That way it would always be in create order.

The order of filters is significant. So we need a way to open a file which has had multiple filters applied to a var, and know what order they were applied in. So if this issue is fixed, then we can use the results of nc_inq_var_filter_ids() to get the correct order that the filters were applied in...

**Comment by DennisHeimbigner** [comment]
I was wrong. I extended a test case to record create order vs read order and they
appear to be the same. So I am confused as to how you saw a difference.

**Comment by edwardhartnett** [comment]
OK, let me recheck my test...

**Comment by DennisHeimbigner** [comment]
As will I.
