### ISSUE TITLE
Dispatch table version should be incremented to 3

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1924]
We have these at the end of the dispatch table:

```
    EXTERNL int
    NC4_inq_var_filter_ids(int ncid, int varid, size_t* nfilters, unsigned int* filterids);
    EXTERNL int
    NC4_inq_var_filter_info(int ncid, int varid, unsigned int id, size_t* nparams, unsigned int* params);

```

But what I had (for version 2 of the dispatch table) was one function, filter_actions. Do I recall that this was removed and these two functions added?

So should we increment the dispatch table number to 3? Was there a release with dispatch table version 2?

**Comment by DennisHeimbigner** [comment]
I do not recall. I will look at the previous releases to see if I can figure it out.

**Comment by edwardhartnett** [comment]
Yes, 4.7.4 had dispatch 2, so I believe that means the version should be incremented.

The PIO configure uses this, which is how I caught on. ;-)

**Comment by edwardhartnett** [comment]
In 4.7.4 the last function in include/netcdf_dispatch.h is:

`   int (*filter_actions)(int ncid, int varid, int action, struct NC_Filterobject*);
`

And in current master we have:

```
    /* Version 3 Replace filteractions with more specific functions */
    int (*inq_var_filter_ids)(int ncid, int varid, size_t* nfilters, unsigned int* filterids);
    int (*inq_var_filter_info)(int ncid, int varid, unsigned int id, size_t* nparams, unsigned int* params);

```
So it looks like past-Dennis also thought we should be at version 3. ;-)

**Comment by DennisHeimbigner** [comment]
In the master branch, this value is currently 3.

**Comment by edwardhartnett** [comment]
In configure.ac on master:

```
# This is the version of the dispatch table. If the dispatch table is
# changed, this should be incremented, so that user-defined format
# applications like PIO can determine whether they have an appropriate
# dispatch table to submit. If this is changed, make sure the value in
# CMakeLists.txt also changes to match.
AC_SUBST([NC_DISPATCH_VERSION], [2])

```

However, I was looking at an outdated master. I just did a fetch...

But I check this on GitHub. Also in CMakeLists.txt the dispatch version is 2. Am I missing something?

**Comment by DennisHeimbigner** [comment]
No, I just forgot that it is used in two places. Wish there was a way to have a single
definition. Do you want to put in a PR or shall I?

**Comment by DennisHeimbigner** [comment]
Actually, maybe it only needs to be in netcdf_dispatch.h and not in either Makefile.am
or CMakeLists.txt

**Comment by edwardhartnett** [comment]
It's in netcdf_meta.h and also the build summary...

**Comment by DennisHeimbigner** [comment]
Bah!

**Comment by edwardhartnett** [comment]
I don't think it needs to be in netcdf_dispatch.h. Instead, let the .c files find it in the config.h.

**Comment by DennisHeimbigner** [comment]
We can fix netcdf_dispatch.h by creating netcdf_dispatch.in to do the substitution.
Ditto netcdf_meta.h.

**Comment by edwardhartnett** [comment]
OK, the version is currently 3, and the netcdf_dispactch.h file is generated at build time, so I will close this issue...
