### ISSUE TITLE
redefining chunking with nc_def_var_chunking on an existing NetCDF file

### ISSUE THREAD

**Issue by miikama** [Unidata/netcdf-c#1932]
Hello,

I opened this ticket more to confirm my testing of defining chunking than as a bug. Thanks for any input!

I have a .nc netcdf template file that is generated from a .cdl template with `ncgen`. To create a new output from my software, I copy this .nc-template into a new file and the fill any fields I want. However, the sizes of the fields are determine runtime, and I would like to redefine the chunking of some (or all) fields.

I attached a code snippet that I thought would allow redefining chunking.

The [documentation](https://www.unidata.ucar.edu/software/netcdf/docs/group__variables.html#gae6439bae5a863994a175ac65f6e97b71) of  `def_var_chunking` states that the variable chunking cannot be changed after enddef(). I initially though this referred to just being in define mode, but after testing this out it seems that the chunking cannot be changed after the initial creation of the file, even if one is in define mode. Is this correct?

In this case, I guess my only solution is to use the template I have and recreate all the fields it contains in a completely new netcdf-file with the desired chunking.

NetCDF version:
4.6.0 (available in the Ubuntu 18.04 apt package manager as libnetcdf-dev)
System info
Description:    Ubuntu 18.04 LTS

```c++

#include <string>
#include <vector>

#include "netcdf.h"

#define ERR {if(err!=NC_NOERR)printf("Error at line %d: %s\n",__LINE__,nc_strerror(err));}

int main()
{

    /**
     *  Create a test file test.nc that has a single chunked 
     *  variable.
     *  
     * 
     *   OUTPUT from ncdump test.nc
     *   
     *   ```
     *      netcdf test {
     *  
     *      group: data {
     *      dimensions:
     *              dimension1 = 2 ;
     *              dimension2 = 4 ;
     *      variables:
     *              int variable(dimension1, dimension2) ;
     *      data:
     *  
     *      variable =
     *      _, _, _, _,
     *      _, _, _, _ ;
     *      } // group data
     *      }
     *   ```
     * 
     *   OUTPUT from h5ls -r -v test.nc
     * 
     *   ```
     *      ...
     *      /data/variable           Dataset {2/2, 4/4}
     *      Attribute: DIMENSION_LIST {2}
     *          Type:      variable length of
     *                  object reference
     *          Data:  (DATASET-1:566), (DATASET-1:862)
     *      Location:  1:1158
     *      Links:     1
     *      Chunks:    {1, 2} 8 bytes
     *      Storage:   32 logical bytes, 0 allocated bytes
     *      Type:      native int
     *   ```
     */

    int err, file_id, group_id, dim1_id, dim2_id, variable_id;

    // Create a test file with couple dimensions and a single variable
    err = nc_create("test.nc", NC_CLOBBER | NC_NETCDF4, &file_id); ERR
    err = nc_def_grp(file_id, "data", &group_id); ERR
    err = nc_def_dim(group_id, "dimension1", 2, &dim1_id); ERR
    err = nc_def_dim(group_id, "dimension2", 4, &dim2_id); ERR    
    std::vector<int> dim_ids {dim1_id, dim2_id};
    err = nc_def_var(group_id, "variable", NC_INT, dim_ids.size(), dim_ids.data(), &variable_id); ERR

    // Define chunking scheme for the variable
    std::vector<size_t> small_chunks {1,2};
    err = nc_def_var_chunking(group_id, variable_id, NC_CHUNKED, small_chunks.data()); ERR

    // Close the file
    err = nc_close(file_id); ERR


    // ################################
    //      reopen same file
    // ################################

    // Open the same file and get the chunked variable 
    err = nc_open("test.nc", NC_WRITE | NC_NETCDF4, &file_id); ERR
    err = nc_inq_grp_ncid(file_id, "data", &group_id); ERR
    err = nc_inq_varid(group_id, "variable", &variable_id); ERR

    // try to enter define mode
    err = ncredef(file_id); ERR
    std::vector<size_t> chunks {2,4};
    // And reset the chunking
    // However, this fails with an error message:
    //      'Attempt to define var properties, like deflate, after enddef.'
    err = nc_def_var_chunking(group_id, variable_id, NC_CHUNKED, chunks.data()); ERR

    err = nc_close(file_id); ERR

    return 0;   
}
```

Compiled with  `gcc redef.cpp -Wall -std=c++11 -O3 -lnetcdf -lcurl -lstdc++ -o main`

**Comment by edwardhartnett** [comment]
Correct: once the var is written to the file, the chunking cannot be changed.

I believe NCO has a utility that will allow you to copy the file and change the chunking...

**Comment by DennisHeimbigner** [comment]
The nccopy program will also allow rechunking.

**Comment by miikama** [comment]
Thank you, I also found that the `ncks` utility contains rechunking. 

This issue is then basically resolved, I'll close this.
