### ISSUE TITLE
change in behavior of nc_redef() since 4.7.4 release

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1935]
Something I noticed from PIO testing. Apparently, nc_redef() no longer returns error, if the file is in define mode. Of course, it should.

When I put nc_redef() line in nc_test4/tst_files6.c, it causes the test to fail.  NC_EINDEFINE is not returned, but should be.

```
     if (nc_create(FILE_NAME, NC_CLOBBER|NC_NETCDF4, &ncid)) ERR;
      if (nc_redef(ncid) != NC_EINDEFINE) ERR;

```

**Comment by DennisHeimbigner** [comment]
Can you do a bisection to find out where the change occurred?

**Comment by DennisHeimbigner** [comment]
Ok, the relevant code in hdf5file.c is this:
````
	return (nc4_info->cmode & NC_CLASSIC_MODEL) ? NC_EINDEFINE : NC_NOERR;
````

Since tst_files6.c creates the file as straight NC_NETCDF4 and not NC_CLASSIC_MODEL,
this behavior seems correct to me.

**Comment by edwardhartnett** [comment]
But did this change since 4.7.4?

**Comment by DennisHeimbigner** [comment]
Yes it changed. The old code (4.7.4) appears to return NC_EINDEFINE
even for non-classic netcdf-4 files.

**Comment by edwardhartnett** [comment]
OK, I guess I agree that redef() should not return EINDEFINE for non-classic files. I will close this issue and change my PIO test.
