### ISSUE TITLE
nccopy -d 0 -c / a.nc b.nc not work

### ISSUE THREAD

**Issue by an-ttt** [Unidata/netcdf-c#1936]
* netcdf 4.7.4
* win10 netcdf-c

nccopy -d 0 -c / a.nc b.nc not work;
My File a.nc has deflation level 9 and chunks, I am going to make b.nc no compression and no chunks, but failed.

After I changed the codes in three place, then it worked, but I am not sure it's a good fix

1. 
`//if(option_deflate_level >= 0 || hasfilterspecforvar(ofqn))
    //ocontig = NC_CHUNKED;
 if (option_deflate_level > 0 || hasfilterspecforvar(ofqn))
    ocontig = NC_CHUNKED;
 //
`

2. 
`} else if(option_deflate_level == 0) { /* special case; force off */
        shuffle_out = 0;
         //deflate_out = 0;
        deflate_out = 1;
        //
         deflate_level_out = 0;
}`

3. 
`//if(shuffle_out != 0 || deflate_out != 0)
        //  NC_CHECK(nc_def_var_deflate(ogrp, o_varid, shuffle_out, deflate_out, deflate_level_out));
        if (shuffle_out != 0 || (deflate_out != 0 && deflate_level_out != 0))
              NC_CHECK(nc_def_var_deflate(ogrp, o_varid, shuffle_out, deflate_out, deflate_level_out));
//`

**Comment by WardF** [comment]
Would it be possible for you to attach the file a.nc, so that I might duplicate your test as closely as possible? If that is not practical, just let me know and I'll create a file on my end.

**Comment by WardF** [comment]
The issue appears to be in nccopy.c:1133, where `shuffle_out == 0` and `deflate_out == 0`.  Diving in to `nc_def_var_deflate()`, I'm finding text that specifies it is unclear whether these values should specify 'disable' or 'leave as is'.  It seems to me that there should be a way to turn off the compression.  @edwardhartnett, @DennisHeimbigner, what am I missing here? It looks like work was put in to handle 'no shuffle, no compression' such that they don't disable compression, but I'm not finding an alternative way to disable compression.

**Comment by WardF** [comment]
@an-ttt A work-around would be to use `ncdump a.nc  > a.cdl` and then `ncgen -k 4 -o b.nc a.cdl`; this introduces an intermediary file, but the end result is an uncompressed binary NetCDF file.

**Comment by DennisHeimbigner** [comment]
Sigh! I wish that the intertwining of filters and chunking was less implicit that it is.
Anyway, part of the problem is that -d 0 specifies a deflate level of zero and nccopy
is interpreting it as turning on deflation but at level 0, so chunking is implicit.
However elsewhere deflatelevel ==0 is interpreted as no-deflation.
I would have said that you should use the -F flag, but I see that it does not work either.
The code I created is such a frankenstein; it really needs revision AGAIN!

**Comment by an-ttt** [comment]
Good to know It's in fixing, thanks.
As to the a.nc, you can try any nc file that use the "nccopy -d9 ..." to get the  deflation level 9 file to test.
