### ISSUE TITLE
It would be great it there was an official CMake FindNetcdf.cmake

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1943]
Not for the first time, some modelers at NOAA and NCAR are tripping over different FindNetcdf.cmake files being used in different projects, coming up with different results.

It would be great if someone who knows cmake a whole lot better than I do could select from among the candidates and promote an official FindNetcdf.cmake file, which correctly handles all the complexity of finding netcdf-c and netcdf-fortran, and setting the appropriate cmake variables to help projects build with netCDF.

Last time I checked, there was a FindHDF5.cmake actually distributed with cmake. If we could select a working FindNetcdf.cmake, we could submit it to the cmake team, and hope to solve this problem for all cmake users in a standard way. 

This would help cmake-using HPC teams a lot! As it is, they write or find a FindNetcdf.cmake somewhere, and all end up with different variables and options. Hilarious build confusion may then ensue.

**Comment by WardF** [comment]
This would be great; it feels like starting with one of the extant FindNetcdf.cmake files being used would be a good starting place. I'll see what I can find. I agree that getting something bundled with cmake would be fantastic.  

Are any of the NOAA projects *using* FindNetcdf.cmake using publicly-available projects/code? I can spin up a netcdf hello-world project to test with/against, but if I can avoid reinventing the wheel, I'll take it.

**Comment by edwardhartnett** [comment]
Yes, for example: https://github.com/NOAA-EMC/UFS_UTILS

**Comment by edwardhartnett** [comment]
Here's an issue in NOAA codes which seems to be caused by differing FindNetCDF.cmake files: https://github.com/NOAA-EMC/hpc-stack/issues/149#issuecomment-769903241

**Comment by ZedThree** [comment]
Just a note that any `FindnetCDF` module should start with something like

```cmake
find_package(netCDF QUIET CONFIG)` 
if (netCDF_FOUND)
  set(netCDF_FOUND TRUE)
  return()
endif()
```

in order to pick up a `netCDFConfig.cmake` file as first preference, as this already exports the `netCDF::netCDF` target.

**Comment by edwardhartnett** [comment]
OK, this is not really a netcdf-c issue. I will close it...
