### ISSUE TITLE
Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument" on MS windows with file on OpenDAP server

### ISSUE THREAD

**Issue by ninsbl** [Unidata/netcdf-c#1946]
To report a non-security related issue, please provide:

I am trying to read a netcdf file through OpenDAP and via GDAL (GDAL 3.0.3, released 2020/01/08) and ncdf4 (version 1.17) package in R 4.0 but I get the following error message:
```
library(ncdf4)
f<-"https://thredds.met.no/thredds/dodsC/senorge/seNorge_2018/Archive/seNorge2018_2021.nc"
nc<-nc_open(f)
Error in R_nc4_open: NetCDF: Invalid argument
Error in nc_open(f) : 
  Error in nc_open trying to open file https://thredds.met.no/thredds/dodsC/senorge/seNorge_2018/Archive/seNorge2018_2021.nc
```
Trying to do the same with GDAL (through OSGeo4W) gives a bit more insight:
```
gdalinfo /vsicurl/https://thredds.met.no/thredds/fileServer/senorge/seNorge_2018/Archive/seNorge2018_2021.nc
Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
ERROR 4: `/vsicurl/https://thredds.met.no/thredds/fileServer/senorge/seNorge_2018/Archive/seNorge2018_2021.nc' not recognized as a supported file format.
gdalinfo failed - unable to open '/vsicurl/https://thredds.met.no/thredds/fileServer/senorge/seNorge_2018/Archive/seNorge2018_2021.nc'.
```

My understanding is that reading the netcdf file strings conversion between UTF8 and windows codepages fails...
Here some more on string handling/conversion on MS Windows: https://docs.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-widechartomultibyte
Though I have to say, that I am not sure in which piece of software the problem is located, yet my guess is it is netcdf library...

**Comment by DennisHeimbigner** [comment]
Do you know what version of the netcdf library you are using?

**Comment by DennisHeimbigner** [comment]
I ran using Visual Studio Community Edition 2019 and using the current netcdf master
from github.
This command succeeds:
> ncdump -h "https://thredds.met.no/thredds/dodsC/senorge/seNorge_2018/Archive/seNorge2018_2021.nc"

In your report, it looks like you are using the following path:
> gdalinfo /vsicurl/https://thredds.met.no/thredds/fileServer/senorge/seNorge_2018/Archive/seNorge2018_2021.nc

but I assume the leading /visicurl/ is a gdal thing and is stripped before passing to netcdf, correct? Because that url is illegal otherwise.

**Comment by ninsbl** [comment]
Thanks for looking into this!

I did not think of using the netcdf binaries. `ncdump` does succeed also on my Windows box. However, there I noticed this:
```
                :comment = "Our open data are licensed under Norwegian Licence for Open Government Data (NLOD) or a Creative
Commons Attribution 4.0 International License at your preference. Credit should be given to The Norwegian Meteorological
institute, shortened ÔÇ£MET NorwayÔÇØ, as the source of data." ;
```
Notice the `ÔÇ£MET NorwayÔÇØ,` in the string. In Python 3 this is presented as `“MET Norway”`
See:
```
from netCDF4 import Dataset as NetCDFFile
nc = NetCDFFile("https://thredds.met.no/thredds/dodsC/senorge/seNorge_2018/Latest/seNorge2018_20210130.nc")
```

On the commandline (ncdump) I have netcdf library version 4.6.2 of Sep  6 2019 22:47:40.
Not sure which version the R packages uses...

P.S.: Yes, `/vsicurl/` instructs GDAL to access the URL as a [virtual file system](https://gdal.org/user/virtual_file_systems.html?highlight=vsicurl)... My reason for trying GDAL was that from my understanding it does not use OpenDAP, and if the error also occurrs there, the issue is probably not with OpenDAP. But it is hard to locate...

**Comment by DennisHeimbigner** [comment]
The character set issue is tricky. Internal to the netcdf library we do attempt
to handle UTF8, but we do not apply it to the results; we just send out the characters
we receive.  On linux, this properly shows utf8, probably MAC also.
Windows still refuses to byte the utf8 bullet.
If you capture the ncdump output in a file and look at it in some editor,
it may properly represent those characters.

**Comment by ninsbl** [comment]
Yes, indeed. In a text editor the characters are displayed correctly.

So, where do you suggest the issue should be adressed?
Both GDAL and the R package seem to expect a different fromat than they get (encoded string?). Would the proper way to fix this Windows issue be adjust the way those two handle output from the netcdf4 library (like python-netcdf obviously does).

**Comment by DennisHeimbigner** [comment]
My speculation is that R and GDAL are not properly set up to handle utf8
on windows. So, I am afraid you are going to have to contact them
about this issue. Since you have a concrete example, that will give them
something to work with to fix it.

**Comment by ninsbl** [comment]
Ok. Anyway, thanks for helping with error diagnostics! Will take that up with R/ncdf4 and GDAL.
