### ISSUE TITLE
Move away from M4 file generation

### ISSUE THREAD

**Issue by ibaned** [Unidata/netcdf-c#1950]
M4 is common on Linux systems but not so much on Windows. Is it possible to use something more portable, like CMake file configuration and C preprocessor macros to generate the source files that are right now generated by M4?

**Comment by WardF** [comment]
Yes, and in fact we provide the CMakeconfig.txt files in parallel with the gnu autotools-based configuration files, so that we might compile on Windows as well as *nix :).  Thanks!

**Comment by ibaned** [comment]
I'm aware of the provided support for CMake. My problem is much more specific to basically trying to build non-release versions of netcdf on Windows. In particular, files like `libsrc/attr.c` don't exist in non-release versions, and CMake can't generate them on Windows. Right now I'll try to get the files from release versions and combine them with other fixes, but the issue remains.
