### ISSUE TITLE
Unable to support CDF5 feature because size_t is less than 8 bytes

### ISSUE THREAD

**Issue by Dave-Allured** [Unidata/netcdf-c#1967]
Problem encountered with NetCDF 4.7.4 (current version).

Macports reports Cmake configure failure entangled with CDF5 support.  Affects an older version of Mac OS, High Sierra released 2017, maybe others.  Quoting the downstream issue:
https://trac.macports.org/ticket/62472

> Trying to install netcdf @4.7.4 with the +universal variant (on macOS High Sierra) fails:
> 
> CMake Error at CMakeLists.txt:1360 (MESSAGE):
>   Unable to support CDF5 feature because size_t is less than 8 bytes

A complete configure log is attached to the downstream ticket.

* Does this look familiar?
* Is there an easy patch to fix this in 4.7.4?
* Can this be fixed for a future release?

**Comment by DennisHeimbigner** [comment]
Is the underlying machine 32 bit (vs 64 bit)?

**Comment by Dave-Allured** [comment]
Yes, the underlying machine is 32 bit.  I missed that before, sorry.  Line 2 of the configure log:

> :debug:sysinfo macOS 10.13.6 (darwin/17.7.0) **arch i386**

So the next question is, is 4.7.4 supposed to support a 32-bit system?

**Comment by WardF** [comment]
@Dave-Allured 4.7.4 does support 32-bit OS, but it does not support the CDF5 format in 32 bit environments.  The configure and CMakeLists.txt check for 32-bit architecture and turn off CDF5 support by default; if the option is passed to try to force it on, we see error messages as above.

**Comment by Dave-Allured** [comment]
@WardF, thanks for explaining.  I will ask Macports to disable CDF5 when building for i386.
