### ISSUE TITLE
Which netCDF versions have the nc_inq_var_deflate() regression for HDF4 files?

### ISSUE THREAD

**Issue by czender** [Unidata/netcdf-c#1968]
Hi All,

Discussions during such as this one

https://www.unidata.ucar.edu/mailing_lists/archives/netcdfgroup/2013/msg00329.html

during the netCDF 4.3.3 release cycle recount that `nc_inq_var_chunking()`
was altered to work on HDF4 files, while other netCDF4 calls like
`nc_inq_var_deflate()` already did. My recollection is that those changes
worked smoothly, and since then NCO has basically treated HDF4 like
any netCDF4 file so long as the netCDF library was >= 4.3.3.

However, I just noticed that netCDF 4.7.4 reports
Error (-111) "NetCDF: Attempting netcdf-4 operation on netcdf-3 file"
when `nc_inq_var_deflate()` is called on HDF4 files.
This regression causes NCO to break when manipulating HDF4 files.

It looks like this regression is fixed in netCDF-4.8.0-development.
That's good, but 4.8.0 is not yet released and I need to patch NCO to
work with older netCDF libraries in perpetuity. Would someone please
tell me which netCDF version(s) contain this regression relative to 4.3.3?

Many thanks,
Charlie

**Comment by DennisHeimbigner** [comment]
This issue appears to be limited to 4.7,4 as part of the multiple filter fiasco.

**Comment by czender** [comment]
Perfect, thanks. I've just implemented a workaround to restore NCO's HDF4 functionality when linked to netCDF 4.7.4.
