### ISSUE TITLE
Test "tst_h_atts3.c" fails with HDF5 v1.12.0

### ISSUE THREAD

**Issue by rmvanhees** [Unidata/netcdf-c#1971]
"make check" failes when netcdf-c 4.8.0 is compiled against hdf5 1.12.0 at test "tst_h_atts3.c".
This can be fixed bij replacing line 212 in tst_h_atts3.c:

> H5O_info_t obj_info;

by:

> #if H5_VERSION_GE(1,12,0)
>       H5O_info2_t obj_info;
> #else
>       H5O_info_t obj_info;
> #endif

Greetings, Richard

**Comment by rmvanhees** [comment]
I did something wrong.

Sorry for the confusion, Richard

**Comment by ArchangeGabriel** [comment]
I’ve also having this test failing, and I’ve seen this warning:
```
/build/netcdf/src/netcdf-c-4.8.0/h5_test/tst_h_atts3.c: In function ‘main’:
/build/netcdf/src/netcdf-c-4.8.0/h5_test/tst_h_atts3.c:282:37: warning: passing argument 6 of ‘H5Oget_info_by_idx3’ from incompatible pointer type [-Wincompatible-pointer-types]
  282 |                                  i, &obj_info, H5O_INFO_BASIC, H5P_DEFAULT) < 0) ERR;
      |                                     ^~~~~~~~~
      |                                     |
      |                                     H5O_info1_t *
In file included from /usr/include/H5Apublic.h:22,
                 from /usr/include/hdf5.h:23,
                 from /build/netcdf/src/netcdf-c-4.8.0/h5_test/tst_h_atts3.c:14:
/usr/include/H5Opublic.h:191:73: note: expected ‘H5O_info2_t *’ but argument is of type ‘H5O_info1_t *’
  191 |     H5_index_t idx_type, H5_iter_order_t order, hsize_t n, H5O_info2_t *oinfo,
      |                                                            ~~~~~~~~~~~~~^~~~~
```
Did your change fixed the test or not in the end? Or only the warning maybe?

My error output is `*** Checking vlen of compound file...Sorry! Unexpected result, /build/netcdf/src/netcdf-c-4.8.0/h5_test/tst_h_atts3.c, line: 289`

**Comment by opoplawski** [comment]
I'm also seeing this test fail with hdf5 1.12.0 so I think this should be re-opened.

**Comment by nh2** [comment]
Coming from https://github.com/Unidata/netcdf-c/issues/1857#issuecomment-900493514

```
FAIL: tst_h_atts3
=================

*** Checking HDF5 attribute functions some more.
*** Creating tst_xplatform2_3.nc with HDF only...ok.
*** Checking vlen of compound file...Sorry! Unexpected result, tst_h_atts3.c, line: 289
FAIL tst_h_atts3 (exit status: 2)
```

`hdf5` is compiled with `--with-default-api-version=v110`, in case that's relevant.
