### ISSUE TITLE
Does not build on Manjaro

### ISSUE THREAD

**Issue by gdkrmr** [Unidata/netcdf-c#1978]
On current manjaro v4.8.0 does not configure:

```
-- Found HDF5 libraries version 1.12.0
-- Using HDF5 include dir: /usr/include
-- HDF5 has szip.
CMake Error at CMakeLists.txt:794 (MESSAGE):
  /usr/lib/libhdf5.so does not contain symbol '_H5Literate'.  Please
  recompile your libhdf5 install using '--with-default-api-version=v18'.
```

**Comment by WardF** [comment]
It looks like your libhdf5 was not built with a default-api-version of v18.  I am investigating a current pull request, #1973, that may correct this, but in the mantime you may need to install libhdf5 by hand, configuring it with `--with-default-api-version-v18`.

**Comment by opoplawski** [comment]
You should also be able to compile netcdf with CPPFLAGS=-DH5_USE_110_API

**Comment by gdkrmr** [comment]
That worked! Thanks!

**Comment by gdkrmr** [comment]
I get one failed test, should I open a bug report?

Compiled with `CPPFLAGS=-DH5_USE_110_API ENABLE_NCZARR=1` and `cmake`

```
149/203 Test #149: tst_h_atts3 ...........................***Failed    0.02 sec
        Start 150: tst_h_atts4
```

**Comment by opoplawski** [comment]
There already is one - #1971

**Comment by srikar-iist** [comment]
tried for hdf5 - 1.12.1 with netcdf - 4.8.0 :

Getting the same error : configure: error: HDF5 was not built with API compatibility version v18. Please recompile your libhdf5 install using '--with-default-api-version=v18'.

when I changed the CPPFLAGS=-DH5_USE_110_API

getting another error : configure: error: Compiling a test with HDF5 failed.  Either hdf5.h cannot be found, or config.log should be checked for other reason.
