### ISSUE TITLE
nc_perf/tst_gfs_data_1.c is not really working well

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1997]
There is a benchmarking program/test that I added in a recent release, tst_gfs_data_1.c. It tests that netcdf-c can output data the way that the NOAA GFS model does it, i.e. with parallel I/O and zlib compression.

This test is working in that it will detect problems with writing this way, which is good.

But it's not really working well because I messed up the decompositions. I am using this same test in the CCR project and have discovered some problems, which I am fixing there. Then I will update the netcdf-c version of the test.

**Comment by WardF** [comment]
Thanks @edhartnett , appreciated as always!
