### ISSUE TITLE
Zarr generation creates a unexpected array value for fill_value

### ISSUE THREAD

**Issue by rouault** [Unidata/netcdf-c#2008]
Version: libnetcdf 4.8.0, built on Ubuntu 20.04 with NCZarr support

Given simple.cdl:
```
netcdf test {
dimensions:
	dim = 1;
variables:
	int test(dim) ;
		test:_FillValue = -32767 ;
data:

 test = 1;
}
```
``~/install-netcdf-4.8.0/bin/ncgen -4 -lb -o "file://simple_zarr#mode=nczarr,file"  simple.cdl`` generates a  ``simple_zarr/test/.zarray`` file with following content :
```json
"zarr_format": 2,"shape": [1],"dtype": "<i4","chunks": [1],"fill_value": [-32767],"order": "C","compressor": null,"filters": null}
```
``"fill_value": [-32767]`` doesn't match what the Python Zarr reference implementation does. It would generate ``"fill_value": -32767`` . The spec at https://zarr.readthedocs.io/en/stable/spec/v2.html#fill-value-encoding is admittedly a bit vague about that, but I wouldn't expect an array from reading it.

**Comment by DennisHeimbigner** [comment]
Good catch. I will have to check, but in netcdf. the value of the attribute is actually a sequence of values, possibly of size 1. I did the translation directly. Instead, I should see if the attribute has a single value and then stored it as such.
Should be an easy fix.

**Comment by DennisHeimbigner** [comment]
Also, this applies because of the netcdf _FillValue attribute.

**Comment by DennisHeimbigner** [comment]
Fixed by PR https://github.com/Unidata/netcdf-c/pull/2017
