### ISSUE TITLE
ncdap_test/test_pathcvt fails on OSX

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#2018]
I am observing failures when running this test on the command line in OSX that do not manifest immediately in Linux, although I'm also seeing different non-fatal oddities in the linux command line when using cmake.  Opening this issue, will flesh out the details as I investigate further.

**Comment by WardF** [comment]
Appears to be related to the `-n` argument being passed to echo, and the explicit `/bin/sh` shell being used.  From `man echo`

>  Some shells may provide a builtin echo command which is similar or identical to this utility. 
> Most notably, the builtin echo in sh(1) does not accept the -n option.  Consult the builtin(1) manual page.

**Comment by WardF** [comment]
Replacing `/bin/sh` with `/bin/bash` fixes the problem on OSX but may introduce additional portability issues.  Investigating.

**Comment by DennisHeimbigner** [comment]
I had a lot of trouble with this test because of the way that different shells handle backslash escapes. Looks like we have another problem to contend with.
Can you post the log file for this test?
Does the builtin echo in bash differ from the echo in sh in accepting -n?

**Comment by WardF** [comment]
@DennisHeimbigner at first glance, it appears that echo in bash accepts `-n` and fixes the issue on OSX.  Refreshing my memory on the portability issue.

**Comment by WardF** [comment]
The log reflects '-n' being passed as part of the string being printed, instead of interpreted, so it was showing up in the text file being concatenated.  Also, because -n wasn't suppressing the trailing newline, the function in the shell script was generating multiple lines per test case.  I'll regenerate the log file.

**Comment by WardF** [comment]
This is the log file generated with the `echo` command used by `/bin/sh`.  I've found a fix for this and am checking for portability now.

* [tmp_pathcvt.txt](https://github.com/Unidata/netcdf-c/files/6627117/tmp_pathcvt.txt)
