### ISSUE TITLE
Inconsistency in text vs. code in configure.ac regarding --disable-dap-remote-tests

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#2045]
```
# Default is to do the short remote tests.
AC_MSG_CHECKING([whether dap remote testing should be enabled (default off)])
AC_ARG_ENABLE([dap-remote-tests],
              [AS_HELP_STRING([--enable-dap-remote-tests],
                                 [enable dap remote tests])])
test "x$enable_dap_remote_tests" = xno || enable_dap_remote_tests=yes
if test "x$enable_dap" = "xno" ; then
  enable_dap_remote_tests=no
fi
AC_MSG_RESULT($enable_dap_remote_tests)
```

But looking at this code, I think the tests are on by default, and the text in AC_MSG_CHECKING and AS_HELP_STRING is incorrect.

If I do this configure:

`autoreconf -i && CC=mpicc LDFLAGS=-L/usr/local/hdf5-1.12.1_v120_zlib-ng_mpich/lib CPPFLAGS=-I/usr/local/hdf5-1.12.1_v120_zlib-ng_mpich/include ./configure --enable-parallel-tests 
`
I get:
`checking whether dap remote testing should be enabled (default off)... yes
`
So it seems this is enabled by default. @DennisHeimbigner and @WardF do you want dap-remote-testing on by default? In which case I will correct the text. Otherwise I can turn it off by default.

(I note it is on by default in the CMake build.)

**Comment by DennisHeimbigner** [comment]
You are correct, the comment is incorrect. The history is that we had
problems with the remote test server and I temporarily turned off dap remote tests.
Apparently when  I re-enabled it, I forgot to fix the comment.
But this raises a question: should it be off by default?

**Comment by WardF** [comment]
I think the more tests that are on by default, the better.  Otherwise we run a greater risk of issues creeping in undetected, and introduces a greater risk from misconfiguring our CI system and overlooking the test.  So, I would say lets keep the remote tests on, and we can make it clear that if they fail in a way that indicates the issue is with the remote server and not the netCDF library, it can be disabled.

**Comment by DennisHeimbigner** [comment]
ok, we can piggy-back this change on the next PR.

**Comment by edwardhartnett** [comment]
OK, I have fixed the text and comment to match what was happening and what is apparently what is desired: the dap remote tests are run by default, if dap is enabled...
