### ISSUE TITLE
nc_open fails in Windows with network drives

### ISSUE THREAD

**Issue by abhibaruah** [Unidata/netcdf-c#2060]
netcdf version: 4.8.0
hdf5 version: 1.8.12
OS: windows 10
Compiler: VS2019 u7.7

This was caught while running some of our tests on netcdf files hosted in a network drive.
nc_open fails when the file is accessed using the network path. However, if I map the network drive, and then try to access the same file, it works fine. 

**I could not reproduce the issue with netcdf v4.7.4 + hdf5 1.8.12.**

As shown in the repro code below, v4.8.0 errors if the file is accessed by the network path
`string FILE_NAME = "\\\\mathworks\\devel\\sandbox\\abaruah\\Features\\NetCDF_New_Features\\temp\\monotonic.nc";`

The output of the program below is
Open status: 2
NCID: -858993460
status after close = -33

But if I map the network drive and then try to access the file, it works
`string FILE_NAME = "Y:\\abaruah\\Features\\NetCDF_New_Features\\temp\\monotonic.nc";`

Open status: 0
NCID: 65536
status after close = 0

```
#include <stdio.h>
#include <string>
#include <netcdf.h>
#include <iostream>
#include <vector>

using namespace std;

int
main()
{
    int status;
    int ncid;
    string FILE_NAME = "\\\\mathworks\\devel\\sandbox\\abaruah\\Features\\NetCDF_New_Features\\temp\\monotonic.nc";
    //string FILE_NAME = "Y:\\abaruah\\Features\\NetCDF_New_Features\\temp\\monotonic.nc";

    status = nc_open(FILE_NAME.c_str(), NC_NOWRITE, &ncid);
    std::cout << "Open status: " << status << std::endl;
    std::cout << "NCID: " << ncid << std::endl;
    status = nc_close(ncid);
    printf("status after close = %d\n", status);


    return 0;
}
```

**Comment by DennisHeimbigner** [comment]
Frankly, I completely forgot about network drives. I suspect I assumed they
would all be mounted under a drive letter. Which probably serve as a work-around.

**Comment by abhibaruah** [comment]
Correct. Mounting the network drive as a drive letter works as a workaround.
But since unmounted network drives worked in previous versions of netcdf, we are concerned if this would break existing customer workflows once we upgrade to v4.8.0.

**Comment by DennisHeimbigner** [comment]
I will add a fix for this case.

**Comment by DennisHeimbigner** [comment]
I tried to fix this here: https://github.com/Unidata/netcdf-c/pull/2065

But since I do not have access to  network drive, I cannot test it.
When it gets integrated, please let me know if it works.

**Comment by DennisHeimbigner** [comment]
This has been integrated into the gihub master. Please test it if you can.

**Comment by abhibaruah** [comment]
Thanks a lot. I tried this out. The bug is resolved.
