### ISSUE TITLE
cannot open zarr array with "fill_value": null

### ISSUE THREAD

**Issue by rouault** [Unidata/netcdf-c#2063]
netcdf git at 84f0696, Ubuntu 20.04
on the attached zarr dataset [byte_fill_value_null.zarr.zip](https://github.com/Unidata/netcdf-c/files/6956668/byte_fill_value_null.zarr.zip)  (after unzipping it),

```
$ ncdump/ncdump "file:///tmp/byte_fill_value_null.zarr#mode=zarr,file"
ncdump/ncdump: file:///tmp/byte_fill_value_null.zarr#mode=zarr,file: NetCDF: NCZarr error
```

Changing fill_value to a numeric value works around the issue

**Comment by DennisHeimbigner** [comment]
Ok, I am testing fixes for:
Issue https://github.com/Unidata/netcdf-c/issues/2063
Issue https://github.com/Unidata/netcdf-c/issues/2062
Issue https://github.com/Unidata/netcdf-c/issues/2061
Thanks for catching these.

**Comment by DennisHeimbigner** [comment]
Fixed by PR https://github.com/Unidata/netcdf-c/pull/2066
