### ISSUE TITLE
Compilation failure on 4.8.1: manyurls.h not found

### ISSUE THREAD

**Issue by ArchangeGabriel** [Unidata/netcdf-c#2085]
The exact excerpt:
```
/build/netcdf/src/netcdf-c-4.8.1/ncdap_test/test_manyurls.c:6:10: fatal error: manyurls.h: No such file or directory
    6 | #include "manyurls.h"
      |          ^~~~~~~~~~~~
compilation terminated.
```

Seems the file wasn’t commited in https://github.com/Unidata/netcdf-c/commit/cab37435682f0e0c7890cf47e33d7c0247eb2e10 where it should have?

**Comment by DennisHeimbigner** [comment]
As a workaround, you can build with --disable-dap-long-tests.

**Comment by DennisHeimbigner** [comment]
Fixed by PR https://github.com/Unidata/netcdf-c/pull/2091
