### ISSUE TITLE
Parallel Tests Fail

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#211]
The cmake-based parallel tests are failing; autotools may as well, I haven't checked as of yet.  See

* http://my.cdash.org/testDetails.php?test=23163288&build=908050

for more information.  This affects openmpi and mpich-based builds.

**Comment by edhartnett** [comment]
I build 4.4.0 on a linux system yesterday with this configure, and parallel
tests passed:

 .CC=mpicc /configure --with-zlib=/usr/local --prefix=/usr/local
--with-szlib=/usr/local --with-hdf5=/usr/local --enable-pnetcdf
--enable-parallel-tests --enable-logging

Ed

**Comment by WardF** [comment]
Hey Ed,

I’ve just fixed this and am waiting for the travis-ci checks to finish so
that I can merge it into master, thanks! The issue was cmake-specific, a
directive to compile a particular binary had been added to Makefile.am but
not CMakeLists.txt

   - https://travis-ci.org/Unidata/netcdf-c

Thanks!

-Ward
​

**Comment by WardF** [comment]
The test program `tst_mode` was not being generated by cmake-based builds.  This has been corrected.
