### ISSUE TITLE
netcdf-c-4.8.1.tar.gz not on ftp site...

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#2110]
4.8.1 was released but the distribution needs to be copied to the ftp site...

**Comment by WardF** [comment]
The ftp site has been removed, but it remains available [via http(s) download](https://www.unidata.ucar.edu/downloads/netcdf/).  Tagging @ddirks and @oxelson for this conversation so that they can weigh in; they've been putting in quite a bit of work on the web backend!

**Comment by edwardhartnett** [comment]
OK, good to know!

There's some data files available via ftp used in netcdf testing. Will those be available somewhere, somehow? Will the ftp commands still work, or do they need to be changed to something else for a script to download a test data file?

**Comment by DennisHeimbigner** [comment]
Those data files that our testing uses are for testing HDF4.
When the removal of the ftp site was raised some time ago,
I raised this issues, but never got any answers.b

**Comment by oxelson** [comment]
Hi @DennisHeimbigner, I'm happy to answer any questions you may have.

**Comment by DennisHeimbigner** [comment]
The files needed for hdf4 testing are in
> ftp://ftp.unidata.ucar.edu/pub/netcdf/sample_data/hdf4/*

I see that this url is still working, but I assume it will disappear soon.
Can we put these files in someplace like google drive or gihub
and download them via a bash script?

**Comment by oxelson** [comment]
> The files needed for hdf4 testing are in
> 
> > ftp://ftp.unidata.ucar.edu/pub/netcdf/sample_data/hdf4/*
> 
> I see that this url is still working, but I assume it will disappear soon.
> Can we put these files in someplace like google drive or gihub
> and download them via a bash script?

Hi Dennis, let's stash them with the rest of the netCDF downloads out on the artifacts/downloads server.  They will be publicly available for your scripts (and anyone ) to access.  I'll follow up with you tomorrow about this.

**Comment by gsjaardema** [comment]
What should be the canonical site for downloading releases:

- https://www.unidata.ucar.edu/downloads/netcdf/
- https://github.com/Unidata/netcdf-c/archive/refs/tags/

I can update the spack package to point to either of these, but would like it to be the one you recommend.

**Comment by gsjaardema** [comment]
Does the https://www.unidata.ucar.edu/downloads/netcdf/ site contain past releases, or only the current?  I tried to download a previous version using the url pattern for 4.8.1 and it couldn't find it...

**Comment by edhartnett** [comment]
I would recommend the GitHub release site, since that's where releases
happen. The website is only updated after the release at some point, I
believe...
