### ISSUE TITLE
Reading .nc4 data

### ISSUE THREAD

**Issue by benberlin7** [Unidata/netcdf-c#2115]
I have read out .nc data with c#, vs2019, netCDF 4.7.2 and SDS2.0.3 with succes, but when using the same code to open a nc4 dataset it fails with the exception : "Extension .nc4 is not registered in the factory".

`try{ dataset = DataSet.Open(path_to_nc4_file); } catch(Exception ex) { Console.Write(ex.Message); }`

Any idea how to manage that?

**Comment by WardF** [comment]
I'm afraid I don't; I am unfamiliar with `SDS`, you might try contacting support for the software you are using; it has clearly incorporated netCDF support, but I cannot guess at why their later release is unable to read the .nc4, nor can I make an educated guess (that I'm satisfied with) based on the exception being returned.
