### ISSUE TITLE
Memory issue with byte-range reading

### ISSUE THREAD

**Issue by abhibaruah** [Unidata/netcdf-c#2122]
NetCDF version: v4.8.1
OS: Debian 10

This issue happens only with netcdf byte-range reading.
When we open an http link for byte-range reading, followed by closing the ncid, the process aborts with a 
`free(): invalid pointer`
error message.

The issue happens with netcdf v4.8.1 (I tried it with hdf5 v1.8.12 and v1.10.7).
The memory issue can be seen only if environment variable MALLOC_CHECK_ is set to 3 before the program execution.

`setenv MALLOC_CHECK_ 3`
See this [link](https://support.microfocus.com/kb/doc.php?id=3113982) for more details about the MALLOC_CHECK_ env variable.

For v1.8.12, to enable byte-range reading, Dennis asked me to add the following to netcdf/include/ncconfigure.h
```
#ifndef HAVE_H5ALLOCATE_MEMORY
#define H5allocate_memory(size,clear) ((clear)?calloc(1,(size)):malloc(size))
#define H5free_memory(buf) free(buf)
#define H5resize_memory(mem,size) realloc(mem,size)
#endif
```

The code to reproduce the memory issue:

```
# include <stdio.h>
# include <netcdf.h>
# include <string>

int main(int argc, char *argv[])
{
    int ncid, status;
	printf("Enter the program");
	std::string filename = "https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadF/2017/060/01/OR_ABI-L1b-RadF-M3C01_G16_s20170600106087_e20170600116454_c20170600116497.nc#mode=bytes";
    status = nc_open(filename.c_str(), NC_NOWRITE, &ncid);
	printf("Status = %d\n", status);
    printf("NCID = %d\n", ncid);
	
	status = nc_close(ncid);
	printf("Status = %d\n", status);
	
	return 0;
}
```

The abortion occurs on the line `status = nc_close(ncid);`
The output of the program above is:
```
Enter the programStatus = 0
NCID = 65536
free(): invalid pointer
Abort

```

P.S: We do not build hdf5 with ROS3 enabled.

**Comment by DennisHeimbigner** [comment]
Ok, I think I have a patch for this. I will put up a PR shortly.
The fix is to change netcdf-c/libhdf5/H5FDhttp.c line 352
from
>    file->url = H5allocate_memory(strlen(name+1),0);

to
>    file->url = H5allocate_memory(strlen(name)+1,0);

**Comment by DennisHeimbigner** [comment]
Fixed by PR https://github.com/Unidata/netcdf-c/pull/2127
