### ISSUE TITLE
Can dimscales be made optional...

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#2128]
I encountered a file that was taking a very long time to write in netCDF-4 (hdf5-based) format.  I ran this through valgrind and it shows that approximately 85% of the execution time was due to `H5DSattach_scale` and its descendents.  As I doubled the complexitfy of this file, an even higher percentage of the time was taken by the attaching of the dimscales.

I then modified `nc4hdf.c` and commented out the call to `H5DSattach_scale` and reran the problem at various scales and the execution time was comparable to what I see for the netCDF-5 output.  The table below shows these timings:

size | netcdf-4 | netcdf-5 | netcdf-4-nodimscale
-- | -- | -- | --
4 | 21.46 | 5.89 | 10.63
8 | 53.28 | 13.05 | 21.02
16 | 146.97 | 33.74 | 42.61
32 | 871.4 | 64.71 | 82.63
64 | 2491.48 | 130.67 | 178.69

The files are definitely out-of-the ordinary for typical netCDF files and contain 10,817 dims and 189,026 vars at the largest size and 952 dims and 16,406 vars at the smallest size.

I was able to read the files generated by the `netcdf-4-nodimscale` modification and the reads seemed to be as fast as reading the normal netcdf-4 files.  

So, the question is what functionality am I losing by not paying the cost of attaching dimscales to my variables? Is this more important for some uses than others?    

I did see this information:
> If dimension scales are not used, then netCDF-4 can still edit the file, and will invent anonymous dimensions for each variable shape. This is done by iterating through the space of each dataset. As each space size is encountered, a phony dimension of that size is checked for. It it does not exist, a new phony dimension is created for that size. In this way, a HDF5 file with datasets that are using shared dimensions can be seen properly in netCDF-4

which seems to indicate that the dimension scales are optional, but there is some coherence lost between variables that use the same dimensions to specify their shapes, but I'm not sure how that affects my files if I am just writing/reading them without modifying them...

Thanks.

**Comment by DennisHeimbigner** [comment]
It used to be that some flags in cmode were being used to record internal state: NC_INDEF for example.
I or someone else fixed this at some point so that the whole upper 16 bits of the cmode flags
is available.
Currently the only flag in the upper 16 bits is NC_CREORD at 0x20000,
so adding a flag at 0x10000 or 0x40000 should be ok.

**Comment by edwardhartnett** [comment]
@DennisHeimbigner we did indeed discuss changing the mode flags to 64 bit. I believe that would be fully backwards compatible. How could this produce files that could not be read by earlier versions of netCDF? 

However, didn't we since determine that there's actually plenty of open mode bits in the upper 16 bits of the existing mode flag? So I don't think we really need to increase the size of the mode flags...

As @gsjaardema notes, this PR is not related to the mode flag issue.

**Comment by DennisHeimbigner** [comment]
The problem with moving to a 64 bit cmode occurs at the binary level.
There are 4 possibilities based on whether the library being used assumes a 64 bit cmode
vs a client program compiled assuming a 32 bit cmode.
The size of what gets put on the stack by the client vs what get read off the stack by the
library will in the case of mismatches screw up the access to arguments following the cmode.

**Comment by gsjaardema** [comment]
@DennisHeimbigner that is true, but that is only an issue if the client is using an include file that is different than what was used during the build of the library.  If the include files and library are consistent, there should be no issue.  If they are different, then there can be many issues and incompatabilities...

**Comment by DennisHeimbigner** [comment]
I do not know about you, but I have numerous times encountered this kind of mismatch
with HDF5 headers vs library. As I said, this is a binary issue.

**Comment by edwardhartnett** [comment]
OK, I suggest we drop the whole idea of changing flags to 64-bit. I don't think it's needed and it might cause some confusion.

**Comment by wkliao** [comment]
To avoids adding a new flag, an approach can be to add a new API, e.g. nc_set_dimscale, to disable or enable using dimension scale. It is like nc_set_fill API, which can disable/enable the fill mode for the entire file.

**Comment by edwardhartnett** [comment]
OK, this improvement was made to the library in like 4.6.1. That is, dimscales are not used unless needed any more. I think this issue can be closed.
