### ISSUE TITLE
Failure in parallel build

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#2136]
I am getting the following error in my current parallel builds.  This looks like it was added in f6e25b695eeaf4706f81c290190d8e603457e601

```
TPL/netcdf/netcdf-c-test/libdispatch/dinfermodel.c:1120:70: error: no member named 's3' in
      'struct NC_MPI_INFO'
                                   ((NC_MPI_INFO*)file->parameters)->s3,
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
1 error generated.
```

**Comment by DennisHeimbigner** [comment]
Sorry. It was a substitution error. Inadvertently changed ->info to ->s3.
fixed by: https://github.com/Unidata/netcdf-c/pull/2137

**Comment by gsjaardema** [comment]
Thanks.
