### ISSUE TITLE
Version numbers in netcdf_meta.h seem inconsistent

### ISSUE THREAD

**Issue by czender** [Unidata/netcdf-c#214]
The numeric and string tokens give different results, 4.4.1-development and 4.4.0-development, respectively:

#define NC_VERSION_MAJOR 4 /*!< netcdf-c major version. */
#define NC_VERSION_MINOR 4 /*!< netcdf-c minor version. */
#define NC_VERSION_PATCH 1 /*!< netcdf-c patch version. */
#define NC_VERSION_NOTE  "-development" /*!< netcdf-c note. May be blank. */

/*! netcdf-c version string.
 *
 * The format of the netcdf-c version string is as follows:
 * \code
 * NC_VERSION_MAJOR.NC_VERSION_MINOR.NC_VERSION_PATCH.NC_VERSION_NOTE
 * \endcode
 * Note that the trailing NC_VERSION_NOTE may be empty. It serves for
 * identifiers such as '-rc1', etc.
 */
#define NC_VERSION       "4.4.0-development"

**Comment by WardF** [comment]
hrm. Thanks, I'll fix this!

**Comment by WardF** [comment]
Ok, taking a look at netcdf_meta.h, it is generated from netcdf_meta.h.in and *should* be populated with values inherited from either CMakeLists.txt or configure.ac.  I see now that the version is incorrect in configure.ac, correcting now.

**Comment by WardF** [comment]
Fixed!
