### ISSUE TITLE
Host path handling for S3

### ISSUE THREAD

**Issue by magnusuMET** [Unidata/netcdf-c#2151]
During some testing to get minio (S3-compatible storage) to work we encountered some issues with the host path handling in this library.

https://github.com/Unidata/netcdf-c/blob/26ac2a6cba7cc7749f1e8b2fa8e2c7bc0c3169dc/libdispatch/ds3util.c#L125 Should probably use `host` and not the default `AWSHOST`.

https://github.com/Unidata/netcdf-c/blob/26ac2a6cba7cc7749f1e8b2fa8e2c7bc0c3169dc/libdispatch/ds3util.c#L123 It should be possible to opt out of in instances where one does not use AWS

https://github.com/Unidata/netcdf-c/blob/26ac2a6cba7cc7749f1e8b2fa8e2c7bc0c3169dc/libdispatch/ds3util.c#L125 A dot is missing between the region and host if one uses a URL like 
`https://example.com/BUCKET/dataset#mode=zarr,s3&aws.region=minio`
The last one can be worked around by specifying the region as `minio.` (trailing dot), although the assumption seems to be that host will always start with a dot (e.g. AWSHOST).

**Comment by WardF** [comment]
Tagging @DennisHeimbigner but we can address these in the next release. Thanks!

**Comment by DennisHeimbigner** [comment]
We were using a local appliance supplied to us by NCAR for testing.
I switched to using S3 when a bucket became available. Looks like
I forgot to check for backward compatibility when I switched.
I will re-instate additional testing on the NCAR appliance and fix any bugs.
Hopefully that will correct your problems.

**Comment by DennisHeimbigner** [comment]
Ok, make the following change to ds3util.c and see if it fixes your problem.

1. edit libdispatch/ds3util.c
2. at line 122 change
> ncbytescat(buf,"s3.");
    ncbytescat(buf,region);
    ncbytescat(buf,AWSHOST);
    host = ncbytesextract(buf);

to
>   if(host == NULL) { /* Construct the revised host */
            ncbytescat(buf,"s3.");
            ncbytescat(buf,region);
            ncbytescat(buf,AWSHOST);
            host = ncbytesextract(buf);
    }

**Comment by magnusuMET** [comment]
Still need to prepend the region in the non-aws case, the following resolves to the correct host:
```c
/* Construct the revised host */
if (host == NULL) {
    ncbytescat(buf, "s3.");
    ncbytescat(buf, region);
    ncbytescat(buf, AWSHOST);
} else {
    ncbytescat(buf, region);
    ncbytescat(buf, ".");
    ncbytescat(buf, host);
}
host = ncbytesextract(buf);
```

**Comment by magnusuMET** [comment]
I am posting this here as it is relevant to s3 handling but could post this as a separate issue if you'd like:
There are disagreements on the signature of `NC_s3sdkfinalize`;

liblib/nc_initialize.c
51:extern int NC_s3sdkfinalize(void);

include/ncs3sdk.h
14:EXTERNL void NC_s3sdkfinalize(void);

libdispatch/ncs3sdk.cpp
80:EXTERNL void
81:NC_s3sdkfinalize(void)

**Comment by DennisHeimbigner** [comment]
There is a problem with your prepending the region to non-aws host.
This is appliance dependent. using the host without prepending the region
works fine for the NCAR appliance. I think is better for the caller to add the region
to the host than assuming the appliance will add it.

**Comment by magnusuMET** [comment]
That makes a lot of sense, the code snippet posted above by @DennisHeimbigner  works as intended when I change the host to the actual host.

**Comment by DennisHeimbigner** [comment]
Anyway, I am in the process of putting up a PR for these issues.

**Comment by DennisHeimbigner** [comment]
Fixed by PR https://github.com/Unidata/netcdf-c/pull/2152
