### ISSUE TITLE
setting deflate to zero is not the same as turning off deflate

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#2155]
Running a benchmark of different compression settings:

```
comp, level, nsd, shuffle, data wr rate (MB/s), file size (MB)
none, 0, 0, 0, 685.143, 7266.68
zlib, 0, 0, 0, 407.153, 7577.2
zlib, 1, 0, 0, 105.689, 2006.82
zlib, 2, 0, 0, 75.5917, 2333.75
zlib, 3, 0, 0, 51.7839, 2311.46
zlib, 4, 0, 0, 58.6335, 1849.85
zlib, 5, 0, 0, 39.4662, 1849.58

```

Note that the first line, with compression "none" means that nc_def_var_deflate() is not called for the variable.

The second line, with compression "zlib", level 0, calls nc_def_var_deflate() with a level of zero. Note that the output file is actually larger, and the write rate is 407 instead of 685, as it is when no compression is used.

These times are consistently showing up for me. Compression with level 0 is obviously not the same as no compression.

The problem is, Fortran programmers are just assuming 0 turns off zlib compression. But it does not seem to.

It should.

**Comment by edwardhartnett** [comment]
And as we see from ncdump, using the -s flag, the deflate is set to zero:

```
	float var_1(time, pfull, grid_yt, grid_xt) ;
		var_1:max_abs_compression_error = 42.22f ;
		var_1:nbits = 5 ;
		var_1:_Storage = "chunked" ;
		var_1:_ChunkSizes = 1, 22, 308, 615 ;
		var_1:_DeflateLevel = 0 ;
		var_1:_Endianness = "little" ;
		var_1:_NoFill = "true" ;
	float var_2(time, pfull, grid_yt, grid_xt) ;
		var_2:max_abs_compression_error = 42.22f ;
		var_2:nbits = 5 ;
		var_2:_Storage = "chunked" ;
		var_2:_ChunkSizes = 1, 22, 308, 615 ;
		var_2:_DeflateLevel = 0 ;
		var_2:_Endianness = "little" ;
		var_2:_NoFill = "true" ;


```

**Comment by edwardhartnett** [comment]
OK, I have a minor change to libhdf5/hdf5var.c which does not turn on the filter if deflate level is set to zero.

I will put up a PR shortly.

**Comment by edwardhartnett** [comment]
OK, it seems this problem would be seen in any F77 code, because it calls nc_def_var_deflate() without checking the deflate_level:

```
 Function nf_def_var_deflate( ncid, varid, shuffle, deflate, deflate_level) &
                               RESULT (status)

! define variable deflation 

 USE netcdf4_nc_interfaces

 Implicit NONE

 Integer, Intent(IN) :: ncid, varid, shuffle, deflate, deflate_level

 Integer             :: status

 Integer(C_INT) :: cncid, cvarid, cshuffle, cdeflate, cdeflate_level, &
                   cstatus

 cncid          = ncid
 cvarid         = varid-1
 cshuffle       = shuffle
 cdeflate       = deflate
 cdeflate_level = deflate_level

 cstatus = nc_def_var_deflate(cncid, cvarid, cshuffle, cdeflate, cdeflate_level) 
 status = cstatus

 End Function nf_def_var_deflate

```

But the F90 API, which most scientists are probably using, is smart enough to handle deflate_level = 0:

```
    ! Handle deflate and shuffle.
    if (present(deflate_level)) then
       if (deflate_level .gt. 0) then
          if (present(shuffle)) then
             if (shuffle) then
                nf90_def_var_oneDim = nf_def_var_deflate(ncid, varid, 1, 1, deflate_level)       
             else
                nf90_def_var_oneDim = nf_def_var_deflate(ncid, varid, 0, 1, deflate_level)       
             end if
             if (nf90_def_var_oneDim .ne. nf90_noerr) return
          end if
       end if
    endif

```

**Comment by gsjaardema** [comment]
There is some related discussion in #828 from several years ago...

**Comment by DennisHeimbigner** [comment]
The version of nc_test4/tst_vars.c I have at line about 907 has this loop:
> for (i = 0; i < NVARS5; i++)
>	 deflate_level[i] = i;

Not that the deflate level of 0 is being used and later tested at line 937.
