### ISSUE TITLE
Problem building version 4.81. with HDF5 (missing fuzz directory in 'make dist' tarball)

### ISSUE THREAD

**Issue by jbensabat** [Unidata/netcdf-c#2166]
Hello I am trying to build netcdf version 4.8.1 with HDF5 support.
First I build and checked hdf5 version 1.13.0 together with the support for ZLIB and SZIP 

I am using MSVC 2017 and CMAKE GUI.
I am getting the following error message. 

 Checking for HDF5 version 1.10.6 or later: ON
CMake Error at CMakeLists.txt:840 (MESSAGE):
  HDF5 was built without zlib.  Rebuild HDF5 with zlib.

besides the fact that I can promise that I have built the library with ZLIB, what else can I do ?
best
jac

To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
* a description of the issue with the steps needed to reproduce it

If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

**Comment by gsjaardema** [comment]
There seems to be some issue with 1.13.0 with netCDF cmake builds that the correct HDF5 library is not found and it instead finds a system-installed version.  The HDF5 team is looking into this.  Unless you need the features in the experimental 1.13.0 version of HDF5, I would suggest using HDF5-1.12.1 or previous

**Comment by WardF** [comment]
It is sadly unsurprising that 1.13 isn't being picked up properly, the mechanisms for detecting seem to change between major versions. I'm at AGU this week but will take a look and see what needs to be done so that we might push out a quick release to correct this.

**Comment by gsjaardema** [comment]
HDF5 team is looking at this and I will forward any issue numbers or resolution steps once they have any...

**Comment by jbensabat** [comment]
Hi
Thank you very much for your support 
I did more or less , intuitively , what you suggested before I read your messages then I got the following error
the directory fuzz is missing 
i created a fuzz directory then I got the error that there is no CMakelist.txt file there 
I just replace the 1.13 version with the previous one 
best
jac

**Comment by jbensabat** [comment]
Hello 
I am now using version 1.12 of HDF5 but I get an error about a missing fuzz directory (same error msg as for version 1.13 of HDF5)
here are the diags from CMAKE

Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19044.
Found HDF5 libraries version 1.12.1
Using HDF5 include dir: C:/wrf_hydro/hdf/build/_CPack_Packages/win64/ZIP/HDF5-1.12.1-win64/include;
HDF5 has szip.
-- Checking for HDF5 version 1.10.6 or later: ON
Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
Enabling use of fill value when NC_ERANGE
Enabling a more relaxed check for NC_EINVALCOORDS
CMake Warning at CMakeLists.txt:1599 (MESSAGE):
  mmap not supported under visual studio: disabling MMAP support.


Found m4: C:/Flex Windows/Bison/bin/m4.exe
Ignoring C:/Windows/System32/bash.exe
CMAKE_SOURCE_DIR=C:/wrf_hydro/netcdf/netcdf-c-4.8.1
CMAKE_BINARY_DIR=C:/wrf_hydro/netcdf/netcdf-c-4.8.1/build
CMAKE_CURRENT_SOURCE_DIR=C:/wrf_hydro/netcdf/netcdf-c-4.8.1/nc_test
CMAKE_CURRENT_BINARY_DIR=C:/wrf_hydro/netcdf/netcdf-c-4.8.1/build/nc_test


Configuration Summary:

Building Shared Libraries:     ON
Building netCDF-4:             ON
Building DAP2 Support:         OFF
Building DAP4 Support:         OFF
Building Byte-range Support:   OFF
Building Utilities:            ON

Tests Enabled:              ON
DAP Remote Tests:  ON
Extra Tests:       OFF
Coverage Tests:    
Parallel Tests:    OFF
Large File Tests:  
Extreme Numbers:   ON
Unit Tests:        OFF

Compiler:

Build Type:           DEBUG
CMAKE_C_COMPILER:     C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
CMAKE_C_FLAGS:        /DWIN32 /D_WINDOWS /W3
CMAKE_C_FLAGS_DEBUG:  /MDd /Zi /Ob0 /Od /RTC1
Linking against:      hdf5::hdf5-shared;hdf5::hdf5_hl-shared;C:/wrf_hydro/bin/Debug/libsz_D.lib

# NetCDF C Configuration Summary
==============================

# General
-------
NetCDF Version:		4.8.1
Dispatch Version:       3
Configured On:		
Host System:		--
Build Directory: 	C:/wrf_hydro/netcdf/netcdf-c-4.8.1/build
Install Prefix:         C:/Program Files/netCDF

# Compiling Options
-----------------
C Compiler:		C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
CFLAGS:			/DWIN32 /D_WINDOWS /W3 /MDd /Zi /Ob0 /Od /RTC1
CPPFLAGS:		 
LDFLAGS:		/machine:x64 /LARGEADDRESSAWARE /STACK:40000000 /debug /INCREMENTAL
AM_CFLAGS:		
AM_CPPFLAGS:		
AM_LDFLAGS:		
Shared Library:		yes
Static Library:		no
Extra libraries:	-lhdf5 -lhdf5_hl -lsz_D

# Features
--------
NetCDF-2 API:		yes
HDF4 Support:		no
HDF5 Support:		yes
NetCDF-4 API:		yes
NC-4 Parallel Support:	no
PnetCDF Support:	no
DAP2 Support:		no
DAP4 Support:		no
Byte-Range Support:	no
Diskless Support:	yes
MMap Support:		no
JNA Support:		no
CDF5 Support:		yes
ERANGE Fill Support:	yes
Relaxed Boundary Check:	yes
SZIP Support:           yes
SZIP Write Support:     yes
Parallel Filters:       yes
NCZarr Support:		no
Multi-Filter Support:	no

CMake Error at CMakeLists.txt:2257 (add_subdirectory):
  add_subdirectory given source "fuzz" which is not an existing directory.


Configuring incomplete, errors occurred!
See also "C:/wrf_hydro/netcdf/netcdf-c-4.8.1/build/CMakeFiles/CMakeOutput.log".
See also "C:/wrf_hydro/netcdf/netcdf-c-4.8.1/build/CMakeFiles/CMakeError.log".

thanks 
jac

**Comment by DennisHeimbigner** [comment]
This was added in PR https://github.com/Unidata/netcdf-c/pull/1972

I do not understand how the fuzz directory got removed; it exists in the github master
and the netcdf-c 4.8.1 release file.
In any case, you have two solutions:
1. remove the line "add_subdirectory(fuzz)" from CMakeLists.txt
2. or recopy the fuzz directory from the github master or the netcdf 4.8.1 release.

**Comment by jbensabat** [comment]
thanks 
jac

**Comment by johnomotani** [comment]
@DennisHeimbigner The source release tarball here https://downloads.unidata.ucar.edu/netcdf-c/4.8.1/src/netcdf-c-4.8.1.tar.gz does not contain any file or directory named `fuzz`. The tarball on the github.com release page https://github.com/Unidata/netcdf-c/archive/refs/tags/v4.8.1.tar.gz does though. I guess the unidata site version is broken?

**Comment by WardF** [comment]
The github tarball is generated automatically.  @DennisHeimbigner the tarballs we create manually are generated by 'make dist'; I don't see any autotools-based infrastructure for including the fuzz directory in the tarball.  I'll add that.
