### ISSUE TITLE
netCDF3 + pnetcdf fails to compile

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#217]
Whilst testing an MPI environment using mpich (openmpi is the same I assume, will check later), `make` fails with:

`````
/home/mpiuser/netcdf-c/libsrcp/ncpdispatch.c:1176:23: error: ‘NC_INDEPENDENT’ undeclared (first use in this function)
     if (par_access != NC_INDEPENDENT && par_access != NC_COLLECTIVE)
`````

This is a `cmake` based build, configured thusly:

    $ cmake .. -DENABLE_PNETCDF=ON -DENABLE_NETCDF_4=OFF -DENABLE_PARALLEL=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_COMPILER=$(which mpicc)

I have not tested autotools yet.

At a glance, it appears that `netcdf_par.h` is not being properly included.  I infer the problem is somewhere in the configuration system.

**Comment by WardF** [comment]
This does not appear to be a problem when building with `configure`, e.g.

    $ autoreconf -if
    $ CC=$(which mpicc) CFLAGS="-I/home/mpiuser/usr/include" LDFLAGS="-L/home/mpiuser/usr/include" ./configure --disable-netcdf-4 --enable-parallel --enable-pnetcdf --disable-shared --enable-static

**Comment by gsjaardema** [comment]
Does your config.h generated in the cmake build define USE_PARALLEL?

**Comment by WardF** [comment]
I'm  guessing not, but I've had to send us aside for a little bit while I go to a meeting. The symptoms indicate leading missing pound define in C make lists is the most likely culprit.

**Comment by gsjaardema** [comment]
It works fine on my mac...
[config.h.txt](https://github.com/Unidata/netcdf-c/files/125449/config.h.txt)

**Comment by WardF** [comment]
Very strange.  I can duplicate the issue readily in a linux VM (ubuntu trusty 64-bit), will continue to diagnose.

**Comment by DennisHeimbigner** [comment]
I agree, the probable problem is that USE_PARALLEL is not being defined.
It appears that the code in CMakeLists.txt does not follow that of configure.ac,
specifically, USE_PARALLEL is set if enable_parallel is set, and enable_parallel is set
(in configure.ac) by  this code:
# Now, set enable_parallel if either pnetcdf or parallel4 is set
if test "x$enable_pnetcdf" = xyes -o "x$enable_parallel4" = xyes; then
enable_parallel=yes
else
enable_parallel=no
fi

**Comment by WardF** [comment]
Thanks Dennis; out of meeting now, this should be a really easy fix.

**Comment by WardF** [comment]
The fix is in, but I am refactoring the parallel logic in CMakeLists.txt to make it a bit more clear; there's a lot of duplication, and it's spread out over several different sections.
