### ISSUE TITLE
Segmentation fault (core dump) using nc_get_vara or nc_get_vara_float in netcdf 4.8.1

### ISSUE THREAD

**Issue by wreckdump** [Unidata/netcdf-c#2175]
When I call `nc_get_vara` or `nc_get_vara_float` with a pointer object declared with stack array (ex: `float var[100];`), I get `segmentation fault (core dump)` error without any extra error messages.  But when I declare the pointer object using dynamic array (ex: `float *var = malloc(100 * sizeof(float);`) it works without any problem. Yet, running the very same code with lower netcdf-c version (< 4.8.1, so far tested with 4.1.1 and 4.7.1) it works fine.

I have no clue why this happens. The example code, (`pres_temp_4D_rd.c`) which uses static array for the pointer object for `nc_get_vara_float`, from the netCDF website works without any problem under the version 4.8.1.. Below is the minimal code to reproduce the problem.

```
#include <stdio.h>
#include <netcdf.h>

#define nx 3024
#define ny 1100
#define nt 2

// variable
#define t_nm "time"
#define y_nm "lat"
#define x_nm "lon"
#define tb_nm "Tb"

#define nc_err(err_code) {printf("Error: %s\n", nc_strerror(err_code)); return 2;}

int main(int argc, char *argv[])
{
char   in_file_nm[200] = "sample_data.nc";

int      ec, in_ncid, in_var_id, in_x_id, in_y_id, in_t_id;


size_t   in_start[3] = {0,0,0}, 
         in_count[3] = {1,ny,nx};

float    t_in[nt],
         x_in[nx],
         y_in[ny],
         in_var[nx * ny];

int      t_idx,i,j;


// open and create netcdf
if ((ec = nc_open(in_file_nm, NC_NOWRITE, &in_ncid))) nc_err(ec);

// inquiry data from input netcdf file
if ((ec = nc_inq_varid(in_ncid, t_nm      , &in_t_id  ))) nc_err(ec);
if ((ec = nc_inq_varid(in_ncid, y_nm      , &in_y_id  ))) nc_err(ec);
if ((ec = nc_inq_varid(in_ncid, x_nm      , &in_x_id  ))) nc_err(ec);
if ((ec = nc_inq_varid(in_ncid, tb_nm     , &in_var_id))) nc_err(ec);

// read dimensional variables from the input netcdf file
if ((ec = nc_get_var_float(in_ncid, in_t_id, &t_in[0]))) nc_err(ec);
if ((ec = nc_get_var_float(in_ncid, in_y_id, &y_in[0]))) nc_err(ec);
if ((ec = nc_get_var_float(in_ncid, in_x_id, &x_in[0]))) nc_err(ec);

// for each time step of variable
for (t_idx=0;t_idx<2;t_idx++)
{
   printf("time step : %d \n",t_idx);
   in_start[0] = t_idx;
   if ((ec = nc_get_vara_float(in_ncid, in_var_id, in_start, in_count, &in_var[0]))) nc_err(ec);
}

printf(". . . done for NCEP CPC 4 km %s %s\n\n",argv[1],argv[2]);


//// now we are done, lets close the netcdf files
if ((ec = nc_close(in_ncid) )) nc_err(ec);

return 0;
}
```

And here is the example netcdf file to work with the above code : [link](https://file.io/M09UkEnucoWs)

**Comment by DennisHeimbigner** [comment]
Can you repost the .nc file?

**Comment by wreckdump** [comment]
sure. here.
[link](https://file.io/7CdOUgXR3E0K)

**Comment by DennisHeimbigner** [comment]
The problem I am encountering is that this declaration:
         in_var[nx * ny];
causes a fault; presumably it is too large for stack allocation.
If I make it static, then everything seems to work ok.

**Comment by wreckdump** [comment]
Ahh!!! Thank you so much!! I kinda had a hunch but I could not just find it out!

I've tried the exact same code in different machines, on some clusters that I have an access to. The code works on those machines. So, I am suspecting that they have set the memory stack size larger than that of my machine?

**Comment by DennisHeimbigner** [comment]
You might check out the limit (ulimit) man page and the -s flag.
It can tell or set the stack size.

**Comment by wreckdump** [comment]
It works!! Wonder why I have not thought of this earlier! Thank you so much!

**Comment by DennisHeimbigner** [comment]
Glad to help.
