### ISSUE TITLE
where is configure?

### ISSUE THREAD

**Issue by simon-Leary42** [Unidata/netcdf-c#2185]
The docs say to download source code and then ./configure, but it doesn't exist
I try automake and it throws a million errors (see link) and there's still no configure
https://pastebin.com/tHMNkPFK

**Comment by WardF** [comment]
You can download a release tarball or zip file, which contains the configure script, from https://github.com/Unidata/netcdf-c/releases . If you download the development branch (which I don't recommend, unless you know for sure that's what you want!), you can run autoreconf -if. This will, if you have the appropriate packages installed on your system, generate the configure script. I suspect you will want to use the tarball or zip file for an official release, however.

**Comment by simon-Leary42** [comment]
Thanks! You're right, I don't want the development branch.
