### ISSUE TITLE
Many function in netcdf.h do not appear to be in the documentation..

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#2186]
I was looking at the generated documentation and noticed that a number of functions in the netcdf.h
API do not appear -- or are misplaced -- in the documentation. Example nc-_set_chunk_cache.

**Comment by edwardhartnett** [comment]
OK, turns out that nc4cache.c was not in the list of input files in Doxyfile.in. I will submit a PR shortly.

@DennisHeimbigner any other functions other than the cache functions?
