### ISSUE TITLE
Lost NOUNDEFINED

### ISSUE THREAD

**Issue by matzeri** [Unidata/netcdf-c#2196]
long time ago NOUNDEFINED was added to configure.ac and to the libnetcdf_la_LDFLAGS
to allow shared libs on Cygwin and other platforms

from version 4.5.0 the NOUNDEFINED  was lost in the Makefile.am
and I am adding every time for the Cygwin package.
I will appreciate to be reinstated.

```
--- origsrc/netcdf-c-4.8.0/liblib/Makefile.am   2019-02-28 21:40:34.000000000 +0100
+++ liblib/Makefile.am  2019-03-17 19:01:38.173060600 +0100
@@ -18,7 +18,7 @@
 # for information regarding incrementing `-version-info`.
 ##

-libnetcdf_la_LDFLAGS = -version-info 19:1:0
+libnetcdf_la_LDFLAGS = -version-info 19:1:0 ${NOUNDEFINED}

 libnetcdf_la_CPPFLAGS = ${AM_CPPFLAGS}
 libnetcdf_la_LIBADD =

```

**Comment by WardF** [comment]
Thanks @matzeri, this appears to have been an accident, I've created a PR to correct it, #2205.
