### ISSUE TITLE
Memory leak in Windows when building netcdf with hdf5 1.10.8

### ISSUE THREAD

**Issue by abhibaruah** [Unidata/netcdf-c#2203]
NetCDF version: 4.8.1
HDF5 version: 1.10.8
OS: Windows 10

I am a developer at The MathWorks Inc. For MATLAB, we were building netcdf with hdf5-1.8.12.
However, we are trying to change netcdf's dependency on hdf5 to v1.10.8.

I built netcdf successfully with hdf5 1.10.8. However, while qualifying, I see that there is a memory leak in Windows when netcdf is built with hdf5 1.10.8. The leak is seen only in Windows, and I did not see it in Linux or MacOS.

I was able to resolve the leak by modifying the definition of the function 
```
static int
ansi2utf8(const char* local, char** u8p)
```
in netcdf\libdispatch\dpathmgr.c

`wchar_t* u16`
is not being freed, which leads to this leak in Windows.
I was able to resolve this by adding `nullfree(u16)` before the return statement in `ansi2utf8`.

The issue can be reproduced by simply opening and closing a netcdf4 file, and running a leak detector in Windows.

```
# include <stdio.h>
# include <netcdf.h>

#define FILE "demo_example.nc"


int main(int argc, char *argv[])
{
    int ncid, retval;
    retval = nc_open(FILE, NC_NOWRITE, &ncid);
    printf("NCID = %d\n", ncid);
    retval = nc_close(ncid);
    printf("Retval = %d\n", retval);
    return 0;
}
```

**Comment by WardF** [comment]
Thank you, this will be an easy fix to incorporate!
