### ISSUE TITLE
Does HDF5 have to be compiled with same compiler as netcdf?

### ISSUE THREAD

**Issue by simon-Leary42** [Unidata/netcdf-c#2230]
The question is self explanatory.
HDF5 is failing to build for me with intel, I was wondering if I could use GNU and still use intel for netcdf.

**Comment by WardF** [comment]
Typically, the compatibility is determined by 'configure', insofar  as it tries to link a test program against the detected libhdf5; if the compiler has not produced a compatible binary, the configure script will fail to compile the test program linked against the target library, and configure will complain about not being able to find a compatible libhdf5.

**Comment by edwardhartnett** [comment]
I think a better question is: why does HDF5 not compile on intel?

I compile HDF5 on intel all the time, without problems, including the 1.10.x series and the 1.12.x series.

So what exactly is the problem building HDF5? Have you requested help in the HDF5 support mailing list?

**Comment by edwardhartnett** [comment]
Can this issue be closed? It does not seem to be a netcdf issue...
