### ISSUE TITLE
NCZarr fill_value is Nan instead of NaN on Windows

### ISSUE THREAD

**Issue by malmans2** [Unidata/netcdf-c#2265]
In [this xarray's PR](https://github.com/pydata/xarray/pull/6420) I found out that I'm having issues reading with python NCZarr data created on Windows.
Looks like the issue has to do with fill_value, which is Nan instead of NaN, and therefore can't be properly parsed by python's `json`.

Sorry, I don't have much more details as I don't have a Windows machine to explore this a bit better. I thought I would open an issue here in case you already have some ideas about what's causing the problem. I guess it's possible that the problem is actually related to `netcdf4-python` as I'm using it to create the NCZarr file.

<details><summary>This is the Python code I'm using to create the NCZarr data</summary>

```python
from xarray.tests.test_dataset import create_test_data
ds = create_test_data()
ds = ds.drop_vars("dim3")
ds.to_netcdf("file://test_data.zarr#mode=nczarr")
```
</details>

**Comment by DennisHeimbigner** [comment]
Looks like a typo on my part.
You should be able to fix as follows:

1. edit the file netcdf-c/libnczarr/zcvt.c
2. Near line 308 you should see this line: ````strcpy(s,"Nan"); break;````
3. Change to this: ````strcpy(s,"NaN"); break;````
 
I will submit a PR for this after I hear if it fixes the problem.

**Comment by malmans2** [comment]
I don't have an easy way to test that change on Windows.

However, I replaced myself all `Nan` in `.zattrs` and `.zarray` with `NaN`, and I can confirm that I'm able to correctly read the data. Therefore, I'm pretty sure that changing `strcpy(s,"Nan")` to `strcpy(s,"NaN")` will fix the problem and I suggest to go ahead with the PR.

**Comment by DennisHeimbigner** [comment]
See PR https://github.com/Unidata/netcdf-c/pull/2267
