### ISSUE TITLE
Inconsistent output from nf-config

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#2276]
For `nc-config` and most `nf-config` output the output is `yes` or `no` however for the `--has-f90`, it is `TRUE`.   Should this be `yes` also, or is there a reason that it needs to be `TRUE`.

Doesn't really affect me, but when it started showing up in the `nc-config` output, it stood out as an inconsistency that may indicate an issue somewhere...

**Comment by WardF** [comment]
Thank you, they should be consistent, I will take a look in preparation for the next release.

**Comment by edwardhartnett** [comment]
OK, this issue should probably be in netcdf-fortran. ;-)

**Comment by gsjaardema** [comment]
That works for me.  Thanks.
