### ISSUE TITLE
Configuration not finding ncmpi_create

### ISSUE THREAD

**Issue by coderodyhpc** [Unidata/netcdf-c#2317]
Hello,
I've been trying to compile netcdf-c with pnetcdf support but the configuration (`./configure --prefix=/opt/netcdfP --enable-pnetcdf --disable--static --enable-shared`) keeps producing the error:
```
...
checking whether parallel io is enabled in hdf5... yes
checking for library containing H5Dread_chunk... none required
checking for library containing H5Pset_fapl_ros3... no
checking whether HDF5 allows parallel filters... yes
checking whether szlib was used when building HDF5... no
checking whether HDF5 library is version 1.10.6 or later... yes
checking whether parallel I/O is enabled for netcdf-4... yes
checking for ncmpi_create in -lpnetcdf... no
configure: error: Cannot link to PnetCDF library.
```
I've tried about a dozen different permutations (building static, shared or both libraries, using the Github repository or the stable version, with or without netcdf4 support) but it's always the same error. The weird thing is that the library seems to have the component causing the issue:
```
$ nm libpnetcdf.so.4.0.3 | grep ncmpi_create
000000000006b52c T ncmpi_create
```
I'm missing something here but not sure what is it. Thanks.   
P.S. OS is Ubuntu20.04

**Comment by wkliao** [comment]
try adding the followings to your configure command line
```
      CC=mpicc \
      CPPFLAGS="-I$PNETCDF_DIR/include -I$HDF5_DIR/include" \
      LDFLAGS="-L$PNETCDF_DIR/lib -L$HDF5_DIR/lib" \
```

**Comment by coderodyhpc** [comment]
Hi @**wkliao**, 
It was a matter of explicitly declaring the path to the PnetCDF libraries and headers (I had already defined CC -even if I didn't mention in my original post- and the paths to HDF5 are pretty standard).
Thanks.

**Comment by edwardhartnett** [comment]
Look in the file config.log to see what error is happening...
