### ISSUE TITLE
zstandard functions do not appear in the documentation (nor do any of the filter functions in dfilter.c)

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#2333]
zstandard functions do not appear in the documentation.

I will submit PR shortly...

**Comment by DennisHeimbigner** [comment]
Please examine PR https://github.com/Unidata/netcdf-c/pull/2249

**Comment by edwardhartnett** [comment]
@DennisHeimbigner I've looked at #2249 - what am I looking for?

Unless I'm mistaken I don't think it includes the doxygen documentation for the zstandard functions.

**Comment by DennisHeimbigner** [comment]
No, but some of the text there might be useful.

**Comment by edwardhartnett** [comment]
It's OK, I've got complete documentation already in the CCR project, I just stole it. ;-)

I added documentation for filter functions that didn't have any.

I have also just added netcdf_filter.h to the doxygen build - previously it was not there.

Once all these PRs are merged I can do another pass to get rid of new doxygen warnings.

**Comment by DennisHeimbigner** [comment]
ok, sounds good.
