### ISSUE TITLE
make distcheck fails on master...

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#2338]
```
make[3]: Entering directory '/home/ed/n3/nc_test'
make  distdir-am
make[4]: Entering directory '/home/ed/n3/nc_test'
make[4]: *** No rule to make target 'run_pnetcdf_test.sh', needed by 'distdir-am'.  Stop.
make[4]: Leaving directory '/home/ed/n3/nc_test'
make[3]: *** [Makefile:1715: distdir] Error 2
make[3]: Leaving directory '/home/ed/n3/nc_test'
make[2]: *** [Makefile:863: distdir-am] Error 1
make[2]: Leaving directory '/home/ed/n3'
make[1]: *** [Makefile:857: distdir] Error 2
make[1]: Leaving directory '/home/ed/n3'
make: *** [Makefile:958: dist] Error 2
```

I will take a look...

**Comment by edwardhartnett** [comment]
OK, I've fixed that problem, but here's the next one:

```
make[4]: Leaving directory '/home/ed/n3/netcdf-c-4.8.2-development/_build/sub/nczarr_test'
make  check-TESTS
make[4]: Entering directory '/home/ed/n3/netcdf-c-4.8.2-development/_build/sub/nczarr_test'
make[5]: Entering directory '/home/ed/n3/netcdf-c-4.8.2-development/_build/sub/nczarr_test'
make[5]: *** No rule to make target 'run_nczfilter.sh', needed by 'run_nczfilter.sh.log'.  Stop.
make[5]: *** Waiting for unfinished jobs....
PASS: run_interop.sh
PASS: run_ut_misc.sh
PASS: run_ut_chunk.sh
PASS: run_quantize.sh
PASS: run_fillonlyz.sh
PASS: run_misc.sh
PASS: run_purezarr.sh
PASS: run_ut_mapapi.sh
PASS: run_nczarr_fill.sh
PASS: run_ncgen4.sh
PASS: run_ut_map.sh
PASS: run_chunkcases.sh
make[5]: Leaving directory '/home/ed/n3/netcdf-c-4.8.2-development/_build/sub/nczarr_test'
make[4]: *** [Makefile:1327: check-TESTS] Error 2
make[4]: Leaving directory '/home/ed/n3/netcdf-c-4.8.2-development/_build/sub/nczarr_test'
make[3]: *** [Makefile:1520: check-am] Error 2
make[3]: Leaving directory '/home/ed/n3/netcdf-c-4.8.2-development/_build/sub/nczarr_test'
make[2]: *** [Makefile:1522: check] Error 2
make[2]: Leaving directory '/home/ed/n3/netcdf-c-4.8.2-development/_build/sub/nczarr_test'
make[1]: *** [Makefile:752: check-recursive] Error 1
make[1]: Leaving directory '/home/ed/n3/netcdf-c-4.8.2-development/_build/sub'
make: *** [Makefile:970: distcheck] Error 1

```

**Comment by edwardhartnett** [comment]
OK, I've got it working. PR shortly...

**Comment by edwardhartnett** [comment]
Also:

```
echo '#define NOOP_INSTANCE 1' > H5Znoop1.c
cat ./H5Znoop.c >> H5Znoop1.c
make  distdir-am
make[4]: Entering directory '/home/ed/n3/plugins'
make[4]: *** No rule to make target 'stdinstall.sh', needed by 'distdir-am'.  Stop.
make[4]: Leaving directory '/home/ed/n3/plugins'
make[3]: *** [Makefile:863: distdir] Error 2
make[3]: Leaving directory '/home/ed/n3/plugins'
make[2]: *** [Makefile:865: distdir-am] Error 1
make[2]: Leaving directory '/home/ed/n3'
make[1]: *** [Makefile:859: distdir] Error 2
make[1]: Leaving directory '/home/ed/n3'
make: *** [Makefile:960: dist] Error 2
ed@mikado:~/n3$ 
```

**Comment by edwardhartnett** [comment]
OK, I have fixed all the missing file problems in the Makefile.am files. However, now I'm left with this more difficult issue:

```
ed@mikado:~/n3/netcdf-c-4.8.2-development/nczarr_test$ bash -x ./run_filter.sh
+ test x = x
++ pwd
+ srcdir=/home/ed/n3/netcdf-c-4.8.2-development/nczarr_test
+ . ../test_common.sh
./run_filter.sh: line 4: ../test_common.sh: No such file or directory
+ . /home/ed/n3/netcdf-c-4.8.2-development/nczarr_test/test_nczarr.sh
++ test x '!=' x
++ test x = x
++ export NCZARR_S3_TEST_HOST=s3.us-east-1.amazonaws.com
++ NCZARR_S3_TEST_HOST=s3.us-east-1.amazonaws.com
++ test x = x
++ export NCZARR_S3_TEST_BUCKET=unidata-zarr-test-data
++ NCZARR_S3_TEST_BUCKET=unidata-zarr-test-data
++ export NCZARR_S3_TEST_URL=https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data
++ NCZARR_S3_TEST_URL=https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data
++ ZMD=/zmapio
+++ pwd
++ WD=/home/ed/n3/netcdf-c-4.8.2-development/nczarr_test
++ cd /home/ed/n3/netcdf-c-4.8.2-development/nczarr_test
+++ pwd
++ abs_srcdir=/home/ed/n3/netcdf-c-4.8.2-development/nczarr_test
++ cd /home/ed/n3/netcdf-c-4.8.2-development/nczarr_test
++ cd
+++ pwd
++ abs_execdir=/home/ed
++ cd /home/ed/n3/netcdf-c-4.8.2-development/nczarr_test
+++ pwd
++ WD=/home/ed/n3/netcdf-c-4.8.2-development/nczarr_test
++ test x '!=' x
++ test x = xyes
++ resetrc
++ test x = x1
++ rm -f /home/ed/n3/netcdf-c-4.8.2-development/nczarr_test/.dodsrc /home/ed/n3/netcdf-c-4.8.2-development/nczarr_test/.daprc /home/ed/n3/netcdf-c-4.8.2-development/nczarr_test/.ncrc
++ unset NCRCENV_IGNORE
++ unset NCRCENV_RC
++ unset DAPRCFILE
+ set -e
+ findplugin h5misc
./run_filter.sh: line 53: findplugin: command not found
ed@mikado:~/n3/netcdf-c-4.8.2-development/nczarr_test$ ls
```

I am going to put up a PR with all the Makefile.am changes, while I work on this issue...

**Comment by edwardhartnett** [comment]
@DennisHeimbigner I think the issue here is the way you are installing the plugins with your own script.

In the CCR project, I install them without a script with some automake magic. Here's the example from the zstd plugin:

```
# This is where HDF5 wants us to install plugins
plugindir = @HDF5_PLUGIN_PATH@

# This linker flag specifies libtool version info.
# See http://www.gnu.org/software/libtool/manual/libtool.html#Libtool-versioning
# for information regarding incrementing `-version-info`.
libh5zstd_la_LDFLAGS = -version-info 0:0:0

# The libh5zstd library for plugin module
# Build it as shared library
plugin_LTLIBRARIES = libh5zstd.la
libh5zstd_la_SOURCES = H5Zzstandard.c

```

This builds and installs the plugin in the HDF5_PLUGIN_DIR, which is set by configure, but defaults to the HDF5 default. No install script needed.

**Comment by DennisHeimbigner** [comment]
I am surprised; I thought we did a distcheck under our github actions. Guess not.

**Comment by DennisHeimbigner** [comment]
Now you have my back up. I refuse to to an auto-install in HDF5_PLUGIN_DIR.
So I strongly recommend this PR not be accepted.

**Comment by edwardhartnett** [comment]
Hmmm? Why the reluctance to install the HDF5 plugins?

It doesn't auto-install - the user has to do a "make install".

Without that, zstandard will not work. ;-)

**Comment by edwardhartnett** [comment]
For example, I just tried adding this test code, and it fails with current master:

```
#ifdef HAVE_ZSTD
#define ZSTANDARD_LEVEL 10
    printf("**** testing zstandard filter...");
    {
        int varid, ncid, dims[NDIM2];
        int level_in, hasfilter;
	int ret;

        if (nc_create(FILE_NAME, NC_NETCDF4 | NC_CLOBBER, &ncid)) ERR;
        if (nc_def_dim(ncid, X_NAME, XDIM_LEN, &dims[0])) ERR;
        if (nc_def_dim(ncid, Y_NAME, YDIM_LEN, &dims[1])) ERR;
        if (nc_def_var(ncid, VAR_NAME, NC_FLOAT, 2, dims, &varid)) ERR;
        if ((ret = nc_def_var_zstandard(ncid, varid, ZSTANDARD_LEVEL)))
	{
	    printf("netcdf error: %s\n", nc_strerror(ret));
	    ERR;
	}
        if (nc_inq_var_zstandard(ncid, varid, &hasfilter, &level_in)) ERR;
	if (!hasfilter || level_in != ZSTANDARD_LEVEL) ERR;
        if (nc_close(ncid)) ERR;

        /* Open the file and check. */
        if (nc_open(FILE_NAME, NC_WRITE, &ncid)) ERR;
        if (nc_inq_var_zstandard(ncid, varid, &hasfilter, &level_in)) ERR;
	if (!hasfilter || level_in != ZSTANDARD_LEVEL) ERR;
        if (nc_close(ncid)) ERR;
    }
    SUMMARIZE_ERR;
#endif  /* HAVE_ZSTD */

```

It fails with ` Filter error: undefined filter encountered`, because the zstandard filter has been built but not installed.

It does not benefit netCDF users if they can't turn on the feature. Have `make install` do all the installing that is needed to make everything work. That is what users expect.

If we demand a second step, where they have to manually install the plugins, we will generate a lot of support questions and user confusion. What is the benefit of that? The plugin directory is there so that plugins can be installed into it. That's how HDF5 intends us to use plugins. So why the reluctance?

**Comment by DennisHeimbigner** [comment]
I took your PR https://github.com/Unidata/netcdf-c/pull/2342 and did some corrections on it.
You exposed some naming problems in nczarr_test and in plugins directories that I fixed.
I also took your suggestion for an alternate plugin install mechanism and applied it;
stdinstall.sh is no longer needed. Thanks.
Anyway, I will post my PR tomorrow; you can either merge it back to yours
or use mine.

**Comment by DennisHeimbigner** [comment]
I had not planned to default to HDF5_PLUGIN_PATH, but since it seems important to you,
I will do it. It will require me to parse HDF5_PLUGIN_PATH, so I need a decision by you.
Suppose HDF5_PLUGIN_PATH looks like this:
> HDF5_PLUGIN_PATH="dir1:dir2:dir3"

Do I install into dir1, dir2, or dir3?

**Comment by edwardhartnett** [comment]
dir1.

Here is how I check for it in configure.ac:

```
AC_MSG_CHECKING([where to put HDF5 plugins])
HDF5_PLUGIN_PATH=${HDF5_PLUGIN_PATH-'/usr/local/hdf5/lib/plugin'}
AC_ARG_WITH([hdf5-plugin-path],
            [AS_HELP_STRING([--with-hdf5-plugin-path=<directory>],
                            [specify HDF5 plugin path (defaults to /usr/local/hdf5/lib/plugin, or value of HDF5_PLUGIN_PATH, if set)])],
            [HDF5_PLUGIN_PATH=$with_hdf5_plugin_path])
AC_MSG_RESULT($HDF5_PLUGIN_PATH)
AC_SUBST([HDF5_PLUGIN_PATH])
```


In addition to using HDF5_PLUGIN_PATH, you need to default to /usr/local/hdf5/lib/plugin if it is not set. (I don't know what the Windows equivalent is). 

Most users will not have HDF5_PLUGIN_PATH set. So we need to use HDF5's default location, because that will allow zstandard to work for netcdf-c out of the box.

Most people will not

**Comment by DennisHeimbigner** [comment]
This won't work if NCZarr is enabled but HDF5 is not.

**Comment by edwardhartnett** [comment]
Yes, the HDF5_PLUGIN_PATH can be completely ignored in that case.

**Comment by DennisHeimbigner** [comment]
Why? NCZarr uses it too.

**Comment by edwardhartnett** [comment]
OK, sorry I didn't know. In any case, when HDF5 is not built, then no need to worry about the HDF5 default path for plugins.

When asking you to support the HDF5 default, I am thinking of NOAA or other HPC systems, where they are going to be producing large netCDF/HDF5 datasets, and will want to use zstandard (as they want to do at NOAA). 

Having zstandard and HDF5 work together out of the box is very important for scientists who are good at science but not very skilled at installing software. Even advanced users are probably not using any HDF5 filters yet, so they will have no concept of where they should be installed. They should not be expected to know anything about plugin paths.

When NOAA starts releasing data with zstandard, we want the community to be able to easily read those files, without having to submit a netcdf support issue, or figure out how to use HDF5 plugins. Instead, it should just quietly work in the default case.

The vast majority of users will not care about plugin paths, and will assume that netcdf is going to install itself in the correct place(s) for everything to work.

**Comment by DennisHeimbigner** [comment]
Side note. Apparently in HDF5 version 1.13, it will be possible to programmatically
modify the value of HDF5_PLUGIN_PATH.
See here: https://docs.hdfgroup.org/hdf5/develop/group___h5_p_l.html#title3
and look at the list on the left side.

**Comment by edwardhartnett** [comment]
That will be handy. For testing, what we will have to do is run tests in a script, which sets the HDF5_PLUGIN_PATH and then runs the test. That way, the test can be run before make install.

Here's an example:
```
# This script runs the tests in the CCR project.
#
# Ed Hartnett 11/18/20
set -x
set -e

# If bitgroom was built, run the bitgroom test. Run this first, so
# that the bitgroom filter can be found by other tests.
if test "@BUILD_BITGROOM@" = "yes"; then
    export HDF5_PLUGIN_PATH="../hdf5_plugins/BITGROOM/src/.libs:$HDF5_PLUGIN_PATH"
    ./tst_bitgroom
fi

# If bzip2 was built, run the bzip2 test.
if test "@BUILD_BZIP2@" = "yes"; then
    export HDF5_PLUGIN_PATH="../hdf5_plugins/BZIP2/src/.libs:$HDF5_PLUGIN_PATH"
    ./tst_bzip2
fi

# If lz4 was built, run the lz4 test.
#if test "@BUILD_LZ4@" = "yes"; then
#    export HDF5_PLUGIN_PATH="../hdf5_plugins/LZ4/src/.libs:$HDF5_PLUGIN_PATH"
#    ./tst_lz4
#fi

# If zstandard was built, run the zstandard test. This must come after
# the bitgroom test.
if test "@BUILD_ZSTD@" = "yes"; then
    export HDF5_PLUGIN_PATH="../hdf5_plugins/ZSTANDARD/src/.libs:$HDF5_PLUGIN_PATH"
    ./tst_zstandard
fi

# Always run the performance test.
./tst_perf

```

**Comment by DennisHeimbigner** [comment]
Yes, although some filter tests are a bit more complex. There is already code
to locate the plugins before installation.

**Comment by edwardhartnett** [comment]
make distcheck is still failing on the current main branch:

```
make[4]: Entering directory '/home/ed/netcdf-c/netcdf-c-4.8.2-development/_build/sub/plugins'
make  distdir-am
make[5]: Entering directory '/home/ed/netcdf-c/netcdf-c-4.8.2-development/_build/sub/plugins'
make[5]: *** No rule to make target 'BZIP2_LICENSE', needed by 'distdir-am'.  Stop.
make[5]: Leaving directory '/home/ed/netcdf-c/netcdf-c-4.8.2-development/_build/sub/plugins'
make[4]: *** [Makefile:865: distdir] Error 2
make[4]: Leaving directory '/home/ed/netcdf-c/netcdf-c-4.8.2-development/_build/sub/plugins'
make[3]: *** [Makefile:864: distdir-am] Error 1
make[3]: Leaving directory '/home/ed/netcdf-c/netcdf-c-4.8.2-development/_build/sub'
make[2]: *** [Makefile:858: distdir] Error 2
make[2]: Leaving directory '/home/ed/netcdf-c/netcdf-c-4.8.2-development/_build/sub'
make[1]: *** [Makefile:959: dist] Error 2
make[1]: Leaving directory '/home/ed/netcdf-c/netcdf-c-4.8.2-development/_build/sub'
make: *** [Makefile:971: distcheck] Error 1

```

**Comment by edwardhartnett** [comment]
It's because of this section in Makefile.am:

```
bzip2::
	rm -fr ./${BZIP2DIR} ${BZIP2SRC} BZIP2_LICENSE
	wget ${BZIP2URL}
	tar -zxf ${BZIP2DIR}.tar.gz
	cd ${BZIP2DIR}; cp ${BZIP2SRC} ..; cp LICENSE ../BZIP2_LICENSE ; cd ..
	rm -fr ./${BZIP2DIR}
```

@DennisHeimbigner what is being attempted here? Removing the BZIP2_LICENSE file is causing trouble.

**Comment by DennisHeimbigner** [comment]
The comment preceding this block says:
> # Record where bzip2 came from; may be out of date

So you should never be invoking this code; it is only to record how bzip2 was built.
How is this getting called?

**Comment by DennisHeimbigner** [comment]
Also, BZIP2_LICENSE is part of the EXTRA_DIST. Did you accidentally delete it?

**Comment by edwardhartnett** [comment]
I did a make check then a make distcheck.

**Comment by DennisHeimbigner** [comment]
Is BZIP2_LICENSE anywhere in your build directory?

**Comment by edwardhartnett** [comment]
OK everything works with a clean clone. I will close this issue.
