### ISSUE TITLE
add new enable/disable-plugin-install to configure.ac

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#2353]
This issue assumes #2348 is merged.

The current state of play is that --with-plugin-dir is used both to determine whether plugins are installed, and, optionally, where they are installed. This is overloading the option in a way that will be confusing for most autoconf users.

Instead, I suggest add a new option --enable-plugin-install. If --enable-plugin-install is used, plugins will be installed (in order of priority):
1 - any directory specified with --with-plugin-dir.
2 - the directory pointed to by HDF5_PLUGIN_PATH (if defined, and if it contains only one directory).
3 - the default plugin location for the platform (different for Unix and Windows).

In this way, the user can specify --enable-plugin-install and get the plugins installed. --with-plugin-dir need only be used if a non-default and non-HDF5_PLUGIN_PATH is specified (and should turn on --enable-plugin-install when used).

So most users can say --enable-plugin-install, and only those that need to can use --with-plugin-dir.

In the build summary and in netcdf_meta.h, there should be an additional yes/no entry for whether or not plugins are installed, in addition to the already existing entry in the summary saying what directory they were installed with.

This will allow user applications to use netcdf_meta.h to learn if plugins have been installed.

**Comment by edwardhartnett** [comment]
@DennisHeimbigner any objection to adding --enable/disable-plugin-install? I can put up a PR shortly...

**Comment by DennisHeimbigner** [comment]
What is wrong with --without-plugin-dir or --with-plugin-dir=no ?
