### ISSUE TITLE
Zstandard should be enabled by default

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#2355]
This assumes #2348 is merged, and #2354 is adopted.

The current state of play is that zstandard will be not working by default (because plugins will not be installed by default).

The original idea here was to prevent data producers from releasing netCDF data that cannot be understood by all users. But while we have now made changes which will allow NOAA and other large data producers to use zstandard without CCR, we still have not achieved the goal of making such files readable to all users.

Most users do:

`./configure --prefix=/install/point && make && make install`

If zstandard is off by default, and plugins are not installed by default, then these users will get an NC_EFILTER error when they try and read the new data files produced by NOAA with zstandard compression.

If zstandard is on by default, then all users will transparently be able to read these files, with no additional effort.

In previous conversations about this topic, the question of whether or not zstandard is enabled by default has been mixed in with discussions about implementation details. Let's have a discussion of just the issue of whether zstandard is enabled by default. We have already determined that zstandard is a firm international standard that is available on all platforms.

My 20 years experience with netCDF users, my current role at NOAA/NCAR, and my conversations with ESA engineers lead me to believe that users would be best served by having zstandard on by default. What is the counter-argument?

**Comment by dopplershift** [comment]
Well, to be fair I'm pretty sure "most users" install pre-built binaries from linux package managers, Homebrew, conda-forge, underpants gnomes on Windows (ok, probably not, but you get the idea). But I wouldn't expect those maintainers to necessarily catch that the new features were added and require new flags to enable. This could impact the speed of deployment of the new stuff, since you've then gotta wait for bug reports to trickle in, get fixed, etc...

**Comment by edwardhartnett** [comment]
I just gave my talk at the EGU where there was a great deal of interest in zstandard. Safe to say that many data producers are going to start using it. Will end users be able to read these files without re-installing netCDF? Only if plugins are installed in the correct place by default.

Otherwise, expect to get support emails: "Reading NOAA/ECMWF/NASA/ESA netCDF file returns an  NC_EFILTER error when I try to read the data..."

**Comment by edwardhartnett** [comment]
This is now working.
