### ISSUE TITLE
ncdump can generate nul characters &#0 ; when dumping ncml using -x.

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#236]
Re e-support TSE-683024
If a char valued attribute contains embedded nul characters,
then illegal xml will be generated when using the -x (ncml) flag.

**Comment by WardF** [comment]
Merged, closing out.

**Comment by DennisHeimbigner** [comment]
Solution:
There is not good solution since we have a char value '\0' that
is legal in a netcdf-c char valued attribute, but is completely
illegal in ncml (i.e. xml).

So, implemented hack is to go ahead and generate '&#0 ;' entities
and then complain that we are generating illegal ncml.
