### ISSUE TITLE
autoreconf warnings

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#2371]
I upgraded to the recently-released ubuntu-22, and now I get these warnings from autoreconf:

```
configure.ac:1125: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:1125: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:1125: the top level
configure.ac:1282: warning: The macro `AC_STRUCT_ST_BLKSIZE' is obsolete.
configure.ac:1282: You should run autoupdate.
./lib/autoconf/types.m4:1000: AC_STRUCT_ST_BLKSIZE is expanded from...
configure.ac:1282: the top level
configure.ac:1283: warning: The macro `AC_TRY_RUN' is obsolete.
configure.ac:1283: You should run autoupdate.
./lib/autoconf/general.m4:2997: AC_TRY_RUN is expanded from...
acinclude.m4:9: UD_CHECK_IEEE is expanded from...
configure.ac:1283: the top level

```

My version:

```
autoconf --version
autoconf (GNU Autoconf) 2.71
```

However, these do not prevent the build from working. make check works fine. ;-)

**Comment by DennisHeimbigner** [comment]
Removing it as I recall causes other problems with other versions.

**Comment by DennisHeimbigner** [comment]
I am trying to remember what caused the problem. I think it has to do with the
autoconf running on ubuntu 18

**Comment by edwardhartnett** [comment]
It apparently requires a more recent version of autoconf as well. I notice that it changed the version of autoconf required at the top of the configure.ac.

Since only developers ever have to run autoreconf, this should be fine. However, as I recommended in the PR, no need to merge this before the 4.9.0 release, so that there's plenty of time to make sure it works everywhere we need it to...
