### ISSUE TITLE
Changelog of v4.9.0

### ISSUE THREAD

**Issue by tbeu** [Unidata/netcdf-c#2394]
Changelog of [v4.9.0](https://github.com/Unidata/netcdf-c/releases/tag/v4.9.0) was created w.r.t. v4.3,1-rc.1 and thus contains far too many contributions.

![image](https://user-images.githubusercontent.com/5444067/173248909-c961bf7e-372d-4478-ae48-00a6bfeb319a.png)

**Comment by WardF** [comment]
Oops.  I'll keep an eye on that for the next release.

**Comment by tbeu** [comment]
You still can edit/fix the changelog of the released v4.9.0.
