### ISSUE TITLE
vpath (out of tree) build fails to find ncx.c

### ISSUE THREAD

**Issue by roblatham00** [Unidata/netcdf-c#242]
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### Environment Information

64 bit Linux (ubuntu 15.10), with autotools build. 

### Summary of Issue

when bbuilding "out of tree" or VPATH style , make cannot find ncx.c (which was generated from .m4 files)

### Steps to reproduce the behavior
- fetch git master
- autoreconf -fi
- mkdir build-dir
- cd build-dir
- ~/work/netcdf-c/configure CC=${HOME}/work/soft/mpich/bin/mpicc --prefix=${HOME}/work/soft/netcdf-master CPPFLAGS=-I${HOME}/work/soft/hdf5-1.8.16/include LDFLAGS=-L${HOME}/work/soft/hdf5-1.8.16/lib
- make

observe this error:

Making all in nc_test
make[2]: Entering directory '/home/robl/work/build/netcdf/nc_test'
cp /home/robl/work/netcdf-c/libsrc/ncx.c .
cp: cannot stat ‘/home/robl/work/netcdf-c/libsrc/ncx.c’: No such file or directory
Makefile:1593: recipe for target 'all' failed

of course it cannot stat libsrc/ncx.c :that file was generated and lives in the build dir.

**Comment by WardF** [comment]
Thanks for the report; I'll get this corrected.

**Comment by WardF** [comment]
Updated the appropriate `Makefile.am` and merged into `master`, so closing out the issue.
