### ISSUE TITLE
PLUGIN_INSTALL_DIR issues

### ISSUE THREAD

**Issue by sebastic** [Unidata/netcdf-c#2429]
[netcdf4-python test failures](https://github.com/Unidata/netcdf4-python/issues/1170) revealed some issues with the CMake build.

The default value doesn't match the documentation:
```cmake
# If user wants, then install selected plugins (default on)
SET(PLUGIN_INSTALL_DIR "NO" CACHE STRING "Whether and where we should install plugins; defaults to yes")
```

It suggest being a boolean (for which YES/ON is equivalent), but treating it as such, by using `-DPLUGIN_INSTALL_DIR:BOOL=ON`, causes the build to fail:
```cmake
Defaulting to -DPLUGIN_INSTALL_DIR=NOTFOUND
```

The default path (`/usr/local/hdf5/lib/plugin`) is also incorrect when using `-DCMAKE_INSTALL_PREFIX=/usr` and `-DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu`. A better default would be `${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/hdf5/plugin`.

**Comment by DennisHeimbigner** [comment]
Odd. I must be testing for the exact value "YES" instead of doing a boolean test.
I will check.

**Comment by DennisHeimbigner** [comment]
I hope https://github.com/Unidata/netcdf-c/pull/2430 fixes this.

**Comment by edwardhartnett** [comment]
This is fixed now and this issue should be closed.
