### ISSUE TITLE
The library cannot be used from the build directory

### ISSUE THREAD

**Issue by dzenanz** [Unidata/netcdf-c#2472]
If I set `netCDF_DIR` CMake setting in my project to netCDF's build directory (`C:\Dev\netCDF-19`), I run into the following:
```log
CMake Error at C:/Dev/netCDF-19/netCDFConfig.cmake:15 (message):
  File or directory C://include referenced by variable netCDF_INCLUDE_DIR
  does not exist !
Call Stack (most recent call first):
  C:/Dev/netCDF-19/netCDFConfig.cmake:23 (set_and_check)
  CMakeLists.txt:21 (find_package)
```
This is not surprising, given the content of `netCDFConfig.cmake`, which contains:
```cmake
get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)
...
set_and_check(netCDF_INCLUDE_DIR "${PACKAGE_PREFIX_DIR}/include")
```
This makes me think that this library is not meant to be used from the build directory.

**Comment by dzenanz** [comment]
Pointing `netCDF_DIR` to the install directory (`C:/Program Files (x86)/netCDF/lib/cmake/netCDF`) works.

**Comment by WardF** [comment]
You are correct that, typically, libraries are not meant to be used from their build directories, but instead from their 'install' directories, as specified by the `--prefix` argument when using the `configure` script, or the `-DCMAKE_INSTALL_PREFIX` argument when using `cmake`.
