### ISSUE TITLE
nc_def_var_zstandard() does not appear in the function documentation

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#2475]
When I look at the documentation here:
https://docs.unidata.ucar.edu/netcdf-c/current/

Under netcdf functions -> variables I see all the variable functions, including nc_def_var_quantize() but not nc_def_var_zstandard().

**Comment by WardF** [comment]
Interesting, let me see why/what happened. It should be straightforward, and I can update the documentation. Thanks!

**Comment by WardF** [comment]
Not sure why that happened, but it's also not relevant; it's fixed now. Thanks @edwardhartnett!

**Comment by edwardhartnett** [comment]
How did you fix without a PR?

I assumed that the problem was the documentation for zstandard didn't have an ingroup variables for doxygen. Was that it?

**Comment by WardF** [comment]
The docs were generated on a system without libzstd installed, and thus didn't process the relevant source.  I regenerated the source, double-checked the documentation was there, and uploaded it. No change to the code base was necessary.
