### ISSUE TITLE
"coordinates" attribute spelling should be lowercase in NUG

### ISSUE THREAD

**Issue by czender** [Unidata/netcdf-c#2481]
Not to be too pedantic, but....the NUG [documentation](https://docs.unidata.ucar.edu/netcdf-c/current/attribute_conventions.html) in Appendix A spells the `coordinates` attribute name with an uppercase `C` where it is defined. The CF conventions, on which this attribute is based, always uses (AFAICT) lowercase for this attribute. I think the attribute case is non-negotiable so I suggest this one-character change be made in the NUG to avoid confusion. Also this give you a chance to go into the weekend knowing you've solved at least one issue today.

**Comment by WardF** [comment]
That is a win I will take; thanks for pointing it out! I'll get a fix in, it is a nice change of pace from trying to sort out a MinGW issue (between reading chapters of a Modern Fortran textbook).
