### ISSUE TITLE
NC_CLASSIC_MODEL and nc_enddef

### ISSUE THREAD

**Issue by wkliao** [Unidata/netcdf-c#2489]
When using flag `NC_CLASSIC_MODEL` to create an HDF5-based file,
is calling `nc_enddef()` required before the first put/get var call?

In the NetCDF-C document, [nc_enddef](https://docs.unidata.ucar.edu/netcdf-c/current/group__datasets.html#gab794d8099a50a0c87cbd312e2f28d3c7) has the following statement, which implies it is not required.
```
It's not necessary to call nc_enddef() for netCDF-4 files.
```

**Comment by edwardhartnett** [comment]
Yes it is necessary when NC_CLASSIC_MODEL is used.

It is not necessary for netCDF-4 files which were created without NC_CLASSIC_MODEL.

**Comment by wkliao** [comment]
I am interested in learning the reason of why it is required. Could you please explain?

Also, look like the nc_enddef document can use a clarification.
