### ISSUE TITLE
nccopy dies when copying an NCZarr file

### ISSUE THREAD

**Issue by czender** [Unidata/netcdf-c#2502]
Using the latest snapshot (9/8/22, 5 PM MT) both `nccopy` and `ncks` fail to copy the 
[in_zarr4.cdl](https://github.com/Unidata/netcdf-c/files/9531082/in_zarr4.cdl.txt) file I posted yesterday. As mentioned in #2494, the `ncdump` and `ncks` tools now successfully print the Zarr version of that file. Here the issue is copying, not printing.

Here are some complementary symptoms that should be easy to reproduce:
```
zender@spectral:~$ nccopy -L 0 "file://${HOME}/nco/data/in_zarr4#mode=nczarr,file" "file://${HOME}/in_zarr4#mode=nczarr,file"
NetCDF: Invalid argument
Location: file nccopy.c; line 1169
zender@spectral:~$ ncks -O --log=0 "file://${HOME}/nco/data/in_zarr4#mode=nczarr,file" "file://${HOME}/in_zarr4#mode=nczarr,file"
ERROR: file nc4attr.c, line 99.
No error
ERROR: file nc4attr.c, line 99.
No error
ERROR: file nc4attr.c, line 99.
No error
ERROR: file nc4attr.c, line 99.
No error
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_close()
nco_err_exit(): ERROR Error code is -1. Translation into English with nc_strerror(-1) is "Unknown Error"
nco_err_exit(): ERROR NCO will now exit with system call abort()
Abort trap: 6
zender@spectral:~$ 
```

The `nccopy` error traces back to an endianness issue:
```
	if(endianness != NC_ENDIAN_NATIVE) { /* native is the default */
	    NC_CHECK(nc_def_var_endian(ogrp, o_varid, endianness));
	}
```
The non-error output from `ncks` ("ERROR: file nc4attr.c, line 99. No error") is a little disconcerting, though presumably harmless, because it also occurs during the (successful) copying from NCZarr->HDF5:
```
zender@spectral:~$ ncks -O --log=0 "file://${HOME}/nco/data/in_zarr4#mode=nczarr,file" ~/in_zarr4.nc
ERROR: file nc4attr.c, line 99.
No error
ERROR: file nc4attr.c, line 99.
No error
ERROR: file nc4attr.c, line 99.
No error
ERROR: file nc4attr.c, line 99.
No error
zender@spectral:~$ 
```
However, `nccopy` still fails when trying to copy NCZarr->HDF5:
```
zender@spectral:~$ nccopy "file://${HOME}/nco/data/in_zarr4#mode=nczarr,file" ~/in_zarr4.nc
NetCDF: Invalid argument
Location: file nccopy.c; line 1169
zender@spectral:~$ 
```
BTW, both `nccopy` and `ncks` successfully copy this file from HDF5->NCZarr.

**Comment by DennisHeimbigner** [comment]
Hopefully fixed by PR https://github.com/Unidata/netcdf-c/pull/2503

**Comment by czender** [comment]
PR #2503 may have fixed the original problem though it seems to have introduced at least one regression, because `nccopy` does not successfully copy with the command and file referenced above. Using the latest netCDF-c from this morning 10 AM CEST 9/15/22, here are the results of the above commands with `nccopy` and `ncks` trying to copy i`n_zarr4` from NCZarr to NCZarr. The commands now fail at a point, common to both commands, where they are trying to manipulate an attribute that, in the original CDL, is a long `NC_CHAR` array (netCDF3 string) and that `ncdump` wants to print (before it, too, fails) as a netCDF4 `string` type. Note that this same attribute (the `original_values` attribute of `ppc_bgr`), has previously caused problems. 

```
zender@spectral:~$ nccopy -L 0 "file://${HOME}/nco/data/in_zarr4#mode=nczarr,file" "file://${HOME}/in_zarr4#mode=nczarr,file"
NetCDF: Invalid argument
Location: file nccopy.c; fcn copy_var line 1427
zender@spectral:~$ 

zender@spectral:~/nco/data$ ncks -O --log=1 "file://${HOME}/nco/data/in_zarr4#mode=nczarr,file" "file://${HOME}/in_zarr4#mode=nczarr,file"
	log_level changed to 1
	HDF5 error messages have been turned off.
	NCZ_open: path file:///Users/zender/nco/data/in_zarr4#mode=nczarr,nczarr,file,file mode 4096 
	NCZ error messages turned on.
	NCZ_close: ncid 0x10000
	NCZ_open: path file:///Users/zender/nco/data/in_zarr4#mode=nczarr,nczarr,file,file mode 4096 
	NCZ error messages turned on.
ERROR: nco_inq_var() fails for variable "ppc_bgr"
ERROR NC_EINVAL Invalid argument
HINT: NC_EINVAL errors can occur for many reasons. Three common ones are described here. 1. When invalid chunking directives are given, e.g., to unchunk a record variable or to chunk a variable with an invalid size (such as zero or larger than a fixed dimension). This is the most frequent/likely cause in our experience. 2. When HDF4-enabled NCO attempts to directly write to an HDF4 (not HDF5) file. Not all HDF5 calls are available with HDF4, and the operators ncrename and ncatted are liklier to trigger this problem. We are working to solve this (fxm TODO nco1104). Please let us know if it affects you. For now the workaround is to convert the HDF4 file to netCDF4 first (e.g., with ncks -4 in.hdf out.nc), then use ncrename or ncatted. 3. When NCO operators attempt to open netCDF4 files using the diskless option, usually invoked with --diskless_all, --ram_all, or --open_ram. Is your input file netCDF4 format?  (http://nco.sf.net/nco.html#fmt_inq shows how to tell.) If so then omitting the diskless option may solve this problem. 4. When floating-point quantization algorithms (e.g., BitGroom) are applied to integer-containing variables.
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_inq_var()
nco_err_exit(): ERROR Error code is -36. Translation into English with nc_strerror(-36) is "NetCDF: Invalid argument"
nco_err_exit(): ERROR NCO will now exit with system call abort()
Abort trap: 6
zender@spectral:~/nco/data$ 
```
This `in_zarr4.cdl` file seems to be a good one for finding bugs, so I suggest that you test both ncdump and nccopy on it before concluding that the underlying problems have all been fixed.

**Comment by DennisHeimbigner** [comment]
Try regenerating in_zarr4 from in_zarr4.cdl and see if it works.
I think I introduced a back compatibility failure.

**Comment by czender** [comment]
YES!!! I guess the on-disk NCZarr format changed due to the recent PR and the new library is incompatible with the old format. Glad you thought of that. Copying and printing both work as advertised. I'll close this issue. Thanks, @DennisHeimbigner
