### ISSUE TITLE
Inconsistency in filter-related info in nc-config vs. netcdf_meta.h

### ISSUE THREAD

**Issue by czender** [Unidata/netcdf-c#2511]
Today's `main` snapshot includes some new info in `nc-config` which is good. However, it seems that `nc-config` and `netcdf_meta.h` are not consistent in what/how they report about available filters. Namely, `netcdf_meta.h` lacks any tokens that declare the availability of the Bzip2 and Blosc filters. `netcdf_meta.h` does contain a useful (meaning client applications like NCO can easily make use of it in C-code) Zstandard token:
```
#define NC_HAS_PAR_FILTERS   1 /* Parallel I/O with filter support. */
#define NC_HAS_NCZARR        1 /*!< Parallel I/O with filter support. */
#define NC_HAS_MULTIFILTERS  1 /*!< Nczarr support. */
#define NC_HAS_LOGGING       1 /*!< Logging support. */
#define NC_HAS_QUANTIZE      1 /*!< Quantization support. */
#define NC_HAS_ZSTD          1 /*!< Zstd support. */
```
(Also note the comment for `NC_HAS_NCZARR` is, erroneously, a copy of the `NC_HAS_PAR_FILTERS` comment). Whereas `nc-config` reports 
 ```
 --has-nczarr       -> yes
  --has-zstd         -> yes
  --has-benchmarks   -> no
  --has-multifilters -> yes
  --has-stdfilters   -> deflate bz2 blosc zstd
  --has-quantize     -> yes
```
So Zstandard is reported by itself (without additional parsing) by both `nc-config` and `netcdf_meta.h`. The presence of Bzip2 and Blosc, on the other hand, can only be learned by parsing the list output of `--has-stdfilters` from `nc-config`. If the new method of specifying available standard filters was intentionally to list them in `nc-config` but not say anything in `netcdf_meta.h` then, well, fine. At least it is intentional. But it the absence of Bzip2 and Blosc from `netcdf_meta.h` is unintentional then please fix it so client applications can make use of `NC_HAS_<filtername>` tokens for all standard filters.

**Comment by WardF** [comment]
Good catch; I'll get this oversight corrected!
