### ISSUE TITLE
checksumhack debugging print statement in libdap4/d4chunk.c 

### ISSUE THREAD

**Issue by j-m-adams** [Unidata/netcdf-c#2536]
Here it is in the main branch: 
https://github.com/Unidata/netcdf-c/blob/main/libdap4/d4chunk.c#L103

I see "checksumhack=0"  printed to the terminal when I access data from variables in opendap dataset URLs that start with dap4:// instead of https://

Here's how to reproduce it with ncdump:
> ncdump -v precipitationCal dap4://gpm1.gesdisc.eosdis.nasa.gov/opendap/GPM_L3/GPM_3IMERGHH.06/2020/001/3B-HHR.MS.MRG.3IMERG.20200101-S023000-E025959.0150.V06B.HDF5 | grep -A5 data:

I also see it when using the Python netCDF4 package. 

```
Python 3.8.5 (default, Sep  4 2020, 02:22:02)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netCDF4 as nc4
>>> nc4.getlibversion()
'4.8.0 of May 17 2021 17:58:15 $'
>>> f=nc4.Dataset('dap4://gpm1.gesdisc.eosdis.nasa.gov/opendap/GPM_L3/GPM_3IMERGHH.06/2020/001/3B-HHR.MS.MRG.3IMERG.20200101-S023000-E025959.0150.V06B.HDF5')
>>> v=f['precipitationCal']
>>> v[0][0][0:5]
checksumhack=0
masked_array(data=[-9999.9, -9999.9, -9999.9, -9999.9, -9999.9],
             mask=False,
       fill_value=1e+20,
            dtype=float32)
>>>

```

**Comment by DennisHeimbigner** [comment]
Sorry about that; the dap4 code is undergoing serious revision.
Fixed by PR https://github.com/Unidata/netcdf-c/pull/2537
