### ISSUE TITLE
Outdated documentation on "Parts of a NetCDF-4 HDF5 File"

### ISSUE THREAD

**Issue by shoyer** [Unidata/netcdf-c#254]
This page mentions special `_netcdf_dim_info` and `_netcdf_var_info` datasets used for storing netcdf specific information:
http://www.unidata.ucar.edu/software/netcdf/docs/file_structure_and_performance.html#parts_of_netcdf4

As far as I can tell based on the precise [format specification](http://www.unidata.ucar.edu/software/netcdf/docs/file_format_specifications.html#netcdf_4_spec) and examining actual netCDF4, these datasets are no longer used.

**Comment by WardF** [comment]
Thanks for the heads up; I'll take a look and address it!

**Comment by WardF** [comment]
Fixed, the documentation on the webpage will be updated with the next release.
