### ISSUE TITLE
trouble installing with zstandard?

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#2541]
From @Hang-Lei-NOAA:

```
Get it solved
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-2022.1.2/netcdf/4.9.0/include/netcdf_meta.h
NC_HAS_ZSTD=1

Not only need to assign the ZSTD_ROOT, but also need to set LDFLAGS  -lzstd lib.
```

Hang had to set LDFLAGS to have the Cmake build find the zstd library. Is that expected?

**Comment by DennisHeimbigner** [comment]
What is ZSTD_ROOT?

**Comment by Hang-Lei-NOAA** [comment]
--with-zstd=$ZSTD_ROOT

**Comment by edwardhartnett** [comment]
I believe Hang is using the netCDF CMake build for this.

The problem is that he has installed a number of times, thinking that he is getting zstandard compression, only to find that NC_HAS_ZSTD as still 0!

In the end he had to set LDFLAGS to include the zstandard library, and I don't think that is intented. CMake should add the LDFLAGS to include zstandard...

@Hang-Lei-NOAA can you post the entire CMake command you used to build netcdf-c?

**Comment by Hang-Lei-NOAA** [comment]
Hi, Ed,
Report to you. At the final, I am using the configure option to solve the
build. I highlight the additions in blue. The script is :
========================================
#!/bin/bash

set -eux

name="netcdf"
c_version=${1:-${STACK_netcdf_version_c}}
f_version=${2:-${STACK_netcdf_version_f}}
cxx_version=${3:-${STACK_netcdf_version_cxx}}

# Hyphenated version used for install prefix
compiler=$(echo $HPC_COMPILER | sed 's/\//-/g')
mpi=$(echo $HPC_MPI | sed 's/\//-/g')

[[ ${STACK_netcdf_enable_pnetcdf:-} =~ [yYtT] ]] && enable_pnetcdf=YES ||
enable_pnetcdf=NO
[[ ${STACK_netcdf_disable_cxx:-} =~ [yYtT] ]] && enable_cxx=NO ||
enable_cxx=YES

if $MODULES; then
    set +x
    source $MODULESHOME/init/bash
    module load hpc-$HPC_COMPILER
    [[ -z $mpi ]] || module load hpc-$HPC_MPI
    module try-load szip
    module load hdf5
    module load zstd
    if [[ ! -z $mpi ]]; then
      [[ $enable_pnetcdf =~ [yYtT] ]] && module load pnetcdf
    fi
    module list
    set -x

    prefix="${PREFIX:-"/opt/modules"}/$compiler/$mpi/$name/$c_version"
    if [[ -d $prefix ]]; then
      if [[ $OVERWRITE =~ [yYtT] ]]; then
          echo "WARNING: $prefix EXISTS: OVERWRITING!"
          $SUDO rm -rf $prefix
          $SUDO mkdir $prefix
      else
          echo "WARNING: $prefix EXISTS, SKIPPING"
          exit 0
      fi
    fi

else
    prefix=${NETCDF_ROOT:-"/usr/local"}
fi

if [[ ! -z $mpi ]]; then
    export FC=$MPI_FC
    export CC=$MPI_CC
    export CXX=$MPI_CXX
else
    export FC=$SERIAL_FC
    export CC=$SERIAL_CC
    export CXX=$SERIAL_CXX
fi

export F77=$FC
export F9X=$FC
export FFLAGS="${STACK_FFLAGS:-} ${STACK_netcdf_FFLAGS:-} -fPIC"
export CFLAGS="${STACK_CFLAGS:-} ${STACK_netcdf_CFLAGS:-} -fPIC"
export CXXFLAGS="${STACK_CXXFLAGS:-} ${STACK_netcdf_CXXFLAGS:-} -fPIC
-std=c++11"
export FCFLAGS="$FFLAGS"

URLroot="https://github.com/Unidata"

cd ${HPC_STACK_ROOT}/${PKGDIR:-"pkg"}
curr_dir=$(pwd)

LDFLAGS1="-L$HDF5_ROOT/lib"
LDFLAGS2=$(cat $HDF5_ROOT/lib/libhdf5.settings | grep AM_LDFLAGS | cut -d:
-f2)
[[ $enable_pnetcdf =~ [yYtT] ]] && LDFLAGS4="-L$PNETCDF_ROOT/lib"
if [[ ${STACK_netcdf_shared:-} != [yYtT] ]]; then
  LDFLAGS1+=" -lhdf5_hl -lhdf5"
  LDFLAGS3=$(cat $HDF5_ROOT/lib/libhdf5.settings | grep "Extra libraries" |
cut -d: -f2)
  [[ $enable_pnetcdf =~ [yYtT] ]] && LDFLAGS4+=" -lpnetcdf"
fi
LDFLAGS5="-L$ZSTD_ROOT/lib"
export LDFLAGS="${LDFLAGS1:-} ${LDFLAGS2:-} ${LDFLAGS3:-} ${LDFLAGS4:-}
${LDFLAGS5:-}"

export CFLAGS+=" -I$HDF5_ROOT/include"
export CPPFLAGS+=" -I$HDF5_ROOT/include"

cd $curr_dir

##################################################
# Download only

if [[ ${DOWNLOAD_ONLY} =~ [yYtT] ]]; then

    version=$c_version
    software=$name-"c"-$version
    [[ -d $software ]] || ( git clone -b "v$version" $URLroot/$name-c.git
$software )

    version=$f_version
    software=$name-"fortran"-$version
    [[ -d $software ]] || ( git clone -b "v$version"
$URLroot/$name-fortran.git $software )

    version=$cxx_version
    software=$name-"cxx4"-$version
    [[ -d $software ]] || ( git clone -b "v$version"
$URLroot/$name-cxx4.git $software )

    exit 0

fi

##################################################

set +x
echo
"################################################################################"
echo "BUILDING NETCDF-C"
echo
"################################################################################"
set -x

version=$c_version
software=$name-"c"-$version
URL="$URLroot/$name-c.git"
[[ -d $software ]] || ( git clone -b "v$version" $URL $software )
[[ -d $software ]] && cd $software || ( echo "$software does not exist,
ABORT!"; exit 1 )
[[ -d build ]] && rm -rf build
mkdir -p build && cd build

[[ ${STACK_netcdf_shared} =~ [yYtT] ]] || shared_flags="--disable-shared"
[[ $enable_pnetcdf =~ [yYtT] ]] && pnetcdf_conf="--enable-pnetcdf"
[[ -z $mpi ]] || extra_conf="--enable-parallel-tests --with-zstd=$ZSTD_ROOT"

../configure --prefix=$prefix \
             --enable-cdf5 \
             --disable-dap \
             --enable-netcdf-4 \
             --disable-doxygen \
             ${shared_flags:-} ${pnetcdf_conf:-} ${extra_conf:-}

VERBOSE=$MAKE_VERBOSE make -j${NTHREADS:-4}
[[ $MAKE_CHECK =~ [yYtT] ]] && make check
$SUDO make install

# generate modulefile from template
[[ -z $mpi ]] && modpath=compiler || modpath=mpi
$MODULES && update_modules $modpath $name $c_version
echo netcdf-c $version $URL >> ${HPC_STACK_ROOT}/hpc-stack-contents.log

##################################################

**Comment by edwardhartnett** [comment]
OK, so you are using the autoconf build. You include --with-zstd=, which is expected.

But you still have to set LDFLAGS? It should be set for you...

**Comment by Hang-Lei-NOAA** [comment]
Hi, Ed, Yes. that is correct. I read into the configure script. We need to
do so, otherwise the info cannot be passed to the step that changes the
value to 1 of variable NC_HAS_ZSTD.

**Comment by edwardhartnett** [comment]
Is there a log that shows what the final configure command and environment settings were for this build?

**Comment by Hang-Lei-NOAA** [comment]
Yes, the only checking for zstd occurs on ld part:

-------------------------------
checking for blosc_init in -lblosc... no
checking for ZSTD_compress in -lzstd... yes
checking for library containing ZSTD_compress... -lzstd
checking whether libzstd library is available... yes
checking for BZ2_bzCompress in -lbz2... yes
--------------------------------

This echo the only reference of zstd in the v4.9.0 configure script  at
line 7648.

**Comment by edwardhartnett** [comment]
I believe this has been resolved and can be closed. Thanks @Hang-Lei-NOAA ! If this is still an issue let me know.
