### ISSUE TITLE
conda-forge build test failure

### ISSUE THREAD

**Issue by dopplershift** [Unidata/netcdf-c#2551]
Running down a test failure in conda-forge/libnetcdf-feedstock#154, `ncdump/tst_bom.sh` and `ncdump/tst_nccopy4.sh` failed, with odd diffs. They were running concurrently, and it turns out the problem is that both test scripts write temporary output to `tmp.cdl`.

I'll also note that `tmp.cdl` is mentioned in `ncdump/run_back_comp_tests.sh` (but commented out). The file is also removed (but not created?) in `ncdump/tst_nccopy5.sh`.

There are also some occurrences in `nczarr_test/run_nccopyz.sh` and `nczarr_test/run_nczarr_fill.sh`. I'm not sure if that's potentially problematic or not.

**Comment by DennisHeimbigner** [comment]
I knew there was a race condition in some of our tests, but never
got around to tracking the cause. Thanks. I will submit a PR.n

**Comment by dopplershift** [comment]
Closing because the tests mentioned here are passing.
