### ISSUE TITLE
zstd install question: what should the user set HDF5_PLUGIN_PATH to?

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#2563]
A user has asked me this:

> Trying to install netcdf on macos clang 14 and when I use the flags that I have used in the past in linux they are not working on clang.  Any ideas?  Or is there a installation guide for mac?
> 
> this is the message i'm getting:
> 
> `configure: WARNING: libnetcdf was built with zstd support, but HDF5_PLUGIN_PATH is not set. Either set the HDF5_PLUGIN_PATH environmental variable if zstandard tests fail, or use --disable-zstandard-plugin when running configure.`

**Comment by HathewayWill** [comment]
Good morning NETCDF community,

I am the user that Ed wrote about.  I wanted to share my commands and log files to help debug this issue.

Below you will find the bash commands and log files for each command in a .zip file.

Thank you for all your help.


```

export CC=gcc
export CXX=g++
export FC=gfortran
export F77=gfortran
export CFLAGS="-fPIC -fPIE -O3"


echo " "


#############################zlib############################
#Uncalling compilers due to comfigure issue with zlib1.2.13
#With CC & CXX definied ./configure uses different compiler Flags

cd $WRF_FOLDER/Downloads
tar -xvzf v1.2.13.tar.gz
cd zlib-1.2.13/
./configure --prefix=$DIR/grib2 | tee zlib.configure.log
make | tee zlib.make.log
make install | tee zlib.make.install.log
#make check


echo " "
#############################libpng############################
cd $WRF_FOLDER/Downloads
export LDFLAGS=-L$DIR/grib2/lib
export CPPFLAGS=-I$DIR/grib2/include
tar -xvzf libpng-1.6.38.tar.gz
cd libpng-1.6.38/
./configure --prefix=$DIR/grib2 | tee libpng.configure.log 
make | tee libpng.make.log
make install | tee libpng.make.install.log
#make check


echo " "
#############################JasPer############################

cd $WRF_FOLDER/Downloads
unzip jasper-1.900.1.zip
cd jasper-1.900.1/
autoreconf -i
CFLAGS="-Wno-implicit-function-declaration" ./configure --prefix=$DIR/grib2 | tee jasper.configure.log
make | tee jasper.make.log
make install | tee jasper.make.install.log
export JASPERLIB=$DIR/grib2/lib
export JASPERINC=$DIR/grib2/include


echo " "
#############################hdf5 library for netcdf4 functionality############################

cd $WRF_FOLDER/Downloads
tar -xvzf hdf5-1_13_2.tar.gz
cd hdf5-hdf5-1_13_2
CFLAGS="-Wno-implicit-function-declaration" ./configure --prefix=$DIR/grib2 --with-zlib=$DIR/grib2 --enable-hl --enable-fortran | tee hdf5.configure.log 
make | tee hdf5.make.log
make install | tee hdf5.make.install.log
#make check

export HDF5=$DIR/grib2
export LD_LIBRARY_PATH=$DIR/grib2/lib:$LD_LIBRARY_PATH


echo " "
##############################Install NETCDF C Library############################
cd $WRF_FOLDER/Downloads
tar -xzvf v4.9.0.tar.gz
cd netcdf-c-4.9.0/
export CPPFLAGS=-I$DIR/grib2/include
export LDFLAGS=-L$DIR/grib2/lib
CFLAGS="-Wno-implicit-function-declaration" ./configure --prefix=$DIR/NETCDF --disable-dap --enable-netcdf-4 --enable-netcdf4 --enable-shared | tee netcdf-c.configure.log
make | tee netcdf-c.make.log
make install | tee netcdf-c.make.install.log
#make check

export PATH=$DIR/NETCDF/bin:$PATH
export NETCDF=$DIR/NETCDF
echo " "

##############################NetCDF fortran library############################

cd $WRF_FOLDER/Downloads
tar -xvzf v4.6.0.tar.gz
cd netcdf-fortran-4.6.0/
export LD_LIBRARY_PATH=$DIR/NETCDF/lib:$LD_LIBRARY_PATH
export CPPFLAGS=-I$DIR/NETCDF/include
export LDFLAGS="-L$DIR/NETCDF/lib -L$DIR/grib2/lib"

CFLAGS="-Wno-implicit-function-declaration" ./configure --prefix=$DIR/NETCDF --enable-netcdf-4 --enable-netcdf4 --enable-shared | tee netcdf-fortran.configure.log
make | tee netcdf-fortran.make.log
make install | tee netcdf-fortran.make.install.log
make check


echo " "
```
[Archive.zip](https://github.com/Unidata/netcdf-c/files/10069237/Archive.zip)

**Comment by HathewayWill** [comment]
```
wills-Mac:OBSGRID will$ gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin


wills-Mac:OBSGRID will$ g++ --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by WardF** [comment]
I'm seeing a warning message re: HDF5_PLUGIN_PATH.  A few questions.

First, is there an error? Does the test fail? Or are you seeing a new warning? You can modify the WRF script to specify `--enable-plugins` and `--with-plugin-dir=<plugin directory of your choice>`; set `HDF5_PLUGIN_PATH` to the same `<plugin directory of your choice>` passed to `--with-plugin-dir`.

**Comment by HathewayWill** [comment]
Good afternoon,

The error messages are attached in the log files (zipped in original message).

Looking at the installation HDF5 and NETCDF-C appear to install correctly but the NETCDF-Fortran has the error.

I have tried setting the flags and variables you mentioned and still get the same result each time.

**Comment by DennisHeimbigner** [comment]
Where (which file and approximate line number) are the errors to which you refer?

**Comment by HathewayWill** [comment]
> Where (which file and approximate line number) are the errors to which you refer?

So sadly my desktop has suffered a fatal non repairable motherboard failure.  So I cannot open the files to get the line number. 

If I remember correctly it is in the netcdf-fortran-make.log file (if I remember the name correctly) at the end of the file. There are Error 1 and Error 2 messages when trying to make netcdf fortran. 

One possible issue that might be the cause is that the Mac is using clang gcc and g++ compilers and homebrew gfortran compilers instead of all the same compiler. 

I was testing all homebrew GCC/G++/GFORTRAN compilers and got through netcdf-C before my motherboard died.  At that time it was working. So not sure if using two different compiler suites was the issue.

**Comment by edwardhartnett** [comment]
I believe all this got sorted out, and the current 4.9.0 release seems to be installing with zstandard everywhere OK. I will close this issue. Thanks all for your assistance.
