### ISSUE TITLE
Fix symbol export for dynamic link libraries

### ISSUE THREAD

**Issue by zklaus** [Unidata/netcdf-c#2599]
I recently added a windows build of netcdf-fortran for conda-forge at conda-forge/netcdf-fortran-feedstock#78.

In the process, I stumbled across two missing symbol exports in netcdf-c, namely `ncerr` and `ncopt`, the only two *variables* that are part of the API. Since they are only part of the V2 API, I worked around that by deactivating that, but it would be nice to fix the underlying issue. It also provides the opportunity to make use of more recent gcc features to tidy up and speed up the API.

The underlying issue is that for these variables, only the `extern` declaration in `netcdf.h` is marked as `__declspec(dllexport)`, but to make sure that also the actual variable gets exported, in addition the variable definitions in https://github.com/Unidata/netcdf-c/blob/bb8087aa1a6f6dfe767f721b6838eeb46848e415/libdispatch/dv2i.c#L35-L37 need to be exported.

Within the current framework, the easiest would be to mark those two lines as `MSC_EXTRA`.

Why don't we run into the same problem with Linux and Osx? That's because the old default of GCC is to export everything, but facilities were added that afford more control over visibility; more on that below.

I think there is an opportunity here to go the extra mile. First, I think there is a misunderstanding about the `extern` keyword. For variables, it changes the linkage to external, meaning that `extern int ncerr;` is the only way to *declare* that variable without *defining* it. But for functions, a pure *declaration* without *definition* as in the `netcdf.h` header file, defaults to external linkage, i.e. the `extern` keyword in normal function declarations is redundant.

Coming back to the visibility on the Linux side of things, the GCC wiki explains it in [this article](https://gcc.gnu.org/wiki/Visibility), which also links to a more in-depth exposition by Ulrich Drepper [here](https://akkadia.org/drepper/dsohowto.pdf). Hiding the private bits of the library provides a number of benefits.

How should this be applied to netcdf? We can almost copy and paste the suggestion from the GCC wiki to add the `__attribute__ ((visibility ...))` using the same macros that are already in place for the Windows DLL support. We can remove the `extern` keyword from the `EXTERNL` macro and add it only to the variables that we want to be exported. It might be a good idea then to rename it to something like `NETCDF_API`.

Side notes:
- `ncerr` and `ncopts` are declared twice in `netcdf.h`, at https://github.com/Unidata/netcdf-c/blob/bb8087aa1a6f6dfe767f721b6838eeb46848e415/include/netcdf.h#L558-L561, and at https://github.com/Unidata/netcdf-c/blob/bb8087aa1a6f6dfe767f721b6838eeb46848e415/include/netcdf.h#L1949 and https://github.com/Unidata/netcdf-c/blob/bb8087aa1a6f6dfe767f721b6838eeb46848e415/include/netcdf.h#L1963. Probably only one declaration is needed.
- Inspecting the windows import library for symbols where only the `extern` declaration was exported but not the definition also showed the variable `ocdebug`.

**Comment by DennisHeimbigner** [comment]
Thanks for this info. I, for one, was not aware that GCC had added this feature
Some issues come to mind that we would need to examine, namely, its effects on (1) unit-tests that access otherwise unexported symbols, (2) tracing and logging, (3) memory leaks.

**Comment by zklaus** [comment]
So I can see how you would like to think about the extended solution a bit, but in the mean time, would you consider fixing the bug of missing exports for `ncerr` and `ncopts`?

**Comment by WardF** [comment]
@zklaus Yes, I'm tidying up for the 4.9.1 release right now, I think we can get the quick fix in in short order, after that we will consider the larger question.  Thanks!

**Comment by zklaus** [comment]
Great, thanks, @WardF and @DennisHeimbigner! I really appreciate all your work here and am very much looking forward to the extended filter and compression options!
