### ISSUE TITLE
SOVERSION decreased from 12 to 11 in 4.4.1-RC2

### ISSUE THREAD

**Issue by sebastic** [Unidata/netcdf-c#262]
The SOVERSION was increased to 12 in 4.4.1-RC1 with these changes in `CMakeLists.txt` & `liblib/Makefile.am` (83f1e01409aeb50d4b1820e382985c3ab42741e2):
```
-SET(netCDF_LIB_VERSION 11.0.0)
-SET(netCDF_SO_VERSION 11)
+SET(netCDF_LIB_VERSION 12.0.0)
+SET(netCDF_SO_VERSION 12)
```
```
-libnetcdf_la_LDFLAGS = -version-info 11:0:0 ${NOUNDEFINED}
+libnetcdf_la_LDFLAGS = -version-info 12:0:0 ${NOUNDEFINED}
```
This SONAME bump was correct because several symbols available in earlier versions were removed, as documeted in the [changes to the Debian package symbols file](https://anonscm.debian.org/cgit/pkg-grass/netcdf.git/commit/?id=4b06e1155e72cad98d3ed150cbc436d29a58d46f)

4.4.1-RC2 reverted the SOVERSION back to 11 with commits 10f85caf265efa66e3cc36b6f02f3de3ed8c588d, 595474d71bb3968c584c5994c5415b78d60723aa & 287e73ca2621dd61045ddeb7a5f837a35f4053fc.

Based on the symbols changes, the SONAME bump was correct and did not need reverting. Case 3 from the [libtool manual](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html) is applicable:
> Programs may need to be changed, recompiled, and relinked in order to use the new version. Bump current, set revision and age to 0.

**Comment by DennisHeimbigner** [comment]
All the changed/deleted symbols are not externally usable; only the symbols
defined in include/netcdf*,h are available for use by library users. I would have said
that only changes to that set of files need to be considered for SONAME bump. Ward?

**Comment by sebastic** [comment]
None of the libnetcdf reverse dependencies in Debian are using any of the removed symbols (all confined to ncdispatch.h), so the SONAME bump is indeed not strictly required.

I think it's safe to close this issue and leave the SONAME as it is in 4.4.1 RC2.
