### ISSUE TITLE
nc_def_var_bzip2 is not documented

### ISSUE THREAD

**Issue by jedwards4b** [Unidata/netcdf-c#2621]
This is in the [current 4.9.1 documentation.](https://docs.unidata.ucar.edu/netcdf-c/current/group__variables.html#ga59cc48a864c142ebd5897779ed703006)  I don't see bzip2 in the list.

**Comment by edwardhartnett** [comment]
Right here now: https://docs.unidata.ucar.edu/netcdf-c/current/netcdf__filter_8h.html#a6f0038befa623732c8d1578c2e47736b

This issue should be closed.
