### ISSUE TITLE
2 nczarr tests fails when testing netcdf 4.9.1

### ISSUE THREAD

**Issue by nhlc143796** [Unidata/netcdf-c#2624]
I'm building netcdf 4.9.1 on ubuntu 22.04 and all tests passed except for two: `nczarr_test_run_interop` and `nczarr_test_run_nczarr_fill`.

Nczarr Test Suite:

>==============================================
   netCDF 4.9.1: nczarr_test/test-suite.log
==============================================
TOTAL: 20
PASS:  18
SKIP:  0
XFAIL: 0
FAIL:  2
XPASS: 0
ERROR: 0
.. contents:: :depth: 2
FAIL: run_interop.sh
====================
findplugin.sh loaded
final HDF5_PLUGIN_DIR=/home/turimao/v4.9.1/netcdf-c-4.9.1/plugins/.libs
./run_interop.sh: 57: unzip: not found
FAIL run_interop.sh (exit status: 127)
FAIL: run_nczarr_fill.sh
========================
findplugin.sh loaded
final HDF5_PLUGIN_DIR=/home/turimao/v4.9.1/netcdf-c-4.9.1/plugins/.libs
*** Test: Github issues #2063, #2062, #2059
*** Test: Github issue #2062
./run_nczarr_fill.sh: 29: unzip: not found
FAIL run_nczarr_fill.sh (exit status: 127)
>
The same 2 tests also failed when trying to build it with Cmake.

**Comment by akrherz** [comment]
The error message `unzip: not found` is noting that the command `unzip` does not exist.  `sudo apt install unzip` is likely the workaround.

**Comment by nhlc143796** [comment]
I'm able to install netcdf now with unzip installed. Thanks!
