### ISSUE TITLE
"No space left on device" filesystem

### ISSUE THREAD

**Issue by cponder** [Unidata/netcdf-c#2625]
I'm running into these messages
```
FAIL: tst_large_cdf5
../test-driver: line 140: tst_large_cdf5.trs: No space left on device
../test-driver: line 141: tst_large_cdf5.trs: No space left on device
../test-driver: line 142: tst_large_cdf5.trs: No space left on device
../test-driver: line 143: tst_large_cdf5.trs: No space left on device
make[3]: [tst_large_cdf5.log] Error 1 (ignored)
../test-driver: line 111: tst_cdf5_begin.log: No space left on device
```
Can you tell me how large these files should be? But also, are they allocated in the build-directory or are they using elsewhere like ```/tmp```?

**Comment by WardF** [comment]
Hi Carl, let me take a look; they can be quite large, and they reside within the build directory.

**Comment by DennisHeimbigner** [comment]
There is a build option,  --enable-large-file-tests, that is disabled by default.
Looks like this test should be condition on that option.

**Comment by WardF** [comment]
@cponder my day has finally wound around to where it started; I've changed the test temporarily to not remove the large files, I'm running the tests and will reply with the temporary file sizes shortly.

**Comment by WardF** [comment]
@cponder The file is 4GB in size.

**Comment by cponder** [comment]
Yeah, that shouldn't be a problem. There are about 40GB free before I start the NetCDF-C install & test but I keep getting these space messages.
There may well be something wrong with the filesystem on the cluster I'm using.
One thing is that 4GB is about the 32-bit limit, which is suspicious.
I'll go ahead and close this one, thanks.
