### ISSUE TITLE
Add support for transient HDF5 datatypes

### ISSUE THREAD

**Issue by ZedThree** [Unidata/netcdf-c#2651]
As raised in #267 and #2650, with HDF5 it is possible to store user-defined datatypes within a variable, for example:

```
HDF5 "test.h5" {
GROUP "/" {
   DATASET "x" {
      DATATYPE  H5T_COMPOUND {
         H5T_IEEE_F64LE "r";
         H5T_IEEE_F64LE "i";
      }
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): {
            1,
            0
         }
      }
   }
}
}
```
or
```
HDF5 "test.nc" {
GROUP "/" {
   DATASET "foo" {
      DATATYPE  H5T_ENUM {
         H5T_STD_I8LE;
         "FALSE"            0;
         "TRUE"             1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): TRUE
      }
   }
}
}
```

NetCDF can already read these datatypes if they have been committed to the file with a name (just in the root group, or in any group?), so presumably it's just the type-lookup logic that needs to be modified?

**Comment by edwardhartnett** [comment]
Yes I believe you are correct. This is a the result of a mistake on my part, I just did not understand that these type definitions could exist. 

Indeed the answer is to modify the metadata reading functions to spot these types and read them.

**Comment by ZedThree** [comment]
Nope, no requirement on the superblock version, this has been in HDF5 since at least 1.6, more than 15 years.
