### ISSUE TITLE
Attached file causes ncdump to fail.

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#269]
The attached file causes ncdump to crash.
[tdset.h5.zip](https://github.com/Unidata/netcdf-c/files/280467/tdset.h5.zip)
See comments in issue https://github.com/Unidata/netcdf-c/issues/265.

**Comment by DennisHeimbigner** [comment]
Problem:  failing to set the hash when phony_dims are created
in nc4hdf.c
Solution: compute hash

**Comment by WardF** [comment]
Tagging to reflect who fixed this issue, closing as it appears to be fixed.
