### ISSUE TITLE
`unit_test_tst_exhash` performs a too-large left shift

### ISSUE THREAD

**Issue by seanm** [Unidata/netcdf-c#2702]
1. build master with UBSan
2. run `ctest -R unit_test_tst_exhash`
3. UBSan will detect a too-large left shift, see my lldb session:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x0000000100a42dc3 libnetcdf.19.dylib`ncexhashprintstats(map=0x0000606000000e60) at ncexhash.c:857:20
   854 	    fprintf(stderr," |leaf|=%d nactive/nleaves=%g", map->leaflen, leafavg);
   855 	    fprintf(stderr," load=%g",leafload);
   856 	    fprintf(stderr,"]\n");
-> 857 	    dirsize = (1ULL<<(map->depth)*((unsigned long long)sizeof(void*)));
   858 	    leafsize = (nleaves)*((unsigned long long)sizeof(NCexleaf));
   859 	    total = dirsize + leafsize;
   860 	    fprintf(stderr,"\tsizeof(directory)=%llu sizeof(leaves)=%lld total=%lld\n",

(lldb) p map->depth
(int) $0 = 11

(lldb) p sizeof(void*)
(unsigned long) $1 = 8
```

So basically it's doing 1ULL << 88.

Not sure what value it's expecting to get with such an operation, but it's undefined behaviour to shift into, or past, the MSB.

**Comment by DennisHeimbigner** [comment]
Looks like I am missing a set of parentheses.
I suspect it should have been:
> dirsize = ((1ULL<<(map->depth))*((unsigned long long)sizeof(void*)));

**Comment by seanm** [comment]
Could be. I have no idea. :)  I changed it to `dirsize = (1ULL << map->depth) * sizeof(void*);` and the test now passes, but that doesn't prove the change is correct of course...

**Comment by seanm** [comment]
At least I think that's what you were suggesting... your asterixes got interpreted as markdown...

**Comment by DennisHeimbigner** [comment]
Fixed by PR https://github.com/Unidata/netcdf-c/pull/2726.
