### ISSUE TITLE
Access Failure when opening DAP4 URLs

### ISSUE THREAD

**Issue by battistowx** [Unidata/netcdf-c#2704]
Hello,

I'm currently in the process of testing NASA Earthdata "Cloud OPeNDAP" (OPeNDAP granules that have been migrated to the AWS cloud, and have been upgraded from DAP2 to DAP4) granule access with netCDF4 and Xarray, and I have encountered `[Errno -77] NetCDF: Access failure` errors when using nc4.Dataset() and xr.open_dataset() to open dap4:// URLs after upgrading from libnetcdf 4.8.1 to 4.9.2. This error is also present in 4.9.1. The notebook I have been using to test is here: https://nasa-openscapes.github.io/earthdata-cloud-cookbook/how-tos/working-locally/Earthdata_Cloud__Data_Access_OPeNDAP_Example.html

The test environment is a Ubuntu Jupyterhub instance deployed inside AWS EC2, with the following environment.yml: https://github.com/NASA-Openscapes/corn/blob/main/ci/environment.yml

Code where the error is triggered:

- `f = nc4.Dataset("dap4://opendap.earthdata.nasa.gov/collections/C2532426483-ORNL_CLOUD/granules/Daymet_Daily_V4R1.daymet_v4_daily_hi_tmax_2010.nc", "r")`
- `xr.open_dataset("https://opendap.earthdata.nasa.gov/collections/C2532426483-ORNL_CLOUD/granules/Daymet_Daily_V4R1.daymet_v4_daily_hi_tmax_2010.nc")`

Currently, the only granule that works is in this OPeNDAP tutorial: https://github.com/OPENDAP/notebooks/blob/master/tutorials/netCDF4_tutorial.ipynb

Note that these work only with dap4:// URLs in 4.9.0 and that downgrading to 4.9.0 or 4.8.1 fixes this issue.

**Comment by DennisHeimbigner** [comment]
What server and version are you using? Hyrax or Thredds or something else?

**Comment by DennisHeimbigner** [comment]
The problem is that that web server does not accept the standard HTTP basic authentication protocol.
It instead sends replies asking for user+pwd in a way that my code cannot currently understand.
If you stick the url into a web browser, it will popup a window asking for the user+pwd interactively.
My code currently does not support such interactive operation.
One other thing. Since the server is Hyrax, you will need to append the fragment '#hyrax'
to the URL. This is because there is a problem with checksum handling in Hyrax servers.

**Comment by DennisHeimbigner** [comment]
I did some experiments. This should work on the current release, so there may be some problem
with the netcdf-c library. I will post further info here if I figure out what is going on.

**Comment by DennisHeimbigner** [comment]
Ok, there s a solution; turns out it is described in the file docs/auth.md.
Anyway, do this:
1. Create file ````~/.netrc```` with permissions 0600 and with the following content:
````machine urs.earthdata.nasa.gov login <username> password <password>````
where *username* is your earthdata user name and *password* is your earthdata password.
2. Create file ````~/.ncrc````  (or if you prefer ````~/.dodsrc````)with the following content:
````
HTTP.COOKIEJAR=/home/<login-name>/urs_cookies
HTTP.NETRC=/home/<login-name>/.netrc
````
where *login-name* is your local machine login name.
4. To test, see if you can read the file using, for example:
````
ncdump -h 'https://opendap.earthdata.nasa.gov/collections/C2532426483-ORNL_CLOUD/granules/Daymet_Daily_V4R1.daymet_v4_daily_hi_tmax_2010.nc'
````

**Comment by battistowx** [comment]
I've verified that my netrc is created with credentials and that my dodsrc/urs_cookies files are present. I also used 4.9.1 to test with ncdump, and the same error occurs. Also verified that it still works with 4.8.1 and 4.9.0. 

Some more information about how I navigate between versions for testing, if that helps:

On my Mac, I have been creating separate conda environments with Python 3.9, and I have been using Anaconda to install libnetcdf==4.9.1 or 4.9.2, which allows me to isolate it from any dependencies installed by netcdf4-python. However, I've also been using pip to install netcdf4-python for testing with that, and I have verified that it installs netcdf-c 4.8.1, even with the latest netcdf4-python version. This could be a coincidence with my environment, though.

**Comment by battistowx** [comment]
Same one as suggested:

`ncdump -h 'https://opendap.earthdata.nasa.gov/collections/C2532426483-ORNL_CLOUD/granules/Daymet_Daily_V4R1.daymet_v4_daily_hi_tmax_2010.nc'`

**Comment by DennisHeimbigner** [comment]
Looks like this will not be fixed until the next release. Sorry.

**Comment by battistowx** [comment]
That's no problem! Thank you for addressing this!

**Comment by battistowx** [comment]
Update: It looks like the release of netcdf4-python 1.6.4 is using the 4.9.3-development version of libnetcdf, and with that version, I am not receiving any access failure errors like before!

**Comment by battistowx** [comment]
Just following up on this thread re: 4.9.2-recently, we have been receiving bug reports where users will attempt to access some of our GrADS servers, and are receiving access errors. Doing the pip install for netcdf4-python 1.6.5 does install the 4.9.3-development branch of libnetcdf, which fixes these errors.
