### ISSUE TITLE
Use of C reserved name: `_FillValue`

### ISSUE THREAD

**Issue by schwehr** [Unidata/netcdf-c#2728]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue

Is included at the current head (6e1895fee86086afee3fed58fdd7cef651551acb)

* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)

Standards conforming C compiler

* a description of the issue with the steps needed to reproduce it

Use a most recent version of GCC or CLANG and enforce standards compliance:

- https://devblogs.microsoft.com/oldnewthing/20230109-00/?p=107685
- https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html

https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf

>  All identifiers that begin with an underscore and either an uppercase letter or another
underscore are always reserved for any use.

```
find . -name "*.[ch]" | grep -v git | xargs grep _FillValue | egrep -v 'test|"_FillValue"|@return|/\*|_FillValue_att\['
./ncdump/ncdump.c:  [-XF]            Unconditionally output the type of the _FillValue attribute\n\
./ncdump/ncdump.c:        || (formatting_specs.xopt_filltype && varid != NC_GLOBAL && strcmp(_FillValue,att.name)==0))
./ncdump/ncdump.c:	 * _FillValue attribute, because nc_def_var_fill() creates a
./ncdump/ncdump.c:	 * _FillValue attribute, if needed, and it's value gets
./ncdump/ncdump.c:    nc_status = nc_inq_att(ncid,varid,_FillValue,&att.type,&att.len);
./ncdump/ncdump.c:	NC_CHECK(nc_get_att(ncid, varid, _FillValue, fillvalp));
./libhdf5/hdf5var.c:        retval = NC4_HDF5_del_att(ncid, varid, _FillValue);
./libhdf5/hdf5var.c:        if ((retval = nc_put_att(ncid, varid, _FillValue, var->type_info->hdr.id,
./libhdf5/hdf5var.c:        retval = NC4_HDF5_del_att(ncid, varid, _FillValue);
./libhdf5/hdf5attr.c:     * struct for this var. (But ignore a global _FillValue
./libhdf5/hdf5attr.c:    if (!strcmp(att->hdr.name, _FillValue) && varid != NC_GLOBAL)
./libsrc/var.c:		status = nc_get_att(ncid, varid, _FillValue, fill_valuep);
./libsrc/var.c:		status = NC3_del_att(ncid, varid, _FillValue);
./libsrc/var.c:		status = NC3_put_att(ncid, varid, _FillValue, varp->type, 1, fill_value, varp->type);
./libsrc/nc3internal.c:    attrpp = NC_findattr(&varp->attrs, _FillValue);
./ncgen3/ncgeny.c:    if (STREQ(atts[natts].name, _FillValue) &&
./ncgen3/ncgeny.c:                   vars[atts[natts].var].name, _FillValue);
./libdispatch/derror.c:	 return "NetCDF: Not a valid data type or _FillValue type mismatch";
./libdispatch/dattput.c: * writing a _FillValue attribute, and will tell the HDF5 layer to use
./libdispatch/dattput.c: * netCDF-4 files, a _FillValue attribute will be checked for
./libdispatch/dattinq.c:         if (nc_put_att_schar(ncid, varid, _FillValue, NC_BYTE, 1, &fill_value)) ERR;
./libdispatch/dvar.c:   _FillValue attribute, if any. If the _FillValue attribute is not
./ncgen/getfill.c:   1. If the tvsym argument is a variable and it has a _FillValue
./ncgen/getfill.c:      _FillValue, then create one based on the variable's basetype.
./ncgen/ncgeny.c:                derror("_FillValue: must be a single (possibly compound) value",
./ncgen/ncgeny.c:                derror("_FillValue attribute not associated with variable: %s",vsym->name);
./ncgen/ncgeny.c:                derror("_FillValue attribute type does not match variable type: %s",vsym->name);
./nc_perf/tst_ar4_4d.c:		thetao:_FillValue = 1.e+20f ;
./nc_perf/tst_ar4_3d.c:		pr:_FillValue = 1.e+20f ;
./nc_perf/tst_ar4.c:		pr:_FillValue = 1.e+20f ;
./libdap2/ncd2dispatch.c:	                    nclog(NCLOGWARN,"_FillValue/Variable type mismatch: variable=%s",var->ncbasename);
./libnczarr/zvar.c:	retval = NCZ_del_att(ncid, varid, _FillValue);
./libnczarr/zvar.c:	if ((retval = nc_put_att(ncid, varid, _FillValue, var->type_info->hdr.id,
./libnczarr/zvar.c:        retval = NCZ_del_att(ncid, varid, _FillValue);
./libnczarr/zattr.c:     * struct for this var. (But ignore a global _FillValue
./libnczarr/zattr.c:    if (!strcmp(att->hdr.name, _FillValue) && varid != NC_GLOBAL)
./libnczarr/zattr.c:	    if(strcmp(fv->hdr.name,_FillValue)==0) break;
./libnczarr/zattr.c:	    if((stat = ncz_makeattr((NC_OBJ*)var,var->att,_FillValue,var->type_info->hdr.id,1,var->fill_value,&fv)))
./libnczarr/zinternal.c: * Side effects: set as default if necessary and build _FillValue attribute.
./libdap4/d4meta.c:	        FAIL(NC_EBADTYPE,"_FillValue/Variable type mismatch: %s:%s",container->name,attr->name);
```

<img width="637" alt="7_1_3_ReservedIdentifiers" src="https://github.com/Unidata/netcdf-c/assets/389869/22000606-119f-45a2-9b0e-dfd136f8a24a">

**Comment by DennisHeimbigner** [comment]
So in summary, you are saying we should not use _FillValue as a C identifier, correct?

**Comment by schwehr** [comment]
> So in summary, you are saying we should not use _FillValue as a C identifier, correct?

That is my reading of the spec. Either drop the `_` or add a prefix.

The minimum change that would work is likely to just change the macro here:

https://github.com/Unidata/netcdf-c/blob/fb40a72b45266d16fa1a0e8b4d04e0f107b45183/include/netcdf.h#L113

**Comment by DennisHeimbigner** [comment]
Unfortunately, this may cause problems for users who use this \#define.
It is part of netcdf.h, which defined the public API for the netcdf-c library.
I think that for the moment, the best we can do is add
> \#define NC_FillValue "_FillValue"

and add a comment that _FillValue is deprecated.
Then we can modify our code to not use _FillValue.

**Comment by WardF** [comment]
This is not a change we will make overnight or without copious discussion. _FillValue has been a part of the netCDF spec for a very long time. Changing that will not be something we can do overnight.

**Comment by WardF** [comment]
Particularly given the decades of archival data that already exists, any approach we take will have to accommodate reading those without issue. At the very least, we would need to publish a new spec, which will require a lot of Yak shaving that's already on our plate. In terms of collating existing info and making sure it's all up to date, as well as developing a standardized process for developing and publishing a new spec. So, this is definitely good info to have, but it's ... uff-dah. It's going to be a whole thing.

**Comment by schwehr** [comment]
As a member of the PROJ and GDAL communities, I understand that this is a complexity change and the need for not breaking things. I'm currently under pressure to quickly patch around this for my org (Google / Alphabet). I'm was thinking of doing an NC_FillValue patch to the local google3 code base (and the same fix for HDF4).  Any other tips on this kind of change? We use bazel for building, so I'll handle the config changes on my own. When I have it working, I can report back about how the transition went. I'd like to stay close to the same solution that ends up in the public repo as carrying custom patches is a big maintenance burden.

**Comment by DennisHeimbigner** [comment]
When you build, do you actually get an error from the compiler, or does it just generate a warning, or what?

**Comment by WardF** [comment]
I will need to look at this closer. The spec appears to refer to variable names/identifiers, which would be easy enough to change. The special attribute "_FillValue" contained in a netCDF dataset is a non-issue (as are the strings in comments in the code), as they are code being compiled, and are not subject to the spec. 

I will take a closer look at this when I return to the office tomorrow afternoon, but the only thing we will need to consider changing would be declared variables in code with a leading underscore followed by a capital letter, '_F' in this case. There is no need to change the reserved netCDF attribute "_FillValue".

**Comment by WardF** [comment]
Which is to says, now that I'm caught up, what you originally said @DennisHeimbigner :)

**Comment by schwehr** [comment]
Turns out that our specific issue was just in HDF4.  See here:

https://github.com/HDFGroup/hdf4/issues/419#issuecomment-1664302504

Yes, changing what is in the string should not need to change. I think it probably would be better to avoid `_[A-Z][_a-zA-Z]`, but need is less than I originally thought.

**Comment by derobins** [comment]
The HDF4 API is full of symbols with leading underscores. Changing this is probably beyond what I can reasonably get away with. I can't prioritize compiler warnings over breaking everyone else's code. Heck, I can't even get rid of the VOID declarations without breaking critical code.

**Comment by DennisHeimbigner** [comment]
Resolved

**Comment by DennisHeimbigner** [comment]
Resolved
