### ISSUE TITLE
nc_open "Abort" crash on a corrupted netCDF classic file

### ISSUE THREAD

**Issue by krisfed** [Unidata/netcdf-c#2731]
Hello netCDF folks!

We are seeing the following crash on a corrupted netcdf file (see nctest_classic_corrupted.nc attached in a ZIP file, [nctest_classic_corrupted.nc.zip](https://github.com/Unidata/netcdf-c/files/12290268/nctest_classic_corrupted.nc.zip)):

```
$ ./a.out 
Assertion failed: (extent < X_INT_MAX), function px_get, file posixio.c, line 540.
Abort trap: 6
```
This is on a mac machine, but we see this crash on all platforms.

Here is the code to reproduce the issue:
```C++
#include <iostream>
#include "netcdf.h"

void checkErrorCode(int status, const char* message){
    if (status != NC_NOERR){
        std::cout << "Error code: " << status << " from " << message << std::endl;
        std::cout << nc_strerror(status) << std::endl << std::endl;
    }
}

int main(int argc, const char * argv[]) {
    int ncid;
    int retval;
    
    // open file
    retval = nc_open("nctest_classic_corrupted.nc", NC_NOWRITE, &ncid);
    checkErrorCode(retval, "nc_open");
    
    // close file
    retval = nc_close(ncid);
    checkErrorCode(retval, "nc_close");
    
    return retval;
}

```

I understand that it makes sense that netCDF functionality does not work on a corrupted file, but it would be nice if a crash could be avoided (even when the file is bad).

We are using netCDF-C v4.9.1.

Thanks in advance for taking a look!

Kris

**Comment by DennisHeimbigner** [comment]
Fixed by PR https://github.com/Unidata/netcdf-c/pull/2732

**Comment by krisfed** [comment]
Wow, thank you so much for a speedy response and fix, Ward!

**Comment by krisfed** [comment]
Thanks again for the super-quick action on this! Wanted to check, is there an approximate timeline for the new netCDF release? Trying to evaluate if we should patch this in our netCDF version now or wait till we can upgrade to the new release that will include this fix.

**Comment by WardF** [comment]
No worries and all credit for the fix to @DennisHeimbigner! I don't have a timeline, we are working through some other issues. I'd like to think we will resolve them very quickly but I'd be over-promising. Patching in for now is probably the safest bet :).
