### ISSUE TITLE
netcdf_SO_VERSION mismatch (SONAME) in 4.9.2

### ISSUE THREAD

**Issue by Dave-Allured** [Unidata/netcdf-c#2740]
**netCDF_SO_VERSION** is defined in two places.  In 4.9.2 and earlier, this SO number is mismatched.

configure.ac:
```
# These linker flags specify libtool version info ...
# These values should match those in CMakeLists.txt
AC_SUBST([netCDF_SO_VERSION]) netCDF_SO_VERSION=21:2:2
```
CMakeLists.txt:
```
# These values should match those in configure.ac ...
SET(netCDF_SO_VERSION 19)
```
Please synchronize these for new releases.  If there is some reason to not synchronize, please explain that in the comments.

**Comment by WardF** [comment]
They are synchronized; the autoconf build system uses the numbers provided to calculate an SO. This value is then synchronized to be reflected in the cmake based system. In both systems, the SO (calculated and assigned) is 19.

**Comment by Dave-Allured** [comment]
Thanks for explaining.  My understanding of sonames and compatibility versioning is incomplete.
