### ISSUE TITLE
Possible bug in NcZarr tests

### ISSUE THREAD

**Issue by ZedThree** [Unidata/netcdf-c#2768]
In current `main`, I found the following warning while having a stab at tidying up type conversion warnings:

```
netcdf-c/nczarr_test/test_utils.c: In function ‘getoptions’:
netcdf-c/nczarr_test/test_utils.c:169:8: warning: the comparison will always evaluate as ‘true’ for the address of ‘file’ will never be NULL [-Waddress]
  169 |     if(options->file) {
      |        ^~~~~~~
In file included from netcdf-c/nczarr_test/test_utils.c:27:
netcdf-c/nczarr_test/test_utils.h:33:10: note: ‘file’ declared here
   33 |     char file[1024];
      |          ^~~~
```

Seeing as this is always true, probably solution is to just remove the conditional?

**Comment by DennisHeimbigner** [comment]
This looks like a false positive to me. The options->file field only gets set if *argcp > 0.
The case of *argcp == 0 can occur, I think if the args are all options with no specified file.
Do you agree?
