### ISSUE TITLE
Some netcdf functions are not in the doxygen documentation on-line.

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#277]
Looking at the docs here:
http://www.unidata.ucar.edu/software/netcdf/docs/

The following functions appear to be missing from the doxygen documentation:
nc_inq_unlimids()
nc_def_grp()
nc_inq_ncid()

**Comment by WardF** [comment]
Thanks for pointing those out, I'll get the documentation updated.

**Comment by WardF** [comment]
I'm not finding `nc_inq_unlimids()` anywhere, can you point me to it? Or, did you perhaps mean nc_inq_unlimdims? That would make sense, as the latter isn't documented either (but should/will be).

**Comment by edhartnett** [comment]
Howdy Ward!

Sorry, typed it wrong. I meant this one (from netcdf.h):

/* The next function is for NetCDF-4 only */
EXTERNL int
nc_inq_unlimdims(int ncid, int *nunlimdimsp, int *unlimdimidsp);

This function is necessary because netCDF-4 files can have more than one unlimited dimension.

**Comment by WardF** [comment]
No problem; it's funny, "Fill in documentation for group-related functions" has been languishing on my todo for a while; nice to finally get that and these other things out of the way.

**Comment by DennisHeimbigner** [comment]
Such functions should not appear in netcdf.h; rather
1. thename should be something like NC_inq_unlimdims
2. it should be defined in e.g. ncdispatch.h
=Dennis

**Comment by edhartnett** [comment]
Dennis,

Why should it not appear in netcdf.h? Is it not a fully supported part of the API?

Ed

**Comment by DennisHeimbigner** [comment]
I did not think it was part of the official API.

**Comment by edhartnett** [comment]
I believe it is and should be availabe for all netcdf files. (Though obviously only netcdf4/hdf5 files can have more than one unlimited dimension.)

**Comment by WardF** [comment]
The functions discussed here have been stubbed in in the dev. branch, and I'm looking at toggling the 'warnings' option in the doxygen configuration.  Closing this out for now, will reopen if it looks like I've missed something.
