### ISSUE TITLE
How to quiet verbose "NOTE:" and "WARN:" messages in latest main branch 

### ISSUE THREAD

**Issue by czender** [Unidata/netcdf-c#2773]
Today's main branch configured/compiled/installed on MacOS with

`CC='clang' CPPFLAGS="-I/opt/homebrew/include" LDFLAGS="-L/opt/homebrew/lib -laws-cpp-sdk-s3" ./configure --prefix=/opt/netcdf --enable-shared --enable-cdf5 --enable-dap --enable-logging --enable-netcdf4 --enable-nczarr --enable-s3 --enable-v2 --with-plugin-dir=${HDF5_PLUGIN_PATH}`

produces some unexpected text output (the "NOTE" and "WARN" lines):

```
zender@spectral:~$ ncgen -b -o ${HOME}/nco/data/in.nc ${HOME}/nco/data/in.cdl
NOTE: Found rc file=/Users/zender/.ncrc
NOTE: Found rc file=/Users/zender/.ncrc
WARN: Could not open file: /Users/zender/.aws/credentials
WARN: AWS config file not loaded
zender@spectral:~$ 
```

How can I quiet this output? Or is this some overly verbose code that should be quieted in the netCDF library? This unexpected lines are also now printed by my netCDF clients (NCO).

**Comment by WardF** [comment]
@czender This is some debug output that leaked into the `main` branch, we'll get it removed :).

**Comment by WardF** [comment]
Well, I thought that's what this was.  It looked like output I was seeing unbidden in #2759.  I'm not immediately seeing this when I try to recreate it, however.  Do you have `NCENVLOGGING` and/or `NCENVTRACING` values set, by any chance?

**Comment by czender** [comment]
No, those variables are not set in my environment.

**Comment by WardF** [comment]
@czender That would have been too clear-cut an answer.  Does the same thing happen if you compile without `--enable-logging`? That will at least narrow down if this is debugging output, or something being generated by the logging subsystem.  It appears to be the latter, but since you haven't specified a log level or even enabled logging output, it's puzzling that it would print it out.

**Comment by czender** [comment]
Unfortunately, compiling netCDF without `--enable-logging` did not make any difference. Behavior remains unchanged.

**Comment by WardF** [comment]
That at least narrows it down, thanks!

**Comment by DennisHeimbigner** [comment]
This should be fixed by this PR https://github.com/Unidata/netcdf-c/pull/2767g

**Comment by czender** [comment]
Aaah. Thanks, Dennis. Please merge ASAP :)

**Comment by WardF** [comment]
Merged now.
