### ISSUE TITLE
Byte range fails on GOES 16 URL present in tst_byterange.c

### ISSUE THREAD

**Issue by abhibaruah** [Unidata/netcdf-c#2798]
To report a non-security related issue, please provide:

NetCDF version: 4.9.1
HDF5 version: 1.10.10
OS: Linux

I am trying to use netCDF byte range reading on the GOES16 URL which is mentioned in the file https://github.com/Unidata/netcdf-c/blob/main/nc_test/tst_byterange.c

"https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2017/059/03/OR_ABI-L1b-RadC-M3C13_G16_s20170590337505_e20170590340289_c20170590340316.nc#mode=bytes"

However, nc_open fails with the status code -74.
Is this because of some changes to the netCDF code or changes in the GOES16 server?

```
#include <stdio.h>
#include <string.h>
#include <netcdf.h>
#include <iostream>

#define FILE_NAME "https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2017/059/03/OR_ABI-L1b-RadC-M3C13_G16_s20170590337505_e20170590340289_c20170590340316.nc#mode=bytes"

int
main()
{
    int status;
    int ncid;
    
    // open the NetCDF-4 file
    status = nc_open(FILE_NAME, NC_NOWRITE, &ncid);
    if(status != NC_NOERR) {
         std::cout << "Status: " << status << std::endl;
		 std::cout << "Could not open the file." << std::endl;
		 
    }
   
    // close the file 
    status = nc_close(ncid);
	
	std::cout << "Status after close: " << status << std::endl;

    return 0;
}

```

```
Status: -74
Could not open the file.
Status after close: -33
```

**Comment by dopplershift** [comment]
@abhibaruah Can you try upgrading to netCDF 4.9.2? IIRC, there were some issues fixed in 4.9.1 around the byte range support. This URL worked for me just now with 4.9.2.

**Comment by abhibaruah** [comment]
@dopplershift Thanks for taking a look.
We have plans to upgrade to 4.9.2 soon. 
I wanted to try it by using the prebuilt binaries (for 4.9.2) that you usually upload on your website. However, I could not find the ones for unix based OS. Do you know where I can download them from?

If they are not available, I will wait until we build netcdf 4.9.2 with our build harness and can verify the same.

**Comment by WardF** [comment]
Hi @abhibaruah, we only provide prebuilt libraries for Windows/Visual Studio. For all other platforms, we provide source code or the community-supported installers through the package manager specific to the distribution/platform.

**Comment by abhibaruah** [comment]
No problem Ward.
We will be upgrading to 4.9.2 soon and will let you know if it works for us or not.

**Comment by dopplershift** [comment]
I can confirm the failure with my setup as well. Not sure what's going on.

**Comment by abhibaruah** [comment]
Confirmed that the corrected url works. 
Thanks Dennis for the solution.

**Comment by dopplershift** [comment]
> The problem is that this URL is using the default region, which is us-east-1. 

Is that because we're trying to parse the URL and use some S3 support directly? IMO the original URL should work just fine using our standard byte range support since it's a URL that supports HTTP Byte Range requests. At the very least, is there some way to fall back to that?

**Comment by DennisHeimbigner** [comment]
If you clear cache on your web browser and insert the original URL, you should see an error message
indicating a URL problem. That is how I learned that the dataset was in us-west-2.
Otherwise, I do not understand your comment. When you say, "...use some S3 support directly..."
can you elaborate on this?

**Comment by abhibaruah** [comment]
I tried to set the environment variable 'AWS_DEFAULT_REGION' to 'us-west-2'
% setenv AWS_REGION us-west-2
But the link
"https://nrel-pds-wtk.s3.amazonaws.com/wtk-techno-economic/pywtk-data/met_data/0/0.nc#mode=bytes"
still fails.
Shouldnt the AWS default region have changed to us-west-2 and this link work?

**Comment by DennisHeimbigner** [comment]
I must be interfering with the URL somewhere and forgot that I did it. Setting the default region (above) should have worked.
Let me investigate.

**Comment by WardF** [comment]
I'm taking a look at #2819 that Dennis put up in support of this, but would appreciate additional eyes/comments, given that we don't have direct access to an Amazon Appliance for testing.

**Comment by krisfed** [comment]
I just wanted to confirm that after upgrading to v4.9.3, the above link ("https://nrel-pds-wtk.s3.amazonaws.com/wtk-techno-economic/pywtk-data/met_data/0/0.nc#mode=bytes") works as-is. I didn't need to set `AWS_REGION` or `AWS_DEFAULT_REGION` to `us-west-2`or to modify the url to contain `us-west-2`.  Is that expected?

**Comment by DennisHeimbigner** [comment]
I think there is some confusion here. ncdump must have a region (unless it is us-east-1).
So the region must be in either the URL, or in the variables AWS_REGION or AWS_DEFAULT_REGION,
or in the default profile.
Did we say something that led you to think otherwise?

**Comment by krisfed** [comment]
Thank you for a quick response!

No, I was just trying to see how this behaves after the upgrade to v4.9.3. I tried the same link ("https://nrel-pds-wtk.s3.amazonaws.com/wtk-techno-economic/pywtk-data/met_data/0/0.nc#mode=bytes") without setting AWS_REGION or AWS_DEFAULT_REGION and expected it to error, but it worked. I was surprised, so just wanted to clarify if that's expected or if I am missing something (e.g. if some automatic region detection was added...).

It helps to confirm that this is indeed unexpected. Can the region be picked up from a different env variable or elsewhere? From my limited understanding, some public buckets can allow access via global endpoint, so maybe that could be why it is working without region specified?

This is what I get with ncdump using v4.9.3
```
$ echo $AWS_REGION

$ echo $AWS_DEFAULT_REGION

$ ./ncdump -h https://nrel-pds-wtk.s3.amazonaws.com/wtk-techno-economic/pywtk-data/met_data/0/0.nc#mode=bytes
netcdf \0 {
dimensions:
	time = UNLIMITED ; // (736416 currently)
variables:
	float wind_speed(time) ;
<..snip..>
```
The same link still errors with v4.9.2 (unless I use the version of the link with the region: https://nrel-pds-wtk.s3.us-west-2.amazonaws.com/wtk-techno-economic/pywtk-data/met_data/0/0.nc#mode=bytes )

**Comment by DennisHeimbigner** [comment]
You must be specifying the region somehow.
The region might be specified thru the following places:
1. env. var AWS_REGION
2. env var AWS_DEFAULT_REGION
3. $HOME/.aws/config: field "aws_region"
4. $HOME/.aws/credentials: field "aws_region"

Can you verify what values you have for those locations?

**Comment by krisfed** [comment]
The env vars are not set and I don't have the AWS config/credentials files (see below).. When you try this on your side, are you able to reproduce the same behavior?

```
$ cat $HOME/.aws/config
cat: <..snip..>/.aws/config: No such file or directory
$ cat $HOME/.aws/credentials
cat: <..snip..>/.aws/credentials: No such file or directory.
$ echo $AWS_REGION

$ echo $AWS_DEFAULT_REGION

$ ./ncdump -h https://nrel-pds-wtk.s3.amazonaws.com/wtk-techno-economic/pywtk-data/met_data/0/0.nc#mode=bytes
netcdf \0 {
dimensions:
	time = UNLIMITED ; // (736416 currently)
variables:
	float wind_speed(time) ;
<..snip..>
```

**Comment by dopplershift** [comment]
@DennisHeimbigner Can't this just be using the byte-range support?

**Comment by DennisHeimbigner** [comment]
I stand corrected -- and mystified.
First, I did not realize that the above url references a netcdf-classic (netcdf-3) dataset.
I mistakenly thought it referenced an HDF5/netcdf-4 file. So I was looking at the HDF5 H5FDros3
when in fact it was using libcurl directly.
Second, I am mystified as to how the dataset can be accessed without specifying a region.
But apparently it can. The question I now need to answer is if a region is ever needed.
It may be that the bucket name alone is sufficient.
