### ISSUE TITLE
tst_specific_filters.sh fails from "Testing processing of filter blosc for map nc 10c10" for 4.9.2

### ISSUE THREAD

**Issue by bzfbmsch** [Unidata/netcdf-c#2868]
Dear all,
Building netcdf-c 4.92 from source. I downloaded the released tar.gz-file, not the from git. 
The system is openSUSE 15.5, with gcc-11, prerequisites hdf5-14.3 + plugins. The plugins include blosc. 

I am interested to learn more on the deflation tools besides libz and have installed several libraries including their development parts. May be I am a little bit lazy, but I am just using those from the linux distribution openSUSE 15.5. The critical tool is the libblosc, I have version 1.21.1-bp155.2.1.7. I have also build several hdf5-plugins that includes blosc. The plugin is also linked with the system version of libblosc. After configure and make, I end up in make check with the same error like that reported in ticket: https://github.com/Unidata/netcdf-c/issues/2572:

FAIL: tst_specific_filters.sh
...... and in the logfile:

findplugin.sh loaded
*** Testing processing of filter deflate for map nc
*** Testing processing of filter szip for map nc
*** Testing processing of filter bzip2 for map nc
*** Testing processing of filter blosc for map nc
10c10
<               ivar:_Filter = "32001,0,0,4,256,5,1,1" ;
---
>               ivar:_Filter = "32001,2,2,4,256,5,1,1" ;
14c14
<               fvar:_Filter = "32001,0,0,4,256,5,1,1" ;
---
>               fvar:_Filter = "32001,2,2,4,256,5,1,1" ;

Inspired from the discussion found in the ticket, I tried a workaround. I edited tst_specific_filters.sh and changed line 18:

if test "x$TESTNCZARR" = x1 ; then
. "$srcdir/test_nczarr.sh"
BLOSCARGS="32001,0,0,0,256,5,1,1"
BLOSCCODEC='[{\"id\": \"blosc\",\"clevel\": 5,\"blocksize\": 256,\"cname\": \"lz4\",\"shuffle\": 1}]'
else
here>>>>>>>>>>>>>>>>>>>>>
BLOSCARGS="32001,2,2,4,256,5,1,1"  
BLOSCCODEC='[{\"id\": \"blosc\",\"clevel\": 5,\"blocksize\": 256,\"cname\": \"lz4\",\"shuffle\": 1}]'
fi

With this change, the error message was not displayed any more, but I am not sure that the error is really gone. May be, I have added the wrong result as referene. 

Here some more details on the configuration after the configure step:
---->>>>
Shared Library:         yes
Static Library:         yes
Extra libraries:        -lm -lz -ldl -lzip -lsz -lbz2 -lzstd -lblosc -lxml2 -lcurl
XML Parser:             libxml2

# Features
--------
Benchmarks:             no
NetCDF-2 API:           yes
HDF4 Support:           no
HDF5 Support:           yes
NetCDF-4 API:           yes
CDF5 Support:           yes
NC-4 Parallel Support:  no
PnetCDF Support:        no

DAP2 Support:           yes
DAP4 Support:           yes
Byte-Range Support:     yes

S3 Support:             no

NCZarr Support:         yes
NCZarr Zip Support:     yes

Diskless Support:       yes
MMap Support:           yes
JNA Support:            yes
ERANGE Fill Support:    yes
Relaxed Boundary Check: yes

Multi-Filter Support:   yes
Quantization:           yes
Logging:                no
SZIP Write Support:     yes
Standard Filters:       deflate bz2 blosc zstd
ZSTD Support:           yes
Parallel Filters:       yes
----->>>

I am not sure, if this is sufficient for an error report. If needed, I can deliver all details on the compiler and the configure flags. For the moment, any hints for a clean solution are very welcome.

Kind regards,

Martin Schmidt

**Comment by dirteat** [comment]
+1

**Comment by DennisHeimbigner** [comment]
I believe the problem is that the parameters for libblosc differ.
I am not entirely sure who is responsible for the differences: HDF5, OS (e.g. opensus vs ubuntu), or libblosc.
Perhaps the correct thing to do is to effectively ignore those two differing parameters since they are not
really important. I will investigate.

**Comment by DennisHeimbigner** [comment]
See PR https://github.com/Unidata/netcdf-c/pull/3046
