### ISSUE TITLE
NetCDF build commands should include ZLIB

### ISSUE THREAD

**Issue by cwardgar** [Unidata/netcdf-c#291]
docs/install.md gives the following commands to build netcdf:

```
$ # Build and install netCDF-4
$ NCDIR=/usr/local
$ CPPFLAGS=-I${H5DIR}/include LDFLAGS=-L${H5DIR}/lib ./configure --prefix=${NCDIR}
$ make check
$ make install  # or sudo make install
```

However, if zlib wasn't installed in a standard location (I put it in `/opt/zlib-1.2.8`), `make` will fail. Instead, I ended up doing:

```
$ # Build and install netCDF-4
$ NCDIR=/opt/netcdf-4.4.1
$ export CPPFLAGS="-I${ZDIR}/include -I${H5DIR}/include"
$ export LDFLAGS="-L${ZDIR}/lib -L${H5DIR}/lib"
$ ./configure --prefix=${NCDIR}
$ make check
$ make install  # or sudo make install
```

**Comment by cwardgar** [comment]
Also, in the building-libhdf5 section of that same document, I'd appreciate it if you could add a link to our [tweaked configure command](http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/netcdf4Clibrary.html#installation_linux_source_build) for TDS users. [TDS needs a thread-safe version](http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/netcdf4Clibrary.html#thread_safety) and I'm hoping to prevent a few extra TDS admins from shooting themselves in the foot by building the library incorrectly.

**Comment by ZedThree** [comment]
Using the `h5cc` wrapper could solve this, as it should include all the necessary flags to link against HDF5. This is actually what the CMake config does. Setting `CC=h5cc` is probably enough, alternatively, you could use [AX_LIB_HDF5](https://www.gnu.org/software/autoconf-archive/ax_lib_hdf5.html) from the autoconf archive to find `h5cc` and get the flags needed from that.

There is a related problem with the CMake config. It uses `FIND_PACKAGE(ZLIB)` to search for ZLIB, but this could find a different version to the one HDF5 uses. I think the solution there is to either not both searching for ZLIB, or to parse the output of `h5cc -showconfig` to see if it already includes the flags for linking against ZLIB.

I might be able to submit a PR in the next week or two to fix these two issues.

**Comment by cesss** [comment]
As of today, the CMake build procedure fails to detect the need for **zlib** if **HDF5** was built with **zlib** support but without **szip** support. The only way to workaround this build bug is to pass `-DNC_EXTRA_DEPS="z"` when invoking `cmake`.
