### ISSUE TITLE
Cmake build does not honor  CMAKE_INSTALL_MANDIR.

### ISSUE THREAD

**Issue by chrisretusn** [Unidata/netcdf-c#2920]
NetCDF Version:         4.9.2
Host System:            x86_64-Linux-6.6.30
Slackware64-current.
cc (GCC) 13.2.0
cmake version 3.29.2

Current behavior:   When using  -DCMAKE_INSTALL_MANDIR=/usr/man, manpages are place in /usr/share/man
Expected behavior: Manpage placed  in /usr/man

To reproduce, this is my cmake build code:
cmake -B build -Wno-dev -Wno-deprecated \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_CXX_FLAGS_RELEASE="$SLKCFLAGS -DNDEBUG" \
  -DCMAKE_C_FLAGS_RELEASE="$SLKCFLAGS -DNDEBUG" \
  -DCMAKE_INSTALL_DOCDIR=/usr/doc/$PKGNAM-$PKGVER \
  -DCMAKE_INSTALL_MANDIR=/usr/man \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_VERBOSE_MAKEFILE=on \
  2>&1 | tee $OUTPUT/cmake.log
cmake --build build -j $NUMJOBS 2>&1 | tee $OUTPUT/build.log
DESTDIR=$PKGDIR cmake --install build --strip 2>&1 | tee $OUTPUT/install.log

**Comment by WardF** [comment]
Thanks, I'll get this fixed!

**Comment by chrisretusn** [comment]
Verified at my end!
