### ISSUE TITLE
Error in the cmake provided FindHDF5.cmake

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#2932]
The version number in H5pubconf.h has changed (as of HDF5 1.14.x) to include
four numbers instead of the 3 numbers plus "-patch".
This causes the cmake provided FindHDF5.cmake to fail.
Attached is a replacement for ```...cmake-3.29.0/Modules/FindHDF5.cmake````
with a minimal patch. This "-patch" issue may occur elsewhere in the
FindHDF5.cmake file, but this one change was sufficient to get it working for me.

This probably needs to be reported to HDF5 group and/or Cmake maintainers.
Not sure who maintains the FindHDF5.cmake file.
[FindHDF5.cmake.txt](https://github.com/Unidata/netcdf-c/files/15462282/FindHDF5.cmake.txt)

**Comment by WardF** [comment]
Can you link to the issue you mentioned on the cmake website? I'm having problems replicating the underlying issue, and want to understand exactly what's happening, in addition to incorporating the fix.

**Comment by WardF** [comment]
Which version of hdf5 was the issue being observed with, as well? I've been testing with 1.14.2 and 1.14.3

**Comment by DennisHeimbigner** [comment]
I was using 1.14.4. It may also be in earlier versions.

**Comment by DennisHeimbigner** [comment]
The kitware issue I saw was this;
https://gitlab.kitware.com/cmake/cmake/-/issues/25945

**Comment by gsjaardema** [comment]
I am having a similar issue.  I am able to build if I remove the `${HDF5_VERSION_REQUIRED}` from dependencies.cmake in the `find_package` call near line 137:
```
  #####
  # First, find the C and HL libraries.
  #####
  find_package(HDF5 ${HDF5_VERSION_REQUIRED} COMPONENTS C HL REQUIRED)

  message(STATUS "Using HDF5 include dir: ${HDF5_INCLUDE_DIRS}")
  target_link_libraries(netcdf
    PRIVATE
    HDF5::HDF5
  )
```
Currently `HDF5_VERSION_REQUIRED` is set to 1.8.10.  I have tried with 1.14.4.3 and 1.10.11.  I get the following error:
```
CMake Error at /opt/homebrew/Cellar/cmake/3.29.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_HL_LIBRARIES) (found
  suitable version "1.10.11", minimum required is "1.8.10")
```

**Comment by gsjaardema** [comment]
Current cmake -- 3.29.6 on a Mac system

**Comment by gsjaardema** [comment]
I tried the WardF/netcdf-c branch v4.9.3-rc1-prep.wif and get the same problem finding HDF5 as shown below.
```
CMake Error at /opt/homebrew/Cellar/cmake/3.29.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_HL_LIBRARIES) (found
  suitable version "1.14.4.3", minimum required is "1.8.10")
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.29.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.29.6/share/cmake/Modules/FindHDF5.cmake:1025 (find_package_handle_standard_args)
  cmake/dependencies.cmake:137 (find_package)
  CMakeLists.txt:907 (include)
```
If I remove the `HDF5_VERSION_REQUIRED` from dependencies.cmake in the `find_package` call, it finds the correct HDF5 installation...
```
  find_package(HDF5 COMPONENTS C HL REQUIRED)

  message(STATUS "Using HDF5 include dir: ${HDF5_INCLUDE_DIRS}")
  target_link_libraries(netcdf
    PRIVATE
    HDF5::HDF5
  )
```
Config output:
```
-- Found HDF5: hdf5-shared (found version "1.14.4") found components: C HL
-- Using HDF5 include dir: /Users/gdsjaar/src/seacas/include
```

**Comment by WardF** [comment]
Thanks for the fix, I was never able to replicate this in practice, despite seeing the logic that might have resulted in it. Thanks!
