### ISSUE TITLE
we seem to have lost zstandard tests

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#2938]
I know that at one time there was a zstandard test.

But now it is not present. Not sure where it went. But obviously we want to test zstandard.

**Comment by DennisHeimbigner** [comment]
Odd. By any chance can you remember a release that had it? Or remember its name?
If so, we can probably find and restore it.

**Comment by WardF** [comment]
I'll take a look now that I've got the zip issue fixed.
