### ISSUE TITLE
nccopy fails in a particular case related to dimension variable.

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#295]
Initially reported via e-support:

---

if a dimension name and a variable name are the same, nccopy will generate an error.
This does not appear to be a problem with netcdf-4/hdf files we are generating programmatically.

We started to observe the following error with 
- hdf5-1.8.10-linux-x86_64 
- netcdf-4.3.3.1

and found it is still present when we tested with:
- hdf5-1.10.0-patch1-linux-centos6-x86_64-gcc447-shared
- netcdf-4.4.1

(prior to netcdf-4.3.3.1 we were just netcdf-3, so I can't comment on when
the problem may have started)

Given the following CDL (afile.cdl):

netcdf afile {
dimensions:
     elapsed_time = UNLIMITED ; // (1 currently)
     aName = 4 ;
variables:
     double aName(elapsed_time, aName) ;

// global attributes:
data:

  aName =
   1, 2, 3, 4 ;

}

ncgen -4 -o afile.nc afile.cdl

nccopy -4 afile.nc afile2.nc

generates the following error:

NetCDF: Index exceeds dimension bound
Location: file nccopy.c; line 1045

if the cdl is more complicated, it still generates an error, but the error
changes to:

NetCDF: HDF error
Location: file nccopy.c; line 1045

If instead of generating a netcdf-4 file with ncgen, we back down to netcdf-3,
using nccopy to create a netcdf-4 version of the file will work. However copying that
netcdf-4 file will (not surprisingly) generate the error.

All of this was discovered when we wanted to retroactively compress existing netcdf-4
files via nccopy.

I did take a quick look at nccopy, but was not able to see anything obvious about why
nccopy would be having a problem.  I went back a couple of years in the netcdf support
archive and didn't see anything that would appear to be relevant to this.

**Comment by WardF** [comment]
Note to self: failing at `libsrc4/nc4hdf.c:628`.  Need to sort out the context so I can determine if the check that's failing can be modified.

**Comment by WardF** [comment]
The issue appears to be related to an error code thrown by `H5DWrite` at `libsrc4/nc4hdf.c:816`.

**Comment by WardF** [comment]
Recalling that `-5` is 64-bit offset, the following works:

    $ ./nccopy -5 gh295.nc tmp.nc
    $ ./nccopy -4 tmp.nc gh295-2.nc

Where 
    
    $ ./nccopy -4 gh295.nc gh295-2.nc 

fails.

**Comment by WardF** [comment]
Re: the call to `h5Sget_simple_extent_dims` at `libsrc4/nc4hdf.c:613`, ensure what we expect the size of `fdims[1]` to be.  Shouldn't it be 4?

**Comment by WardF** [comment]
Ok, the issue appears to be when writing the file via `ncgen`, the dimension data is being written to `_nc4_non_coord_aName` instead of to `aName`, but `aName` is being queried by h5Sget_simple_extent_dims.

**Comment by RMShectman** [comment]
On your comment from two days ago, did you mean nccopy as opposed to ncgen?

**Comment by WardF** [comment]
Using `ncgen` to generate the binary file (as outlined above) from the CDL and then using `h5dump` to inspect the generated file shows results in the observation from 2 days ago.

**Comment by WardF** [comment]
note to self: ncdump is working properly; the call to `h5Sget_simple_extent_dims()` (in the 900s) invoked by ncdump returns the values expected, unlike the call referenced above, at 613.  See `gdb_ncdump.txt` for specific line number.

**Comment by WardF** [comment]
From a conversation with Russ Rew, we are working with **Auxiliary Coordinate Variables**.  Here is some information that can be used for determining what *should* happen:

* [Definition of a trajectory variable from the CDF 1.6.0 convention](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#_multidimensional_array_representation_of_trajectories)

Note that all the examples provided in that link place the dimension with the shared named *first*.  This is different from the CDL above.  We already know the CDL can be modified to place `aName` first, but this then requires reshaping the associated data.  

The question remains, is this valid or not; I'm still not certain. Also, ncgen *will* create the file just fine.  It's nccopy that is having the problem.  It seems like nccopy should copy anything that ncgen creates.

**Comment by WardF** [comment]
TODO: update logging to capture/print the various hdf-related id's to ensure things are being consistent.

**Comment by WardF** [comment]
Neither dimension is being flagged as a coordinate variable, which makes sense but it supports the notion that this may not be supported.

**Comment by jdemaria** [comment]
Hi,

I recently fell also into this issue.
My case is easily reproducible :

```
cat bug_nccopy.cdl

netcdf bug_nc {
dimensions:
	a = 1 ;
	b = 2048 ;
variables:
	float b(a, b) ;
		b:_Storage = "chunked" ;
		b:_ChunkSizes = 1, 2048 ;
}

ncgen bug_nccopy.cdl -o bug_nccopy.nc
```

then with NetCDF v4.2 nccopy works, but with v4.7.4 I get this error:
```
NetCDF: Index exceeds dimension bound
Location: file nccopy.c; line 1618
```

I found several things which "solve" the crash:
- remove chunking
- set chunksize < 2048 for the second dimension ; in fact it seems that the crash happens when the product of all _ChunkSizes dimensions >= 8192 bytes because for example a = 2 with b = 1024 crashs too but with 1023 there is no crash. Is 8192 an internal default chunk cache (or other) limit?
- reverse the dimensions order from float b(a, b) to float b(b, a)
- remove dimension a

So for me it seems it is a real regression in nccopy. Or if this kind of variable is invalid ncgen must raise an error.

Thanks in advance,
Julien

**Comment by WardF** [comment]
Thanks for reporting this. I’ve been out of the office but will be back tomorrow and will look at this. You mention a crash and post an error message; is there a crash after the error is reported, or does it exit after reporting the issue? I will check for myself once I am able to shit down at my computer. Thanks!

**Comment by jdemaria** [comment]
Thanks for quick answer. Sorry there is no crash in fact, just the error message then the exit status is 1. Thanks!

**Comment by WardF** [comment]
So I'm trying to duplicate the issue with v4.7.4 and HDF5 1.10.6, and I saw a different issue with the syntax you were using.  Instead of the error message you report, I got the error `ncgen: only one input file argument permitted`.  When I modified the command as follows:

    $ ./ncgen -o bug.nc bug.cdl

I generated the binary netcdf file (attached) without error.  What happens if you modify your ncgen syntax?

*  [bug.nc.zip](https://github.com/Unidata/netcdf-c/files/5131247/bug.nc.zip)

**Comment by jdemaria** [comment]
Sorry if I was not clear, it's not ncgen which produces an error but nccopy. ncgen is just used to generate the file that will crash nccopy. Now try this nccopy command (v4.7.4) on your bug.nc:
```
nccopy bug.nc bug_copy.nc
```
and you will have the error.

**Comment by WardF** [comment]
Thanks; I'm able to recreate this, and am investgating.

**Comment by DennisHeimbigner** [comment]
You might set the environment variable
export NETCDF_LOG_LEVEL=0
then run the command and see if there are any meaningful
HDF5 errors.

**Comment by jdemaria** [comment]
Hi, I tried to export NETCDF_LOG_LEVEL=0 but got no more error details.

**Comment by DennisHeimbigner** [comment]
Ok, that probably means that there are no errors at the HDF5 level.
