### ISSUE TITLE
nc-config may report wrong paths when using CMake installation 

### ISSUE THREAD

**Issue by reuterbal** [Unidata/netcdf-c#2954]
* netCDF Version
```
$ nc-config --version
netCDF 4.9.2
```

* Environment:
```
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterprise
Description:    Red Hat Enterprise Linux release 8.8 (Ootpa)
Release:        8.8
Codename:       Ootpa
$ cmake --version
cmake version 3.20.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

* Issue:

When using CMake to build and install NetCDF, the `nc-config` utility may report wrong paths if the installation prefix is only provided at install time, not at configure time:

Correct:

```
cmake <path/to/source> -DHDF5_DIR=${HDF5_ROOT}/cmake -DCMAKE_INSTALL_PREFIX="${NETCDF_INSTALL_DIR}"
cmake --build . --config Release
cmake --install .
```
In this case, `nc-config` reports the correct path (prefix substituted by ${NETCDF_INSTALL_DIR}):
```
$ nc-config --libs
-L${NETCDF_INSTALL_DIR}/lib64 -lnetcdf
```

Wrong (but valid CMake installation procedure):

```
cmake <path/to/source> -DHDF5_DIR=${HDF5_ROOT}/cmake
cmake --build . --config Release
cmake --install . --prefix "${NETCDF_INSTALL_DIR}"
```
In this case, `nc-config` reports the system-default installation prefix despite being installed elsewhere:
```
$ nc-config --libs
-L/usr/local/lib64 -lnetcdf
```

I suppose there is some templating happening that should not take place at configure/generator/build time but instead be deferred to install time.

**Comment by WardF** [comment]
Thank you for submitting this; you are correct about what is happening.  I'll take a look to see how this should be handled.

**Comment by WardF** [comment]
After some investigation, there is no clear way to run `configure_file()` at `install` time, outside of some convoluted hacks or scripting, and even that rapidly became overly complicated.  Unfortunately, for the time being, specifying `-DCMAKE_INSTALL_PREFIX` at configure time is probably going to be the best way, as long as you specify the same argument you pass to `cmake --install . --prefix`.  As always, PR's welcome!

**Comment by reuterbal** [comment]
Indeed, seems tricky and looks like an overlooked requirement on CMake's side. I wasn't aware that this isn't possible. Thanks for looking into this! 

For anyone who finds this in the future, I'll leave here a link to the open ticket in the Kitware issue tracker: https://gitlab.kitware.com/cmake/cmake/-/issues/24887

**Comment by WardF** [comment]
Thank you very much!

**Comment by WardF** [comment]
Thank you very much, I'll be following that issue! Seeing that we can do this at install time, it would be nice to accommodate users who do that as part of their workflow. Thanks!
