### ISSUE TITLE
Unable to build netcdf-c with pnetcdf using NVHPC

### ISSUE THREAD

**Issue by lcebaman** [Unidata/netcdf-c#2955]
* Tested versions: Netcdf-C 4.9.2 , 4.8.1
* Compiler: latest version of NVHPC (23.11)

* Issue: netcdf-c cannot be built with pnetcdf (`--enable-pnetcdf`):

```bash
CPPFLAGS="-I${extdir}/include" LDFLAGS="-L${extdir}/lib" LIBS="-lhdf5_hl -lhdf5 -lz" ../configure --prefix=${extdir} --enable-pnetcdf --disable-libxml2
```

* Error:
```bash
/bin/sh ../libtool  --tag=CXX   --mode=link mpicxx -std=c++11 -fPIC -O3 -march=core-avx2  -L~/GPU/libs/lib -o libncxml.la  ncxml_tinyxml2.lo tinyxml2.lo  -lpnetcdf -lm -lbz2 -lzstd -lcurl -lhdf5_hl -lhdf5 -lz
/usr/bin/grep: /libmpi_usempif08.la: No such file or directory
/usr/bin/sed: can't read /libmpi_usempif08.la: No such file or directory
libtool:   error: '/libmpi_usempif08.la' is not a valid libtool archive
make[2]: *** [Makefile:536: libncxml.la] Error 1
```

**Comment by WardF** [comment]
This looks to be an issue outside of netcdf; it is referencing `/libmpi_usempif08.la`, and it is unlikely that this file exists at the root of the filesystem. Do you have the `config.log` generated when you run `configure`?

**Comment by edwardhartnett** [comment]
You need to build with the MPI compilers and include "use mpi" in your fortran code.

This does not look like a netCDF issue and should be closed.

**Comment by WardF** [comment]
Closing as I suspect @edwardhartnett is right, and no additional information has been forthcoming.
