### ISSUE TITLE
questions about script findplugin.sh

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#2972]
Related to #2348

We have: ./plugins/findplugin.in

This is turned into findplugin.sh by configure and  gets copied to multiple directories during the build by configure.ac:

```
for FP in plugins nc_test4 nczarr_test examples/C ; do
AC_CONFIG_FILES(${FP}/findplugin.sh:plugins/findplugin.in, [chmod ugo+x ${FP}/findplugin.sh])
done

```

And this results in:

```
find . -name "findplugin.sh"
./nc_test4/findplugin.sh
./examples/C/findplugin.sh
./nczarr_test/findplugin.sh
./plugins/findplugin.sh

```

findplugin is called from multiple test scripts, for example nc_test4/tst_filter_vlen.sh:

```
# Load the findplugins function
. ${builddir}/findplugin.sh
echo "findplugin.sh loaded"

findplugin h5deflate
echo "HDF5_PLUGIN_DIR=$HDF5_PLUGIN_DIR"
```

We clean these in our Makefile.am files:

```
find . -name Makefile.am |xargs grep findplugin
./nc_test4/Makefile.am:DISTCLEANFILES = findplugin.sh run_par_test.sh
./examples/C/Makefile.am:DISTCLEANFILES = findplugin.sh
./nczarr_test/Makefile.am:DISTCLEANFILES = findplugin.sh ${BUILT_SOURCES}
./plugins/Makefile.am:EXTRA_DIST = CMakeLists.txt findplugin.in
./plugins/Makefile.am:DISTCLEANFILES = H5Znoop1.c H5Znoop2.c ncjson.h findplugin.sh

```

Is there any documentation for this? If not, I can prepare some, once I understand it.

@DennisHeimbigner seems like all the plugin directory information should be available at configure-time. Why then have a script to find it at run-time?

**Comment by DWesl** [comment]
Three of the four versions of `findplugin.sh` look like they are for tests, which might be run before installing the plugins to the location determined at build-time
