### ISSUE TITLE
Creating new variable with partially filled unlimited dimension creates RuntimeError: Bad chunk sizes.

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf-c#299]
see https://github.com/Unidata/netcdf4-python/issues/566 for more details.

**Comment by WardF** [comment]
I missed this one; as with the other C issue you created, resource constrained but will address ASAP! Working on #295 at the moment.

**Comment by jswhit** [comment]
No problem - I just didn't want it to get lost.

**Comment by Lnaden** [comment]
I'd like to also bump this issue as we are having the same problem on our packages as well. We would like to use variable creation on the same dimension post writing to another variable, and with chunk sizes > 1. The simple test case from the original post recreates our problem exactly and the block of code [pointed out recently on the original post](https://github.com/Unidata/netcdf4-python/issues/566#issuecomment-343780187) appears to be where the check is.

I'm not good with C++, so bear with me here, but I think if [this line](https://github.com/Unidata/netcdf-c/blob/98dd736a40a9ffae67e2ba9d13ae8bd1b38ce3bd/libsrc4/nc4var.c#L1081) is changed from 
`if(var->dim[d]->len > 0 && chunksizes[d] > var->dim[d]->len)`
to
`if(! var->dim[d]->unlimited && var->dim[d]->len > 0 && chunksizes[d] > var->dim[d]->len)`
that would remove this error, but I'm not sure if there are problems with chunking a dimension differently on 2 different variables post writing data to one of the variables.
