### ISSUE TITLE
_NCProperties attribute is a fixed length string of size 8192

### ISSUE THREAD

**Issue by shoyer** [Unidata/netcdf-c#300]
```
$ h5dump empty-4.4.1.nc
HDF5 "empty-4.4.1.nc" {
GROUP "/" {
   ATTRIBUTE "_NCProperties" {
      DATATYPE  H5T_STRING {
         STRSIZE 8192;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "version=1|netcdflibversion=4.4.1|hdf5libversion=1.8.17"
      }
   }
}
}
```
vs
```
$ h5dump empty-4.4.0.nc
HDF5 "empty-4.4.0.nc" {
GROUP "/" {
}
}
```

This means that an empty netCDF4 file is 8428 bytes with netCDF v4.4.1, versus only 239 bytes with netCDF v4.4.0, which seems like quite a bit more space than necessary.

**Comment by DennisHeimbigner** [comment]
Fair enough. I will attempt to use malloc to reduce the space needed in the file.

**Comment by WardF** [comment]
The pull request appears to be in order; merging shortly.

**Comment by WardF** [comment]
Closed prematurely; need Windows test to finish then will close.
