### ISSUE TITLE
Misleading documentation note for NC_FORMATX_NCZARR

### ISSUE THREAD

**Issue by sval-dev** [Unidata/netcdf-c#3007]
* the version of the software with which you are encountering an issue
Current main

* a description of the issue with the steps needed to reproduce it

The [documentation](https://github.com/Unidata/netcdf-c/blob/411f791dcaf5c8dc87f2cba20cb2aeea86917f41/include/netcdf.h#L199) for the NC_FORMATX_NCZARR states that it was "Added in version 4.3.1", however that is not accurate.
Instead, NC_FORMATX_ZARR was added in 4.3.1, and then the NC_FORMATX_ZARR symbol was renamed to NC_FORMAT_NCZARR released as part of 4.8.0 (renamed in [59e04a](https://github.com/Unidata/netcdf-c/commit/59e04ae0712a59688e5ae80dfbe7fc4c295d2826)).

This issue surfaced since version 1.7.1post2 of the python module uses this symbol, and version 4.7.0 of the C library was on the system, but we got:
`external/nc_complex/src/nc_complex.c:637:21: error: ‘NC_FORMATX_NCZARR’ undeclared (first use in this function)`

Looking up the symbol suggested it was introduced in 4.3.1, and given that 4.7.0 was on the system led to some confusion.

**Comment by WardF** [comment]
Thanks! I will update the documentation to reflect this!
