### ISSUE TITLE
netcdf-c make check, fail run_chunkcases.sh

### ISSUE THREAD

**Issue by wannh2** [Unidata/netcdf-c#3026]
I'm trying to install netcdf-c 4.9.2, but has an error when use 'make check'

![image](https://github.com/user-attachments/assets/59a2c0ad-23fc-4657-8c71-e43fe9b65644)
I have installed zlib-1.2.11 and hdf5-1.14.4-3, Here are the command

export CC=pgcc
export FC=pgfortran
export CXX=pgC++
export F77=pgfortran 
export CFLAGS="-O3"  

cd zlib-1.2.11
./configure --prefix=/mnt/work/wannh/build_megan/library/netcdf_pg/Build_WRF/LIBRARIES/zlib/
make check
make install
#set env
export ZLIB=/mnt/work/wannh/build_megan/library/netcdf_pg/Build_WRF/LIBRARIES/zlib/
export PATH=$ZLIB/bin:$PATH
export ZLIB_LIB=$ZLIB/lib
export ZLIB_INC=$ZLIB/include
export LD_LIBRARY_PATH=$ZLIB/lib:$LD_LIBRARY_PATH 

cd hdf5-1.14.4-3
./configure --with-zlib=/mnt/work/wannh/build_megan/library/netcdf_pg/Build_WRF/LIBRARIES/zlib/ --prefix=/mnt/work/wannh/build_megan/library/netcdf_pg/Build_WRF/LIBRARIES/hdf5/ --enable-fortran 
make
make check
here I got error 'Testing hard signed char -> long double conversions    Command terminated by signal 11'
I saw on github say it's fixed in develp https://github.com/HDFGroup/hdf5/wiki/Known-Issues#autotools 

so I contiune to the command
make install
make check-install
it passed, and 'h5cc --showconfig" works and return hdf5 package information, 

but for netcdf-c
CPPFLAGS=-I/mnt/work/wannh/build_megan/library/netcdf_pg/Build_WRF/LIBRARIES/hdf5/include 
LDFLAGS=-L/mnt/work/wannh/build_megan/library/netcdf_pg/Build_WRF/LIBRARIES/hdf5/lib 
./configure --prefix=/mnt/work/wannh/build_megan/library/netcdf_pg/Build_WRF/LIBRARIES/netcdf/ 
make check

then it shows error in above figure, I attached config.log and test-suite.log, I  saw some errors in config.log, looks like related to hdf5, any suggestions for this? Thank you in advance.
[test-suite.log](https://github.com/user-attachments/files/17034524/test-suite.log)
[config.log](https://github.com/user-attachments/files/17034525/config.log)

**Comment by WardF** [comment]
It looks like this is an issue with hdf5 1.14.4; you'll need to install their `develop` branch, or wait for the next release.
