### ISSUE TITLE
Build failure of netCDF daily snapshot and HDF5 1.8.17

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#303]
Building on vanilla fedora box. Using mpich 3.2. Built HDF5 with:

CC=mpicc ./configure --with-zlib=/usr/local --prefix=/usr/local --with-szlib=/usr/local --enable-parallel

I cloned netCDF-c from github, but this also happened on 4.4.1:

CC=mpicc ./configure --with-zlib=/usr/local --prefix=/usr/local --with-szlib=/usr/local --with-hdf5=/usr/local --enable-pnetcdf --enable-parallel-tests --enable-logging

The test h5_test/tst_h_vars fails on this line:

```
  if (filter != H5Z_FILTER_DEFLATE || cd_nelems != 1 ||
  cd_values[0] != DEFLATE_LEVEL || strcmp(name, DEFLATE_NAME)) ERR;
```

**Comment by WardF** [comment]
I'm unable to duplicate this on my end, but I don't have access to a fedora box.  Are you able to duplicate this in a different environment, assuming there is one handy?

**Comment by edhartnett** [comment]
Do you have the same version of MPICH and HDF5?

This has happened to me on two different fedora systems today. One was a
clean build from scratch of fedora 23, with everything totally up to date.
The other was my laptop, running a several month old fedora.

Thanks,
Ed

**Comment by WardF** [comment]
I'm at the HPC symposium right now so I will double check the version of mpich bundled in the docker environment when I have a chance; whatever version it is, it's the default version for Ubuntu 14.04. I'll follow up here when I can investigate.

**Comment by WardF** [comment]
Current version of mpich in the docker image is 3.0.4; I'll set up a VM and investigate 3.2 when I have some time and decent bandwidth.

**Comment by WardF** [comment]
I've just tested this on Ubuntu 16.04 with mpich 3.2 without error, but my system doesn't have szlib on it yet.  I will install szip shortly for completeness sake; I'd like to sort out this issue if I can just replicate it.

**Comment by WardF** [comment]
Out of curiosity, @edhartnett, and unrelated to this issue.  Can you tell offhand what the default version of cmake is provided by your fedora system? It will help inform #307.

**Comment by edhartnett** [comment]
cmake version 3.5.2

**Comment by edhartnett** [comment]
I am going to go ahead and close this ticket that I opened. The current HEAD is building well with the latest HDF5 with parallel IO, and that's good enough for me. ;-)

**Comment by WardF** [comment]
Sounds good! When you say latest version, do you mean the 1.8.x or 1.10.x branch?

**Comment by edhartnett** [comment]
I mean 1.10.1.
