### ISSUE TITLE
nc-config has wrong entries for static build

### ISSUE THREAD

**Issue by clintpells** [Unidata/netcdf-c#3032]
* netcdf-c-4.9.2
* linux building with static hdf5 static libz
* configure with `./configure --prefix=/blah/blah/build --disable-examples --disable-byterange --disable-libxml2 --enable-mmap --disable-dap --enable-static --disable-shared --enable-netcdf-4`

`./bin/nc-config` --libs results in 
`-L/blah/blah/build/lib -L/blah/blah/build/lib -lnetcdf -lhdf5_hl -lhdf5 -lm -lz -lsz -lzstd`

`./bin/nc-config --libs --static` results in
`-L/blah/blah/build/lib -L/blah/blah/build/lib -lnetcdf -lhdf5_hl -lhdf5 -lm -lz -lsz -lzstd -lhdf5_hl -lhdf5 -lm -lz -lsz -lzstd`

`./bin/nc-config  --static` has no result

None of the -l libraries are available as shared objects, only as static archives.

**Comment by WardF** [comment]
Thanks! I'll take a look and get this resolved.

**Comment by WardF** [comment]
It looks like this has been fixed in `v4.9.3-rc1`, although it requires you to pass `--libs --static`, which I will modify to work with just `--static`.  But the underlying issue appears to have been fixed.
