### ISSUE TITLE
Default _FillVAlue for double (NC_DOUBLE) seems wrong

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [Unidata/netcdf-c#3041]
* the version of the software with which you are encountering an issue

main branch (and going back a while ...)

* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)

All
 
Looking at `netcdf.h`, the default _FillValues for floats are:

```
#define NC_FILL_FLOAT   (9.9692099683868690e+36f) /* near 15 * 2^119 */
#define NC_FILL_DOUBLE  (9.9692099683868690e+36)
```
the float one makes sense, but shouldn't the double one be along the lines of:

1.7976931348623157E+308

(which I got from a Google search)

Or in any case, something with E+308? it makes little sense to use the same value as float.

But while we're at it -- why 9.9692099683868690e+36f ? that doesn't seem to match the maximum value I've seen documented elsewhere:

(in fact, it's about two order of magnitude low! -- E36 rather than E38)

For instance (using numpy).
```
In [6]: np.finfo(np.float32).max
Out[6]: np.float32(3.4028235e+38)

In [7]: np.finfo(np.float64).max
Out[7]: np.float64(1.7976931348623157e+308)
```

This was using numpy, but I'm pretty sure these are the IEE754 values -- I see them all over the web.

Again, while we are at it, the float types have NaN -- wouldn't that be a better default fill value?

Whether it's worth changing any of this now I don't know, but the one for NC_FILL_DOUBLE does seem very wrong.

NOTE: I quick look at the integer values looks OK, though I'm curious why it's using a minimum value for the signed integers, and a maximum for the floats, and maximum for unsigned ints (except char).

Is the reasoning behind this documented somewhere?

**Comment by czender** [comment]
There is some discussion of optimal `_FillValue`'s here: https://stackoverflow.com/questions/43811309/significance-of-netcdfs-fallback-fill-value-for-floats-9-9692099683868690e36/44055587#44055587
I think NaN would be a bad choice for reasons described [here](http://nco.sf.net/nco.html#nan).
FWIW, I like having `NC_FLOAT` and `NC_DOUBLE` use the same number for `_FillValue`. It makes type conversion of variables less error-prone.

**Comment by Dave-Allured** [comment]
This decision for same number for `_FillValue` was made over 20 years ago, back in the days of netcdf2/3.  I do not know the exact history.  However, same number means that you can make endless round trip conversions between float and double, and maintain identical results.  I strongly suspect this was the dominant reason.

Best practice is that for variables ranging anywhere close to this `_FillValue` magnitude, **do not count on the default**, and use an explicit `_FillValue` that is well outside of the data range.

@ChrisBarker-NOAA, please close this ticket if this answer is acceptable and you have no further burning questions about this.

**Comment by ChrisBarker-NOAA** [comment]
For posterity's sake, this is my summary of how the default fill values  for the floating point types were selected:

The fill value for floats is:

9.9692099683868690e+36f 

Which is a number close to the largest value storable in a float that is also a highly compressible bit pattern. 

The value for double is the same as for float, so that data can be converted to/from float and double without losing the fill value.

NaN was not used for floats, as there are complications with software checking for Fill values, a NaN is not equal to any value, even NaN itself, so software would need to handle NaN fill values differently than non-nan fill values.

If this is right, perhaps it would be good to add a note or two to the source, or the NUG? I'd be happy to write a PR if you think that's a good idea.

Other than that, I'm happy -- thanks for the explainations. Closing.
