### ISSUE TITLE
unable to open remote HDF4 file from private S3 bucket

### ISSUE THREAD

**Issue by itcarroll** [Unidata/netcdf-c#3045]
* libnetcdf 4.9.2 from conda-forge
* netcdf4 1.7.2 from pip (with --no-binary netcdf4)
* Ubuntu 22.04.5 LTS

Attempting to read a dataset from an AWS S3 remote raises an `OSError` with message "Malformed URL".
```python
path = "s3://<bucket-name>/test.hdf"
netCDF4.Dataset(f"{path}#mode=bytes", "r")
```
```python
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[5], line 1
----> 1 netCDF4.Dataset(f"{path}#mode=bytes", "r")

File src[/netCDF4/_netCDF4.pyx:2521](https://<hub-domain>/netCDF4/_netCDF4.pyx#line=2520), in netCDF4._netCDF4.Dataset.__init__()

File src[/netCDF4/_netCDF4.pyx:2158](https://<hub-domain>/netCDF4/_netCDF4.pyx#line=2157), in netCDF4._netCDF4._ensure_nc_success()

OSError: [Errno -74] NetCDF: Malformed URL: 's3://<bucket-name>/test.hdf#mode=bytes'
```

I can verify that I have permission to access the bucket and that the target is an HDF4 file.
```python
with fsspec.open(path) as f:
    print([i for i in f.read(4)])
```
```python
[14, 3, 19, 1]  # i.e. HDF4 file signature [0x0E, 0x03, 0x13, 0x01]
```

I can also verify that my installation is able to read a dataset from a different AWS S3 remote
```python
path = (
    "s3://noaa-goes16/ABI-L1b-RadC/2017/059/03/"
    "OR_ABI-L1b-RadC-M3C13_G16_s20170590337505_e20170590340289_c20170590340316.nc"
)
netCDF4.Dataset(f"{path}#mode=bytes", "r")
```
```python
<class 'netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    naming_authority: gov.nesdis.noaa
    ....
```

I grant you, I don't understand all the permissions configuration with AWS S3. I'm on a managed JupyterHub that does not show any credentials file at `~/.aws`. I think it uses a web identity provider.

**Comment by DennisHeimbigner** [comment]
The problem is ours/hdfgroup.
In order to read HDF4 from an S3 object, the HDF4
code needs to have an S3 read driver. As far as I know,
there is no such driver for HDF4. There are a couple of things
you can try:
* Contact the HDF group and as is they can add an S3 driver to the HDF4 code. Once they do that, then I can modify our code to support it.
* Convert the HDF4 file to an HDF5 file and put that up on S3.
