### ISSUE TITLE
nc_get_vara freezes on latest netcdf when not call by all processes

### ISSUE THREAD

**Issue by muralidhar-nalabothula** [Unidata/netcdf-c#3054]
Version : netcdf=4.9.4-development and hdf5=1.14.4
OS        :  MacOS 15.1.1 (hdf5 installed via homebrew, openmpi, apple-clang), EndeavourOS (both netcdf and hdf5 installed via pacman)

As mentioned in the title, in the latest NetCDF/HDF5 versions, ```nc_get_vara``` freezes when it is not called by all processes. This issue does not occur with older versions, tested with( NetCDF 4.7.4/Version 1.10.7.)

Please find attached the necessary files to reproduce the problem.

Thank you

[test_nc.zip](https://github.com/user-attachments/files/17875034/test_nc.zip)

**Comment by edwardhartnett** [comment]
It must be called by all processes.

In the previous release, this was not caught and sometimes worked, but with some MPI libraries less so (IIRC). 

But as clearly stated in the docs, all participating processes must make a call. You can set the count to 0 for processes which have no data to read/write.

**Comment by muralidhar-nalabothula** [comment]
Thanks a lot for the reply. But why does the following work? (Now I am making at least one but unequal number of calls ). 

```
    // make atleast one call
    nc_err = nc_get_vara(ncid, varid, sp, cp, D_mat);
    printf("%d, %f %f \n",my_rank,creal(D_mat[0]), cimag(D_mat[1]));

   // make unequal number of calls.
    if (my_rank)
    {

        ++sp[0]; 
        nc_err = nc_get_vara(ncid, varid, sp, cp, D_mat);
        printf("%d, %f %f \n",my_rank,creal(D_mat[0]), cimag(D_mat[1]));
    }

```

**Comment by edwardhartnett** [comment]
IDK.
