### ISSUE TITLE
Update use of upload-artifact/download-artifact actions

### ISSUE THREAD

**Issue by dopplershift** [Unidata/netcdf-c#3064]
GitHub will be [shutting down](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) v3 of its artifact support in GitHub Actions on 30 January 2025. Here are the relevant places netcdf-c is using the deprecated actions:

* https://github.com/Unidata/netcdf-c/blob/197b4d7d988df86166bb1457ed06628f155d5855/.github/workflows/run_tests_ubuntu.yml#L211
* https://github.com/Unidata/netcdf-c/blob/197b4d7d988df86166bb1457ed06628f155d5855/.github/workflows/run_tests_ubuntu.yml#L306
* https://github.com/Unidata/netcdf-c/blob/197b4d7d988df86166bb1457ed06628f155d5855/.github/workflows/run_tests_ubuntu.yml#L650
* https://github.com/Unidata/netcdf-c/blob/197b4d7d988df86166bb1457ed06628f155d5855/.github/workflows/run_tests_win_mingw.yml#L75

[Here](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md) is GitHub's migration guide for the deprecation.

**Comment by WardF** [comment]
Sounds good, added to the list of things I'll be taking care of.

-Ward
