### ISSUE TITLE
Make ncgen respect case for keywords

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#310]
re: esupport  IUD-363917

For opendap, it is possible to use keywords as identifiers
when there is no ambiguity. However, the DAP2 parser
looses the case of the identifier and always uses the lower
case version. So, fix the parser to track the original case and use it
when a keyword is being used as an identifier.

**Comment by WardF** [comment]
Going through old issues not assigned to a milestone; is this one still open or should it be fixed and/or closed?

**Comment by DennisHeimbigner** [comment]
let me see if this was fixed or what.

**Comment by DennisHeimbigner** [comment]
Fixed by pull request https://github.com/Unidata/netcdf-c/pull/434

**Comment by WardF** [comment]
Excellent thanks Dennis going through the motions to merge it now.
