### ISSUE TITLE
OPeNDAP throws bogus messages with missing files

### ISSUE THREAD

**Issue by Dave-Allured** [Unidata/netcdf-c#314]
### Environment Information

Linux, Mac OSX, presumably all other platforms.
Recent netcdf-C releases through 4.4.1.

### Summary of Issue

When OPeNDAP encounters a file not found condition, client applications print a couple of strange messages, in addition to receiving an expected return code for file not found:

`syntax error, unexpected WORD_STRING, expecting WORD_WORD`
`context: Error { code = 404; message = "Datasets/ncep.reanalysis.dailyavgs/pressure/air.1947.nc"^;};`

These messages are confusing, so I would like to suppress them.   It appears that these messages are not intentional, rather they are due to a problem in the DAP parser.

This is similar to [Jira NCF-218](http://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg11576.html), but that fix is already in recent releases, and it did not fix the current problem with file not found.

I will offer a small patch, once I figure out how this Github thing works.   ;-)

### Steps to reproduce the behavior

Ncdump serves as a simple reproducer:

`ncdump -k http://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/ncep.reanalysis.dailyavgs/pressure/air.1947.nc`

To test the non-error condition, change 1947 to 1948, which is a known good URL on our TDS server.

**Comment by DennisHeimbigner** [comment]
Fix submitted: see https://github.com/Unidata/netcdf-c/pull/315

**Comment by Dave-Allured** [comment]
Thanks Dennis.  Your fix is about the same as mine, so I will not send my patch.  Closing #314, refer to #315.
