### ISSUE TITLE
[--enable-benchmarks] Error message and failure during make/check

### ISSUE THREAD

**Issue by serbinsh** [Unidata/netcdf-c#321]
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### Environment Information

```
[sserbin@modex netcdf-c-4.4.1]$ uname -a
Linux modex 2.6.32-642.4.2.el6.x86_64 #1 SMP Tue Aug 23 11:15:56 CDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [X ] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [X ] 64-bit
* What build system are you using?
  * [X ] autotools (`configure`)
  * [ ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [ ] Yes (please attach to this issue, thank you!)
  * [X ] No
  * [ ] Not at this time

### Summary of Issue

I am getting these error messages when running

```
make check 1>out.txt 2>err.txt & cat out.txt err.txt |grep -i 'fail\|error'
```

```
tst_large2.c: In function ‘main’:
tst_large2.c:98:4: warning: implicit declaration of function ‘nc_finalize’ [-Wimplicit-function-declaration]
    nc_finalize();
    ^
tst_create_files.c: In function ‘main’:
tst_create_files.c:22:5: error: ‘nc_argc’ undeclared (first use in this function)
     nc_argc = argc;
     ^
tst_create_files.c:22:5: note: each undeclared identifier is reported only once for each function it appears in
tst_create_files.c:23:5: error: ‘nc_argv’ undeclared (first use in this function)
     nc_argv = argv;
     ^
tst_create_files.c:176:18: warning: implicit declaration of function ‘pow’ [-Wimplicit-function-declaration]
       for (len = pow(TOTAL_SIZE, (float)1/ndims), d = 0; d < ndims; d++)
                  ^
tst_create_files.c:176:18: warning: incompatible implicit declaration of built-in function ‘pow’
tst_create_files.c:176:18: note: include ‘<math.h>’ or provide a declaration of ‘pow’
tst_create_files.c:288:18: warning: incompatible implicit declaration of built-in function ‘pow’
       for (len = pow(TOTAL_SIZE, (float)1/ndims), d = 0; d < ndims; d++)
                  ^
tst_create_files.c:288:18: note: include ‘<math.h>’ or provide a declaration of ‘pow’
make[2]: *** [tst_create_files.o] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
~
```

This is my module environment
```
Currently Loaded Modulefiles:
  1) /gfortran/5.4.0         2) /gcc/5.4.0              3) /m4/1.4.17              4) /autoconf/2.69          5) /openmpi/2.0.1-gnu540   6) /hdf5/1.8.17-gcc540
```
### Steps to reproduce the behavior

none

**Comment by WardF** [comment]
Hi, could you send your `config.log` generated when you ran configure to `support-netcdf@unidata.ucar.edu`?  It's strange that you are encountering this; the information in `config.log` will contain additional info.  You could also attach it to this issue if you'd like.

**Comment by serbinsh** [comment]
@WardF Here is the config.log (as a .txt so I could upload here)

[config.txt](https://github.com/Unidata/netcdf-c/files/534156/config.txt)

Thanks!

**Comment by WardF** [comment]
Ok, the issue appears to be with `--enable-benchmarks`; if you drop that option when configuring, the issue should go away.  In the meantime I'll take a look and see if I can get these fixed for the next release.

**Comment by serbinsh** [comment]
Ok, thanks for looking into it @WardF!

**Comment by WardF** [comment]
Ok.  Largely functional in branch `gh321`.  Need to ensure things are working properly in a parallel environment.  Tasks to complete for this issue:

* [ ] Make sure pnetcdf tests work properly.
* [ ] Fix issue with .travis configuration, AC_OPTS, while we're here.
