### ISSUE TITLE
data type of NC_FILL_INT

### ISSUE THREAD

**Issue by wkliao** [Unidata/netcdf-c#322]
In netcdf.h, NC_FILL_INT is defined as a constant of type long int.
[Line 72](https://github.com/Unidata/netcdf-c/blob/master/include/netcdf.h#L72)    #define NC_FILL_INT     (-2147483647L)

Shouldn't it be of type int? i.e. -2147483647  (no "L" at the end.)

gcc gives a warning message below, if I tried printf the value.
printf("NC_FILL_INT=%d\n",NC_FILL_INT);
warning: format '%d' expects type 'int', but argument 2 has type 'long int'

**Comment by edhartnett** [comment]
Good catch. I have fixed this in my current branch. It will make it into a PR in a bit.
