### ISSUE TITLE
nc_test fails for 4.4.1 on mpich build - needs to work to support HPC and parallel I/O

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#326]
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

When building 4.4.1 with mpicc (using mpich library) nc_test fails with errors like this:

*** testing nc_put_att_schar ... 
	FAILURE at line 11355 of test_put.c: NetCDF: Numeric conversion not representable
	FAILURE at line 11355 of test_put.c: NetCDF: Numeric conversion not representable
 41 good comparisons. 
	### 2 FAILURES TESTING nc_put_att_schar! ###

Full output is attached.
[nc_test.zip](https://github.com/Unidata/netcdf-c/files/580756/nc_test.zip)

### Environment Information

config.log is attached.
[config.log.zip](https://github.com/Unidata/netcdf-c/files/580754/config.log.zip)

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [ ] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [ ] 64-bit
* What build system are you using?
  * [ ] autotools (`configure`)
  * [ ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [ ] Yes (please attach to this issue, thank you!)
  * [ ] No
  * [ ] Not at this time

[ed@mikado netcdf-4.4.1]$ uname -a
Linux mikado 4.8.4-200.fc24.x86_64 #1 SMP Tue Oct 25 13:06:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[ed@mikado netcdf-4.4.1]$ mpicc --version
gcc (GCC) 6.2.1 20160916 (Red Hat 6.2.1-2)
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### Summary of Issue
nc_test fails.

### Steps to reproduce the behavior

Build netCDF using latest mpich library.

**Comment by WardF** [comment]
My initial thought, recorded here before I've done *any* research, but so that I don't forget: Is this related to #324 ?

**Comment by edhartnett** [comment]
No I don't think so. I think it's related to the recent changes of UBYTE
and/or SBYTE handling. (I can't remember the details, but didn't someone
just commit some changes to that code?)

The error does not occur in 4.4.0.

**Comment by wkliao** [comment]
If you are using PnetCDF 1.7.0 to build netCDF library, then please see #258 and #319.
This is indeed related to NC_UBYTE issue. The current solution is to use PnetCDF 1.6.1.

**Comment by WardF** [comment]
@edhartnett Can you confirm you are using pnetcdf 1.7.0 and/or if using pnetcdf 1.6.1 resolves this?

**Comment by edhartnett** [comment]
I am using 1.7.0. I will try 1.6.1 and let you know...

**Comment by edhartnett** [comment]
I tried with parallel-netcdf 1.6.1 and everything worked! Thanks!

**Comment by WardF** [comment]
Great, thanks! I'll close this out.  I'm also going to be reviewing the conversation/changes made in the pull request that should get 1.7.0 working, once I'm finished with #323
