### ISSUE TITLE
valgrind complains nc_test/tst_small.c

### ISSUE THREAD

**Issue by wkliao** [Unidata/netcdf-c#330]
When running the test program tst_small.c, one of valgrind's complains is about "uninitialised" bytes.  The cause points to file nc_test/tst_small.c, line 106
```
105	 /* Create null-terminated text string of correct length. */
106	 strncpy(att, source, t);
```
To make a string null-terminated, a line below is needed after line 106.
```
107	 att[t] = '\0';
```

**Comment by edhartnett** [comment]
@WardF this ticket can be closed.

The suggested line of code was added to the test at some point. Valgrind and the address santizer are both happy with tst_small.c.
