### ISSUE TITLE
fortran parallel example fails

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#340]
Building the fortran library and running parallel tests failed.

I built like this:
make distclean; LD_LIBRARY_PATH=/usr/local/netcdf-c-4.4.1/lib FC=mpifort CPPFLAGS=-I/usr/local/netcdf-c-4.4.1/include LDFLAGS=-L/usr/local/netcdf-c-4.4.1/lib CC=mpicc ./configure --enable-parallel-tests --prefix=/usr/local/netcdf-c-4.4.1 && make check

Turns out the problem is in the examples/F90 directory:

[ed@localhost F90]$ bash -x ./run_f90_par_examples.sh
+ mpiexec -n 4 ./simple_xy_par_wr

 *** SUCCESS writing example file simple_xy_par.nc! 
+ mpiexec -n 4 ./simple_xy_par_rd
 *** SUCCESS reading example file simple_xy_par.nc! 
+ mpiexec -n 4 ./simple_xy_par_wr2
 NetCDF: Attempt to extend dataset during NC_INDEPENDENT I/O operation. Use nc_va
 NetCDF: Attempt to extend dataset during NC_INDEPENDENT I/O operation. Use nc_va
STOP 2
STOP 2
 NetCDF: Attempt to extend dataset during NC_INDEPENDENT I/O operation. Use nc_va
STOP 2
[ed@localhost F90]$

**Comment by edhartnett** [comment]
I just tried this same build for netcdf-fortran-4.4.3 and it worked fine.

**Comment by WardF** [comment]
Confirmed, will take a look at.  No need to move this one but it might fit better under the `netcdf-fortran/` project :).  Now that I'm back from AGU I'm going to spend some time getting pull requests and issues addressed.

**Comment by edhartnett** [comment]
Just realized I should have put this in netcdf-fortran project. I'll try to remember that next time. :-)

**Comment by WardF** [comment]
No big deal. It appears we have a pull request to fix this, actually:

* https://github.com/Unidata/netcdf-fortran/pull/56

On my end, it *appears* to fix the issue.  Any red flags that you can see? If not, I'll merge it shortly and put out a new netCDF-Fortran release at the same time (or before) that I do the next netCDF-C release.
