### ISSUE TITLE
nc_set_log_level() should always be defined, but a no-op if logging is not enabled.

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#341]
I regret the way that I implemented the nc_set_log_level() function. It is not included in the library unless logging is enabled.

This means that every client library has to keep track of whether this function is present or not, or provide a (no-op) version of the function to stop their links from breaking. 

This is happening to me right now with the PIO library:

CMakeFiles/pio_unit_test.dir/nc_set_log_level2.c.o: In function `nc_set_log_level2_':
/home/ed/pio3/ParallelIO/tests/unit/nc_set_log_level2.c:7: undefined reference to `nc_set_log_level'
collect2: error: ld returned 1 exit status

What I did with the PIO logging function, and what would make more sense with the netcdf one, is to always define the function, but just have it do nothing if logging is not defined. Then user code could use logging in development, and then just move the code to production without taking out the call to nc_set_log_level().

This is already the case with the LOG() macro (that is, it can be used in code, and will evaluate to nothing of logging is not enabled). But this is not true of the nc_set_log_level() function.

To execute the change is trivial, and I can submit a PR, but I wanted to see what the netcdf team thinks.

**Comment by WardF** [comment]
Makes sense to me, and wouldn't cause any harm that I can think of off the top of my head.  What do you think @DennisHeimbigner?

**Comment by DennisHeimbigner** [comment]
I agree, this seems quite reasonable.

**Comment by edhartnett** [comment]
Actually it might cause some downstream pertubation, and it might be best to add a configure option that did it the old way.

The reason it could cause downstream problems is some librarys and programs have no-doubt defined their own versions of it, because they are used to it being not present in production.

So those users, if any, could use the configure option to get a quick upgrade working, and then take the time to tear out whatever code they have to support a sometimes-missing nc_set_log_level().

**Comment by WardF** [comment]
Something like `--provide-set-log-level-stub` would work; I agree that we
don't want to cause a collision for those who already have a work around in
place, good thinking!

**Comment by ndkeen** [comment]
I'm hitting this error with PIO1
`/opt/apps/cmake/3.8.2/share/cmake-3.8/Modules/CheckFunctionExists.c:17: undefined reference to `nc_set_log_level'`

**Comment by edhartnett** [comment]
If this is a PIO error, you should put on the PIO github project, not the netCDF one.

Both PIO and netCDF have an --enable-logging as a configure option. Try building PIO without it. If that doesn't work, put up an issue in the PIO project:
https://github.com/NCAR/ParallelIO
