### ISSUE TITLE
4.4.1.1 make check fails with parallel builds

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#343]
I am building 4.4.1.1 like this:

LD_LIBRARY_PATH=/usr/local/lib CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib CC=mpicc ./configure --enable-parallel-tests --enable-logging --prefix=/usr/local/netcdf-4.4.1.1 

make check fails like this:

mpicc -DHAVE_CONFIG_H -I. -I..  -I../include   -I/usr/local/include   -MT tst_h_par.o -MD -MP -MF $depbase.Tpo -c -o tst_h_par.o tst_h_par.c &&\
mv -f $depbase.Tpo $depbase.Po
tst_h_par.c: In function ‘main’:
tst_h_par.c:89:54: error: ‘ERR’ undeclared (first use in this function)
       if ((fapl_id = H5Pcreate(H5P_FILE_ACCESS)) < 0) ERR;
                                                      ^
tst_h_par.c:89:54: note: each undeclared identifier is reported only once for each function it appears in
tst_h_par.c:226:7: error: ‘SUMMARIZE_ERR’ undeclared (first use in this function)
       SUMMARIZE_ERR;
       ^
tst_h_par.c:231:7: error: ‘FINAL_RESULTS’ undeclared (first use in this function)
       FINAL_RESULTS;
       ^
Makefile:907: recipe for target 'tst_h_par.o' failed
make[2]: *** [tst_h_par.o] Error 1

[config.log.txt](https://github.com/Unidata/netcdf-c/files/666759/config.log.txt)

**Comment by WardF** [comment]
I believe this issue was related to a missing `#include` in `tst_h_par.c`  I don't recall the commit offhand that fixed this, but it is currently fixed in `master`.

**Comment by simoccc** [comment]
Hi, I'm writing just to tell you that the official stable release download is still with this bug.
