### ISSUE TITLE
ncdump then ncgen on same file

### ISSUE THREAD

**Issue by havenerk** [Unidata/netcdf-c#352]
[test.zip](https://github.com/Unidata/netcdf-c/files/726825/test.zip)
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### Environment Information

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [x ] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [ x] 64-bit
* What build system are you using?
  * [x ] autotools (`configure`)
  * [ ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [x ] Yes (please attach to this issue, thank you!)
  * [ ] No
  * [ ] Not at this time

### Summary of Issue
Trying to dump, then regenerate a netcdf3 file.  It may be user error.  Dropping this issue at request of dmh
### Steps to reproduce the behavior

ncdump test.nc >> test.txt; ncgen3 test.txt
[test.zip](https://github.com/Unidata/netcdf-c/files/726831/test.zip)

**Comment by havenerk** [comment]
You may close this issue.  I am the originator and I figured out what I was doing wrong.  Simple user error already covered in the documentation.

**Comment by WardF** [comment]
I'm glad you were able to get this working; do you mind sharing what the issue was? I'd be interested to know if it's something we need to better document or make more clear. Thanks, have a good one!
