### ISSUE TITLE
Autotools build has major library version one greater than intended

### ISSUE THREAD

**Issue by ilovezfs** [Unidata/netcdf-c#355]
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### Environment Information

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [ ] Linux
  * [ ] Windows
  * [x] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [x] 64-bit
* What build system are you using?
  * [x] autotools (`configure`)
  * [ ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [ ] Yes (please attach to this issue, thank you!)
  * [ ] No
  * [ ] Not at this time

### Summary of Issue
The Autotools based build ends up producing library version 12.4.0 not 11.4.0. I noticed this because in Homebrew we just switched from Autotools to CMake (since the tests only pass with CMake, but I digress), and the library version dropped from 12.4.0 to 11.4.0, thereby breaking all of our reverse dependencies, and requiring everything to be revision bumped.

### Steps to reproduce the behavior
Build with Autotools. Observe incorrect library version number using `otool -l /usr/local/Cellar/netcdf/4.4.1.1/lib/libnetcdf.dylib`:
```
          cmd LC_ID_DYLIB
      cmdsize 80
         name /usr/local/Cellar/netcdf/4.4.1.1/lib/libnetcdf.11.dylib (offset 24)
   time stamp 1 Wed Dec 31 16:00:01 1969
      current version 12.4.0
compatibility version 12.0.0
```

Increasing the 11.4.0 in liblib/Makefile.am to 12.4.0 causes it to come out as 13.4.0, confirming the off-by-one error.

**Comment by WardF** [comment]
Thanks for pointing this out; I'll address this in the upcoming release.

**Comment by WardF** [comment]
This issue is strange, as the correct version, 11.4.0, is being specified in the file `liblib/Makefile.am`.  I have no idea why it is ending up as 12.4.0 as reported by `otool -l`.

**Comment by WardF** [comment]
Ok.  The way libtool computes the versions internally are different than how cmake computes versions.  It may or may not be possible for us to keep these consistent, and I'm not completely convinced that we *need* to, depending on the build system.  I need to look into this a bit further.

**Comment by WardF** [comment]
For reference, an old cmake discussion regarding this:

* https://cmake.org/Bug/bug_relationship_graph.php?bug_id=4383&graph=dependency

**Comment by WardF** [comment]
I've brought things into line so that the same version info is contained in the header, if not reflected in the file names.  That should work for now until I get this completely sorted out and reconciled.
