### ISSUE TITLE
Visual Studio 14 tests failing

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#357]
Some tests are failing when building with `master` and Visual Studio 14.  Investigating `nctest` so far, there appears to be a problem with utf8proc_map, for some reason.  There are other tests failing, will flesh out this issue as I go.

**Comment by WardF** [comment]
Fixed. Refer to some of the MSVC/Windows specific info at the top of config.h.cmake.in

**Comment by edhartnett** [comment]
Ward you should get some kind of freaking statue or something commemorating your support for microsoft development environment. Maybe also some kind of bonus or extra vacation to the South of France.

**Comment by WardF** [comment]
I agree completely! :). Perhaps they will have a conference there and I will make the case for going :).  Thanks for the kind words!
