### ISSUE TITLE
ncdump -t error printing 366 day calendar

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#359]
As originally reported via netCDF support (ticket ID OYW-455599)

Netcdf support,

When using ncdump -t, I get invalid dates for calendar attribute
"366_day".  In both versions 4.4.1 and 4.4.1.1 of netcdf-C, the 366-day
calendar returns 30-day months for the first 11 months of the year, and
December has an extra five days.  The extra five dates are displayed with
garbage characters.

The 360-day and 365-day calendars appear to be working correctly in these
versions.  I have not tested extensively.

Can you please fix the 366-day calendar for an upcoming release?  Thank you.

**Test Files are attached to this issue as a zip file.**
[cal.zip](https://github.com/Unidata/netcdf-c/files/745621/cal.zip)

**Comment by WardF** [comment]
@DennisHeimbigner does anything about this leap out at you, before I dive in to debug this?

**Comment by DennisHeimbigner** [comment]
The calendar stuff is in libdispatch/nctme.c and ncdump/nctime0.c
I doubt that this has been updated in years. One place to start
is to see if there is a later version of the software embodied in nctime.
The copyright says:
` * This code was extracted with permission from the CDMS time
 * conversion and arithmetic routines developed by Bob Drach, Lawrence
 * Livermore National Laboratory as part of the cdtime library.  Russ
 * Rew of the UCAR Unidata Program made changes and additions to
 * support the "-t" option of the netCDF ncdump utility, including a
 * 366-day climate calendar.`

**Comment by DennisHeimbigner** [comment]
Just to be sure I understand. since I am not a calendar expert.
A 366 day calendar
has 30 day months for April, June, Sept. Nov.
31 day months for Jan March May July Aug Oct Dec.
29 days (always) for Feb.
Is this correct.

**Comment by Dave-Allured** [comment]
Yes, that is right.  It should work just like the 365-day calendar, except that February always has 29 days, rather than 28.

**Comment by DennisHeimbigner** [comment]
FYI, still working on this. The library we use is external
and rather obscure.

**Comment by Dave-Allured** [comment]
Dennis, thanks for the update.  Please feel free to lower the priority and work on this after the 4.4.2 release.

**Comment by czender** [comment]
FYI we just re-wrote all the calendar code for NCO and I think it works well for default, 360, 365, and 366 day calendars. Friendly warning: the CDMS time code (as implented in ncdump -t) works well usually but can produce some strange results like printing 60 seconds instead of bumping to the next minute. You are welcome to steal NCO's code. Happy to relicense it as necessary. See https://github.com/nco/nco/blob/master/src/nco/nco_cln_utl.c

**Comment by DennisHeimbigner** [comment]
I think we would be interested. The current code we use is old and obscure.

**Comment by DennisHeimbigner** [comment]
Gave up on using the NCO calandar code because it is too intertwined with the
rest of NCO. Will just have to try to fix the nctime.c we have.

**Comment by DennisHeimbigner** [comment]
Ok, I have a fix for this. Unfortunately, it will have to wait until after the existing pull requests
are all merged.

**Comment by DennisHeimbigner** [comment]
resolved by pull request https://github.com/Unidata/netcdf-c/pull/444
