### ISSUE TITLE
ncdump not showing byte type fill values correctly?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#360]
I have a test file with a variable of every (classic atomic) type. I write half the values (the first timestep) and leave the rest alone, so they get fill values. The ncdump is attached.

Not that the first var has a byte type. The fillvalue is -127, which is correct. However I expect it to be displayed as an underscore like the other fill values.

```
netcdf test_pioc_more_classic {
dimensions:
	timestep = 2 ;
	x = 4 ;
	y = 4 ;
variables:
	byte foo_1(timestep, x, y) ;
	char foo_2(timestep, x, y) ;
	short foo_3(timestep, x, y) ;
	int foo_4(timestep, x, y) ;
	float foo_5(timestep, x, y) ;
	double foo_6(timestep, x, y) ;
data:

 foo_1 =
  -42, -42, -42, -42,
  -42, -42, -42, -42,
  -42, -42, -42, -42,
  -42, -42, -42, -42,
  -127, -127, -127, -127,
  -127, -127, -127, -127,
  -127, -127, -127, -127,
  -127, -127, -127, -127 ;

 foo_2 =
  "hi",
  "hi",
  "hi",
  "hi",
  "",
  "",
  "",
  "" ;

 foo_3 =
  -300, -300, -300, -300,
  -300, -300, -300, -300,
  -300, -300, -300, -300,
  -300, -300, -300, -300,
  _, _, _, _,
  _, _, _, _,
  _, _, _, _,
  _, _, _, _ ;

 foo_4 =
  -10000, -10000, -10000, -10000,
  -10000, -10000, -10000, -10000,
  -10000, -10000, -10000, -10000,
  -10000, -10000, -10000, -10000,
  _, _, _, _,
  _, _, _, _,
  _, _, _, _,
  _, _, _, _ ;

 foo_5 =
  -42.42, -42.42, -42.42, -42.42,
  -42.42, -42.42, -42.42, -42.42,
  -42.42, -42.42, -42.42, -42.42,
  -42.42, -42.42, -42.42, -42.42,
  _, _, _, _,
  _, _, _, _,
  _, _, _, _,
  _, _, _, _ ;

 foo_6 =
  -420000000000.5, -420000000000.5, -420000000000.5, -420000000000.5,
  -420000000000.5, -420000000000.5, -420000000000.5, -420000000000.5,
  -420000000000.5, -420000000000.5, -420000000000.5, -420000000000.5,
  -420000000000.5, -420000000000.5, -420000000000.5, -420000000000.5,
  _, _, _, _,
  _, _, _, _,
  _, _, _, _,
  _, _, _, _ ;
}

```

Note that the same problem appears with the netCDF-4 UBYTE:

```
 foo_7 =
  255, 255, 255, 255,
  255, 255, 255, 255,
  255, 255, 255, 255,
  255, 255, 255, 255,
  43, 43, 43, 43,
  43, 43, 43, 43,
  43, 43, 43, 43,
  43, 43, 43, 43 ;

```
The 255s should be shown as underscores since they are the fill value, right?

**Comment by DennisHeimbigner** [comment]
It turns out there is a comment in ncdump#get_fill_info:
>   vp->has_fillval = 1; /* by default, but turn off for bytes */
I have no idea why there is an exception for bytes. But see if
the code can shed any light on this.

**Comment by DennisHeimbigner** [comment]
ok, looking a little further, we see this:
>	case NC_BYTE:
>	    /* don't do default fill-values for bytes, too risky */
>	    vp->has_fillval = 0;
>	    free(fillvalp);
>	    fillvalp = 0;

But I can find no explanation about what is risky about byte fillvalues.

**Comment by edhartnett** [comment]
Hmm, interesting. This of course is the work of our own famous Russ Rew. And I think I get where he was coming from.

There is a default fill value for both bytes and unsigned bytes, and they are defined in netcdf.h. And they are the values that I see when I write some values but leave others unwritten. 

```
#define NC_FILL_BYTE	((signed char)-127)
#define NC_FILL_UBYTE   (255)

```
But suppose I was using a byte variable, and I was using all the values, and I don't want a fill value. In that case, if ncdump used the default fill value, I would awkwardly get underscores instead of -127 or 255. Hilarious confusion would no doubt ensue.

Well that makes a sort of sense, but on the other hand, and exception is also confusing. Anyway, thanks for helping clear up the mystery. I will leave it for you to decide if this is a bug or a feature.

**Comment by edhartnett** [comment]
Ward any objection if I close this ticket? Seems like Denis has answered my question and byte has a different way of displaying in ncdump for historical reasons.

**Comment by WardF** [comment]
Go for it, or reopen and close if you’d like to but I’ll handle it :).
