### ISSUE TITLE
netcdf 4.4.1 test failures when configured with pnetcdf 1.8.1

### ISSUE THREAD

**Issue by ccaamad** [Unidata/netcdf-c#361]
* Environment:

- CentOS7
- x86_64
- OS-provided GCC 4.8.5
- openmpi 2.0.2 built from source
- hdf5 1.8.17 built from source (with PHDF5 enabled)
- pnetcdf 1.8.1 built from source (cannot use 1.6.1, as it does not pass its own tests in my environment)

* Platform:
  * [X] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [X] 64-bit
* What build system are you using?
  * [X] autotools (`configure`)
  * [ ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [ ] Yes (please attach to this issue, thank you!)
  * [X] No
  * [ ] Not at this time

### Summary of Issue

Some tests fail when built against pnetcdf - any ideas, please? config.log and test-suite.log attached to ticket.

Thanks,

Mark

make check ends in...
[config.log.txt](https://github.com/Unidata/netcdf-c/files/757712/config.log.txt)
[test-suite.log.txt](https://github.com/Unidata/netcdf-c/files/757714/test-suite.log.txt)

make[3]: Entering directory `/tmp/nbuild/netcdf-4.4.1/nc_test'
PASS: t_nc
PASS: tst_small
FAIL: nc_test
PASS: tst_misc
PASS: tst_norm
PASS: tst_names
PASS: tst_nofill
PASS: tst_nofill2
PASS: tst_nofill3
FAIL: tst_atts3
PASS: tst_meta
PASS: tst_inq_type
PASS: tst_atts
PASS: tst_put_vars
PASS: tst_parallel2
PASS: tst_pnetcdf
PASS: tst_addvar
PASS: tst_formatx_pnetcdf
PASS: run_diskless.sh
PASS: run_pnetcdf_test.sh
============================================================================
Testsuite summary for netCDF 4.4.1
============================================================================
# TOTAL: 20
# PASS:  18
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See nc_test/test-suite.log
Please report to support-netcdf@unidata.ucar.edu
============================================================================
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory `/tmp/nbuild/netcdf-4.4.1/nc_test'
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory `/tmp/nbuild/netcdf-4.4.1/nc_test'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/tmp/nbuild/netcdf-4.4.1/nc_test'
make: *** [check-recursive] Error 1

### Steps to reproduce the behavior

The following script, run with the argument "4.4.1", reproduces the  behaviour:

#!/bin/bash

set -x
set -e

ver=$1

# Setup installation directory
rm -rf build
mkdir build
prefix=`pwd`/build
export PATH=${prefix}/bin:${PATH}
export CPATH=${prefix}/include:${CPATH}
export LIBRARY_PATH=${prefix}/lib:${LIBRARY_PATH}
export LD_LIBRARY_PATH=${prefix}/lib:${LD_LIBRARY_PATH}

# Build pnetcdf
rm -rf parallel-netcdf-1.8.1
tar xvf parallel-netcdf-1.8.1.tar.gz
cd parallel-netcdf-1.8.1

MPICC=`which mpicc` MPICXX=`which mpicxx` \
  MPIF77=`which mpif90` MPIF90=`which mpif90` \
  ./configure --prefix="$prefix" --with-mpi=$MPI_HOME

# No "--with-pic" configure option, so have to add in manually
cp macros.make macros.make.orig
cat macros.make.orig \
    | sed 's/^CFLAGS\t*=.*/& -fPIC/' \
    | sed 's/^CXXFLAGS\t*=.*/& -fPIC/' \
    > macros.make
make
#make check
#make ptest
make install
cd ..

# Build netcdf
rm -rf netcdf-${ver}
tar xvf netcdf-${ver}.tar.gz
cd netcdf-${ver}

export CC=mpicc
export CXX=mpicxx
export FC=mpif90
export F77=mpif90
export F90=mpif90

./configure --disable-dap-remote-tests --enable-parallel-tests --enable-pnetcdf
make
make check

**Comment by WardF** [comment]
Currently the latest version of pnetcdf which passes all of the netCDF tests is pnetcdf 1.6.1.  There is a pull request from the pnetcdf group to fix this, #319, but there are other issues currently being worked through.

In the meantime, I believe that the core issue with pnetcdf versions beyond 1.6.1 is the result of a false negative; i.e., it should be safe to ignore the test failure for the time being.  I cannot recommend that for obvious reasons, but if you wanted to move forward immediately without waiting for #319 to be merged, that may be a way to go (at your own risk); I would try a test file or two first and validate that what is being written is what you expect to be written.

Thanks!

**Comment by ccaamad** [comment]
Hi Ward,

Thanks for getting back to me, but my problem is that the rest of the world has moved on from pnetcdf 1.6.1 and I'm having major problems building and testing it against recent MPIs on our platform. I'm not the end user, so there's a limited amount meaningful testing I can do beyond the test suites.

I'm somewhat stuck between a rock and a hard place on this one: I don't appear to have a way forward unless I start badgering the pnetcdf people about problems that are ancient history to them.

Cheers,

Mark

**Comment by WardF** [comment]
This should be fixed now with the release of the 4.5.0 release candidate, and in the future full 4.5.0 release.
