### ISSUE TITLE
netcdf installation

### ISSUE THREAD

**Issue by rojinsafavi** [Unidata/netcdf-c#362]
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### Environment Information

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [ x] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [x ] 64-bit
* What build system are you using?
  * [ ] autotools (`configure`)
  * [ x] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [ ] Yes (please attach to this issue, thank you!)
  * [x ] No
  * [ ] Not at this time

### Summary of Issue

I get the following error in the ctest:

 56/150 Test  #56: nc_test4_tst_files ...............***Failed    0.87 sec

and when I run make install I get the following error:

Install the project...
-- Install configuration: "DEBUG"
CMake Error at cmake_install.cmake:36 (file):
  file cannot create directory: /usr/local/lib64/pkgconfig.  Maybe need
  administrative privileges.

make: *** [install] Error 1
[rojinsafavi@citrisdance ~/netcdf-c]$ 

I do not have root access. Is there anyway I get install netcdf without a root access?

Thanks!

**Comment by WardF** [comment]
As far as the installation goes, you will need to specify a location you have access to by passing the `--prefix=[path]` option to `configure`.  Regarding the test failure, can you send the `config.log` and `test-suite.log` files to `support-netcdf@unidata.ucar.edu`?  Thanks! Closing out this issue, but please reference it in your email.
