### ISSUE TITLE
OPeNDAP problem on Win 10 64 with 4.4.1.1

### ISSUE THREAD

**Issue by dopplershift** [Unidata/netcdf-c#365]
This fails for me on windows (at least win 10 64-bit) with 4.4.1.1, using both conda-forge build and Unidata pre-built binaries:

```
ncdump -h http://thredds.ucar.edu/thredds/dodsC/nexrad/composite/gini/n0r/1km/20170216/Level3_Composite_n0r_1km_20170216_1635.gini
```
The error is:

```
ncdump: http://thredds.ucar.edu/thredds/dodsC/nexrad/composite/gini/n0r/1km/20170216/Level3_Composite_n0r_1km_20170216_1635.gini: NetCDF: Invalid argument
```

**Comment by DennisHeimbigner** [comment]
I can duplicate the problem when using cmake and visual studio.
My problem is that I cannot figure out how to step into non _declspec()'d
functions in the visual studio debugger. Hence I am not able to find out where
the failure is occurring. There must be some VS magic of which I am ignorant.
gcc/gdb is so much easier.

**Comment by WardF** [comment]
I'm able to set a break point and run the debugger as expected, although it is only useful when built in debug mode. So there shouldn't be anything extra/special you have to do. When debugging I do the entire build chain from within visual studio; cmake configures the project and generates project files which I then open in VS, set debug mode and then compile whatever. Note that If you're debugging a utility, you have to build NetCDF first and put the dll on your path or it will complain at runtime.

**Comment by DennisHeimbigner** [comment]
That sounds like what I am doing. I open vs and point it to
ALL_BUILD.vcxproj. Mode is debug.
What does this mean?
 > you have to
 > build NetCDF first and put the dll on your path or it will complain at
 > runtime.

**Comment by DennisHeimbigner** [comment]
Should be fixed by https://github.com/Unidata/netcdf-c/pull/366

**Comment by dopplershift** [comment]
Awesome. Thanks @DennisHeimbigner !

**Comment by ocefpaf** [comment]
Many thanks @DennisHeimbigner!!!
