### ISSUE TITLE
Failed to create DataSet instance from Extension .nc is not registered in the factory 

### ISSUE THREAD

**Issue by hemanta25** [Unidata/netcdf-c#368]
I am using Visual Studio 2015, I am created projected for .nc conversion and code is working fine in windows form.
In web application I added created project and reference but when I am running web application it show error.

Failed to create DataSet instance from Extension .nc is not registered in the factory .

Please help me.

**Comment by WardF** [comment]
I'm glad you were able to get the code working as a native executable, but I'm afraid we can't provide any support for running as a web application.  I wouldn't even know where to begin. You might try the NetCDF mailing list, details available here: http://www.unidata.ucar.edu/software/netcdf/mailing-lists.html
