### ISSUE TITLE
Revisiting the request to create NetCDF "classic" files with large dims and vars count

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#371]
This is reopening the discussion that was in #148 (request increase in NC_MAX_DIMS and NC_MAX_VARS).

I would like to revist the discussion in #148 with hopefully a new proposal that will not break any existing applications and give exodus users the options to use the "classic" formats and in particular the option to use the PNetCDF output format if desired for parallel I/O performance. 

**Background**
As you are probably aware, Sandia's exodus database uses netcdf, but for exodus, we need to increase the values of NC_MAX_DIMS and NC_MAX_VARS to store reasonably-sized models. In the past, this "locally-modified" netcdf library was OK; however, recently, the use of exodus has spread to more projects and people have started to provide binary packages for Ubuntu and other systems.

Although the netcdf-4 non-classic format solves a portion of this issue, we would still like to be able to use the classic format and also use the PNetCDF library for parallel I/O.  Although HDF5 is very capable and performant, there are still areas where we want to use PNetCDF.

**Proposal**
I had previously proposed increasing the values of NC_MAX_DIMS and NC_MAX_VARS, but that proposal has backwards compatibility issues in that it can cause memory issues in existing applications and therefore cause an application to break when linked to the modified library.

My current proposal is as follows:

- Provide an additional flag, `NC_IGNORE_MAX_VARS_DIMS` that would be passed through the `cmode` argument to `ex_create` and `ex_open` (read/write). Open to better name.
 - For writing, as the application is creating the file, the library would behave normally until either the `NC_MAX_DIMS` or `NC_MAX_VARS` values were exceeded by a `nc_def_dim` or `nc_def_var` call. 
- *IF* the calling code had *not* passed the `NC_IGNORE_MAX_VARS_DIMS` flag, then the library would error out as normal; no difference in behavior compared to current library.
- *IF* the calling code *did* pass the `NC_IGNORE_MAX_VARS_DIMS` flag, then the library would modify the file type (the `x` in the `CDFx` file signature).  One option would be to change the 1,2,3 to A,B,C or some other convention.  Basically, any file in which the number of dims or vars defined in the file exceeded the default `NC_MAX_DIMS` or `NC_MAX_VARS` values would no longer advertise itself as a valid NetCDF classic file.
- For reading, if the application is linked to a library that existed prior to this change, the open of the file would fail with `NC_ENOTNC` "not a netcdf file" error.  An entry on the NetCDF FAQ page could be added which would tell users something about the issue so they could google the problem and find a discussion of the issue. 
- For reading if the application *is* linked to a library that contains this change, a better error message could be output which would tell the user that this is an "enhanced" or "nonstandard" or some other good message and tell the user what needs to be done to enable the reading of this file.  This is probably similar or better than the current behavior when a user presents a netcdf-4 NetCDF file to an application that was compiled without netcdf-4 support.  Or, in other words, the current library has times when an application can not read a "valid" NetCDF file that was created with a differently configured NetCDF library.
- For reading if the application *is* linked to a library the contains this change *and* the application has passed the `NC_IGNORE_MAX_VARS_DIMS` flag to the `nc_open` call, then the library correctly opens the file and converts the `x` of the `CDFx` back to the correct value (1,2,3,...)  which the file would have been had it not exceeded the `NC_MAX_DIMS` or `NC_MAX_VARS` values.

** Summary **
Hopefully this proposal addresses all or at least most of the objections to the previous proposal.  Most importantly, I think that this proposal does not violate the strict backwards compatibility guarantee.  

It also does not create files that an "unknowing" application would try to read and then break due to the dims or vars count exceeding the standard values.  The only way that the application would be able to open the file successfully would be to pass the `NC_IGNORE_MAX_VARS_DIMS` flag to the `nc_open` call -- basically advertising that they are willing and able to handle a file with unlimited dims and vars.  This is similar to reading a non-classic netcdf4 file which also has no limits on the dims and vars count.

If you think that this is worth pursuing, or would like to see a more concrete implementation, I will be willing to create a pull-request so we can discuss concrete details instead of vapor-ware.

@nmhamster, @wkliao

**Comment by DennisHeimbigner** [comment]
In thinking about this I propose instead the following:
1. We add a new netcdf API function wit signature something like this:
      int_nc_inq_all(int ncid, int *ndimsp, int *nvarsp, int *unlimdimidp, int* ngroups)
      which will return the total numer of dimensions, vars, unlimiteddimensions, and groups
      defined anywhere in the file whose root id is ncid. [?should we also allow asking
      for total # of attributes as well?]. Any *n arguments that are null are ignored.
This function would allow users to allocate fixed space conforming to the specific file.
2. we eventually eliminate NC_MAX_VARS and NC_MAX_DIMS -- this is AFAIK ok because
    we no longer use these internally in the library.

**Comment by wkliao** [comment]
For the new API, nc_inq_all, proposed by Dennis, isn't this already covered by nc_inq and its family APIs?

I am glad to hear that Dennis is OK to eliminate NC_MAX_VARS and NC_MAX_DIMS.

Here are my 2 observations.
First, NC_MAX_DIMS/NC_MAX_VARS/NC_MAX_ATTRS are only defined in NetCDF library. The specifications of CDF file formats do not impose such limits. Strictly speaking, files containing more dimensions, variables, and attributes than these limits are still valid CDF files.
Secondly, regarding to backward compatibility, I do not see lifting these limits (or even eliminating them) should create a problem. By definition, the fact a software of newer version can still work properly on the data created by older versions is backward compatible. On the other hand, a file created by a newer version is not guaranteed to be readable by the older versions.

From the discussion in #148, I can understand the issue concerned by Ward and Dennis. As a software developer, sometimes all I can do is to encourage our users to use the latest release. 

My personal preference is also to eliminate these limits (same as Ed and Dennis). I am glad to hear from Dennis that NetCDF no longer uses them and OK with their elimination. I also have revised PnetCDF to remove their usage internally. (An exception is NC_MAX_NAME which requires more work, as there are still many statically allocated arrays of that size.)

CC to people also involved in discussion.
@roblatham00 
@edhartnett
@jedwards4b

**Comment by edhartnett** [comment]
BTW although I advocate for the elimination of NC_MAX_VARS and NC_MAX_DIM, I use NC_MAX_NAME everywhere and if you took that away, I would just have to define it myself.

I think NC_MAX_NAME is not a problem for users, so I hope we will not be eliminating that.

**Comment by gsjaardema** [comment]
Both `NC_MAX_NAME` and `NC_MAX_VAR_DIMS` would remain.  They are still used throughout the code and are not an issue for the exodus uses of NetCDF.   I don't need for `NC_MAX_ATTRS` to be unlimited, but for consistency it would probably be good to treat it the same as `NC_MAX_DIMS` and `NC_MAX_VARS`

**Comment by gsjaardema** [comment]
I think that the `nc_inq_ndims()` and similar return the number of dims *per group* instead of *per file* as Dennis proposed.  Since the `NC_MAX_VARS` and `NC_MAX_DIMS` changes only affect "classic" files which only have one group, the `nc_inq_ndims()` function should provide the needed information, but it may be useful to also have the `nc_inq_all` function for other uses.

**Comment by DennisHeimbigner** [comment]
Agreed, NC_MAX_NAME and NC_MAX_VAR_DIMS must remain. I am only considering the
per-file global counts NC_MAX_VARS and NC_MAX_DIMS.

**Comment by wkliao** [comment]
I would like to point out that the current value set for NC_MAX_NAME is 256. I will not be surprised in the future, if not soon, some application users challenge this limit. If these limits must be enforced, I suggest we come up with a mechanism to leave a room for future extension, something similar to what Greg proposed. Note that the current implementation of NetCDF and PnetCDF treat values beyond the limits as an error and terminate the function call.

For PnetCDF, I plan to start minimizing the use of these constants if not possible to eliminate them. Of course, my top priority is the consistency to NetCDF.

**Comment by edhartnett** [comment]
Eliminating NC_MAX_NAME is probably not possible. There is no way for the API to tell you in advance what the length of an object's name is. So when I do an nc_inq_varname(), how do I know how much space to allocate to hold the name?

It would be fine if it is increased, but difficult to do without.

**Comment by DennisHeimbigner** [comment]
In retrospect, this is a flaw in the API. When asking for a name, it should have been possible
to specify the size of the name buffer and/or get the size of the name. There are probably
other, similar, flaws elsewhere.

**Comment by edhartnett** [comment]
One could imagine a new function which got the maximum name size in a file...

**Comment by gsjaardema** [comment]
That is what is done in the exodus library.  We write an attribute to the file when it is closed which is the size of the maximum name that was stored in the file.  The reader of the file can then query that value and then allocate the right amount of memory for all reads of name data.   We currently have a hard limit of NC_MAX_NAME.

**Comment by gsjaardema** [comment]
[continued]  The user can also specify a maximum name length on read and the library will truncate any names that are larger than that length.   This is done for backward compatibility since we used to have a maximum name length of 32 characters in exodus library.  The default name length is set to 32 characters, so any client that does not change the maximum name length after opening the file will get the old maximum of 32 characters -- this way we don't exceed any buffers that the client may be using to store the names.  Newer clients query the library for the maximum name length in the file and then set the maximum length for returned strings to that value so no names are truncated.

**Comment by gsjaardema** [comment]
The consensus seems to be that we will work toward eliminating `NC_MAX_VARS`, `NC_MAX_DIMS` and `NC_MAX_ATTRS' .  The `NC_MAX_NAME` limit will be retained.

There will be a function `int nc_inq_all(int ncid, int *ndimsp, int *nvarsp, int *nunlimdimidp, int *ngroups)` which will return the total number of dimensions, variables, unlimiteddimensions, and groups anywhere in the file whose root id is `ncid` if the corresponding argument is non-null. (For example, if `*nvarsp` is NULL, then `nvarsp` will not be set).

The counts are cumulative counts over all groups.  For example, if the file contains 5 groups and each group has 3 dimensions and 4 variables, then `*ndimsp=15`, `*nvarsp=20`, and `*ngroups=5`.  

If a client is only interested in per-group counts, then they can use the existing `int nc_inq(int ncid, int *ndimsp, int *nvarsp, int *nattsp, int *unlimdimidp);` function or they can use the `nc_inq_dimids` and `nc_inq_varids` to query the dimension and variable counts individually.

----
My main question at this point is what is the path to that end?  Is it permissible to just eliminate the checks for exceeding `NC_MAX_VARS` and `NC_MAX_DIMS` or does there need to be an intermediate step in which the client can specify that they want the "new" behavior (i.e. no limits) both on write and on read?

I am fine developing a patch for the above, but would like to have a consensus on what the intermediate step(s) need to look like.

**Comment by edhartnett** [comment]
I believe the checks against NC_MAX_DIMS and NC_MAX_VARS should simply be removed.

I don't think this violates the promise of netcdf backward compatibility.
