### ISSUE TITLE
parallel build of 4.4.1.1 with mpich-3.0.2 and hdf5 1.10.0-patch1 fails building tst_h_par.c...

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#377]
Today I am rebuilding all the tools that go into PIO. ;-)

So I have upgraded to the latest versions, but netcdf-4.4.1.1 fails to build:

```
mpicc -DHAVE_CONFIG_H -I. -I..  -I../include   -I/usr/local/szip-2.1_mpich-3.2/include -I/usr/local/zlib-1.2.11_mpich-3.2/include -I/usr/local/hdf5-1.10.0-patch1/include   -MT tst_h_par.o -MD -MP -MF $depbase.Tpo -c -o tst_h_par.o tst_h_par.c &&\
mv -f $depbase.Tpo $depbase.Po
tst_h_par.c: In function ‘main’:
tst_h_par.c:89:55: error: ‘ERR’ undeclared (first use in this function)
       if ((fapl_id = H5Pcreate(H5P_FILE_ACCESS)) < 0) ERR;
                                                       ^~~
tst_h_par.c:89:55: note: each undeclared identifier is reported only once for each function it appears in
tst_h_par.c:226:7: error: ‘SUMMARIZE_ERR’ undeclared (first use in this function)
       SUMMARIZE_ERR;
       ^~~~~~~~~~~~~
tst_h_par.c:231:7: error: ‘FINAL_RESULTS’ undeclared (first use in this function)
       FINAL_RESULTS;
       ^~~~~~~~~~~~~
Makefile:907: recipe for target 'tst_h_par.o' failed
make[2]: *** [tst_h_par.o] Error 1
make[2]: Leaving directory '/home/ed/Downloads/netcdf-4.4.1.1/h5_test'
Makefile:1378: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/ed/Downloads/netcdf-4.4.1.1/h5_test'
Makefile:691: recipe for target 'check-recursive' failed
```

The build command I was trying:
`CPPFLAGS='-I/usr/local/szip-2.1_mpich-3.2/include -I/usr/local/zlib-1.2.11_mpich-3.2/include -I/usr/local/hdf5-1.10.0-patch1/include' LDFLAGS='-L/usr/local/szip-2.1_mpich-3.2/lib -L/usr/local/zlib-1.2.11_mpich-3.2/lib -L/usr/local/hdf5-1.10.0-patch1/lib' CC=mpicc ./configure --prefix=/usr/local/netcdf-4.4.1.1_mpich-3.2 --enable-parallel-tests && make all check
`

I will attach config.log
[config.log.txt](https://github.com/Unidata/netcdf-c/files/844479/config.log.txt)

**Comment by WardF** [comment]
Hi Ed, this is a known issue but has been resolved for the upcoming release.  tst_h_par.c is missing an include.  At the top of the file, there should be an `#include "err_macros.h"` immediately after `#include <nc_tests.h>`.  Sorry about that! :). Closing out since this is addressed in the latest dev branch for the upcoming release.

**Comment by edhartnett** [comment]
OK, thanks! I'll look forward to the new release.
