### ISSUE TITLE
put attribute _FillValue to a global variable

### ISSUE THREAD

**Issue by wkliao** [Unidata/netcdf-c#388]
According to the document of [nc_put_att](http://www.unidata.ucar.edu/software/netcdf/docs/group__attributes.html#ga14b66e0be82ccf41afe4c8f7f8b1f66a), error code NC_EINVAL should be returned when trying to put attribute _FillValue to a global variable. Instead, NC_NOERR is returned. Below is a small test program that reproduces the issue.
```
#include <stdio.h>
#include <netcdf.h>
#define ERR {if(err!=NC_NOERR){printf("Error at line %d: %s\n",__LINE__,nc_strerror(err)); break;}}
int
main(int argc, char **argv)
{
    int i, ncid, cmode, err, fillv=9;
    int formats[5]={0,
                    NC_64BIT_OFFSET,
                    NC_64BIT_DATA,
                    NC_NETCDF4,
                    NC_CLASSIC_MODEL | NC_NETCDF4};
    char *formatnames[5]={"CDF-1", "CDF-2", "CDF-5", "NETCDF4", "CLASSIC_MODEL"};

    for (i=0; i<5; i++) {
        cmode = NC_CLOBBER | formats[i];
        err = nc_create("testfile.nc", cmode, &ncid); ERR

        err = nc_put_att_int(ncid, NC_GLOBAL, "_FillValue", NC_INT, 1, &fillv);
        if (err != NC_EINVAL)
            printf("%13s Error at line %d: expecting NC_EINVAL but got %d\n",
                   formatnames[i],__LINE__,err);
        err = nc_close(ncid); ERR
    }
    return 0;
}
```

**Comment by wkliao** [comment]
I also suggest to return NC_EGLOBAL instead of NC_EINVAL, which is more informative.
"NetCDF: Action prohibited on NC_GLOBAL varid"

**Comment by WardF** [comment]
This may need to be revisited in light of comments by @czender in #458

**Comment by wkliao** [comment]
My understanding of the final decision of this issue is that NetCDF allows _FillValue attribute for NC_GLOBAL. I assume the NetCDF documents have been revised accordingly.

**Comment by DennisHeimbigner** [comment]
Almost. If I recall correctly, a global _FillValue is allowed to avoid breaking
existing files. A global fillvalue attribute is currently explicitly ignored
by the netcdf library and by ncgen.
