### ISSUE TITLE
Try create a NetCDF4 file using NetCDF ibrary built with --disable-netcdf-4

### ISSUE THREAD

**Issue by wkliao** [Unidata/netcdf-c#392]
A question.
When using NC_NETCDF4 mode to create a file using a netCDF library built without netcdf4 enabled (i.e. --disable-netcdf-4), should the nc_create function return NC_EINVAL?

FYI. I tested this using the latest master branch and the file is created without error, but the file is in the classic format.

**Comment by DennisHeimbigner** [comment]
My take is that it should return NC_EINVAL. One way to check is to see what is
returned by the code when checking other flags (like parallel).

**Comment by edhartnett** [comment]
I suspect the code ignores anything other than NC_CLOBBER. 

That is, it does not check for invalid mode flags, just checks whether the mode flag it is interested in is set.

**Comment by edhartnett** [comment]
OK, I have a PR which will cause netCDF to return NC_EINVAL if nc_create uses NC_NETCDF4 on a library where netCDF-4 was not built. I added a test in nc_test/tst_misc.c.

Also had to make a bunch of changes to nc_test/tst_global_fillval.c. This test was calling nc_create with NC_NETCDF4 even on non-netCDF-4 builds. I've changed the code so it no longer does that. Also updated it's use of ERR macro to match other tests.

But should this also happen if NC_DISKLESS is used? Right now, the code will just silently turn off NC_DISKLESS:

```
#ifndef USE_DISKLESS
   cmode &= (~ NC_DISKLESS); /* Force off */
#endif


```

@DennisHeimbigner what do you think? Should I also return NC_EINVAL if NC_DISKLESS is requested on builds without DISKLESS?

**Comment by Dave-Allured** [comment]
Perspectives from user land:

1.  Always deal with the requested create mode bits.  To avoid surprises, nc_create should not default to an alternate format, when a specific file mode is requested.  This behavior should include NC_NETCDF4, NC_DISKLESS, and any other format variations.  "I would rather the program crash then silently ignore my format request."

2.  When a requested component was disabled, the return should be NC_ENOTBUILT.  NC_EINVAL should be used only for universally unknown mode settings.  I see that PR #562 is moving in that direction; good.

**Comment by DennisHeimbigner** [comment]
NC_DISKLESS is a statement about the storage of a file not about its format.
I would have said that if NC_DISKLESS is not available, the file should still be created
but in the File system.
Also, we need a statement about under what conditions nc_set_default_format()
is nonored. In order to do this, we need to divide the mode flags into
file format flags vs other kinds of flags.

**Comment by Dave-Allured** [comment]
@DennisHeimbigner, I see your point that NC_DISKLESS is not exactly a file format.  However, nc_create carries the expectation of a particular kind of storage, based on the various mode flags.  In my mind I expect NC_DISKLESS to be stored a particular way, in memory only.  Likewise with NC_MMAP, and both of these are optionable in configure.

So from a naive user viewpoint, a new disk file would be unexpected.  I would prefer to get the NC_ENOTBUILT error and stop my program.  However I do not use the in-memory features, so I am fuzzy about their application.  That said, I defer to your judgement.

**Comment by edhartnett** [comment]
I agree with @Dave-Allured. If the user asks for something like NC_DISKLESS, and it is not available, the user should get an error. It is up to the user to then decide whether they want to create the file on disk, or re-build netCDF to include NC_DISKLESS (which is actually what they should do in most cases, if they really want NC_DISKLESS.)

In the open PR (#562) this is dealt with for NC_NETCDF4. Once I fix the CMake business, that can be merged. Should I then move on to do the same with NC_DISKLESS? I believe I should.

**Comment by DennisHeimbigner** [comment]
Ok, so the specification of mode handling would be something like this for nc_create
and nc_open.
1. The incoming mode is or'd with the value of nc_set_default_format
2. If there are conflicting format flags (e.g. CDF5 and NC4) then an error is reported.
    Question: what error?
3. If any flag is set that requires a library capability that is not enabled,
   then the error NC_ENOTBUILT is returned.
This assumes that at configure time all conflicting combinations such
as --enable-pio + --enable-diskless are caught.

**Comment by edhartnett** [comment]
In answer to your question in 2, NC_EINVAL. Because the user has passed in invalid parameter information.

**Comment by edhartnett** [comment]
I believe we have reached consensus that if NC_DISKLESS is asked for, and diskless was not built, then instead of silently turning NC_DISKLESS off, nc_create() should return NC_ENOTBUILT. I am going to make that change to my outstanding PR on this #562.

Moving on to other mode flag issues:

What is the difference between NC_INMEMORY and NC_DISKLESS?

Other than netCDF-4 and DISKLESS, what other cases of NC_ENOTBUILT can there be? I can think of:

NC_PNETCDF
NC_HDF4
NC_CDF5

Did I miss any? I can add these checks. Not sure at the moment about OPENDAP.

Then we need to check conflicting format flags. For reference here are all the flag conflicts:
* NC_MMAP with anything other than NC_DISKLESS
* NC_DISKLESS and NC_NETCDF4/NC_PNETCDF/NC_HDF4 (can you have a diskless CDF5 file?)
* We already check NC_POSIXIO and NC_MPIIO.
```
#define NC_NOWRITE       0x0000 /**< Set read-only access for nc_open(). */
#define NC_WRITE         0x0001 /**< Set read-write access for nc_open(). */
#define NC_CLOBBER       0x0000 /**< Destroy existing file. Mode flag for nc_create(). */
#define NC_NOCLOBBER     0x0004 /**< Don't destroy existing file. Mode flag for nc_create(). */

#define NC_DISKLESS      0x0008  /**< Use diskless file. Mode flag for nc_open() or nc_create(). */
#define NC_MMAP          0x0010  /**< Use diskless file with mmap. Mode flag for nc_open() or nc_create(). */

#define NC_64BIT_DATA    0x0020  /**< CDF-5 format: classic model but 64 bit dimensions and sizes */
#define NC_CDF5          NC_64BIT_DATA  /**< Alias NC_CDF5 to NC_64BIT_DATA */

#define NC_CLASSIC_MODEL 0x0100 /**< Enforce classic model on netCDF-4. Mode flag for nc_create(). */
#define NC_64BIT_OFFSET  0x0200  /**< Use large (64-bit) file offsets. Mode flag for nc_create(). */

/** \deprecated The following flag currently is ignored, but use in
 * nc_open() or nc_create() may someday support use of advisory
 * locking to prevent multiple writers from clobbering a file
 */
#define NC_LOCK          0x0400

/** Share updates, limit caching.
Use this in mode flags for both nc_create() and nc_open(). */
#define NC_SHARE         0x0800

#define NC_NETCDF4       0x1000  /**< Use netCDF-4/HDF5 format. Mode flag for nc_create(). */

/** Turn on MPI I/O.
Use this in mode flags for both nc_create() and nc_open(). */
#define NC_MPIIO         0x2000
/** Turn on MPI POSIX I/O.
Use this in mode flags for both nc_create() and nc_open(). */
#define NC_MPIPOSIX      0x4000 /**< \deprecated As of libhdf5 1.8.13. */

#define NC_INMEMORY      0x8000  /**< Read from memory. Mode flag for nc_open() or nc_create(). */

`
#define NC_PNETCDF       (NC_MPIIO) /**< Use parallel-netcdf library; alias for NC_MPIIO. */
``

**Comment by DennisHeimbigner** [comment]
>What is the difference between NC_INMEMORY and NC_DISKLESS?
NC_INMEMORY refers to the nc_open function in netcdf_mem.h
It allows the content of a file to be read from memory rather than from
a file system file. 
NC_DISKLESS causes the library to create a file internally in memory
rather than creating a file.

**Comment by DennisHeimbigner** [comment]
Other combinations to check:
- (netcdf3 | cdf5|64bitoffset) can support NC_DISKLESS if NC_DISKLESS was built.
NC_PNETCDF (alias for NC_MPIIO) requires mpi support is enabled.

I note that there is a --enable-cdf5 in configure.ac, but that is a holdover
and needs to be removed. CDF5 support is always built into libsrc (netcdf-3).
This flag was for early testing and is no longer need.

**Comment by edhartnett** [comment]
OK, I have taken down my PR while I work out these additional issues.

This work is taking place on the World Domination fork of netCDF: https://github.com/NetCDF-World-Domination-Council/netcdf-c 

on branch ejh_no_netcdf4_create

**Comment by edhartnett** [comment]
@DennisHeimbigner when built with --disable-diskless is NC_INMEMORY still valid?

**Comment by DennisHeimbigner** [comment]
> Note that this procedure uses a limited set of flags because it forcibly sets 
> NC_NOWRITE|NC_DISKLESS|NC_INMEMORY.
So no, inmemory requires diskless.

**Comment by DennisHeimbigner** [comment]
I also note that if diskless is not enabled, nc_open_mem return NC_EDISKLESS.
Perhaps it should return NC_ENOTBUILT.

**Comment by DennisHeimbigner** [comment]
One more conflict: diskless and parallel are mutually exclusive.

**Comment by edhartnett** [comment]
OK, let us consider create and open modes separately.

Here's a function I have added on my branch for create mode checking.

I check for invalid combinations first. Then for NOTBUILT errors.

Did I get everything for create mode?

```
static int
check_create_mode(int cmode)
{
    int mode_format;

    /* This is a clever check to see if more than one format bit is
    * set. */
    mode_format = (cmode & NC_NETCDF4) | (cmode & NC_64BIT_OFFSET) |
       (cmode & NC_CDF5);
   if (mode_format && (mode_format & (mode_format - 1)))
       return NC_EINVAL;

   /* Can't use both NC_MPIIO and NC_MPIPOSIX. Make up your damn
    * mind! */
   if (cmode & NC_MPIIO && cmode & NC_MPIPOSIX)
       return NC_EINVAL;

   /* Can't use both parallel and diskless. */
   if ((cmode & NC_MPIIO && cmode & NC_DISKLESS) ||
       (cmode & NC_MPIPOSIX && cmode & NC_DISKLESS))
       return NC_EINVAL;

#ifndef USE_DISKLESS
   /* If diskless is requested, but not built, return error. */
   if (cmode & NC_DISKLESS)
       return NC_ENOTBUILT;       
#endif
   
#ifndef USE_NETCDF4
   /* If the user ask for a netCDF-4 file, and the library was built
    * without netCDF-4, then return an error.*/
   if (cmode & NC_NETCDF4)
       return NC_ENOTBUILT;
#endif /* USE_NETCDF4 undefined */

#ifndef USE_PARALLEL
   /* If parallel support is not included, these mode flags won't
    * work. */
   if (cmode & NC_PNETCDF || cmode & NC_MPIPOSIX)
       return NC_ENOTBUILT;
#endif /* USE_PARALLEL */

   /* Well I guess there is some sanity in the world after all. */
   return NC_NOERR;
}
```

**Comment by DennisHeimbigner** [comment]
Note that NC_PNETCDF is an alias for NC_MPIIO
because the libpnetcdf will handle all of the classic formats.

**Comment by DennisHeimbigner** [comment]
ok, otherwise I think this ok. You should make sure that this test
covers the similar tests currently in NC3_create and NC4_create
and NCP_create

**Comment by edhartnett** [comment]
I will remove the (partial) checking in those other places, to the extent possible, and centralize all mode flag checking in dfile.c if I can.

This is already passing all existing tests, and I have added tests that ensure the correct error code is returned for INVAL combinations or NOTBUILT.

I will do the open mode checking next...

**Comment by DennisHeimbigner** [comment]
Some notes about nc_open and dap2 and dap4.

1. Checking for DAP2 or DAP4 requires detailed looks at the passed url,
    This will be encoded as a specific model.
    so some checking need to be delayed until you know if dap2/dap4 is to be used.
2. DAP2/DAP4 require NC_DISKLESS, so it must be forcibly set before
    doing mode flag checking.
3. DAP2 always implies simple netcdf classic.
4. DAP4 always implies simple netcdf enhanced.

**Comment by DennisHeimbigner** [comment]
Some notes about nc_open and dap2 and dap4.

1. Checking for DAP2 or DAP4 requires detailed looks at the passed url,
    This will be encoded as a specific model.
    so some checking need to be delayed until you know if dap2/dap4 is to be used.
2. DAP2/DAP4 require NC_DISKLESS, so it must be forcibly set before
    doing mode flag checking.
3. DAP2 always implies simple netcdf classic.
4. DAP4 always implies simple netcdf enhanced.
5. Both DAP2 and DAP4 imply read-only

**Comment by edhartnett** [comment]
BTW @DennisHeimbigner  diskless works with netCDF-4, correct? I thought you said that it did not, but when I disallowed it some test failed (tst_diskless.c). Looking briefly at the test it does seem to be creating a netCDF-4 diskless file (though I didn't study the code long).

So just to confirm - we can have  a diskless netCDF-4/HDF5 file, correct?

**Comment by edhartnett** [comment]
OK moving on to open mode. Here's a question.

Do we wish to error if any format flag is set in open? It should not be allowed, correct?

(This will be different with PIO. User will be able to specify NC_PIO|NC_SHARE|NC_NETCDF4 to use PIO and open a file with parallel netCDF4. But wihtout PIO the user has no choice of what code is used to read the file after an nc_open call.)

**Comment by edhartnett** [comment]
Also I actually am not checking anything dap related, because I am just checking the mode flag. I am not looking at the path and attempting to determine whether it is dap.

In this work, I will just check the mode flags for basic sanity and any attempt to use parts of the library that were not built (the original goal of this issue). So the individual opens/create will get a mode that has had some basic sanity checking.

As you suggest, each particular open/create function will have to do some extra checking on the mode flag. For example, DAP code will have to check the mode flag for non-DAPy things.

**Comment by edhartnett** [comment]
In answer to my own question above, I have decided NOT to return an error when a format flag is used in nc_open(). It breaks a number of tests and probably a lot of user code.

Instead, I will have nc_open return an error when you specify the wrong format. For example, an nc_open call that uses NC_NETCDF4 will fail on a CDF5 file, but pass on a netCDF-4/HDF5 file. This will require some checking in the individual dispatched open calls.

**Comment by edhartnett** [comment]
@DennisHeimbigner:

> I also note that if diskless is not enabled, nc_open_mem return NC_EDISKLESS.
> Perhaps it should return NC_ENOTBUILT.

Not any more. Because my mode checking is called in the dispatch NC_open(), your nc_open_mem() will never be called if NC_DISKLESS or NC_INMEMORY are used, and USE_DISKLESS is not defined.

**Comment by DennisHeimbigner** [comment]
Do not understand. Your checker will still have to return some kind of error
when the user calls nc_open_mem and diskless was not enabled at configure time.

**Comment by DennisHeimbigner** [comment]
PIO will be similar to pnetcdf in that it can
read/write multiple kinds of formats.

**Comment by edhartnett** [comment]
OK, I have a PR pending to deal with #590. After that is merged I will proceed on this issue.

**Comment by edhartnett** [comment]
This work requires some changes in library behavior.

1 What happens if you ask for a format that has not been built?
2 What happens if you use an incorrect format in nc_open()?

In this issue we decided that the answer to 1 is that the user should get NC_ENOTBUILT. (Current behavior is to ignore the troublesome flag).

I am going to elevate 2 to it's own issue so it can get a proper discussion.

**Comment by edhartnett** [comment]
I just put up PR #642 with changes for this ticket.
