### ISSUE TITLE
OpenMPI - Parallel file access with HDF5 1.10.0 fails, MPICH works

### ISSUE THREAD

**Issue by janoliver** [Unidata/netcdf-c#395]
I am trying to use NetCDF 4.4.1 with OpenMPI 1.10.6 and HDF5 1.10.0, and I am running into this bug:

https://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg13804.html

On my machine, the test also fails with the same stack trace. Is there any progress on this, or a workaround I could try? I would like to avoid downgrading to the older HDF5. 

Thank you!

**Comment by WardF** [comment]
Would it be possible to test with the latest netCDF, 4.4.1.1, or even the `master` branch?  We're still not recommending people switch over to the 1.10 branch as the 1.8 branch is still under active development, but I thought we had addressed this issue in a subsequent release.

**Comment by janoliver** [comment]
I tried with master and `run_par_test.sh` still fails.

**Comment by WardF** [comment]
Ok, I've been able to duplicate this issue.  The fact that the test passes with hdf5 1.8.x but fails with 1.10.x suggests to me that this is a problem with the underlying HDF5 library.  I will try to figure out what's going on, or if have an idea for a fix a pull request would be gratefully accepted!  In the short term, you will need to ignore this error or change over to HDF5 1.8.x.

**Comment by janoliver** [comment]
Thank you for confirming it. Switching to the older HDF5 would break compatibility with NC files generated previously. (I am only now changing the way parallelism is handled and adding parallel IO to our code.)

I might have a glance at the code, however, I am very unfamiliar with the internals of NetCDF and HDF5, so I don't think I'll come up with a patch.

I think, btw., that it is an issue of OpenMPI. Older reports suggest that there is no problem with MPICH.

**Comment by WardF** [comment]
> Thank you for confirming it. Switching to the older HDF5 would break compatibility with NC files generated previously. (I am only now changing the way parallelism is handled and adding parallel IO to our code.)

Are you certain this would be the case?  The only files which would be explicitly incompatible would be those generated with HDF5 1.10.x + netCDF 4.4.0 or older.  The window for that possibility was as small as we were able to make it; the HDF5 1.10 release was without warning, and the decision to break backwards binary compatibility by default was puzzling.  netCDF4 files generated with 1.10.x and netCDF 4.4.1+ should be readable by older versions of netCDF.  

> I think, btw., that it is an issue of OpenMPI. Older reports suggest that there is no problem with MPICH.

Thanks for this insight; I am not an expert in MPI, my parallelism expertise is of the 'multithreaded' variety, although I'm working on fixing this gap.  If mpich works, then that would certainly confirm your conclusion.  I'll see if I can confirm that on my end.

**Comment by janoliver** [comment]
> Are you certain this would be the case? The only files which would be explicitly incompatible would be those generated with HDF5 1.10.x + netCDF 4.4.0 or older. The window for that possibility was as small as we were able to make it; the HDF5 1.10 release was without warning, and the decision to break backwards binary compatibility by default was puzzling. netCDF4 files generated with 1.10.x and netCDF 4.4.1+ should be readable by older versions of netCDF.

Oh, I didn't know that. I'll check if reverting to HDF5 1.8 solves the issue for us then. Thank you.

**Comment by WardF** [comment]
No problem, and if you discover this not to be true (although we test for it explicitly) please let us know!

**Comment by WardF** [comment]
I can confirm that this failure doesn't happen when using mpich and hdf 1.10.x.
