### ISSUE TITLE
ncdump_tst_h_rdc0 test case fails on Windows7 x64bit

### ISSUE THREAD

**Issue by t-b** [Unidata/netcdf-c#396]
* What platform are you using? (please provide specific distribution/version in summary)
  * [x] Windows 7 x64
* 32 and/or 64 bit?
  * [x] 64-bit
* What build system are you using?
  * [x] cmake

### Summary of Issue

The test ncdump_tst_h_rdc0 fails when netcdf-c is configured with cmake.

```
$ ./ncdump_tst_h_rdc0.exe

*** Checking HDF5 file c0.nc.
*** Checking HDF5 objcts...HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: E:\projekte\netCDF-svn-WM\CMake-hdf5-1.10.0-patch1\hdf5-1.10.0-patch1\src\H5F.c line 579 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: E:\projekte\netCDF-svn-WM\CMake-hdf5-1.10.0-patch1\hdf5-1.10.0-patch1\src\H5Fint.c line 1100 in H5F_open(): unable to open file: tim
e = Tue Apr 11 17:46:15 2017
, name = 'c0.nc', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: E:\projekte\netCDF-svn-WM\CMake-hdf5-1.10.0-patch1\hdf5-1.10.0-patch1\src\H5FD.c line 812 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: E:\projekte\netCDF-svn-WM\CMake-hdf5-1.10.0-patch1\hdf5-1.10.0-patch1\src\H5FDsec2.c line 348 in H5FD_sec2_open(): unable to open fi
le: name = 'c0.nc', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
Sorry! Unexpected result, E:\projekte\netCDF-svn-WM\netcdf-c\ncdump\tst_h_rdc0.c, line: 28
```

If I copy the file with `cp ncgen/c0.nc ncdump` the test passes.

If you can hint me at the place where I need to add the fix I can give it a shot.

**Comment by WardF** [comment]
What version of netCDF are you experiencing this with?  This appears to be related to an older release of netCDF.  Can you confirm you are working with either 4.4.1.1 or the 4.5.0 release candidate?

**Comment by t-b** [comment]
@WardF I could reproduce with the 4.5.0 release candidate.

To be more correc the fix is `ncgen\ncgen.exe -4 -o ncdump\c0.nc ncgen\c0.cdl` executed in the build directory.

With that I get

```
XXX\ncdump>ncdump_tst_h_rdc0.exe

*** Checking HDF5 file c0.nc.
*** Checking HDF5 objcts...ok.
*** Tests successful!
```

**Comment by edwardhartnett** [comment]
This is very old. Is this still relevant? @t-b can you try again with the current main branch and see if it resolved your issue?

**Comment by t-b** [comment]
Thanks for the reply. Feel free to close for now. I'll reopen once I find time to reproduce.

**Comment by edwardhartnett** [comment]
@t-b can you close the issue please? I don't have permissions. ;-)
