### ISSUE TITLE
Windows/Visual Studio 2015: Fix stack corruption issue in nc_test4_tst_vars

### ISSUE THREAD

**Issue by t-b** [Unidata/netcdf-c#397]
* What platform are you using? (please provide specific distribution/version in summary)
  * [x] Windows 7 x64
* 32 and/or 64 bit?
  * [x] 64-bit
* What build system are you using?
  * [x] cmake

### Summary of Issue

The test `nc_test4_tst_vars.exe` fails using a debug build with Visual Studio 2015.
According to Visual Studio the stack is corrupted.

The code in line 1125ff defines the array `data_in[D1_TARGET][D2_LEN]` but according to my quick and dirty analysis it should have one more row.

```
diff --git a/nc_test4/tst_vars.c b/nc_test4/tst_vars.c
index f7c991c7..7cfdd48e 100644
--- a/nc_test4/tst_vars.c
+++ b/nc_test4/tst_vars.c
@@ -1136,7 +1136,7 @@ main(int argc, char **argv)
       size_t index[ND1];
       int varid;
       int no_fill;
-      int data = TARGET_VALUE, data_in[D1_TARGET][D2_LEN], fill_value_in;
+      int data = TARGET_VALUE, data_in[D1_TARGET + 1][D2_LEN], fill_value_in;
       int i, j;

       /* Create a netcdf-4 file with one dim and 1 NC_USHORT var. */
```

**Comment by DennisHeimbigner** [comment]
let me see if valgrind catches this.

**Comment by DennisHeimbigner** [comment]
Ok, valgrind is not showing any corruption. Will need to see if
we can duplicate using VS.

**Comment by t-b** [comment]
I could reproduce with the 4.5.0 release candidate.

**Comment by t-b** [comment]
@DennisHeimbigner 
Line 1155 writes `data` into the D1_Target (3) and D2_Target (2) index. But the zeroth dimension of data_in, which gets written into in line 1158 with `nc_get_var_int` only has D1_Target (3) rows. And this can not work.

**Comment by t-b** [comment]
Not present anymore in 4.6.1 on Windows 7 with VS 2015.

**Comment by edhartnett** [comment]
This is probably one of the many memory issues we cleared up before the 4.6.1 release...
