### ISSUE TITLE
conda install doesn't work on a Mac

### ISSUE THREAD

**Issue by mbakker7** [Unidata/netcdf-c#398]
Just tried to install netCDF4 version 1.2.7 with `conda install netcdf4` for Python 3.6 on a Mac. This installs version 1.2.4, which doesn't run as it complains that libnetcdf libraries are not matching. Trying to upgrade to 1.2.7 with conda gives an error message that 1.2.7 doesn't exist. Upgrading afterwards with pip works fine, which upgraded to 1.2.7, which works great. But it is odd, as conda install should have done the trick out of the box.

**Comment by WardF** [comment]
You may want to reopen this under the http://github.com/Unidata/netcdf4-python project; tagging in @dopplershift so he can provide information as well.

**Comment by mbakker7** [comment]
Done. See [#647](https://github.com/Unidata/netcdf4-python/issues/647l)
