### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by thehesiod** [Unidata/netcdf-c#407]
It's been more than 6 months since the last release with lots of fixes in-between, sounds like a good time for a new release :)

**Comment by WardF** [comment]
I agree completely! I am currently working on #385 and, once that is corrected, we will be releasing a new C library as quickly as I can; within a day or two, for the release candidate at least.  Fortran and C++ releases will then follow quickly on that :)

**Comment by WardF** [comment]
Closing this out, as there isn't an issue per-se. But testing is done on the fix for #385 and I'm beginning to pull a release candidate together.
