### ISSUE TITLE
Who maintains conventions page?

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/netcdf-c#412]
Who maintains the page:

http://www.unidata.ucar.edu/software/netcdf/conventions.html

It does not look like it's contained within the repo, but it is under the software/netcdf webspace.

**Comment by WardF** [comment]
Dennis and I do.

**Comment by lesserwhirls** [comment]
Is it in the repo and I just missed it, or does it only exist on our web server?

**Comment by WardF** [comment]
It is only on the webserver.  Things are a melange of static and generated pages.  I've started (a while ago) a static pages in /docs/ so that these things are under version control, and I will add the conventions page to it.

**Comment by lesserwhirls** [comment]
Cool - I was on a webex meeting with the netCDF-LD project yesterday and this page was mentioned. They have some ideas and feedback regarding the page, so I was curious who best to direct them to.

**Comment by jyucsiro** [comment]
@lesserwhirls @WardF as part of the ncld WG, we've started to explore this in as a Linked Data register of known conventions. Currently here for testing purposes, but the idea is to mint an identifier for a convention and provide useful links from it to documentation and related resources. See https://github.com/binary-array-ld/bald/issues/41 for more details. 

Would appreciate feedback about whether this sort of system would be useful to a broader audience...

**Comment by edwardhartnett** [comment]
I think this issue can be closed. It is not a netcdf-c issue...
