### ISSUE TITLE
Issue running 4.5.0-rc1 Tests: Multiple Failures

### ISSUE THREAD

**Issue by mathomp4** [Unidata/netcdf-c#416]
* What platform are you using? (please provide specific distribution/version in summary)
  * [x] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [x] 64-bit
* What build system are you using?
  * [x] autotools (`configure`)
  * [ ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [x] Yes (please attach to this issue, thank you!)
  * [ ] No
  * [ ] Not at this time

### Summary of Issue

I can't seem to run the 'make check' for netcdf-c. I built my library against HDF5 1.10.1 `--enable-parallel` with these modules:
```
comp/intel-17.0.4.196
mpi/sgi-mpt-2.15
lib/mkl-17.0.4.196
other/comp/gcc-5.3-sp3
```
on a SLES11 SP3 cluster. As I'm using MPT in a "lazy" way, `mpicc` evaluates to:
```
(1053)((no branch)) $ mpicc --version
gcc (GCC) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
So, on the plus side, not an issue with icc! My configure line was:
```
  $ ./configure --prefix=/discover/swdev/mathomp4/Baselibs/ESMA-Baselibs-5.0.4-beta25-patch1-HDF110-NC45/x86_64-unknown-linux-gnu/ifort_17.0.4.196-mpt_2.15/L
inux --includedir=/discover/swdev/mathomp4/Baselibs/ESMA-Baselibs-5.0.4-beta25-patch1-HDF110-NC45/x86_64-unknown-linux-gnu/ifort_17.0.4.196-mpt_2.15/Linux/in
clude/netcdf --enable-hdf4 --enable-dap --enable-parallel-tests --disable-shared --enable-netcdf-4 CC=mpicc FC=mpif90 CXX=mpicxx F77=mpif90

```
When I try to run `make check` I die in ncgen3:
```
make[4]: Entering directory `/gpfsm/dswdev/mathomp4/Baselibs/ESMA-Baselibs-5.0.4-beta25-patch1-HDF110-NC45/src/netcdf-c-4.5.0-rc1/ncgen3'
make[5]: Entering directory `/gpfsm/dswdev/mathomp4/Baselibs/ESMA-Baselibs-5.0.4-beta25-patch1-HDF110-NC45/src/netcdf-c-4.5.0-rc1/ncgen3'
FAIL: run_tests.sh
FAIL: run_nc4_tests.sh
============================================================================
Testsuite summary for netCDF 4.5.0-rc1
============================================================================
# TOTAL: 2
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See ncgen3/test-suite.log
Please report to support-netcdf@unidata.ucar.edu
============================================================================
```
As for that log file:
```
=============================================
   netCDF 4.5.0-rc1: ncgen3/test-suite.log
=============================================

# TOTAL: 2
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: run_tests.sh
==================

*** Testing ncgen3.
*** creating classic file c0.nc from c0.cdl...
reorder:
./run_tests.sh: line 12:  2729 Segmentation fault      (core dumped) ${NCGEN3} -b -o c0.nc ${ncgen3c0}
FAIL run_tests.sh (exit status: 139)

FAIL: run_nc4_tests.sh
======================

*** Testing ncgen3 for netCDF-4.
*** creating netCDF-4 file c0_4.nc from c0.cdl...
reorder:
./run_nc4_tests.sh: line 12:  2748 Segmentation fault      (core dumped) ${NCGEN3} -k3 -b -o c0_4.nc ${ncgen3c0}
FAIL run_nc4_tests.sh (exit status: 139)
```
Note, I actually discovered this because a netcdf-Fortran program blew a gasket. I then went back to the library and ran the `make check` and discovered these issues. And since that program is all NC4, I figured I could try `make check` in `nc_test4` thinking "I've never even heard of `ncgen3`" but:
```
===============================================
   netCDF 4.5.0-rc1: nc_test4/test-suite.log
===============================================

# TOTAL: 65
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  63
# XPASS: 0
# ERROR: 0
```
### Steps to reproduce the behavior
```
make install
make check
```

**Comment by WardF** [comment]
~~~Interesting~~~ Frustrating! Ok, I'll take a look at this and see if I can replicate the error.  I don't have access to ifort or icc, so hopefully I can get this to happen with gcc.  I will follow up with you once I've addressed this.

**Comment by mathomp4** [comment]
@WardF I actually just realized I never tried running `make check` on hdf5! So there is a chance it might not be netCDF-C. I'll try that soon to see if this is HDF Group's issue instead.

**Comment by mathomp4** [comment]
Well, hdf4 tested clean, and hdf5 is doing okay at the moment. It's currently in one of those loooooong tests it can have with certain compiler/MPI combos. I'll probably run out of allocation on the cluster before it finishes, but I think HDF5 is okay.

**Comment by opoplawski** [comment]
I think I'm seeing the same thing with 4.5.0-rc1 on RHEL7 with hdf5 1.8.12.
```
(gdb) list
516             fprintf(stderr,"<EMPTY>\n");
517             return;
518         }
519         for(i=0;i<nclistlength(triples);i++) {
520             NCD4triple* t = (NCD4triple*)nclistget(triples,i);
521             fprintf(stderr,"\t%s\t%s\t%s\n",
522                     (strlen(t->host)==0?"--":t->host),t->key,t->value);
523         }
524         fflush(stderr);
525     }
(gdb) print t
$1 = (NCD4triple *) 0x623c70
(gdb) print *t
$2 = {host = 0x0, key = 0x623c90 "USE_CACHE", value = 0x623cb0 "0"}
```
looks like strlen(0) segfaults.

**Comment by DennisHeimbigner** [comment]
If you feel like doing an experiment, try this.
Change line 522 to the following:
522                     (t->host == NULL || strlen(t->host)==0?"--":t->host),t->key,t->value);
and see if that fixes the failure.

**Comment by mathomp4** [comment]
@DennisHeimbigner I tried your patch and it does seem to help! I can get through the ncgen3 tests. I'm doing a full clean-and-rebuild now because trying to run a complete make check when hilariously bad, but I'm hoping that's due to me putting it in a bad state, make-wise.

But, so far, good news!

**Comment by mathomp4** [comment]
Hmm. Well, this isn't good in that I can't seem to run any of the "useful" parallel tests in nc_test4:

```
(676)((no branch)) $ mpiexec -np 4 ./tst_parallel

*** tst_parallel testing very basic parallel access.
Sorry! Unexpected result, tst_parallel.c, line: 112
Sorry! Unexpected result, tst_parallel.c, line: 112
Sorry! Unexpected result, tst_parallel.c, line: 112
Sorry! Unexpected result, tst_parallel.c, line: 112
```
and then it just pegs four processors and never lets go.

**Comment by mathomp4** [comment]
More info. netcdf-fortran seems to point to HDF:

```
$ mpiexec -np 4 ./f90tst_parallel
  
 *** Testing netCDF-4 parallel I/O from Fortran 90.
 Error: NetCDF: HDF error
 Error: NetCDF: HDF error
 Error: NetCDF: HDF error
 Error: NetCDF: HDF error
2
2
2
2
```
But maybe that's a generic netcdf error? I then tried a parallel test in HDF5 and that had an issue so...

I'm going to try a different MPI stack to see what that does. Is this endemic, or an HDF5/Netcdf/MPT issue...

**Comment by mathomp4** [comment]
Back from moving days, and I can verify that there seems to be some interaction between NetCDF and MPT. If I build with Intel MPI 17.0.4, I can get NetCDF to pass the tests (save ones that need internet).

**Comment by WardF** [comment]
Just making a note to show this hasn't fallen off the radar.

**Comment by edhartnett** [comment]
Is this issue still active?

The current master builds and tests well for me with parallel builds. @mathomp4 can you try again with master and see if you still have this problem?

**Comment by WardF** [comment]
Closing and will re-open if the issue persists.
