### ISSUE TITLE
minor bug in trim

### ISSUE THREAD

**Issue by wkliao** [Unidata/netcdf-c#420]
Found a minor bug in file nc_test/tst_utf8_validate.c, line 353
```
353     for(i=l-1;l >= 0; i--) {
354         if(t[i] != ' ') break;
```
should be
```
353     for(i=l-1; i>= 0; i--) {
354         if(t[i] != ' ') break;
```
Because tst_utf8_validate.c is considered by git a binary file, I did not create a pull request.

**Comment by wkliao** [comment]
The same bug appears in file nc_test/tst_utf8_phrases.c, line 272.

**Comment by WardF** [comment]
Thanks @wkliao fixing shortly!
