### ISSUE TITLE
surprising output to ncdump -s with empty netcdf-4 file

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#428]
I create an empty netcdf-4 file, and do an ncdump -s, and I get the following:

```
netcdf test_pioc_unlim_multiple_unlim_dim_3 {

// global attributes:
		:_NCProperties = "version=1|netcdflibversion=4.4.1.1|hdf5libversion=1.10.0" ;
		:_SuperblockVersion = 0 ;
		:_IsNetcdf4 = 0 ;
		:_Format = "netCDF-4" ;
}

```

I am surprised that _IsNtecdf4 = 0. Is that expected?

Also, is _SuperblockVersion 0 a valid version?

After I add a dimension, I get the following:

```
netcdf test_pioc_unlim_multiple_unlim_dim_3 {
dimensions:
	unlimited1 = UNLIMITED ; // (0 currently)

// global attributes:
		:_NCProperties = "version=1|netcdflibversion=4.4.1.1|hdf5libversion=1.10.0" ;
		:_SuperblockVersion = 0 ;
		:_IsNetcdf4 = 1 ;
		:_Format = "netCDF-4" ;
}

```

**Comment by DennisHeimbigner** [comment]
> I am surprised that _IsNtecdf4 = 0. Is that expected?
yes, because no netcdf-4 specific informationis available.
The value 0 in this case means that  it looks lilke an HDF5 file
that was not created by netcdf.

>Also, is _SuperblockVersion 0 a valid version?
You might do a hexdump on the file and see what value the
superblock varsion in the file has.

**Comment by edhartnett** [comment]
OK, thanks for the quick answer!

**Comment by edhartnett** [comment]
But wait a moment! The library should know this file was created with netCDF-4 from _NCproperties, right?

**Comment by DennisHeimbigner** [comment]
Not for older files that do not have _Ncproperties.
_isnetcdf4 is computed.

**Comment by DennisHeimbigner** [comment]
Look at the "provenance" section here.
http://www.unidata.ucar.edu/software/netcdf/docs/attribute_conventions.html

**Comment by edhartnett** [comment]
Ok thanks.
