### ISSUE TITLE
Failure to build parallel tests

### ISSUE THREAD

**Issue by ArchangeGabriel** [Unidata/netcdf-c#429]
### Environment Information

* What platform are you using? (please provide specific distribution/version in summary)
  * [x] Linux
* 32 and/or 64 bit?
  * [x] 64-bit
* What build system are you using?
  * [x] autotools (`configure`)

### Summary of Issue

When running `make check` with `--enable-parallel-tests` added to `./configure`, I’m having a failure with:
```
/usr/bin/ld: tst_h_par.o: undefined reference to symbol 'MPI_Wtime'
/usr/lib/openmpi/libmpi.so.12: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

### Steps to reproduce the behavior

```
./configure --prefix=/usr --enable-shared --enable-pnetcdf --enable-parallel-tests
make
make check
```

EDIT: Sorry, message was sent before being finished.

**Comment by ArchangeGabriel** [comment]
(Note that I’ve fixed https://github.com/Unidata/netcdf-c/issues/343 / https://github.com/Unidata/netcdf-c/issues/377 by patching 4.4.1.1 using https://github.com/Unidata/netcdf-c/commit/a83702834938b23cc2e843589aa223e2024a7e6f)

**Comment by WardF** [comment]
Excellent; it should be fixed in the 4.5.0 release candidate as well; I'll double check before closing this out.

**Comment by WardF** [comment]
Corrected, closing this out.

**Comment by ArchangeGabriel** [comment]
@WardF: Not sure I’ve made myself clear. I faced #343/#377 and fixed those through https://github.com/Unidata/netcdf-c/commit/a83702834938b23cc2e843589aa223e2024a7e6f. But the issue I’m reporting in my initial post here is what I’m facing next, and is not fixed on my side.

If there is a fix in master, please tell. ;)

**Comment by WardF** [comment]
No problem @ArchangeGabriel .  As I read your post, you are encountering this with 4.4.1.1.  This issue has been fixed in `master` since it was reported, and is also in the recently released `4.5.0 release candidate 1`.  My phrasing was unclear as to whether it was future or present tense.

If you are encountering this in `master` or `4.5.0-release candidate 1` let me know as it *should* be fixed; indeed, I can no longer recreate it on my end!

**Comment by ArchangeGabriel** [comment]
Can you link me to the commit that fixed it? I failed to found any.

**Comment by ArchangeGabriel** [comment]
(I’ve not tried building with master or the RC yet, will do soon though)

**Comment by WardF** [comment]
It's the link you provided above, a83702834938b23cc2e843589aa223e2024a7e6f, was merged into master on November 29, 2016, capturing the fix.  A hash for the merge of @opoplawski's pull request is here:  1e39435adb08177fb85b35fd136ef49156329ce3

**Comment by ArchangeGabriel** [comment]
So I have not made myself clear, sorry about that… Yes, 4.4.1.1 is affected by an issue that is fixed through https://github.com/Unidata/netcdf-c/commit/a83702834938b23cc2e843589aa223e2024a7e6f.

I’ve mentioned this initially to explain that I know about it but fixed that locally (by applying this commit on top of 4.4.1.1) before building, but then faced a new failure, which is the issue I’m reporting here.

I’ll try to build the RC tomorrow, but I expect the same issue now.

**Comment by WardF** [comment]
Oh ok, I just saw your edit to the top level; my mistake and apologies, I do understand this is a new issue now. Let me take a look.

**Comment by ArchangeGabriel** [comment]
Adding a bit more lines:
```
depbase=`echo tst_h_par.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I../oc2  -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -MT tst_h_par.o -MD -MP -MF $depbase.Tpo -c -o tst_h_par.o tst_h_par.c &&\
mv -f $depbase.Tpo $depbase.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -Wl,-O1,--sort-common,--as-needed,-z,relro -o tst_h_par tst_h_par.o  -lhdf5_hl -lhdf5 -ldl -lm -lz -lcurl 
libtool: link: gcc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro -o tst_h_par tst_h_par.o  -lhdf5_hl -lhdf5 -ldl -lm -lz -lcurl
```

**Comment by ArchangeGabriel** [comment]
(Apparently this could be an issue of linking order or missing library linking. Like MPI?

**Comment by WardF** [comment]
Let me take a look and see if I can recreate it; once I've got it recreated I should be able to untangle the knot of linking/etc.  I suspect you are right (now that I understand this is a new issue, sorry for taking so long to figure that out!) and neither the RC nor the `master` fix this.  I will follow up after I have a moment to take a look.

**Comment by wkliao** [comment]
Hi, @ArchangeGabriel

The  messages from your make command indicate gcc is used. To enable parallel I/O feature, you need to specify the MPI compiler at configure command line, such as
```
CC=mpicc ./configure --enable-parallel --prefix=${H5DIR}
```
See NetCDF user guide below for full description of command-line options
http://www.unidata.ucar.edu/software/netcdf/docs/getting_and_building_netcdf.html#build_parallel

**Comment by ArchangeGabriel** [comment]
@wkliao You’re right, thanks. I had an `export CC=mpicc` but after the `./configure` line… I should have been warned by those lines (discovered now after looking back at logs):
```
checking for ncmpi_create in -lpnetcdf... no
checking Is libpnetcdf version 1.6.0 or later?... yes
configure: WARNING: Cannot link to pnetcdf library, --enable-pnetcdf disabled.
```
```
PNetCDF Support:        no
```
Sorry for the noise, everything is working now.
