### ISSUE TITLE
abort configure when a feature is explicitly enabled but fails to meet the requirement

### ISSUE THREAD

**Issue by wkliao** [Unidata/netcdf-c#431]
* What build system are you using?
  * [x] autotools (`configure`)
  * [x] cmake

A suggestion for configure.ac and CMakeLists.txt.

When a feature is explicitly enabled on the configure/cmake command line and
the libraries (PnetCDF or HDF5) do not meet the requirement (min version etc.),
aborting the configure/cmake command seems better than just printing a warning
message and then disabling the feature. For example, when a user explicitly use
"--enable-pnetcdf" on the command line, indicating the user's intent to build netcdf
with pnetcdf feature, aborting the build with error messages can draw a better attention.

On the other hand, when --enable-netcdf-4 is NOT used on the configure command
line (netcdf-4 feature is default), it implies the user does not mind. So if the HDF5
library does not meet the requirement, then printing a warning message is fine.
However, similar to the above pnetcdf case, if --enable-netcdf-4 is explicitly used,
aborting the build seems a better behavior.

**Comment by edhartnett** [comment]
I have a PR up now that does this for the autotools build (PR #548).

**Comment by edhartnett** [comment]
My PR fixing this issue in the autotools build has been merged (thanks @WardF!).

CMake does not seem to deal with pnetcdf at all, so doesn't suffer from this issue.

The CMake build already errors out of you request netCDF-4 but HDF5 cannot be found.

So I suggest that this issue be closed.
