### ISSUE TITLE
Parallel Failures for netcdf 4.5.0 release branch

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#445]
Creating this issue to capture parallel test failures in netCDF 4.5.0-release candidate branch, in preparation for rc2.  The issue is becoming rather complicated, so I am creating this issue to keep track of failure matrix.

**Comment by WardF** [comment]
The attached script will show roughly what I'm doing, although I am playing around with various options to try to nail down the various failure state/conditions.

* [mytest.sh.zip](https://github.com/Unidata/netcdf-c/files/1184141/mytest.sh.zip)

**Comment by WardF** [comment]
Ok! In the branch `v4.5.0-release-branch`, we see one failure (`nc_test4/run_par_test`) when pnetcdf is **disabled**. If pnetcdf is **enabled** we see the following failures:

* nc_test/run_pnetcdf_test
* nc_test/t_nc
* nc_test/tst_small
* nc_test/tst_norm
* nc_test/tst_nofill
* nc_test/tst_atts
* nc_test/nc_test
* nc_test4/run_par_tst

So, it looks like it is the inclusion of **pnetcdf** that triggers most of the errors, now.  So whatever bug we introduced has to do with pnetcdf.

**Comment by edhartnett** [comment]
What version of pnetcdf are you using?

**Comment by WardF** [comment]
1.8.1, but it appears to be something on our side not theirs. I've reverted #405 locally and will be pushing once I'm positive that something in there caused this issue, but I'm 99% right now.

**Comment by WardF** [comment]
This is fixed so closing.  We reverted and pushed back to github so that we are before `magic.dmh` was merged in.  This will make it easier to merge once the branch is fixed.
