### ISSUE TITLE
authenticated opendap over proxy

### ISSUE THREAD

**Issue by ocehugo** [Unidata/netcdf-c#45]
Hello unidata,
I hope that this is the right place to post this (for sure it's the easier way for me hehe):

I'm having problems trying to access an opendap server that require authentication. The problem is i'm behind a proxy server and when i request the url, ncdump returns me an error. On another machine without the proxy everything works as expected.

Example:

export http_proxy="http://username1:password1@myproxy.com:8080/"
ncdump "http://username2:password2@myopendap.com/thredds/dodsC/test.nc"

returns this:

syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: <!DOCTYPE^ html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Access Denied</title><meta http-equiv="Content-Language" content="English" /><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><link rel="stylesheet" type="text/css"
...
(omited proxy and login informations).

since I don't have control over the proxy I would like to ask if anyone have a solution for this or if you can access opendap servers through proxy servers that both requires authentication. I think this is related to the curl library and the plain password, but i think that you guys should have something to say about it.

**Comment by WardF** [comment]
Just a ping to see if this was ever resolved and, if so, can I close out the issue.

**Comment by DennisHeimbigner** [comment]
I don't recall getting a response back so I
do not know the status.
=Dennis


Ward Fisher wrote:

**Comment by WardF** [comment]
Closing until we get more information.

**Comment by ocehugo** [comment]
Hi,

I believe this was fixed. I just tested here in a new machine/new curl/new netcdf with the same proxy/opendap url and now works. I talked to @WardF sometime ago through email, and he told me that this was a supposed bug in the curl...since i can't check the version of curl that was used in this bug report, I believe it's safe to let this close.
