### ISSUE TITLE
Current snapshot version string is "4.5.1-development"

### ISSUE THREAD

**Issue by czender** [Unidata/netcdf-c#452]
The current snapshot version string returned by nc_inq_libvers() on 20170804 is "4.5.1-development". AFAICT this should say "4.5.0-development".

**Comment by WardF** [comment]
Hi Charlie, we're trying a different way or organizing the release work this time.  The 4.5.0 work is all going on the `v4.5.0-release-branch` branch.  From this branch, we create new `rc` and (on one golden day) the "final release" branch.  Any bug fixes and whatnot that go into the v4.5.0-release-branch can be merged back into `master`, but it also means that features and such merged into `master` don't automatically become part of the v4.5.0 release.  It's a way of managing pull requests that are just too complicated to consider for the immediate release, but which I also don't want to languish.

In that spirit, the `master` truly is the root of the 4.5.1 release at this point, and that is why it identifies as 4.5.1-development.  Nothing going directly into `master` is going to end up in the 4.5.0 release.

**Comment by czender** [comment]
Makes sense. Thanks for ncexplaining.
