### ISSUE TITLE
Documentation issue on Unidata web site in netCDF docs

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#454]
There are some problems with the documentation here:
http://www.unidata.ucar.edu/software/netcdf/docs/file_structure_and_performance.html#large_file_support

The table at the bottom of the section has lost formatting.

Also where it says "See Which Format" the hyperlink of "Which Format" is missing.

**Comment by WardF** [comment]
Thanks! Lots of work left to do to get the documentation squared away, this sort of catch is very helpful!  Also, thanks for your recent blog post, it was *very* informative. :).

**Comment by WardF** [comment]
Merging into 4.5.0 release branch, will propagate to `master` after checks have finished.
