### ISSUE TITLE
nc_check_for_hdf is called with incorrect flags

### ISSUE THREAD

**Issue by dqwu** [Unidata/netcdf-c#461]
Currently, nc_check_for_hdf is only called by NC4_open:
```
/* Figure out if this is a hdf4 or hdf5 file. */
if ((res = nc_check_for_hdf(path, use_parallel, parameters, &hdf_file)))
    goto done;
```
Here, use_parallel (possible values are 0 or 1) is passed to nc_check_for_hdf as the 2nd parameter.

Note that the 2nd parameter of nc_check_for_hdf should be a variable containing some bit flags.
```
nc_check_for_hdf(const char *path, int flags, void* parameters, int *hdf_file)
{
    ...
    int use_parallel = ((flags & NC_MPIIO) == NC_MPIIO);
    ...
    int inmemory = ((flags & NC_INMEMORY) == NC_INMEMORY);
    ...
}
```
In this case, the 2nd argument flags has an integer value of 0 or 1, the two local variables (use_parallel and inmemory) will always be set to 0 after the bit flag check.

For comparison, NC_open calls NC_check_file_type with correct flags being set:
int flags = 0;
...
```
/* Try to find dataset type */
if(useparallel) flags |= NC_MPIIO;
if(inmemory) flags |= NC_INMEMORY;
if(diskless) flags |= NC_DISKLESS;
stat = NC_check_file_type(path,flags,parameters,&model,&version);
```
Then NC_check_file_type can retrieve the flags as:
```
int diskless = ((flags & NC_DISKLESS) == NC_DISKLESS);
int use_parallel = ((flags & NC_MPIIO) == NC_MPIIO);
int inmemory = (diskless && ((flags & NC_INMEMORY) == NC_INMEMORY));
```
PS, there is another issue with nc_check_for_hdf when checking for NC_HDF5_FILE
```
/* Check for HDF4. */
if (memcmp(blob, "\016\003\023\001", 4)==0)
    *hdf_file = NC_HDF4_FILE;
else if (memcmp(blob, "HDF", 3)==0)
	  *hdf_file = NC_HDF5_FILE;
else
    *hdf_file = 0;
```
For NC_HDF5_FILE, the logic should be:
`if(blob[1] == 'H' && blob[2] == 'D' && blob[3] == 'F')`
This logic is used in NC_interpret_magic_number:
```
    /* Look at the magic number */
    /* Ignore the first byte for HDF */
#ifdef USE_NETCDF4
    if(magic[1] == 'H' && magic[2] == 'D' && magic[3] == 'F') {
	*model = NC_FORMATX_NC4;
	*version = 5;
#ifdef USE_HDF4
    } else if(magic[0] == '\016' && magic[1] == '\003'
              && magic[2] == '\023' && magic[3] == '\001') {
	*model = NC_FORMATX_NC4;
	*version = 4;
#endif
```

**Comment by DennisHeimbigner** [comment]
nc_check_for_hdf has been eliminated as part of a yet to be merged
branch (magic.dmh). It was eliminated to help centralize the file format
detection code into libdispatc/dfile.c#NC_check_file_type.
