### ISSUE TITLE
ncgen fails to produce CDF5 file from netCDF4 atomic types CDL file

### ISSUE THREAD

**Issue by czender** [Unidata/netcdf-c#469]
Now that I'm seeing more CDF5 files "in the wild" I've started adding more tests/support for CDF5. However it is tougher than I expected because my understanding of CDF5 is limited, and some of what I expect to "just work" does not do so. Apologies in advance for misunderstandings rooted in  my ignorance, but here goes: My impression is that the netCDF4 atomic types (strings, unsigned, int64) should work in CDF5. Is this correct, or are there netCDF4 atomic types that CDF5 is not intended to support? I'm currently stumped why ncgen succeeds at converting [this](http://dust.ess.uci.edu/tmp/in_tst.cdl) CDL file to netCDF4, yet fails to convert it to CDF5:
```
zender@firn:~$ ncgen -k netCDF-4 -b -o ~/in_tst.nc4 ~/in_tst.cdl # works
zender@firn:~$ ncgen -k cdf5     -b -o ~/in_tst.nc5 ~/in_tst.cdl # borken
ncgen: NetCDF: Not a valid data type or _FillValue type mismatch
	(/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_science_netcdf/netcdf/work/netcdf-c-4.4.1.1/ncgen/genbin.c:125)
```
There are no groups or other extended features, or explicit mention of _FillValue, for that matter, in the input file, just the netCDF4 atomic types. Same behavior occurs on 4.4.1.1 and today's development snapshot.

**Comment by wkliao** [comment]
NC_STRING is not supported in CDF5, due to the limitations of CDF file format specifications.

**Comment by czender** [comment]
Ahh. My understanding was based on the documentation on this [page](http://www.unidata.ucar.edu/software/netcdf/docs/data_type.html) that says CDF5 _does_ support NC_STRING. So I guess the issue now becomes to fix the documentation...

**Comment by WardF** [comment]
I've corrected the documentation for the next release, thanks!
