### ISSUE TITLE
netcdf-c-4.5.0-rc2 build on cygwin broken

### ISSUE THREAD

**Issue by matzeri** [Unidata/netcdf-c#485]
I noticed that on current release candidate the NOUNDEFINED that is set in configure
for cygwin and other platform was removed from the Makefile.am.
This break the build on cygwin, and it was there on 4.4.1.1-1.
Reinstating it, the build is fine and pass all tests.

```
--- origsrc/netcdf-c-4.5.0-rc2/liblib/Makefile.am       2017-08-07 19:25:26.000000000 +0200
+++ src/netcdf-c-4.5.0-rc2/liblib/Makefile.am   2017-09-16 22:44:50.747636500 +0200
@@ -18,7 +18,7 @@ lib_LTLIBRARIES = libnetcdf.la
 # for information regarding incrementing `-version-info`.
 ##

-libnetcdf_la_LDFLAGS = -version-info 12:0:1
+libnetcdf_la_LDFLAGS = -version-info 12:0:1 ${NOUNDEFINED}

 libnetcdf_la_CPPFLAGS = ${AM_CPPFLAGS}
 libnetcdf_la_LIBADD =

```

**Comment by edwardhartnett** [comment]
This is very old. Is this issue still relevant or should it be closed?

**Comment by matzeri** [comment]
forgot about it. Same of https://github.com/Unidata/netcdf-c/issues/2196 that has been solved
