### ISSUE TITLE
nc_inq_var returns NC_FIRSTUSERTYPEID instead of NC_VLEN for a variable created with nc_def_vlen

### ISSUE THREAD

**Issue by Alexander-Barth** [Unidata/netcdf-c#486]
I try to write a generic software which detects the type of a NetCDF variable. I would have expected that when I create a variable-length NetCDF variable, the call to nc_inq_var would return NC_VLEN as a type.
Attached is a sample code (adapted from your tst_vl.c).

### Environment Information

* What platform are you using? (please provide specific distribution/version in summary)
  * [x ] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [x ] 64-bit
* What build system are you using?
  * [ ] autotools (`configure`)
  * [ ] cmake
  * [x] precompiled package from Ubuntu 16.04

* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [ x] Yes (please attach to this issue, thank you!)

### Steps to reproduce the behavior

gcc -o test_vlen2 test_vlen2.c -lnetcdf && ./test_vlen2

output:
```
var_type 32 13 32
```

Expected output
```
var_type 13 13 32
```

[test_vlen2.c.txt](https://github.com/Unidata/netcdf-c/files/1311032/test_vlen2.c.txt)

**Comment by DennisHeimbigner** [comment]
Returning NC_FIRSTUSERTYPEID is in fact the correct behavior.
Let's examine the equivalent CDL file for the first part (see below).
Notice that the type of the variable var is in fact name1.
The  type name1 is what is called a constructed type. NC_VLEN
is what is called a type constructor. Thus, NC_VLEN is used
to construct a specific type with, in this case, name "name1".
The typeid is then the typeid of "name1", which is different from NC_VLEN.
So, a variable will never have type NC_VLEN but rather the typeid of the
constructed type (i.e. name1). If you inquire about the type of name1,
Hope this helps.

netcdf tst_v1 {
types:
    int(*) name1;
dimensions:
    dim = 3;
variables:
    name1 var(dim);
data:
    ...
}

**Comment by Alexander-Barth** [comment]
Thank you very much! This helps a lot!
