### ISSUE TITLE
CURLOPT_KEYPASSWD, others not properly guarded in occurlflags.c

### ISSUE THREAD

**Issue by jwpeterson** [Unidata/netcdf-c#487]
### Environment Information

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [x] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [x] 64-bit
* What build system are you using?
  * [x] autotools (`configure`)
  * [ ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [ ] Yes (please attach to this issue, thank you!)
  * [x] No
  * [ ] Not at this time

### Summary of Issue

Building netcdf 4.4.1.1 on a system with an old curl (7.19.7, circa November 4 2009) fails. There are configure tests for these macros in configure.ac, but their use isn't guarded in the source code... One of the lines in question is, for example:

https://github.com/Unidata/netcdf-c/blob/fde8720fd332f7b06d15e07460d060ebe893a406/oc2/occurlflags.c#L25

### Steps to reproduce the behavior

Compile with an older curl, e.g. 7.19.7.

**Comment by DennisHeimbigner** [comment]
oops! Will fix.

**Comment by DennisHeimbigner** [comment]
Should be fixed with pull request https://github.com/Unidata/netcdf-c/pull/488
