### ISSUE TITLE
configure should error out if --enable-pnetcdf/parallel4 is specified by user, but can't be built

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#494]
There are at least some cases (--enable-pnetcdf) in which the user request for pnetcdf is overridden by the configure file. If the user requests pnetcdf, and pnetcdf is not found, then the configure issues a warning and builds without pnetcdf.

This is incorrect behavior. If the user passes an unknown --enable-something, it should be ignored. but if a known --enable is passed, and cannot be satisfied, then configure should error out.

The reason is that sysadmins may believe they are building with support for pnetcdf, and not look at any output, except that the build succeeded.

The code in configure.ac looks like this:
```
if test "x$pnetcdf_conflict" = xyes ; then
  AC_MSG_WARN([Cannot link to pnetcdf library, --enable-pnetcdf disabled.])
  enable_pnetcdf=no
fi

```
The AC_MSG_WARN should be changed to AC_MSG_ERROR().

Note that in other cases (HDF4 for example), the configure file errors out (correctly) if requested libraries are not found.

```
   # If the user wants hdf4 built in, check it out.
   if test "x$enable_hdf4" = xyes; then
      AC_CHECK_HEADERS([mfhdf.h], [], [nc_mfhdf_h_missing=yes])
      if test "x$nc_mfhdf_h_missing" = xyes; then
         AC_MSG_ERROR([Cannot find mfhdf.h, yet --enable-hdf4 was used.])
      fi
      AC_CHECK_LIB([df], [Hclose], [], [AC_MSG_ERROR([Can't find or link to the hdf4 df library. See config.log for errors.])])
      AC_CHECK_LIB([mfhdf], [SDcreate], [], [AC_MSG_ERROR([Can't find or link to the hdf4 mfhdf library. See config.log for errors.])])

     AC_CHECK_LIB([jpeg], [jpeg_set_quality], [], [AC_MSG_ERROR([Can't find or link to the jpeg library (required by hdf4). See config.log for errors.])])

      AC_DEFINE([USE_HDF4], [1], [if true, use HDF4 too])
   fi

```

**Comment by wkliao** [comment]
I echo that.
A similar suggestion was made in #431

**Comment by DennisHeimbigner** [comment]
Is there not a similar issue with default flags?
If a sysadmin does, say, a default configure but some
default --enable items must be disabled because of e.g.
missing capabilities: what should happen?
If the sysadmin does not look at the settings that
are output at the end of ./configure, then the sysadmin
may be mislead into thinking that a complete default
build succeeded.

**Comment by edhartnett** [comment]
If I type --enable-pnetcdf, then I expect to get pnetcdf or an error in configure (because most likely I need to fix something and try again.)

With default behavior the user has not explicitly told us that he or she wants some specific feature. So we make our best guess. That is not the same as assuming we know better than the user. In other words, we are not overriding anything.

In addition, failing --enable-pnetcdf (if pnetcdf is not found) would match the behavior of other unix packages and what I expect to see from autotools, and the behavior of netCDF with other libraries. It will also simplify the configure.ac file.

I will change the title of this ticket to refer specifically to --enable-pnetcdf, since its the one I know is problematic...

**Comment by wkliao** [comment]
This is not limited to --enable-pnetcdf. Here is another example.
When --enable-parallel4 is explicitly used and the underneath HDF5 was not configured with parallel I/O feature, only warning message is generated. 
https://github.com/Unidata/netcdf-c/blob/fde8720fd332f7b06d15e07460d060ebe893a406/configure.ac#L1047-L1051

**Comment by DennisHeimbigner** [comment]
There are a number of similar situations in configure.ac.
I think that the dap code, for example will only warn if curl
is not available.

**Comment by edhartnett** [comment]
If we agree that configure should error out, then I can make those changes for pnetcdf, parallel4.

Do we agree on that?

**Comment by WardF** [comment]
The current state of warnings vs hard exits is largely a matter of how things were configured previous to my involvement, and mirrored in CMakeLists.txt.  Barring a counter argument, I'm happy to have these warnings converted into errors; it makes perfect sense to me.

**Comment by DennisHeimbigner** [comment]
I an ok with it. Remember in looking at configure.ac, that this
can be more complicated than it first looks. This is because in
some cases the dependency library that is required for a --enable-XXX
may not be tested for until later in the configure.ac.

**Comment by edhartnett** [comment]
OK, I will take a stab at this, *after* I get my first PIO integration merged. So it will be a while...

**Comment by edhartnett** [comment]
OK, while waiting for my other PRs to merge, I am trying to close this ticket.

I now have --enable-pnetcdf behaving as it should. If the user specifies --enable-pnetcdf, and no pnetcdf is found, the configure dies:

```
checking for ncmpi_create in -lpnetcdf... no
configure: error: Cannot link to pnetcdf library.

```

Building with pnetcdf yields some odd-looking configure output:

```
checking for full path of header file pnetcdf.h... /usr/local/pnetcdf-1.8.1_mpich-3.2/include/pnetcdf.h
checking if erange-fill is enabled in PnetCDF... configure: yes
configure: WARNING: Enable erange-fill to conform with PnetCDF setting
checking if relax-coord-bound is enabled in PnetCDF... configure: no
```
This was because we were using AC_MSG_NOTICE instead of AC_MSG_RESULT in two places, which I have fixed. So now the pnetcdf output looks good:

```
checking for ncmpi_create in -lpnetcdf... yes
checking Is libpnetcdf version 1.6.0 or later?... yes
checking for full path of header file pnetcdf.h... /usr/local/pnetcdf-1.8.1_mpich-3.2/include/pnetcdf.h
checking if erange-fill is enabled in PnetCDF... yes
configure: WARNING: Enable erange-fill to conform with PnetCDF setting
checking if relax-coord-bound is enabled in PnetCDF... no

```

I will discuss the --enable-parallel4 issue in a separate comment.

**Comment by edhartnett** [comment]
The --enable-parallel4 issue is a little more complex and I want to make sure I understand what is going on.

The configure.ac currently contains:

```
# Should we suppress parallel io for netcdf-4?
if test "x$enable_netcdf_4" = xyes ; then
     AC_MSG_CHECKING([whether parallel I/O is enabled for netcdf-4])
     AC_ARG_ENABLE([parallel4], [AS_HELP_STRING([--disable-parallel4],
                                          [disable parallel I/O for netcdf-4, even if it's enabled in libhdf5]  )])
  test "x$enable_parallel4" = xno || enable_parallel4=yes
  AC_MSG_RESULT($enable_parallel4)
else
  enable_parallel4=no
fi
if test "x$hdf5_parallel" = xno; then
  # hdf5 does not support parallel io, so disable parallel4
  enable_parallel4=no
  AC_MSG_WARN([Parallel io disabled for netcdf-4 because hdf5 does not support])
fi

```

One problem here is that we are going to show a warning when there is no problem for every non-parallel build. There is no need to warn that HDF5 is not parallel when the user has not specified any parallel options.

So I think the behavior we want is:
if enable-parallel4 is specified, and parallel IO is not available, then configure should error out.
if disable-parallel4 is specified, parallel IO should be disabled if available, ignored otherwise.

Currently enable-parallel is true by default. I suspect what we want is only to make it true by default if there are parallel features available (i.e. HDF5 supports parallel IO, or pnetcdf is being used).

I will look into this and try to find the autoconf-ish way to do this.

**Comment by edhartnett** [comment]
I have decided that there is no good way to improve the

**Comment by edhartnett** [comment]
I have made modifications to the code so that:
* if --enable-parallel4 is specified, and HDF5 does not provide parallel IO, there is an error in configure.
* if nothing is specified, enable-parallel4 is set based on whether HDF5 has parallel I/O (same as current behavior).
* if --disable-parallel4 is used, no warning is issued if HDF5 does not support parallel IO.

Here's the relevant section of configure.ac after these changes:
```
# Should we provide parallel io for netcdf-4?
if test "x$enable_netcdf_4" = xyes ; then
   AC_MSG_CHECKING([whether parallel I/O is enabled for netcdf-4])
   AC_ARG_ENABLE([parallel4],
	[AS_HELP_STRING([--disable-parallel4],
                        [disable parallel I/O for netcdf-4, even if it's enabled in libhdf5])],
			[user_set_parallel4=${enableval}])
   test "x$enable_parallel4" = xno || enable_parallel4=yes
   AC_MSG_RESULT($enable_parallel4)

   # If user wants parallel IO for netCDF-4, make sure HDF5 can provide it.
   if test "x$enable_parallel4" = xyes; then
      if test "x$hdf5_parallel" = xno; then
      	 # If user specifically asked for parallel4, then error out.
	 if test "x$user_set_parallel4" = xyes; then
	    AC_MSG_ERROR([Paralllel IO in netCDF-4 requested, but HDF5 does not provide parallel IO.])
	 fi
         # User didn't specify, so disable parallel4
	 enable_parallel4=no
	 AC_MSG_WARN([Parallel io disabled for netcdf-4 because hdf5 does not support])
      fi
   fi
else
   enable_parallel4=no
fi

```

I will submit this PR tomorrow, which will allow this issue to be closed. Comments welcome.
