### ISSUE TITLE
make install should not uninstall

### ISSUE THREAD

**Issue by jeroen** [Unidata/netcdf-c#498]
In order to work around https://github.com/Unidata/netcdf-c/issues/496 we tried making a build script like this:

```ruby
  args << "-DENABLE_TESTS=OFF"
  args << "-DNC_EXTRA_DEPS=-lmpi" if Tab.for_name("hdf5").with? "mpi"
  args << "-DENABLE_DAP_AUTH_TESTS=OFF" << "-DENABLE_NETCDF_4=ON" << "-DENABLE_DOXYGEN=OFF"

  cmake .. -DBUILD_SHARED_LIBS=ON, *args
  make install
  make clean
  cmake .. -DBUILD_SHARED_LIBS=OFF, *args
  make install
```
However it looks like the second run of `make install` (installing the static libs) actually wipes out the first run with the shared libs. After running this script we only had static libs.

I think there may be a bug in `make install` that triggers `make uninstall`?

**Comment by WardF** [comment]
I'll take a look at this, although we depend on the inherent functionality for cmake for 'make install', so if there is a bug I would expect it to be upstream in the core cmake utility.  I'll investigate and report back.

**Comment by jeroen** [comment]
I don't think the bug is in cmake, we use this for many other cmake packages where it works fine.

**Comment by WardF** [comment]
Cleaning up old issues, this one has clearly languished.  It has been fixed at some point between the last review and now.
