### ISSUE TITLE
Is my performance issue in netcdf4-python related to the netCDF C library?

### ISSUE THREAD

**Issue by dierssen** [Unidata/netcdf-c#50]
Hi!

Jeff Whitaker from https://code.google.com/p/netcdf4-python/ asked me to post my original mail to him on this forum.

Greetings Werner.

**Jeff's response.**

Werner:  This is probably an issue in the underlying C library.  Would you mind posting this as an issue on the github site for the netcdf library? (http://github.com/Unidata/netcdf-c).
-Jeff

**This was my original mail to Jeff, with code.**

Hi Jeffrey,
First of all: thanks for your library!
We are working on a satellite observation project and work with netCDF. We work with big data files >10GB per file. 

I now have the problem that when I have a file with a lot of groups, the netCDF library performance is not good.

I build 2 test programs of which one is based on the HDF5 Python library and the performance is much better:

    [dierssen@machine test]$ ./groups_h5.py
    File opened in write mode (0s)
    Groups created (36s)
    File closed (36s)
    File opened in append mode (37s)
    Groups created (37s)
    [dierssen@machine test]$ ./groups_netcdf.py
    File opened in write mode (0s)
    Groups created (138s)
    File closed (138s)
    File opened in append mode (188s)
    Groups created (203s)

I am not sure if you already know the existence of this issue, but is there any possibility how I could solve it? I prefer to use the netCDF library instead of the HDF5 library.

I hope to hear from you! Below I added the source code for both implementations.

Werner.
I made more test programs and in most cases the HDF5 library was faster, but in the above case the difference was really big.

The netCDF code:

    #!/usr/bin/env python
    """ Create a netCDF file with 6000 groups and print some timing information."""
    from __future__ import print_function
    from __future__ import division

    from netCDF4 import Dataset
    import numpy as np
    import numpy.random as rnd
    import datetime as dt

    def main():
        """ Main function. Called when module is run from the command line."""
        t0=dt.datetime.now()
        nc4_name = 'test_groups.nc'
        fid = Dataset(nc4_name, 'w')
        grp = fid.createGroup('BAND1')

        t1=dt.datetime.now()
        print('File opened in write mode ({}s)'.format((t1-t0).seconds))
        data = rnd.rand(1024, 512)
        for block in range(5000):
            block_name = ('ICID_99999_GROUP_%05d' % block)
            sgrp = grp.createGroup( block_name )
            sgrp.createGroup( 'GEODATA' )
            sgrp.createGroup( 'INSTRUMENT' )
            ssgrp = sgrp.createGroup( 'OBSERVATIONS' )
            sgrp.createDimension('row', size=1024)
            sgrp.createDimension('column', size=512)
            var = ssgrp.createVariable('signal', np.float32, dimensions=('row','column'))
            var[:] = data

        t1=dt.datetime.now()
        print('Groups created ({}s)'.format((t1-t0).seconds))
        fid.close()
        t1=dt.datetime.now()
        print('File closed ({}s)'.format((t1-t0).seconds))

        fid = Dataset( nc4_name, 'a' )
        t1=dt.datetime.now()
        print('File opened in append mode ({}s)'.format((t1-t0).seconds))
        grp = fid.groups['BAND1']
        for block in range(5000, 6000):
            block_name = ('ICID_99999_GROUP_%05d' % block)
            sgrp = grp.createGroup( block_name )
            sgrp.createGroup( 'GEODATA' )
            sgrp.createGroup( 'INSTRUMENT' )
            sgrp.createGroup( 'OBSERVATIONS' )

        t1=dt.datetime.now()
        print('Groups created ({}s)'.format((t1-t0).seconds))
        fid.close()

     if __name__ == '__main__':
        main()

The HDF5 code:

    #!/usr/bin/env python
    """ Create a HDF5 file with 6000 groups and print some timing information."""
    from __future__ import print_function
    from __future__ import division
    
    import h5py
    #import numpy as np
    import numpy.random as rnd
    import datetime as dt
    
    def main():
        """ Main function. Called when module is run from the command line."""
        t0=dt.datetime.now()

        h5_name = 'test_groups.h5'
        fid = h5py.File( h5_name, 'w' )
        grp = fid.create_group( 'BAND1' )

        t1=dt.datetime.now()
        print('File opened in write mode ({}s)'.format((t1-t0).seconds))
        data = rnd.rand(1024, 512)

        for block in range(5000):
            block_name = ('ICID_99999_GROUP_%05d' % block)
            sgrp = grp.create_group( block_name )
            sgrp.create_group( 'GEODATA' )
            sgrp.create_group( 'INSTRUMENT' )
            ssgrp = sgrp.create_group( 'OBSERVATIONS' )
            #sgrp.create_dimension('row', size=1024)
            #sgrp.create_dimension('column', size=512)
            var = ssgrp.create_dataset('signal', (1024, 512), dtype='f')
            var[:] = data

        t1=dt.datetime.now()
        print('Groups created ({}s)'.format((t1-t0).seconds))
        fid.close()
        t1=dt.datetime.now()
        print('File closed ({}s)'.format((t1-t0).seconds))

        fid = h5py.File( h5_name, 'a' )
        t1=dt.datetime.now()
        print('File opened in append mode ({}s)'.format((t1-t0).seconds))

        grp = fid['BAND1']
        for block in range(5000, 6000):
            block_name = ('ICID_99999_GROUP_%05d' % block)
            sgrp = grp.create_group( block_name )
            sgrp.create_group( 'GEODATA' )
            sgrp.create_group( 'INSTRUMENT' )
            sgrp.create_group( 'OBSERVATIONS' )

        t1=dt.datetime.now()
        print('Groups created ({}s)'.format((t1-t0).seconds))
        fid.close()

    if __name__ == '__main__':
        main()

**Comment by WardF** [comment]
I'm not sure where this stands, and it is a bit old so I'm closing the issue.  I'll reopen it as circumstance dictates!
