### ISSUE TITLE
tst_h_atts2.c depends on output from tst_xplatform2.c

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#542]
The test tst_h_atts2.c uses pure HDF5 to confirm the contents of tst_xplatform2.c.

Instead, it would be better to just run these (few) tests at the end of tst_xplatform2.c, eliminating the dependency between these two files.

Ward, are you OK with that? I have the new tst_xplatform2.c working fine with the tests from tst_h_atts2.c, the next step is to remove tst_h_atts2.c and also remove it from Makefile.am and CMakelists.txt.

Sound OK?

**Comment by WardF** [comment]
On paper it sounds good, give me a few to go review the file first. Also, any thoughts @DennisHeimbigner

**Comment by DennisHeimbigner** [comment]
Sounds like a good idea to me.

**Comment by edhartnett** [comment]
OK, after current backlog has gone through the pipeline, I will submit a PR...

**Comment by WardF** [comment]
Testing the current multi-merge right now; it passed Travis.  Hoping/assuming that that will be good enough and that the individual PR's won't need to pass as well.  We will see.

**Comment by edhartnett** [comment]
Thanks Ward! I have a PR up now which will close this ticket...
