### ISSUE TITLE
"Not a valid data type or _FillValue type mismatch" when using NC_BYTE

### ISSUE THREAD

**Issue by lwh1990** [Unidata/netcdf-c#543]
Hi, when I used ncmpi_def_var(..,NC_BYTE,...) and ncmpi_put_vara_all(...,MPI_BYTE), it will throw a error "NetCDF: Not a valid data type or _FillValue type mismatch". And when I change the datatype "BYTE" to other datatype like "INT", the error is gone. How can I fix it if i want to use "BYTE" datatype? Thanks.

**Comment by edhartnett** [comment]
I think you want to take this to the parallel-netcdf team. The ncmpi_ functions are not from netCDF, they are from parallel-netcdf. (https://trac.mcs.anl.gov/projects/parallel-netcdf)

And I also have noticed that the 1-byte types don't work in pnetcdf. So please do report that bug and I hope they get it fixed.

**Comment by lwh1990** [comment]
Thanks for the reply. I have figure it out that starting from PnetCDF 1.7.0, MPI_BYTE does not correspond to any internal data type used in NetCDF/PnetCDF APIs. And changing MPI_BYTE to MPI_SIGNED_CHAR or just use ncmpi_put_vara_schar() can fix this problem.
