### ISSUE TITLE
Problems with DAP support

### ISSUE THREAD

**Issue by marcosgsilva1995** [Unidata/netcdf-c#553]
Hello,

While using the "ncdump" command I get the following error message:

marcos@marcosVB:~$ ncdump -h http://oceandata.sci.gsfc.nasa.gov/MODIS-Terra/L3SMI/2013/001/T2013001.L3m_DAY_SST_sst_4km.nc
curl error details: 
ncdump: http://oceandata.sci.gsfc.nasa.gov/MODIS-Terra/L3SMI/2013/001/T2013001.L3m_DAY_SST_sst_4km.nc: NetCDF: I/O failure

Additionally, curl spawns the following message:

marcos@marcosVB:~$ curl --verbose http://oceandata.sci.gsfc.nasa.gov/MODIS-Terra/L3SMI/2013/001/T2013001.L3m_DAY_SST_sst_4km.nc
*   Trying 169.154.128.84...
* TCP_NODELAY set
* connect to 169.154.128.84 port 80 failed: Connection timed out
* Failed to connect to oceandata.sci.gsfc.nasa.gov port 80: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to oceandata.sci.gsfc.nasa.gov port 80: Connection timed out

Anyone has any idea on how to solve this issue? By the way, I'm using NetCDF-4.5.0 and curl-7.56.0

Thanks,

Marcos Gonçalves

**Comment by DennisHeimbigner** [comment]
It looks like the server http://oceandata.sci.gsfc.nasa.gov is down.
I think you will have to talk to them.

**Comment by DennisHeimbigner** [comment]
Do you know what kind of server oceandata.sci.gsfc.nasa.gov is?
It does not appear to be a thredds server; is it hyrax?

**Comment by DennisHeimbigner** [comment]
I used my browser to walk to the file T2013001.L3m_DAY_SST_sst_4km.nc.
It is in fact a real netcdf-4 file and can be downloaded as such. Why did you think
you were accessing it using DAP?

**Comment by marcosgsilva1995** [comment]
My initial ideal was to retrieve data from this file without downloading it manually. To be clear, I'm actually using R-interface's packages (RNetCDF, especifically) to retrieve data from this database in order to model a 5-years time series. So I had this idea of accessing them using cURL, inside RNetCDF. I don't really know if it is possible, to be honest, but I see cURL is having a hard time accessing this server.

I'm not familiar with server types, so I'm afraid I can't provide you with this info. But I know it is indeed a real file, I just don't want to download all of them files, lol. Do you have any idea why this is happening?

**Comment by cofinoa** [comment]
@marcosgsilva1995 

You are having a `NetCDF: I/O failure` because the server it's not supporting DAP access. 

For DAP access the URL

```
antonio@xps:~$ ncdump -h "https://oceandata.sci.gsfc.nasa.gov/opendap/MODIST/L3SMI/2003/001/T2003001.L3m_DAY_SST_sst_4km.nc"netcdf T2003001.L3m_DAY_SST_sst_4km {
dimensions:
	eightbitcolor = 256 ;
	lat = 4320 ;
	lon = 8640 ;
	rgb = 3 ;
variables:
	float lat(lat) ;
.... [TRUNCATED]
```

**Comment by marcosgsilva1995** [comment]
I've tried different commands and the best I could get is the following message. As for the <code>https</code> issue, my cURL version says it's not supported or it's disabled in <code>libcurl</code>. What NetCDF and cURL built version are you using?

<pre><code>marcos@marcosVB:~$ ncdump -h "http://oceandata.sci.gsfc.nasa.gov:443/opendap/MODIST/L3SMI/2003/001/T2003001.L3m_DAY_SST_sst_4km.nc"
syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR

ncdump: http://oceandata.sci.gsfc.nasa.gov:443/opendap/MODIST/L3SMI/2003/001/T2003001.L3m_DAY_SST_sst_4km.nc: NetCDF: Access failure

marcos@marcosVB:~$ curl --verbose "http://oceandata.sci.gsfc.nasa.gov:443/opendap/MODIST/L3SMI/2003/001/T2003001.L3m_DAY_SST_sst_4km.nc"
*   Trying 169.154.128.84...
* TCP_NODELAY set
* Connected to oceandata.sci.gsfc.nasa.gov (169.154.128.84) port 443 (#0)
> GET /opendap/MODIST/L3SMI/2003/001/T2003001.L3m_DAY_SST_sst_4km.nc HTTP/1.1
> Host: oceandata.sci.gsfc.nasa.gov:443
> User-Agent: curl/7.56.0
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Server: nginx
< Date: Tue, 31 Oct 2017 18:28:23 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 665
< Connection: close
< ETag: "585d4968-299"
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< 
* Closing connection 0
</code></pre>

**Comment by DennisHeimbigner** [comment]
Plug this url into your browser and see if you get back something readable.
https://oceandata.sci.gsfc.nasa.gov/opendap/MODIST/L3SMI/2003/001/T2003001.L3m_DAY_SST_sst_4km.nc.dds

**Comment by DennisHeimbigner** [comment]
You can find out what protocols your version of curl supports by doing this command:
    curl --version
See if https is included.

**Comment by marcosgsilva1995** [comment]
In my browser I got something readable, but in my curl version https is not included. How do I proceed?

**Comment by DennisHeimbigner** [comment]
Either you or your system administrator will have to rebuild libcurl
with https support.
The flags I use for building libcurl are as follows.
./configure --enable-http --enable-file --enable-proxy --enable-ipv6 --enable-cookies --with-zlib --with-ssl
You can see all the available flags using the command
./configure --help
The tricky part is seeing what ssl package you have installed. You might try building
with my flags and see if it complains about the --with-ssl flag.

**Comment by marcosgsilva1995** [comment]
Yes, you were right. I rebuilt libcurl and now it works just fine. For future reference I used the following commands.

Thanks for the valuable help, @DennisHeimbigner

## Commands

Download openssl-1.10f (at least for me other versions didn't work)
Untar it and enter the directory

<pre>
<code>
$  ./confi -fPIC shared --prefix=/usr/local
$  make && make test
$  sudo make install
</code>
</pre>

Download cURL
Untar it and enter the directory

<pre>
<code>
$  ./configure --with-ssl=/usr/local
$  make check && make install
</code>
</pre>
