### ISSUE TITLE
cut time of nc_test runs by ~ 50%?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#556]
While working on nc_test I notice that it is running the tests for netCDF-4 classic model twice. Since this is by far the slowest part of the test, running it twice almost doubles overall test time, from ~12s to ~23s on my machine.

In light of Ward's recent comments about the length of time that a single CI cycle is taking, would you like me to submit a PR with this simple fix? I already have it working, and it's quite trivial. I change the main loop to:

```
	  case NC_FORMAT_NETCDF4: /* skip pure netCDF-4. */
	      continue; /* loop i */
	     
	  case NC_FORMAT_NETCDF4_CLASSIC:
#ifdef USE_NETCDF4
	     nc_set_default_format(NC_FORMAT_NETCDF4_CLASSIC, NULL);
	     strcpy(testfile, "nc_test_netcdf4.nc");
	     fprintf(stderr, "\n\nSwitching to netCDF-4 format (with NC_CLASSIC_MODEL).\n");
	     break;
#else
	     continue; /* loop i */
#endif

```

**Comment by WardF** [comment]
I'll wrap it in to the current ball of pull requests I'm handling by hand. Thanks!

**Comment by WardF** [comment]
Merged!
