### ISSUE TITLE
More functions should return NC_ENOTNC4

### ISSUE THREAD

**Issue by Dave-Allured** [Unidata/netcdf-c#563]
**Platforms:** All
**Sample C program:** Included

**Summary of Issue:**

More API functions should return error code NC_ENOTNC4 when attempting netcdf-4 operations on netcdf-3 format files, to improve self-diagnosis.  This request is inspired by today's help request posted by Dan Hitt:

http://www.unidata.ucar.edu/mailing_lists/archives/netcdfgroup/2017/msg00215.html

Dan's original program accidentally tried to write a string attribute to a netcdf-3 format file.  The function returned NC_EBADTYPE (not a valid data type).  However, NC_ENOTNC4 (attempting netcdf-4 operation on netcdf-3 file) would be more appropriate and helpful.

I suspect there are several other API functions that return some other specific error when NC_ENOTNC4 would be more informative.  However, so far I have not investigated anything other than nc_put_att_string in the current example.

If developers agree, then please phase in NC_ENOTNC4 into nc_put_att_string and other functions, when appropriate.  This is a low priority request.

**Steps to reproduce:**

1.  Compile and run this sample program, modified from Dan Hitt's posted version.  This version creates a netcdf-3 file, then attempts to write a string type attribute which is only possible with netcdf-4 format.
```
#include <stdlib.h>
#include <stdio.h>
#include <netcdf.h>
#include <string.h>

char* copy_string( const char* s ) {
  char* new_str = malloc( strlen(s) + 1);
  strcpy( new_str, s );
  return new_str;
}

int main(int argc,char** argv ) {
  char* outfile = "test.nc";
  int ncid;

  int format_select = 0;   		/* netcdf3 classic format */
/*  int format_select = NC_NETCDF4;   	/* netcdf4 full format */

  int status = nc_create( outfile, NC_CLOBBER | format_select, &ncid );
  if ( status ) {
    fprintf(stderr,"Could not create '%s'; failed with status %d: %s\n",
            outfile, status, nc_strerror( status ) );
    return 1;
  }
  const char* key = copy_string( "my-key" );
  const char* val = copy_string( "my value" );
  status = nc_put_att_string( ncid, NC_GLOBAL, key, 1, &val );
  if ( status ) {
    fprintf(stderr, "nc_put_att_string:\n");
    fprintf(stderr, "Status %d, %s.\n", status, nc_strerror( status ) );
    return 2;
  }
  status = nc_close( ncid );
  if ( status ) {
    fprintf(stderr,"Failed on attempt to close %s; error %d: %s.\n",
            outfile, status, nc_strerror( status ) );
    return 3;
  }
  return 0;
}
```

**Expected result with current API versions (tested with netcdf-4.4.1.1):**
```
nc_put_att_string:
Status -45, NetCDF: Not a valid data type or _FillValue type mismatch.
```

**Desired result:**
```
nc_put_att_string:
Status -111, NetCDF: Attempting netcdf-4 operation on netcdf-3 file.
```

**Comment by edhartnett** [comment]
I must respectfully disagree in the general case.

While it's true that in this particular case, an error of NOTNC4 would make sense, that is not always (or even usually) true when the type parameter is wrong. There are many reasons the typeid might not be valid (for example, if it is uninitialized), which would not be clear from NC_ENOTNC4.

However, I do agree that the nc_put/get functions for the netCDF4 atomic types should return NC_ENOTBUILT if they are used in a build that does not include netCDF-4. This would be a straightforward change that would help with better error messages.

**Comment by DennisHeimbigner** [comment]
This is part of a larger problem. The use of simple integer error codes makes it difficult
(as we see here) to properly report the detailed problem back to the user.
We have available a logging mechanism (separate from the nc_logging one used only
in libsrc4) that could be used to provide a more detailed explanation of the failure.
Or we could consider implementing something like the HDF5 error stack.
Or we could provide some space in the NC structure in which to store a fixed length error message.

**Comment by Dave-Allured** [comment]
Thanks for your thoughtful replies.  Ed, I fully agree that existing error codes are more appropriate than ENOTNC4 in many cases.  However, my intention was that error handlers would make a smart decision when to return ENOTNC4 in place of a conventional error code like EBADTYPE.  Similar logic would also apply in your other scenario, ENOTBUILT.

In the appropriate cases, I would expect that all the necessary decision information is available at the point of error detection.  However I have not yet looked at the relevant code.  I will try to post an example when I get some "spare time".

**Comment by Dave-Allured** [comment]
@DennisHeimbigner, I agree detailed reporting is desirable and also constrained by simple integer codes.  The available logging mechanism is good, and I hope that detailed reporting can be expanded in the future.

However, single integer codes work well in the majority debugging situations, and the user world is used to them.  So let me recharacterize this as a suggestion to incrementally improve the value of integer return codes in appropriate cases, when implementation is simple and there is no significant performance impact.

**Comment by edhartnett** [comment]
OK, we have had an interesting discussion but I would like to try and close this ticket. ;-)

Widening the netCDF error reporting infrastructure is beyond the scope of this ticket, IMHO. Also, though flawed, the C system of returning a single integer error code is very robust and works pretty well most of the time. After all, there is only so much the library can do to tell a user where they have gone astray.

Once current PRs are merged, netCDF will return NC_ENOTBUILT when you try and create a netCDF-4 file on a library that does not allow it.

I thought it would be useful to do the same for functions like nc_put_vara_longlong (and other non-classic atomic types). But due to CDF5 those function no longer apply only to netCDF-4 (which is a great thing). Other netCDF-4 functions (like nc_get_vara_string()) are only in the library if netCDF-4 is built, so returning NC_ENOTBUILT is possible. They already return NC_ENOTNC4 when used on a classic file.

So I think this ticket is done. Unless someone can come up with another specific function that should return NC_ENOTBUILT when netCDF-4 is not built, I suggest this ticket be closed.

**Comment by edhartnett** [comment]
BTW I should also add that I'm doing an overhaul of the error messages for both create and mode flags, including full use of the NOTBUILT code when a requested feature is not built into the library. Follow that work on issue #392.
