### ISSUE TITLE
Remove --disable-cdf5 from configure?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#580]
In configure.ac we have:

```
# Check whether we want to enable CDF5 support.
AC_MSG_CHECKING([whether CDF5 support should be enabled (default off)])
AC_ARG_ENABLE([cdf5],
              [AS_HELP_STRING([--enable-cdf5],
                              [build with CDF5 support.])])
test "x$enable_cdf5" = xyes || enable_cdf5=no
AC_MSG_RESULT($enable_cdf5)

if test "x$enable_cdf5" = xyes; then
   AC_DEFINE([USE_CDF5], [1], [if true, enable CDF5 Support])
   AC_DEFINE([ENABLE_CDF5], [1], [if true, enable CDF5 Support])
fi

AM_CONDITIONAL(USE_CDF5, [test x$enable_cdf5 = xyes ])
AM_CONDITIONAL(ENABLE_CDF5, [test x$enable_cdf5 = xyes ])
```

Denis believes that CDF5 is always built into the library and this option should be removed.

I have encountered USE_CDF5 several places in the code, and if it can be removed, I think that would be a GOOD THING.

@WardF any thoughts?

I will look at the code to see...

**Comment by DennisHeimbigner** [comment]
> I have encountered USE_CDF5 several places in the code, and if it can be removed, ...
I just did a search for it and found no instances of either USE_CDF5 or ENABLE_CDF5
(except in config.h)
Where did you see it?

**Comment by WardF** [comment]
It was added as part of the 4.5.0 release. There have been a number of CDF5-related issues which have arisen and are outstanding, including issues on 32-bit platforms for which the solution appears to be either disable CDF5 support on these platforms under some circumstances, or re-implement 64-bit offset in CDF5.  Neither is a good solution.  Adding it allowed us to disable support for CDF5 by default, sidestep these issues, and get 4.5.0 out the door.

**Comment by DennisHeimbigner** [comment]
I thought those issues had to do with pnetcdf, not cdf5 per-se.

**Comment by WardF** [comment]
No, those were for the issues related to the 'native' CDF5 support added to libnetcdf.  Charlie Zender has an issue open for it, I don't recall which one at the moment but will go look.

**Comment by WardF** [comment]
As it stands, unless we can guarantee that CDF5 works across all platforms, which we cannot, we need to have a way to enforce disabling it on those platforms where it won't work.

**Comment by DennisHeimbigner** [comment]
I stand corrected. But why is the control option not
used in any of the Makefile.am files in the current master branch?
Is this change still waiting to be merged?

**Comment by edhartnett** [comment]
@DennisHeimbigner to answer your question, I encountered USE_CDF5 in a test in nc_test.

**Comment by WardF** [comment]
It went into config.h because there are no libraries to be linked against. There are conditional blocks in the code.
