### ISSUE TITLE
Test nc_test/tst_cdf5format.c is not being built or run

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#588]
There is a test called tst_cdf5format.c which is in nc_test, but not in the Makefile.am.

Looking at the code, it will clearly not compile right now.

So this test should be fixed.

**Comment by DennisHeimbigner** [comment]
Check to see if this test actually is needed. It might be holdover from the original
cdf5 code insertion.

**Comment by edhartnett** [comment]
Well that brings up the interesting question of test code coverage, which I don't think you are measuring right now. 

I will see what I can set up in my own jenkins build to measure test coverage.

**Comment by DennisHeimbigner** [comment]
If we do it, it is probably being done using CDash.
Ward?

**Comment by edhartnett** [comment]
Well it just took 10 minutes to get a cobertura coverage report on my
jenkins server for netcdf. Very interesting!



Here's a screenshot:


​

On Sun, Nov 5, 2017 at 12:04 PM, Dennis Heimbigner <notifications@github.com

**Comment by WardF** [comment]
We generate test coverage on an on-demand basis. Some areas could be better but without more resources there isn’t much we can do at the moment to retrofit old code for testing outside of reported bugs. It’s interesting to find out though. 

You can turn this on by using -DENABLE_COVERAGE_TESTS=TRUE (I think, on my phone so can’t double check) when configuring with CMake, and then run ‘make experimental’ to submit the results to our cdash, http://cdash.unidata.ucar.edu.

**Comment by edhartnett** [comment]
No need to close the ticket. I will apply a little TLC and get
tst_cdf5format.c running again. Probably tomorrow morning.

My sense from recent work is that NC_CDF5 is not super well tested in the
enhanced data area. (nctest and nc_test of course deliver great testing for
the classic layer.) There are a bunch of tests in nc_test4 that could now
easily be used for CDF5, in the same way that nc_test is used for both
classic and netCDF-4 testing. I will ponder that for the future.

The code coverage shows a respectable 82% for libsrc, and only 71% for
libsrc4, which I certainly will enjoy raising. libdap2 and 4 are at 58 and
62% coverage.

In my experience with C code, >85% is a good goal, >90% is impossible
usually due to all the error handling.

I am running this coverage with gcc's built in gcov, and the free software
package gconv to convert the output to a format that jenkins understands.
Took about 10 minutes to set up. So it's part of my jenkins CI now and I
will see it update every time I write to the WDC netCDF clone. This will
allow me to target missing coverage in the libsrc4 directory.

Thanks,
Ed

**Comment by DennisHeimbigner** [comment]
We have previously only used jenkins for java. Can you point me to your jenkins build
for C?

**Comment by edhartnett** [comment]
It's the same jenkins. Just create a jenkins job which downloads the repo you want and there's a build section where you put the commands. For example, here's my build section for the build that does the coverage report:

```
autoreconf -i 
export CPPFLAGS='-I/usr/local/zlib-1.2.11/include -I/usr/local/szip-2.1/include -I/usr/local/hdf5-1.10.1/include' 
export LDFLAGS='-L/usr/local/zlib-1.2.11/lib -L/usr/local/szip-2.1/lib -L/usr/local/hdf5-1.10.1/lib' 
export CFLAGS='-fprofile-arcs -ftest-coverage'
./configure --enable-cdf5 --enable-diskless
make check
gcovr -r . --xml-pretty>cov.xml

```

It's easy to copy and existing job and make a modification to the configure. So now I have more than 15 jobs that run whenever I commit to a branch starting with ejh_ in my WDC clone of netCDF. Very handy. So before I put up a PR it has already passed all the different configurations.

I have a rasberry pi somewhere around here, I am hoping to get that set up and add it to the jenkins runs as well. ;-)

**Comment by WardF** [comment]
Didn’t mean to close it, but things are stacking up. Will try to get to them the first part of next week :)

**Comment by DennisHeimbigner** [comment]
I assume that somewhere you have jenkins config page like this one:
https://jenkins-aws.unidata.ucar.edu/job/threddsMaster/configure

**Comment by WardF** [comment]
FWIW I think we’re ok leaving Jenkins for java internally.

**Comment by edhartnett** [comment]
Agile processes have developed over time.

It's pretty normal these days for each programmer to have their own local
jenkins and their own local CI. For example, Dennis, you could install
jenkins on your machine, and then open it with localhost:8080. It's super
easy for you to set up and maintain your own jenkins.

It is very convenient and ensures that you never or very, very rarely
submit a PR which bounces back to you. So it is all about making life
easier for the programmer.

For example, if I make a simple change to configure, I could easily break
some obscure feature I never personally use. Then if it is caught by the
travis CI, I have to circle around and edit my PR, and wait again to get it
merged. If it is not caught by the travis CI, then I just introduced a bug,
which later I will have to fix. What a lot of work that is!

You know what the very least amount of work is? For me never to introduce
that bug in the first place.

Instead, I keep an eye on my jenkins page as I develop, so I see if I broke
anything immediately. Before I put up the PR for team review, I do my final
clean-up and edits and commit. Then I wait until Jenkins is all green
before I submit the PR. So I know it works in parallel with
--enable-parallel-tests --enable-cdf5 --disable-netcdf4, and also that it
works sequentially for --disable-netccdf4 --disable-dap. And many other
combinations (not every combination though, there are many, many). But any
time I have a failure later on in CI, I add another test configuration to
my personal jenkins.

As we get things working like the memory-sanitized build, I also add those
to my Jenkins server. Jenkins supports other code checking which can be
turned on and used to improve the code base (like code coverage). So it
really supports and enables continuous improvement of the code base.

It's great! I urge you to use it fully for C and Fortran in addition to
Java. ;-)

Ed
