### ISSUE TITLE
make -j check does not seem to work in h5_test

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#598]
I think there is some problem preventing make -j check working in h5_test. Not sure why, but it never works for me. I get this error:

```
PASS: tst_h_files4
PASS: tst_h_files2
PASS: tst_h_strings
PASS: tst_h_ints
PASS: tst_h_atts3
PASS: tst_h_grps
PASS: tst_h_compounds2
PASS: tst_h_atts4
PASS: tst_h_opaques
PASS: tst_h_enums
PASS: tst_h_vars
PASS: tst_h_wrt_cmp
PASS: tst_h_vars3
PASS: tst_h_files
PASS: tst_h_compounds
PASS: tst_h_dimscales3
PASS: tst_h_strings1
PASS: tst_h_vl
PASS: tst_h_rd_cmp
PASS: tst_h_dimscales4
PASS: tst_h_strings2
FAIL: tst_h_dimscales1
PASS: tst_h_atts
PASS: tst_h_dimscales2
PASS: tst_h_dimscales
PASS: run_par_tests.sh
PASS: tst_h_vars2

```

Not obvious why tst_h_dimscales1 is failing. The code does not seem to depend on other tests. So WTF?

Because of this I am avoiding make -j, which is probably costing me a lot of time.

**Comment by edhartnett** [comment]
I have a PR up to fix this. It was a mistake in the name of the test file. By reusing the name of the test file from another test, make -j was confused.

**Comment by WardF** [comment]
Excellent! Does it result in any issues outside of the h5_test directory? I closed this issue since it was something we're aware of and weren't going to address, but fixing it via PR is great.  I'm catching up on esupport and cloud projects today but will take a look at this for the next clump of PR's.
