### ISSUE TITLE
Some problems with EXTRA_TESTS

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#608]
There is a configure option called extra_tests:

```
# Does the user want to do some extra tests?
AC_MSG_CHECKING([whether netCDF extra tests should be run (developers only)])
AC_ARG_ENABLE([extra-tests],
              [AS_HELP_STRING([--enable-extra-tests],
                              [enable some extra tests that may not pass because of known issues])])
test "x$enable_extra_tests" = xno || enable_extra_tests=yes
AC_MSG_RESULT($enable_extra_tests)
if test "x$enable_extra_tests" = xyes; then
   AC_DEFINE([EXTRA_TESTS], [1], [if true, run extra tests which may not work yet])
fi
AM_CONDITIONAL(EXTRA_TESTS, [test x$enable_extra_tests = xyes])

```
This was intended (when I added it) to default to disabled. Extra tests were tests that didn't currently pass, (plus a way to indicate to the ncdump Makefile.am that ctest.c and ctest64,c could not be generated in distcheck builds).

But somewhere along the way, extra_tests got turned on by default. All of the extra tests now pass, due to bug fixes in the library, so all test guarded as EXTRA_TESTS are really just ordinary tests.

The only remaining valid use is in the ncdump directory, in which EXTRA_TESTS is still useful, because with it (if it is off by default), you can do ./confugure && make distcheck.

So I am going to change the tests that are currently guarded by EXTRA_TESTS so they are no longer guarded. Then I will change the default of extra_tests back to disabled, and it can be used for tests which don't work. (For example if the user contributes a test that demonstrates a bug, Using extra_tests you can commit that test even without a fix.)

**Comment by DennisHeimbigner** [comment]
It is possible that extra_tests was at some point reinterpreted
to cover tests that take a long time to run (not quite the same
as large_tests, which IMO referred to file sizes.

**Comment by edhartnett** [comment]
There is one more important use of EXTRA_TESTS I forgot to mention above. It is used to determine how HDF5 files are closed by the netCDF-4 code:

```
#ifdef EXTRA_TESTS
   if (H5Pset_fclose_degree(fapl_id, H5F_CLOSE_SEMI))
      BAIL(NC_EHDFERR);
#else
   if (H5Pset_fclose_degree(fapl_id, H5F_CLOSE_STRONG))
      BAIL(NC_EHDFERR);
#endif /* EXTRA_TESTS */
```

If extra tests is enabled (the current default), then H5F_CLOSE_SEMI is used. This will cause an error if there is any HDF5 object left open in the file.

If extra_tests is not enabled, H5F_CLOSE_STRONG is used, which just closes the file and releases any resources without complaining.

The idea here was that the stricter checking would not be used by default. However, it always worked because netCDF-4 is good at cleaning up HDF5 objects. This is confirmed by valgrind testing and (more recently) by address sanitizer testing.

So I intend to just remove the use of EXTRA_TESTS here and always close using SEMI, since it's working well and has been for many years.
