### ISSUE TITLE
Function NC_mktmp returning result of incorrect type in libdispatch if file is read-only

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#612]
Here's one of the few remaining warnngs. @DennisHeimbigner I believe you will be interested in this one.

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -I/usr/local/zlib-1.2.11_mpich-3.2/include -I/usr/local/szlib-2.1/include -I/usr/local/hdf5-1.10.1/include -g -Wall -MT libdispatch_la-dutil.lo -MD -MP -MF .deps/libdispatch_la-dutil.Tpo -c dutil.c  -fPIC -DPIC -o .libs/libdispatch_la-dutil.o
dutil.c: In function ‘NC_mktmp’:
dutil.c:249:15: warning: return makes pointer from integer without a cast [-Wint-conversion]
        return (NC_EPERM);
               ^
```

The problem function is:

```
/**
Wrap mktmp and return the generated path,
or null if failed.
Base is the base file path. XXXXX is appended
to allow mktmp add its unique id.
Return the generated path.
*/

char*
NC_mktmp(const char* base)
{
    int fd;
    char* cvtpath = NULL;
    char tmp[NC_MAX_PATH];
#ifdef HAVE_MKSTEMP
    mode_t mask;
#endif

    /* Make sure that this path conversion has been applied */
    cvtpath = NCpathcvt(base);
    strncpy(tmp,cvtpath,sizeof(tmp));
    nullfree(cvtpath);
	strncat(tmp, "XXXXXX", sizeof(tmp));

#ifdef HAVE_MKSTEMP
    /* Note Potential problem: old versions of this function
       leave the file in mode 0666 instead of 0600 */
    mask=umask(0077);
    fd = mkstemp(tmp);
    (void)umask(mask);
#else /* !HAVE_MKSTEMP */
    {
#ifdef HAVE_MKTEMP
#ifdef _MSC_VER
        /* Use _mktemp_s */
	_mktemp_s(tmp,sizeof(tmp)-1);
#else /*!_MSC_VER*/
        mktemp(tmp);
	tmo[sizeof[tmp]-1] = '\0';
#endif
#else /* !HAVE_MKTEMP */
	/* Need to simulate by using some kind of pseudo-random number */
	{
	    int rno = rand();
	    char spid[7];
	    if(rno < 0) rno = -rno;
            snprintf(spid,sizeof(spid),"%06d",rno);
            strncat(tmp,spid,sizeof(tmp));
	}
#endif /* HAVE_MKTEMP */
#ifdef _MSC_VER
        fd=NCopen3(tmp,O_RDWR|O_BINARY|O_CREAT, _S_IREAD|_S_IWRITE);
#else
        fd=NCopen3(tmp,O_RDWR|O_CREAT|O_EXCL, S_IRWXU);
#endif
    }
#endif /* !HAVE_MKSTEMP */
    if(fd < 0) {
       nclog(NCLOGERR, "Could not create temp file: %s",tmp);
       return (NC_EPERM);
    } else
	close(fd);
    return strdup(tmp);
}

```

This function is supposed to return a pointer to an array of char, but if the file is read-only the function returns NC_EPERM, which is what is generating the warning.

This function is used in only a few places:

```
find . -name "*.c" |xargs grep NC_mktmp
./libdispatch/dutil.c:NC_mktmp(const char* base)
./oc2/ocinternal.c:    tmppath = NC_mktmp(path);
./oc2/ocinternal.c:        tmppath = NC_mktmp(path);
./libdap4/d4file.c:        newpath = NC_mktmp(path);
```

When I look at some of the uses of this function, I see that the return code is not checked (from ocinternal.c):

```
        tmppath = NC_mktmp(path);
        free(path);
```

So, what should be done?

IMO, best would be to change NC_mktmp to pass the pointer to the resulting char array as a parameter, and to return an integer error code like other netCDF functions. Then the return code can be checked and handled.

I am surprised that this code has never generated a seg fault.

**Comment by DennisHeimbigner** [comment]
I think that there is an as yet unmerged pr that fixes this as a side effect.

**Comment by WardF** [comment]
Which one? I'm doing them piecemeal as I can, but also staying on top of the cloud stuff and AMS/AGU as well.  If I know which PR I'll make sure it goes in in the next bundle.

**Comment by DennisHeimbigner** [comment]
It is the one that pulls out common dap4/dap2 common code.

**Comment by WardF** [comment]
I thought I had merged that one, or was that the one with the OSX issue... yes I think it was maybe? I'll go look.

**Comment by DennisHeimbigner** [comment]
I stand corrected, the relevant pr https://github.com/Unidata/netcdf-c/pull/477
was merged. So it is a legitimate error. It should return NULL instead of EPERM.,

**Comment by edhartnett** [comment]
FYI My code coverage indicates this execution path is not run during testing.

**Comment by edhartnett** [comment]
Dennis, do you want me to submit a fix for this? I can knock it off in 15 now that it's figured out...

**Comment by edhartnett** [comment]
I put up a PR with a simple fix. Now it returns NULL, and the three places in the code which call this function check for NULL return and goto fail. But I am going to take the PR down because I actually don't know if the error handling is correct. For example one call of this function (with no modifications from me) is in d4file.c:

```
	/* Create the unique cookie file name */
        newpath = NC_mktmp(path);
        free(path);
	if(newpath == NULL) {
	    fprintf(stderr,"Cannot create cookie file\n");
	    goto fail;
	}

```

So this code seems like it is already able to handle a NULL return. But a closer inspection shows that it will print out an error message and the function will still return 0, because ret is not set to an error code. Is this intended? I'm not sure whether inability to create a cookie file is indented to be a non-fatal error...

**Comment by edhartnett** [comment]
Looks like @DennisHeimbigner took care of this in his last set of changes. Thanks Dennis! ;-)
