### ISSUE TITLE
nctest fails make -j check due to unrecorded dependency between tests

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#614]
The nctest directory fails a make -j check:

```
FAIL: compare_test_files.sh
PASS: tst_rename
PASS: nctest
```
The reason is that compare_test_files.sh compares the test files produced with nctest with some reference files. So nctest has to run first.

This can be communicated to the autotools system by adding this to the Makefile.am (documented here https://www.gnu.org/software/automake/manual/html_node/Parallel-Test-Harness.html):

```
# compare_test_files depends on nctest executing first.
compare_test_files.log: nctest.log 

```

Once added, make -j check works in nctest.

PR will be up shortly.

(I would like to get make -j check working for the core library, to speed builds.)

**Comment by DennisHeimbigner** [comment]
IMO trying to get  make -j working is a rabbit hole. I believe
that there are too many inter-test dependencies.

**Comment by edhartnett** [comment]
I think it is easier than you suspect. In fact, I am nearly there.

With this fix and the nc_test4 one, make -j check should work for
--disable-dap --disable-utilities. (Haven't tried DAP at all yet.)

I have taken a look at the ncdump directory (where all the dependencies
are) and actually it looks like it will just take a few minutes to fix, and
then make -j will work for the utilities too.

Two simple rules:
1 - all tests must produce unique output data (i.e. no sharing file names
between tests).
2 - dependencies must be noted in the Makefile.am like this:

TEST2.log: TEST1.log

Where TEST2 and TEST1 are two tests, and this line ensures that TEST2 will
only be run after TEST1 is complete. (As many dependancies as needed may be
used). The ".log" is automake magic. (Because running TEST1 produces a file
called TEST1.log).

In a previous PR a couple weeks ago, I combined two tests to remove the
dependency, but that is not necessary. Any arbitrary dependencies can be
easily specified and we're done.

I remember struggling with this years ago, but it seems so simple now! ;-)

I seem to recall, Dennis, that once you suggested moving all utilities
tests to a util_test directory, to help manage the dependancies. If you're
still interested, I could do that as well, to help organize the code. But I
don't think it will be needed to get make -j check working for the
utilities.

Ed
