### ISSUE TITLE
Should nc_open() return error if incorrect binary flag is used?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#622]
This is related to #392.

Consider the following code:

```
      if (nc_create(FILE_NAME, NC_CDF5, &ncid)) ERR;
      if (nc_close(ncid)) ERR;
      if (nc_open(FILE_NAME, NC_NETCDF4, &ncid)) ERR;

```

The first two lines create and close a CDF5 file.

The third line opens it, specifying NC_NETCDF4. Currently, the (incorrect) NC_NETCDF4 flag is ignored.

Should the nc_open() instead return error?

Note that it is not necessary for the user to specify any binary format anyway. But if the user does specify a format, what should the library do?

1 - Ignore the flag (current behavior).
2 - Return error.

I think 2 is the correct answer. Anyone else agree or disagree? 

I am willing to be convinced, because changing this will no doubt break some user code somewhere. (It breaks several of our tests, so why should our users be any more careful?)

But I am not willing to accept the incorrect answer out of mere expediency. If the correct answer is to change it, let's change it and deal with it.

Note that the work for this is mostly done on this branch: https://github.com/NetCDF-World-Domination-Council/netcdf-c/tree/ejh_no_netcdf4_create.

It was not hard to accomplish, but I want to make sure it's really what we want to do before submitting a PR.

**Comment by WardF** [comment]
Breaking user code is a pretty good reason to consider avoiding changes. Is there a demonstrated problem with the historic behavior?

**Comment by edhartnett** [comment]
Nope. Not really. That's why I elevated this to it's own issue. (BTW returning NC_ENOTBUILT when part of the library is not built will also change behavior of user code.)

But if the user does:

`nc_open(FILE, NC_CDF5, &ncid);
`
And we silently open a netCDF-4 file (because that is what FILE is), is that a problem? The user could be excused for thinking he or she is specifically opening a CDF5 file.

**Comment by WardF** [comment]
Since the flag seems to be ignored in the first place, does it serve a purpose at all? I mean, we can't realistically remove it at this point but it doesn't seem to do anything.  It opens the file properly even if the specified type is incorrect.  Perhaps the better thing to do would be to document and emphasize that the file type flag for `nc_open()` is deprecated?  As well as officially deprecating it?

Sorry for my brevity, don't want to let this go ignored but also juggling several different things :).

**Comment by edhartnett** [comment]
I am open to just ignoring it. That's why I opened the ticket.

Anyone else want to offer an opinion?

**Comment by gsjaardema** [comment]
Note that there is a place where the flag is currently used in `NC_open()`.  If `NC_PNETCDF` is passed, then we have the following:
```
   } else if(model == NC_FORMATX_NC3) {
      cmode &= ~NC_NETCDF4; /* must be netcdf-3 (CDF-1, CDF-2, CDF-5) */
      /* User may want to open file using the pnetcdf library */
      if(cmode & NC_PNETCDF) {
         /* dispatch is determined by cmode, rather than file format */
         model = NC_FORMATX_PNETCDF;
      }
```
If `NC_PNETCDF` or `NC_MPIIO` is not passed in parallel for a `non-netcdf4` file, then the file uses the `NC3_dispatch_table` and parallel doesn't work correctly.  

I think this is an error and needs to be fixed before the flag can be ignored.  This is the only place I have found where the flag to `nc_open_par` is required.

**Comment by DennisHeimbigner** [comment]
One thing to remember is that after opening a file, the user can
invoke nc_inq_format &/or nc_inq_format_extended to see
what the file really is.

As noted by Greg, remember that there are several mode flags like MMAP and MPIIO/PNETCDF
and MEMORY that still needed to be specified in the mode flag.

Bottom line for me. I say we document which flags are ignored on nc_open() and then
continue to ignore them.

Also, off-hand is it possible to look a netcdf-4 file and determine if it is a
netcdf-4-classic?

p.s. In retrospect, making NC_PNETCDF be an alias for NC_MPIIO was an error on my part.
It makes it look like a mode flag when it is not.

**Comment by edhartnett** [comment]
OK, what I am hearing is that the answer is to just document and ignore.

That's cool.

There is going to be some unavoidable confusion from the fact that some mode flags are format-related, some are not. Some can be used for both open and create, and some just for create.

The new flag NC_PIO will be like NC_PNETCDF in that multiple binary formats can be read by PIO. (All of them, eventually). So the confusion will continue. I will document carefully.
