### ISSUE TITLE
Test ncdump/tst_bug324.c should be moved to nc_test4 directory

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#628]
This test has nothing to do with ncdump, but somehow ended up in the ncdump directory. 

It's a straight-up netCDF-4 test related to an old bug. It's a good test though.

I will move it in a future PR.

**Comment by WardF** [comment]
I think it was originally tied into a shell script and was never migrated.  Similar to tst_bug321.  But I don't recall exactly.

**Comment by edhartnett** [comment]
I will do this after PR #633 gets merged.
