### ISSUE TITLE
After recent merge, pnetcdf build no longer working

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#647]
In my CI, the pnetcdf build just broke:

```
ncpdispatch.c: In function ‘NCP_inq_var_all’:
ncpdispatch.c:1176:8: error: ‘options_maskp’ undeclared (first use in this function)
     if(options_maskp) return NC_ENOTNC4;
        ^~~~~~~~~~~~~
ncpdispatch.c:1176:8: note: each undeclared identifier is reported only once for each function it appears in
ncpdispatch.c: At top level:
ncpdispatch.c:1596:1: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
 NCP_set_var_chunk_cache,
 ^~~~~~~~~~~~~~~~~~~~~~~
ncpdispatch.c:1596:1: note: (near initialization for ‘NCP_dispatcher.def_var_filter’)
ncpdispatch.c:1597:1: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
 NCP_get_var_chunk_cache,
 ^~~~~~~~~~~~~~~~~~~~~~~

```

When I look at the code, it seems like it could never have compiled. options_maskp is not declared, but is used in the code.

@WardF do you think you have a travis pnetcdf build? If so, can you check to see why it didn't catch this?

**Comment by edhartnett** [comment]
I took a lot at travis and I see no pnetcdf build. Also no HDF4 build, unless I am mistaken.

My I suggest that you guys take advantage of jenkins to add a local CI in addition to the travis one? (Or you can each set up jenkins on your desktop and have your own.)

I'm happy to share my jenkins xml file with 30 different autotools and cmake builds (and that number goes up almost daily as I add new test builds).

Instead of catching these problems weeks after the coding was done, you can catch them minutes after they occur, making them far cheaper and easier to fix.

**Comment by DennisHeimbigner** [comment]
I believe that Ward's cdash testing does this.

**Comment by edhartnett** [comment]
Then perhaps you need to add pnetcdf builds to CDash?
