### ISSUE TITLE
--enable-hdf4 --disable-utilities does not work

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#655]
Looks like one of the CDF5 tests used the utilities.

I will put up a fix after current PRs have been merged.

**Comment by edhartnett** [comment]
I can't reproduce so either this was not real or has already been fixed.

**Comment by WardF** [comment]
Glad I'm not the only one that happens to.

**Comment by edhartnett** [comment]
Reopening. It was HDF4 not CDF5.

I've got a fix, will be in my next PR.
