### ISSUE TITLE
Should DAP program ncdump/ocprint be installed or not?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#661]
I see this in the ncdump Makefile.am:

```
# Conditionally build the ocprint program, but do not install
if ENABLE_DAP
bin_PROGRAMS += ocprint
ocprint_SOURCES = ocprint.c
endif
```

If ocprint is not supposed to be installed, this should say:
`noinst_PROGRAMS += ocprint
`
@DennisHeimbigner is ocprint intended to be installed? Currently I believe it is being installed, in spite of what the comment says.

**Comment by DennisHeimbigner** [comment]
I have slowly been moving the oc2 directory into libdap2.
This is part of that. I guess it should be marked as noinst_...

**Comment by edhartnett** [comment]
OK, that's what I guessed. I've got it changed in the PR I will put up shortly. Thanks for the quick answer!
