### ISSUE TITLE
Take out old, no-longer-working ming DLL stuff in autotools build, leaving full support for cygwin

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#662]
Before @WardF came along and wrote the CMake build system, I had attempted to build the netcdf dll with Cygwin and also with ming32.

I had various degrees of success, but it was a real pain, and now I am happy that the CMake build system handles Windows.

However, my attempts left a lot of cruft in the build files. I will remove it as part of my make -j check changes.

**Comment by edhartnett** [comment]
But I see some work since then on at least the cygwin build.

Let me get my old windows machine out of the closet and I will try a Cygwin build...

**Comment by WardF** [comment]
@DennisHeimbigner still uses cygwin and I believe autotools therein.

**Comment by DennisHeimbigner** [comment]
I routinely use cygwin, but not mingw. I also use cmake with visual studio.
