### ISSUE TITLE
CMake build doesn't handle szip in separate directory

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#666]
I believe that the CMake build has problems when HDF5 and szip are in different directories.

In order to support all my CI testing, I install each package in its own directory under local. This leads to lots of CPPFLAGS and LDFLAGS to get all my libraries in the autotools builds, but allows me to mix and match freely.

When I try this with the CMake build, I can't get it to find the szlib library. So instead I installed zlib, szlib, and hdf5 all in the same place, and use that for CMake. Now everything works.

@WardF you may wish to simply close this ticket. Not sure how important it is that the CMake build deal with this corner case.

**Comment by WardF** [comment]
You can pass CMAKE_PREFIX_PATH multiple directories; for example, if everything were in a single directory you could pass -DCMAKE_PREFIX_PATH=/custom/lib/install .  I can never remember if multiple directories are colon or semicolon delineated, however.
