### ISSUE TITLE
Recent merges broke make distcheck

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#671]
A file is left in the dap4_test directory. I will submit a fix shortly.

```
ERROR: files left in build directory after distclean:
./dap4_test/tmp_1025
Makefile:981: recipe for target 'distcleancheck' failed
```

**Comment by DennisHeimbigner** [comment]
Do not try to fix this. There is a bigger issue here. The fact that you are seeing this
means that DISKLESS support is disabled.

**Comment by edhartnett** [comment]
OK I will take down PR.

But can you please fix soon @DennisHeimbigner? It is breaking the make distcheck runs of my CI, and those are very handy to have. In fact, if you guys had them running, this problem would have showed up before these changes were merged. ;-)

**Comment by DennisHeimbigner** [comment]
I routinely use make distcheck. However we never run with DISKLESS turned off?

**Comment by DennisHeimbigner** [comment]
My proposed fix is to modify defile.c
The modified file is attached for you to test.
[d4file.zip](https://github.com/Unidata/netcdf-c/files/1493086/d4file.zip)

**Comment by edhartnett** [comment]
OK, I get it. This is not test output but output of DAP and should have been removed by DAP?

I used this to get a broken distcheck. It is a parallel build:

`make distclean && autoreconf -i && CC=mpicc CFLAGS='-Wall -g' CPPFLAGS='-I/usr/local/zlib-1.2.11_mpich-3.2/include -I/usr/local/szlib-2.1_mpich-3.2/include -I/usr/local/hdf5-1.10.1_mpich-3.2/include' LDFLAGS='-L/usr/local/zlib-1.2.11_mpich-3.2/lib -L/usr/local/szlib-2.1_mpich-3.2/lib -L/usr/local/hdf5-1.10.1_mpich-3.2/lib' ./configure && CC=mpicc CFLAGS='-Wall -g' CPPFLAGS='-I/usr/local/zlib-1.2.11_mpich-3.2/include -I/usr/local/szlib-2.1_mpich-3.2/include -I/usr/local/hdf5-1.10.1_mpich-3.2/include' LDFLAGS='-L/usr/local/zlib-1.2.11_mpich-3.2/lib -L/usr/local/szlib-2.1_mpich-3.2/lib -L/usr/local/hdf5-1.10.1_mpich-3.2/lib' make distcheck`

This breaks on master right now like this:

```
rm -f Makefile
ERROR: files left in build directory after distclean:
./dap4_test/tmp_1025
Makefile:981: recipe for target 'distcleancheck' failed
```

I tried your fix, but it didn't work. Same problem, a tmp_ file left over after make distcheck.

Here's some output with the changed d4file.c you sent:
[make_output_2.txt](https://github.com/Unidata/netcdf-c/files/1493193/make_output_2.txt)
[config.log](https://github.com/Unidata/netcdf-c/files/1493196/config.log)

**Comment by DennisHeimbigner** [comment]
I am completely baffled. You should see that file only in one of two ways.
1. The url being used is prefixed with [debug] or [copy]
2. the program was stopped before nc_close() was called.
As a speculation, try making without -j flag

**Comment by edhartnett** [comment]
Not using the -j flag yet. (Can't start until outstanding PR is merged.)

Do we even need this to work? My goal was just to make sure PIO doesn't break anything. And for that I need it to work with a regular build of the distribution, and a distcheck that builds with parallel. So I should be using:

`make distclean && autoreconf -i && CFLAGS='-Wall -g' CPPFLAGS='-I/usr/local/zlib-1.2.11/include -I/usr/local/szlib-2.1/include -I/usr/local/hdf5-1.10.1/include' LDFLAGS='-L/usr/local/zlib-1.2.11/lib -L/usr/local/szlib-2.1/lib -L/usr/local/hdf5-1.10.1/lib' ./configure && CC=mpicc CFLAGS='-Wall -g' CPPFLAGS='-I/usr/local/zlib-1.2.11_mpich-3.2/include -I/usr/local/szlib-2.1_mpich-3.2/include -I/usr/local/hdf5-1.10.1_mpich-3.2/include' LDFLAGS='-L/usr/local/zlib-1.2.11_mpich-3.2/lib -L/usr/local/szlib-2.1_mpich-3.2/lib -L/usr/local/hdf5-1.10.1_mpich-3.2/lib' make distcheck`

And that actually does work. So my bad. I will close this ticket. Why a distribution built with mpicc does not work is probably a mystery we need not solve.
