### ISSUE TITLE
szip test commented out at the end of tst_vars3.c

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#705]
No point in commented out test code. If this is a good test I will get it working. If not, I will delete it.

**Comment by edhartnett** [comment]
Well the problem here is the test uses nc_def_var_szip().

But there is no such function. ;-) Apparently it was removed at some point. Does anyone know why?

So szip is a read-only thing for netCDF? NetCDF can't create szip compressed files? @WardF is this something you did or something I did and have forgotten?

Do we not create szip compressed files due to concerns about it's license?

**Comment by DennisHeimbigner** [comment]
The szip situation is now this.
1. szip support was folded into  nc_def_var_filter
2. we now have access to read/write open-source szip libraries, so there
   is no longer any reason to make szip read-only.
Should I restore nc_def_var_szip as a simple wrapper around nc_def_var filter?

**Comment by edhartnett** [comment]
Howdy Dennis!

How would I call nc_def_var_filter to turn on szip? Can you give me a sample?

Not sure if we need nc_def_var_szip(), but I can change the test code to use nc_def_var_filter().

**Comment by DennisHeimbigner** [comment]
IMO we should not define nc_def_filter_szip and force use of use nc_def_var_filter instead.
Note that nc_inq_var_szip still exists.
To do the equivalent of nc_def_var_szip:
	unsigned int params[2];
	params[0] = mask;
	params[1] = bits_per_pixel;
	status = nc_def_var_filter(ncid,varid,H5_FILTER_SZIP,2,params);
where H5_FILTER_SZIP == 4

**Comment by DennisHeimbigner** [comment]
Actually, there is a test in nc_test4  called test_szip.c

**Comment by edhartnett** [comment]
I will convert test code in tst_vars3.c to use nc_def_var_filter().

I will not re-add nc_def_var_szip(). I will put this szip example in the documentation as an example for nc_def_var_filter(), and I will mention it in the nc_inq_var_szip() documentation.

Thanks!

**Comment by edhartnett** [comment]
When working on this test I encountered an szip filter bug. I will add as a separate issue.
