### ISSUE TITLE
Remove unused function nc_use_parallel_enabled() in libsrc4/nc4file.c

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#714]
In libsrc4/nc4file.c we have:

```
#ifdef USE_PARALLEL4
int
nc_use_parallel_enabled()
{
   return 0;
}
#endif /* USE_PARALLEL4 */

```

This is both incorrect (since it should return 1) and also completely unused anywhere. I will remove it.

**Comment by wkliao** [comment]
nc_use_parallel_enabled() is used by netcdf-fortran.
Without it, netcdf-fortran will disable the parallel feature, even if it is enabled in the netcdf-c.

**Comment by edhartnett** [comment]
How is it used?

**Comment by wkliao** [comment]
Its availability is checked in [line 465](https://github.com/Unidata/netcdf-fortran/blob/6c4af0420389a712c215f1b5903f4adef3f1bdeb/configure.ac#L465) of configure.ac and sets the value of [nc_has_parallel](https://github.com/Unidata/netcdf-fortran/blob/6c4af0420389a712c215f1b5903f4adef3f1bdeb/configure.ac#L482)

**Comment by amckinstry** [comment]
This is also true for netcdf-cxx4-4.3.0

**Comment by edhartnett** [comment]
These packages should use a real parallel function, like nc_create_par(). We should not be adding useless functions for this purpose when a perfectly reasonably alternative already exists.

**Comment by wkliao** [comment]
I agree. The latest master branch of netcdf-fortran is now checking netcdf_meta.h for the value of [NC_HAS_PARALLEL4](https://github.com/Unidata/netcdf-fortran/blob/f0e060c42182ef72a28d61268a0fa8e583666869/configure.ac#L65-L72) to determine whether or not the underneath netcdf-c is built with parallel I/O support.

However, removing nc_use_parallel_enabled() from netcdf-c can be a problem for current/older versions of netcdf-fortran and netcdf-cxx to build with parallel I/O enabled when using new netcdf-c.
