### ISSUE TITLE
nc_copy_var()/nc_copy_add() documentation mising

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#716]
Not only did the functions not have doxygen comments for these functions, but the dcopy.c file was also not being included in the documentation build.

I have fixed these on my current PR.

**Comment by DennisHeimbigner** [comment]
Actually, there are probably a number of new files not included,
I tend to forget to do this.

**Comment by edhartnett** [comment]
It's cool.

In my current PR I have cleared all doxygen warnings for libsrc4, libdispatch, and netcdf.h.

By getting to netcdf.h I was able to see all public functions that don't have documentation. Only nc_free() and nc_free_mp() remain undocumented.
