### ISSUE TITLE
Trying to write with count of 0 may fail for HDF5 parallel collective access

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#719]
I have a test, test_pioc_putget.c, which does all combinations of put/get calls.

When calling put_var_*() on an empty record var, the function should do nothing. 

But when called with netCDF-4 parallel, in collective mode, I get this:

```
HDF5-DIAG: Error detected in HDF5 (1.10.1) MPI-process 3:
  #000: H5Dio.c line 269 in H5Dwrite(): can't prepare for writing data
    major: Dataset
    minor: Write failed
  #001: H5Dio.c line 345 in H5D__pre_write(): can't write data
    major: Dataset
    minor: Write failed
  #002: H5Dio.c line 791 in H5D__write(): can't write data
    major: Dataset
    minor: Write failed
  #003: H5Dmpio.c line 758 in H5D__chunk_collective_write(): write error
    major: Dataspace
    minor: Write failed
  #004: H5Dmpio.c line 686 in H5D__chunk_collective_io(): couldn't finish linked chunk MPI-IO
    major: Low-level I/O
    minor: Can't get value
  #005: H5Dmpio.c line 1025 in H5D__link_chunk_collective_io(): couldn't allocate total chunk address arraybuffer
    major: Dataset
    minor: Can't allocate space
  C-c C-c
```

I added a check in the PIO for a zero count, and now it works. Not sure if there is a check somewhere for this case without PIO. I can't see such a check in the code. (But PIO is directly calling the NC4_put_vara() functions, so the check may be occurring somewhere in the dispatch layer.)

I will add a test to check.

**Comment by DennisHeimbigner** [comment]
This rings a bell. Some time ago we had an issue about
parallel writing with a zero-length dimension. This might be related.

**Comment by edhartnett** [comment]
Yes, this has been fixed in netcdf since I filed this ticket. I just added some tests that confirm this works. I will close this ticket.
