### ISSUE TITLE
CDF5 build broken on master

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#723]
When I clone master and build like this:

 `autoreconf -i && CPPFLAGS='-I/usr/local/hdf5-1.10.1/include' LDFLAGS='-L/usr/local/hdf5-1.10.1/lib' CFLAGS='-g -Wall' ./configure --disable-dap --enable-cdf5 && make -j check`

I get this build error:

```
tst_global_fillval.c:46:13: error: lvalue required as increment operand
  num_formats++;
             ^~

```

@WardF I believe this is a result of a change made to get visual studio to build.

Do you have CDF5 testing turned on in any of your CI runs? I am surprised they did not catch this.

I will have a fix up shortly that works on linux. Not sure what the visual studio issues were, so Ward you are going to have to look at my changes and see if they are OK for VS.

**Comment by WardF** [comment]
Thanks for catching it, I thought I had turned it on but that branch never got pulled? I'm fixing this as  part of a pull request to turn on CDF5 in travis, so that fix will be up shortly. Thanks!

**Comment by edhartnett** [comment]
This has been fixed and CDF5 builds fine for me now on master. Thanks!
