### ISSUE TITLE
performance problems when opening and closing a lot of netCDF files which contain compound data

### ISSUE THREAD

**Issue by dierssen** [Unidata/netcdf-c#73]
Hi.

Jeff Whitaker asked me to make an issue here regarding some perfomance issues I encountered. I was reading a few thousand netCDF files (opening and closing sequentially) when my Python program suddenly slowed down. Opening a file suddenly took more than 1 minute. At the same moment I noticed memory leakage. However, it only occurred when I was reading in files which contain compound data structures.

I made a similar program in C, to check if I got the same problem. I did not see the memory leakage anymore, but the significant slow down was still present after opening and closing around 3000 or 4000 times the file. It is pretty reproducable. I do not experience any problems when using the HDF library.

My C test program is:

``` c
#include <stdlib.h>
#include <stdio.h>
#include <netcdf.h>

#define FILE_NAME "test.nc"

int main()
{
    int retval;
    int ncid;
    int grp_ncid;
    int index;
    int rh_id;

    struct s1 {
      double i1;
      double i2;
    };
    struct s1 compound_data[1024][512];

    for ( index = 0; index < 8000; index++ ) {

        retval = nc_open( FILE_NAME, NC_NOWRITE, &ncid );

        (void) printf( "attempt %d\n", index);

        retval = nc_inq_ncid(ncid, "group0", &grp_ncid);
        retval = nc_inq_varid (grp_ncid, "data0", &rh_id);
        retval = nc_get_var(grp_ncid, rh_id, &compound_data[0][0]);

        printf("i1=%f\n", compound_data[0][0].i1);

        retval = nc_close( ncid );
    }

    return retval;
};
```

My Python code (which creates the file in the first place, but also shows the slowdown):

``` python
import netCDF4 as nc
import numpy as no
import time

#create test file
filename = "test.nc"
nc_file = nc.Dataset(filename, 'w')
nc_file.createDimension('nRows', 1024)
nc_file.createDimension('nColumns', 512)
for group_nr in range(10):
    nc_group = nc_file.createGroup("group{}".format(group_nr))
    complex128 = np.dtype([('real',np.float64),('imag',np.float64)])
    complex128_t = nc_group.createCompoundType(complex128,'complex128')
    for nr in range(20):
        cheb_data = np.ndarray(shape=(1024,512), dtype=complex128_t)
        cheb_data['real'] = np.ones((1024,512)) * 8.0
        cheb_data['imag'] =np.ones((1024,512)) * 5.0
        var = nc_group.createVariable("data{}".format(nr), complex128_t, dimensions=('nRows', 'nColumns',))
        var[:] = cheb_data
nc_file.close()

#read test file number of times
index = 0

for i in range(12000):
    start_time = int(round(time.time() * 1000))
    ds_root = nc.Dataset(filename, 'r')
    ds_root.close()
    stop_time = int(round(time.time() * 1000))
    index+=1
    print("{}: {}".format(index, stop_time-start_time))
```

The libraries we use are Python 2.7.3, numpy 1.7.0 and netCDF4 1.0.8 (ncdf4lib: 4.3.1.1, hdf5lib: 1.8.10).

So, I do have a workaround (in using the HDF library), but I do think the issue is important enough to mention. Reading in a lot of files which contain compound data should not give problems. And the problem is pretty is to reproduce.

Well, I just wanted to let you guys know!

Greetings Werner.

**Comment by jarethholt** [comment]
Hi,

Have there been any updates to this issue?  I'm running into it (well, the same HDF5 error at least).  I'm reading data from a lot of CSV files and saving to a single netCDF, so I'm not opening and closing the file in between.  Python also never takes up more than 50MB of memory, and all processes total ~2.5 GB out of 8, so I don't think it's a memory issue.  (The final variable should have total size ~ 160x1826x14 ~ 4 million floats ~ 250 MB, so it's odd that the python process isn't taking up more memory, actually.)

I can't post all the CSV files and I'm starting on a minimal working example, but here's my script:
https://gist.github.com/jarethholt/b7dfd4f5c4980faf1374

**Comment by edwardhartnett** [comment]
OK, this is a very old issue. I'm wondering if this is still relevant or if this should be closed.

I believe there was a significant refactoring of the compound data structure handling by @DennisHeimbigner which fixed memory leaks and recursion problems...

**Comment by WardF** [comment]
Happy to reopen it if need be.
