### ISSUE TITLE
New var name in nc_rename_var() is not normalized for utf8. Should it be?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#742]
In nc_rename_dim() the new name is run through nc_utf8_normalize().

But this doesn't happen with nc_rename_var().

Shouldn't it?

**Comment by DennisHeimbigner** [comment]
yes, it should be normalized.

**Comment by edhartnett** [comment]
What kind of string can I pass to make sure that normalization is taking place?

That is, what string can I pass that comes out differently after being normalized?

I would like to write some tests before fixing...

**Comment by DennisHeimbigner** [comment]
There should be a utf8 test case that tests normalization.

**Comment by edhartnett** [comment]
OK, I will hunt one down and add a test.

**Comment by DennisHeimbigner** [comment]
not obvious we need a rename normalization test specifically sine i presume you will use same
name check code used in e.g. nc_def_var

**Comment by edhartnett** [comment]
If we had a rename normalization test then this bug would have been noticed before. So of course we need a test for it.

**Comment by DennisHeimbigner** [comment]
I am confused. Did normalization fail or was it just missing?

**Comment by edhartnett** [comment]
Normalization is actually happening as I've just confirmed with a test. I will add the test to my current PR. When it's merged this ticket will be closed.
