### ISSUE TITLE
nc4_rec_detect_need_to_preserve_dimids() incorrectly decides that all new vars need to preserve dimids

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#745]
In nc4hdf5.c we have function nc4_rec_detect_need_to_preserve_dimids() which contains this code:

```
         /* Did the user define a dimension, end define mode, reenter define
          * mode, and then define a coordinate variable for that dimension?
          * If so, dimensions will be out of order. */
         if (var->is_new_var || var->became_coord_var)
         {
            LOG((5, "%s: coord var defined after enddef/redef", __func__));
            *bad_coord_orderp = NC_TRUE;
            return NC_NOERR;
         }
```

However this if statement is true for all newly created coord vars, not just ones that were created out of order. So this code causes the optional dimids attribute to be used:

```
   if (nc_set_default_format(format, NULL)) ERR;
   if (nc_create(path, 0, &ncid)) ERR;
   if (nc_def_dim(ncid, LAT, DIM_LEN, &dims[0])) ERR;
   if (nc_def_var(ncid, LAT, NC_INT, VAR_RANK, dims, &varid)) ERR;
   if (nc_def_var(ncid, RH, NC_FLOAT, VAR_RANK, dims, &var2id)) ERR;
   if (nc_enddef(ncid)) ERR;    /* not necessary for netCDF-4 files */
   if (nc_put_var_int(ncid, varid, lats)) ERR;
   if (nc_put_var_float(ncid, var2id, rh)) ERR;
   if (nc_close(ncid)) ERR;
```

Not sure yet if this should be corrected in code, or the code left as it is, and the comments corrected.

**Comment by DennisHeimbigner** [comment]
i would be very careful about changing this.
i have noted a couple of other miscommented funtions like this.

**Comment by edhartnett** [comment]
I am proceeding with extreme care.

However, I have also discovered many problems with renames of dims and coordinate vars. So there is a lot of improvement possible here.

What I am doing is ensuring the simple cases are working perfectly and then adding complexity.

However, in this case, everything has to work with or without this optional attribute. So I am not messing with it yet, but just making sure everything works as it should when this att is present.

**Comment by DennisHeimbigner** [comment]
we have had a number of problems with dim/coord rename, so an improvements you can make
will be much appreciated.

**Comment by edhartnett** [comment]
This got fixed when I did all those rename and other dim/var fixes for various corner cases. I will close this issue.
