### ISSUE TITLE
libnetcdf.settings

### ISSUE THREAD

**Issue by nschloe** [Unidata/netcdf-c#75]
This `libnetcdf.settings` file, what is it there for? It's not for machine reading I suppose, so installing it into `lib/` is really exaggerated. If anything it should be in `CMAKE_INSTALL_DOCDIR`.

**Comment by opoplawski** [comment]
I have to comment that this is a strange thing to do.  Not sure why the need to invent yet another mechanism to pass on library settings when several already exist (pkg-config, cmake files).
