### ISSUE TITLE
CI warning for libsrc/dim.c

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#756]
Here's an interesting warning about dim.c in the CI LGTM scan...
```
Source root/libsrc/dim.c
        if(ncp->flags & NC_64BIT_DATA) {/*CDF-5*/
            if((sizeof(size_t) > 4) && (size > X_UINT64_MAX - 3)) /* "- 3" handles rounded-up size */

Comparison is always false because size <= 18446744073709552000.

```

**Comment by WardF** [comment]
Thanks; going to close this since warnings are low priority and may not merit a dedicated issue, but we can regenerate warnings as need bevia LGTM :)
