### ISSUE TITLE
Missing NC_HAVE_META_H define

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#761]
The netcdf.h include file no longer defines "NC_HAVE_META_H".  I had been using that define to determine whether the netcdf_meta.h include file existed and could be included.  Without that define, I am not sure how to make this decision.

Is this an intentional change and if so, what is the recommended practice for determining at compile time whether the netcdf_meta.h file exists.

**Comment by gsjaardema** [comment]
This was removed in 4de61e21f26c2da3b7d130c822ef75cfae2ff206

**Comment by WardF** [comment]
I will revert this.

**Comment by edhartnett** [comment]
Do not revert all changes from that PR.

Let's just put NC_HAVE_META_H back...

**Comment by edhartnett** [comment]
In fact, it is just one line of code. I will submit a PR with just that. Please don't revert the mentioned PR...

**Comment by edhartnett** [comment]
Also, of course, we should add something to a test so we know if we break this. I will also add a comment...

**Comment by WardF** [comment]
Yes I wasn’t going to revert the PR, just the change mentioned. I have a branch I’m merging in that I just tacked it onto and will merge in a bit.

**Comment by edhartnett** [comment]
OK, great. Add some documentation too, for future reference...

**Comment by edhartnett** [comment]
BTW @gsjaardema I gather from your comments that you don't use autoconf with your code? Because autoconf has a super-easy macro to determine if a header file is present.

If so, you should probably upgrade to autoconf/automake. It only takes about a day, and will obviate the need for extra macros in the netcdf.h file.

**Comment by gsjaardema** [comment]
I am very aware of autoconf and avoid it like the plague.  I much prefer CMake which will also determine if a header file is present. However, I think that the presence of the `NC_HAVE_META_H` define obviates the need for the test in either build system.  

My exodus library is also embedded into a couple other systems (one using CMake and one using BJam), so it is much easier to have a build-system agnostic method of determining whether the include file exists.

I also question whether `netcdf.h` itself should just contain the symbols in `netcdf_meta.h` or do the `#include<netcdf_meta.h>` itself.
