### ISSUE TITLE
.gitignore needs to include these files...

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#767]
.gitignore needs to include these files.

Because they are not listed in gitignore, git will not let me change branches on the code. For example if I check out a revision and do a build, and then do a make distclean, and then try to checkout a different revision, I get this error:

```
ed@mikado:~/tmp/n1$ git checkout f443e74e1d6424f965ee4a8832155cc67bd3e1b5
error: Your local changes to the following files would be overwritten by checkout:
	Makefile.in
	aclocal.m4
	config.guess
	config.h.in
	config.sub
	configure
	dap4_test/Makefile.in
	docs/Makefile.in
	docs/images/Makefile.in
	examples/C/Makefile.in
	examples/CDL/Makefile.in
	examples/Makefile.in
	h5_test/Makefile.in
	include/Makefile.in
	install-sh
	libdap2/Makefile.in
	libdap4/Makefile.in
	libdispatch/Makefile.in
	liblib/Makefile.in
	libsrc/Makefile.in
	libsrc/ncx.c
	libsrc4/Makefile.in
	libsrcp/Makefile.in
	ltmain.sh
	m4/libtool.m4
	nc_test/Makefile.in
	nc_test4/Makefile.in
	ncdap_test/Makefile.in
	ncdap_test/expected3/Makefile.in
	ncdap_test/expectremote3/Makefile.in
	ncdap_test/testdata3/Makefile.in
	ncdump/Makefile.in
	ncdump/cdl/Makefile.in
	ncdump/expected/Makefile.in
	ncgen/Makefile.in
	ncgen3/Makefile.in
	nctest/Makefile.in
	oc2/Makefile.in
Please commit your changes or stash them before you switch branches.
Aborting
```

**Comment by WardF** [comment]
This has caused problems and missing files in the past when it comes time to craft a release that includes these files. Rather than risk that whole mess again, I recommend running `git clean -fd` from the root directory, to clean out those files. 

I notice the message you’re seeing says it won’t let you change because of local changes; are you starting on a release branch? I’m at the airport so can’t check, but assume git doesn’t care about untracked files, which suggests you are starting on a release branch. Or I am mistaken, just a thought.

**Comment by edhartnett** [comment]
I'm sure that we can manage to have a working .gitignore and a working release as well. Many projects enjoy that, and we can too. ;-)

After you get 4.6.0 released, I will circle around to this problem and fix .gitignore and also the releases, so everything works properly. With the distcheck target, autotools releases are automatically checked. So I presume it is the CMake release that is the problem. 

Are you running a Jenkins instance at Unidata? My first thought would be simply to have a Jenkins task to do a CMake full test cycle (equivalent of distcheck) every repo change to master. Seems like this would  solve most release issues by allowing them to be detected immediately.

At the moment I am working through commits, trying to find where a change was introduced to netCDF that causes a breakage in some parallel code that works fine with 4.4.1.1 but breaks with 4.5.0. For this kind of thing, git can be helpful, if it works well. Or a real pain. ;-)

But all the extra files in the git status command also makes it much less useful. So I'll get this cleared up right after the 4.6.0 release.

**Comment by WardF** [comment]
The issue is autotools, with generated files not being added automatically. I’ll revisit the issue later on but for the time being ‘git clean -fd’ suffices :). Thanks for the offer!
