### ISSUE TITLE
[injection] NETCDF3_64BIT_DATA in-memory load broke with latest release

### ISSUE THREAD

**Issue by thehesiod** [Unidata/netcdf-c#770]
### Environment Information

Version 4.5.0

* What platform are you using? (please provide specific distribution/version in summary)
  * [x] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [x] 64-bit
* What build system are you using?
  * [ ] autotools (`configure`)
  * [x ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [x] Yes (please attach to this issue, thank you!)
  * [ ] No
  * [ ] Not at this time

### Summary of Issue
in a previous RC of 4.5.0, loading of `NETCDF3_64BIT_DATA` files from memory worked, however in the final build it broke.

See https://github.com/Unidata/netcdf4-python/issues/752 for corresponding python issue

### Steps to reproduce the behavior
```c++
#include <stdio.h>
#include "netcdf.h"
#include "netcdf_mem.h"
#include <unistd.h>
#include <time.h>
#include <sys/time.h> /* Extra high precision time info. */
#include <string.h>
#include <stdlib.h>
#include <iostream>
#include <fstream>

#define FILE_PATH "/tmp/foo.nc"

using namespace std;

void handle_error(int status) {
    if(status != NC_NOERR) {
        printf("ret: %d err: %s", status, nc_strerror(status));
        exit(1);
    }
}

char* read_file(long& size) {
	ifstream file (FILE_PATH, ios::in|ios::binary|ios::ate);
	size = file.tellg();
        file.seekg(0, ios::beg);
	char* buffer = (char*)malloc(size);
	file.read(buffer, size);
	file.close();
	return buffer;
}

int main(void)
{
	int ncid = 0;

	// create file
	int status = nc_create(FILE_PATH, NC_64BIT_DATA, &ncid);
	handle_error(status);
	status = nc_close(ncid);
	handle_error(status);

	// load file
	long size = 0;
	char* buffer = read_file(size);
	status = nc_open_mem("dummy.nc", NC_DISKLESS|NC_INMEMORY, size, buffer, &ncid);
	handle_error(status);
}
```

**Comment by wkliao** [comment]
In function read_file(), after calling `size = file.tellg();`, you need to rewind the file pointer, e.g. `file.seekg(0, ios::beg);` before reading the whole file to buffer. Without rewinding, your read takes no effect, as it reads from EOF.

**Comment by thehesiod** [comment]
ya, hmm, and fixing that seems to resolve the issue, let me get back to my python testcase to repro

**Comment by thehesiod** [comment]
ok interestingly the files created between the two differ

**Comment by thehesiod** [comment]
seems like the netcdf file created from netcdf-python creates a header with CDF\x05 which I'm guessing is wrong, I'll close this until it's investigated from the python side

**Comment by thehesiod** [comment]
updated example to reproduce issue, happens with `NC_64BIT_DATA`

**Comment by WardF** [comment]
Going through to prepare for the 4.7.1 release, I believe we have this fixed.
