### ISSUE TITLE
Missing NC_HAVE_META_H in v4.6.0

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#805]
In version 4.6.0, it is not possible to determine if the netcdf_meta.h file exists as is documented in RELEASE_NOTES.md:

```
* Added a new file, `netcdf_meta.h`.  This file is generated automatically at configure time and contains information related to the capabilities of the netcdf library.  This file may be used by projects dependent upon `netcdf` to make decisions during configuration, based on how the `netcdf` library was built.  The macro `NC_HAVE_META_H` is defined in `netcdf.h`.  Paired with judicious use of `ifdef`'s, this macro will indicate to developers whether or not the meta-header file is present. See [NCF-313](https://bugtracking.unidata.ucar.edu/browse/NCF-313).
```
This method has worked since version 4.3.3 and is used by my library to determine configuration information about the netcdf library.

I'm not sure how the library is supposed to determine this configuration information in the current (v4.6.0) release.

**Comment by WardF** [comment]
I will go fix this now; since we didn't do the regular release-candidate cycle, I anticipated doing a quick 4.6.1 release.

**Comment by WardF** [comment]
Fixed, will merge into `master` when travis finishes testing branch `gh805`, will have in 4.6.1 asap.

**Comment by gsjaardema** [comment]
Thanks for the quick response.
