### ISSUE TITLE
failed to build 4.6.0

### ISSUE THREAD

**Issue by wkliao** [Unidata/netcdf-c#811]
At first, I am curious why there is no 4.6.0.rc1 etc. like 4.5.0 and priors.
Also I notice a few PRs marked as 4.6.0 milestone but are not in 4.6.0.

* What platform are you using? (please provide specific distribution/version in summary)
  *  Linux - Redhat
  *  64-bit, little Endian
  *  autotools (`configure`)
  *  cmake

My configure command: (similar for cmake)
`./configure --enable-cdf5 --enable-netcdf-4 --enable-parallel-tests --disable-shared CC=mpicc CFLAGS=-g CPPFLAGS=-I$HOME/HDF5/include LDFLAGS=-L$HOME/HDF5/lib`

HDF5 version 1.8.17
MPICH version 3.2
mpicc is built with clang 3.4.2 (also tried with gcc 4.4.7)

Warning message at configure run:
```
./configure: line 19038: enable_filter_testing: command not found
```

Error message at make:
```
Making all in hdf5plugins
H5Zmisc.c:175:13: fatal error: invalid suffix 'd' on floating constant
            dval = DBLVAL;
                   ^
H5Zmisc.c:19:33: note: expanded from macro 'DBLVAL'
#define DBLVAL 12345678.12345678d
                                ^
1 error generated.
make[3]: *** [H5Zmisc.lo] Error 1
```

**Comment by DennisHeimbigner** [comment]
This error: H5Zmisc.c:175:13: fatal error: invalid suffix 'd' on floating constant
is because some compilers treat all floating constants as double (apple, visual-studio)
and some allow a d|f suffix (gcc, at least some versions).
Is it the case that clang does not allow the 'd' suffix?

**Comment by wkliao** [comment]
Using the test program below, I got the same error when trying gcc 4.4.7, 4.8.4, and 6.2.0, clang 3.4.2 and 3.8.0.
```
#define DBLVAL 12345678.12345678d
int main(int argc, char *argv[]) {
    double dval = DBVAL;
    return 0;
}
```

**Comment by gsjaardema** [comment]
If I change `DBVAL` to `DBLVAL`, then it works with all my gcc versions, but fails for clang.

**Comment by wkliao** [comment]
Sorry for introducing a bug when reporting a bug.
Of all C compilers available to me, the error appears when using following compilers:
gcc 4.4.7
clang 3.4.2 and 3.8.0
pgcc 16.4 and 16.9
IBM xlc/bgxlc for BlueGene V12.1
Fujitsu fccpx 1.2.0

**Comment by hubert-reinterpretcast** [comment]
The `d` and `D` cases were part of the language proposed by ISO/IEC TR 24732:2009. They appear to have been dropped from the superseding document, ISO/IEC TS 18661-2, along with the `FLOAT_CONST_DECIMAL64` pragma. It seems using the suffixes should be reserved for when they prove necessary and helpful, and they are not usually necessary.

**Comment by WardF** [comment]
I want to get this fix in the impending 4.6.1 maintenance release.  If this is behavior we can determine at configure time, we should be able to gate it with #ifdefs.  I'll take a look at adding a test program to autoconf and cmake based builds.

**Comment by gsjaardema** [comment]
They should never be necessary.  All floating point constants in C are by default always doubles unless suffixed with a 'f' in which case they are float.  This is in all C standards...

**Comment by WardF** [comment]
Is there any objection from anybody on this issue to just removing the suffixes from the code altogether?

**Comment by DennisHeimbigner** [comment]
PR https://github.com/Unidata/netcdf-c/pull/813
does this.

**Comment by WardF** [comment]
Oh, easy enough then! Will merge #813 asap.
