### ISSUE TITLE
NCRCglobalstate used anywhere?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#839]
In ddispatch.c I find:

`NCRCglobalstate ncrc_globalstate;
`

There is a bunch of code that sets this seemingly based on an .rc file?

However, as far as I can see, there are no settings that the globalstate is never used anywhere. Is that correct?

If it is not being used, let's remove it.

**Comment by DennisHeimbigner** [comment]
It is used in libdispatch/drc.c
