### ISSUE TITLE
No need for ENABLE_CDF5 and USE_CDF5

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#841]
From the configure.ac:

```
if test "x${enable_cdf5}" = xyes; then
   AC_DEFINE([USE_CDF5], [1], [if true, enable CDF5 Support])
   AC_DEFINE([ENABLE_CDF5], [1], [if true, enable CDF5 Support])
fi

AM_CONDITIONAL(USE_CDF5, [test x$enable_cdf5 = xyes ])
AM_CONDITIONAL(ENABLE_CDF5, [test x$enable_cdf5 = xyes ])

```

No need for both. USE_CDF5 should be used to match USE_HDF4, USE_PNETCDF, USE_PARALLEL, etc.

**Comment by DennisHeimbigner** [comment]
This is to some degree a style issue. I prefer ENABLE_XXX
while Ed and Russ preferred USE_XXX.
In any case both are used in the code, so we need to pick one
and fix the uses of the other.

**Comment by DennisHeimbigner** [comment]
This is to some degree a style issue. I prefer ENABLE_XXX
while Ed and Russ preferred USE_XXX.
In any case both are used in the code, so we need to pick one
and fix the uses of the other.

**Comment by DennisHeimbigner** [comment]
BTW, there are other aliases in configure.ac. I think, for example,
there are 2 aliases for USE_NETCDF4

**Comment by edhartnett** [comment]
I actually don't care whether "ENABLE" or "USE" is used, but I would like there to be just one defined macro that is used everywhere.

For example, I just noticed an ENABLE_CDF5 in a Makefile.am and went around for a bit thinking that was a mistake, and it should be USE_CDF5, as in other Makefile.am files. So having two introduces confusion and an unneeded definition in the Makefiles.

The build is complex enough, we don't need to introduce unnecessary definitions.

It will be about the same amount of effort (5 minutes) to change them all to "ENABLE" or change "ENABLE_CDF5" to "USE_CDF5", so I really don't mind. Changing them all to ENABLE will touch more files.

I would also be in favor of reducing the other aliases. Really no need for them - just use the correct macro everywhere in the build system. But USE_CDF5/ENABLE_CDF5 is new and I think we should just make up our minds on one or the other.

**Comment by WardF** [comment]
I prefer `enable` as well, but this feels pretty low priority.  It's purely a style/preference thing, not really an issue as nothing is broken.  I'll leave this issue open but it can stay how it is for the time being.

**Comment by WardF** [comment]
Ok, I'm going to back off the brusqueness of my previous response without pretending it didn't happen, BUT this does feel like a lower priority for me.  But if somebody wants to make the merge to clean up the code, that is perfectly fine and it will receive the same attention as any other contribution.  My apologies for my shortness above, wrestling with tech issues this morning and it has left me short on patience :)

**Comment by WardF** [comment]
I would suggest we continue to use `enable` because that has been the developer/user facing syntax; as I recall, the `USE_` syntax is used internally.

I thought there was more of a reason for the ENABLE/USE convention, since it was what was in place when I came on board; funny how it turns out maybe not so much :)

**Comment by edhartnett** [comment]
Usually when I file a ticket you can assume I intend to do the work as well. I add the ticket because it is part of your requested process, and so that there will be a good record of what is going on.

There is no reason for the ENABLE/USE split. I think it was just a mistake (by me, years ago). I can change to ENABLE_ everywhere and get rid of the USE_. I agree that is more intuitive, since you get things with options like --enable-SOMETHING.

Also, as with PIO, there is a distinction between ENABLE_PIO (PIO code is built), and use_pio, an int that is used inside NC_open() which keeps track of whether PIO is in use on a particular open file. So using ENABLE instead of USE for the build options make sense.

I will leave this one for a bit until all the outstanding PRs get merged, because it will touch a lot of Makefiles.

**Comment by edhartnett** [comment]
OK, hard to see this getting done since I already have a large backlog of more important changes waiting to get in. I will close this ticket.
