### ISSUE TITLE
Memory corruption in NC3 variables on Windows/x64

### ISSUE THREAD

**Issue by mathstuf** [Unidata/netcdf-c#845]
### Environment Information

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [x] Windows
* 32 and/or 64 bit?
  * [x] 64-bit
* What build system are you using?
  * [x] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [x] Not at this time

### Summary of Issue

Invalid `free` for NC3 variables. This is a very odd error "fixed" in VTK [back in 2011](https://gitlab.kitware.com/vtk/vtk/commit/f93057722e6fb6f7a8ad159b293dc5d859642bc1). @mathturtle and I just spent a few days encountering it again and using it still works, but this is something that should be properly fixed here :) . The commit message seems to indicate that memory sizes are mismatched. While writing this, it occurred to me to check this and found this line:

```diff
        (void) memcpy(varp->dsizes, rvarp->dsizes,
-                        rvarp->ndims * sizeof(size_t));
+                        rvarp->ndims * sizeof(off_t));
```

in `dup_NC_var` which I think should fix it properly. The `dsizes` is allocated as a `off_t` array, but here it is copied as a `size_t` array. We'll try this fix in VTK tomorrow. In case this isn't the real fix, I'm opening this as documentation.

### Steps to reproduce the behavior

VTK's `vtkIOExodusCxx-TestMultiBlockExodusWrite` causes this. We can work to try and get a minimal test case in the coming weeks though.

**Comment by WardF** [comment]
Excellent, thanks for the report! I'll get this merged in shortly for the upcoming release :).

**Comment by mathstuf** [comment]
I'm trying the fix in [this VTK MR](https://gitlab.kitware.com/vtk/vtk/merge_requests/3896).

**Comment by mathstuf** [comment]
This does indeed look to fix the issue.

**Comment by mathstuf** [comment]
I wonder if this issue isn't the reason for the `MALLOCHACK` thing hanging around these variables…
