### ISSUE TITLE
Allow lazy-read of netCDF-4/HDF5 files

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#857]
At this point, this represents more an aspiration that a plan, but there has been some discussion (see PR #849) of how to enable lazy reads of netCDF-4 file metadata.

Files with a very large amount of metadata take a long time to load because netCDF reads all metadata at file open. For classic files, this doesn't seem to bother people much. But for netCDF-4/HDF5 files, it does. Perhaps this can be explained by the use of netCDF-4/HDF5 for some really complex and large datasets, which end up with tens of thousands of attributes, variables, dimensions, and/or groups. Or perhaps the classic formats, having all their metadata in a block at the beginning of the file, just load faster.

This has already cost us satellite users - the NPP uses netCDF-4, but the follow-on JPSS spacecraft switched to HDF5 without netCDF, due to the slow load times. I was told a similar story about a ESA satellite system by a very active netCDF user in the Netherlands. (Satellite L2 data files generally contain a very large number of attributes, some of which may be reasonably large arrays.)

One idea I suggested is to read each group only as needed. This would be pretty easy to implement I think. It would help where there's lot of groups. @DennisHeimbigner points out that this will not help with files that contain lots of vars. He indicates a known use case with a very large number of vars, all in the root group.

Well, that's another good idea all shot to hell. ;-)

In order to do lazy reads as Dennis suggests I think much of the libsrc4 code would have to be rewritten. (The good news is that with #849 soon to merge, and #856 to follow, the libsrc4 code will be a fair bit smaller than it is now.)

For example, if we open a file and read nothing, and then the user does an nc_inq(), we need to find out how many variables there are. In the current code, we count our list, because we have already read them. In the lazy-read code, we would rsee if there's a way we can get the numbers we need without reading every variable's metadata. That is probably possible in HDF5, but not how the code is currently written.

Handling dimensions in a lazy-read is going to be particularly tricky. They may be in different groups from a variable. So if the user opens a file and does a nc_inq_var() on a var deep in the group structure, we will have to have code smart enough to find all the dimensions in whatever group they are in. All this information is in the HDF5 file, but the code to read it and use it properly remains to be written.

**Comment by DennisHeimbigner** [comment]
I should note that the metadata read speedup that I already have
still reads all the metadata at one time (i.e., not lazily). It gets
its speedup from pervasive use of hashing. I just put up a PR
for the initial integration of this speed up. Waiting for the netcdf-4
rename stuff to be completed before I do the final step.

**Comment by DennisHeimbigner** [comment]
Another issue I discovered was that if we do lazy eval, then the various integer
ids (dimid, varid, etc)  will probably change depending on the order in which
the meta-data elements are read. Specifically, any user code that assumes anything
about the ids is potentially going to fail. Issue https://github.com/Unidata/netcdf-c/issues/851 is relevant here.

**Comment by edhartnett** [comment]
Maybe an easy way to do this would be a special attribute that contains a table of metadata. So instead of reading each object in a lazy way, we read the table. Then all our data structure code continues to work.

Files that do not have the table of metadata can not be read quickly. But they could add the table and then quick reads would work on the file.

We could store the metadata in various ways, like a file level attribute that lists all the dims in the file, a group-level table that lists all vars in a group, etc. Or we can package it up as one big metadata element (perhaps just store the output of ncdump -h as a char attribute).

**Comment by DennisHeimbigner** [comment]
Not a bad idea. The problem is that if we have large amounts of metadata, then
that extra attribute itself becomes very large. We would need some very
good encoding method.

**Comment by edhartnett** [comment]
Even a very large ncgen -h output, stored as a char array, would read hugely faster than opening all the objects in HDF5 and querying them each. The whole thing would be 1 disk access, instead of tens or hundreds of thousands. Essentially it would be O(1) instead of O(N), right?

The more I think about it, the more I like it. Instead of re-writing all the libsrc4 code, it all will still work just fine.

**Comment by edhartnett** [comment]
Would it be at all possible/practical to put the existing ncgen/ncdump parsing code into the library, so that we could literally use the output of ncdump -h?

Or is that just nutty?

**Comment by DennisHeimbigner** [comment]
That is just nutty :-)
It also occurs to me that we need to allow for non-lazy (bulk) read of the
metadata when the caller is e.g. something like ncdump.

**Comment by edhartnett** [comment]
Let us say we have an optional text attribute in the root group with a protected name which contains some compressed, easy to parse representation of the metadata in the file.

Each time any metadata is added or altered, the attribute is updated so it is always correct.

We add a function nc_put_metadata() which does the bulk read of metadata and (re-)creates this attribute.

Then why wouldn't ncdump be able to use the metadata too? Seems like that would be useful and a lot faster.

**Comment by DennisHeimbigner** [comment]
But this does not solve anything; innstead of reading all the metadata at once
as we do now, we are reading the equivalent in that single attribute. Plus
we have the overhead of parsing it, which is potentially a big cost. This
reminds me of the HDF-EOS solution.

**Comment by edhartnett** [comment]
It does remind me of the HDF-EOS thing too, and that is certainly not a compliment to the idea. So perhaps not the way to go.

**Comment by DennisHeimbigner** [comment]
Before this goes much further, we need to have
a software architecture and design document to
codfy the API and the critical implementation
details. Something in markdown like a cross between
this https://github.com/Unidata/netcdf-c/blob/master/docs/filters.md
and this https://support.hdfgroup.org/HDF5/doc/Advanced/DynamicallyLoadedFilters/HDF5DynamicallyLoadedFilters.pdf

**Comment by edhartnett** [comment]
Having worked with this code a bunch, I do see an optimization which would be pretty easy, and could result in significant speed-up of file opens.

In NC_VAR_INFO_T we we add a field atts_read.

When opening the file we don't read any variable atts.

When the user asks for a variable att, we check atts_read. If zero, we read all atts for that variable and set it to 1.

Anyone have any thoughts or opinions on this approach?

**Comment by Dave-Allured** [comment]
Developers, have you considered no attribute cacheing as an alternative strategy to cacheing and lazy reads, in the case of netCDF4?  HDF5 offers efficient attribute access by name and by index number.  It seems to me that a thin wrapper approach for attributes would result in less memory demand and simpler library code, with little impact on performance in most real cases.

This approach may also be valid for other alternative storage formats such as cloud.

**Comment by edhartnett** [comment]
An update on this ticket:

* Lazy att reads were part of the last release. Atts for a group or var are all read when any information is requested about any atts in that group/var. That is, if there are 10 atts in a var, all 10 will be read into memory if you ask about any of them.

* Lazy var reads are more of a problem. I have worked out a faster way to read vars, but am now trying to make it less impactfull on the code and the data format. (That is, I am looking for a lazier and easier way to obtain the same speedup.)

Here's some gprof output for the following code:

 ```
     int ncid;
      int i;
      for (i = 0; i < 1000; i++)
      {
         if (nc_open("wrfbdy_d01", NC_WRITE, &ncid)) ERR;
         if (nc_close(ncid)) ERR;
      }

```

The file used is from a WRF model run, it's got lots of vars and attributes, but it is a real data file which is read a gadjillion times a day, all over the world, by anyone using the WRF model.

(I have cut off the call graph where times dropped below .1 s.)

This is with current master, + PR #1234 + some additional minor cleanups and optimizations that will be in a future PR.

```
index % time    self  children    called     name
                                                 <spontaneous>
[1]     62.5    0.00    0.20                 main [1]
                0.00    0.13    1000/1000        nc_close [4]
                0.00    0.07    1000/1000        nc_open [13]
-----------------------------------------------
                0.00    0.13    1000/1000        nc_close [4]
[2]     40.6    0.00    0.13    1000         NC4_close [2]
                0.00    0.13    1000/1000        nc4_close_hdf5_file [3]
                0.00    0.00    1000/1000        nc4_find_nc_grp_h5 [81]
-----------------------------------------------
                0.00    0.13    1000/1000        NC4_close [2]
[3]     40.6    0.00    0.13    1000         nc4_close_hdf5_file [3]
                0.00    0.08    1000/1000        nc4_close_netcdf4_file [7]
                0.04    0.00    1000/1000        nc4_rec_grp_HDF5_del [16]
                0.00    0.01    1000/1000        sync_netcdf4_file [32]
-----------------------------------------------
                0.00    0.13    1000/1000        main [1]
[4]     40.6    0.00    0.13    1000         nc_close [4]
                0.00    0.13    1000/1000        NC4_close [2]
                0.00    0.00    1000/2000        NC_check_id [56]
                0.00    0.00    1000/1000        del_from_NCList [75]
                0.00    0.00    1000/1000        free_NC [78]
-----------------------------------------------
                                                 <spontaneous>
[5]     35.9    0.03    0.09                 read_hdf5_obj [5]
                0.01    0.08  140000/140000      read_dataset [6]
-----------------------------------------------
                0.01    0.08  140000/140000      read_hdf5_obj [5]
[6]     28.1    0.01    0.08  140000         read_dataset [6]
                0.06    0.02  131000/131000      read_var [10]
                0.00    0.00    9000/9000        read_scale [36]
-----------------------------------------------
                0.00    0.08    1000/1000        nc4_close_hdf5_file [3]
[7]     25.0    0.00    0.08    1000         nc4_close_netcdf4_file [7]
                0.00    0.08    1000/1000        nc4_rec_grp_del [8]
                0.00    0.00    3000/143002      nclistfree [44]
                0.00    0.00    1000/1000        NC4_free_provenance [63]
-----------------------------------------------
                0.00    0.08    1000/1000        nc4_close_netcdf4_file [7]
[8]     25.0    0.00    0.08    1000         nc4_rec_grp_del [8]
                0.04    0.04  131000/131000      var_free [9]
                0.00    0.00    5000/136000      ncindexfree [18]
                0.00    0.00  140000/2931000     ncindexith [40]
                0.00    0.00    9000/9000        dim_free [53]
-----------------------------------------------
                0.04    0.04  131000/131000      nc4_rec_grp_del [8]
[9]     24.7    0.04    0.04  131000         var_free [9]
                0.00    0.03  131000/136000      ncindexfree [18]
                0.01    0.00  131000/131000      nc4_type_free [28]
-----------------------------------------------
                0.06    0.02  131000/131000      read_dataset [6]
[10]    24.6    0.06    0.02  131000         read_var [10]
                0.00    0.02  131000/131000      nc4_var_list_add [19]
                0.00    0.00  131000/131000      get_type_info2 [47]
                0.00    0.00  131000/131000      nc4_adjust_var_cache [48]
-----------------------------------------------
                0.01    0.06    1000/1000        NC_open [12]
[11]    21.9    0.01    0.06    1000         NC4_open [11]
                0.00    0.06    1000/1000        nc4_open_file [14]
-----------------------------------------------
                0.00    0.07    1000/1000        nc_open [13]
[12]    21.9    0.00    0.07    1000         NC_open [12]
                0.01    0.06    1000/1000        NC4_open [11]
                0.00    0.00    1000/1000        NC_urlmodel [70]
                0.00    0.00    1000/1000        NC_check_file_type [68]
                0.00    0.00    1000/1000        new_NC [85]
                0.00    0.00    1000/1000        add_to_NCList [71]
                0.00    0.00       1/1           nc_initialize [110]
-----------------------------------------------
                0.00    0.07    1000/1000        main [1]
[13]    21.9    0.00    0.07    1000         nc_open [13]
                0.00    0.07    1000/1000        NC_open [12]
-----------------------------------------------
                0.00    0.06    1000/1000        NC4_open [11]
[14]    18.8    0.00    0.06    1000         nc4_open_file [14]
                0.04    0.01    1000/1000        rec_match_dimscales [15]
                0.01    0.00    1000/1000        rec_read_metadata [31]
                0.00    0.00    1000/1000        nc4_nc4f_list_add [38]
                0.00    0.00    1000/1000        check_for_classic_model [73]
                0.00    0.00    1000/1000        NC4_read_ncproperties [66]
-----------------------------------------------
                0.04    0.01    1000/1000        nc4_open_file [14]
[15]    15.6    0.04    0.01    1000         rec_match_dimscales [15]
                0.01    0.00  494000/494000      nc4_find_dim [24]
                0.00    0.00 2116000/2931000     ncindexith [40]
-----------------------------------------------
                0.04    0.00    1000/1000        nc4_close_hdf5_file [3]
[16]    12.5    0.04    0.00    1000         nc4_rec_grp_HDF5_del [16]
                0.00    0.00  140000/2931000     ncindexith [40]
-----------------------------------------------
                0.03    0.00  136000/136000      ncindexfree [18]
[17]     9.4    0.03    0.00  136000         NC_hashmapfree [17]
-----------------------------------------------
                0.00    0.00    5000/136000      nc4_rec_grp_del [8]
                0.00    0.03  131000/136000      var_free [9]
[18]     9.4    0.00    0.03  136000         ncindexfree [18]
                0.03    0.00  136000/136000      NC_hashmapfree [17]
                0.00    0.00  136000/143002      nclistfree [44]
-----------------------------------------------
                0.00    0.02  131000/131000      read_var [10]
[19]     5.8    0.00    0.02  131000         nc4_var_list_add [19]
                0.00    0.02  131000/131000      nc4_var_list_add2 [20]
                0.00    0.00  131000/131000      nc4_var_set_ndims [49]
-----------------------------------------------
                0.00    0.02  131000/131000      nc4_var_list_add [19]
[20]     5.8    0.00    0.02  131000         nc4_var_list_add2 [20]
                0.00    0.02  131000/140000      ncindexadd [23]
                0.00    0.00  131000/141000      NC_hashmapkey [34]
                0.00    0.00  131000/136000      ncindexnew [46]
-----------------------------------------------
[21]     5.1    0.00    0.02  140000+99000   <cycle 1 as a whole> [21]
                0.00    0.02  238000             NC_hashmapadd <cycle 1> [22]
                0.00    0.00    1000             rehash <cycle 1> [89]
-----------------------------------------------
                               98000             rehash <cycle 1> [89]
                0.00    0.02  140000/140000      ncindexadd [23]
[22]     5.1    0.00    0.02  238000         NC_hashmapadd <cycle 1> [22]
                0.01    0.00  238000/238000      locate [27]
                0.00    0.01  238000/379000      NC_crc32 [25]
                                1000             rehash <cycle 1> [89]
-----------------------------------------------
                0.00    0.00    9000/140000      nc4_dim_list_add [35]
                0.00    0.02  131000/140000      nc4_var_list_add2 [20]
[23]     5.1    0.00    0.02  140000         ncindexadd [23]
                0.00    0.02  140000/140000      NC_hashmapadd <cycle 1> [22]
                0.00    0.00  140000/146031      nclistpush [42]
-----------------------------------------------
                0.01    0.00  494000/494000      rec_match_dimscales [15]
[24]     3.1    0.01    0.00  494000         nc4_find_dim [24]
                0.00    0.00  494000/3426027     nclistget [39]
-----------------------------------------------
                0.00    0.00  141000/379000      NC_hashmapkey [34]
                0.00    0.01  238000/379000      NC_hashmapadd <cycle 1> [22]
[25]     3.1    0.00    0.01  379000         NC_crc32 [25]
                0.01    0.00  379000/379000      crc32_z [26]
-----------------------------------------------
                0.01    0.00  379000/379000      NC_crc32 [25]
[26]     3.1    0.01    0.00  379000         crc32_z [26]
-----------------------------------------------
                0.01    0.00  238000/238000      NC_hashmapadd <cycle 1> [22]
[27]     3.1    0.01    0.00  238000         locate [27]
-----------------------------------------------
                0.01    0.00  131000/131000      var_free [9]
[28]     3.1    0.01    0.00  131000         nc4_type_free [28]
-----------------------------------------------
                0.01    0.00  131000/131000      nc4_rec_write_metadata [30]
[29]     3.1    0.01    0.00  131000         write_var [29]
-----------------------------------------------
                0.00    0.01    1000/1000        sync_netcdf4_file [32]
[30]     3.1    0.00    0.01    1000         nc4_rec_write_metadata [30]
                0.01    0.00  131000/131000      write_var [29]
                0.00    0.00  142000/2931000     ncindexith [40]
                0.00    0.00    9000/9000        write_dim [54]
                0.00    0.00    1000/1000        write_attlist [90]
                0.00    0.00    1000/1000        attach_dimscales [72]
-----------------------------------------------
                0.01    0.00    1000/1000        nc4_open_file [14]
[31]     3.1    0.01    0.00    1000         rec_read_metadata [31]
                0.00    0.00  131000/2931000     ncindexith [40]
                0.00    0.00    1000/143004      nclistnew [43]
                0.00    0.00    1000/143002      nclistfree [44]

```

I am analyzing this now to see where the time is really being spent opening and closing a file.

I am surprised to see how slow it is to close the file.

**Comment by edhartnett** [comment]
I am going to close, as the changes discussed here have all be merged.
