### ISSUE TITLE
blosc compressor

### ISSUE THREAD

**Issue by milos-korenciak** [Unidata/netcdf-c#863]
Could there be added [blosc](https://github.com/Blosc/c-blosc2) compressor, please?
It is simply superior compared to some other compressors.

**Comment by WardF** [comment]
With the recent release we introduced user-defined compression routines, which should theoretically support blosc.  I know it is also distributed with some block-storage schemes, which we are actively evaluating for inclusion in netCDF.

**Comment by DennisHeimbigner** [comment]
Apparently this has already been done here:
https://github.com/Blosc/hdf5-blosc
