### ISSUE TITLE
Continue separation of HDF4 dispatch code from HDF5 code

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#870]
In #856 we have the ambitious goal of separating the HDF5 format-specific code from the internal code that represents the enhanced data model. There are many good reasons for this - see #856 for a full discussion. Here I propose a very small incremental step in that direction, isolated to the HDF4 dispatch layer.

Recently the HDF4 code was moved to its own directory and dispatch layer, instead of being treated as a special case of HDF5 file. This improved code clarity by getting that HDF4 stuff out of the way and isolated. However, no attempt was made to remove HDF4 specific fields from the internal data structures. For example, 

```
/* This is a struct to handle the var metadata. */
typedef struct NC_VAR_INFO
{
...
#ifdef USE_HDF4
   /* Stuff below is for hdf4 files. */
   int sdsid;
   int hdf4_data_type;
#endif /* USE_HDF4 */
...
} NC_VAR_INFO_T;

```
There are also some HDF4 specific fields in the file info struct. (But nowhere else.)

What I propose here is a further evolution of the HDF4 code. I will remove HDF4-specific fields from the VAR_INFO and FILE_INFO data structs, and use a void * to point to a HDF4-specific data structs, which will be fully managed within the HDF4 dispatch code. 

This is the same kind of work planned for HDF5 in #856, but on a much smaller scale. This will give us a chance to work out some idioms and conventions. This will also benefit the code by further isolating HDF4-specific items to the HDF4 dispatch code, and away from HDF5 and enhanced model code.

As part of this I will add a section to Dennis' dispatch documentation, explaining the HDF4 dispatch layer as an example of a read-only, classic model dispatch. Unbelievably, only 6 functions are required to implement HDF4. And I think 3 of them can be eliminated, leaving an nc_open/nc_close and a nc_get_vara function.

In support of user-defined formats, this is awesome. That means they can implement 3 functions, and netCDF will be able to read their format. But that is outside the scope of this issue, which is just to improve the HDF4 layer.

**Comment by edhartnett** [comment]
Another way in which I have separated the HDF4 code is by creating an hdf4_test directory, and move all HDF4 tests there. This cleans out the already-crowded nc_test4. I have this working in my fork.

**Comment by DennisHeimbigner** [comment]
BTW, be warned. I am working on a major rewrite of the libsrc4 code.
So their is high probability that any code you write will be obsolete
in whole or part.

**Comment by edhartnett** [comment]
But this set of HDF4 and dispatch layer changes is OK, right?
