### ISSUE TITLE
Remove --enable-valgrind-tests, and valgrind test scripts, but continue to support valgrind tools

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#873]
There is a build option --enable-valgrind-tests. If used (only works with --disable-shared), some extra tests scripts will run. These will rerun a subset of the tests using valgrind, to check for memory leaks.

Currently it is broken, BTW. Some of the tests have been moved or removed. Fixing it would not be hard, but it would still break for parallel builds, unless we also add a bunch of dependency info to the Makefile.am and CMakeLists.txt files.

However, instead of fixing it, I think the valgrind testing should just be removed, including the configure option, the test scripts that run valgrind, and the code in Makefile.am and CMakeLists.txt which deal with it.

I added this to get some automatic memory checking, and it was useful for that. But now we have the address sanitizer built right into gcc. It is more sensitive than valgrind, gives better error messages, and only requires some extra CFLAGS.  - no extra tests scripts to maintain. No dependencies need be tracked, and every new test is automatically added to the memory checking, just by being part of the build. So it is superior in every way.

I am running several address sanitizer runs as part of my CI. So the valgrind tests are not needed.

**Comment by WardF** [comment]
This is fine with me. CMake has valgrind functionality baked in that we can use when needed; the valgrind tests option was always one of those legacy things that wasn’t much used/bothered with when I came on board.

**Comment by edhartnett** [comment]
Awesome. I will take care of this in my next PR, which separates the HDF4 tests.

**Comment by DennisHeimbigner** [comment]
I did not know that. What is the cmake memory checking called?

**Comment by edhartnett** [comment]
OK, I took down the HDF4 test PR because some if it might conflict with Dennis' current hashmap PR.

But these valgrind cleanups won't interfere with anything. I will put these up as a separate PR.
