### ISSUE TITLE
undefined reference to `nc__testurl'

### ISSUE THREAD

**Issue by seeksahil88** [Unidata/netcdf-c#875]
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### Environment Information

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [ ] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [ ] 64-bit
* What build system are you using?
  * [ ] autotools (`configure`)
  * [ ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [ ] Yes (please attach to this issue, thank you!)
  * [ ] No
  * [ ] Not at this time

**Comment by seeksahil88** [comment]
CMakeFiles/ncdump-json.dir/src/ncdump.c.o: In function main': /path/ncdump-json-r13/src/ncdump.c:(.text+0x6e6): undefined reference tonc__testurl'
/path/ncdump-json-r13/src/ncdump.c:(.text+0x892): undefined reference to `nc__testurl'

**Comment by WardF** [comment]
What version of NetCDF are you using?

**Comment by DennisHeimbigner** [comment]
Also, do you have dap support disabled?

**Comment by seeksahil88** [comment]
i am using netcdf 4.3.3.1

**Comment by WardF** [comment]
Is DAP support enabled?

**Comment by seeksahil88** [comment]
please tell me how to check that

**Comment by DennisHeimbigner** [comment]
there are two ways:
1. when you did the ./configure command was --disable-dap one of its arguments?
2. Figure out where netcdf is installed (probably /usr (if /usr/bin/ncdump exists)
   or /usr/local (if /usr/local/bin/ncdump exists). Support it is in /usr, then
   look at the file /usr/lib/libnetcdf.settings and see if it says: 
DAP2 Support:		yes
DAP4 Support:		yes

**Comment by DennisHeimbigner** [comment]
Looking at the code for the current master, there should be no problem.
It is distinctly possible that 4.3.3.1 had improper #ifdef's around nc__testurl.
Since we have had no further response on this. I am going to close it.
