### ISSUE TITLE
--enable-parallel-tests should not silently turn itself off when parallel is not present

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#882]
@WardF just noticed that somewhere we broke parallel builds. That surprised me, since I have several parallel builds in my CI. Sure enough, parallel was being turned off without causing a failure.

I have a suggestion to prevent re-occurrence.

Right now we have this in configure.ac. Note that parallel tests are ignored if parallel build did not happen:
```
# Does the user want to run extra parallel tests when parallel netCDF-4 is built?
AC_MSG_CHECKING([whether parallel IO tests should be run])
AC_ARG_ENABLE([parallel-tests],
              [AS_HELP_STRING([--enable-parallel-tests],
                              [Run extra parallel IO tests. Ignored if \
                               netCDF-4 is not enabled, or built on a system \
                               without parallel I/O support.])])
test "x$enable_parallel_tests" = xyes || enable_parallel_tests=no
AC_MSG_RESULT($enable_parallel_tests)
```

I suggest that, after @WardF has fixed the current issue, I change this so that --enable-parallel-tests will cause the build to fail if the parallel build does not work. This way, we can catch future parallel build problems in our CI systems by using --enable-parallel-tests.

I think it's also fair to say that if the user specifies parallel tests, and we can't successfully build and run them, then the build should fail.

**Comment by WardF** [comment]
This makes sense, when a user specifies something and it can't be accommodated, it should not silently deviate from expectations.  I can roll this into the extant pull request I'm working on, once this meeting I'm in is over.

**Comment by edhartnett** [comment]
OK, great. Hopefully I haven't broken any parallel code while my CI system has been showing me that parallel builds are working. ;-) If so, I will fix immediately.
