### ISSUE TITLE
Test nc_test4/tst_bug324 is run by Makefile.am but not CMakeLists.txt

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#885]
There is a test that is not being run by the cmake build. When I add it everything works fine. I will put this in my PR I'm about to put up on valgrind removal.

**Comment by edhartnett** [comment]
Never mind, it is run, but only with HDF4. I will close this issue.

**Comment by edhartnett** [comment]
OK, sorry for the confusion, but now I've figured out what the heck I am trying to do here. 

The issue is that tst_bug324.c is run as a HDF4 test, but, in fact, has nothing to do with HDF4. It should just be run as a regular test. I noticed this when I separated out the HDF4 tests into their own directory.

That PR is still to come, but meanwhile, in my current PR I have moved tst_bug324 from being a HDF4 test to just a regular C test.

**Comment by DennisHeimbigner** [comment]
Ed-
I suspect this test refers to this issue:
     https://github.com/Unidata/netcdf-c/issues/324
which appears, as you note, to be independent of hdf4.
But be aware that we had a couple of failures where is failed if hdf4 was enabled,
even if the test was not specifically an hdf4 test.

**Comment by edhartnett** [comment]
OK, good to know. It has been unassociated with HDF4 in the autotools build for some time, not sure when. Seems to be working OK.

In HPC NetCDF the HDF4 tests have all been moved to another dir, and tst_bug324.c left in nc_test4. Is it OK if I continue with this, and disassociate tst_bug324 from HDF4?

**Comment by DennisHeimbigner** [comment]
Ok with me.
