### ISSUE TITLE
Files called Make0 committed by mistake?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#890]
There are some files called Make0 which I believe were committed to the repo by mistake.

I don't believe they are serving any purpose in the current build. @DennisHeimbigner am I correct? If so, I will simply remove them.

```
./libdispatch/Make0
./ncdump/Make0
./oc2/Make0
./libdap2/Make0
./nc_test/Make0
./libdap4/Make0
./Make0
./nc_test4/filter_test/Make0
./nc_test4/Make0
./ncgen/Make0
./dap4_test/Make0
```

**Comment by DennisHeimbigner** [comment]
There are a number of files in the repo but not in the distribution
that I leave there to help me debug things. So I would prefer they are left.
These include Make0, cf, and cf.cmake

**Comment by edhartnett** [comment]
OK, thanks for letting me know.
