### ISSUE TITLE
Data out-of-date -- docs/all-error-codes.md

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#891]
Not sure if it matters, but discovered while grepping the code tree for an error code translation that the values in all-error-codes.md are incomplete and in some cases incorrect.  For example `NC_EBADGRPID` is -116 in netcdf.h, but listed as -113 in `all-error-codes.md`

**Comment by DennisHeimbigner** [comment]
I wonder if we could build a tool using e.g. awk to automatically
create all-error-codes.md from netcdf.h?

**Comment by edhartnett** [comment]
I believe this file is not needed. Doxygen already provides good documentation for the error codes, from the .h file. So no need to list them twice.

**Comment by edhartnett** [comment]
The error codes are actually poorly documented in netcdf.h.

I suggest that we fix up the error documentation there.

I don' t think that programmers will naturally look to a separate documentation file for information, so I think all-error-codes.md is perhaps not needed.

**Comment by DennisHeimbigner** [comment]
A perhaps simple solution is to provide the documentation in the
doxygen documentation for the nc_strerror function and
modify all-error-codes.md to just tell people to look at the documentation for
nc_strerror. That way, at least everything is in a single file.

**Comment by edwardhartnett** [comment]
I believe we should remove all-error-codes.md, and in nc_strerror() we should simply refer to netcdf.h.

In netcdf.h we should (as we already have) document each error code with a doxygen comment. 

If we do all this, doxygen will display the error codes just fine: 

![image](https://user-images.githubusercontent.com/38856240/166722149-721a994b-62ab-4f23-8901-3eff2ba47cf4.png)

I will submit a PR with this change.
