### ISSUE TITLE
Remove some unused legacy files, remove legacy m4 macros from acinclude.m4

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#897]
I noticed the following legacy files which are not used and can be removed:
test_prog.f90
test_prog.F
nctest/README (has instructions for building on VMS!)

While working on #873 I also noticed that there are loads of legacy macros in acinclude.m4 which can safely be removed. These were the macros from the pre-Automake netCDF build which existed pre-3.6.0 (2003?) Starting with 3.6.0, automake and libtool were used, and these macros gradually began to disappear from use.

Some of them are to check for things that autoconf/automake can now check for, and others have to do with the old, combined C/Fortran build.

**Comment by WardF** [comment]
Thanks for pointing that out; I'll update this and roll it in with the final 4.6.1 updates, and then we can move on to the next release.

**Comment by edhartnett** [comment]
I haven't put up the changes yet. No hurry really, but if you want them for 4.6.1 I can prepare a PR...
