### ISSUE TITLE
Make netcdf-4 use the the stride > 1 facilities of hdf5

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#908]
Currently, netcdf-4 uses a very slow implementation of vars when stride > 1.
Convert to use the stride capabilities of the underlying hdf5.

**Comment by czender** [comment]
FYI NCO long ago implemented a workaround that addresses this issue for the special case when the strided dimension is the first dimension and only one dimension is strided. The code flag is USE_NC4_SRD_WORKAROUND in nco_msa.c. Once the library fix for #908 is done then we can deprecate our workaround. Pinging @hmb1 so he is aware of this pending development.

**Comment by DennisHeimbigner** [comment]
Thanks for the reminder. I am starting work on this just now.

**Comment by DennisHeimbigner** [comment]
Ok, I think I have this working. It looks like it is going to make
a very big performance improvement. For a simple test
on a 16000000 integer variable with stride 2X2, the difference
I see is a factor of about 150.
Your mileage may vary.
Anyway, as soon as it passes all the relevant tests, I will turn it into
a pull request.

**Comment by DennisHeimbigner** [comment]
This is now solved by pull request https://github.com/Unidata/netcdf-c/pull/1001
