### ISSUE TITLE
Defined order for group IDs returned by nc_inq_grps()?

### ISSUE THREAD

**Issue by czender** [Unidata/netcdf-c#909]
In what order, if any, does nc_inq_grps() return group IDs? e.g., is it random, in order of creation date, alphabetical, "left-to-right", or "right-to-left"? If there is an order, is that order _guaranteed_? If there is no pre-defined ordering might it be useful to implement one?

I ask because this CF2-Group Draft specification [here](https://docs.google.com/document/d/1KK6IZ2ZmpaUTVgrw-GlFd6almppjvGz6D7nxVTO3BtI/edit) utilizes "width-wide" searches, and specifies that the first (i.e., "left-most") group returned that matches a specified criteria should be used. But I have no idea how netCDF/HDF5 decide to order the returned group IDs, and thus whether the ordering is reliably maintained between successive nc_inq_grps() calls.

**Comment by DennisHeimbigner** [comment]
Looking at the code, it appears to be creation order. But note that this is not
recursive, so it will only return the groups immediately contained in a specific group.
If you want, say, breadth-first, then you need to implement that yourself.

**Comment by czender** [comment]
Thank you, that answers my question.
