### ISSUE TITLE
DAP 2 fails on certain URLS

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#924]
re e-support: OCR-368719
This URL fails on NC_EINVAL.
https://mynasadata.larc.nasa.gov/thredds/dodsC/sealevelheight
At first I thought it was because the .das contains a _FillValue attribute,
but the submitter claims that other urls succeed that contain _FillValue.

The reason is that setting fill value for a netcdf-3 file (and read-only at that)
is disallowed. Need to decide how to handle this.

**Comment by AnsleyManke** [comment]
Looking at the attributes of that variable, it looks to me that is shouldn't be marked as integer type. It's got attributes data_min: -0.63600004,   data_max: 0.51100004  so there's something wrong.  I'll contact the data provider.

**Comment by AnsleyManke** [comment]
We've corrected the attributes using ncml on the thredds server where it lives, so they're the correct "packed" integer values for the dataset, so the error condition no longer occurs.

ncdump -h https://mynasadata.larc.nasa.gov/thredds/dodsC/sealevelheight
...

**Comment by WardF** [comment]
Great! Thanks very much :)

**Comment by DennisHeimbigner** [comment]
There is still a bug in the dap code; the original url should not have failed
as it did. I will fix as a separate pull request at some point.
