### ISSUE TITLE
Should netCDF library make use of C99?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#925]
Currently we are writing for the C90 standard.

However, C99 has been out quite a while. It is supported by all commercial and free software compilers that I am aware of, and is in common use. For example, PIO uses C99 and has never encountered a build problem because of a system that does not support C99.

The key feature in C99 which would greatly benefit netCDF code is the variable length array (see https://en.wikipedia.org/wiki/Variable-length_array).

This allows code like this (from nc4_rec_match_dimscales):

```
            if (var->ndims)
            {
               if (!(h5dimlen = malloc(var->ndims * sizeof(hsize_t))))
                  return NC_ENOMEM;
               if (!(h5dimlenmax = malloc(var->ndims * sizeof(hsize_t))))
               {
                  free(h5dimlen);
                  return NC_ENOMEM;
               }
               if ((dataset_ndims = H5Sget_simple_extent_dims(spaceid, h5dimlen,
                                                              h5dimlenmax)) < 0) {
                  free(h5dimlenmax);
                  free(h5dimlen);
                  return NC_EHDFERR;
               }
               if (dataset_ndims != var->ndims) {
                  free(h5dimlenmax);
                  free(h5dimlen);
                  return NC_EHDFERR;
               }
            }
```

To become:

 ```
           if (var->ndims)
            {
               hsize_t h5dimlen[var->ndims];
               hsize_t h5dimlenmax[var->ndims]
               if ((dataset_ndims = H5Sget_simple_extent_dims(spaceid, h5dimlen,
                                                              h5dimlenmax)) < 0) 
                  return NC_EHDFERR;
               if (dataset_ndims != var->ndims) 
                  return NC_EHDFERR;
            }

```  

This is a significant improvement in code size and readability. Unlike the first block of code, in the C99 block we do not have to concern ourselves with freeing all memory on all exit paths. Instead, the compiler guarantees that it will free the memory when it goes out of scope.

Unfortunately this is not something that it makes sense to use a configure option to turn on and off. We either go for it, or not.

Note also that PIO does require C99, so the HPC features that I am putting in require C99. Without C99 users cannot build with --enable-pio. What I am suggesting in this ticket is that C99 be required for the entire library.

**Comment by WardF** [comment]
I would need to see if Visual Studio has adopted c99 yet; they hadn’t when I came on board. Recent versions adopted a subset of c99 I believe. I will look into it.

**Comment by edhartnett** [comment]
Well I forgot all about visual studio. (Not an accident - I try to block out all memory of it.)

Of course it does not support variable length arrays - the only modern compiler that doesn't. Oh well, another perfectly good idea all shot to hell. ;-)

I will close the ticket...
