### ISSUE TITLE
Use <> and not "" for system includes

### ISSUE THREAD

**Issue by schwehr** [Unidata/netcdf-c#928]
System includes should use `<>`, not `""`.

https://github.com/Unidata/netcdf-c/blob/master/libdispatch/dv2i.c#L15

```diff
--- a/libdispatch/dv2i.c	2018-04-18 09:25:37.000000000 -0700
+++ b/libdispatch/dv2i.c	2018-04-18 09:26:01.000000000 -0700
@@ -12,7 +12,7 @@
 #include <stdio.h>
 #include <stdarg.h>
 #include "netcdf.h"
-#include "math.h"
+#include <math.h>

--- a/src4/error4.c	2018-03-15 14:22:57.000000000 -0700
+++ b/src4/error4.c	2018-04-18 09:28:53.000000000 -0700
@@ -17,7 +17,7 @@
 #include <stdarg.h>
 #include <stdlib.h>
 #include <stdio.h>
-#include "assert.h"
+#include <assert.h>
 #include <hdf5.h>
 
 /* This contents of this file get skipped if LOGGING is not defined
```

### Environment Information

* What platform are you using? (please provide specific distribution/version in summary)
  * [x] Linux - custom distro
* 32 and/or 64 bit?
  * [x] 64-bit
* What build system are you using?
  * [x] configure -> bazel
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [x] No

### Summary of Issue

The bazel build cleaner complains about not being able to find a dependency that provides `"assert.h"` or `"math.h"`

There may be other includes with the same issue.  I'm only building the core libraries.

**Comment by WardF** [comment]
Thanks; I'll take a look, I hadn't heard of `bazel`.  Thanks!

**Comment by schwehr** [comment]
I will create a pull request later today

**Comment by WardF** [comment]
If you like; I've already made the changes around assert.h and math.h but if there are further changes a PR will be very much appreciated!

**Comment by WardF** [comment]
correction: I've made the changes in a local branch and am putting up a PR for travis CI myself.

**Comment by schwehr** [comment]
No more changes on this issue.  Thanks!

**Comment by DennisHeimbigner** [comment]
Interesting; I usually find that the problem is usng <> around netcdf-c related includes.
e.g. finding <netcdf.h> instead of "netcdf.h"
