### ISSUE TITLE
Please re-enable CDF5 by default

### ISSUE THREAD

**Issue by czender** [Unidata/netcdf-c#931]
Now that the CDF5 bug is fixed, please consider turning-on the `--enable-cdf5` option to configure by default. That option was introduced in 4.5.0, and some distros are unaware of its existence, and as a result they ship netCDF with CDF5 disabled, which creates headaches all-around. See #930 for an example of what happened with conda-forge.

**Comment by WardF** [comment]
Easy enough, with the CDF5 issue corrected we can take care of this.
