### ISSUE TITLE
Test run_par_test.sh fails on machines with less than 16 threads

### ISSUE THREAD

**Issue by opoplawski** [Unidata/netcdf-c#932]
### Environment Information

* What platform are you using? (please provide specific distribution/version in summary)
  * [X] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [X] 64-bit
* What build system are you using?
  * [X] autotools (`configure`)
  * [ ] cmake

openmpi 3.0.1

### Summary of Issue
```
Testing simple parallel I/O with 16 processors...
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 16 slots
that were requested by the application:
  ./tst_parallel3

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
FAIL run_par_test.sh (exit status: 1)
```
which then fails the build.  I would suggest checking for the number of available processor threads first.

**Comment by edhartnett** [comment]
When I run with parallel on a machine with only one core, it still creates as many processes as needed to pretend to be as multi-core as the tests require.

So how is it that your system is limited to less that 16 cores?

And do you know of a good way to check that during configure or at run time?

**Comment by opoplawski** [comment]
Also:
```
There are not enough slots available in the system to satisfy the 8 slots
that were requested by the application:
  ./tst_parallel4
```

**Comment by opoplawski** [comment]
oenmpi can take an --oversubscribe option, but not sure how portable that is...

**Comment by opoplawski** [comment]
oenmpi can take an --oversubscribe option, but not sure how portable that is...

**Comment by edhartnett** [comment]
@opoplawski this may be helpful: https://www.open-mpi.org/faq/?category=running#oversubscribing

I should set up an openmpi build on my CI system - then perhaps i would be more sympathetic. ;-) I will give that a try. I withdraw my comment about closing this issue - let's make sure our parallel build and test work on both openmpi and MPICH, since those are the two major MPI libraries out there.

**Comment by WardF** [comment]
We currently test on `openmpi` and `mpich` systems and we do observe the failure discussed here when running the openmpi system.  This can be easily viewed using the following docker command:

    $ docker run --rm -it -e TESTPROC=[processor count] unidata/nctests:openmpi
    $ docker run --rm -it -e TESTPROC=[processor count] unidata/nctests:mpich

**Comment by edhartnett** [comment]
OK, I will take a look...

**Comment by WardF** [comment]
For reference, ‘processor count’ is passed as the argument to `-j`, it doesn’t manipulate how many processors the docker engine will use.

**Comment by opoplawski** [comment]
We now run MPI tests with:
```
export OMPI_MCA_rmaps_base_oversubscribe=1
```
And this does not appear to be a netcdf issue, so feel free to close it.

**Comment by WardF** [comment]
Thanks @opoplawski
