### ISSUE TITLE
CDF5 misinformation...

### ISSUE THREAD

**Issue by dnadeau4** [Unidata/netcdf-c#936]
Your first 4 bytes are now, "C,D,F,5" and when I try to know what has changed I found this awesome web page saying that netCFD-5 is now using the "grib-2" file format or BUFR. 

https://www.unidata.ucar.edu/blogs/developer/entry/netcdf_5_format_to_be

I updated my software quickly and push a new release and finally wanted to read more about this and realized that it was an `April Fool's` day for 2012.   

It would be a good time to remove that page now that "CDF-5" really exist.  😏

**Comment by edwardhartnett** [comment]
I agree. It was funny but now it's just confusing.

@oxelson can we remove the blog post in question? I'm sure John Caron will not mind... ;-)

**Comment by dopplershift** [comment]
It says at the top (now at least):
> NOTE:
This article was published back in 2012 as an April Fool's Day joke. Six years later, folks searching for information about netCDF see the part about version 5 and assume that the article is real, without reading to the end of the post where it says "P.S. April Fools." So here's your warning — this is a joke!

I think we can leave it with just that.

**Comment by edwardhartnett** [comment]
@dopplershift this is not the first time I've encountered this confusion. Does Unidata gain anything from having this article up on the web?

@oxelson it was funny at the time, but not any more. Unidata is not a comedy club and people are not expecting Unidata web documentation to try and be funny.

I'm all for a laugh, but not when it causes confusion and extra work for our users.
