### ISSUE TITLE
check for existence of m4

### ISSUE THREAD

**Issue by nschloe** [Unidata/netcdf-c#94]
A little nitpicking here: The doc build scripts on Linux use `m4`, and the build process fails if it's not available on the system. It should rather be the configuration script that fails though.
A check for the existence of the `m4` executable at configure time would be in order.

**Comment by WardF** [comment]
Thanks for pointing this out; I've added a check in configure.ac, and an explicit exit when it is not found to cmake.  m4 was already being checked for, but no action was taken if it was not found.

**Comment by nschloe** [comment]
How about `CMakeLists.txt`?

**Comment by WardF** [comment]
As mentioned above, m4 was already being checked for, but no action was taken if it was not found. I added an explicit exit if it's not found.
