### ISSUE TITLE
Two questions on user-defined types API

### ISSUE THREAD

**Issue by czender** [Unidata/netcdf-c#948]
1. Why is the class type returned as the last argument of nc_inq_user_type(...,&class_type) of type int, rather than nc_type? Must not all class_type's be an identifier enumerated by nc_type? Or am I missing something? I ask because as NCO moves toward more support for user-defined types, I want to understand the intent of the API.

2. Prior to trying this, I had always thought that netCDF identifier namespaces had no reserved words. But this  

netcdf vlen {
 types:
  int(*) vlen_int;
 variables:
  vlen_int vlen_int;
 data:
  vlen_int={17,18,19};
}

fails with "ncgen: NetCDF: String match to name in use
(genbin.c:125)". So it looks like any vlen type name (e.g.,
"vlen_int")  cannot be a variable name.
Is this intentional? i.e., bug or feature?

**Comment by edhartnett** [comment]
1 - the class_type is not the nc_type. The nc_type is passed in to nc_inq_user_type() as parameter xtype. The class_type tells you what kind of user-defined type is involved. As it says in the docs:

```
\param classp Return the class of the user defined type, ::NC_VLEN,
::NC_OPAQUE, ::NC_ENUM, or ::NC_COMPOUND. \ref ignored_if_null.

```

2. Groups, vars, and types must all have unique names, and that namespace applies to all three at once. So you cannot have a group with the same name as a type or variable.

**Comment by czender** [comment]
1. I understand that class_type differs from the nc_type of a variable. But all class_type's are nonetheless valid nc_types. Hence I do not see the logic of returning an int rather than an nc_type for class_type, and I was wondering if there were some deeper point to returning an int. I guess that choice was made to avoid confusing people which returned parameter contained the nc_type of the variable.

2. I never realized that the "namespace applies to all three at once". I thought groups, variables, and types had their own namespaces. Thanks for pointing this out!
