### ISSUE TITLE
source code contains archive libncdap.tar.gz

### ISSUE THREAD

**Issue by nschloe** [Unidata/netcdf-c#97]
Keeping this data as an archive in the tree hides its contents and doesn't contribute a smaller file size: Releases are zipped anyways, and Git compresses its data, too. (Possibly better than what tar.gz can do.)

Hence the suggestion: Unpack (or remove) the tarball in the sources.

**Comment by WardF** [comment]
Thanks for pointing this out; I'm not going to update the current RC, but I will ensure that it is not included in the final `4.3.3` release. Thanks!
