### ISSUE TITLE
Should szip constants be moved back to netcdf.h?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#973]
At some point long ago, two szip constants were removed from netcdf.h and moved to nc4var.c:

```
#define NC_SZIP_EC_OPTION_MASK 4  /**< @internal SZIP EC option mask. */
#define NC_SZIP_NN_OPTION_MASK 32 /**< @internal SZIP NN option mask. */

```

Now that filters allow the user to set szip for writing, should these two defines be moved back to netcdf.h?

They are required for the user to set the szip filter, as in the following test code:

```
      /* Create a netcdf-4 file with one dimensions. */
      if (nc_create(FILE_NAME, NC_NETCDF4, &ncid)) ERR;
      if (nc_def_dim(ncid, DIM_NAME_1, DIM_LEN_1, &dimid)) ERR;

      /* Add a var. Turn on szip filter. */
      if (nc_def_var(ncid, V_SMALL, NC_INT64, NDIMS1, &dimid, &varid)) ERR;
      params[0] = NC_SZIP_NN_OPTION_MASK;
      params[1] = 32;
      if (nc_def_var_chunking(ncid, varid, NC_CHUNKED, NULL)) ERR;
      if (nc_def_var_filter(ncid, varid, H5_FILTER_SZIP, NUM_PARAMS, params)) ERR;
      if (nc_close(ncid)) ERR;

```

If we all agree that these should be moved, I will put them back in netcdf.h.

**Comment by edhartnett** [comment]
Similarly, should H5_FILTER_SZIP be defined (or get an NC_ named define) in netcdf.h?

**Comment by DennisHeimbigner** [comment]
I say no. My rule is that the only compression that has a privileged status is zip.
All other filters, including szip, are treated the same. If a test uses such a filter,
then the necessary constants should be in the test specifically. 
Note that for historical reasons, szip has its own api code in HDF5, but that
is a holdover from pre- loadable-filters time.

**Comment by edhartnett** [comment]
OK, I will close this ticket.
