### ISSUE TITLE
eliminate unused HDF5_CONVERT and related code in nc4hdf5.c

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#985]
In nc4hdf5.c we have some code like this:

```
#ifndef HDF5_CONVERT
   int need_to_convert = 0;
   size_t len = 1;
#endif
#ifdef HDF5_CONVERT
   hid_t mem_typeid = 0;
#endif

```
This occurs with a lot of code in nc4hdf5.c, but no where else.

The HDF5_CONVERT macro is never set anywhere.

At first I wrote the netccdf-4 code so that HDF5 did data conversions on reads/writes. But it was impossible to get HDF5 to follow the exact rules of netCDF with regard to some of the corner cases. So I re-wrote the netcdf-4 code to convert the data as needed.

The HDF5 team told me they would put in fixes so that HDF5 could correctly handle the corner cases. Then I could remove the conversion code in netCDF-4. But that went the way of most good intentions.

So for all this time, we have been converting the data, and I guess we are going to continue to do so. The HDF5_CONVERT code does not even compile at this point. I will take it all out and clean up the code.

**Comment by DennisHeimbigner** [comment]
I have a vague recollection that this was a Quincy operation. He proposed we use
the HDF5 converters. But it looks like he (or whoever) never completed the conversion.

**Comment by edhartnett** [comment]
Here's a sad little note in the code I am removing:

```
* @note I should be able to take this out when HDF5 does the right thing
 * with data type conversion. Ed Hartnett, 11/15/3

```

15 years ago! What an optimistic young programmer I was.
