### ISSUE TITLE
We should not use MPI_COMM_WORLD as a default in parallel code

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#989]
I may have started this when I first wrote the parallel I/O code, but sometimes in the code we default to MPI_COMM_WORLD. For example:

```
int
NC4_open(const char *path, int mode, int basepe, size_t *chunksizehintp,
         int use_parallel, void *parameters, NC_Dispatch *dispatch, NC *nc_file)
{
   int res;
#ifdef USE_PARALLEL4
   NC_MPI_INFO mpidfalt = {MPI_COMM_WORLD, MPI_INFO_NULL};
#endif
#if defined USE_PARALLEL4
   int inmemory = ((mode & NC_INMEMORY) == NC_INMEMORY);
#endif

   assert(nc_file && path);

   LOG((1, "%s: path %s mode %d params %x",
        __func__, path, mode, parameters));

#ifdef USE_PARALLEL4
   if (!inmemory && use_parallel && parameters == NULL)
      parameters = &mpidfalt;
#endif /* USE_PARALLEL4 */
```

This is not a correct thing to do. It's likely to work in all our tests and toy cases, but cause a  hang in a real-world HPC system.

When a user is using parallel I/O, they simply must pass in an MPI communicator. This will not be a problem, as they must have a communicator, and all MPI programmers already understand that they must provide a communicator to open/create a disk file.

**Comment by DennisHeimbigner** [comment]
There will be back compatibility issues if we start requiring a communicator?

**Comment by DennisHeimbigner** [comment]
Did all of our existing tests specify a communicator?

**Comment by edhartnett** [comment]
Yes.

Furthermore, the point is moot. There is no way to have use_parallel set, without a communicator and info being passed, so these defaults can never be used anyway.

The only way to set use_parallel is via nc_create_par/nc_open_par, and these functions both explicitly copy the comm/info provided in the parameters. It's not a pointer, so it can't be null.

**Comment by DennisHeimbigner** [comment]
ok. That seems definitive.

**Comment by edhartnett** [comment]
PR up shortly.
