### ISSUE TITLE
NC4_isnetcdf4() should not walk the file

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#991]
We have:

```
/**
 * @internal Determine whether file is netCDF-4.
 *
 * We define a file as being from netcdf-4 if any of the following
 * are true:
 * 1. NCPROPS attribute exists in root group
 * 2. NC3_STRICT_ATT_NAME exists in root group
 * 3. any of NC_ATT_REFERENCE_LIST, NC_ATT_CLASS,
 * NC_ATT_DIMENSION_LIST, NC_ATT_NAME,
 * NC_ATT_COORDINATES, NC_DIMID_ATT_NAME
 * exist anywhere in the file; note that this
 * requires walking the file.
```

It's hard for me to tell when this function is called, but seemingly it will be called for every non-netcdf-4 HDF5 file, and any older netcdf-4 file without a NCPROPS special property attribute.

In these cases we will be walking the file twice. HDF5 is super slow at walking though all the attributes in the file.

I am trying to figure out from the code what the consequences are of not being found to be a netcdf-4 file, but I haven't quite sorted out what is going on.

**Comment by DennisHeimbigner** [comment]
This should only be called if the _IsNetcdf4 attribute is accessed.

**Comment by edhartnett** [comment]
OK, so this is not run unless the user specifically tries to get the _IsNetcdf4 attribute? Awesome. I will close this ticket.
